#!/bin/sh
set -eu

crate_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_dir=$(CDPATH= cd -- "$crate_dir/../.." && pwd)
formal_dir="$repo_dir/formal/dclutch-semantics"
accepted="$crate_dir/src/generated.rs"
temporary=$(mktemp "${TMPDIR:-/tmp}/dclutch-liability-basis-v2.XXXXXX")
trap 'rm -f "$temporary"' EXIT HUP INT TERM

(
  cd "$formal_dir"
  lake build DClutchSemantics.LiabilityBasisV2
  lake env lean --run EmitLiabilityBasisV2Rust.lean > "$temporary"
)

expected_header='// @generated by formal/dclutch-semantics/EmitLiabilityBasisV2Rust.lean; do not edit.'
test "$(sed -n '1p' "$temporary")" = "$expected_header"
test "$(sed -n '2p' "$temporary")" = 'use super::{AgreementCaseV2, RefusalCaseV2, TransitionCaseV2};'
# 549, moved from 548 at d0c0990fc and NOT moved with it. That commit split the
# one request magic out under its canonical name and aliased the old one to it
# -- BASIS_REQUEST_MAGIC_V2, plus RAMP_MAGIC_V2 as an alias, where there had
# been one line -- so the re-emission was correct and this pin was the only
# thing that noticed it, which is what the pin is for. It fired, red, on
# 2026-09-02, and nothing ran this script for two days.
test "$(wc -l < "$temporary" | tr -d ' ')" -eq 549
# The magic the ramp and the spline now SHARE rather than each declaring: the
# reviewed content of that same move, pinned here so a silent un-sharing is a
# red line rather than a quiet second authority.
grep -q '^pub const BASIS_REQUEST_MAGIC_V2: \[u8; 8\] = \[0x44, 0x43, 0x4c, 0x54, 0x4c, 0x42, 0x56, 0x32\];$' "$temporary"
grep -q '^pub const RAMP_MAGIC_V2: \[u8; 8\] = BASIS_REQUEST_MAGIC_V2;$' "$temporary"
grep -q '^pub const AGREEMENT_CASES_V2: \[AgreementCaseV2; 16\] = \[$' "$temporary"
grep -q '^pub const REFUSAL_CASES_V2: \[RefusalCaseV2; 19\] = \[$' "$temporary"
grep -q '^pub const TRANSITION_CASES_V2: \[TransitionCaseV2; 24\] = \[$' "$temporary"
cmp "$temporary" "$accepted"
