//! Source-bound finite comparisons for the Series Consume shadow evaluator.
//!
//! Direct's `DCLTTRV1` evidence names different executors and cannot authorize
//! a Series certificate. This manifest binds a Series corpus, every observed
//! comparison, the validator, the complete compiler source inventory, and the
//! toolchain. It records finite agreement, not universal refinement or SBF
//! execution. The runtime campaign supplies that separate evidence.

use std::collections::BTreeSet;

use dclutch_core_contract::ContentId;
use serde_json::Value;

use crate::{Error, Result, sha256};

/// Canonical Series comparison manifest magic, distinct from Direct's schema.
pub const CHECKED_SERIES_TRANSLATION_MAGIC_V1: [u8; 8] = *b"DCLTSV01";
/// Number and order of source/evidence inputs hashed by this manifest.
pub const CHECKED_SERIES_TRANSLATION_LABELS_V1: [&str; 8] = [
    "semantic_source",
    "compiler_source_manifest",
    "toolchain_manifest",
    "corpus",
    "validator_source",
    "validator_result",
    "rustc_verbose",
    "cargo_lock",
];
/// Exact canonical encoded width.
pub const CHECKED_SERIES_TRANSLATION_BYTES_V1: usize =
    16 + 32 * CHECKED_SERIES_TRANSLATION_LABELS_V1.len();

/// Exact inputs from one completed Series Consume comparison run.
#[derive(Clone, Copy)]
pub struct SeriesTranslationEvidenceV1<'a> {
    /// Exact Consume semantic source selected by the compiler.
    pub semantic_source: &'a [u8],
    /// Complete source inventory of the compiler, native owners and executors.
    pub compiler_source_manifest: &'a [u8],
    /// Exact toolchain/build provenance used by the comparison.
    pub toolchain_manifest: &'a [u8],
    /// Ordered case identities and input digests, schema `dclutch-series-consume-corpus-v1`.
    pub corpus: &'a [u8],
    /// Comparison driver source; its dependency closure is in the source inventory.
    pub validator_source: &'a [u8],
    /// All native/interpreted/shadow observations, schema `dclutch-series-consume-result-v1`.
    pub validator_result: &'a [u8],
    /// Exact `rustc -Vv` output.
    pub rustc_verbose: &'a [u8],
    /// Root workspace Cargo lock used by the comparison.
    pub cargo_lock: &'a [u8],
}

impl<'a> SeriesTranslationEvidenceV1<'a> {
    fn ordered(self) -> [&'a [u8]; 8] {
        [
            self.semantic_source,
            self.compiler_source_manifest,
            self.toolchain_manifest,
            self.corpus,
            self.validator_source,
            self.validator_result,
            self.rustc_verbose,
            self.cargo_lock,
        ]
    }

    fn validate(self) -> Result<()> {
        if self.ordered().iter().any(|bytes| bytes.is_empty())
            || !self.rustc_verbose.starts_with(b"rustc ")
            || !self.rustc_verbose.ends_with(b"\n")
            || !self
                .cargo_lock
                .starts_with(b"# This file is automatically @generated by Cargo.")
        {
            return Err(Error::InvalidTranslationValidation);
        }
        let corpus = canonical_json(self.corpus)?;
        let result = canonical_json(self.validator_result)?;
        let inputs = cases(&corpus, "dclutch-series-consume-corpus-v1")?;
        let outputs = cases(&result, "dclutch-series-consume-result-v1")?;
        if inputs.is_empty() || inputs.len() != outputs.len() {
            return Err(Error::InvalidTranslationValidation);
        }
        let mut names = BTreeSet::new();
        let mut accepted = false;
        let mut refused = false;
        for (input, output) in inputs.iter().zip(outputs) {
            exact_keys(input, &["case", "input_sha256"])?;
            exact_keys(
                output,
                &[
                    "case",
                    "input_sha256",
                    "outcome",
                    "native_projection_sha256",
                    "interpreted_projection_sha256",
                    "shadow_projection_sha256",
                ],
            )?;
            let name = input["case"]
                .as_str()
                .ok_or(Error::InvalidTranslationValidation)?;
            if name.is_empty()
                || !name.is_ascii()
                || !names.insert(name)
                || output["case"].as_str() != Some(name)
                || input["input_sha256"] != output["input_sha256"]
            {
                return Err(Error::InvalidTranslationValidation);
            }
            digest_text(&input["input_sha256"])?;
            let native = digest_text(&output["native_projection_sha256"])?;
            if native != digest_text(&output["interpreted_projection_sha256"])?
                || native != digest_text(&output["shadow_projection_sha256"])?
            {
                return Err(Error::CheckedTranslationValidationMismatch);
            }
            match output["outcome"].as_str() {
                Some("accepted") => accepted = true,
                Some("refused") => refused = true,
                _ => return Err(Error::InvalidTranslationValidation),
            }
        }
        // A refusal-only run does not demonstrate that an admitted route can
        // finish; an accepted-only run does not compare its refusal boundary.
        if !accepted || !refused {
            return Err(Error::InvalidTranslationValidation);
        }
        Ok(())
    }
}

// Compact, sorted-key serde_json encoding, with one optional final newline.
// Re-encoding refuses duplicate object keys and alternative textual encodings
// before the document can become a canonical evidence identity.
fn canonical_json(bytes: &[u8]) -> Result<Value> {
    let bytes = bytes.strip_suffix(b"\n").unwrap_or(bytes);
    let value: Value =
        serde_json::from_slice(bytes).map_err(|_| Error::InvalidTranslationValidation)?;
    if serde_json::to_vec(&value).map_err(|_| Error::InvalidTranslationValidation)? != bytes {
        return Err(Error::InvalidTranslationValidation);
    }
    Ok(value)
}

fn exact_keys(value: &Value, keys: &[&str]) -> Result<()> {
    let object = value
        .as_object()
        .ok_or(Error::InvalidTranslationValidation)?;
    if object.len() != keys.len() || keys.iter().any(|key| !object.contains_key(*key)) {
        return Err(Error::InvalidTranslationValidation);
    }
    Ok(())
}

fn cases<'a>(value: &'a Value, schema: &str) -> Result<&'a Vec<Value>> {
    exact_keys(value, &["schema", "cases"])?;
    if value["schema"].as_str() != Some(schema) {
        return Err(Error::InvalidTranslationValidation);
    }
    value["cases"]
        .as_array()
        .ok_or(Error::InvalidTranslationValidation)
}

fn digest_text(value: &Value) -> Result<&str> {
    let text = value.as_str().ok_or(Error::InvalidTranslationValidation)?;
    if text.len() != 64
        || text.bytes().all(|byte| byte == b'0')
        || !text
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
    {
        return Err(Error::InvalidTranslationValidation);
    }
    Ok(text)
}

/// Canonical digest manifest of one source-bound finite Series comparison.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CheckedSeriesTranslationV1 {
    digests: [[u8; 32]; 8],
}

impl CheckedSeriesTranslationV1 {
    /// Construct only after every corpus row has a matching comparison outcome.
    pub fn build(evidence: SeriesTranslationEvidenceV1<'_>) -> Result<Self> {
        evidence.validate()?;
        let mut digests = [[0; 32]; 8];
        for (digest, bytes) in digests.iter_mut().zip(evidence.ordered()) {
            *digest = sha256(bytes);
        }
        Self::decode(&Self { digests }.encode())
    }

    /// Hostile-decode the exact Series schema; a Direct manifest is refused.
    pub fn decode(bytes: &[u8]) -> Result<Self> {
        if bytes.len() != CHECKED_SERIES_TRANSLATION_BYTES_V1 {
            return Err(Error::InvalidLength);
        }
        if bytes[..8] != CHECKED_SERIES_TRANSLATION_MAGIC_V1 {
            return Err(Error::InvalidMagic);
        }
        if bytes[8..16] != [1, 0, 8, 0, 0, 0, 0, 0] {
            return Err(Error::InvalidTranslationValidation);
        }
        let mut digests = [[0; 32]; 8];
        for (digest, encoded) in digests.iter_mut().zip(bytes[16..].chunks_exact(32)) {
            digest.copy_from_slice(encoded);
            if *digest == [0; 32] {
                return Err(Error::ZeroIdentifier);
            }
        }
        Ok(Self { digests })
    }

    /// Encode the one fixed representation.
    pub fn encode(self) -> [u8; CHECKED_SERIES_TRANSLATION_BYTES_V1] {
        let mut bytes = [0; CHECKED_SERIES_TRANSLATION_BYTES_V1];
        bytes[..8].copy_from_slice(&CHECKED_SERIES_TRANSLATION_MAGIC_V1);
        bytes[8..16].copy_from_slice(&[1, 0, 8, 0, 0, 0, 0, 0]);
        for (encoded, digest) in bytes[16..].chunks_exact_mut(32).zip(self.digests) {
            encoded.copy_from_slice(&digest);
        }
        bytes
    }

    /// Require the certificate's actual semantic, compiler and toolchain inputs.
    pub fn require_sources(self, semantic: &[u8], compiler: &[u8], toolchain: &[u8]) -> Result<()> {
        if [sha256(semantic), sha256(compiler), sha256(toolchain)] != self.digests[..3] {
            return Err(Error::CheckedTranslationValidationMismatch);
        }
        Ok(())
    }

    /// Verify every original evidence byte against this manifest.
    pub fn verify(self, evidence: SeriesTranslationEvidenceV1<'_>) -> Result<()> {
        if Self::build(evidence)? != self {
            return Err(Error::CheckedTranslationValidationMismatch);
        }
        Ok(())
    }

    /// Content identity for the Series certificate's translation-validation field.
    pub fn translation_validation_id(self) -> Result<ContentId> {
        ContentId::new(sha256(&self.encode())).map_err(|_| Error::ZeroIdentifier)
    }
}

#[cfg(test)]
#[path = "series_translation_tests.rs"]
mod tests;
