// @generated by formal/dclutch-semantics/EmitSourceWindowSpecV1Rust.lean; do not edit.
/// Canonical window-specification magic: `DCLTWIN1`.
pub const WINDOW_SPEC_MAGIC: [u8; 8] = [0x44, 0x43, 0x4c, 0x54, 0x57, 0x49, 0x4e, 0x31];
/// Exact width of a window-specification preimage.
pub const WINDOW_SPEC_BYTES: usize = 112;
/// Exact magic width, so a prefix check stops borrowing the version's coordinate.
pub const WINDOW_SPEC_MAGIC_BYTES_V1: usize = 8;
/// Canonical-zero span between the kind tag and the source identity.
pub const WINDOW_SPEC_HEADER_RESERVED_BYTES_V1: usize = 5;
/// Canonical window-specification magic.
pub const WINDOW_SPEC_MAGIC_OFFSET_V1: usize = 0;
/// Crate-wide `SCHEMA_VERSION`, at this record's coordinate.
pub const WINDOW_SPEC_SCHEMA_VERSION_OFFSET_V1: usize = 8;
/// Window kind tag.
pub const WINDOW_SPEC_KIND_OFFSET_V1: usize = 10;
/// Canonical-zero span between the kind tag and the identity.
pub const WINDOW_SPEC_HEADER_RESERVED_OFFSET_V1: usize = 11;
/// Identity of the source specification the window reads.
pub const WINDOW_SPEC_SOURCE_SPEC_ID_OFFSET_V1: usize = 16;
/// Closed lower time bound of the window.
pub const WINDOW_SPEC_START_UNIX_SECONDS_OFFSET_V1: usize = 48;
/// Closed upper time bound of the window.
pub const WINDOW_SPEC_END_UNIX_SECONDS_OFFSET_V1: usize = 56;
/// Maximum admissible sample staleness.
pub const WINDOW_SPEC_MAX_AGE_SECONDS_OFFSET_V1: usize = 64;
/// Maximum admissible sample skew into the future.
pub const WINDOW_SPEC_MAX_FUTURE_SKEW_SECONDS_OFFSET_V1: usize = 68;
/// Identity of the schedule the samples must land on.
pub const WINDOW_SPEC_SCHEDULE_ID_OFFSET_V1: usize = 72;
