//! Exact comparison against one embedded Series artifact bundle.

use alloc::{vec, vec::Vec};

use dclutch_account_profile_contract::{
    AccountObservationV1,
    v2::{
        AccountProfileV2, ProjectionRegistersV2, derive_effect_permissions_with_dynamic_spans,
        project_dynamic_fixed_spans_atomic,
    },
};
use dclutch_capability_program_contract::v4::CapabilityProgramV4;
use dclutch_core_contract::ContentId;
use dclutch_effect_kernel::{
    v2::{AccountInput, AccountPermission, FixedRole},
    v3::{
        ProjectionV3, ResolvedReceiptDependenciesV3, RouteKindV3,
        project_atomic as project_effect_atomic,
    },
    v4::ProgramV4 as EffectProgramV4,
};
use dclutch_execution_strategy_contract::{
    shadow_digest_v3::{
        ShadowEffectProjectionV3, ShadowReceiptDependencyV3, ShadowResolvedRouteV3,
        ShadowRouteKindV3, ShadowRouteRoleV3, ShadowRuntimeObservationV3, candidate_digest_v3,
        effect_digest_v3, family_request_digest_v3, receipt_dependencies_digest_v4,
        runtime_observations_digest_v3,
    },
    shadow_v3::{ShadowAckV3, ShadowArtifactTupleV3, ShadowRequestV3},
    v2::{AcceleratorTransportProfileV2, ExecutionStrategyProgramV2, StrategyDispositionV2},
};
use dclutch_market_core_codec::SERIES_CORE_REQUEST_BYTES_V1;
use dclutch_request_profile_contract::{
    ProjectionRegistersV1, RequestProfileV1, project_atomic as project_request_atomic,
};
use dclutch_series_v3_kernel::{
    AccountKeyV3, AuthenticatedProductProjectionV2,
    request::SeriesActionV3,
    shadow::{SeriesShadowInputV3, SeriesShadowObservationsV3, evaluate_series_shadow_v3},
    template_content_id,
};
use dclutch_transition_vm::v3::{
    ProgramV3 as TransitionProgramV3, RegisterInput, RegisterOutput, execute_fold_atomic,
};
use sha2::{Digest, Sha256};

/// Exact fixed scalar width of the Series Consume artifact family.
pub const SERIES_SHADOW_SCALAR_COUNT_V4: usize = 5;
/// Exact fixed identity width of the Series Consume artifact family.
pub const SERIES_SHADOW_IDENTITY_COUNT_V4: usize = 1;
/// Fixed logical account width before the ordered FundingState span.
pub const SERIES_SHADOW_LOGICAL_ACCOUNT_BASE_V4: usize = 157;
/// Minimum and maximum admitted ordered FundingState count.
pub const SERIES_SHADOW_MINIMUM_FUNDING_COUNT_V4: usize = 1;
/// Maximum admitted ordered FundingState count.
pub const SERIES_SHADOW_MAXIMUM_FUNDING_COUNT_V4: usize = 16;
/// Common scalar containing the bounded FundingState count.
pub const SERIES_SHADOW_FUNDING_COUNT_SCALAR_V4: usize = 4;

const SERIES_ROOT_COORDINATE_V4: usize = 0;
const SERIES_CONFIG_COORDINATE_V4: usize = 1;
const SERIES_PRODUCT_COORDINATE_V4: usize = 2;
const SERIES_REGISTRY_COORDINATE_V4: usize = 8;
const SERIES_TRADING_COORDINATE_V4: usize = 9;
const SERIES_MARKET_COORDINATE_V4: usize = 18;
const SERIES_TICKET_STATE_COORDINATE_V4: usize = 53;
const SERIES_TEMPLATE_RAW_COORDINATE_V4: usize = 54;
const SERIES_OCCURRENCE_RAW_COORDINATE_V4: usize = 56;
const SERIES_TICKET_RAW_COORDINATE_V4: usize = 58;
const SERIES_CLOCK_COORDINATE_V4: usize = 60;
const SERIES_CORE_FOUND_ROUTE_V4: usize = 1;
const SERIES_CORE_OPEN_ROUTE_V4: usize = 4;

/// One compile-time-selected artifact bundle.
///
/// Production passes one `static` value generated by the canonical artifact
/// compiler. The acknowledgement binds its content tuple, never these slices
/// by address or by caller assertion.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct EmbeddedSeriesShadowBundleV4<'a> {
    /// Exact selected CapabilityProgramV4 bytes.
    pub capability_program: &'a [u8],
    /// Exact Profile13 bytes.
    pub account_profile: &'a [u8],
    /// Exact fixed-header RequestProfile bytes.
    pub request_profile: &'a [u8],
    /// Exact TransitionVM V3 bytes.
    pub transition: &'a [u8],
    /// Exact global DCE5 Effect bytes.
    pub effect: &'a [u8],
    /// Exact Shadow-AOT ExecutionStrategy bytes.
    pub strategy: &'a [u8],
    /// Exact translation-certificate content identity bound to this ELF.
    pub certificate: ContentId,
}

/// Adapter-authenticated facts that are not parallel persisted records.
///
/// The Product projection is the output of the canonical Product Runtime
/// graph reader. `now_slot` is accepted only when it equals the Clock bytes in
/// the authenticated AccountProfile vector.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SeriesShadowAuthenticatedFactsV4 {
    /// Canonical Product Runtime graph projection.
    pub product: AuthenticatedProductProjectionV2,
    /// Current slot authenticated from the canonical Clock sysvar.
    pub now_slot: u64,
}

/// Independently observed input for one stateless comparison.
pub struct SeriesShadowEvaluationV4<'a> {
    /// Complete generic Shadow V3 request bytes from Trading.
    pub shadow_request: &'a [u8],
    /// Compile-time-selected artifact bundle.
    pub bundle: EmbeddedSeriesShadowBundleV4<'a>,
    /// AccountProfile logical observations with descriptor-derived privileges.
    pub profile_observations: &'a [AccountObservationV1<'a>],
    /// The same account facts normalized to the read-only Shadow transcript.
    pub transcript_observations: &'a [ShadowRuntimeObservationV3<'a>],
    /// Adapter-authenticated Product and Clock facts.
    pub authenticated_facts: SeriesShadowAuthenticatedFactsV4,
}

/// Stable refusal from independent Series Shadow evaluation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SeriesShadowAotErrorV4 {
    /// Generic Shadow request hostile decoding refused.
    ShadowRequest,
    /// Embedded descriptor, strategy, or content tuple differed.
    Artifact,
    /// Runtime dimensions, facts, or normalized transcript differed.
    Runtime,
    /// AccountProfile projection refused.
    AccountProfile,
    /// RequestProfile projection refused.
    RequestProfile,
    /// Transition execution refused.
    Transition,
    /// Series content, proof, replay, schedule, or effect semantics refused.
    Semantic,
    /// Effect projection or resolved route transcript refused.
    Effect,
    /// Recomputed family, runtime, candidate, or effect digest differed.
    Digest,
}

/// Result alias for Series Shadow-AOT evaluation.
pub type Result<T> = core::result::Result<T, SeriesShadowAotErrorV4>;

/// Independently reexecute one exact embedded Series artifact bundle.
///
/// Success returns only a typed acknowledgement. It grants no account write,
/// CPI, signer, replay, or commit authority.
pub fn evaluate_series_shadow_aot_v4(input: SeriesShadowEvaluationV4<'_>) -> Result<ShadowAckV3> {
    let shadow = ShadowRequestV3::decode(input.shadow_request)
        .map_err(|_| SeriesShadowAotErrorV4::ShadowRequest)?;
    let (descriptor, strategy) = authenticate_embedded_bundle(input.bundle, shadow.artifacts)?;
    if strategy.disposition() != StrategyDispositionV2::ShadowAot
        || strategy.transport_profile() != Ok(AcceleratorTransportProfileV2::ShadowTranscriptV3)
        || strategy.transition_program() != descriptor.transition().program()
    {
        return Err(SeriesShadowAotErrorV4::Artifact);
    }
    let funding_count = funding_count(shadow)?;
    let profile = AccountProfileV2::decode(input.bundle.account_profile)
        .map_err(|_| SeriesShadowAotErrorV4::AccountProfile)?;
    require_runtime_agreement(
        profile,
        shadow,
        funding_count,
        input.profile_observations,
        input.transcript_observations,
    )?;
    let mut account_scratch_scalars = [0_u64; SERIES_SHADOW_SCALAR_COUNT_V4];
    let mut account_output_scalars = [0_u64; SERIES_SHADOW_SCALAR_COUNT_V4];
    let mut account_scratch_identities = [[0_u8; 32]; SERIES_SHADOW_IDENTITY_COUNT_V4];
    let mut account_output_identities = [[0_u8; 32]; SERIES_SHADOW_IDENTITY_COUNT_V4];
    let mut account_input_scalars = [0_u64; SERIES_SHADOW_SCALAR_COUNT_V4];
    account_input_scalars[SERIES_SHADOW_FUNDING_COUNT_SCALAR_V4] =
        u64::try_from(funding_count).map_err(|_| SeriesShadowAotErrorV4::Runtime)?;
    let account_input_identities = [shadow.trading_program.to_bytes()];
    project_dynamic_fixed_spans_atomic(
        profile,
        shadow.shape.tail_count,
        &[u32::try_from(funding_count).map_err(|_| SeriesShadowAotErrorV4::Runtime)?],
        input.profile_observations,
        ProjectionRegistersV2 {
            input_scalars: &account_input_scalars,
            input_identities: &account_input_identities,
            scratch_scalars: &mut account_scratch_scalars,
            scratch_identities: &mut account_scratch_identities,
            output_scalars: &mut account_output_scalars,
            output_identities: &mut account_output_identities,
        },
    )
    .map_err(|_| SeriesShadowAotErrorV4::AccountProfile)?;

    let request_profile = RequestProfileV1::decode(input.bundle.request_profile)
        .map_err(|_| SeriesShadowAotErrorV4::RequestProfile)?;
    let family_header = shadow
        .family_request
        .get(..128)
        .ok_or(SeriesShadowAotErrorV4::ShadowRequest)?;
    let mut request_scratch_scalars = [0_u64; SERIES_SHADOW_SCALAR_COUNT_V4];
    let mut request_output_scalars = [0_u64; SERIES_SHADOW_SCALAR_COUNT_V4];
    let mut request_scratch_identities = [[0_u8; 32]; SERIES_SHADOW_IDENTITY_COUNT_V4];
    let mut request_output_identities = [[0_u8; 32]; SERIES_SHADOW_IDENTITY_COUNT_V4];
    project_request_atomic(
        request_profile,
        0,
        family_header,
        ProjectionRegistersV1 {
            input_scalars: &account_output_scalars,
            input_identities: &account_output_identities,
            scratch_scalars: &mut request_scratch_scalars,
            scratch_identities: &mut request_scratch_identities,
            output_scalars: &mut request_output_scalars,
            output_identities: &mut request_output_identities,
        },
    )
    .map_err(|_| SeriesShadowAotErrorV4::RequestProfile)?;

    let transition = TransitionProgramV3::decode(input.bundle.transition)
        .map_err(|_| SeriesShadowAotErrorV4::Transition)?;
    let mut transition_scratch_scalars = [0_u64; SERIES_SHADOW_SCALAR_COUNT_V4];
    let mut candidate_scalars = [0_u64; SERIES_SHADOW_SCALAR_COUNT_V4];
    let mut transition_scratch_identities = [[0_u8; 32]; SERIES_SHADOW_IDENTITY_COUNT_V4];
    let mut candidate_identities = [[0_u8; 32]; SERIES_SHADOW_IDENTITY_COUNT_V4];
    execute_fold_atomic(
        transition,
        0,
        RegisterInput {
            scalars: &request_output_scalars,
            identities: &request_output_identities,
        },
        RegisterOutput {
            scalars: &mut transition_scratch_scalars,
            identities: &mut transition_scratch_identities,
        },
        RegisterOutput {
            scalars: &mut candidate_scalars,
            identities: &mut candidate_identities,
        },
    )
    .map_err(|_| SeriesShadowAotErrorV4::Transition)?;

    let expected_core = evaluate_semantic_core_request(
        shadow,
        input.profile_observations,
        input.authenticated_facts,
    )?;
    let (output_lamports, request_bank, routes) = project_effect(
        profile,
        input.bundle.effect,
        shadow,
        funding_count,
        input.profile_observations,
        &candidate_scalars,
        &candidate_identities,
    )?;
    require_core_request_equivalence(&request_bank, &routes, &expected_core)?;

    let family_digest = family_request_digest_v3(shadow.family_request)
        .map_err(|_| SeriesShadowAotErrorV4::Digest)?;
    let runtime_digest = runtime_observations_digest_v3(input.transcript_observations)
        .map_err(|_| SeriesShadowAotErrorV4::Digest)?;
    let candidate_digest = candidate_digest_v3(
        shadow.shape.tail_count,
        &candidate_scalars,
        &candidate_identities,
    )
    .map_err(|_| SeriesShadowAotErrorV4::Digest)?;
    let projected_effect_digest = effect_digest_v3(ShadowEffectProjectionV3 {
        tail_count: shadow.shape.tail_count,
        output_lamports: &output_lamports,
        request_bank: &request_bank,
        routes: &routes,
    })
    .map_err(|_| SeriesShadowAotErrorV4::Digest)?;
    if shadow.digests.family_request != family_digest
        || shadow.digests.runtime_observations != runtime_digest
        || shadow.digests.interpreted_candidate != candidate_digest
        || shadow.digests.interpreted_effect != projected_effect_digest
    {
        return Err(SeriesShadowAotErrorV4::Digest);
    }
    let request_digest = content(input.shadow_request)?;
    Ok(ShadowAckV3::accepted(shadow, request_digest))
}

fn evaluate_semantic_core_request(
    shadow: ShadowRequestV3<'_>,
    observations: &[AccountObservationV1<'_>],
    facts: SeriesShadowAuthenticatedFactsV4,
) -> Result<[u8; SERIES_CORE_REQUEST_BYTES_V1]> {
    let root = observation(observations, SERIES_ROOT_COORDINATE_V4)?;
    let config = observation(observations, SERIES_CONFIG_COORDINATE_V4)?;
    let product = observation(observations, SERIES_PRODUCT_COORDINATE_V4)?;
    let registry = observation(observations, SERIES_REGISTRY_COORDINATE_V4)?;
    let trading = observation(observations, SERIES_TRADING_COORDINATE_V4)?;
    let market = observation(observations, SERIES_MARKET_COORDINATE_V4)?;
    let ticket_state = observation(observations, SERIES_TICKET_STATE_COORDINATE_V4)?;
    let template = observation(observations, SERIES_TEMPLATE_RAW_COORDINATE_V4)?;
    let occurrence = observation(observations, SERIES_OCCURRENCE_RAW_COORDINATE_V4)?;
    let ticket = observation(observations, SERIES_TICKET_RAW_COORDINATE_V4)?;
    let clock = observation(observations, SERIES_CLOCK_COORDINATE_V4)?;
    let template_id =
        template_content_id(template.data()).map_err(|_| SeriesShadowAotErrorV4::Semantic)?;
    let now_slot = clock
        .data()
        .get(..8)
        .and_then(|bytes| bytes.try_into().ok())
        .map(u64::from_le_bytes)
        .ok_or(SeriesShadowAotErrorV4::Runtime)?;
    if root.key() != shadow.root.to_bytes()
        || config.key() != template_id.to_bytes()
        || product.key() != facts.product.product_record().to_bytes()
        || registry.key() != shadow.registry_program.to_bytes()
        || trading.key() != shadow.trading_program.to_bytes()
        || market.key() != shadow.market.to_bytes()
        || now_slot != facts.now_slot
    {
        return Err(SeriesShadowAotErrorV4::Runtime);
    }
    let registry_program = AccountKeyV3::new(shadow.registry_program.to_bytes())
        .map_err(|_| SeriesShadowAotErrorV4::Runtime)?;
    let ticket_state_account =
        AccountKeyV3::new(ticket_state.key()).map_err(|_| SeriesShadowAotErrorV4::Runtime)?;
    let semantic_input = SeriesShadowInputV3 {
        family_request: shadow.family_request,
        template: template.data(),
        occurrence: Some(occurrence.data()),
        ticket: Some(ticket.data()),
        series_state: root.data(),
        ticket_state: Some(ticket_state.data()),
        observations: SeriesShadowObservationsV3 {
            product: Some(facts.product),
            registry_program: Some(registry_program),
            ticket_state_account: Some(ticket_state_account),
            now_slot,
        },
    };
    let plan =
        evaluate_series_shadow_v3(&semantic_input).map_err(|_| SeriesShadowAotErrorV4::Semantic)?;
    if plan.action() != SeriesActionV3::Consume {
        return Err(SeriesShadowAotErrorV4::Semantic);
    }
    plan.effects()
        .core()
        .ok_or(SeriesShadowAotErrorV4::Semantic)?
        .encode()
        .map_err(|_| SeriesShadowAotErrorV4::Semantic)
}

fn observation<'a>(
    observations: &'a [AccountObservationV1<'a>],
    coordinate: usize,
) -> Result<AccountObservationV1<'a>> {
    observations
        .get(coordinate)
        .copied()
        .ok_or(SeriesShadowAotErrorV4::Runtime)
}

fn require_core_request_equivalence(
    request_bank: &[u8],
    routes: &[ShadowResolvedRouteV3],
    expected: &[u8; SERIES_CORE_REQUEST_BYTES_V1],
) -> Result<()> {
    for route in [SERIES_CORE_FOUND_ROUTE_V4, SERIES_CORE_OPEN_ROUTE_V4] {
        let resolved = routes.get(route).ok_or(SeriesShadowAotErrorV4::Effect)?;
        let start =
            usize::try_from(resolved.request_offset).map_err(|_| SeriesShadowAotErrorV4::Effect)?;
        let len =
            usize::try_from(resolved.request_len).map_err(|_| SeriesShadowAotErrorV4::Effect)?;
        let end = start
            .checked_add(len)
            .ok_or(SeriesShadowAotErrorV4::Effect)?;
        if len != SERIES_CORE_REQUEST_BYTES_V1
            || request_bank.get(start..end) != Some(expected.as_slice())
        {
            return Err(SeriesShadowAotErrorV4::Semantic);
        }
    }
    Ok(())
}

fn authenticate_embedded_bundle(
    bundle: EmbeddedSeriesShadowBundleV4<'_>,
    expected: ShadowArtifactTupleV3,
) -> Result<(CapabilityProgramV4, ExecutionStrategyProgramV2)> {
    let descriptor = CapabilityProgramV4::decode(bundle.capability_program)
        .map_err(|_| SeriesShadowAotErrorV4::Artifact)?;
    let strategy = ExecutionStrategyProgramV2::decode(bundle.strategy)
        .map_err(|_| SeriesShadowAotErrorV4::Artifact)?;
    let actual = ShadowArtifactTupleV3 {
        capability_program: content(bundle.capability_program)?,
        account_profile: content(bundle.account_profile)?,
        request_profile: content(bundle.request_profile)?,
        transition: content(bundle.transition)?,
        effect: content(bundle.effect)?,
        strategy: content(bundle.strategy)?,
        certificate: bundle.certificate,
    };
    if actual != expected
        || descriptor.account_profile().program() != actual.account_profile
        || descriptor.request_profile().program() != actual.request_profile
        || descriptor.transition().program() != actual.transition
        || descriptor.effect().program() != actual.effect
        || descriptor.strategy().program() != actual.strategy
        || strategy.certificate_program() != Some(actual.certificate)
    {
        return Err(SeriesShadowAotErrorV4::Artifact);
    }
    Ok((descriptor, strategy))
}

fn funding_count(request: ShadowRequestV3<'_>) -> Result<usize> {
    let account_count = usize::try_from(request.shape.account_count)
        .map_err(|_| SeriesShadowAotErrorV4::Runtime)?;
    let funding = account_count
        .checked_sub(SERIES_SHADOW_LOGICAL_ACCOUNT_BASE_V4)
        .ok_or(SeriesShadowAotErrorV4::Runtime)?;
    if !(SERIES_SHADOW_MINIMUM_FUNDING_COUNT_V4..=SERIES_SHADOW_MAXIMUM_FUNDING_COUNT_V4)
        .contains(&funding)
        || request.shape.scalar_count
            != u32::try_from(SERIES_SHADOW_SCALAR_COUNT_V4)
                .map_err(|_| SeriesShadowAotErrorV4::Runtime)?
        || request.shape.identity_count
            != u32::try_from(SERIES_SHADOW_IDENTITY_COUNT_V4)
                .map_err(|_| SeriesShadowAotErrorV4::Runtime)?
    {
        return Err(SeriesShadowAotErrorV4::Runtime);
    }
    Ok(funding)
}

fn require_runtime_agreement(
    account_profile: AccountProfileV2<'_>,
    request: ShadowRequestV3<'_>,
    funding_count: usize,
    profile: &[AccountObservationV1<'_>],
    transcript: &[ShadowRuntimeObservationV3<'_>],
) -> Result<()> {
    if profile.len() != transcript.len()
        || profile.len()
            != usize::try_from(request.shape.account_count)
                .map_err(|_| SeriesShadowAotErrorV4::Runtime)?
    {
        return Err(SeriesShadowAotErrorV4::Runtime);
    }
    let span = [u32::try_from(funding_count).map_err(|_| SeriesShadowAotErrorV4::Runtime)?];
    for (coordinate, (left, right)) in profile
        .iter()
        .copied()
        .zip(transcript.iter().copied())
        .enumerate()
    {
        let executable = account_profile
            .route_privileges_with_dynamic_spans(request.shape.tail_count, &span, coordinate)
            .map_err(|_| SeriesShadowAotErrorV4::AccountProfile)?
            .executable();
        if left.key() != right.key
            || left.owner() != right.owner
            || left.lamports() != right.lamports
            || left.data() != right.data
            || executable != right.executable
            || right.signer
            || right.writable
        {
            return Err(SeriesShadowAotErrorV4::Runtime);
        }
    }
    Ok(())
}

fn project_effect(
    profile: AccountProfileV2<'_>,
    effect_bytes: &[u8],
    shadow: ShadowRequestV3<'_>,
    funding_count: usize,
    observations: &[AccountObservationV1<'_>],
    scalars: &[u64; SERIES_SHADOW_SCALAR_COUNT_V4],
    identities: &[[u8; 32]; SERIES_SHADOW_IDENTITY_COUNT_V4],
) -> Result<(Vec<u64>, Vec<u8>, Vec<ShadowResolvedRouteV3>)> {
    let effect =
        EffectProgramV4::decode(effect_bytes).map_err(|_| SeriesShadowAotErrorV4::Effect)?;
    effect
        .validate_request_coverage(
            shadow.family_request.len(),
            shadow.shape.tail_count,
            scalars,
            identities,
        )
        .map_err(|_| SeriesShadowAotErrorV4::Effect)?;
    let span = [u32::try_from(funding_count).map_err(|_| SeriesShadowAotErrorV4::Runtime)?];
    let mut aliases = Vec::with_capacity(observations.len());
    for coordinate in 0..observations.len() {
        aliases.push(
            profile
                .representative_with_dynamic_spans(shadow.shape.tail_count, &span, coordinate)
                .map_err(|_| SeriesShadowAotErrorV4::AccountProfile)?,
        );
    }
    let mut permissions = vec![AccountPermission::read_only(); observations.len()];
    derive_effect_permissions_with_dynamic_spans(
        profile,
        shadow.shape.tail_count,
        &span,
        &mut permissions,
    )
    .map_err(|_| SeriesShadowAotErrorV4::AccountProfile)?;
    let accounts = observations
        .iter()
        .map(|observation| AccountInput {
            lamports: observation.lamports(),
            data_len: observation.data().len(),
        })
        .collect::<Vec<_>>();
    let request_bytes = effect
        .base()
        .request_bytes(shadow.shape.tail_count)
        .map_err(|_| SeriesShadowAotErrorV4::Effect)?;
    let mut scratch_lamports = vec![0_u64; observations.len()];
    let mut output_lamports = vec![0_u64; observations.len()];
    let mut scratch_requests = vec![0_u8; request_bytes];
    let mut output_requests = vec![0_u8; request_bytes];
    project_effect_atomic(
        effect.base(),
        shadow.shape.tail_count,
        ProjectionV3 {
            scalars,
            identities,
            aliases: &aliases,
            accounts: &accounts,
            permissions: &permissions,
            scratch_lamports: &mut scratch_lamports,
            output_lamports: &mut output_lamports,
            scratch_requests: &mut scratch_requests,
            output_requests: &mut output_requests,
        },
    )
    .map_err(|_| SeriesShadowAotErrorV4::Effect)?;
    let routes = shadow_routes(effect, shadow.shape.tail_count, scalars, identities)?;
    Ok((output_lamports, output_requests, routes))
}

fn shadow_routes(
    effect: EffectProgramV4<'_>,
    tail_count: u32,
    scalars: &[u64],
    identities: &[[u8; 32]],
) -> Result<Vec<ShadowResolvedRouteV3>> {
    let mut output = Vec::new();
    let mut route = 0_u16;
    while route < effect.base().route_count() {
        let count = effect
            .base()
            .invocation_count(route, tail_count, scalars, identities)
            .map_err(|_| SeriesShadowAotErrorV4::Effect)?;
        let mut invocation_index = 0_u32;
        while invocation_index < count {
            let resolved = effect
                .resolved_invocation(route, invocation_index, tail_count, scalars, identities)
                .map_err(|_| SeriesShadowAotErrorV4::Effect)?;
            let invocation = resolved.invocation;
            let borrowed_witness = match resolved.borrowed_range_count() {
                0 => None,
                1 => {
                    let range = effect
                        .resolved_borrowed_range(route, 0, scalars)
                        .map_err(|_| SeriesShadowAotErrorV4::Effect)?;
                    Some((
                        u32::try_from(range.source_offset())
                            .map_err(|_| SeriesShadowAotErrorV4::Effect)?,
                        u32::try_from(range.len()).map_err(|_| SeriesShadowAotErrorV4::Effect)?,
                    ))
                }
                _ => return Err(SeriesShadowAotErrorV4::Effect),
            };
            let dependencies = shadow_dependencies(effect.base(), invocation.receipt_dependencies)?;
            let receipt_dependency = if dependencies.len() == 1 {
                dependencies.first().copied()
            } else {
                None
            };
            let receipt_dependency_count =
                u16::try_from(dependencies.len()).map_err(|_| SeriesShadowAotErrorV4::Effect)?;
            let receipt_dependencies_digest = if dependencies.is_empty() {
                [0; 32]
            } else {
                receipt_dependencies_digest_v4(&dependencies)
                    .map_err(|_| SeriesShadowAotErrorV4::Effect)?
            };
            output.push(ShadowResolvedRouteV3 {
                role: shadow_role(invocation.role),
                kind: shadow_kind(invocation.kind),
                item: invocation.item,
                fixed_account_start: invocation.fixed_account_start,
                fixed_account_count: invocation.fixed_account_count,
                item_account_start: u32::try_from(invocation.item_account_start)
                    .map_err(|_| SeriesShadowAotErrorV4::Effect)?,
                item_account_count: invocation.item_account_count,
                item_account_stride: invocation.item_account_stride,
                repeated_item_count: invocation.repeated_item_count,
                request_offset: u32::try_from(invocation.request_offset)
                    .map_err(|_| SeriesShadowAotErrorV4::Effect)?,
                request_len: u32::try_from(invocation.request_len)
                    .map_err(|_| SeriesShadowAotErrorV4::Effect)?,
                borrowed_witness,
                receipt_dependency,
                receipt_dependency_count,
                receipt_dependencies_digest,
            });
            invocation_index = invocation_index
                .checked_add(1)
                .ok_or(SeriesShadowAotErrorV4::Effect)?;
        }
        route = route.checked_add(1).ok_or(SeriesShadowAotErrorV4::Effect)?;
    }
    Ok(output)
}

fn shadow_dependencies(
    effect: dclutch_effect_kernel::v3::ProgramV3<'_>,
    dependencies: ResolvedReceiptDependenciesV3,
) -> Result<Vec<ShadowReceiptDependencyV3>> {
    let mut output = Vec::with_capacity(usize::from(dependencies.len()));
    let mut index = 0_u16;
    while index < dependencies.len() {
        let dependency = effect
            .resolved_receipt_dependency(dependencies, index)
            .map_err(|_| SeriesShadowAotErrorV4::Effect)?;
        output.push(ShadowReceiptDependencyV3 {
            producer_role: shadow_role(dependency.producer_role),
            producer_route: dependency.producer_route,
            producer_invocation: dependency.producer_invocation,
            expected_receipt_bytes: dependency.expected_receipt_bytes,
        });
        index = index.checked_add(1).ok_or(SeriesShadowAotErrorV4::Effect)?;
    }
    Ok(output)
}

const fn shadow_role(role: FixedRole) -> ShadowRouteRoleV3 {
    match role {
        FixedRole::Core => ShadowRouteRoleV3::Core,
        FixedRole::Claims => ShadowRouteRoleV3::Claims,
        FixedRole::Resolution => ShadowRouteRoleV3::Resolution,
        FixedRole::Custody => ShadowRouteRoleV3::Custody,
    }
}

const fn shadow_kind(kind: RouteKindV3) -> ShadowRouteKindV3 {
    match kind {
        RouteKindV3::Once => ShadowRouteKindV3::Once,
        RouteKindV3::AffineOnce => ShadowRouteKindV3::AffineOnce,
        RouteKindV3::Each => ShadowRouteKindV3::Each,
    }
}

fn content(bytes: &[u8]) -> Result<ContentId> {
    ContentId::new(Sha256::digest(bytes).into()).map_err(|_| SeriesShadowAotErrorV4::Digest)
}

#[cfg(test)]
mod tests;
