import DClutchSemantics.ProjectedCustodyStateV2Abi
import DClutchSemantics.Codec
import DClutchSemantics.RustEmit

open DClutch.RustEmit (rustByte emitConst)

/-! Emit the projected-custody state's layout and tag ABI as Rust.

The four `ProjectedCustodyPhaseV1` discriminants, the byte they are persisted
at, the record's magic and width, its two canonical-zero spans and every
coordinate in it.  Before this emitter all nineteen were `projected.rs`'s
alone, twelve of them written as bare arguments inside `encode` and `decode`,
and the phase coordinate had no name at all -- which is why the SDK generator
recovered it by requiring an encode and a decode expression to agree. -/

open DClutch
open DClutch.ProjectedCustodyStateV2Abi

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitProjectedCustodyStateV2Rust.lean; do not edit."
  IO.println "/// Canonical projected-custody state magic: `DCLPCS02`."
  -- One line, with formatting suppressed, because the SDK's state-machine
  -- generator reads a record magic with a single-line regex and every other
  -- emitted magic in this tree is printed this way.
  IO.println "#[rustfmt::skip]"
  IO.println s!"pub const PROJECTED_CUSTODY_STATE_MAGIC_V2: [u8; {magic.length}] = [{String.intercalate ", " (magic.map rustByte)}];"
  emitConst "PROJECTED_CUSTODY_STATE_BYTES_V2" "usize" (toString projectedStateBytes)
    "Exact persisted-state width."
  emitConst "PROJECTED_CUSTODY_STATE_SCHEMA_VERSION_V2" "u16" (toString schemaVersion)
    "Implemented persisted-state schema version."
  for phase in Phase.all do
    emitConst (Phase.rustName phase) "u8" (toString (Phase.tag phase))
      (Phase.doc phase)
  emitConst "PROJECTED_CUSTODY_PHASE_LIMIT_V1" "u8" (toString phaseLimit)
    "One past the greatest phase tag; the machine numbers from one, so bit zero is never occupied."
  emitConst "PROJECTED_CUSTODY_STATE_IDENTITY_COUNT_V2" "usize" (toString identityCount)
    "Content identities in the immutable request block."
  emitConst "PROJECTED_CUSTODY_STATE_IDENTITY_BYTES_V2" "usize" (toString identityBytes)
    "Width of one content identity in that block."
  emitConst "PROJECTED_CUSTODY_STATE_IDENTITIES_BYTES_V2" "usize"
    (toString (Field.width .identities))
    "Width of the whole identity run, which is the count times the identity width."
  emitConst "PROJECTED_CUSTODY_STATE_TAIL_OFFSET_V2" "usize" (toString tailOffset)
    "Where the mutable tail begins: the header plus the whole identity run."
  emitConst "PROJECTED_CUSTODY_HEADER_MAGIC_OFFSET_V1" "usize" (toString familyMagicOffset)
    "Magic coordinate of the header EVERY record in this family shares."
  emitConst "PROJECTED_CUSTODY_HEADER_MAGIC_BYTES_V1" "usize" (toString familyMagicBytes)
    "Magic width of that shared header."
  emitConst "PROJECTED_CUSTODY_HEADER_VERSION_OFFSET_V1" "usize" (toString familyVersionOffset)
    "ABI-version coordinate of that shared header."
  emitConst "PROJECTED_CUSTODY_HEADER_BYTES_V1" "usize" (toString familyHeaderBytes)
    "Total width of that shared header: the magic plus the version word."
  emitConst "PROJECTED_CUSTODY_STATE_HEAD_RESERVED_BYTES_V2" "usize"
    (toString (Field.width .headReserved))
    "Width of the canonical-zero span between the three tags and the cap count."
  emitConst "PROJECTED_CUSTODY_STATE_CAP_RESERVED_BYTES_V2" "usize"
    (toString (Field.width .capReserved))
    "Width of the canonical-zero span between the cap count and the identity block."
  for field in Field.all do
    emitConst (Field.rustName field) "usize" (toString (Field.offset field))
      (Field.doc field)
