import DClutchSemantics.ClearingPriceV1Abi

/-! Emit the `ClearingPriceV1` tail of the General batch record.

The tail's offsets are relative to the V1 batch record's end, which
`ClearingPriceV1Abi.the_tail_begins_where_v1_ended` pins at 224; the emitted
constants are ABSOLUTE record offsets so a fixed-offset EffectProgram write
and the SDK decoder read one number. Guard:
`crates/dclutch-trading/tests/general__clearing_price_v1_generator_fresh.rs`. -/

open DClutch.General.RuntimeWireV2 (place recordBytes)
open DClutch.General.ClearingPriceV1

def hexDigit (value : Nat) : String :=
  ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f"].getD
    value "0"

def hexByte (value : Nat) : String :=
  "0x" ++ hexDigit (value / 16) ++ hexDigit (value % 16)

def byteArray (values : List Nat) : String :=
  "[" ++ String.intercalate ", " (values.map hexByte) ++ "]"

def emitAbsolute (recordPrefix : String) (base : Nat)
    (fields : List DClutch.General.RuntimeWireV2.Field) : IO Unit := do
  for entry in place fields do
    let upper := entry.1.toUpper
    IO.println s!"/// Absolute byte offset of the `{entry.1}` field in the batch record."
    IO.println s!"pub const {recordPrefix}_{upper}_OFFSET_V1: u32 = {base + entry.2.1};"
    IO.println s!"/// Exact byte width of the `{entry.1}` field."
    IO.println s!"pub const {recordPrefix}_{upper}_BYTES_V1: usize = {entry.2.2};"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitClearingPriceV1AbiRust.lean; do not edit."
  IO.println "/// Canonical batch record magic, `DCGBAT02`."
  IO.println s!"pub const BATCH_MAGIC_V2: [u8; 8] = {byteArray batchMagic};"
  IO.println "/// Batch record ABI version."
  IO.println s!"pub const BATCH_VERSION_V2: u16 = {batchVersion};"
  IO.println "/// Status tag of a batch still admitting orders."
  IO.println s!"pub const BATCH_STATUS_COLLECTING_V2: u8 = {statusCollecting};"
  IO.println "/// Status tag of a batch whose order set is final."
  IO.println s!"pub const BATCH_STATUS_CLOSED_V2: u8 = {statusClosed};"
  IO.println "/// Status tag of a batch the settlement close has cleared, once."
  IO.println s!"pub const BATCH_STATUS_CLEARED_V2: u8 = {statusCleared};"
  IO.println ""
  IO.println "/// Exact bytes of the V1 batch record the clearing tail follows."
  IO.println s!"pub const BATCH_V1_BYTES: usize = {batchV1Bytes};"
  IO.println "/// Absolute byte offset of the clearing tail."
  IO.println s!"pub const CLEARING_OFFSET_V1: u32 = {clearingOffset};"
  IO.println "/// Exact fixed bytes of the clearing tail before its two runtime vectors."
  IO.println s!"pub const CLEARING_FIXED_BYTES_V1: usize = {clearingFixedBytes};"
  IO.println "/// Absolute byte offset of the first price cell."
  IO.println s!"pub const CLEARING_PRICES_OFFSET_V1: u32 = {pricesOffset};"
  IO.println "/// Exact byte width of one price or residual cell."
  IO.println s!"pub const CLEARING_TAIL_STRIDE_V1: u32 = {tailStride};"
  IO.println "/// Runtime-width vectors after the fixed tail: prices, then residual."
  IO.println s!"pub const CLEARING_TAIL_COUNT_V1: usize = {tailCount};"
  IO.println "/// Complete-set move tag: none."
  IO.println s!"pub const CLEARING_MOVE_NONE_V1: u8 = {moveNone};"
  IO.println "/// Complete-set move tag: the close minted sets."
  IO.println s!"pub const CLEARING_MOVE_MINT_V1: u8 = {moveMint};"
  IO.println "/// Complete-set move tag: the close merged sets."
  IO.println s!"pub const CLEARING_MOVE_MERGE_V1: u8 = {moveMerge};"
  emitAbsolute "CLEARING" clearingOffset clearingFields
