import DClutchSemantics.ProductRuntimeV2Abi

open DClutch.ProductRuntimeV2Abi

def line (name : String) (value : Nat) : String :=
  s!"pub const {name}: usize = {value};"

def main : IO Unit := do
  IO.println "// @generated by EmitProductRuntimeV2Rust.lean; do not edit."
  IO.println "pub const PRODUCT_RUNTIME_V2_SCHEMA_VERSION: u16 = 2;"
  IO.println "pub const DOMAIN_MAGIC: [u8; 8] = *b\"DCLTPRD2\";"
  IO.println (line "DOMAIN_HEADER_BYTES" domainHeaderBytes)
  IO.println (line "DOMAIN_REGION_COUNT_OFFSET" domainRegionCountOffset)
  IO.println (line "DOMAIN_CUT_COUNT_OFFSET" domainCutCountOffset)
  IO.println (line "DOMAIN_PRODUCT_ID_OFFSET" domainProductIdOffset)
  IO.println (line "DOMAIN_COORDINATE_DOMAIN_ID_OFFSET" domainCoordinateDomainIdOffset)
  IO.println (line "DOMAIN_RESULT_UNIT_ID_OFFSET" domainResultUnitIdOffset)
  IO.println (line "DOMAIN_LIABILITY_BASIS_ID_OFFSET" domainLiabilityBasisIdOffset)
  IO.println (line "DOMAIN_REPRESENTATION_RELEASE_ID_OFFSET" domainRepresentationReleaseIdOffset)
  IO.println (line "DOMAIN_MAPPING_RELEASE_ID_OFFSET" domainMappingReleaseIdOffset)
  IO.println (line "DOMAIN_CUT_DENOMINATOR_OFFSET" domainCutDenominatorOffset)
  IO.println (line "DOMAIN_CUT_BYTES" domainCutBytes)
  IO.println "pub const PORTFOLIO_MAGIC: [u8; 8] = *b\"DCLTPRF2\";"
  IO.println (line "PORTFOLIO_HEADER_BYTES" portfolioHeaderBytes)
  IO.println (line "PORTFOLIO_COEFFICIENT_COUNT_OFFSET" portfolioCoefficientCountOffset)
  IO.println (line "PORTFOLIO_ROUNDING_OFFSET" portfolioRoundingOffset)
  IO.println (line "PORTFOLIO_PRODUCT_ID_OFFSET" portfolioProductIdOffset)
  IO.println (line "PORTFOLIO_RESULT_DOMAIN_ID_OFFSET" portfolioResultDomainIdOffset)
  IO.println (line "PORTFOLIO_CLAIM_BASIS_ID_OFFSET" portfolioClaimBasisIdOffset)
  IO.println (line "PORTFOLIO_LIABILITY_BASIS_ID_OFFSET" portfolioLiabilityBasisIdOffset)
  IO.println (line "PORTFOLIO_REPRESENTATION_RELEASE_ID_OFFSET" portfolioRepresentationReleaseIdOffset)
  IO.println (line "PORTFOLIO_DENOMINATOR_OFFSET" portfolioDenominatorOffset)
  IO.println (line "PORTFOLIO_COEFFICIENT_BYTES" portfolioCoefficientBytes)
  IO.println "pub const REPRESENTATION_FLOOR_TAG: u8 = 1;"
