import DClutchSemantics.GeneralOrderV2Abi

/-! Emit the General order record V2 layout.

Every offset is derived by `place` from the field sequence in
`GeneralOrderV2Abi`; the Rust decoder, encoder and every EffectProgram write
that names an order byte read these constants. Guard:
`crates/dclutch-trading/tests/general__order_v2_generator_fresh.rs`. -/

open DClutch.General.RuntimeWireV2 (place recordBytes)
open DClutch.General.OrderV2

def hexDigit (value : Nat) : String :=
  ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f"].getD
    value "0"

def hexByte (value : Nat) : String :=
  "0x" ++ hexDigit (value / 16) ++ hexDigit (value % 16)

def byteArray (values : List Nat) : String :=
  "[" ++ String.intercalate ", " (values.map hexByte) ++ "]"

def emitPlacement (recordPrefix : String) (fields : List DClutch.General.RuntimeWireV2.Field) :
    IO Unit := do
  for entry in place fields do
    let upper := entry.1.toUpper
    IO.println s!"/// Byte offset of the `{entry.1}` field."
    IO.println s!"pub const {recordPrefix}_{upper}_OFFSET_V2: u32 = {entry.2.1};"
    IO.println s!"/// Exact byte width of the `{entry.1}` field."
    IO.println s!"pub const {recordPrefix}_{upper}_BYTES_V2: usize = {entry.2.2};"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitGeneralOrderV2AbiRust.lean; do not edit."
  IO.println "/// Canonical order record magic, `DCGSORD2`."
  IO.println s!"pub const ORDER_MAGIC_V2: [u8; 8] = {byteArray orderMagic};"
  IO.println "/// Order record ABI version."
  IO.println s!"pub const ORDER_VERSION_V2: u16 = {orderVersion};"
  IO.println "/// Order record phase byte."
  IO.println s!"pub const ORDER_PHASE_V2: u8 = {orderPhase};"
  IO.println "/// Side tag of a buy: the maker receives claims on its interval."
  IO.println s!"pub const ORDER_SIDE_BUY_V2: u8 = {sideBuy};"
  IO.println "/// Side tag of a sell: the maker delivers claims on its interval."
  IO.println s!"pub const ORDER_SIDE_SELL_V2: u8 = {sideSell};"
  IO.println ""
  IO.println "/// Exact bytes of the signed immutable header: the identity preimage."
  IO.println s!"pub const ORDER_HEADER_BYTES_V2: usize = {recordBytes orderHeaderFields};"
  IO.println "/// Exact bytes of the mutable escrow window the identity masks."
  IO.println s!"pub const ORDER_STATE_BYTES_V2: usize = {recordBytes orderStateFields};"
  IO.println "/// Byte offset of the mutable escrow window."
  IO.println s!"pub const ORDER_STATE_OFFSET_V2: u32 = {orderStateOffset};"
  IO.println "/// Byte offset of the first derived `(receive, deliver)` row."
  IO.println s!"pub const ORDER_ROW_BASE_V2: u32 = {orderRowBase};"
  IO.println "/// Byte stride of one derived per-outcome row."
  IO.println s!"pub const ORDER_ROW_STRIDE_V2: usize = {rowStride};"
  IO.println "/// Exact bytes of the shape window the joint clearing added."
  IO.println s!"pub const ORDER_SHAPE_BYTES_V2: usize = {recordBytes shapeFields};"
  IO.println "/// Exact bytes of the V1 header the V2 header extends byte for byte."
  IO.println s!"pub const ORDER_V1_HEADER_BYTES: usize = {recordBytes orderHeaderV1Fields};"
  emitPlacement "ORDER" orderFixedFields
