import DClutchSemantics.RelayedVenueDecodingRulesV1

open DClutch DClutch.RelayedVenueDecodingRulesV1

def rustByte (byte : UInt8) : String := s!"0x{Codec.byteHex byte}"

def emitBytes (visibility name : String) (value : List UInt8) : IO Unit := do
  IO.println "#[rustfmt::skip]"
  IO.println s!"{visibility} const {name}: [u8; {value.length}] = ["
  IO.println s!"    {String.intercalate ", " (value.map rustByte)},"
  IO.println "];"

def emitLengths (name : String) (value : List Nat) : IO Unit := do
  IO.println s!"pub const {name}: &[u32] = &["
  IO.println s!"    {String.intercalate ", " (value.map toString)},"
  IO.println "];"

def rustInt (value : Int) : String :=
  if value < 0 then s!"-{-value}" else toString value

def emitAcceptanceTable (name : String) (rows : List (Nat × Nat × Nat × Bool × Int)) : IO Unit := do
  IO.println "#[cfg(test)]"
  IO.println s!"pub(crate) const {name}_COUNT: usize = {rows.length};"
  IO.println "#[cfg(test)]"
  IO.println "#[rustfmt::skip]"
  IO.println s!"pub(crate) const {name}: [(u8, u8, u64, bool, i128); {rows.length}] = ["
  for row in rows do
    let (progress, isMigrated, finish, accepted, atoms) := row
    let acceptedText := if accepted then "true" else "false"
    IO.println s!"    ({progress}, {isMigrated}, {finish}, {acceptedText}, {rustInt atoms}),"
  IO.println "];"

def emitMintAcceptanceTable (name : String) (rows : List (Nat × Nat × Nat × Bool × Int)) : IO Unit := do
  IO.println "#[cfg(test)]"
  IO.println s!"pub(crate) const {name}_COUNT: usize = {rows.length};"
  IO.println "#[cfg(test)]"
  IO.println "#[rustfmt::skip]"
  IO.println s!"pub(crate) const {name}: [(u32, u8, u32, bool, i128); {rows.length}] = ["
  for row in rows do
    let (authorityTag, isInitialized, freezeTag, accepted, atoms) := row
    let acceptedText := if accepted then "true" else "false"
    IO.println s!"    ({authorityTag}, {isInitialized}, {freezeTag}, {acceptedText}, {rustInt atoms}),"
  IO.println "];"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitRelayedVenueDecodingRulesV1Rust.lean; do not edit."
  IO.println "// The venue decoding-rules table of `RelayedMainnetStateV1`: which observable a"
  IO.println "// Source selects, where the observed bytes live, and what a graduation is."

  IO.println s!"pub const RELAYED_OBSERVABLE_DBC_MIGRATION_PROGRESS_V1: u32 = {Observable.selector .dbcMigrationProgress};"
  IO.println s!"pub const RELAYED_OBSERVABLE_DBC_RAW_EXPONENT_V1: i32 = {rustInt (Observable.rawExponent .dbcMigrationProgress)};"

  IO.println s!"pub const DBC_VENUE_SET_CARDINALITY_V1: u16 = {Observable.setCardinality .dbcMigrationProgress};"
  IO.println s!"pub const DBC_PROGRAM_POSITION_V1: u16 = {Observable.programPosition .dbcMigrationProgress};"
  IO.println s!"pub const DBC_PROGRAMDATA_POSITION_V1: u16 = {Observable.programDataPosition .dbcMigrationProgress};"
  IO.println s!"pub const DBC_VENUE_POSITION_V1: u16 = {Observable.statePosition .dbcMigrationProgress};"
  IO.println s!"pub const DBC_CLOCK_POSITION_V1: u16 = {Observable.clockPosition .dbcMigrationProgress};"

  emitBytes "pub" "OBSERVED_CLOCK_SYSVAR_KEY_V1" clockSysvarKey
  emitBytes "pub" "OBSERVED_SYSVAR_OWNER_V1" sysvarOwner
  IO.println s!"pub const OBSERVED_CLOCK_SLOT_OFFSET_V1: usize = {clockSlotOffset};"
  IO.println s!"pub const OBSERVED_CLOCK_UNIX_TIMESTAMP_OFFSET_V1: usize = {clockUnixTimestampOffset};"
  IO.println s!"pub const OBSERVED_CLOCK_FIELD_BYTES_V1: usize = {clockFieldBytes};"

  emitBytes "pub" "DBC_VIRTUAL_POOL_DISCRIMINATOR_V1" virtualPoolDiscriminator
  emitBytes "pub" "DBC_TRANSFER_HOOK_POOL_DISCRIMINATOR_V1" transferHookPoolDiscriminator
  emitLengths "DBC_ADMITTED_DATA_LENGTHS_V1" admittedDataLengths
  IO.println s!"pub const DBC_DISCRIMINATOR_OFFSET_V1: usize = {discriminatorOffset};"
  IO.println s!"pub const DBC_DISCRIMINATOR_BYTES_V1: usize = {discriminatorBytes};"
  IO.println s!"pub const DBC_IS_MIGRATED_OFFSET_V1: usize = {isMigratedOffset};"
  IO.println s!"pub const DBC_MIGRATION_PROGRESS_OFFSET_V1: usize = {migrationProgressOffset};"
  IO.println s!"pub const DBC_FINISH_CURVE_TIMESTAMP_OFFSET_V1: usize = {finishCurveTimestampOffset};"
  IO.println s!"pub const DBC_FINISH_CURVE_TIMESTAMP_BYTES_V1: usize = {finishCurveTimestampBytes};"
  IO.println s!"pub const DBC_VENUE_INLINE_BYTES_V1: usize = {venueInlineBytes};"

  IO.println s!"pub const MIGRATION_PROGRESS_PRE_BONDING_CURVE_V1: u8 = {MigrationProgress.byte .preBondingCurve};"
  IO.println s!"pub const MIGRATION_PROGRESS_POST_BONDING_CURVE_V1: u8 = {MigrationProgress.byte .postBondingCurve};"
  IO.println s!"pub const MIGRATION_PROGRESS_LOCKED_VESTING_V1: u8 = {MigrationProgress.byte .lockedVesting};"
  IO.println s!"pub const MIGRATION_PROGRESS_CREATED_POOL_V1: u8 = {MigrationProgress.byte .createdPool};"

  emitAcceptanceTable "DBC_GRADUATION_ACCEPTANCE_TABLE_V1" acceptanceTable

  IO.println "// Row 1: SPL Token-2022 `Mint.mint_authority`, as a renunciation proposition."
  IO.println s!"pub const RELAYED_OBSERVABLE_MINT_AUTHORITY_RENOUNCED_V1: u32 = {Observable.selector .token2022MintAuthorityRenounced};"
  IO.println s!"pub const RELAYED_OBSERVABLE_MINT_AUTHORITY_RAW_EXPONENT_V1: i32 = {rustInt (Observable.rawExponent .token2022MintAuthorityRenounced)};"
  IO.println s!"pub const MINT_AUTHORITY_SET_CARDINALITY_V1: u16 = {Observable.setCardinality .token2022MintAuthorityRenounced};"
  IO.println s!"pub const MINT_AUTHORITY_PROGRAM_POSITION_V1: u16 = {Observable.programPosition .token2022MintAuthorityRenounced};"
  IO.println s!"pub const MINT_AUTHORITY_PROGRAMDATA_POSITION_V1: u16 = {Observable.programDataPosition .token2022MintAuthorityRenounced};"
  IO.println s!"pub const MINT_AUTHORITY_MINT_POSITION_V1: u16 = {Observable.statePosition .token2022MintAuthorityRenounced};"
  IO.println s!"pub const MINT_AUTHORITY_CLOCK_POSITION_V1: u16 = {Observable.clockPosition .token2022MintAuthorityRenounced};"
  emitLengths "MINT_ADMITTED_DATA_LENGTHS_V1" mintAdmittedDataLengths
  IO.println s!"pub const MINT_AUTHORITY_TAG_OFFSET_V1: usize = {mintAuthorityTagOffset};"
  IO.println s!"pub const MINT_COPTION_TAG_BYTES_V1: usize = {coptionTagBytes};"
  IO.println s!"pub const MINT_SUPPLY_OFFSET_V1: usize = {mintSupplyOffset};"
  IO.println s!"pub const MINT_DECIMALS_OFFSET_V1: usize = {mintDecimalsOffset};"
  IO.println s!"pub const MINT_IS_INITIALIZED_OFFSET_V1: usize = {mintIsInitializedOffset};"
  IO.println s!"pub const MINT_FREEZE_AUTHORITY_TAG_OFFSET_V1: usize = {mintFreezeAuthorityTagOffset};"
  IO.println s!"pub const MINT_INLINE_BYTES_V1: usize = {mintInlineBytes};"
  IO.println s!"pub const COPTION_NONE_TAG_V1: u32 = {coptionNoneTag};"
  IO.println s!"pub const COPTION_SOME_TAG_V1: u32 = {coptionSomeTag};"
  IO.println s!"pub const MINT_AUTHORITY_HELD_V1: u8 = {MintAuthorityState.byte .held};"
  IO.println s!"pub const MINT_AUTHORITY_RENOUNCED_V1: u8 = {MintAuthorityState.byte .renounced};"
  emitMintAcceptanceTable "MINT_AUTHORITY_ACCEPTANCE_TABLE_V1" mintAcceptanceTable
