import DClutchSemantics.CapabilityManifestV1Abi
import DClutchSemantics.Codec

/-! Emit the Lean-owned capability-manifest, typed-funding and opening-readiness
byte ABI as Rust constants. -/

open DClutch.CapabilityManifestV1Abi

def schemaByte (byte : UInt8) : String := s!"0x{DClutch.Codec.byteHex byte}"

def emitSchemaIdentity (preimageName idName preimage : String)
    (digest : List UInt8) : IO Unit := do
  IO.println s!"pub const {preimageName}: &[u8] = b\"{preimage}\";"
  IO.println s!"pub const {idName}: [u8; {digest.length}] = ["
  for line in List.range ((digest.length + 7) / 8) do
    let chunk := (digest.drop (line * 8)).take 8
    IO.println s!"    {String.intercalate ", " (chunk.map schemaByte)},"
  IO.println "];"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitCapabilityManifestV1AbiRust.lean; do not edit."
  IO.println s!"pub const CAPABILITY_MANIFEST_MAGIC_V1: [u8; 8] = *b\"{manifestMagic}\";"
  IO.println s!"pub const CAPABILITY_MANIFEST_SCHEMA_VERSION_V1: u16 = {manifestSchemaVersion};"
  IO.println s!"pub const CAPABILITY_MANIFEST_ARTIFACT_PROFILE_V1: u16 = {manifestArtifactProfile};"
  IO.println s!"pub const CAPABILITY_MANIFEST_HEADER_BYTES_V1: usize = {headerBytes};"
  IO.println s!"pub const CAPABILITY_MANIFEST_HEADER_RESERVED_BYTES_V1: usize = {headerReservedBytes};"
  IO.println s!"pub const CAPABILITY_MANIFEST_MAX_BYTES_V1: usize = {maxManifestBytes};"
  IO.println s!"pub const MAX_CAPABILITIES_V1: usize = {maxCapabilities};"
  IO.println s!"pub const MAX_DEPENDENCIES_PER_CAPABILITY_V1: usize = {maxDependenciesPerCapability};"
  for field in headerLayout do
    IO.println s!"pub const {HeaderField.constantName field.spec.name}: usize = {field.offset};"

  IO.println s!"pub const CAPABILITY_ENTRY_BYTES_V1: usize = {entryBytes};"
  IO.println s!"pub const CAPABILITY_ENTRY_RESERVED_BYTES_V1: usize = {entryReservedBytes};"
  for field in entryLayout do
    IO.println s!"pub const {EntryField.constantName field.spec.name}: usize = {field.offset};"

  IO.println s!"pub const CAPABILITY_FUNDING_QUOTE_MAGIC_V1: [u8; 8] = *b\"{fundingQuoteMagic}\";"
  IO.println s!"pub const CAPABILITY_FUNDING_QUOTE_SCHEMA_VERSION_V1: u16 = {fundingQuoteSchemaVersion};"
  IO.println s!"pub const CAPABILITY_FUNDING_QUOTE_BYTES_V1: usize = {quoteBytes};"
  IO.println s!"pub const CAPABILITY_FUNDING_QUOTE_RESERVED_BYTES_V1: usize = {quoteReservedBytes};"
  for field in quoteLayout do
    IO.println s!"pub const {QuoteField.constantName field.spec.name}: usize = {field.offset};"

  IO.println s!"pub const CAPABILITY_FUNDING_ALLOCATION_BYTES_V1: usize = {allocationBytes};"
  IO.println s!"pub const CAPABILITY_FUNDING_ALLOCATION_RESERVED_BYTES_V1: usize = {allocationReservedBytes};"
  for field in allocationLayout do
    IO.println s!"pub const {AllocationField.constantName field.spec.name}: usize = {field.offset};"

  IO.println s!"pub const CAPABILITY_FUNDING_AMOUNTS_BYTES_V1: usize = {amountsBytes};"
  for field in amountsLayout do
    IO.println s!"pub const {AmountsField.constantName field.spec.name}: usize = {field.offset};"

  IO.println s!"pub const CAPABILITY_FUNDING_BINDING_BYTES_V1: usize = {bindingBytes};"
  for field in bindingLayout do
    IO.println s!"pub const {BindingField.constantName field.spec.name}: usize = {field.offset};"

  IO.println s!"pub const CAPABILITY_FUNDING_STATE_MAGIC_V1: [u8; 8] = *b\"{fundingStateMagic}\";"
  IO.println s!"pub const CAPABILITY_FUNDING_STATE_SCHEMA_VERSION_V1: u16 = {fundingStateSchemaVersion};"
  IO.println s!"pub const CAPABILITY_FUNDING_STATE_BYTES_V1: usize = {stateBytes};"
  IO.println s!"pub const CAPABILITY_FUNDING_STATE_HEADER_RESERVED_BYTES_V1: usize = {stateHeaderReservedBytes};"
  IO.println s!"pub const CAPABILITY_FUNDING_STATE_BODY_RESERVED_BYTES_V1: usize = {stateBodyReservedBytes};"
  IO.println s!"pub const CAPABILITY_FUNDING_STATE_REMAINING_RENT_AMOUNT_OFFSET_V1: usize = {stateRemainingRentAmountOffset};"
  for field in stateLayout do
    IO.println s!"pub const {StateField.constantName field.spec.name}: usize = {field.offset};"
  IO.println s!"pub const CAPABILITY_FUNDING_PDA_DOMAIN_V1: &[u8] = b\"{fundingPdaDomain}\";"
  IO.println s!"pub const CAPABILITY_FUNDING_AUTHORITY_PDA_DOMAIN_V1: &[u8] = b\"{fundingAuthorityPdaDomain}\";"
  IO.println s!"pub const CAPABILITY_FUNDING_VAULT_PDA_DOMAIN_V1: &[u8] = b\"{fundingVaultPdaDomain}\";"

  IO.println s!"pub const CAPABILITY_FUNDING_LEDGER_MAGIC_V2: [u8; 8] = *b\"{fundingLedgerMagicV2}\";"
  IO.println s!"pub const CAPABILITY_FUNDING_LEDGER_SCHEMA_VERSION_V2: u16 = {fundingLedgerSchemaVersionV2};"
  IO.println s!"pub const CAPABILITY_FUNDING_LEDGER_HEADER_BYTES_V2: usize = {ledgerHeaderBytesV2};"
  IO.println s!"pub const CAPABILITY_FUNDING_LEDGER_SLOT_BYTES_V2: usize = {ledgerSlotBytesV2};"
  IO.println s!"pub const CAPABILITY_FUNDING_LEDGER_HEADER_RESERVED_BYTES_V2: usize = {ledgerHeaderReservedBytesV2};"
  IO.println s!"pub const CAPABILITY_FUNDING_LEDGER_SLOT_RESERVED_BYTES_V2: usize = {ledgerSlotReservedBytesV2};"
  for field in ledgerHeaderLayoutV2 do
    IO.println s!"pub const {LedgerHeaderFieldV2.constantName field.spec.name}: usize = {field.offset};"
  for field in ledgerSlotLayoutV2 do
    IO.println s!"pub const {LedgerSlotFieldV2.constantName field.spec.name}: usize = {field.offset};"
  for status in LedgerSlotStatusV2.all do
    IO.println s!"/// {LedgerSlotStatusV2.doc status}"
    IO.println s!"pub const {LedgerSlotStatusV2.constantName status}: u8 = {LedgerSlotStatusV2.tag status};"
  IO.println "/// One past the greatest slot-status tag: every status indexes its own bit of a `u8`."
  IO.println s!"pub const CAPABILITY_FUNDING_LEDGER_STATUS_LIMIT_V2: u8 = {ledgerSlotStatusLimitV2};"
  IO.println s!"pub const CAPABILITY_FUNDING_LEDGER_PDA_DOMAIN_V2: &[u8] = b\"{fundingLedgerPdaDomainV2}\";"
  IO.println s!"pub const CAPABILITY_FUNDING_LEDGER_AUTHORITY_PDA_DOMAIN_V2: &[u8] = b\"{fundingLedgerAuthorityPdaDomainV2}\";"
  IO.println s!"pub const CAPABILITY_FUNDING_LEDGER_VAULT_PDA_DOMAIN_V2: &[u8] = b\"{fundingLedgerVaultPdaDomainV2}\";"

  IO.println s!"pub const MARKET_OPENING_READINESS_MAGIC_V1: [u8; 8] = *b\"{readinessMagic}\";"
  IO.println s!"pub const MARKET_OPENING_READINESS_SCHEMA_VERSION_V1: u16 = {readinessSchemaVersion};"
  IO.println s!"pub const MARKET_OPENING_READINESS_BYTES_V1: usize = {readinessBytes};"
  IO.println s!"pub const READINESS_HEADER_RESERVED_BYTES_V1: usize = {readinessHeaderReservedBytes};"
  IO.println s!"pub const READINESS_BODY_RESERVED_BYTES_V1: usize = {readinessBodyReservedBytes};"
  for field in readinessLayout do
    IO.println s!"pub const {ReadinessField.constantName field.spec.name}: usize = {field.offset};"
  IO.println s!"pub const MARKET_OPENING_READINESS_PDA_DOMAIN_V1: &[u8] = b\"{readinessPdaDomain}\";"
  emitSchemaIdentity "CAPABILITY_MANIFEST_SCHEMA_RELEASE_PREIMAGE_V1" "CAPABILITY_MANIFEST_SCHEMA_RELEASE_ID_V1"
    schemaReleasePreimage schemaReleaseId
