import DClutchSemantics.ProtocolParametersV1
import DClutchSemantics.Codec

open DClutch DClutch.ProtocolParametersV1

def rustByte (byte : UInt8) : String := s!"0x{Codec.byteHex byte}"

def emitMagic (name : String) (value : List UInt8) : IO Unit :=
  IO.println
    s!"pub const {name}: [u8; {value.length}] = [{String.intercalate ", " (value.map rustByte)}];"

def emitOffset {Name : Type} [DecidableEq Name]
    (rustPrefix : String) (layout : List (AbiSchema.PlacedField Name))
    (name : String) (field : Name) : IO Unit :=
  let offset := ((AbiSchema.coordinate? field layout).getD (0, 0)).1
  IO.println s!"pub(crate) const {rustPrefix}_{name}_OFFSET: usize = {offset};"

def main : IO Unit := do
  IO.println
    "// @generated by formal/dclutch-semantics/EmitProtocolParametersV1Rust.lean; do not edit."
  IO.println s!"pub const PROTOCOL_PARAMETERS_ABI_VERSION_V1: u16 = {abiVersion};"
  IO.println s!"pub const PROTOCOL_PARAMETERS_RECORD_BYTES_V1: usize = {recordBytes};"
  IO.println s!"pub const PROTOCOL_PARAMETERS_RECEIPT_BYTES_V1: usize = {receiptBytes};"
  emitMagic "PROTOCOL_PARAMETERS_RECORD_MAGIC_V1" recordMagic
  emitMagic "PROTOCOL_PARAMETERS_RECEIPT_MAGIC_V1" receiptMagic
  IO.println s!"pub const PROTOCOL_PARAMETERS_PDA_DOMAIN_V1: &[u8] = b\"{recordPdaDomain}\";"
  IO.println s!"pub const PROTOCOL_BASIS_POINT_DENOMINATOR_V1: u16 = {basisPointDenominator};"
  IO.println
    s!"pub const PROTOCOL_ABSOLUTE_FEE_CEILING_BASIS_POINTS_V1: u16 = {absoluteFeeCeilingBasisPoints};"
  IO.println s!"pub const PROTOCOL_SLOTS_PER_NOMINAL_DAY_V1: u64 = {slotsPerNominalDay};"
  IO.println
    s!"pub const PROTOCOL_MINIMUM_CHANGE_DELAY_SLOTS_V1: u64 = {minimumChangeDelaySlots};"
  IO.println
    s!"pub const PROTOCOL_GENESIS_MAX_FEE_BASIS_POINTS_V1: u16 = {genesis.maxFeeBasisPoints};"
  IO.println
    s!"pub const PROTOCOL_GENESIS_TAKE_BASIS_POINTS_V1: u16 = {genesis.protocolTakeBasisPoints};"
  IO.println
    s!"pub const PROTOCOL_GENESIS_CLOSER_CARVE_BASIS_POINTS_V1: u16 = {genesis.closerCarveBasisPoints};"
  IO.println
    s!"pub const PROTOCOL_GENESIS_CLOSER_REWARD_CAP_LAMPORTS_V1: u64 = {genesis.closerRewardCapLamports};"
  IO.println
    s!"pub const PROTOCOL_GENESIS_CRANK_REWARD_CAP_LAMPORTS_V1: u64 = {genesis.crankRewardCapLamports};"
  for (name, field) in [
      ("VERSION", RecordField.version), ("KIND", .kind), ("BUMP", .bump),
      ("RESERVED_HEADER", .reservedHeader),
      ("GOVERNANCE_AUTHORITY", .governanceAuthority),
      ("PROTOCOL_BENEFICIARY", .protocolBeneficiary),
      ("PENDING_DIGEST", .pendingDigest),
      ("GENERATION", .generation), ("ACTIVATION_SLOT", .activationSlot),
      ("CHANGE_DELAY_SLOTS", .changeDelaySlots),
      ("PENDING_EARLIEST_APPLY_SLOT", .pendingEarliestApplySlot),
      ("CLOSER_REWARD_CAP", .closerRewardCapLamports),
      ("CRANK_REWARD_CAP", .crankRewardCapLamports),
      ("MAX_FEE_BASIS_POINTS", .maxFeeBasisPoints),
      ("TAKE_BASIS_POINTS", .protocolTakeBasisPoints),
      ("CLOSER_CARVE_BASIS_POINTS", .closerCarveBasisPoints),
      ("RESERVED_TAIL", .reservedTail)] do
    emitOffset "PROTOCOL_PARAMETERS_RECORD" recordLayout name field
  for (name, field) in [
      ("VERSION", ReceiptField.version), ("RESERVED_HEADER", .reservedHeader),
      ("PREVIOUS_DIGEST", .previousDigest), ("NEW_DIGEST", .newDigest),
      ("GENERATION", .generation), ("PROPOSED_AT_SLOT", .proposedAtSlot),
      ("ACTIVATION_SLOT", .activationSlot), ("DELAY_SLOTS", .delaySlots)] do
    emitOffset "PROTOCOL_PARAMETERS_RECEIPT" receiptLayout name field
