import DClutchSemantics.SourceScheduledMedianV1
import DClutchSemantics.Codec
import DClutchSemantics.RustEmit

open DClutch.RustEmit (emitBytesRows emitSliceSkip)

/-!
Emit the cadence tolerance's wire coordinate inside `WindowSpecV1`'s reserved
tail, its lifting-plan identity, and two finite corpora: admitted and refused
tolerated schedules, and the exact median over the atoms of an admitted window
including every tie the one-answer theorem exists for.

The handwritten Rust kernel consumes this output; this executable emits no Rust
control flow.
-/

open DClutch.SourceScheduledMedianV1
open DClutch.AbiSchema

def maxSamples : Nat := 7

def padded (values : List Int) : List Int :=
  values ++ List.replicate (maxSamples - values.length) 0

def renderInts (values : List Int) : String :=
  String.intercalate ", " (values.map fun value => toString value)

def emitSchedule (index : Nat) (case : Schedule × List Int) : IO Unit := do
  let schedule := case.1
  let times := case.2
  if times.length > maxSamples then
    throw <| IO.userError s!"schedule case {index} exceeds the emitted sample width"
  let samples := times.map fun time => ({ unixSeconds := time, atoms := 0 } : Sample)
  let verdict := admittedSchedule schedule samples
  IO.println "    ScheduleCaseV1 {"
  IO.println s!"        start_unix_seconds: {schedule.start},"
  IO.println s!"        cadence_seconds: {schedule.cadence},"
  IO.println s!"        count: {schedule.count},"
  IO.println s!"        tolerance_seconds: {schedule.tolerance},"
  IO.println s!"        offered: {times.length},"
  IO.println s!"        times: [{renderInts (padded times)}],"
  IO.println s!"        admitted: {if verdict then "true" else "false"},"
  IO.println "    },"

def emitMedian (index : Nat) (atoms : List Int) : IO Unit := do
  if atoms.length > maxSamples then
    throw <| IO.userError s!"median case {index} exceeds the emitted sample width"
  let expected ← match median? atoms with
    | some value => pure value
    | none => throw <| IO.userError s!"median case {index} produced no answer"
  IO.println "    MedianCaseV1 {"
  IO.println s!"        count: {atoms.length},"
  IO.println s!"        atoms: [{renderInts (padded atoms)}],"
  IO.println s!"        expected: {expected},"
  IO.println "    },"

def main : IO Unit := do
  IO.println
    "// @generated by formal/dclutch-semantics/EmitSourceScheduledMedianV1Rust.lean; do not edit."
  IO.println "use super::{MedianCaseV1, ScheduleCaseV1};"
  for field in tailLayout do
    IO.println s!"pub const {TailField.rustName field.spec.name}: usize = {field.offset};"
  IO.println s!"pub const WINDOW_SPEC_CADENCE_TOLERANCE_TAIL_RESERVED_BYTES_V1: usize = {_root_.DClutch.SourceWindowSpecV1Abi.Field.width .tailReserved};"
  emitSliceSkip "CADENCE_TOLERANCE_LIFTING_PLAN_PREIMAGE_V1" liftingPlanPreimage
  emitBytesRows "pub" "CADENCE_TOLERANCE_LIFTING_PLAN_ID_V1" liftingPlanId
  IO.println s!"pub const SCHEDULED_MEDIAN_CORPUS_MAX_SAMPLES_V1: usize = {maxSamples};"
  IO.println s!"pub const SCHEDULE_CASES_V1: [ScheduleCaseV1; {scheduleCases.length}] = ["
  for indexed in scheduleCases.zipIdx do
    emitSchedule indexed.2 indexed.1
  IO.println "];"
  IO.println s!"pub const MEDIAN_CASES_V1: [MedianCaseV1; {medianCases.length}] = ["
  for indexed in medianCases.zipIdx do
    emitMedian indexed.2 indexed.1
  IO.println "];"
