import DClutchSemantics.Codec
import DClutchSemantics.DirectIntentV3Codec
import DClutchSemantics.RustEmit

open DClutch.RustEmit (emitRustBytes)

/-! Emit the RFQ ticket ABI: the Direct signed-intent V3 with its counterparty. -/

open DClutch
open DClutch.DirectIntentV3Codec

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitDirectIntentV3Rust.lean; do not edit."
  IO.println s!"pub const COMPACT_INTENT_VERSION_V3: u16 = {intentVersionV3};"
  IO.println s!"pub const COMPACT_INTENT_BYTES_V3: usize = {compactIntentBytesV3};"
  IO.println s!"pub const COMPACT_INTENT_SIGNED_PREIMAGE_BYTES_V3: usize = {signedPreimageBytesV3};"
  emitRustBytes "pub" "COMPACT_INTENT_MAGIC_V3" intentMagicV3
  emitRustBytes "pub" "COMPACT_INTENT_SIGNATURE_DOMAIN_ID_V3" signatureDomainIdV3
  for field in intentLayoutV3 do
    IO.println s!"pub(crate) const {IntentFieldV3.rustName field.spec.name}: usize = {field.offset};"
  IO.println ""
  IO.println "#[cfg(test)]"
  emitRustBytes "pub(crate)" "COMPACT_INTENT_NAMED_EXAMPLE_V3" (encodeCompactIntentV3 Examples.named)
  IO.println "#[cfg(test)]"
  emitRustBytes "pub(crate)" "COMPACT_INTENT_NAMED_SIGNED_EXAMPLE_V3" (signedPreimageV3 Examples.named)
  IO.println "#[cfg(test)]"
  emitRustBytes "pub(crate)" "COMPACT_INTENT_BEARER_EXAMPLE_V3" (encodeCompactIntentV3 Examples.bearer)
