import DClutchSemantics.ProtocolInfrastructure

/-! Emit the ArtifactRelease finalization-observation decision-case corpus.

This emits VECTORS, not the rule. `dclutch-registry-contract` keeps
`ArtifactReleaseV1::authenticate_deployment` and `dclutch-registry-sbf` keeps
the three-way refusal partition; the corpus is what makes them answerable to
`ProtocolInfrastructure.lean`.
-/

open DClutch
open DClutch.ProtocolInfrastructure

def rustOptionIdentity : Option Identity → String
  | none => "None"
  | some identity => s!"Some({identity})"

def rustBool : Bool → String
  | true => "true"
  | false => "false"

def rustImmutable : UpgradePolicy → String
  | .immutable => "true"
  | .exactAuthority => "false"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitArtifactReleaseFinalizationCorpusRust.lean; do not edit."
  IO.println "/// One ArtifactRelease finalization observation, as Lean decides it."
  IO.println "#[derive(Clone, Copy, Debug, Eq, PartialEq)]"
  IO.println "pub struct ReleaseFinalizationVectorV1 {"
  IO.println "    /// The Lean decision case this vector stands for."
  IO.println "    pub name: &'static str,"
  IO.println "    /// Bound upgrade policy: immutable, or one exact named authority."
  IO.println "    pub bound_policy_immutable: bool,"
  IO.println "    /// Authority fill byte the release bound, expanded to 32 bytes."
  IO.println "    pub bound_authority: Option<u8>,"
  IO.println "    /// Deployment slot the release bound."
  IO.println "    pub bound_slot: u64,"
  IO.println "    /// ELF digest fill byte the release bound, expanded to 32 bytes."
  IO.println "    pub bound_elf_digest: u8,"
  IO.println "    /// Program/ProgramData/loader identities equal the bound triple."
  IO.println "    pub observed_identity_matches: bool,"
  IO.println "    /// The Program body's ProgramData link equals the bound one."
  IO.println "    pub observed_programdata_link_matches: bool,"
  IO.println "    /// Loader V3 owns both observed accounts."
  IO.println "    pub observed_loader_owns_both: bool,"
  IO.println "    /// The observed Program account is executable."
  IO.println "    pub observed_program_executable: bool,"
  IO.println "    /// The observed ProgramData account is executable (it must not be)."
  IO.println "    pub observed_programdata_executable: bool,"
  IO.println "    /// Deployment slot observed on live ProgramData."
  IO.println "    pub observed_slot: u64,"
  IO.println "    /// ELF digest fill byte observed on live ProgramData."
  IO.println "    pub observed_elf_digest: u8,"
  IO.println "    /// Authority fill byte observed on live ProgramData."
  IO.println "    pub observed_authority: Option<u8>,"
  IO.println "    /// Expected outcome tag: 0 admit, 1 not deployed, 2 superseded, 3 ELF mismatch."
  IO.println "    pub outcome: u8,"
  IO.println "}"
  IO.println ""
  IO.println s!"pub const RELEASE_FINALIZATION_OUTCOME_ADMIT: u8 = {FinalizationOutcome.admit.tag};"
  IO.println s!"pub const RELEASE_FINALIZATION_OUTCOME_NOT_DEPLOYED: u8 = {FinalizationOutcome.refuseNotDeployed.tag};"
  IO.println s!"pub const RELEASE_FINALIZATION_OUTCOME_SUPERSEDED: u8 = {FinalizationOutcome.refuseSuperseded.tag};"
  IO.println s!"pub const RELEASE_FINALIZATION_OUTCOME_ELF_MISMATCH: u8 = {FinalizationOutcome.refuseElfMismatch.tag};"
  IO.println ""
  IO.println s!"pub const RELEASE_FINALIZATION_VECTORS_V1: [ReleaseFinalizationVectorV1; {finalizationVectors.length}] = ["
  for vector in finalizationVectors do
    let o := vector.observation
    IO.println "    ReleaseFinalizationVectorV1 {"
    IO.println s!"        name: \"{vector.name}\","
    IO.println s!"        bound_policy_immutable: {rustImmutable o.boundUpgradePolicy},"
    IO.println s!"        bound_authority: {rustOptionIdentity o.boundUpgradeAuthority},"
    IO.println s!"        bound_slot: {o.boundDeploymentSlot},"
    IO.println s!"        bound_elf_digest: {o.boundElfDigest},"
    IO.println s!"        observed_identity_matches: {rustBool o.observedIdentityMatches},"
    IO.println s!"        observed_programdata_link_matches: {rustBool o.observedProgramDataLinkMatches},"
    IO.println s!"        observed_loader_owns_both: {rustBool o.observedLoaderOwnsBoth},"
    IO.println s!"        observed_program_executable: {rustBool o.observedProgramExecutable},"
    IO.println s!"        observed_programdata_executable: {rustBool o.observedProgramDataExecutable},"
    IO.println s!"        observed_slot: {o.observedDeploymentSlot},"
    IO.println s!"        observed_elf_digest: {o.observedElfDigest},"
    IO.println s!"        observed_authority: {rustOptionIdentity o.observedUpgradeAuthority},"
    IO.println s!"        outcome: {o.outcome.tag},"
    IO.println "    },"
  IO.println "];"
