import DClutchSemantics.FractionalClaimV1
import DClutchSemantics.Codec

/-! Emit only the Lean-owned Fractional V1 physical layout constants. -/

open DClutch.FractionalClaimV1.PhysicalAbi

def rustByte (byte : UInt8) : String := s!"0x{DClutch.Codec.byteHex byte}"

def rustBytes (bytes : List UInt8) : String :=
  s!"[{String.intercalate ", " (bytes.map rustByte)}]"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitFractionalClaimV1AbiRust.lean; do not edit."
  IO.println s!"pub const FRACTIONAL_TERMS_MAGIC_V1: [u8; 8] = {rustBytes termsMagic};"
  IO.println s!"pub const FRACTIONAL_PROJECTION_MAGIC_V1: [u8; 8] = {rustBytes projectionMagic};"
  IO.println s!"pub const SCHEMA_VERSION_V1: u16 = {schemaVersion};"
  IO.println s!"pub const FRACTIONAL_TERMS_HEADER_BYTES_V1: usize = {termsHeaderBytes};"
  IO.println s!"pub const FRACTIONAL_TERMS_MINT_BYTES_V1: usize = {termsMintBytes};"
  IO.println s!"pub const FRACTIONAL_PROJECTION_HEADER_BYTES_V1: usize = {projectionHeaderBytes};"
  IO.println s!"pub const FRACTIONAL_PROJECTION_ROW_BYTES_V1: usize = {projectionRowBytes};"
  IO.println s!"pub(crate) const TERMS_VERSION_OFFSET: usize = {termsVersionOffset};"
  IO.println s!"pub(crate) const TERMS_RESERVED_A_OFFSET: usize = {termsReservedAOffset};"
  IO.println s!"pub(crate) const TERMS_RESERVED_A_BYTES: usize = {termsReservedABytes};"
  IO.println s!"pub(crate) const TERMS_MARKET_OFFSET: usize = {termsMarketOffset};"
  IO.println s!"pub(crate) const TERMS_RESULT_DOMAIN_OFFSET: usize = {termsResultDomainOffset};"
  IO.println s!"pub(crate) const TERMS_RELEASE_SET_OFFSET: usize = {termsReleaseSetOffset};"
  IO.println s!"pub(crate) const TERMS_TOKEN_PROGRAM_OFFSET: usize = {termsTokenProgramOffset};"
  IO.println s!"pub(crate) const TERMS_TOKEN_BEHAVIOR_OFFSET: usize = {termsTokenBehaviorOffset};"
  IO.println s!"pub(crate) const TERMS_OUTCOME_COUNT_OFFSET: usize = {termsOutcomeCountOffset};"
  IO.println s!"pub(crate) const TERMS_RESERVED_B_OFFSET: usize = {termsReservedBOffset};"
  IO.println s!"pub(crate) const TERMS_RESERVED_B_BYTES: usize = {termsReservedBBytes};"
  IO.println s!"pub(crate) const TERMS_DENOMINATOR_OFFSET: usize = {termsDenominatorOffset};"
  IO.println s!"pub(crate) const PROJECTION_VERSION_OFFSET: usize = {projectionVersionOffset};"
  IO.println s!"pub(crate) const PROJECTION_PHASE_OFFSET: usize = {projectionPhaseOffset};"
  IO.println s!"pub(crate) const PROJECTION_RESERVED_OFFSET: usize = {projectionReservedOffset};"
  IO.println s!"pub(crate) const PROJECTION_RESERVED_BYTES: usize = {projectionReservedBytes};"
  IO.println s!"pub(crate) const PROJECTION_TERMS_ID_OFFSET: usize = {projectionTermsIdOffset};"
  IO.println s!"pub(crate) const PROJECTION_MARKET_OFFSET: usize = {projectionMarketOffset};"
  IO.println s!"pub(crate) const PROJECTION_OUTCOME_COUNT_OFFSET: usize = {projectionOutcomeCountOffset};"
  IO.println s!"pub(crate) const PROJECTION_TERMINAL_OUTCOME_OFFSET: usize = {projectionTerminalOutcomeOffset};"
  IO.println s!"pub(crate) const PROJECTION_REVISION_OFFSET: usize = {projectionRevisionOffset};"
  IO.println s!"pub(crate) const NO_TERMINAL_OUTCOME: u32 = {noTerminalOutcome};"
