import DClutchSemantics.ScoringRuleV1
import DClutchSemantics.ScoringRuleAbiV1
import DClutchSemantics.RustEmit

/-! Emit the scoring Dealer's Lean-owned constants for
`crates/dclutch-trading/src/scoring_rule/generated_scoring_rule.rs`: the
63-entry root-chain table (the SPECIFICATION of `Ê`, pinned to the chain by
`table_is_the_root_chain`), the fixed-point constants, every record's magic,
width and offsets, the PDA domains, the account frames, and -- under
`#[cfg(test)]` -- the corpus the Lean evaluates, so the Rust kernel's tests
pin against numbers Lean computed rather than numbers a human typed.

Guard: `crates/dclutch-trading/tests/scoring_rule__generator_fresh.rs`. -/

open DClutch.ScoringRuleV1 DClutch.ScoringRuleAbiV1 DClutch.AbiSchema

def emitOffsets {α : Type} [DecidableEq α] (rename : α → String)
    (layout : List (PlacedField α)) : IO Unit := do
  for field in layout do
    IO.println s!"pub const {rename field.spec.name}: usize = {field.offset};"

def emitMagic (name value : String) : IO Unit :=
  IO.println s!"pub const {name}: [u8; 8] = *b\"{value}\";"

/-- A PDA seed domain, with the length bound the runtime enforces held in
place.  A seed segment past 32 bytes makes every address that uses it
underivable, and the failure is at the derivation and not at the declaration,
so the assert travels with the constant. -/
def emitDomain (name value : String) : IO Unit := do
  IO.println s!"pub const {name}: &[u8] = b\"{value}\";"
  IO.println s!"const _: () = assert!({name}.len() <= 32);"

def emitFrame (prefix_ : String) (frame : List FrameSlot) : IO Unit := do
  IO.println s!"pub const {prefix_}_ACCOUNT_COUNT: usize = {frame.length};"
  let mut index := 0
  for slot in frame do
    IO.println s!"pub const {slotConstantName prefix_ slot}: usize = {index};"
    index := index + 1
  let bools (pick : FrameSlot → Bool) : String :=
    String.intercalate ", " (frame.map fun slot => if pick slot then "true" else "false")
  IO.println s!"pub const {prefix_}_WRITABLE: [bool; {frame.length}] = [{bools (·.writable)}];"
  IO.println s!"pub const {prefix_}_SIGNER: [bool; {frame.length}] = [{bools (·.signer)}];"

def emitVector (values : List Nat) : String :=
  "[" ++ String.intercalate ", " (values.map toString) ++ "]"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitScoringRuleV1Rust.lean; do not edit."
  IO.println "//! The scoring Dealer's Lean-owned constants. See `ScoringRuleV1.lean` and"
  IO.println "//! `ScoringRuleAbiV1.lean`; the corpus at the tail is what Lean evaluated."
  IO.println "#![allow(missing_docs, reason = \"Lean-emitted constants; their documentation is ScoringRuleAbiV1.lean\")]"
  IO.println s!"pub const FRACTION_BITS: u32 = {fractionBits};"
  IO.println s!"pub const ONE_Q62: u128 = {one};"
  IO.println s!"pub const LOG_SLACK: u128 = {logSlack};"
  IO.println s!"pub const MAX_OUTCOMES: usize = {maxOutcomes};"
  IO.println s!"pub const VECTOR_BYTES: usize = {vectorBytes};"
  IO.println s!"pub const WIRE_VERSION: u16 = {wireVersion};"
  IO.println s!"pub const RULE_VERSION: u16 = {ruleVersion};"
  IO.println s!"pub const REFUSAL_SUB_BAND_OFFSET: u32 = {refusalSubBandOffset};"
  IO.println s!"pub const MIN_OUTCOMES: usize = 2;"
  IO.println s!"pub const MAX_LIQUIDITY: u64 = {2 ^ 40};"
  IO.println "/// The root chain: `T[0] = 2^61`, `T[k] = isqrt(T[k-1] * 2^62)`."
  IO.println "#[rustfmt::skip]"
  IO.println s!"pub const EXP2_NEG_TABLE_Q62: [u128; {tableList.length}] = ["
  for value in tableList do
    IO.println s!"    {value},"
  IO.println "];"
  emitMagic "RULE_MAGIC" ruleMagic
  emitMagic "FUND_MAGIC" fundMagic
  emitMagic "QUOTE_MAGIC" quoteMagic
  emitMagic "FOUND_REQUEST_MAGIC" foundRequestMagic
  emitMagic "QUOTE_REQUEST_MAGIC" quoteRequestMagic
  emitMagic "FILL_REQUEST_MAGIC" fillRequestMagic
  emitMagic "WITHDRAW_REQUEST_MAGIC" withdrawRequestMagic
  emitMagic "REDEEM_REQUEST_MAGIC" redeemRequestMagic
  emitMagic "RECEIPT_MAGIC" receiptMagic
  emitMagic "FILL_WITNESS_MAGIC" fillWitnessMagic
  emitDomain "RULE_PDA_DOMAIN" rulePdaDomain
  emitDomain "FUND_PDA_DOMAIN" fundPdaDomain
  emitDomain "QUOTE_PDA_DOMAIN" quotePdaDomain
  IO.println s!"pub const RULE_BYTES: usize = {ruleBytes};"
  IO.println s!"pub const FUND_BYTES: usize = {fundBytes};"
  IO.println s!"pub const QUOTE_BYTES: usize = {quoteBytes};"
  IO.println s!"pub const FOUND_REQUEST_BYTES: usize = {foundRequestBytes};"
  IO.println s!"pub const QUOTE_REQUEST_BYTES: usize = {quoteRequestBytes};"
  IO.println s!"pub const FILL_REQUEST_BYTES: usize = {fillRequestBytes};"
  IO.println s!"pub const WITHDRAW_REQUEST_BYTES: usize = {withdrawRequestBytes};"
  IO.println s!"pub const REDEEM_REQUEST_BYTES: usize = {redeemRequestBytes};"
  IO.println s!"pub const RECEIPT_BYTES: usize = {receiptBytes};"
  IO.println s!"pub const FILL_WITNESS_BYTES: usize = {fillWitnessBytes};"
  emitOffsets RuleFieldName (specialize ruleSchema)
  emitOffsets FundField.constantName fundLayout
  emitOffsets QuoteField.constantName quoteLayout
  emitOffsets FoundRequestField.constantName foundRequestLayout
  emitOffsets QuoteRequestField.constantName quoteRequestLayout
  emitOffsets FillRequestField.constantName fillRequestLayout
  emitOffsets WithdrawRequestField.constantName withdrawRequestLayout
  emitOffsets RedeemRequestFieldName redeemRequestLayout
  emitOffsets ReceiptField.constantName receiptLayout
  emitOffsets FillWitnessField.constantName fillWitnessLayout
  IO.println s!"pub const FUND_PHASE_OPEN: u8 = {fundPhaseOpen.toNat};"
  IO.println s!"pub const FUND_PHASE_RETIRED: u8 = {fundPhaseRetired.toNat};"
  IO.println s!"pub const ROUTE_FOUND: u8 = {routeFound.toNat};"
  IO.println s!"pub const ROUTE_QUOTE: u8 = {routeQuote.toNat};"
  IO.println s!"pub const ROUTE_FILL: u8 = {routeFill.toNat};"
  IO.println s!"pub const ROUTE_WITHDRAW: u8 = {routeWithdraw.toNat};"
  IO.println s!"pub const ROUTE_REDEEM: u8 = {routeRedeem.toNat};"
  emitFrame "REDEEM" redeemFrame
  emitFrame "FOUND" foundFrame
  emitFrame "QUOTE" quoteFrame
  emitFrame "FILL" fillFrame
  emitFrame "WITHDRAW" withdrawFrame
  IO.println "#[cfg(test)]"
  IO.println "pub const EXP2_NEG_CORPUS: [(u64, u64, u128); 5] = ["
  for (b, d) in [(2 ^ 30, 0), (2 ^ 30, 2 ^ 29), (2 ^ 30, 2 ^ 30 - 1),
      (2 ^ 30, 3 * 2 ^ 30 + 7), (2 ^ 30, 62 * 2 ^ 30)] do
    IO.println s!"    ({b}, {d}, {exp2Neg b d}),"
  IO.println "];"
  IO.println "#[cfg(test)]"
  IO.println "pub const LOG2_CEIL_CORPUS: [(u128, u128); 3] = ["
  for s in [one, 2 * one, 5 * one] do
    IO.println s!"    ({s}, {log2Ceil s}),"
  IO.println "];"
  IO.println "#[cfg(test)]"
  IO.println "pub const SUBSIDY_CORPUS: [(u64, u8, u64); 3] = ["
  for (b, k) in [(2 ^ 30, 2), (2 ^ 30, 5), (2 ^ 20, 3)] do
    IO.println s!"    ({b}, {k}, {subsidyOf b k}),"
  IO.println "];"
  let inventory := [12345, 2 ^ 30 / 3 + 12345, 2 * 2 ^ 30 / 3 + 12345, 2 ^ 30 + 12345,
    4 * 2 ^ 30 / 3 + 12345]
  IO.println "#[cfg(test)]"
  IO.println s!"pub const LMSR_VALUE_CORPUS_INVENTORY: [u64; 5] = {emitVector inventory};"
  IO.println "#[cfg(test)]"
  IO.println s!"pub const LMSR_VALUE_CORPUS_MINIMUM: u64 = {listMin inventory};"
  IO.println "#[cfg(test)]"
  IO.println s!"pub const LMSR_VALUE_CORPUS_COST: u64 = {liquidityCost (2 ^ 30) inventory};"
  IO.println "#[cfg(test)]"
  IO.println s!"pub const PRICES_CORPUS_TWO: [u64; 2] = {emitVector (pricesOf (2 ^ 30) one [0, 0])};"
  IO.println "#[cfg(test)]"
  IO.println s!"pub const PRICES_CORPUS_SKEWED: [u64; 2] = {emitVector (pricesOf (2 ^ 30) one [0, 2 ^ 30])};"
  IO.println "#[cfg(test)]"
  IO.println s!"pub const PRICES_CORPUS_FIVE: [u64; 5] = {emitVector (pricesOf (2 ^ 30) one inventory)};"
