import DClutchSemantics.SourcePrincipalCapacityV1
import DClutchSemantics.Codec

/-!
Emit the `ManipulationFloorV1` ABI, κ's two coordinates inside the existing
`SourceCapacityProfileV1` reserved tail, the conservative default κ with its
lifting-plan identity, and two finite corpora: the founding-admission verdicts
and the hostile floor-decoder refusals with their named reasons.

The handwritten Rust kernel consumes this output; this executable emits no Rust
control flow.
-/

open DClutch.SourcePrincipalCapacityV1
open DClutch.AbiSchema

def rustByte (byte : UInt8) : String := s!"0x{DClutch.Codec.byteHex byte}"

def emitBytes (visibility name : String) (value : List UInt8) : IO Unit := do
  IO.println "#[rustfmt::skip]"
  IO.println s!"{visibility} const {name}: [u8; {value.length}] = ["
  for line in List.range ((value.length + 15) / 16) do
    let chunk := (value.drop (line * 16)).take 16
    IO.println s!"    {String.intercalate ", " (chunk.map rustByte)},"
  IO.println "];"

def emitSlice (name : String) (value : List UInt8) : IO Unit := do
  IO.println "#[rustfmt::skip]"
  IO.println s!"pub const {name}: &[u8] = &["
  IO.println s!"    {String.intercalate ", " (value.map rustByte)},"
  IO.println "];"

def emitAdmission (case : Nat × Nat × Nat × Nat) : IO Unit := do
  let kappa : Kappa := { numerator := case.1, denominator := case.2.1 }
  let floorAtoms := case.2.2.1
  let principal := case.2.2.2
  let verdict := admit kappa floorAtoms principal
  IO.println "    PrincipalAdmissionCaseV1 {"
  IO.println s!"        numerator: {kappa.numerator},"
  IO.println s!"        denominator: {kappa.denominator},"
  IO.println s!"        floor_atoms: {floorAtoms},"
  IO.println s!"        principal_atoms: {principal},"
  IO.println s!"        admitted: {if verdict then "true" else "false"},"
  IO.println "    },"

def emitRefusal (index : Nat) (candidate : List UInt8) : IO Unit := do
  let reason ← match refuse? candidate with
    | some reason => pure reason
    | none => throw <| IO.userError s!"hostile floor {index} was admitted"
  IO.println "    ("
  IO.println "        &["
  for line in List.range ((candidate.length + 15) / 16) do
    let chunk := (candidate.drop (line * 16)).take 16
    IO.println s!"            {String.intercalate ", " (chunk.map rustByte)},"
  IO.println "        ],"
  IO.println s!"        {reason.tag},"
  IO.println "    ),"

def main : IO Unit := do
  IO.println
    "// @generated by formal/dclutch-semantics/EmitSourcePrincipalCapacityV1Rust.lean; do not edit."
  IO.println "use super::PrincipalAdmissionCaseV1;"
  IO.println s!"pub const MANIPULATION_FLOOR_V1_BYTES: usize = {bytes};"
  IO.println s!"pub const MANIPULATION_FLOOR_V1_SCHEMA_VERSION: u16 = {schemaVersion};"
  emitBytes "pub" "MANIPULATION_FLOOR_V1_MAGIC" magic
  emitSlice "MANIPULATION_FLOOR_SCHEMA_RELEASE_PREIMAGE_V1" schemaReleasePreimage
  emitBytes "pub" "MANIPULATION_FLOOR_SCHEMA_RELEASE_ID_V1" schemaReleaseId
  emitSlice "PRINCIPAL_CAPACITY_LIFTING_PLAN_PREIMAGE_V1" liftingPlanPreimage
  emitBytes "pub" "PRINCIPAL_CAPACITY_LIFTING_PLAN_ID_V1" liftingPlanId
  emitSlice "BONDING_CURVE_FLOOR_DERIVATION_PREIMAGE_V1" curveDerivationReleasePreimage
  emitBytes "pub" "BONDING_CURVE_FLOOR_DERIVATION_ID_V1" curveDerivationReleaseId
  for field in layout do
    IO.println s!"pub const {Field.rustName field.spec.name}: usize = {field.offset};"
  IO.println s!"pub const MANIPULATION_FLOOR_V1_RESERVED_BYTES: usize = 5;"
  IO.println s!"pub const MANIPULATION_FLOOR_V1_TAIL_RESERVED_BYTES: usize = 8;"
  IO.println s!"pub const MANIPULATION_FLOOR_V1_CURVE_DERIVED_TAG: u8 = {FloorBasis.curveDerived.tag};"
  IO.println s!"pub const MANIPULATION_FLOOR_V1_OBSERVED_DEPTH_TAG: u8 = {FloorBasis.observedDepth.tag};"
  for field in tailLayout do
    IO.println s!"pub const {TailField.rustName field.spec.name}: usize = {field.offset};"
  IO.println
    s!"pub const SOURCE_CAPACITY_PRINCIPAL_TAIL_RESERVED_BYTES_V1: usize = 16;"
  IO.println
    s!"pub const CHAIN_STATE_DEFAULT_KAPPA_NUMERATOR_V1: u32 = {defaultKappa.numerator};"
  IO.println
    s!"pub const CHAIN_STATE_DEFAULT_KAPPA_DENOMINATOR_V1: u32 = {defaultKappa.denominator};"
  IO.println
    s!"pub const BONDING_CURVE_GRADUATION_FLOOR_LAMPORTS_V1: u64 = {graduationFloorLamports};"
  IO.println s!"pub const PRINCIPAL_ADMISSION_CASES_V1: [PrincipalAdmissionCaseV1; {admissionCases.length}] = ["
  for case in admissionCases do
    emitAdmission case
  IO.println "];"
  IO.println "#[cfg(test)]"
  IO.println "#[rustfmt::skip]"
  IO.println
    s!"pub(crate) const MANIPULATION_FLOOR_V1_REFUSAL_CORPUS: [(&[u8], u8); {refusalCorpus.length}] = ["
  for indexed in refusalCorpus.zipIdx do
    emitRefusal indexed.2 indexed.1
  IO.println "];"
  IO.println "#[cfg(test)]"
  emitBytes "pub(crate)" "MANIPULATION_FLOOR_V1_EXAMPLE" (encode exampleFloor)
