import DClutchSemantics.Codec
import DClutchSemantics.RationalTerminalHotV3Abi
import DClutchSemantics.TsEmit
import DClutchSemantics.RustEmit

open DClutch.RustEmit (rustByte emitBytesSkip emitSliceSkip)

/-! Emit the Rational terminal Hot V3 wallet ABI: `rust` (the default) prints
the terminal family's constants for `dclutch-rational-representation-v2-contract`;
`ts` prints the browser and SDK module.

The browser used to obtain these coordinates by running regular expressions
over TWO Lean-emitted Rust modules at once -- the Claims-child request layout
and the Hot specialization -- a mirror of a mirror that also had to re-spell
all fifty-three constant NAMES to find them, and pinned the request width as a
literal of its own.  Physical ABI v3 made the request header ACTION-CONDITIONAL,
so the TypeScript prints the common prefix once under class-free names and each
class's tail under that class's prefix; the terminal family's own coordinates
are printed in full from `emittedFields`, the same list the Rust arm iterates. -/

namespace Rust

open DClutch
open DClutch.RationalTerminalHotV3Abi

def run : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitRationalTerminalHotV3.lean; do not edit."
  IO.println s!"pub const RATIONAL_TERMINAL_HOT_VERSION_V3: u16 = {version};"
  IO.println s!"pub const RATIONAL_TERMINAL_HOT_REQUEST_BYTES_V3: usize = {requestBytes};"
  IO.println s!"pub const RATIONAL_TERMINAL_HOT_FIXED_ASSET_COUNT_V3: u32 = {fixedAssetCount};"
  emitSliceSkip "RATIONAL_TERMINAL_HOT_REQUEST_SCHEMA_PREIMAGE_V3" requestSchemaPreimage
  emitBytesSkip "RATIONAL_TERMINAL_HOT_REQUEST_SCHEMA_ID_V3" requestSchemaId
  IO.println s!"pub const RATIONAL_TERMINAL_HOT_MAGIC_V3: [u8; {familyMagic.length}] ="
  IO.println s!"    [{String.intercalate ", " (familyMagic.map rustByte)}];"
  for field in emittedFields do
    IO.println s!"pub const {familyName field}: usize = {requestOffset field};"
  IO.println s!"pub const RATIONAL_TERMINAL_HOT_ASSET_OFFSET_V3: usize = {assetStartOffset};"
  for field in DClutch.RationalRepresentationV2PhysicalAbi.AssetField.all do
    IO.println s!"pub const {familyAssetName field}: usize = {absoluteAssetOffset field};"

end Rust

namespace Ts

open DClutch.AbiSchema
open DClutch.TsEmit
open DClutch.RationalRepresentationV2PhysicalAbi
  (RequestField AssetField RequestClass Action CallerRole commonSchema classLayout
   classHeaderBytes commonPrefixBytes assetLayout assetBytes requestMagic)
open DClutch.RationalTerminalHotV3Abi
  (familyMagic familyName familyAssetName emittedFields requestOffset requestBytes
   fixedAssetCount assetStartOffset absoluteAssetOffset)

/-- A class tail constant, named exactly as the Rust twin names it. -/
def classTailOffsets (kind : RequestClass) : List String :=
  ((classLayout kind).drop commonSchema.length).map fun placed =>
    nat s!"{RequestClass.rustName kind}_{RequestField.rustName placed.spec.name}_V3" placed.offset

def run : IO Unit :=
  emit (header "EmitRationalTerminalHotV3.lean" "abi:rational-terminal-v3") [
    [ nat "PHYSICAL_ABI_VERSION_V3" DClutch.RationalRepresentationV2PhysicalAbi.version,
      nat "REQUEST_COMMON_PREFIX_BYTES_V3" commonPrefixBytes,
      nat "ASSET_BYTES_V3" assetBytes ]
      ++ (RequestClass.all.map fun kind =>
            nat s!"REQUEST_{RequestClass.rustName kind}_HEADER_BYTES_V3" (classHeaderBytes kind)),
    (specialize commonSchema).map fun placed =>
      nat s!"{RequestField.rustName placed.spec.name}_V3" placed.offset,
    (RequestClass.all.map classTailOffsets).flatten,
    assetLayout.map fun placed =>
      nat s!"{AssetField.rustName placed.spec.name}_V3" placed.offset,
    [ nat "ACTION_DENOMINATE" (Action.tag .denominate),
      nat "ACTION_RECONSTITUTE" (Action.tag .reconstitute),
      nat "ACTION_ISSUE_STRUCTURED" (Action.tag .issueStructured),
      nat "ACTION_UNWRAP_STRUCTURED" (Action.tag .unwrapStructured),
      nat "ACTION_REDEEM_TERMINAL" (Action.tag .redeemTerminal),
      nat "CALLER_ROLE_CORE" (CallerRole.tag .core),
      nat "CALLER_ROLE_TRADING" (CallerRole.tag .trading),
      nat "RATIONAL_TERMINAL_HOT_VERSION_V3"
        DClutch.RationalTerminalHotV3Abi.version,
      nat "RATIONAL_TERMINAL_HOT_REQUEST_BYTES_V3" requestBytes,
      nat "RATIONAL_TERMINAL_HOT_FIXED_ASSET_COUNT_V3" fixedAssetCount ]
      ++ (emittedFields.map fun field => nat (familyName field) (requestOffset field))
      ++ [ nat "RATIONAL_TERMINAL_HOT_ASSET_OFFSET_V3" assetStartOffset ]
      ++ (AssetField.all.map fun field =>
            nat (familyAssetName field) (absoluteAssetOffset field)),
    [ bytes "REQUEST_MAGIC_V2" requestMagic,
      bytes "RATIONAL_TERMINAL_HOT_MAGIC_V3" familyMagic ]
  ]

end Ts

def main (args : List String) : IO Unit :=
  match args with
  | [] | ["rust"] => Rust.run
  | ["ts"] => Ts.run
  | _ => throw (IO.userError "usage: lake env lean --run EmitRationalTerminalHotV3.lean [rust | ts]")
