import DClutchSemantics.CapabilityExecutionAbi
import DClutchSemantics.Codec
import DClutchSemantics.RustEmit

open DClutch.RustEmit (schemaByte emitBytes)

/-! Emit the Lean-owned fixed-role capability execution-selection layout. -/

open DClutch
open DClutch.AbiSchema
open DClutch.CapabilityExecutionAbi

def emitSchemaIdentity (preimageName idName preimage : String)
    (digest : List UInt8) : IO Unit := do
  IO.println s!"pub const {preimageName}: &[u8] = b\"{preimage}\";"
  IO.println s!"pub const {idName}: [u8; {digest.length}] = ["
  for line in List.range ((digest.length + 7) / 8) do
    let chunk := (digest.drop (line * 8)).take 8
    IO.println s!"    {String.intercalate ", " (chunk.map schemaByte)},"
  IO.println "];"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitCapabilityExecutionAbiRust.lean; do not edit."
  IO.println s!"pub const CAPABILITY_EXECUTION_SELECTION_BYTES_V1: usize = {bytes};"
  IO.println s!"pub const CAPABILITY_EXECUTION_SELECTION_SCHEMA_VERSION_V1: u16 = {schemaVersion};"
  IO.println s!"pub const CAPABILITY_EXECUTION_SELECTION_PROFILE_V1: u16 = {artifactProfile};"
  emitBytes "CAPABILITY_EXECUTION_SELECTION_MAGIC_V1" magic
  for field in layout do
    IO.println s!"pub const {Field.rustName field.spec.name}: usize = {field.offset};"
  emitSchemaIdentity "EXECUTION_RELEASE_SET_SCHEMA_RELEASE_PREIMAGE_V1" "EXECUTION_RELEASE_SET_SCHEMA_RELEASE_ID_V1"
    schemaReleasePreimage schemaReleaseId
