import DClutchSemantics.LiabilityBasisV2PriceGateAbi
import DClutchSemantics.Codec
import DClutchSemantics.RustEmit

open DClutch.RustEmit (rustBytes)

/-!
Emit the `DCLTPGT1` price-gate ABI constants into the crate that owns the live
basis wire.

# Why a second emitter rather than a second author

`BASIS_ABI_UNIFICATION_V1` §6.3 puts the degree-`≥ 2` price gate at **founding**,
which means the certificate has to be decodable from the crate Core links --
`dclutch-product-payoff-v2-codec`. It cannot be decoded through
`dclutch-liability-basis-v2-kernel`: under the option-D ruling that kernel is
retained as a *non-authoritative differential reference* only, and it is wired
as a **dev-dependency** of the codec precisely so it stays one ("linked into the
test binary and into no ELF"). Reaching into it from a founding route would make
it a live writer and break `O-005`.

So the certificate's decoder is ported, exactly as the de Boor evaluator was.
What must not be ported is the *specification*: §1.6.1 measured what happens
when one wire tag acquires four independent authors, and the answer was that the
on-chain one had no specification and the specified one had no guard.

This executable therefore emits the **same constants from the same Lean ABI
owner** (`DClutch.LiabilityBasisV2.PriceGate.PhysicalAbi`) into a second Rust
destination. The kernel's `generated_price_gate.rs` and the codec's
`generated_price_gate_v1.rs` are two emissions of one specification, each byte-
guarded, rather than two hand-kept copies that agree until they do not.

The corpora stay in the kernel. They are the differential reference's business,
and the codec consumes them across the dev-dependency edge in its own tests.
-/

open DClutch.LiabilityBasisV2.PriceGate
open DClutch.LiabilityBasisV2.PriceGate.PhysicalAbi

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitProductPriceGateV1AbiRust.lean; do not edit."
  IO.println s!"pub const PRICE_GATE_REQUEST_BYTES_V1: usize = {requestBytes};"
  IO.println s!"pub const PRICE_GATE_SCHEMA_VERSION_V1: u16 = {schemaVersion};"
  IO.println s!"pub const PRICE_GATE_PROFILE_V1: u16 = {profileTag};"
  IO.println s!"pub const PRICE_GATE_MAX_WIDTH_V1: usize = {maxWidth};"
  IO.println s!"pub const PRICE_GATE_MAX_ATOMS_V1: usize = {maxAtoms};"
  IO.println s!"pub const PRICE_GATE_MAGIC_OFFSET_V1: usize = {magicOffset};"
  IO.println s!"pub const PRICE_GATE_VERSION_OFFSET_V1: usize = {versionOffset};"
  IO.println s!"pub const PRICE_GATE_PROFILE_OFFSET_V1: usize = {profileOffset};"
  IO.println s!"pub const PRICE_GATE_SCALE_OFFSET_V1: usize = {scaleOffset};"
  IO.println s!"pub const PRICE_GATE_MASS_OFFSET_V1: usize = {massOffset};"
  IO.println s!"pub const PRICE_GATE_DEGREE_OFFSET_V1: usize = {degreeOffset};"
  IO.println s!"pub const PRICE_GATE_WIDTH_OFFSET_V1: usize = {widthOffset};"
  IO.println s!"pub const PRICE_GATE_ATOM_COUNT_OFFSET_V1: usize = {atomCountOffset};"
  IO.println s!"pub const PRICE_GATE_RESERVED_OFFSET_V1: usize = {reservedOffset};"
  IO.println s!"pub const PRICE_GATE_RESERVED_BYTES_V1: usize = {reservedBytes};"
  IO.println s!"pub const PRICE_GATE_PRICES_OFFSET_V1: usize = {pricesOffset};"
  IO.println s!"pub const PRICE_GATE_PRICE_BYTES_V1: usize = {priceBytes};"
  IO.println s!"pub const PRICE_GATE_WEIGHTS_OFFSET_V1: usize = {weightsOffset};"
  IO.println s!"pub const PRICE_GATE_WEIGHT_BYTES_V1: usize = {weightBytes};"
  IO.println s!"pub const PRICE_GATE_NUMERATORS_OFFSET_V1: usize = {numeratorsOffset};"
  IO.println s!"pub const PRICE_GATE_NUMERATOR_BYTES_V1: usize = {numeratorBytes};"
  IO.println s!"pub const PRICE_GATE_DENOMINATORS_OFFSET_V1: usize = {denominatorsOffset};"
  IO.println s!"pub const PRICE_GATE_DENOMINATOR_BYTES_V1: usize = {denominatorBytes};"
  IO.println s!"pub const PRICE_GATE_EXEMPT_DEGREE_V1: u8 = {exemptDegree};"
  IO.println s!"pub const PRICE_GATE_MAGIC_V1: [u8; 8] = {rustBytes requestMagic};"
