import DClutchSemantics.Codec
import DClutchSemantics.RealmPositionAbi
import DClutchSemantics.TsEmit
import DClutchSemantics.RustEmit

open DClutch.RustEmit (schemaByte)

/-! Emit the Lean-owned Realm byte ABI, and the Position seed domain, to both
backends from one program: `rust` (the default) prints the crate's constants,
`ts` the browser and SDK module.  The Position RECORD is not emitted on
either: it was banished with the DCLTCAT1 stratum and the emission outlived
it, which is what left the browser's explorer holding a decoder arm for a
record nothing writes. -/

namespace Rust

open DClutch.RealmPositionAbi

def emitSchemaIdentity (preimageName idName preimage : String)
    (digest : List UInt8) : IO Unit := do
  IO.println s!"pub const {preimageName}: &[u8] = b\"{preimage}\";"
  IO.println s!"pub const {idName}: [u8; {digest.length}] = ["
  for line in List.range ((digest.length + 7) / 8) do
    let chunk := (digest.drop (line * 8)).take 8
    IO.println s!"    {String.intercalate ", " (chunk.map schemaByte)},"
  IO.println "];"

def run : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitRealmPositionAbi.lean; do not edit."
  IO.println s!"pub const REALM_BYTES_V1: usize = {realmBytes};"
  IO.println s!"pub const REALM_MAGIC_V1: [u8; 8] = *b\"{realmMagic}\";"
  IO.println s!"pub const REALM_SCHEMA_VERSION_V1: u16 = {realmSchemaVersion};"
  IO.println s!"pub const REALM_PDA_DOMAIN_V1: &[u8] = b\"{realmPdaDomain}\";"
  IO.println s!"pub const REALM_RESERVED_BYTES_V1: usize = {realmReservedBytes};"
  for field in realmLayout do
    IO.println s!"pub const {RealmField.constantName field.spec.name}: usize = {field.offset};"
  IO.println s!"pub const POSITION_PDA_DOMAIN_V1: &[u8] = b\"{positionPdaDomain}\";"
  emitSchemaIdentity "REALM_SCHEMA_RELEASE_PREIMAGE_V1" "REALM_SCHEMA_RELEASE_ID_V1"
    schemaReleasePreimage schemaReleaseId

end Rust

namespace Ts

open DClutch.RealmPositionAbi
open DClutch.TsEmit

def run : IO Unit :=
  emit (header "EmitRealmPositionAbi.lean" "abi:realm-position") [
    [ nat "SVM_MAX_SEED_BYTES" svmMaxSeedBytes ],
    [ ascii "REALM_MAGIC_V1" realmMagic,
      nat "REALM_SCHEMA_VERSION_V1" realmSchemaVersion,
      nat "REALM_BYTES_V1" realmBytes,
      nat "REALM_RESERVED_BYTES_V1" realmReservedBytes,
      domain "REALM_PDA_DOMAIN_V1" realmPdaDomain ],
    offsets RealmField.constantName realmLayout,
    [ domain "POSITION_PDA_DOMAIN_V1" positionPdaDomain ]
  ]

end Ts

def main (args : List String) : IO Unit :=
  match args with
  | [] | ["rust"] => Rust.run
  | ["ts"] => Ts.run
  | _ => throw (IO.userError "usage: lake env lean --run EmitRealmPositionAbi.lean [rust | ts]")
