import DClutchSemantics.GeneralControllerRequestV2
import DClutchSemantics.GeneralControllerRequestV3
import DClutchSemantics.Codec
import DClutchSemantics.RustEmit

open DClutch.RustEmit (rustByte)

/-! Emit both generations of the 64-byte General controller request.  V2 is
the settlement wire (`DCGREQ02`) and V3 the front-half wire (`DCGREQ03`); the
crate speaks both, so one emitter prints both into one module. -/

open DClutch DClutch.General

def emitBytes (name : String) (bytes : List UInt8) : IO Unit := do
  IO.println s!"pub(crate) const {name}: [u8; {bytes.length}] = ["
  IO.println s!"    {String.intercalate ", " (bytes.map rustByte)},"
  IO.println "];"

def emitCoordinate {α : Type} [DecidableEq α]
    (layout : List (AbiSchema.PlacedField α)) (name : String) (field : α)
    (width : Bool := false) : IO Unit := do
  let (offset, bytes) := (AbiSchema.coordinate? field layout).getD (0, 0)
  IO.println s!"pub(crate) const {name}_OFFSET: usize = {offset};"
  if width then IO.println s!"pub(crate) const {name}_BYTES: usize = {bytes};"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitGeneralControllerRequestV3Rust.lean; do not edit."
  IO.println s!"pub(crate) const REQUEST_V2_ABI_VERSION: u16 = {ControllerRequestV2.abiVersion};"
  IO.println s!"pub(crate) const REQUEST_V2_BYTES: usize = {ControllerRequestV2.requestBytes};"
  emitBytes "REQUEST_V2_MAGIC" ControllerRequestV2.requestMagic
  let v2 := ControllerRequestV2.requestLayout
  emitCoordinate v2 "REQUEST_V2_ACTION" .action
  emitCoordinate v2 "REQUEST_V2_MANIFEST_ORDER" .manifestOrderIndex
  emitCoordinate v2 "REQUEST_V2_RESERVED_A" .reservedA (width := true)
  emitCoordinate v2 "REQUEST_V2_EXPECTED_REVISION" .expectedRevision
  emitCoordinate v2 "REQUEST_V2_CANDIDATE_ID" .candidateId
  emitCoordinate v2 "REQUEST_V2_PAGE_INDEX" .pageIndex
  emitCoordinate v2 "REQUEST_V2_EXECUTION_INDEX" .executionIndex
  emitCoordinate v2 "REQUEST_V2_STATE_BUMP" .stateBump
  emitCoordinate v2 "REQUEST_V2_TERMINAL_BUMP" .terminalRecordBump
  emitCoordinate v2 "REQUEST_V2_RESERVED_B" .reservedB
  IO.println s!"pub(crate) const REQUEST_V3_ABI_VERSION: u16 = {ControllerRequestV3.abiVersion};"
  IO.println s!"pub(crate) const REQUEST_V3_BYTES: usize = {ControllerRequestV3.requestBytes};"
  emitBytes "REQUEST_V3_MAGIC" ControllerRequestV3.requestMagic
  let v3 := ControllerRequestV3.requestLayout
  emitCoordinate v3 "REQUEST_V3_ACTION" .action
  emitCoordinate v3 "REQUEST_V3_MANIFEST_ORDER" .manifestOrderIndex
  emitCoordinate v3 "REQUEST_V3_EXPECTED_REVISION" .expectedRevision
  emitCoordinate v3 "REQUEST_V3_SUBJECT_ID" .subjectId
  emitCoordinate v3 "REQUEST_V3_PAGE_INDEX" .pageIndex
  emitCoordinate v3 "REQUEST_V3_EXECUTION_INDEX" .executionIndex
  emitCoordinate v3 "REQUEST_V3_PRIMARY_BUMP" .primaryStateBump
  emitCoordinate v3 "REQUEST_V3_SECONDARY_BUMP" .secondaryStateBump
  emitCoordinate v3 "REQUEST_V3_RESULT_BUMP" .resultStateBump
