import DClutchSemantics.SeriesAbi

open DClutch
open DClutch.Series
open DClutch.Series.Abi

def rustByte (byte : UInt8) : String := s!"0x{Codec.byteHex byte}"

def emitBytes (name : String) (bytes : List UInt8) : IO Unit := do
  IO.println s!"pub(crate) const {name}: [u8; {bytes.length}] = ["
  for line in List.range ((bytes.length + 15) / 16) do
    let chunk := (bytes.drop (line * 16)).take 16
    IO.println s!"    {String.intercalate ", " (chunk.map rustByte)},"
  IO.println "];"

def emitNat (name : String) (value : Nat) : IO Unit :=
  IO.println s!"pub(crate) const {name}: usize = {value};"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitSeriesAbiRust.lean; do not edit."
  IO.println s!"pub(crate) const ABI_VERSION: u16 = {version};"
  emitBytes "TEMPLATE_MAGIC" templateMagic
  emitBytes "SERIES_MAGIC" seriesMagic
  emitBytes "TICKET_MAGIC" ticketMagic
  emitBytes "RECEIPT_MAGIC" receiptMagic
  emitBytes "REQUEST_MAGIC" requestMagic
  emitNat "TEMPLATE_BYTES" templateBytes
  emitNat "SERIES_BYTES" seriesBytes
  emitNat "TICKET_BYTES" ticketBytes
  emitNat "RECEIPT_BYTES" receiptBytes
  emitNat "REQUEST_BYTES" requestBytes
  emitNat "HEADER_VERSION_OFFSET" headerVersionOffset
  emitNat "HEADER_TAG_OFFSET" headerTagOffset
  emitNat "HEADER_RESERVED_OFFSET" headerReservedOffset
  emitNat "TEMPLATE_TEMPLATE_ID_OFFSET" TemplateOffset.templateId
  emitNat "TEMPLATE_REALM_ID_OFFSET" TemplateOffset.realmId
  emitNat "TEMPLATE_PRODUCT_ID_OFFSET" TemplateOffset.productId
  emitNat "TEMPLATE_RELEASE_SET_ID_OFFSET" TemplateOffset.releaseSetId
  emitNat "TEMPLATE_SERIES_REFUND_OWNER_OFFSET" TemplateOffset.seriesRefundOwner
  emitNat "TEMPLATE_OUTCOME_COUNT_OFFSET" TemplateOffset.outcomeCount
  emitNat "TEMPLATE_OCCURRENCE_COUNT_OFFSET" TemplateOffset.occurrenceCount
  emitNat "TEMPLATE_FIRST_SLOT_OFFSET" TemplateOffset.firstOccurrenceSlot
  emitNat "TEMPLATE_PERIOD_SLOTS_OFFSET" TemplateOffset.periodSlots
  emitNat "TEMPLATE_RETRY_WINDOW_OFFSET" TemplateOffset.retryWindowSlots
  emitNat "TEMPLATE_SEED_QUANTITY_OFFSET" TemplateOffset.seedQuantity
  emitNat "TEMPLATE_MARKET_RENT_OFFSET" TemplateOffset.marketRent
  emitNat "TEMPLATE_CAPABILITY_RENT_OFFSET" TemplateOffset.capabilityRent
  emitNat "TEMPLATE_FOUNDING_WORK_OFFSET" TemplateOffset.foundingWork
  emitNat "TEMPLATE_CLOSE_RENT_OFFSET" TemplateOffset.seriesCloseRent
  emitNat "SERIES_SERIES_ID_OFFSET" SeriesOffset.seriesId
  emitNat "SERIES_TEMPLATE_ID_OFFSET" SeriesOffset.templateId
  emitNat "SERIES_NEXT_OCCURRENCE_OFFSET" SeriesOffset.nextOccurrence
  emitNat "SERIES_RESERVED_BODY_OFFSET" SeriesOffset.reservedBody
  emitNat "SERIES_REVISION_OFFSET" SeriesOffset.revision
  emitNat "SERIES_CLOSE_RENT_OFFSET" SeriesOffset.closeRent
  emitNat "TICKET_TICKET_ID_OFFSET" TicketOffset.ticketId
  emitNat "TICKET_TEMPLATE_ID_OFFSET" TicketOffset.templateId
  emitNat "TICKET_FOUNDER_OFFSET" TicketOffset.founder
  emitNat "TICKET_REFUND_OWNER_OFFSET" TicketOffset.refundOwner
  emitNat "TICKET_MARKET_ID_OFFSET" TicketOffset.committedMarketId
  emitNat "TICKET_OCCURRENCE_OFFSET" TicketOffset.occurrence
  emitNat "TICKET_RESERVED_BODY_OFFSET" TicketOffset.reservedBody
  emitNat "TICKET_REVISION_OFFSET" TicketOffset.revision
  emitNat "TICKET_HOARD_OFFSET" TicketOffset.hoardPrincipal
  emitNat "TICKET_MARKET_RENT_OFFSET" TicketOffset.marketRent
  emitNat "TICKET_CAPABILITY_RENT_OFFSET" TicketOffset.capabilityRent
  emitNat "TICKET_FOUNDING_WORK_OFFSET" TicketOffset.foundingWork
  emitNat "RECEIPT_REGISTRY_PROGRAM_OFFSET" ReceiptOffset.registryProgram
  emitNat "RECEIPT_RELEASE_SET_ID_OFFSET" ReceiptOffset.releaseSetId
  emitNat "RECEIPT_OBSERVED_PROGRAM_OFFSET" ReceiptOffset.observedProgram
  emitNat "RECEIPT_ARTIFACT_RELEASE_OFFSET" ReceiptOffset.artifactRelease
  emitNat "RECEIPT_SEMANTIC_RELEASE_OFFSET" ReceiptOffset.semanticRelease
  emitNat "REQUEST_NOW_SLOT_OFFSET" RequestOffset.nowSlot
  emitNat "REQUEST_SERIES_REVISION_OFFSET" RequestOffset.expectedSeriesRevision
  emitNat "REQUEST_TICKET_REVISION_OFFSET" RequestOffset.expectedTicketRevision
  emitNat "REQUEST_WORK_RECIPIENT_OFFSET" RequestOffset.workRecipient
  IO.println s!"pub(crate) const CORE_ROLE_TAG: u8 = {coreRoleTag};"
  IO.println s!"pub(crate) const RECEIPT_AUTHENTICATED_FLAGS: u8 = {receiptAuthenticatedFlags};"
  IO.println s!"pub(crate) const ACTION_CONSUME: u8 = {actionConsume};"
  IO.println s!"pub(crate) const ACTION_EXPIRE: u8 = {actionExpire};"
  IO.println s!"pub(crate) const ACTION_CLOSE: u8 = {actionClose};"
  IO.println s!"pub(crate) const PHASE_ACTIVE: u8 = {phaseActive};"
  IO.println s!"pub(crate) const PHASE_TERMINAL: u8 = {phaseTerminal};"
  IO.println s!"pub(crate) const PHASE_CLOSED: u8 = {phaseClosed};"
  IO.println s!"pub(crate) const TICKET_READY: u8 = {ticketReady};"
  IO.println s!"pub(crate) const TICKET_CONSUMED: u8 = {ticketConsumed};"
  IO.println s!"pub(crate) const TICKET_EXPIRED: u8 = {ticketExpired};"
  IO.println ""
  IO.println "pub(crate) fn schedule_window(first: u64, period: u64, occurrence: u32, retry: u64) -> Option<(u64, u64)> {"
  IO.println "    let due = period.checked_mul(u64::from(occurrence))?.checked_add(first)?;"
  IO.println "    Some((due, due.checked_add(retry)?))"
  IO.println "}"
  IO.println ""
  IO.println "pub(crate) const fn next_series_phase(next: u32, count: u32) -> Option<u8> {"
  IO.println "    if next == count { Some(PHASE_TERMINAL) } else if next < count { Some(PHASE_ACTIVE) } else { None }"
  IO.println "}"
  IO.println ""
  IO.println "#[cfg(test)]"
  emitBytes "TEMPLATE_EXAMPLE" (encodeTemplate Examples.template)
  IO.println "#[cfg(test)]"
  emitBytes "SERIES_EXAMPLE" (encodeSeries Examples.series0)
  IO.println "#[cfg(test)]"
  emitBytes "TICKET_EXAMPLE" (encodeTicket Examples.ticket0)
  IO.println "#[cfg(test)]"
  emitBytes "RECEIPT_EXAMPLE" (encodeReceipt Examples.releaseAdmission.receipt)
  IO.println "#[cfg(test)]"
  emitBytes "REQUEST_EXAMPLE" (encodeRequest Examples.consume0)
