import DClutchSemantics.DirectLifecycleAbi

open DClutch
open DClutch.DirectLifecycleAbi

def rustByte (byte : UInt8) : String := s!"0x{Codec.byteHex byte}"

def emitRustBytes (visibility name : String) (bytes : List UInt8) : IO Unit := do
  IO.println s!"{visibility} const {name}: [u8; {bytes.length}] = ["
  for line in List.range ((bytes.length + 15) / 16) do
    let chunk := (bytes.drop (line * 16)).take 16
    IO.println s!"    {String.intercalate ", " (chunk.map rustByte)},"
  IO.println "];"

def decodeExpression (field : StateField) : String :=
  let offset := s!"$crate::generated_lifecycle::{StateField.rustName field}"
  match field with
  | .phase => s!"$crate::byte($input, {offset})?"
  | .controller | .maker => s!"$crate::array($input, {offset})?"
  | .intent =>
      s!"$crate::CompactIntentV1::decode($crate::slice($input, {offset}, $crate::COMPACT_INTENT_BYTES)?)?"
  | .remaining | .sequence => s!"$crate::u64_at($input, {offset})?"
  | .magic | .version | .reserved => "unreachable!()"

def encodeStatement (field : StateField) : String :=
  let offset := s!"$crate::generated_lifecycle::{StateField.rustName field}"
  let value := s!"$value.{StateField.rustFieldName field}"
  match field with
  | .phase => s!"$crate::put_byte(&mut $output, {offset}, {value})?;"
  | .controller | .maker => s!"$crate::put(&mut $output, {offset}, &{value})?;"
  | .intent => s!"$crate::put(&mut $output, {offset}, &{value}.encode()?)?;"
  | .remaining | .sequence =>
      s!"$crate::put(&mut $output, {offset}, &{value}.to_le_bytes())?;"
  | .magic | .version | .reserved => "unreachable!();"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitDirectLifecycleAbiRust.lean; do not edit."
  IO.println s!"pub(crate) const REGISTERED_STATE_BYTES_VALUE: usize = {stateBytes};"
  IO.println s!"pub(crate) const REGISTERED_STATE_ABI_VERSION: u16 = {version};"
  emitRustBytes "pub(crate)" "REGISTERED_STATE_MAGIC_BYTES" stateMagic
  for field in StateField.all do
    IO.println s!"pub(crate) const {StateField.rustName field}: usize = {StateField.offset field};"
  IO.println ""
  IO.println "macro_rules! decode_registered_state_fields {"
  IO.println "    ($input:expr) => {"
  IO.println "        $crate::RegisteredIntentStateV1 {"
  for field in StateField.dynamic do
    IO.println s!"            {StateField.rustFieldName field}: {decodeExpression field},"
  IO.println "        }"
  IO.println "    };"
  IO.println "}"
  IO.println "pub(crate) use decode_registered_state_fields;"
  IO.println ""
  IO.println "macro_rules! encode_registered_state_fields {"
  IO.println "    ($output:ident, $value:ident) => {{"
  for field in StateField.dynamic do
    IO.println s!"        {encodeStatement field}"
  IO.println "    }};"
  IO.println "}"
  IO.println "pub(crate) use encode_registered_state_fields;"
  IO.println ""
  for register in DirectLifecycleProgram.ScalarSlot.runtimeRegisters do
    IO.println s!"pub(crate) const {DirectLifecycleProgram.ScalarSlot.rustName register}: usize = {DirectLifecycleProgram.ScalarSlot.index register};"
  IO.println s!"pub(crate) const REGISTERED_INPUT_COUNT: usize = {DirectLifecycleProgram.ScalarSlot.inputs.length};"
  IO.println "macro_rules! registered_fill_inputs {"
  IO.println "    ("
  for register in DirectLifecycleProgram.ScalarSlot.inputs do
    let field := DirectLifecycleProgram.ScalarSlot.rustFieldName register
    IO.println s!"        {field}: ${field}:expr,"
  IO.println "    ) => {"
  IO.println "        ["
  for register in DirectLifecycleProgram.ScalarSlot.inputs do
    let field := DirectLifecycleProgram.ScalarSlot.rustFieldName register
    IO.println s!"            ${field},"
  IO.println "        ]"
  IO.println "    };"
  IO.println "}"
  IO.println "pub(crate) use registered_fill_inputs;"
  IO.println ""
  emitRustBytes "pub(crate)" "REGISTERED_FILL_PROGRAM"
    (TransitionVM.Codec.encodeProgram DirectLifecycleProgram.program)
  IO.println ""
  IO.println "#[cfg(test)]"
  emitRustBytes "pub(crate)" "REGISTERED_STATE_EXAMPLE"
    (encodeRegisteredIntentStateV1 Examples.registeredState)
