import DClutchSemantics.DirectLifecycleAbi
import DClutchSemantics.RegisteredControllerAbi
import DClutchSemantics.TsEmit
import DClutchSemantics.RustEmit

open DClutch.RustEmit (emitRustBytes)

/-! Emit the registered Direct ABI -- the persisted lifecycle state and the
controller, create, terminal and retire records -- as three modules from one
program: `lifecycle` and `controller` are the two Rust modules
`crates/dclutch-direct-codec` checks in, `ts` the browser and SDK module.

The TypeScript half retired `generate-registered-direct.mjs`, which scraped
the two Lean-emitted Rust modules for sixty-one values and had to name all
sixty-one to find them.  Its six fixtures are whole encoded records produced
by Lean's own encoders; the scraper could copy those bytes only because the
Rust emitter had written them behind `#[cfg(test)]`.  `REGISTERED_TERMINAL_CANCEL`
and `REGISTERED_TERMINAL_EXPIRE` derive from `Terminal.actionTag` on every
target, where the Rust once printed `0` and `1` as its own literals. -/

namespace Lifecycle

open DClutch
open DClutch.DirectLifecycleAbi

def decodeExpression (field : StateField) : String :=
  let offset := s!"$crate::generated_lifecycle::{StateField.rustName field}"
  match field with
  | .phase => s!"$crate::byte($input, {offset})?"
  | .controller | .maker => s!"$crate::array($input, {offset})?"
  | .intent =>
      s!"$crate::CompactIntentV1::decode($crate::slice($input, {offset}, $crate::COMPACT_INTENT_BYTES)?)?"
  | .remaining | .sequence => s!"$crate::u64_at($input, {offset})?"
  | .magic | .version | .reserved => "unreachable!()"

def encodeStatement (field : StateField) : String :=
  let offset := s!"$crate::generated_lifecycle::{StateField.rustName field}"
  let value := s!"$value.{StateField.rustFieldName field}"
  match field with
  | .phase => s!"$crate::put_byte(&mut $output, {offset}, {value})?;"
  | .controller | .maker => s!"$crate::put(&mut $output, {offset}, &{value})?;"
  | .intent => s!"$crate::put(&mut $output, {offset}, &{value}.encode()?)?;"
  | .remaining | .sequence =>
      s!"$crate::put(&mut $output, {offset}, &{value}.to_le_bytes())?;"
  | .magic | .version | .reserved => "unreachable!();"

def run : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitRegisteredDirect.lean; do not edit."
  IO.println s!"pub(crate) const REGISTERED_STATE_BYTES_VALUE: usize = {stateBytes};"
  IO.println s!"pub(crate) const REGISTERED_STATE_ABI_VERSION: u16 = {version};"
  emitRustBytes "pub(crate)" "REGISTERED_STATE_MAGIC_BYTES" stateMagic
  for field in StateField.all do
    IO.println s!"pub(crate) const {StateField.rustName field}: usize = {StateField.offset field};"
  IO.println ""
  IO.println "macro_rules! decode_registered_state_fields {"
  IO.println "    ($input:expr) => {"
  IO.println "        $crate::RegisteredIntentStateV1 {"
  for field in StateField.dynamic do
    IO.println s!"            {StateField.rustFieldName field}: {decodeExpression field},"
  IO.println "        }"
  IO.println "    };"
  IO.println "}"
  IO.println "pub(crate) use decode_registered_state_fields;"
  IO.println ""
  IO.println "macro_rules! encode_registered_state_fields {"
  IO.println "    ($output:ident, $value:ident) => {{"
  for field in StateField.dynamic do
    IO.println s!"        {encodeStatement field}"
  IO.println "    }};"
  IO.println "}"
  IO.println "pub(crate) use encode_registered_state_fields;"
  IO.println ""
  for register in DirectLifecycleProgram.ScalarSlot.runtimeRegisters do
    IO.println s!"pub(crate) const {DirectLifecycleProgram.ScalarSlot.rustName register}: usize = {DirectLifecycleProgram.ScalarSlot.index register};"
  IO.println s!"pub(crate) const REGISTERED_INPUT_COUNT: usize = {DirectLifecycleProgram.ScalarSlot.inputs.length};"
  IO.println "macro_rules! registered_fill_inputs {"
  IO.println "    ("
  for register in DirectLifecycleProgram.ScalarSlot.inputs do
    let field := DirectLifecycleProgram.ScalarSlot.rustFieldName register
    IO.println s!"        {field}: ${field}:expr,"
  IO.println "    ) => {"
  IO.println "        ["
  for register in DirectLifecycleProgram.ScalarSlot.inputs do
    let field := DirectLifecycleProgram.ScalarSlot.rustFieldName register
    IO.println s!"            ${field},"
  IO.println "        ]"
  IO.println "    };"
  IO.println "}"
  IO.println "pub(crate) use registered_fill_inputs;"
  IO.println ""
  emitRustBytes "pub(crate)" "REGISTERED_FILL_PROGRAM"
    (TransitionVM.Codec.encodeProgram DirectLifecycleProgram.program)
  IO.println ""
  IO.println "#[cfg(test)]"
  emitRustBytes "pub(crate)" "REGISTERED_STATE_EXAMPLE"
    (encodeRegisteredIntentStateV1 Examples.registeredState)

end Lifecycle

namespace Controller

open DClutch
open DClutch.Direct.RegisteredControllerAbi

def run : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitRegisteredDirect.lean; do not edit."
  IO.println s!"pub(crate) const REGISTERED_CONTROLLER_BYTES_VALUE: usize = {bytes};"
  IO.println s!"pub(crate) const REGISTERED_CONTROLLER_ABI_VERSION: u16 = {version};"
  emitRustBytes "pub(crate)" "REGISTERED_CONTROLLER_MAGIC_BYTES" magic
  for field in Field.all do
    IO.println s!"pub(crate) const {Field.rustName field}: usize = {Field.offset field};"
  IO.println s!"pub(crate) const REGISTERED_CLAIM_FILL_BYTES_VALUE: usize = {DClutch.Direct.RegisteredPhysical.instructionBytes};"
  IO.println s!"pub(crate) const REGISTERED_CLAIM_FILL_OFFSET: usize = 8;"
  emitRustBytes "pub(crate)" "REGISTERED_CLAIM_FILL_TEMPLATE"
    (DClutch.Direct.RegisteredPhysical.encodeInstruction 0)
  IO.println ""
  IO.println "#[cfg(test)]"
  emitRustBytes "pub(crate)" "REGISTERED_CONTROLLER_EXAMPLE"
    (encode exampleInstruction)
  IO.println ""
  IO.println s!"pub(crate) const REGISTERED_CREATE_BYTES_VALUE: usize = {Registration.bytes};"
  IO.println s!"pub(crate) const REGISTERED_CREATE_ABI_VERSION: u16 = {Registration.version};"
  emitRustBytes "pub(crate)" "REGISTERED_CREATE_MAGIC_BYTES" Registration.magic
  for field in Registration.Field.all do
    IO.println s!"pub(crate) const {Registration.Field.rustName field}: usize = {Registration.Field.offset field};"
  IO.println ""
  IO.println "#[cfg(test)]"
  emitRustBytes "pub(crate)" "REGISTERED_CREATE_EXAMPLE"
    (Registration.encode Registration.exampleInstruction)
  IO.println ""
  IO.println s!"pub(crate) const REGISTERED_TERMINAL_BYTES_VALUE: usize = {Terminal.bytes};"
  IO.println s!"pub(crate) const REGISTERED_TERMINAL_ABI_VERSION: u16 = {Terminal.version};"
  emitRustBytes "pub(crate)" "REGISTERED_TERMINAL_MAGIC_BYTES" Terminal.magic
  for field in Terminal.Field.all do
    IO.println s!"pub(crate) const {Terminal.Field.rustName field}: usize = {Terminal.Field.offset field};"
  IO.println s!"pub(crate) const REGISTERED_TERMINAL_CANCEL: u8 = {Terminal.actionTag .cancel};"
  IO.println s!"pub(crate) const REGISTERED_TERMINAL_EXPIRE: u8 = {Terminal.actionTag .expire};"
  emitRustBytes "pub(crate)" "REGISTERED_CLAIM_CANCEL_TEMPLATE"
    (DClutch.Direct.RegisteredPhysical.encodeTerminalInstruction .cancel 0)
  emitRustBytes "pub(crate)" "REGISTERED_CLAIM_EXPIRE_TEMPLATE"
    (DClutch.Direct.RegisteredPhysical.encodeTerminalInstruction .expire 0)
  IO.println "pub(crate) const REGISTERED_CLAIM_TERMINAL_SEQUENCE_OFFSET: usize = 8;"
  IO.println ""
  IO.println "#[cfg(test)]"
  emitRustBytes "pub(crate)" "REGISTERED_TERMINAL_CANCEL_EXAMPLE"
    (Terminal.encode Terminal.exampleCancel)
  IO.println "#[cfg(test)]"
  emitRustBytes "pub(crate)" "REGISTERED_TERMINAL_EXPIRE_EXAMPLE"
    (Terminal.encode Terminal.exampleExpire)
  IO.println ""
  IO.println s!"pub(crate) const REGISTERED_RETIRE_BYTES_VALUE: usize = {Retirement.bytes};"
  IO.println s!"pub(crate) const REGISTERED_RETIRE_ABI_VERSION: u16 = {Retirement.version};"
  emitRustBytes "pub(crate)" "REGISTERED_RETIRE_MAGIC_BYTES" Retirement.magic
  for field in Retirement.Field.all do
    IO.println s!"pub(crate) const {Retirement.Field.rustName field}: usize = {Retirement.Field.offset field};"
  IO.println ""
  IO.println "#[cfg(test)]"
  emitRustBytes "pub(crate)" "REGISTERED_RETIRE_EXAMPLE"
    (Retirement.encode Retirement.exampleInstruction)

end Controller

namespace Ts

open DClutch.AbiSchema
open DClutch.TsEmit
open DClutch.DirectLifecycleAbi hiding version
open DClutch.Direct.RegisteredControllerAbi hiding magic version bytes

def run : IO Unit :=
  emit (header "EmitRegisteredDirect.lean" "abi:registered") [
    [ nat "REGISTERED_STATE_BYTES_VALUE" stateBytes,
      nat "REGISTERED_STATE_ABI_VERSION" DClutch.DirectLifecycleAbi.version ]
      ++ offsets StateField.rustName stateLayout
      ++ [ nat "REGISTERED_CONTROLLER_BYTES_VALUE"
             DClutch.Direct.RegisteredControllerAbi.bytes,
           nat "REGISTERED_CONTROLLER_ABI_VERSION"
             DClutch.Direct.RegisteredControllerAbi.version ]
      ++ offsets Field.rustName layout
      ++ [ nat "REGISTERED_CREATE_BYTES_VALUE" Registration.bytes,
           nat "REGISTERED_CREATE_ABI_VERSION" Registration.version ]
      ++ offsets Registration.Field.rustName Registration.layout
      ++ [ nat "REGISTERED_TERMINAL_BYTES_VALUE" Terminal.bytes,
           nat "REGISTERED_TERMINAL_ABI_VERSION" Terminal.version ]
      ++ offsets Terminal.Field.rustName Terminal.layout
      ++ [ nat "REGISTERED_TERMINAL_CANCEL" (Terminal.actionTag .cancel).toNat,
           nat "REGISTERED_TERMINAL_EXPIRE" (Terminal.actionTag .expire).toNat,
           nat "REGISTERED_RETIRE_BYTES_VALUE" Retirement.bytes,
           nat "REGISTERED_RETIRE_ABI_VERSION" Retirement.version ]
      ++ offsets Retirement.Field.rustName Retirement.layout,
    bytesBlock "REGISTERED_STATE_MAGIC_BYTES" stateMagic
      ++ bytesBlock "REGISTERED_STATE_EXAMPLE"
           (encodeRegisteredIntentStateV1
             DClutch.DirectLifecycleAbi.Examples.registeredState)
      ++ bytesBlock "REGISTERED_CONTROLLER_MAGIC_BYTES"
           DClutch.Direct.RegisteredControllerAbi.magic
      ++ bytesBlock "REGISTERED_CONTROLLER_EXAMPLE" (encode exampleInstruction)
      ++ bytesBlock "REGISTERED_CREATE_MAGIC_BYTES" Registration.magic
      ++ bytesBlock "REGISTERED_CREATE_EXAMPLE"
           (Registration.encode Registration.exampleInstruction)
      ++ bytesBlock "REGISTERED_TERMINAL_MAGIC_BYTES" Terminal.magic
      ++ bytesBlock "REGISTERED_TERMINAL_CANCEL_EXAMPLE"
           (Terminal.encode Terminal.exampleCancel)
      ++ bytesBlock "REGISTERED_TERMINAL_EXPIRE_EXAMPLE"
           (Terminal.encode Terminal.exampleExpire)
      ++ bytesBlock "REGISTERED_RETIRE_MAGIC_BYTES" Retirement.magic
      ++ bytesBlock "REGISTERED_RETIRE_EXAMPLE"
           (Retirement.encode Retirement.exampleInstruction)
  ]

end Ts

def main (args : List String) : IO Unit :=
  match args with
  | ["lifecycle"] => Lifecycle.run
  | ["controller"] => Controller.run
  | ["ts"] => Ts.run
  | _ => throw (IO.userError "usage: lake env lean --run EmitRegisteredDirect.lean [lifecycle | controller | ts]")
