import DClutchSemantics.GeneralV5Assurance

/-! Emit the General V5 selection decision corpus.

Vectors, not the rule: `consider_verified_candidate_v2` stays a hand-written
fold over a persisted cursor, and this is what makes it answerable to
`GeneralV5Assurance.lean`. Each row carries what the runtime reads -- claim
banks, aggregate quote fields, filled lots, a little-endian content identity --
and what Lean decides from them. -/

open DClutch.General
open DClutch.General.V5Assurance

/-- One `Nat` content identity as the runtime's little-endian 32-byte array. -/
def leBytes32 (value : Nat) : String :=
  "[" ++ String.intercalate ", "
    ((List.range 32).map (fun index => toString (value / (256 ^ index) % 256))) ++ "]"

def natSlice (values : List Nat) : String :=
  "&[" ++ String.intercalate ", " (values.map toString) ++ "]"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitGeneralSelectionDecisionCorpusRust.lean; do not edit."
  IO.println "/// One submitted certificate exactly as the runtime selection cursor reads it."
  IO.println "#[derive(Clone, Copy, Debug, Eq, PartialEq)]"
  IO.println "pub struct GeneralSelectionSubmissionV1 {"
  IO.println "    /// Immutable Candidate content identity, little-endian."
  IO.println "    pub candidate_id: [u8; 32],"
  IO.println "    /// Candidate-wide filled-lots objective."
  IO.println "    pub filled_lots: u64,"
  IO.println "    /// Per-outcome claim inputs the certificate collects."
  IO.println "    pub claim_inputs: &'static [u64],"
  IO.println "    /// Per-outcome claim outputs the certificate distributes."
  IO.println "    pub claim_outputs: &'static [u64],"
  IO.println "    /// Exact aggregate quote debit."
  IO.println "    pub quote_debit: u64,"
  IO.println "    /// Exact aggregate quote credit."
  IO.println "    pub quote_credit: u64,"
  IO.println "    /// Quote remainder Lean derives after materialization and credits."
  IO.println "    pub quote_surplus: u64,"
  IO.println "}"
  IO.println ""
  IO.println "/// One General selection decision case, as Lean decides it."
  IO.println "#[derive(Clone, Copy, Debug, Eq, PartialEq)]"
  IO.println "pub struct GeneralSelectionVectorV1 {"
  IO.println "    /// The decision case this vector stands for."
  IO.println "    pub name: &'static str,"
  IO.println "    /// Submissions in the exact order the cursor considers them."
  IO.println "    pub submissions: &'static [GeneralSelectionSubmissionV1],"
  IO.println "    /// One-based Batch coordinate of the winning submission."
  IO.println "    pub best_coordinate: u32,"
  IO.println "    /// Content identity of the winning submission."
  IO.println "    pub best_candidate_id: [u8; 32],"
  IO.println "    /// Filled lots of the winning submission."
  IO.println "    pub best_filled_lots: u64,"
  IO.println "    /// Quote surplus of the winning submission."
  IO.println "    pub best_quote_surplus: u64,"
  IO.println "}"
  IO.println ""
  IO.println s!"pub const GENERAL_SELECTION_VECTORS_V1: [GeneralSelectionVectorV1; {selectionVectors.length}] = ["
  for vector in selectionVectors do
    let decision := vector.decision
    IO.println "    GeneralSelectionVectorV1 {"
    IO.println s!"        name: \"{vector.name}\","
    IO.println "        submissions: &["
    for submitted in vector.submissions do
      let candidate := certificateCandidate submitted
      IO.println "            GeneralSelectionSubmissionV1 {"
      IO.println s!"                candidate_id: {leBytes32 submitted.candidateId},"
      IO.println s!"                filled_lots: {candidate.objective.filledLots},"
      IO.println s!"                claim_inputs: {natSlice (claimInputs candidate)},"
      IO.println s!"                claim_outputs: {natSlice (claimOutputs candidate)},"
      IO.println s!"                quote_debit: {quoteInputs candidate},"
      IO.println s!"                quote_credit: {quoteOutputs candidate},"
      IO.println s!"                quote_surplus: {candidate.objective.quoteSurplus},"
      IO.println "            },"
    IO.println "        ],"
    IO.println s!"        best_coordinate: {decision.1},"
    IO.println s!"        best_candidate_id: {leBytes32 decision.2.2.2},"
    IO.println s!"        best_filled_lots: {decision.2.1},"
    IO.println s!"        best_quote_surplus: {decision.2.2.1},"
    IO.println "    },"
  IO.println "];"
