import DClutchSemantics.GeneralTransitionV3

open DClutch
open DClutch.General.ControllerAbi
open DClutch.General.TransitionV3

private def hexByte (byte : UInt8) : String :=
  let digits := "0123456789abcdef".toList
  let value := byte.toNat
  String.ofList [digits[value / 16]!, digits[value % 16]!]

private def rustByte (byte : UInt8) : String := s!"0x{hexByte byte}"

private def emitConst (doc name «type» value : String) : IO Unit := do
  IO.println s!"/// {doc}"
  IO.println s!"pub const {name}: {«type»} = {value};"

private def rustStem : Action → String
  | .consider => "CONSIDER"
  | .freeze => "FREEZE"
  | .initializeSettlement => "INITIALIZE"
  | .collect => "COLLECT"
  | .materialize => "MATERIALIZE"
  | .distribute => "DISTRIBUTE"
  | .close => "CLOSE"
  | .openBatch => "OPEN_BATCH"
  | .placeOrder => "PLACE_ORDER"
  | .cancelOrder => "CANCEL_ORDER"
  | .closeBatch => "CLOSE_BATCH"
  | .submitCandidate => "SUBMIT_CANDIDATE"
  | .verifyCandidateRow => "VERIFY_CANDIDATE_ROW"
  | .releaseOrder => "RELEASE_ORDER"
  | .closeCandidate => "CLOSE_CANDIDATE"

private def rustLabel : Action → String
  | .consider => "Consider"
  | .freeze => "Freeze"
  | .initializeSettlement => "InitializeSettlement"
  | .collect => "Collect"
  | .materialize => "Materialize"
  | .distribute => "Distribute"
  | .close => "Close"
  | .openBatch => "OpenBatch"
  | .placeOrder => "PlaceOrder"
  | .cancelOrder => "CancelOrder"
  | .closeBatch => "CloseBatch"
  | .submitCandidate => "SubmitCandidate"
  | .verifyCandidateRow => "VerifyCandidateRow"
  | .releaseOrder => "ReleaseOrder"
  | .closeCandidate => "CloseCandidate"

private def emitProgram (action : Action) : IO Unit := do
  let stem := rustStem action
  let label := rustLabel action
  let bytes := TransitionVMV3.Codec.encodeProgram (program action)
  emitConst s!"Exact prelude instruction count of the {label} transition program."
    s!"GENERAL_{stem}_PRELUDE_INSTRUCTIONS_V3" "usize" (toString (program action).prelude.length)
  emitConst s!"Exact per-Product-item instruction count of the {label} transition program."
    s!"GENERAL_{stem}_ITEM_INSTRUCTIONS_V3" "usize" (toString (program action).itemBody.length)
  emitConst s!"Exact epilogue instruction count of the {label} transition program."
    s!"GENERAL_{stem}_EPILOGUE_INSTRUCTIONS_V3" "usize" (toString (program action).epilogue.length)
  emitConst s!"Exact encoded {label} TransitionVM V3 width."
    s!"GENERAL_{stem}_TRANSITION_BYTES_V3" "usize" (toString bytes.length)
  IO.println s!"/// The exact {label} TransitionVM V3 program."
  IO.println
    s!"pub const GENERAL_{stem}_TRANSITION_V3: [u8; GENERAL_{stem}_TRANSITION_BYTES_V3] = ["
  for line in List.range ((bytes.length + 11) / 12) do
    let chunk := (bytes.drop (line * 12)).take 12
    IO.println s!"    {String.intercalate ", " (chunk.map rustByte)},"
  IO.println "];"

def main : IO Unit := do
  IO.println
    "// @generated by formal/dclutch-semantics/EmitGeneralTransitionV3Rust.lean; do not edit."
  emitConst "Exact common scalar-bank width in the General Hot38 ABI."
    "GENERAL_TRANSITION_COMMON_SCALARS_V3" "u32" (toString commonScalars)
  emitConst "Exact per-Product-item scalar stride in the General Hot38 ABI."
    "GENERAL_TRANSITION_ITEM_SCALAR_STRIDE_V3" "u32" (toString itemScalarStride)
  emitConst "Exact common identity-bank width in the General Hot38 ABI."
    "GENERAL_TRANSITION_COMMON_IDENTITIES_V3" "u32" (toString commonIdentities)
  emitConst "General has no per-Product-item identity tail."
    "GENERAL_TRANSITION_ITEM_IDENTITY_STRIDE_V3" "u32" (toString itemIdentityStride)
  emitConst "Number of General actions whose transition program is Lean-authored."
    "GENERAL_AUTHORED_TRANSITION_ACTION_COUNT_V3" "usize" (toString authoredActions.length)
  for action in authoredActions do
    emitProgram action
