import DClutchSemantics.CoreFoundFrameV3Abi

/-! Emit the Core Found V3 account frame as Rust.

The counts and the named indices become projections of the slot list, and the
privileges become a table the operator's `found_metas` is checked against, so
the order that used to live only in a `vec!` literal has a second reader. -/

open DClutch.CoreFoundFrameV3Abi

def rustBool (value : Bool) : String := if value then "true" else "false"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitCoreFoundFrameV3Rust.lean; do not edit."
  IO.println "/// Exact ordinary mutating `Found` V3 account count."
  IO.println s!"pub const FOUND_ACCOUNT_COUNT_V3: usize = {accountCount};"
  IO.println "/// Rent-sysvar coordinate in the ordinary mutating Found V3 frame."
  IO.println s!"pub const FOUND_RENT_SYSVAR_INDEX_V3: usize = {rentSysvarIndex};"
  IO.println "/// Capability-manifest raw-record index in the ordinary V3 Found frame."
  IO.println s!"pub const FOUND_CAPABILITY_MANIFEST_RAW_INDEX_V3: usize = {capabilityManifestRawIndex};"
  IO.println "/// Capability-manifest staging-cursor index in the ordinary V3 Found frame."
  IO.println s!"pub const FOUND_CAPABILITY_MANIFEST_STAGING_INDEX_V3: usize = {capabilityManifestStagingIndex};"
  IO.println "/// Price-gate certificate raw-record index, in the extended Found frame."
  IO.println s!"pub const FOUND_PRICE_GATE_RAW_INDEX_V3: usize = {priceGateRawIndex};"
  IO.println "/// Price-gate certificate staging-cursor index, in the extended Found frame."
  IO.println s!"pub const FOUND_PRICE_GATE_STAGING_INDEX_V3: usize = {priceGateStagingIndex};"
  IO.println "/// Exact ordinary mutating `Found` V3 account count with a certificate."
  IO.println s!"pub const FOUND_PRICE_GATE_ACCOUNT_COUNT_V3: usize = {priceGateAccountCount};"
  IO.println "/// Writable and signer privilege of every slot in the extended frame, in"
  IO.println "/// order. The canonical frame is the first `FOUND_ACCOUNT_COUNT_V3` entries."
  IO.println s!"pub const FOUND_ACCOUNT_ROLES_V3: [(bool, bool); {priceGateAccountCount}] = ["
  -- `crates/dclutch-market-core-codec/check.sh` compares RAW emitter output, so
  -- the trailing comments are aligned the way rustfmt aligns them: to one space
  -- past the widest entry, which is `(false, false),`.
  for slot in extendedFrame do
    let entry := s!"({rustBool slot.writable}, {rustBool slot.signer}),"
    let padding := String.ofList (List.replicate (15 - entry.length) ' ')
    IO.println s!"    {entry}{padding} // {slot.field}"
  IO.println "];"
