import DClutchSemantics.ParentReferenceV1Abi
import DClutchSemantics.RustEmit

/-! Emit the parent reference record, the derived settle request, the derived
family's identities and the settle frame as Rust.

Offsets are projections of the specialized layouts, so a field inserted
anywhere moves every coordinate after it in one place.  The identities are
printed as preimage AND digest; `crates/dclutch-source` recomputes each digest
from its preimage in a test, which is the check Lean cannot make. -/

open DClutch.RustEmit (rustByte emitBytes emitRustBytes)
open DClutch DClutch.ParentReferenceV1Abi DClutch.AbiSchema

def rustBool (value : Bool) : String := if value then "true" else "false"

def emitOffsets {Name : Type} (layout : List (PlacedField Name)) (rustName : Name → String)
    : IO Unit := do
  for field in layout do
    IO.println s!"pub const {rustName field.spec.name}: usize = {field.offset};"

/-- A refusal corpus and its count.  Both are `#[cfg(test)] pub(crate)`: they
are decision fixtures the Rust twin replays in its own tests and nothing else
reads, and a shipped build that carried them would carry kilobytes of hostile
records into every consumer. -/
def emitCorpus (name : String) (corpus : List (List UInt8)) (width : Nat) : IO Unit := do
  IO.println "#[cfg(test)]"
  IO.println s!"pub(crate) const {name}_COUNT: usize = {corpus.length};"
  IO.println "#[cfg(test)]"
  IO.println "#[rustfmt::skip]"
  IO.println s!"pub(crate) const {name}: [[u8; {width}]; {corpus.length}] = ["
  for candidate in corpus do
    IO.println "    ["
    for line in List.range ((candidate.length + 15) / 16) do
      let chunk := (candidate.drop (line * 16)).take 16
      IO.println s!"        {String.intercalate ", " (chunk.map rustByte)},"
    IO.println "    ],"
  IO.println "];"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitParentReferenceV1Rust.lean; do not edit."
  IO.println "// The parent reference a child market founds against, the derived provider's"
  IO.println "// settle request, the derived family's identities, and the settle frame."

  IO.println "/// Registry schema identity of a finalized `ParentReferenceV1` record."
  IO.println s!"pub const PARENT_REFERENCE_SCHEMA_PREIMAGE_V1: &[u8] = b\"{recordSchemaPreimage}\";"
  emitBytes "PARENT_REFERENCE_SCHEMA_ID_V1" recordSchemaId
  IO.println s!"pub const DERIVED_FAMILY_RELEASE_PREIMAGE_V1: &[u8] = b\"{familyReleasePreimage}\";"
  emitBytes "DERIVED_FAMILY_RELEASE_ID_V1" familyReleaseId
  IO.println s!"pub const DERIVED_PROVIDER_EXTENSION_PREIMAGE_V1: &[u8] = b\"{extensionReleasePreimage}\";"
  emitBytes "DERIVED_PROVIDER_EXTENSION_RELEASE_ID_V1" extensionReleaseId
  IO.println s!"pub const DERIVED_TRANSPORT_PROFILE_PREIMAGE_V1: &[u8] = b\"{transportProfilePreimage}\";"
  emitBytes "DERIVED_TRANSPORT_PROFILE_ID_V1" transportProfileId
  IO.println s!"pub const DERIVED_DECODING_RULES_PREIMAGE_V1: &[u8] = b\"{decodingRulesPreimage}\";"
  emitBytes "DERIVED_DECODING_RULES_ID_V1" decodingRulesId
  IO.println s!"pub const DERIVED_EVIDENCE_DOMAIN_V1: &[u8] = b\"{evidenceDomainPreimage}\";"

  IO.println "/// `SourceAccessProfile::DerivedFromParents`, as the byte `SourceSpecV1` carries."
  IO.println s!"pub const DERIVED_ACCESS_PROFILE_V1: u8 = {derivedAccessProfile};"
  IO.println s!"pub const PARENT_REFERENCE_KIND_PRODUCT_V1: u8 = {Kind.byte .product};"
  IO.println s!"pub const PARENT_REFERENCE_KIND_CONDITIONAL_V1: u8 = {Kind.byte .conditional};"

  emitBytes "PARENT_REFERENCE_MAGIC_V1" recordMagic
  IO.println s!"pub const PARENT_REFERENCE_VERSION_V1: u16 = {recordVersion};"
  IO.println s!"pub const PARENT_REFERENCE_BYTES_V1: usize = {recordBytes};"
  IO.println s!"pub const PARENT_REFERENCE_PARENT_STRIDE_V1: usize = {parentStride};"
  emitOffsets recordLayout RecordField.rustName
  IO.println "#[cfg(test)]"
  emitRustBytes "pub(crate)" "PARENT_REFERENCE_PRODUCT_EXAMPLE_V1" (encodeRecord productExample)
  IO.println "#[cfg(test)]"
  emitRustBytes "pub(crate)" "PARENT_REFERENCE_CONDITIONAL_EXAMPLE_V1"
    (encodeRecord conditionalExample)
  emitCorpus "PARENT_REFERENCE_REFUSAL_CORPUS_V1" recordRefusalCorpus recordBytes

  emitBytes "DERIVED_SETTLE_MAGIC_V1" requestMagic
  IO.println s!"pub const DERIVED_SETTLE_VERSION_V1: u16 = {requestVersion};"
  IO.println s!"pub const DERIVED_SETTLE_ACTION_V1: u8 = {requestSettleAction};"
  IO.println s!"pub const DERIVED_SETTLE_REQUEST_BYTES_V1: usize = {requestBytes};"
  emitOffsets requestLayout RequestField.rustName
  IO.println "#[cfg(test)]"
  emitRustBytes "pub(crate)" "DERIVED_SETTLE_REQUEST_EXAMPLE_V1" (encodeRequest requestExample)
  emitCorpus "DERIVED_SETTLE_REFUSAL_CORPUS_V1" requestRefusalCorpus requestBytes

  IO.println "/// Exact settle frame width with parent B's suffix."
  IO.println s!"pub const DERIVED_SETTLE_ACCOUNT_COUNT_V1: usize = {settleAccountCount};"
  IO.println "/// Exact settle frame width for a conditional child off its condition: no parent B."
  IO.println s!"pub const DERIVED_SETTLE_OFF_CONDITION_ACCOUNT_COUNT_V1: usize = {settleOffConditionAccountCount};"
  IO.println s!"pub const DERIVED_SETTLE_MARKET_INDEX_V1: usize = {marketIndex};"
  IO.println s!"pub const DERIVED_SETTLE_SOURCE_STATE_INDEX_V1: usize = {sourceStateIndex};"
  IO.println s!"pub const DERIVED_SETTLE_CERTIFICATE_INDEX_V1: usize = {certificateIndex};"
  IO.println s!"pub const DERIVED_SETTLE_MATERIAL_RAW_INDEX_V1: usize = {materialRawIndex};"
  IO.println s!"pub const DERIVED_SETTLE_PARENT_REFERENCE_RAW_INDEX_V1: usize = {parentReferenceRawIndex};"
  IO.println s!"pub const DERIVED_SETTLE_PRODUCT_RAW_INDEX_V1: usize = {productRawIndex};"
  IO.println s!"pub const DERIVED_SETTLE_CLOCK_INDEX_V1: usize = {clockIndex};"
  IO.println s!"pub const DERIVED_SETTLE_RENT_INDEX_V1: usize = {rentIndex};"
  IO.println s!"pub const DERIVED_SETTLE_SYSTEM_INDEX_V1: usize = {systemIndex};"
  IO.println s!"pub const DERIVED_SETTLE_PARENT_A_MARKET_INDEX_V1: usize = {parentAMarketIndex};"
  IO.println s!"pub const DERIVED_SETTLE_PARENT_B_MARKET_INDEX_V1: usize = {parentBMarketIndex};"
  IO.println s!"pub const DERIVED_SETTLE_PARENT_SLOT_COUNT_V1: usize = {parentSlotCount};"
  IO.println "/// Writable and signer privilege of every settle slot, in order; the"
  IO.println "/// off-condition frame is the first `DERIVED_SETTLE_OFF_CONDITION_ACCOUNT_COUNT_V1`."
  IO.println s!"pub const DERIVED_SETTLE_ACCOUNT_ROLES_V1: [(bool, bool); {settleAccountCount}] = ["
  for slot in settleFrameWithB do
    let entry := s!"({rustBool slot.writable}, {rustBool slot.signer}),"
    let padding := String.ofList (List.replicate (15 - entry.length) ' ')
    IO.println s!"    {entry}{padding} // {slot.field}"
  IO.println "];"
