import DClutchSemantics.UpkeepVaultV1
import DClutchSemantics.Codec
import DClutchSemantics.RustEmit

open DClutch.RustEmit (rustByte)

open DClutch DClutch.UpkeepVaultV1

def emitMagic (name : String) (value : List UInt8) : IO Unit :=
  IO.println
    s!"pub const {name}: [u8; {value.length}] = [{String.intercalate ", " (value.map rustByte)}];"

def emitOffset {Name : Type} [DecidableEq Name]
    (rustPrefix : String) (layout : List (AbiSchema.PlacedField Name))
    (name : String) (field : Name) : IO Unit :=
  let offset := ((AbiSchema.coordinate? field layout).getD (0, 0)).1
  IO.println s!"pub(crate) const {rustPrefix}_{name}_OFFSET: usize = {offset};"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitUpkeepVaultV1Rust.lean; do not edit."
  IO.println s!"pub const UPKEEP_VAULT_ABI_VERSION_V1: u16 = {abiVersion};"
  IO.println s!"pub const UPKEEP_VAULT_RECORD_BYTES_V1: usize = {recordBytes};"
  IO.println s!"pub const UPKEEP_VAULT_REQUEST_BYTES_V1: usize = {requestBytes};"
  IO.println s!"pub const UPKEEP_VAULT_RECEIPT_BYTES_V1: usize = {receiptBytes};"
  emitMagic "UPKEEP_VAULT_RECORD_MAGIC_V1" recordMagic
  emitMagic "UPKEEP_VAULT_REQUEST_MAGIC_V1" requestMagic
  emitMagic "UPKEEP_VAULT_RECEIPT_MAGIC_V1" receiptMagic
  for c in SourceClass.all do
    IO.println s!"pub const {SourceClass.rustName c}: u8 = {SourceClass.tag c};"
  IO.println s!"pub const UPKEEP_OPERATION_FOUND_TAG_V1: u8 = {Operation.tag .found};"
  IO.println s!"pub const UPKEEP_OPERATION_CREDIT_TAG_V1: u8 = {Operation.tag .credit};"
  IO.println s!"pub const UPKEEP_OPERATION_DEBIT_TAG_RESERVED_V1: u8 = {debitTag};"
  IO.println s!"pub const UPKEEP_FOUND_ACCOUNT_COUNT_V1: usize = {foundAccountCount};"
  IO.println s!"pub const UPKEEP_DEPOSIT_CREDIT_ACCOUNT_COUNT_V1: usize = {depositCreditAccountCount};"
  IO.println s!"pub const UPKEEP_PROTOCOL_CREDIT_ACCOUNT_COUNT_V1: usize = {protocolCreditAccountCount};"
  for (name, field) in [
      ("VERSION", RecordField.version), ("KIND", .kind), ("BUMP", .bump),
      ("RESERVED_HEADER", .reservedHeader),
      ("INFLOW_TOTAL", .inflowTotal), ("OUTFLOW_TOTAL", .outflowTotal),
      ("INFLOW_RESIDUE", .inflowResidue), ("INFLOW_DONATION", .inflowDonation),
      ("INFLOW_SEAT_RENT", .inflowSeatRent), ("INFLOW_DEPOSIT", .inflowDeposit),
      ("CREDIT_COUNT", .creditCount), ("LAST_CREDIT_DIGEST", .lastCreditDigest),
      ("RESERVED_TAIL", .reservedTail)] do
    emitOffset "UPKEEP_VAULT_RECORD" recordLayout name field
  for (name, field) in [
      ("VERSION", RequestField.version), ("OPERATION", .operation),
      ("SOURCE_CLASS", .sourceClass), ("CALLER_ROLE", .callerRole),
      ("RESERVED_HEADER", .reservedHeader),
      ("RELEASE_SET", .releaseSet), ("MARKET", .market), ("CONTEXT", .context),
      ("RECEIPT_DIGEST", .receiptDigest), ("AMOUNT", .amount),
      ("RESERVED_TAIL", .reservedTail)] do
    emitOffset "UPKEEP_VAULT_REQUEST" requestLayout name field
  for (name, field) in [
      ("VERSION", ReceiptField.version), ("OPERATION", .operation),
      ("SOURCE_CLASS", .sourceClass), ("RESERVED_HEADER", .reservedHeader),
      ("REQUEST_DIGEST", .requestDigest), ("VAULT", .vault), ("AMOUNT", .amount),
      ("INFLOW_TOTAL_AFTER", .inflowTotalAfter), ("OUTFLOW_TOTAL_AFTER", .outflowTotalAfter),
      ("CREDIT_COUNT_AFTER", .creditCountAfter)] do
    emitOffset "UPKEEP_VAULT_RECEIPT" receiptLayout name field
