import DClutchSemantics.RationalRepresentationV2PhysicalAbi
import DClutchSemantics.Codec
import DClutchSemantics.RustEmit

open DClutch.RustEmit (emitBytes)

open DClutch
open DClutch.AbiSchema
open DClutch.RationalRepresentationV2PhysicalAbi

/-- Physical ABI revision three names every request and asset constant it
moved.  A constant whose value changed keeps no old name, so a consumer that
was not revisited is a compile error rather than a silent reinterpretation.
The receipt layout did not change and keeps its version-two names. -/
def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitRationalRepresentationV2PhysicalAbiRust.lean; do not edit."
  IO.println s!"pub const PHYSICAL_ABI_VERSION_V3: u16 = {version};"
  IO.println s!"pub const REQUEST_COMMON_PREFIX_BYTES_V3: usize = {commonPrefixBytes};"
  for kind in RequestClass.all do
    IO.println s!"pub const REQUEST_{RequestClass.rustName kind}_HEADER_BYTES_V3: usize = {classHeaderBytes kind};"
  IO.println s!"pub const ASSET_BYTES_V3: usize = {assetBytes};"
  IO.println s!"pub const RECEIPT_BYTES_V2: usize = {receiptBytes};"
  emitBytes "REQUEST_MAGIC_V2" requestMagic
  emitBytes "RECEIPT_MAGIC_V2" receiptMagic
  for placed in specialize commonSchema do
    IO.println s!"pub const {RequestField.rustName placed.spec.name}_V3: usize = {placed.offset};"
  for kind in RequestClass.all do
    for placed in (classLayout kind).drop commonSchema.length do
      IO.println s!"pub const {RequestClass.rustName kind}_{RequestField.rustName placed.spec.name}_V3: usize = {placed.offset};"
  for field in AssetField.all do
    IO.println s!"pub const {AssetField.rustName field}_V3: usize = {AssetField.offset field};"
  for field in ReceiptField.all do
    IO.println s!"pub const {ReceiptField.rustName field}: usize = {ReceiptField.offset field};"
  IO.println s!"pub const ACTION_DENOMINATE: u8 = {Action.tag .denominate};"
  IO.println s!"pub const ACTION_RECONSTITUTE: u8 = {Action.tag .reconstitute};"
  IO.println s!"pub const ACTION_ISSUE_STRUCTURED: u8 = {Action.tag .issueStructured};"
  IO.println s!"pub const ACTION_UNWRAP_STRUCTURED: u8 = {Action.tag .unwrapStructured};"
  IO.println s!"pub const ACTION_REDEEM_TERMINAL: u8 = {Action.tag .redeemTerminal};"
  IO.println s!"pub const CALLER_ROLE_CORE: u8 = {CallerRole.tag .core};"
  IO.println s!"pub const CALLER_ROLE_TRADING: u8 = {CallerRole.tag .trading};"
