import DClutchSemantics.GeneralRequestProfilesV1

/-! Emit Lean-owned General action RequestProfile artifacts. -/

open DClutch
open DClutch.General.ControllerAbi
open DClutch.General.RequestProfilesV1
open DClutch.RequestProfileAbi

def rustByte (byte : UInt8) : String := s!"0x{Codec.byteHex byte}"

def emitBytes (name : String) (bytes : List UInt8) : IO Unit := do
  IO.println s!"pub const {name}: [u8; {bytes.length}] = ["
  IO.println s!"    {String.intercalate ", " (bytes.map rustByte)},"
  IO.println "];"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitGeneralRequestProfilesV1Rust.lean; do not edit."
  IO.println s!"pub const GENERAL_REQUEST_PROFILE_ACTION_COUNT_V1: usize = {actions.length};"
  emitBytes "GENERAL_CONSIDER_REQUEST_PROFILE_V1" (encodeProfile (profile .consider))
  emitBytes "GENERAL_FREEZE_REQUEST_PROFILE_V1" (encodeProfile (profile .freeze))
  emitBytes "GENERAL_INITIALIZE_REQUEST_PROFILE_V1" (encodeProfile (profile .initializeSettlement))
  emitBytes "GENERAL_COLLECT_REQUEST_PROFILE_V1" (encodeProfile (profile .collect))
  emitBytes "GENERAL_MATERIALIZE_REQUEST_PROFILE_V1" (encodeProfile (profile .materialize))
  emitBytes "GENERAL_DISTRIBUTE_REQUEST_PROFILE_V1" (encodeProfile (profile .distribute))
  emitBytes "GENERAL_CLOSE_REQUEST_PROFILE_V1" (encodeProfile (profile .close))
  emitBytes "GENERAL_OPEN_BATCH_REQUEST_PROFILE_V1" (encodeProfile (profile .openBatch))
  emitBytes "GENERAL_CLOSE_BATCH_REQUEST_PROFILE_V1" (encodeProfile (profile .closeBatch))
  emitBytes "GENERAL_PLACE_ORDER_REQUEST_PROFILE_V1" (encodeProfile (profile .placeOrder))
  emitBytes "GENERAL_CANCEL_ORDER_REQUEST_PROFILE_V1" (encodeProfile (profile .cancelOrder))
  emitBytes "GENERAL_SUBMIT_CANDIDATE_REQUEST_PROFILE_V1" (encodeProfile (profile .submitCandidate))
  emitBytes "GENERAL_VERIFY_CANDIDATE_ROW_REQUEST_PROFILE_V1" (encodeProfile (profile .verifyCandidateRow))
  emitBytes "GENERAL_RELEASE_ORDER_REQUEST_PROFILE_V1" (encodeProfile (profile .releaseOrder))
  emitBytes "GENERAL_CLOSE_CANDIDATE_REQUEST_PROFILE_V1" (encodeProfile (profile .closeCandidate))
