#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""The Lean emission guard: which generated files are checked, and which are not.

This repository generates ~70 source files from Lean, each opening with a
provenance header naming the emitter that printed it. Roughly twenty
hand-written `check-generated.sh` scripts re-run an emitter and `cmp` its
output against the committed bytes -- a real byte-identity gate, and a good
one. The problem this tool exists for is not that the gate is weak. It is
that the gate is *partial and invisible*: most generated files have no check
script, nothing enumerates which ones, and no CI runs any of them. A
generated file with no guard can be hand-edited, or drift behind its Lean
source, and nothing in the repository notices.

So this tool does two separable things, deliberately kept apart because they
cost wildly different amounts:

  CENSUS (cheap -- milliseconds, no build, no toolchain). Reads first lines
  and shell scripts. Answers: which generated files exist, which emitter
  authored each, and which of them a check script actually guards. Writes
  `COVERAGE.md`, which is committed and byte-gated by `--verify`. That is the
  ratchet: adding a new *unguarded* emission changes the committed census and
  reds `--verify` until someone either writes a check script or records the
  gap on purpose. The gap stops being invisible, which is the whole point.

  RUN (expensive -- needs `lake`, `rustfmt`, and a Lean build). Executes the
  check scripts themselves. Scoped by a git range so a pre-push hook does not
  pay for a Lean build on every push, only on the pushes that could actually
  move an emission.

The two halves answer different questions and neither substitutes for the
other. A green census does not mean the bytes match; it means we know which
bytes nobody is checking.

Usage:
    tools/emission-guard/emission_guard.py                 census to stdout
    tools/emission-guard/emission_guard.py --write         write COVERAGE.md
    tools/emission-guard/emission_guard.py --verify        byte-gate COVERAGE.md
    tools/emission-guard/emission_guard.py --affected BASE..HEAD
                                                           list scripts a range
                                                           could have moved
    tools/emission-guard/emission_guard.py --run BASE..HEAD
                                                           run those scripts
    tools/emission-guard/emission_guard.py --run --all     run every guard
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys
from dataclasses import dataclass, field

REPO_ROOT_DEFAULT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_COVERAGE_REL = "tools/emission-guard/COVERAGE.md"
FORMAL_DIR = "formal/dclutch-semantics"

# The provenance header a Lean emitter prints as its first line. This is the
# same rule the existing check scripts assert with `sed -n '1p'`; matching it
# rather than inventing a second convention is deliberate, so this tool and
# the gates it inventories agree on what "generated" means.
HEADER_RE = re.compile(
    r"^(?://|#|--) @generated by formal/dclutch-semantics/(Emit[A-Za-z0-9_]+\.lean); do not edit\.$"
)

# `lake env lean --run EmitFoo.lean` inside a check script: the emitter that
# script actually re-runs. The `lake build <Module>` lines are not used for
# the guard relation -- a module can be built without its output being
# compared, and it is the comparison that constitutes a guard.
SCRIPT_EMITTER_RE = re.compile(r"lake env lean --run\s+(Emit[A-Za-z0-9_]+\.lean)")

# `node scripts/lean-emit.mjs <Module> EmitFoo.lean <target> --check` in a
# package.json script: the browser half of the same pattern.
LEAN_EMIT_RE = re.compile(
    r"lean-emit\.mjs\s+\S+\s+(Emit[A-Za-z0-9_]+\.lean)\s+(\S+)(?:\s+(--check))?"
)

# The third guard kind, and the one this census was blind to until it was
# taught to look: a Rust integration test that runs the emitter through
# `Command` and asserts its stdout equals the committed bytes. These cannot be
# found with SCRIPT_EMITTER_RE, because `.args(["env", "lean", "--run",
# "EmitFoo.lean"])` puts the emitter on its own line -- so the emitter appears
# only as a bare string literal.
RUST_EMITTER_RE = re.compile(r'"(Emit[A-Za-z0-9_]+\.lean)"')

# What promotes such a test from "runs Lean" to "is a guard". The tool's rule
# everywhere else is that the COMPARISON constitutes a guard, never the build,
# so a test qualifies only if it both reads the committed artifact back and
# asserts equality. Deliberately conservative: a test that merely rebuilds a
# module, or shells out for a digest without comparing it, is not counted.
RUST_READBACK_RE = re.compile(r"fs::read\b|include_str!|read_to_string\b")
RUST_COMPARE_RE = re.compile(r"assert_eq!")


@dataclass
class Guard:
    """One runnable byte-identity check, and the emitters it re-runs."""

    path: str  # repo-relative script, or "<package.json script> in <dir>"
    emitters: set[str] = field(default_factory=set)
    kind: str = "shell"  # "shell" | "lean-emit"
    workdir: str = ""
    command: list[str] = field(default_factory=list)


class ToolError(Exception):
    """The census could not be taken at all.

    Distinct from drift ON PURPOSE, and the distinction is exit-code-visible:
    2 means this tool could not run, 1 means this tree disagrees with its
    committed census. Conflating them is a defect this repository has already
    paid for once -- `tools/seam-audit` used to exit 1 when `ast-grep` was
    absent, the same code it uses for "this tree has a seam defect", because
    the "install it" message sat behind a returncode check that an absent
    binary never reaches. It was fixed there in c3de7b46 and the same hole was
    open here: `git ls-files` under `check=True` raises, Python exits 1, and a
    CI job reading only the status calls a tree it never examined broken.

    A gate that cannot run has not passed and has not failed. It has to say so.
    """


def tracked_files(root: pathlib.Path) -> list[str]:
    result = subprocess.run(
        ["git", "-C", str(root), "ls-files"],
        text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        raise ToolError(
            f"cannot enumerate tracked files under {root}: "
            f"{result.stderr.strip() or 'git ls-files failed'}. The census "
            f"reads `git ls-files`, so it needs a git checkout -- an exported "
            f"or vendored copy of this tree is not one. This says nothing "
            f"about whether the census would pass."
        )
    return sorted(line for line in result.stdout.splitlines() if line)


def first_line(path: pathlib.Path) -> str | None:
    try:
        with path.open("rb") as handle:
            raw = handle.readline(4096)
    except OSError:
        return None
    try:
        return raw.decode("utf-8").rstrip("\n")
    except UnicodeDecodeError:
        return None


def discover_generated(root: pathlib.Path, files: list[str]) -> dict[str, str]:
    """repo-relative generated file -> the emitter named in its own header.

    Files under `formal/` are excluded: an emitter *prints* the header as a
    string literal, so it matches the pattern while being the author rather
    than the artifact. Including them would double-count every emission and
    invert the direction of the relation.
    """
    generated: dict[str, str] = {}
    for rel in files:
        if rel.startswith(f"{FORMAL_DIR}/") or rel == FORMAL_DIR:
            continue
        line = first_line(root / rel)
        if not line:
            continue
        match = HEADER_RE.match(line)
        if match:
            generated[rel] = match.group(1)
    return generated


def discover_guards(root: pathlib.Path, files: list[str]) -> list[Guard]:
    guards: list[Guard] = []
    for rel in files:
        if not rel.endswith(".sh") or "check" not in pathlib.PurePosixPath(rel).name:
            continue
        try:
            text = (root / rel).read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        emitters = set(SCRIPT_EMITTER_RE.findall(text))
        if emitters:
            guards.append(
                Guard(path=rel, emitters=emitters, kind="shell",
                      workdir=str(pathlib.PurePosixPath(rel).parent),
                      command=["sh", str(root / rel)])
            )

    for rel in files:
        if pathlib.PurePosixPath(rel).name != "package.json":
            continue
        try:
            text = (root / rel).read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        pkg_dir = str(pathlib.PurePosixPath(rel).parent)
        for emitter, target, check in LEAN_EMIT_RE.findall(text):
            if not check:
                continue  # the writer variant regenerates; only --check guards
            guards.append(
                Guard(path=f"{pkg_dir}: lean-emit {emitter}", emitters={emitter},
                      kind="lean-emit", workdir=pkg_dir,
                      command=["node", "scripts/lean-emit.mjs"])
            )

    for rel in files:
        path = pathlib.PurePosixPath(rel)
        if path.suffix != ".rs" or path.parent.name != "tests":
            continue
        crate_dir = path.parent.parent
        if not (root / crate_dir / "Cargo.toml").is_file():
            continue
        try:
            text = (root / rel).read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if not RUST_READBACK_RE.search(text) or not RUST_COMPARE_RE.search(text):
            continue
        emitters = set(RUST_EMITTER_RE.findall(text))
        if emitters:
            guards.append(
                Guard(path=rel, emitters=emitters, kind="cargo-test",
                      workdir=str(crate_dir),
                      command=["cargo", "test", "--manifest-path",
                               f"{crate_dir}/Cargo.toml", "--test", path.stem])
            )

    return sorted(guards, key=lambda g: g.path)


@dataclass
class Census:
    generated: dict[str, str]
    guards: list[Guard]

    @property
    def guarded_emitters(self) -> set[str]:
        covered: set[str] = set()
        for guard in self.guards:
            covered |= guard.emitters
        return covered

    def split(self) -> tuple[dict[str, str], dict[str, str]]:
        covered = self.guarded_emitters
        guarded = {f: e for f, e in self.generated.items() if e in covered}
        unguarded = {f: e for f, e in self.generated.items() if e not in covered}
        return guarded, unguarded


def build_census(root: pathlib.Path) -> Census:
    files = tracked_files(root)
    return Census(discover_generated(root, files), discover_guards(root, files))


def render_coverage(census: Census) -> str:
    guarded, unguarded = census.split()
    emitters = set(census.generated.values())
    covered = census.guarded_emitters & emitters
    lines: list[str] = []
    lines.append("<!-- @generated by tools/emission-guard/emission_guard.py -- do not hand-edit -->")
    lines.append("# Lean emission coverage")
    lines.append("")
    lines.append(
        "Which generated files a byte-identity guard actually re-runs and "
        "compares, and which are generated with nothing watching them. "
        "Regenerate with `tools/emission-guard/emission_guard.py --write`; "
        "byte-gate with `--verify`. This census is cheap — it reads first "
        "lines, shell scripts, `package.json` scripts and Rust integration "
        "tests, and never runs Lean."
    )
    lines.append("")
    lines.append(
        f"**{len(census.generated)} generated files from {len(emitters)} emitters. "
        f"{len(guarded)} guarded ({len(covered)} emitters), "
        f"{len(unguarded)} unguarded ({len(emitters) - len(covered)} emitters).**"
    )
    lines.append("")
    lines.append(
        "An unguarded row is not a bug in itself — it is a file that can be "
        "hand-edited, or drift behind the Lean source it claims to come from, "
        "with nothing in the repository noticing. The number above is the "
        "thing to drive down, and this file being byte-gated is what stops it "
        "drifting up unremarked: a new emission with no check script changes "
        "this census and reds `--verify` until someone decides, on purpose, "
        "which it is going to be."
    )
    lines.append("")

    lines.append("## Guards")
    lines.append("")
    lines.append(
        "Each runs its emitter and compares the output against the committed "
        "bytes. All of them need `lake` (and the shell ones `rustfmt`), which "
        "is why they are not on a cheap CI tier. A guard is a comparison, "
        "never a build: three kinds qualify — a `check*.sh` script, a "
        "`package.json` script passing `--check`, and a Rust integration test "
        "that reads the committed artifact back and asserts equality."
    )
    lines.append("")
    lines.append("| Guard | Kind | Emitters re-run |")
    lines.append("|---|---|---|")
    for guard in census.guards:
        names = ", ".join(f"`{e}`" for e in sorted(guard.emitters))
        lines.append(f"| `{guard.path}` | {guard.kind} | {names} |")
    lines.append("")

    lines.append("## Guarded generated files")
    lines.append("")
    lines.append("| File | Emitter |")
    lines.append("|---|---|")
    for rel in sorted(guarded):
        lines.append(f"| `{rel}` | `{guarded[rel]}` |")
    lines.append("")

    lines.append("## Unguarded generated files")
    lines.append("")
    if unguarded:
        lines.append(
            "No guard of any kind re-runs these emitters. Listed by emitter, "
            "because a single new guard covers every file in a group."
        )
        lines.append("")
        by_emitter: dict[str, list[str]] = {}
        for rel, emitter in unguarded.items():
            by_emitter.setdefault(emitter, []).append(rel)
        lines.append("| Emitter | Files with no guard |")
        lines.append("|---|---|")
        for emitter in sorted(by_emitter):
            files = "<br>".join(f"`{f}`" for f in sorted(by_emitter[emitter]))
            lines.append(f"| `{emitter}` | {files} |")
    else:
        lines.append("None. Every generated file has a check script behind it.")
    lines.append("")
    return "\n".join(lines) + "\n"


def changed_paths(root: pathlib.Path, revision_range: str) -> list[str]:
    result = subprocess.run(
        ["git", "-C", str(root), "diff", "--name-only", revision_range],
        text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        raise ToolError(
            f"cannot read '{revision_range}': {result.stderr.strip()}"
        )
    return [line for line in result.stdout.splitlines() if line]


def affected_guards(census: Census, changed: list[str]) -> tuple[list[Guard], str]:
    """Which guards could a change have moved, and why.

    Deliberately conservative in one direction and precise in the other. Any
    edit under `formal/` selects EVERY guard: Lean modules import each other,
    so a shared definition can move an emission whose own module was not
    touched, and guessing the import graph here would be a guess. An edit to a
    generated file alone selects only that file's guard -- which is the case
    worth catching precisely, because a hand-edited generated file is the
    failure this whole pattern exists to prevent.
    """
    touched_formal = [p for p in changed if p.startswith(f"{FORMAL_DIR}/")]
    if touched_formal:
        return list(census.guards), (
            f"{len(touched_formal)} file(s) under {FORMAL_DIR}/ changed; Lean "
            "modules share definitions, so every guard is in scope"
        )

    reasons: list[str] = []
    selected: dict[str, Guard] = {}
    changed_set = set(changed)
    for guard in census.guards:
        if guard.path in changed_set:
            selected[guard.path] = guard
            reasons.append(f"{guard.path} itself changed")
    for rel, emitter in census.generated.items():
        if rel not in changed_set:
            continue
        for guard in census.guards:
            if emitter in guard.emitters:
                selected[guard.path] = guard
                reasons.append(f"{rel} changed, guarded by {guard.path}")
    return list(selected.values()), "; ".join(reasons) if reasons else "nothing in scope"


def unguarded_changes(census: Census, changed: list[str]) -> list[str]:
    _, unguarded = census.split()
    return sorted(set(changed) & set(unguarded))


def run_guards(root: pathlib.Path, guards: list[Guard]) -> int:
    failures = 0
    for guard in guards:
        print(f"EMISSION-GUARD\trun\t{guard.path}", flush=True)
        if guard.kind == "shell":
            result = subprocess.run(["sh", guard.path], cwd=root)
        elif guard.kind == "cargo-test":
            # Named exactly, never a bare `-p <crate>`: the guard is this one
            # test binary, and running its crate's whole suite to check one
            # byte comparison would be a resource grab rather than diligence.
            result = subprocess.run(guard.command, cwd=root)
        else:
            # The package script owns its exact arguments; running it through
            # npm keeps this tool from restating a command line that lives in
            # package.json, which is the restatement bug the emissions pattern
            # exists to avoid in the first place.
            script = guard.path.split(": lean-emit ")[0]
            emitter = guard.path.split(": lean-emit ")[1]
            name = npm_script_for(root, script, emitter)
            if name is None:
                print(f"EMISSION-GUARD\tskip\t{guard.path}\tno --check script found")
                continue
            result = subprocess.run(["npm", "run", "--silent", name], cwd=root / script)
        if result.returncode != 0:
            failures += 1
            print(f"EMISSION-GUARD\tFAIL\t{guard.path}", flush=True)
        else:
            print(f"EMISSION-GUARD\tok\t{guard.path}", flush=True)
    return failures


def npm_script_for(root: pathlib.Path, pkg_dir: str, emitter: str) -> str | None:
    import json

    try:
        data = json.loads((root / pkg_dir / "package.json").read_text())
    except (OSError, ValueError):
        return None
    for name, body in (data.get("scripts") or {}).items():
        if emitter in body and "--check" in body:
            return name
    return None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--root", default=str(REPO_ROOT_DEFAULT))
    parser.add_argument("--out", default=None, help=f"default: <root>/{DEFAULT_COVERAGE_REL}")
    parser.add_argument("--write", action="store_true", help="write the census file")
    parser.add_argument("--verify", action="store_true", help="byte-gate the census file")
    parser.add_argument("--affected", metavar="RANGE", help="list guards a git range could move")
    parser.add_argument("--run", metavar="RANGE", nargs="?", const="", help="run affected guards")
    parser.add_argument("--all", action="store_true", help="with --run: every guard")
    args = parser.parse_args(argv)

    root = pathlib.Path(args.root).resolve()
    out = pathlib.Path(args.out).resolve() if args.out else root / DEFAULT_COVERAGE_REL
    census = build_census(root)
    guarded, unguarded = census.split()

    if args.verify:
        fresh = render_coverage(census)
        previous = out.read_text() if out.is_file() else None
        drifted = previous != fresh
        print(
            f"SUMMARY\tgenerated={len(census.generated)}\tguarded={len(guarded)}"
            f"\tunguarded={len(unguarded)}\tguards={len(census.guards)}"
            f"\tdrift={drifted}\tstatus={'STOP' if drifted else 'PASS'}"
        )
        if drifted:
            print(
                "emission_guard: COVERAGE.md is stale. Regenerate it with "
                "--write. If the unguarded count went UP, that is the census "
                "doing its job: a new generated file arrived with nothing "
                "checking it.",
                file=sys.stderr,
            )
        return 1 if drifted else 0

    if args.write:
        out.write_text(render_coverage(census))
        print(f"COVERAGE\t{out}")
        print(
            f"SUMMARY\tgenerated={len(census.generated)}\tguarded={len(guarded)}"
            f"\tunguarded={len(unguarded)}\tguards={len(census.guards)}"
        )
        return 0

    if args.affected is not None or args.run is not None:
        revision_range = args.affected if args.affected is not None else args.run
        if args.all:
            selected, why = list(census.guards), "--all"
            touched: list[str] = []
        elif not revision_range:
            raise SystemExit("emission_guard: --run needs a git range, or --all")
        else:
            touched = changed_paths(root, revision_range)
            selected, why = affected_guards(census, touched)
        print(f"EMISSION-GUARD\tscope\t{why}")
        for guard in sorted(selected, key=lambda g: g.path):
            print(f"EMISSION-GUARD\tselected\t{guard.path}")
        if touched:
            for rel in unguarded_changes(census, touched):
                print(
                    f"EMISSION-GUARD\tUNGUARDED\t{rel}\t"
                    "generated file changed and NO check script re-runs its "
                    "emitter -- nothing verified these bytes"
                )
        if args.run is not None:
            if not selected:
                print("EMISSION-GUARD\tnothing to run")
                return 0
            failures = run_guards(root, selected)
            print(f"SUMMARY\tran={len(selected)}\tfailures={failures}")
            return 1 if failures else 0
        return 0

    sys.stdout.write(render_coverage(census))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except ToolError as error:
        print(f"emission_guard: {error}", file=sys.stderr)
        # 2, matching tools/seam-audit/seam_audit.py, so this tree has ONE
        # convention for "the checker could not run" rather than two.
        sys.exit(2)
