#!/bin/sh
set -eu

# The three Direct emissions check-successor-generated.sh does not cover: the
# controller codec layout, the registered lifecycle state, and the registered
# controller/create/terminal records. All three are persisted wire layouts and
# all three were generated with nothing re-running their emitters.

crate_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repository_dir=$(CDPATH= cd -- "$crate_dir/../.." && pwd)
formal_dir="$repository_dir/formal/dclutch-semantics"

candidate=$(mktemp "${TMPDIR:-/tmp}/dclutch-generated.XXXXXX")
trap 'rm -f "$candidate"' EXIT HUP INT TERM

# Assert the provenance header and that the emitter produced a whole file
# rather than a truncated one, then normalize with the repository's pinned
# rustfmt and byte-compare. Formatting is normalized rather than asserted
# because the committed bytes are rustfmt output, not raw emitter output;
# `rustfmt` resolves through rust-toolchain.toml from inside the tree.
#
# Each emission is spelled out rather than folded into a loop, because the
# emission census matches `lake env lean --run <Emitter>` literally: an emitter
# reached through a shell variable is an emitter the census cannot see, and a
# guard the census cannot see guards nothing as far as the ratchet is concerned.
verify() {
  emitter=$1
  target=$2
  minimum_lines=$3
  test "$(sed -n '1p' "$candidate")" = "// @generated by formal/dclutch-semantics/$emitter; do not edit."
  test "$(wc -l <"$candidate" | tr -d ' ')" -ge "$minimum_lines"
  rustfmt --edition 2024 "$candidate"
  cmp "$candidate" "$crate_dir/src/$target"
}

(
  cd "$formal_dir"
  lake build DClutchSemantics.DirectControllerCodec >/dev/null
  lake env lean --run EmitDirectCodecRust.lean >"$candidate"
)
grep -q '^pub(crate) const ABI_VERSION: u16 = 1;$' "$candidate"
verify EmitDirectCodecRust.lean generated_layout.rs 80

(
  cd "$formal_dir"
  lake build DClutchSemantics.DirectLifecycleAbi >/dev/null
  lake env lean --run EmitDirectLifecycleAbiRust.lean >"$candidate"
)
grep -q '^pub(crate) const REGISTERED_STATE_BYTES_VALUE: usize = 232;$' "$candidate"
verify EmitDirectLifecycleAbiRust.lean generated_lifecycle.rs 80

(
  cd "$formal_dir"
  lake build DClutchSemantics.RegisteredControllerAbi >/dev/null
  lake env lean --run EmitRegisteredControllerAbiRust.lean >"$candidate"
)
grep -q '^pub(crate) const REGISTERED_CONTROLLER_BYTES_VALUE: usize = 32;$' "$candidate"
grep -q '^pub(crate) const REGISTERED_CREATE_BYTES_VALUE: usize = 152;$' "$candidate"
grep -q '^pub(crate) const REGISTERED_TERMINAL_BYTES_VALUE: usize = 24;$' "$candidate"
verify EmitRegisteredControllerAbiRust.lean generated_registered_controller.rs 80
