[package]
name = "dclutch-trading-outer-test-program"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-or-later"
publish = false

[lib]
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"

[features]
default = []
no-entrypoint = []
custom-heap = []
custom-panic = []

[dependencies]
dclutch-trading-sbf = { path = "../../..", default-features = false, features = ["no-entrypoint", "outer-only"] }
solana-program = { version = "=3.0.0", default-features = false }

[workspace]

[lints.rust]
missing_docs = "deny"
unsafe_code = "forbid"
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(target_os, values("solana"))'] }
