[workspace]
members = [
    "crates/dclutch-collateral-contract",
    "crates/dclutch-core-contract",
    "crates/dclutch-kernel",
    "crates/dclutch-operator",
    "crates/dclutch-pyth-svm",
    "crates/dclutch-pyth-contract",
    "crates/dclutch-realm-contract",
    "crates/dclutch-token-svm",
    "programs/dclutch-sbf",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "AGPL-3.0-or-later"
rust-version = "1.89"

[workspace.lints.rust]
missing_docs = "deny"
unsafe_code = "forbid"
unexpected_cfgs = { level = "deny", check-cfg = ['cfg(target_os, values("solana"))'] }

[workspace.lints.clippy]
cast_possible_truncation = "deny"
cast_sign_loss = "deny"
checked_conversions = "deny"
float_arithmetic = "deny"
indexing_slicing = "deny"
panic = "deny"
unwrap_used = "deny"
