#!/bin/sh
set -eu

# The Series V3 template and occurrence layouts. Both widths are persisted, and
# both were generated with nothing re-running the emitter.

crate_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repository_dir=$(CDPATH= cd -- "$crate_dir/../.." && pwd)
formal_dir="$repository_dir/formal/dclutch-semantics"

candidate=$(mktemp "${TMPDIR:-/tmp}/dclutch-generated.XXXXXX")
trap 'rm -f "$candidate"' EXIT HUP INT TERM

# Assert the provenance header and that the emitter produced a whole file
# rather than a truncated one, then normalize with the repository's pinned
# rustfmt and byte-compare. Formatting is normalized rather than asserted
# because the committed bytes are rustfmt output, not raw emitter output;
# `rustfmt` resolves through rust-toolchain.toml from inside the tree.
#
# Each emission is spelled out rather than folded into a loop, because the
# emission census matches `lake env lean --run <Emitter>` literally: an emitter
# reached through a shell variable is an emitter the census cannot see, and a
# guard the census cannot see guards nothing as far as the ratchet is concerned.
verify() {
  emitter=$1
  target=$2
  minimum_lines=$3
  test "$(sed -n '1p' "$candidate")" = "// @generated by formal/dclutch-semantics/$emitter; do not edit."
  test "$(wc -l <"$candidate" | tr -d ' ')" -ge "$minimum_lines"
  rustfmt --edition 2024 "$candidate"
  cmp "$candidate" "$crate_dir/src/$target"
}

(
  cd "$formal_dir"
  lake build DClutchSemantics.SeriesOccurrenceV3Abi >/dev/null
  lake env lean --run EmitSeriesOccurrenceV3Rust.lean >"$candidate"
)
grep -q '^pub const SERIES_TEMPLATE_SCHEMA_V3: u16 = 3;$' "$candidate"
grep -q '^pub const SERIES_TEMPLATE_BYTES_V3: usize = 400;$' "$candidate"
grep -q '^pub const SERIES_OCCURRENCE_BYTES_V3: usize = 288;$' "$candidate"
verify EmitSeriesOccurrenceV3Rust.lean generated.rs 70
