#![no_std]
#![forbid(unsafe_code)]
#![deny(missing_docs)]

//! Finalized physical artifacts for exact fractional categorical claims.
//!
//! This contract keeps the pure allocation kernel as the sole owner of
//! denomination, remainder, reserve, and lifecycle arithmetic. It only joins
//! independently finalized generic interpreter artifacts and defines the
//! family request/root wire formats used by a future thin SBF adapter.

mod artifacts;
mod atomic_v3;
mod hot_v2;
mod physical_v3;
mod request;
mod request_v2;
mod retirement_v3;
mod root;

pub use artifacts::{
    ArtifactAdmissionV1, FractionalArtifactAdmissionsV1, FractionalArtifactBundleV1,
    FractionalArtifactBytesV1, FractionalArtifactErrorV1, FractionalArtifactSelectionV1,
    FractionalChildProgramsV1, Result as ArtifactResult,
    authenticate_fractional_artifact_bundle_v1,
};
pub use atomic_v3::{
    FRACTIONAL_ATOMIC_ACCOUNT_COUNT_V3, FRACTIONAL_ATOMIC_ACTOR_V3,
    FRACTIONAL_ATOMIC_HOLDER_TOKEN_V3, FRACTIONAL_ATOMIC_RECEIPT_BYTES_V3,
    FRACTIONAL_ATOMIC_RECEIPT_MAGIC_V3, FRACTIONAL_ATOMIC_RECEIPT_SCHEMA_PREIMAGE_V3,
    FRACTIONAL_ATOMIC_ROOT_V3, FRACTIONAL_ATOMIC_SHARD_MINT_V3,
    FRACTIONAL_ATOMIC_SIGNED_DELTA_ACCOUNT_COUNT_V3, FRACTIONAL_ATOMIC_TERMS_RAW_V3,
    FRACTIONAL_ATOMIC_TERMS_STAGING_V3, FRACTIONAL_ATOMIC_TOKEN_BEHAVIOR_RAW_V3,
    FRACTIONAL_ATOMIC_TOKEN_BEHAVIOR_STAGING_V3, FRACTIONAL_ATOMIC_TOKEN_PROGRAM_V3,
    FRACTIONAL_ROOT_PDA_SEED_V1, FRACTIONAL_TERMINAL_ACCOUNT_COUNT_V3,
    FRACTIONAL_TERMINAL_ACTOR_V3, FRACTIONAL_TERMINAL_ATOMIC_RECEIPT_BYTES_V3,
    FRACTIONAL_TERMINAL_ATOMIC_RECEIPT_MAGIC_V3,
    FRACTIONAL_TERMINAL_ATOMIC_RECEIPT_SCHEMA_PREIMAGE_V3,
    FRACTIONAL_TERMINAL_BASE_ACCOUNT_COUNT_V3, FRACTIONAL_TERMINAL_ROOT_V3,
    FRACTIONAL_TERMINAL_SHARD_MINT_V3, FRACTIONAL_TERMINAL_SOURCE_TOKEN_V3,
    FRACTIONAL_TERMINAL_TERMS_RAW_V3, FRACTIONAL_TERMINAL_TERMS_STAGING_V3,
    FRACTIONAL_TERMINAL_TOKEN_BEHAVIOR_RAW_V3, FRACTIONAL_TERMINAL_TOKEN_BEHAVIOR_STAGING_V3,
    FractionalAtomicReceiptErrorV3, FractionalAtomicReceiptV3, FractionalTerminalAtomicReceiptV3,
    Result as FractionalAtomicReceiptResultV3,
};
pub use hot_v2::{
    FRACTIONAL_HOT_MAX_TOKEN_EFFECTS_V2, FRACTIONAL_HOT_NO_ROUTE_ACCOUNTS_V2,
    FractionalHotAccountRefV2, FractionalHotCandidateInputV2, FractionalHotCandidateV2,
    FractionalHotClaimsEffectV2, FractionalHotErrorV2, FractionalHotRentCloseV2,
    FractionalHotTokenEffectV2, FractionalHotTokenKindV2, FractionalHotTokenPostV2,
    Result as FractionalHotResultV2,
};
pub use physical_v3::{
    FractionalChildRouteV3, FractionalPhysicalErrorV3, FractionalPhysicalPlanV3,
    FractionalSignerRoleV3, Result as FractionalPhysicalResultV3, plan_fractional_physical_v3,
};
pub use request::{
    FRACTIONAL_FAMILY_REQUEST_BYTES_V1, FRACTIONAL_FAMILY_REQUEST_MAGIC_V1,
    FRACTIONAL_FAMILY_REQUEST_SCHEMA_ID_V1, FRACTIONAL_FAMILY_REQUEST_SCHEMA_PREIMAGE_V1,
    FRACTIONAL_REQUEST_ACTION_OFFSET_V1, FRACTIONAL_REQUEST_DESTINATION_TOKEN_OFFSET_V1,
    FRACTIONAL_REQUEST_EXPECTED_REVISION_OFFSET_V1, FRACTIONAL_REQUEST_HEADER_RESERVED_BYTES_V1,
    FRACTIONAL_REQUEST_HEADER_RESERVED_OFFSET_V1, FRACTIONAL_REQUEST_MARKET_OFFSET_V1,
    FRACTIONAL_REQUEST_OUTCOME_OFFSET_V1, FRACTIONAL_REQUEST_OWNER_OFFSET_V1,
    FRACTIONAL_REQUEST_PRODUCT_RECORD_OFFSET_V1, FRACTIONAL_REQUEST_QUANTITY_OFFSET_V1,
    FRACTIONAL_REQUEST_RELEASE_SET_OFFSET_V1, FRACTIONAL_REQUEST_RESULT_DOMAIN_OFFSET_V1,
    FRACTIONAL_REQUEST_SOURCE_TOKEN_OFFSET_V1, FRACTIONAL_REQUEST_TAIL_RESERVED_BYTES_V1,
    FRACTIONAL_REQUEST_TAIL_RESERVED_OFFSET_V1, FRACTIONAL_REQUEST_TERMINAL_DIGEST_OFFSET_V1,
    FRACTIONAL_REQUEST_TERMINAL_OUTCOME_OFFSET_V1, FRACTIONAL_REQUEST_TERMS_OFFSET_V1,
    FRACTIONAL_REQUEST_TOKEN_BEHAVIOR_OFFSET_V1, FractionalActionV1,
    FractionalFamilyRequestInputV1, FractionalFamilyRequestV1, FractionalRequestErrorV1,
    NO_TERMINAL_OUTCOME_V1, Result as RequestResult,
};
pub use request_v2::{
    FRACTIONAL_EXPOSURE_REQUEST_ACTION_OFFSET_V2, FRACTIONAL_EXPOSURE_REQUEST_BYTES_V2,
    FRACTIONAL_EXPOSURE_REQUEST_DESTINATION_TOKEN_OFFSET_V2,
    FRACTIONAL_EXPOSURE_REQUEST_EXPECTED_REVISION_OFFSET_V2,
    FRACTIONAL_EXPOSURE_REQUEST_EXPOSURE_OFFSET_V2,
    FRACTIONAL_EXPOSURE_REQUEST_HEADER_RESERVED_OFFSET_V2, FRACTIONAL_EXPOSURE_REQUEST_MAGIC_V2,
    FRACTIONAL_EXPOSURE_REQUEST_MARKET_OFFSET_V2, FRACTIONAL_EXPOSURE_REQUEST_OWNER_OFFSET_V2,
    FRACTIONAL_EXPOSURE_REQUEST_PRODUCT_RECORD_OFFSET_V2,
    FRACTIONAL_EXPOSURE_REQUEST_QUANTITY_OFFSET_V2,
    FRACTIONAL_EXPOSURE_REQUEST_RELEASE_SET_OFFSET_V2,
    FRACTIONAL_EXPOSURE_REQUEST_REPRESENTATION_COORDINATE_OFFSET_V2,
    FRACTIONAL_EXPOSURE_REQUEST_RESULT_DOMAIN_OFFSET_V2, FRACTIONAL_EXPOSURE_REQUEST_SCHEMA_ID_V2,
    FRACTIONAL_EXPOSURE_REQUEST_SCHEMA_PREIMAGE_V2,
    FRACTIONAL_EXPOSURE_REQUEST_SOURCE_TOKEN_OFFSET_V2,
    FRACTIONAL_EXPOSURE_REQUEST_TAIL_RESERVED_OFFSET_V2,
    FRACTIONAL_EXPOSURE_REQUEST_TERMINAL_DIGEST_OFFSET_V2,
    FRACTIONAL_EXPOSURE_REQUEST_TERMS_OFFSET_V2,
    FRACTIONAL_EXPOSURE_REQUEST_TOKEN_BEHAVIOR_OFFSET_V2, FractionalExposureActionV2,
    FractionalExposureRequestErrorV2, FractionalExposureRequestInputV2,
    FractionalExposureRequestV2, NO_EXPOSURE_COORDINATE_V2, Result as ExposureRequestResult,
};
pub use retirement_v3::{
    FRACTIONAL_RETIREMENT_BEGIN_ACCOUNT_COUNT_V3,
    FRACTIONAL_RETIREMENT_COORDINATE_ACCOUNT_COUNT_V3,
    FRACTIONAL_RETIREMENT_COORDINATE_RECEIPT_BYTES_V3,
    FRACTIONAL_RETIREMENT_COORDINATE_RECEIPT_MAGIC_V3, FRACTIONAL_RETIREMENT_COORDINATE_ROOT_V3,
    FRACTIONAL_RETIREMENT_CURSOR_BYTES_V3, FRACTIONAL_RETIREMENT_CURSOR_MAGIC_V3,
    FRACTIONAL_RETIREMENT_CURSOR_PDA_SEED_V3, FRACTIONAL_RETIREMENT_CURSOR_SCHEMA_ID_V3,
    FRACTIONAL_RETIREMENT_CURSOR_SCHEMA_PREIMAGE_V3, FRACTIONAL_RETIREMENT_FINISH_ACCOUNT_COUNT_V3,
    FRACTIONAL_RETIREMENT_LIFECYCLE_RECEIPT_BYTES_V3,
    FRACTIONAL_RETIREMENT_LIFECYCLE_RECEIPT_MAGIC_V3, FRACTIONAL_RETIREMENT_REQUEST_BYTES_V3,
    FRACTIONAL_RETIREMENT_REQUEST_MAGIC_V3, FRACTIONAL_RETIREMENT_REQUEST_SCHEMA_ID_V3,
    FRACTIONAL_RETIREMENT_REQUEST_SCHEMA_PREIMAGE_V3, FractionalRetireCoordinateObservationV3,
    FractionalRetirementActionV3, FractionalRetirementCoordinateReceiptV3,
    FractionalRetirementCursorInputV3, FractionalRetirementCursorV3, FractionalRetirementErrorV3,
    FractionalRetirementFinishV3, FractionalRetirementLifecycleObservationV3,
    FractionalRetirementLifecycleReceiptV3, FractionalRetirementRequestInputV3,
    FractionalRetirementRequestV3, NO_RETIREMENT_COORDINATE_V3,
    Result as FractionalRetirementResultV3,
};
pub use root::{
    FRACTIONAL_CAPABILITY_ROOT_BYTES_V4, FRACTIONAL_CAPABILITY_ROOT_STATE_OFFSET_V4,
    FRACTIONAL_ROOT_BYTES_V1, FRACTIONAL_ROOT_MAGIC_V1, FRACTIONAL_ROOT_MARKET_OFFSET_V1,
    FRACTIONAL_ROOT_RENT_BENEFICIARY_OFFSET_V1, FRACTIONAL_ROOT_RENT_PRINCIPAL_OFFSET_V1,
    FRACTIONAL_ROOT_REVISION_OFFSET_V1, FRACTIONAL_ROOT_SCHEMA_ID_V1, FRACTIONAL_ROOT_SCHEMA_ID_V2,
    FRACTIONAL_ROOT_SCHEMA_PREIMAGE_V1, FRACTIONAL_ROOT_SCHEMA_PREIMAGE_V2,
    FRACTIONAL_ROOT_SELECTION_CONFIG_OFFSET_V2, FRACTIONAL_ROOT_TERMS_OFFSET_V1,
    FractionalCapabilityRootV4, FractionalRootInputV1, FractionalRootInputV2,
    FractionalRootStateV2, FractionalRootV1, FractionalRootV2,
    decode_fractional_capability_root_v4, fractional_root_creation_tail_v2,
};

/// Finalized capability-kind semantic identity.
pub const FRACTIONAL_CAPABILITY_KIND_ID_V1: [u8; 32] = [
    0x99, 0x3d, 0xb3, 0xca, 0x5f, 0xfc, 0x4d, 0x67, 0x42, 0xe0, 0x48, 0x77, 0x9f, 0x8d, 0xac, 0xa2,
    0x3c, 0x18, 0x06, 0xc0, 0x3b, 0x27, 0xab, 0x19, 0x39, 0x9c, 0xd8, 0x68, 0x83, 0xcc, 0x1e, 0x9b,
];
