//! Exact Lean-generator freshness and schema-digest checks for Structured V2.

#![allow(clippy::panic)]

use std::path::PathBuf;
use std::process::Command;

use dclutch_structured_v2_kernel::{
    STRUCTURED_CAPABILITY_KIND_ID_V2, STRUCTURED_CAPABILITY_KIND_PREIMAGE_V2,
    STRUCTURED_CAPACITY_PROFILE_ID_V2, STRUCTURED_CAPACITY_PROFILE_PREIMAGE_V2,
    STRUCTURED_REQUEST_SCHEMA_ID_V2, STRUCTURED_REQUEST_SCHEMA_PREIMAGE_V2,
    STRUCTURED_ROOT_SCHEMA_ID_V2, STRUCTURED_ROOT_SCHEMA_PREIMAGE_V2,
    STRUCTURED_TERMS_SCHEMA_ID_V2, STRUCTURED_TERMS_SCHEMA_PREIMAGE_V2,
};
use sha2::{Digest, Sha256};

#[test]
fn checked_in_structured_v2_abi_is_exact_lean_output() {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let formal = manifest.join("../../formal/dclutch-semantics");
    let build = Command::new("lake")
        .args(["build", "DClutchSemantics.StructuredV2Abi"])
        .current_dir(&formal)
        .output()
        .unwrap_or_else(|error| panic!("launch Lean build: {error}"));
    assert!(
        build.status.success(),
        "Structured V2 ABI build failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&build.stdout),
        String::from_utf8_lossy(&build.stderr)
    );

    let generated = Command::new("lake")
        .args(["env", "lean", "--run", "EmitStructuredV2AbiRust.lean"])
        .current_dir(&formal)
        .output()
        .unwrap_or_else(|error| panic!("launch Lean generator: {error}"));
    assert!(
        generated.status.success(),
        "Structured V2 generator failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&generated.stdout),
        String::from_utf8_lossy(&generated.stderr)
    );

    let expected_header =
        b"// @generated by formal/dclutch-semantics/EmitStructuredV2AbiRust.lean; do not edit.\n";
    assert!(
        generated.stdout.starts_with(expected_header),
        "generator emitted an unexpected header"
    );

    let temporary = std::env::temp_dir().join(format!(
        "dclutch-structured-v2-generated-{}.rs",
        std::process::id()
    ));
    std::fs::write(&temporary, &generated.stdout)
        .unwrap_or_else(|error| panic!("write generated Rust: {error}"));
    let formatted = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .arg(&temporary)
        .output()
        .unwrap_or_else(|error| panic!("launch rustfmt: {error}"));
    assert!(
        formatted.status.success(),
        "rustfmt failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&formatted.stdout),
        String::from_utf8_lossy(&formatted.stderr)
    );
    let formatted = std::fs::read(&temporary)
        .unwrap_or_else(|error| panic!("read formatted generated Rust: {error}"));
    std::fs::remove_file(&temporary)
        .unwrap_or_else(|error| panic!("remove generated Rust: {error}"));
    let checked_in = std::fs::read(manifest.join("src/generated_abi.rs"))
        .unwrap_or_else(|error| panic!("read checked-in generated Rust: {error}"));
    assert_eq!(formatted, checked_in);
}

#[test]
fn structured_v2_schema_identities_are_exact_digests() {
    for (preimage, expected) in [
        (
            STRUCTURED_TERMS_SCHEMA_PREIMAGE_V2,
            STRUCTURED_TERMS_SCHEMA_ID_V2,
        ),
        (
            STRUCTURED_ROOT_SCHEMA_PREIMAGE_V2,
            STRUCTURED_ROOT_SCHEMA_ID_V2,
        ),
        (
            STRUCTURED_REQUEST_SCHEMA_PREIMAGE_V2,
            STRUCTURED_REQUEST_SCHEMA_ID_V2,
        ),
        (
            STRUCTURED_CAPABILITY_KIND_PREIMAGE_V2,
            STRUCTURED_CAPABILITY_KIND_ID_V2,
        ),
        (
            STRUCTURED_CAPACITY_PROFILE_PREIMAGE_V2,
            STRUCTURED_CAPACITY_PROFILE_ID_V2,
        ),
    ] {
        let digest: [u8; 32] = Sha256::digest(preimage).into();
        assert_eq!(
            digest,
            expected,
            "schema digest differs for {}",
            String::from_utf8_lossy(preimage)
        );
    }
}
