/**
 * Run one Lean TypeScript emitter and write or byte-compare its output.
 *
 * This is the browser half of the house emission pattern. The Rust half is
 * `crates/<crate>/check-generated.sh`: run the Lean emitter, pin a few exact
 * literals so a silent width change cannot pass, and `cmp` against the file
 * checked into the tree. This does the same for `lib/generated/*.ts`.
 *
 * It deliberately does NOT scrape Rust. The older `generate-*.mjs` scripts read
 * generated Rust with regexes, which made the browser a mirror of a mirror: a
 * Lean edit reached the browser only if someone regenerated the Rust first, and
 * a hand-edited Rust constant reached the browser as though Lean had said it.
 * Here the Lean schema is the only authority, and both backends print from it.
 *
 * Usage:
 *   node scripts/lean-emit.mjs <DClutchSemantics.Module[,Module...]> <EmitFoo.lean> <lib/generated/foo.ts> [--check]
 *
 * WHAT GETS BUILT, and why it is not the argument. `lake env lean --run` needs
 * its imports already built and does not build them, so anything left unbuilt
 * fails at run time rather than silently emitting from a stale olean -- which
 * is exactly what happened: every emitter imports `DClutchSemantics.TsEmit`,
 * no invocation ever named it, and the day `TsEmit` gained `bytesBlock` the
 * registered ABI could not be emitted in any checkout whose olean predated it.
 * The emitter's own `import` lines are the authority on what it needs, so they
 * are what is built, together with whatever the invocation names. A surface
 * whose authority is genuinely two schemas -- the registered Direct ABI is the
 * lifecycle state and the controller records, which do not import one another
 * -- still names both, comma separated; the argument is now a way to build
 * MORE than the imports, never the only thing built.
 *
 * Requires `lake` (elan) on PATH, exactly as the Rust check scripts do.
 */
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const [leanModules, emitter, target, ...flags] = process.argv.slice(2);
if (!leanModules || !emitter || !target) {
  console.error('usage: node scripts/lean-emit.mjs <DClutchSemantics.Module[,Module...]> <EmitFoo.lean> <lib/generated/foo.ts> [--check]');
  process.exit(2);
}
const modules = leanModules.split(',').filter(Boolean);
if (modules.length === 0) {
  console.error('lean-emit: no Lean module named');
  process.exit(2);
}

const repositoryRoot = new URL('../../../', import.meta.url);
const formalDir = fileURLToPath(new URL('formal/dclutch-semantics/', repositoryRoot));
const outputUrl = new URL(`../${target}`, import.meta.url);
const check = flags.includes('--check');
// Anything else after the target is handed to the emitter: an emitter that
// prints more than one module (`EmitRegisteredDirect.lean lifecycle|controller|ts`)
// selects the module by argument, and `ts` is that selection here.
const emitterArguments = flags.filter((flag) => flag !== '--check');

function lake(args) {
  const result = spawnSync('lake', args, { cwd: formalDir, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  if (result.error) {
    console.error(`${emitter}: could not run lake (${result.error.message}); elan must be on PATH`);
    process.exit(1);
  }
  if (result.status !== 0) {
    console.error(result.stderr || result.stdout);
    console.error(`${emitter}: lake ${args.join(' ')} failed`);
    process.exit(1);
  }
  return result.stdout;
}

const emitterSource = readFileSync(new URL(emitter, new URL('formal/dclutch-semantics/', repositoryRoot)), 'utf8');
const imported = [...emitterSource.matchAll(/^import[ \t]+([A-Za-z0-9_.]+)/gm)].map((match) => match[1]);
if (imported.length === 0) {
  console.error(`${emitter}: imports nothing; there is no schema to build`);
  process.exit(1);
}
for (const leanModule of [...new Set([...imported, ...modules])]) lake(['build', leanModule]);
const emitted = lake(['env', 'lean', '--run', emitter, ...emitterArguments]);

const expectedHeader = `// @generated by formal/dclutch-semantics/${emitter}; do not edit.`;
if (!emitted.startsWith(`${expectedHeader}\n`)) {
  console.error(`${emitter}: emitted module does not open with its own provenance header`);
  process.exit(1);
}

if (check) {
  let current;
  try {
    current = readFileSync(outputUrl, 'utf8');
  } catch {
    console.error(`${target} is missing; run the writer script to create it`);
    process.exit(1);
  }
  if (current !== emitted) {
    console.error(`${target} differs from what ${emitter} emits; regenerate it`);
    process.exit(1);
  }
} else {
  writeFileSync(fileURLToPath(outputUrl), emitted);
}
