#![no_std]
#![forbid(unsafe_code)]
#![deny(missing_docs)]

//! Generated fixed-layout semantic contract for canonical collateral custody.
//!
//! The contract is SDK-free, allocation-free, and total over hostile bytes.
//! It owns one transfer projection and one replay cursor shared by every
//! execution role. The composing adapter remains responsible for hashing,
//! Registry CPI and return-data provenance, PDA derivation, exact Realm and
//! token-state parsing, token/System CPI, account ownership, and transaction
//! rollback.

#[cfg(test)]
extern crate std;

#[allow(missing_docs)]
mod generated;

pub use generated::{
    ABI_VERSION_V1, CUSTODY_RECEIPT_BYTES_V1, CUSTODY_REPLAY_BYTES_V1, CUSTODY_REQUEST_BYTES_V1,
};

use generated::*;

/// The caller role is the canonical release-set role type, not a Custody DTO.
pub use dclutch_release_set_contract::ExecutionRoleV1 as CallerRoleV1;

/// Exact Custody transfer-authority PDA seed domain.
pub const CUSTODY_AUTHORITY_PDA_DOMAIN_V1: &[u8] = b"dclutch:custody-authority:v1";
/// Exact per-context Custody replay PDA seed domain.
pub const CUSTODY_REPLAY_PDA_DOMAIN_V1: &[u8] = b"dclutch:custody-replay:v1";
/// Exact token-vault PDA seed domain.
pub const CUSTODY_VAULT_PDA_DOMAIN_V1: &[u8] = b"dclutch:custody-vault:v1";
/// Domain separating the adapter's token/replay poststate commitment.
pub const CUSTODY_POSTSTATE_DOMAIN_V1: &[u8] = b"dclutch:custody-poststate:v1";

/// Exact request magic generated by the Lean ABI.
pub const CUSTODY_REQUEST_MAGIC_V1: [u8; 8] = *b"DCLCUSR1";
/// Exact replay-state magic generated by the Lean ABI.
pub const CUSTODY_REPLAY_MAGIC_V1: [u8; 8] = *b"DCLCUSS1";
/// Exact receipt magic generated by the Lean ABI.
pub const CUSTODY_RECEIPT_MAGIC_V1: [u8; 8] = *b"DCLCUSC1";

const RESERVED_REQUEST_BYTES: usize = 24;
const RESERVED_RECEIPT_BYTES: usize = 16;

/// Stable refusal returned by the canonical Custody contract.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Error {
    /// A wire did not have its one exact width.
    InvalidLength,
    /// Magic bytes selected another wire family.
    InvalidMagic,
    /// A wire named an unsupported schema.
    UnsupportedSchema,
    /// An operation discriminator was unknown.
    UnknownOperation,
    /// A caller execution role was unknown or selected Custody itself.
    UnknownCallerRole,
    /// A collateral-compartment tag was unknown.
    UnknownCompartment,
    /// Reserved or operation-inactive bytes were nonzero.
    NonCanonicalBytes,
    /// A required identity or digest was all zero.
    ZeroIdentity,
    /// Exact source and destination accounts aliased.
    AliasedTransferAccounts,
    /// An external token side lacked one exact nonzero semantic owner.
    ExternalActorRequired,
    /// Optimistic replay arithmetic overflowed or skipped a revision.
    RevisionOverflow,
    /// Request fields did not form the selected operation's exact shape.
    InvalidOperationShape,
    /// Persisted replay authority differed from the current request.
    ReplayBindingMismatch,
    /// The expected revision had already been consumed or was stale.
    ReplayRevisionMismatch,
    /// Exact transfer balance arithmetic overflowed or underflowed.
    BalanceArithmetic,
    /// A receipt did not acknowledge the exact request and poststate.
    ReceiptMismatch,
}

/// Result alias for Custody contract operations.
pub type Result<T> = core::result::Result<T, Error>;

/// Physical operation executed by Custody.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum OperationV1 {
    /// Create and bind one replay cursor from prepaid rent.
    InitializeReplay = 0,
    /// Create an empty Realm-selected token vault.
    OpenVault = 1,
    /// Move one positive exact collateral quantity.
    Transfer = 2,
    /// Close one empty Realm-selected token vault to its named rent refund.
    CloseVault = 3,
}

impl OperationV1 {
    fn decode(value: u8) -> Result<Self> {
        match value {
            0 => Ok(Self::InitializeReplay),
            1 => Ok(Self::OpenVault),
            2 => Ok(Self::Transfer),
            3 => Ok(Self::CloseVault),
            _ => Err(Error::UnknownOperation),
        }
    }
}

/// Economic compartment labeling one exact token account role.
///
/// These tags are evidence, not balances. The caller remains the sole owner of
/// its economic transition. Their distinct encodings prevent a receipt for
/// Hoard principal from being accepted as a fee, liveness, recovery, or rent
/// effect. Rent has no token-compartment tag at all.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum CompartmentV1 {
    /// Canonical inactive value for a non-transfer side.
    None = 0,
    /// Externally owned depositor, recipient, executor, or beneficiary.
    External = 1,
    /// General settlement inventory.
    Settlement = 2,
    /// Market Hoard principal, never fee or liveness capital.
    HoardPrincipal = 3,
    /// Direct or Dealer trading principal.
    TradingPrincipal = 4,
    /// Physically segregated realized fees.
    FeeVault = 5,
    /// Present funded-liveness capital.
    LivenessVault = 6,
    /// Series Ticket principal before Market creation.
    SeriesEscrow = 7,
    /// Present recovery-reserve capital.
    RecoveryReserve = 8,
}

impl CompartmentV1 {
    fn decode(value: u8) -> Result<Self> {
        match value {
            0 => Ok(Self::None),
            1 => Ok(Self::External),
            2 => Ok(Self::Settlement),
            3 => Ok(Self::HoardPrincipal),
            4 => Ok(Self::TradingPrincipal),
            5 => Ok(Self::FeeVault),
            6 => Ok(Self::LivenessVault),
            7 => Ok(Self::SeriesEscrow),
            8 => Ok(Self::RecoveryReserve),
            _ => Err(Error::UnknownCompartment),
        }
    }

    /// Return the canonical one-byte physical compartment seed.
    pub const fn tag(self) -> u8 {
        self as u8
    }
}

/// Canonical Custody transfer-authority seeds under the Custody program.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CustodyAuthoritySeedsV1 {
    market: [u8; 32],
    release_set: [u8; 32],
}

impl CustodyAuthoritySeedsV1 {
    /// Project the sole transfer-authority tuple from one request.
    pub const fn from_request(request: CustodyRequestV1) -> Self {
        Self {
            market: request.market,
            release_set: request.release_set,
        }
    }

    /// Borrow the exact ordered SVM seed slices, excluding the bump.
    pub fn as_slices(&self) -> [&[u8]; 3] {
        [
            CUSTODY_AUTHORITY_PDA_DOMAIN_V1,
            &self.market,
            &self.release_set,
        ]
    }
}

/// Canonical per-context replay seeds under the Custody program.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CustodyReplaySeedsV1 {
    market: [u8; 32],
    release_set: [u8; 32],
    context: [u8; 32],
}

impl CustodyReplaySeedsV1 {
    /// Project the sole replay tuple from one request.
    pub const fn from_request(request: CustodyRequestV1) -> Self {
        Self {
            market: request.market,
            release_set: request.release_set,
            context: request.context,
        }
    }

    /// Borrow the exact ordered SVM seed slices, excluding the bump.
    pub fn as_slices(&self) -> [&[u8]; 4] {
        [
            CUSTODY_REPLAY_PDA_DOMAIN_V1,
            &self.market,
            &self.release_set,
            &self.context,
        ]
    }
}

/// Canonical compartment/context Vault seeds under the Custody program.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CustodyVaultSeedsV1 {
    market: [u8; 32],
    release_set: [u8; 32],
    context: [u8; 32],
    compartment: [u8; 1],
}

impl CustodyVaultSeedsV1 {
    /// Construct the sole canonical Vault seed tuple from its semantic facts.
    pub const fn new(
        market: [u8; 32],
        release_set: [u8; 32],
        context: [u8; 32],
        compartment: CompartmentV1,
    ) -> Self {
        Self {
            market,
            release_set,
            context,
            compartment: [compartment.tag()],
        }
    }

    /// Project source- or destination-side Vault seeds.
    pub const fn from_request(request: CustodyRequestV1, source: bool) -> Self {
        Self::new(
            request.market,
            request.release_set,
            if source {
                request.source_vault_context
            } else {
                request.destination_vault_context
            },
            if source {
                request.source_compartment
            } else {
                request.destination_compartment
            },
        )
    }

    /// Borrow the exact ordered SVM seed slices, excluding the bump.
    pub fn as_slices(&self) -> [&[u8]; 5] {
        [
            CUSTODY_VAULT_PDA_DOMAIN_V1,
            &self.market,
            &self.release_set,
            &self.context,
            &self.compartment,
        ]
    }
}

/// Caller-owned exact semantic context carried through Custody unchanged.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ContextV1 {
    /// Optional best-valid-submitted candidate identity.
    pub candidate: [u8; 32],
    /// Optional actor, holder, founder, or beneficiary identity.
    pub actor: [u8; 32],
    /// Optional order or Ticket identity.
    pub order: [u8; 32],
    /// SHA-256 of the caller's complete canonical parent packet.
    pub parent_request_digest: [u8; 32],
    /// Caller-defined replay nonce for a row or Ticket.
    pub order_nonce: u64,
    /// Market or resource generation.
    pub generation: u64,
    /// Page coordinate, zero when inapplicable.
    pub page_index: u32,
    /// Execution coordinate, zero when inapplicable.
    pub execution_index: u32,
    /// Ordered effect coordinate within one outer action.
    pub transfer_index: u16,
}

/// All exact coordinates of one canonical Custody request.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CustodyRequestV1 {
    /// Physical operation.
    pub operation: OperationV1,
    /// Registry role of the calling program.
    pub caller_role: CallerRoleV1,
    /// Source's economic compartment.
    pub source_compartment: CompartmentV1,
    /// Destination's economic compartment.
    pub destination_compartment: CompartmentV1,
    /// Immutable execution-release-set content identity.
    pub release_set: [u8; 32],
    /// Exact Market identity.
    pub market: [u8; 32],
    /// Exact immutable Realm content identity.
    pub realm: [u8; 32],
    /// Replay namespace, such as candidate, Ticket, or venue state identity.
    pub context: [u8; 32],
    /// Exact selected caller program.
    pub caller_program: [u8; 32],
    /// Caller-owned semantic coordinates.
    pub semantic: ContextV1,
    /// Exact source token account, or zero for inactive operations.
    pub source: [u8; 32],
    /// Exact destination token account, or zero for inactive operations.
    pub destination: [u8; 32],
    /// PDA namespace of a Custody-owned source, or zero for External/inactive.
    pub source_vault_context: [u8; 32],
    /// PDA namespace of a Custody-owned destination, or zero for External/inactive.
    pub destination_vault_context: [u8; 32],
    /// Exact Realm-selected collateral Mint.
    pub mint: [u8; 32],
    /// Exact Realm-selected Token or Token-2022 program.
    pub token_program: [u8; 32],
    /// Exact rent payer for account creation, otherwise zero.
    pub payer: [u8; 32],
    /// Exact lamport refund beneficiary, otherwise zero.
    pub rent_refund: [u8; 32],
    /// Optimistic replay revision before execution.
    pub expected_revision: u64,
    /// Required next revision; exactly expected plus one.
    pub resulting_revision: u64,
    /// Positive raw collateral atoms for Transfer, otherwise zero.
    pub amount: u64,
    /// Exact lamports used or recovered by account creation/close, never tokens.
    pub rent_lamports: u64,
}

impl CustodyRequestV1 {
    /// Hostile-decode one exact generated request.
    pub fn decode(input: &[u8]) -> Result<Self> {
        require_header(
            input,
            &CUSTODY_REQUEST_MAGIC_V1,
            CUSTODY_REQUEST_BYTES_V1,
            REQUEST_VERSION_OFFSET,
        )?;
        require_zero(input, REQUEST_RESERVED_OFFSET, RESERVED_REQUEST_BYTES)?;
        let value = Self {
            operation: OperationV1::decode(read_byte(input, REQUEST_OPERATION_OFFSET)?)?,
            caller_role: decode_caller_role(read_byte(input, REQUEST_CALLER_ROLE_OFFSET)?)?,
            source_compartment: CompartmentV1::decode(read_byte(
                input,
                REQUEST_SOURCE_COMPARTMENT_OFFSET,
            )?)?,
            destination_compartment: CompartmentV1::decode(read_byte(
                input,
                REQUEST_DESTINATION_COMPARTMENT_OFFSET,
            )?)?,
            release_set: read_array(input, REQUEST_RELEASE_SET_OFFSET)?,
            market: read_array(input, REQUEST_MARKET_OFFSET)?,
            realm: read_array(input, REQUEST_REALM_OFFSET)?,
            context: read_array(input, REQUEST_CONTEXT_OFFSET)?,
            caller_program: read_array(input, REQUEST_CALLER_PROGRAM_OFFSET)?,
            semantic: ContextV1 {
                candidate: read_array(input, REQUEST_CANDIDATE_OFFSET)?,
                actor: read_array(input, REQUEST_ACTOR_OFFSET)?,
                order: read_array(input, REQUEST_ORDER_OFFSET)?,
                parent_request_digest: read_array(input, REQUEST_PARENT_REQUEST_DIGEST_OFFSET)?,
                order_nonce: read_u64(input, REQUEST_ORDER_NONCE_OFFSET)?,
                generation: read_u64(input, REQUEST_GENERATION_OFFSET)?,
                page_index: read_u32(input, REQUEST_PAGE_INDEX_OFFSET)?,
                execution_index: read_u32(input, REQUEST_EXECUTION_INDEX_OFFSET)?,
                transfer_index: read_u16(input, REQUEST_TRANSFER_INDEX_OFFSET)?,
            },
            source: read_array(input, REQUEST_SOURCE_OFFSET)?,
            destination: read_array(input, REQUEST_DESTINATION_OFFSET)?,
            source_vault_context: read_array(input, REQUEST_SOURCE_VAULT_CONTEXT_OFFSET)?,
            destination_vault_context: read_array(input, REQUEST_DESTINATION_VAULT_CONTEXT_OFFSET)?,
            mint: read_array(input, REQUEST_MINT_OFFSET)?,
            token_program: read_array(input, REQUEST_TOKEN_PROGRAM_OFFSET)?,
            payer: read_array(input, REQUEST_PAYER_OFFSET)?,
            rent_refund: read_array(input, REQUEST_RENT_REFUND_OFFSET)?,
            expected_revision: read_u64(input, REQUEST_EXPECTED_REVISION_OFFSET)?,
            resulting_revision: read_u64(input, REQUEST_RESULTING_REVISION_OFFSET)?,
            amount: read_u64(input, REQUEST_AMOUNT_OFFSET)?,
            rent_lamports: read_u64(input, REQUEST_RENT_LAMPORTS_OFFSET)?,
        };
        value.validate()?;
        Ok(value)
    }

    /// Encode one exact generated request after validating its operation shape.
    pub fn to_bytes(self) -> Result<[u8; CUSTODY_REQUEST_BYTES_V1]> {
        self.validate()?;
        let mut output = [0; CUSTODY_REQUEST_BYTES_V1];
        put(&mut output, 0, &CUSTODY_REQUEST_MAGIC_V1)?;
        put_u16(&mut output, REQUEST_VERSION_OFFSET, ABI_VERSION_V1)?;
        put_byte(&mut output, REQUEST_OPERATION_OFFSET, self.operation as u8)?;
        put_byte(
            &mut output,
            REQUEST_CALLER_ROLE_OFFSET,
            self.caller_role as u8,
        )?;
        put_byte(
            &mut output,
            REQUEST_SOURCE_COMPARTMENT_OFFSET,
            self.source_compartment as u8,
        )?;
        put_byte(
            &mut output,
            REQUEST_DESTINATION_COMPARTMENT_OFFSET,
            self.destination_compartment as u8,
        )?;
        put_u16(
            &mut output,
            REQUEST_TRANSFER_INDEX_OFFSET,
            self.semantic.transfer_index,
        )?;
        for (offset, value) in [
            (REQUEST_RELEASE_SET_OFFSET, self.release_set),
            (REQUEST_MARKET_OFFSET, self.market),
            (REQUEST_REALM_OFFSET, self.realm),
            (REQUEST_CONTEXT_OFFSET, self.context),
            (REQUEST_CALLER_PROGRAM_OFFSET, self.caller_program),
            (REQUEST_CANDIDATE_OFFSET, self.semantic.candidate),
            (REQUEST_ACTOR_OFFSET, self.semantic.actor),
            (REQUEST_ORDER_OFFSET, self.semantic.order),
            (
                REQUEST_PARENT_REQUEST_DIGEST_OFFSET,
                self.semantic.parent_request_digest,
            ),
            (REQUEST_SOURCE_OFFSET, self.source),
            (REQUEST_DESTINATION_OFFSET, self.destination),
            (
                REQUEST_SOURCE_VAULT_CONTEXT_OFFSET,
                self.source_vault_context,
            ),
            (
                REQUEST_DESTINATION_VAULT_CONTEXT_OFFSET,
                self.destination_vault_context,
            ),
            (REQUEST_MINT_OFFSET, self.mint),
            (REQUEST_TOKEN_PROGRAM_OFFSET, self.token_program),
            (REQUEST_PAYER_OFFSET, self.payer),
            (REQUEST_RENT_REFUND_OFFSET, self.rent_refund),
        ] {
            put(&mut output, offset, &value)?;
        }
        for (offset, value) in [
            (REQUEST_EXPECTED_REVISION_OFFSET, self.expected_revision),
            (REQUEST_RESULTING_REVISION_OFFSET, self.resulting_revision),
            (REQUEST_ORDER_NONCE_OFFSET, self.semantic.order_nonce),
            (REQUEST_GENERATION_OFFSET, self.semantic.generation),
            (REQUEST_AMOUNT_OFFSET, self.amount),
            (REQUEST_RENT_LAMPORTS_OFFSET, self.rent_lamports),
        ] {
            put_u64(&mut output, offset, value)?;
        }
        put_u32(
            &mut output,
            REQUEST_PAGE_INDEX_OFFSET,
            self.semantic.page_index,
        )?;
        put_u32(
            &mut output,
            REQUEST_EXECUTION_INDEX_OFFSET,
            self.semantic.execution_index,
        )?;
        Ok(output)
    }

    /// Validate common identities, exact revision advance, and operation fields.
    pub fn validate(self) -> Result<()> {
        for value in [
            self.release_set,
            self.market,
            self.realm,
            self.context,
            self.caller_program,
            self.semantic.parent_request_digest,
        ] {
            require_nonzero(&value)?;
        }
        if self.caller_role == CallerRoleV1::Custody {
            return Err(Error::UnknownCallerRole);
        }
        if self.expected_revision.checked_add(1) != Some(self.resulting_revision) {
            return Err(Error::RevisionOverflow);
        }
        match self.operation {
            OperationV1::InitializeReplay => {
                if self.expected_revision != 0
                    || self.resulting_revision != 1
                    || self.source_compartment != CompartmentV1::None
                    || self.destination_compartment != CompartmentV1::None
                    || !is_zero(&self.source)
                    || !is_zero(&self.destination)
                    || !is_zero(&self.source_vault_context)
                    || !is_zero(&self.destination_vault_context)
                    || !is_zero(&self.mint)
                    || !is_zero(&self.token_program)
                    || is_zero(&self.payer)
                    || is_zero(&self.rent_refund)
                    || self.amount != 0
                    || self.rent_lamports == 0
                {
                    return Err(Error::InvalidOperationShape);
                }
            }
            OperationV1::OpenVault => {
                if self.source_compartment != CompartmentV1::None
                    || self.destination_compartment == CompartmentV1::None
                    || self.destination_compartment == CompartmentV1::External
                    || !is_zero(&self.source)
                    || is_zero(&self.destination)
                    || !is_zero(&self.source_vault_context)
                    || is_zero(&self.destination_vault_context)
                    || self.destination_vault_context != self.context
                    || is_zero(&self.mint)
                    || is_zero(&self.token_program)
                    || is_zero(&self.payer)
                    || is_zero(&self.rent_refund)
                    || self.amount != 0
                    || self.rent_lamports == 0
                {
                    return Err(Error::InvalidOperationShape);
                }
            }
            OperationV1::Transfer => {
                if self.source_compartment == CompartmentV1::None
                    || self.destination_compartment == CompartmentV1::None
                    || is_zero(&self.source)
                    || is_zero(&self.destination)
                    || is_zero(&self.mint)
                    || is_zero(&self.token_program)
                    || !is_zero(&self.payer)
                    || !is_zero(&self.rent_refund)
                    || self.amount == 0
                    || self.rent_lamports != 0
                {
                    return Err(Error::InvalidOperationShape);
                }
                if (self.source_compartment == CompartmentV1::External)
                    != is_zero(&self.source_vault_context)
                    || (self.destination_compartment == CompartmentV1::External)
                        != is_zero(&self.destination_vault_context)
                {
                    return Err(Error::InvalidOperationShape);
                }
                if (self.source_compartment == CompartmentV1::External
                    || self.destination_compartment == CompartmentV1::External)
                    && is_zero(&self.semantic.actor)
                {
                    return Err(Error::ExternalActorRequired);
                }
                if self.source == self.destination {
                    return Err(Error::AliasedTransferAccounts);
                }
            }
            OperationV1::CloseVault => {
                if self.source_compartment == CompartmentV1::None
                    || self.source_compartment == CompartmentV1::External
                    || self.destination_compartment != CompartmentV1::None
                    || is_zero(&self.source)
                    || !is_zero(&self.destination)
                    || is_zero(&self.source_vault_context)
                    || !is_zero(&self.destination_vault_context)
                    || self.source_vault_context != self.context
                    || is_zero(&self.mint)
                    || is_zero(&self.token_program)
                    || !is_zero(&self.payer)
                    || is_zero(&self.rent_refund)
                    || self.amount != 0
                    || self.rent_lamports == 0
                {
                    return Err(Error::InvalidOperationShape);
                }
            }
        }
        Ok(())
    }
}

/// Persisted replay authority for one Market/context/release tuple.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CustodyReplayV1 {
    /// Registry role of the sole calling program.
    pub caller_role: CallerRoleV1,
    /// Immutable selected release set.
    pub release_set: [u8; 32],
    /// Exact Market identity.
    pub market: [u8; 32],
    /// Exact immutable Realm identity.
    pub realm: [u8; 32],
    /// Exact replay context identity.
    pub context: [u8; 32],
    /// Exact selected caller program.
    pub caller_program: [u8; 32],
    /// Immutable lamport refund beneficiary for this cursor.
    pub rent_refund: [u8; 32],
    /// Next required request revision.
    pub next_revision: u64,
    /// Market or resource generation.
    pub generation: u64,
    /// Digest of the last accepted exact request.
    pub last_request_digest: [u8; 32],
    /// Commitment to the last token/replay poststate.
    pub last_poststate_commitment: [u8; 32],
}

impl CustodyReplayV1 {
    /// Initialize the first replay state from an exact initialization request.
    pub fn initialize(
        request: CustodyRequestV1,
        request_digest: [u8; 32],
        poststate_commitment: [u8; 32],
    ) -> Result<Self> {
        request.validate()?;
        if request.operation != OperationV1::InitializeReplay
            || is_zero(&request_digest)
            || is_zero(&poststate_commitment)
        {
            return Err(Error::InvalidOperationShape);
        }
        Ok(Self {
            caller_role: request.caller_role,
            release_set: request.release_set,
            market: request.market,
            realm: request.realm,
            context: request.context,
            caller_program: request.caller_program,
            rent_refund: request.rent_refund,
            next_revision: request.resulting_revision,
            generation: request.semantic.generation,
            last_request_digest: request_digest,
            last_poststate_commitment: poststate_commitment,
        })
    }

    /// Hostile-decode one exact replay account.
    pub fn decode(input: &[u8]) -> Result<Self> {
        require_header(
            input,
            &CUSTODY_REPLAY_MAGIC_V1,
            CUSTODY_REPLAY_BYTES_V1,
            REPLAY_VERSION_OFFSET,
        )?;
        if read_byte(input, REPLAY_STATUS_OFFSET)? != 1 {
            return Err(Error::NonCanonicalBytes);
        }
        require_zero(input, REPLAY_RESERVED_HEADER_OFFSET, 4)?;
        let value = Self {
            caller_role: decode_caller_role(read_byte(input, REPLAY_CALLER_ROLE_OFFSET)?)?,
            release_set: read_array(input, REPLAY_RELEASE_SET_OFFSET)?,
            market: read_array(input, REPLAY_MARKET_OFFSET)?,
            realm: read_array(input, REPLAY_REALM_OFFSET)?,
            context: read_array(input, REPLAY_CONTEXT_OFFSET)?,
            caller_program: read_array(input, REPLAY_CALLER_PROGRAM_OFFSET)?,
            rent_refund: read_array(input, REPLAY_RENT_REFUND_OFFSET)?,
            next_revision: read_u64(input, REPLAY_NEXT_REVISION_OFFSET)?,
            generation: read_u64(input, REPLAY_GENERATION_OFFSET)?,
            last_request_digest: read_array(input, REPLAY_LAST_REQUEST_DIGEST_OFFSET)?,
            last_poststate_commitment: read_array(input, REPLAY_LAST_POSTSTATE_COMMITMENT_OFFSET)?,
        };
        value.validate()?;
        Ok(value)
    }

    /// Encode one exact replay account.
    pub fn to_bytes(self) -> Result<[u8; CUSTODY_REPLAY_BYTES_V1]> {
        self.validate()?;
        let mut output = [0; CUSTODY_REPLAY_BYTES_V1];
        put(&mut output, 0, &CUSTODY_REPLAY_MAGIC_V1)?;
        put_u16(&mut output, REPLAY_VERSION_OFFSET, ABI_VERSION_V1)?;
        put_byte(&mut output, REPLAY_STATUS_OFFSET, 1)?;
        put_byte(
            &mut output,
            REPLAY_CALLER_ROLE_OFFSET,
            self.caller_role as u8,
        )?;
        for (offset, value) in [
            (REPLAY_RELEASE_SET_OFFSET, self.release_set),
            (REPLAY_MARKET_OFFSET, self.market),
            (REPLAY_REALM_OFFSET, self.realm),
            (REPLAY_CONTEXT_OFFSET, self.context),
            (REPLAY_CALLER_PROGRAM_OFFSET, self.caller_program),
            (REPLAY_RENT_REFUND_OFFSET, self.rent_refund),
            (REPLAY_LAST_REQUEST_DIGEST_OFFSET, self.last_request_digest),
            (
                REPLAY_LAST_POSTSTATE_COMMITMENT_OFFSET,
                self.last_poststate_commitment,
            ),
        ] {
            put(&mut output, offset, &value)?;
        }
        put_u64(&mut output, REPLAY_NEXT_REVISION_OFFSET, self.next_revision)?;
        put_u64(&mut output, REPLAY_GENERATION_OFFSET, self.generation)?;
        Ok(output)
    }

    /// Advance replay only for the exact next request and poststate commitment.
    pub fn advance(
        self,
        request: CustodyRequestV1,
        request_digest: [u8; 32],
        poststate_commitment: [u8; 32],
    ) -> Result<Self> {
        request.validate()?;
        if request.operation == OperationV1::InitializeReplay
            || request.caller_role != self.caller_role
            || request.release_set != self.release_set
            || request.market != self.market
            || request.realm != self.realm
            || request.context != self.context
            || request.caller_program != self.caller_program
            || request.semantic.generation != self.generation
        {
            return Err(Error::ReplayBindingMismatch);
        }
        if request.expected_revision != self.next_revision {
            return Err(Error::ReplayRevisionMismatch);
        }
        if matches!(
            request.operation,
            OperationV1::OpenVault | OperationV1::CloseVault
        ) && request.rent_refund != self.rent_refund
        {
            return Err(Error::ReplayBindingMismatch);
        }
        if is_zero(&request_digest) || is_zero(&poststate_commitment) {
            return Err(Error::InvalidOperationShape);
        }
        Ok(Self {
            next_revision: request.resulting_revision,
            last_request_digest: request_digest,
            last_poststate_commitment: poststate_commitment,
            ..self
        })
    }

    fn validate(self) -> Result<()> {
        for value in [
            self.release_set,
            self.market,
            self.realm,
            self.context,
            self.caller_program,
            self.rent_refund,
            self.last_request_digest,
            self.last_poststate_commitment,
        ] {
            require_nonzero(&value)?;
        }
        if self.next_revision == 0 {
            return Err(Error::ReplayRevisionMismatch);
        }
        Ok(())
    }
}

/// Exact token and replay poststate facts committed by a receipt.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ReceiptEvidenceV1 {
    /// Source balance before CPI, or zero when inactive.
    pub source_before: u64,
    /// Source balance after CPI, or zero when inactive.
    pub source_after: u64,
    /// Destination balance before CPI, or zero when inactive.
    pub destination_before: u64,
    /// Destination balance after CPI, or zero when inactive.
    pub destination_after: u64,
    /// SHA-256 commitment to exact token and replay poststate.
    pub poststate_commitment: [u8; 32],
    /// SHA-256 of exact committed replay-state bytes.
    pub replay_state_digest: [u8; 32],
}

/// Immediate producer-authenticated acknowledgement of one Custody request.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CustodyReceiptV1 {
    /// Physical operation acknowledged.
    pub operation: OperationV1,
    /// Calling Registry role acknowledged.
    pub caller_role: CallerRoleV1,
    /// Exact source compartment acknowledged.
    pub source_compartment: CompartmentV1,
    /// Exact destination compartment acknowledged.
    pub destination_compartment: CompartmentV1,
    /// Exact ordered transfer index acknowledged.
    pub transfer_index: u16,
    /// Exact release set acknowledged.
    pub release_set: [u8; 32],
    /// Exact Market acknowledged.
    pub market: [u8; 32],
    /// Exact replay context acknowledged.
    pub context: [u8; 32],
    /// Exact parent packet digest acknowledged.
    pub parent_request_digest: [u8; 32],
    /// SHA-256 of the complete exact Custody request.
    pub request_digest: [u8; 32],
    /// Exact source account acknowledged.
    pub source: [u8; 32],
    /// Exact destination account acknowledged.
    pub destination: [u8; 32],
    /// Revision consumed.
    pub expected_revision: u64,
    /// Revision committed.
    pub resulting_revision: u64,
    /// Exact token and replay poststate evidence.
    pub evidence: ReceiptEvidenceV1,
    /// Exact collateral amount acknowledged.
    pub amount: u64,
    /// Exact lamport amount acknowledged independently from collateral.
    pub rent_lamports: u64,
}

impl CustodyReceiptV1 {
    /// Construct a receipt and prove balance deltas for the selected operation.
    pub fn new(
        request: CustodyRequestV1,
        request_digest: [u8; 32],
        evidence: ReceiptEvidenceV1,
    ) -> Result<Self> {
        request.validate()?;
        if is_zero(&request_digest)
            || is_zero(&evidence.poststate_commitment)
            || is_zero(&evidence.replay_state_digest)
        {
            return Err(Error::ReceiptMismatch);
        }
        match request.operation {
            OperationV1::Transfer => {
                if evidence.source_before.checked_sub(request.amount) != Some(evidence.source_after)
                    || evidence.destination_before.checked_add(request.amount)
                        != Some(evidence.destination_after)
                {
                    return Err(Error::BalanceArithmetic);
                }
            }
            OperationV1::InitializeReplay | OperationV1::OpenVault | OperationV1::CloseVault => {
                if evidence.source_before != 0
                    || evidence.source_after != 0
                    || evidence.destination_before != 0
                    || evidence.destination_after != 0
                {
                    return Err(Error::ReceiptMismatch);
                }
            }
        }
        Ok(Self {
            operation: request.operation,
            caller_role: request.caller_role,
            source_compartment: request.source_compartment,
            destination_compartment: request.destination_compartment,
            transfer_index: request.semantic.transfer_index,
            release_set: request.release_set,
            market: request.market,
            context: request.context,
            parent_request_digest: request.semantic.parent_request_digest,
            request_digest,
            source: request.source,
            destination: request.destination,
            expected_revision: request.expected_revision,
            resulting_revision: request.resulting_revision,
            evidence,
            amount: request.amount,
            rent_lamports: request.rent_lamports,
        })
    }

    /// Hostile-decode one exact receipt.
    pub fn decode(input: &[u8]) -> Result<Self> {
        require_header(
            input,
            &CUSTODY_RECEIPT_MAGIC_V1,
            CUSTODY_RECEIPT_BYTES_V1,
            RECEIPT_VERSION_OFFSET,
        )?;
        require_zero(input, RECEIPT_RESERVED_OFFSET, RESERVED_RECEIPT_BYTES)?;
        Ok(Self {
            operation: OperationV1::decode(read_byte(input, RECEIPT_OPERATION_OFFSET)?)?,
            caller_role: decode_caller_role(read_byte(input, RECEIPT_CALLER_ROLE_OFFSET)?)?,
            source_compartment: CompartmentV1::decode(read_byte(
                input,
                RECEIPT_SOURCE_COMPARTMENT_OFFSET,
            )?)?,
            destination_compartment: CompartmentV1::decode(read_byte(
                input,
                RECEIPT_DESTINATION_COMPARTMENT_OFFSET,
            )?)?,
            transfer_index: read_u16(input, RECEIPT_TRANSFER_INDEX_OFFSET)?,
            release_set: read_array(input, RECEIPT_RELEASE_SET_OFFSET)?,
            market: read_array(input, RECEIPT_MARKET_OFFSET)?,
            context: read_array(input, RECEIPT_CONTEXT_OFFSET)?,
            parent_request_digest: read_array(input, RECEIPT_PARENT_REQUEST_DIGEST_OFFSET)?,
            request_digest: read_array(input, RECEIPT_REQUEST_DIGEST_OFFSET)?,
            source: read_array(input, RECEIPT_SOURCE_OFFSET)?,
            destination: read_array(input, RECEIPT_DESTINATION_OFFSET)?,
            expected_revision: read_u64(input, RECEIPT_EXPECTED_REVISION_OFFSET)?,
            resulting_revision: read_u64(input, RECEIPT_RESULTING_REVISION_OFFSET)?,
            evidence: ReceiptEvidenceV1 {
                source_before: read_u64(input, RECEIPT_SOURCE_BEFORE_OFFSET)?,
                source_after: read_u64(input, RECEIPT_SOURCE_AFTER_OFFSET)?,
                destination_before: read_u64(input, RECEIPT_DESTINATION_BEFORE_OFFSET)?,
                destination_after: read_u64(input, RECEIPT_DESTINATION_AFTER_OFFSET)?,
                poststate_commitment: read_array(input, RECEIPT_POSTSTATE_COMMITMENT_OFFSET)?,
                replay_state_digest: read_array(input, RECEIPT_REPLAY_STATE_DIGEST_OFFSET)?,
            },
            amount: read_u64(input, RECEIPT_AMOUNT_OFFSET)?,
            rent_lamports: read_u64(input, RECEIPT_RENT_LAMPORTS_OFFSET)?,
        })
    }

    /// Encode one exact receipt.
    pub fn to_bytes(self) -> Result<[u8; CUSTODY_RECEIPT_BYTES_V1]> {
        if is_zero(&self.request_digest)
            || is_zero(&self.evidence.poststate_commitment)
            || is_zero(&self.evidence.replay_state_digest)
        {
            return Err(Error::ReceiptMismatch);
        }
        let mut output = [0; CUSTODY_RECEIPT_BYTES_V1];
        put(&mut output, 0, &CUSTODY_RECEIPT_MAGIC_V1)?;
        put_u16(&mut output, RECEIPT_VERSION_OFFSET, ABI_VERSION_V1)?;
        put_byte(&mut output, RECEIPT_OPERATION_OFFSET, self.operation as u8)?;
        put_byte(
            &mut output,
            RECEIPT_CALLER_ROLE_OFFSET,
            self.caller_role as u8,
        )?;
        put_byte(
            &mut output,
            RECEIPT_SOURCE_COMPARTMENT_OFFSET,
            self.source_compartment as u8,
        )?;
        put_byte(
            &mut output,
            RECEIPT_DESTINATION_COMPARTMENT_OFFSET,
            self.destination_compartment as u8,
        )?;
        put_u16(
            &mut output,
            RECEIPT_TRANSFER_INDEX_OFFSET,
            self.transfer_index,
        )?;
        for (offset, value) in [
            (RECEIPT_RELEASE_SET_OFFSET, self.release_set),
            (RECEIPT_MARKET_OFFSET, self.market),
            (RECEIPT_CONTEXT_OFFSET, self.context),
            (
                RECEIPT_PARENT_REQUEST_DIGEST_OFFSET,
                self.parent_request_digest,
            ),
            (RECEIPT_REQUEST_DIGEST_OFFSET, self.request_digest),
            (RECEIPT_SOURCE_OFFSET, self.source),
            (RECEIPT_DESTINATION_OFFSET, self.destination),
            (
                RECEIPT_POSTSTATE_COMMITMENT_OFFSET,
                self.evidence.poststate_commitment,
            ),
            (
                RECEIPT_REPLAY_STATE_DIGEST_OFFSET,
                self.evidence.replay_state_digest,
            ),
        ] {
            put(&mut output, offset, &value)?;
        }
        for (offset, value) in [
            (RECEIPT_EXPECTED_REVISION_OFFSET, self.expected_revision),
            (RECEIPT_RESULTING_REVISION_OFFSET, self.resulting_revision),
            (RECEIPT_SOURCE_BEFORE_OFFSET, self.evidence.source_before),
            (RECEIPT_SOURCE_AFTER_OFFSET, self.evidence.source_after),
            (
                RECEIPT_DESTINATION_BEFORE_OFFSET,
                self.evidence.destination_before,
            ),
            (
                RECEIPT_DESTINATION_AFTER_OFFSET,
                self.evidence.destination_after,
            ),
            (RECEIPT_AMOUNT_OFFSET, self.amount),
            (RECEIPT_RENT_LAMPORTS_OFFSET, self.rent_lamports),
        ] {
            put_u64(&mut output, offset, value)?;
        }
        Ok(output)
    }

    /// Require this receipt to be the exact acknowledgement of `request`.
    pub fn verify_for(
        self,
        request: CustodyRequestV1,
        request_digest: [u8; 32],
        replay_state_digest: [u8; 32],
    ) -> Result<()> {
        let expected = Self::new(request, request_digest, self.evidence)?;
        if self != expected || self.evidence.replay_state_digest != replay_state_digest {
            return Err(Error::ReceiptMismatch);
        }
        Ok(())
    }
}

fn require_header(input: &[u8], magic: &[u8; 8], width: usize, version: usize) -> Result<()> {
    if input.len() != width {
        return Err(Error::InvalidLength);
    }
    if input.get(..8) != Some(magic.as_slice()) {
        return Err(Error::InvalidMagic);
    }
    if read_u16(input, version)? != ABI_VERSION_V1 {
        return Err(Error::UnsupportedSchema);
    }
    Ok(())
}

fn decode_caller_role(value: u8) -> Result<CallerRoleV1> {
    match value {
        0 => Ok(CallerRoleV1::Core),
        1 => Ok(CallerRoleV1::Claims),
        2 => Ok(CallerRoleV1::Trading),
        3 => Ok(CallerRoleV1::Resolution),
        _ => Err(Error::UnknownCallerRole),
    }
}

fn require_nonzero(value: &[u8; 32]) -> Result<()> {
    if is_zero(value) {
        Err(Error::ZeroIdentity)
    } else {
        Ok(())
    }
}

fn is_zero(value: &[u8; 32]) -> bool {
    value.iter().all(|byte| *byte == 0)
}

fn require_zero(input: &[u8], offset: usize, width: usize) -> Result<()> {
    if slice(input, offset, width)?.iter().any(|byte| *byte != 0) {
        return Err(Error::NonCanonicalBytes);
    }
    Ok(())
}

fn read_byte(input: &[u8], offset: usize) -> Result<u8> {
    input.get(offset).copied().ok_or(Error::InvalidLength)
}

fn read_u16(input: &[u8], offset: usize) -> Result<u16> {
    Ok(u16::from_le_bytes(read_array(input, offset)?))
}

fn read_u32(input: &[u8], offset: usize) -> Result<u32> {
    Ok(u32::from_le_bytes(read_array(input, offset)?))
}

fn read_u64(input: &[u8], offset: usize) -> Result<u64> {
    Ok(u64::from_le_bytes(read_array(input, offset)?))
}

fn read_array<const N: usize>(input: &[u8], offset: usize) -> Result<[u8; N]> {
    slice(input, offset, N)?
        .try_into()
        .map_err(|_| Error::InvalidLength)
}

fn slice(input: &[u8], offset: usize, width: usize) -> Result<&[u8]> {
    let end = offset.checked_add(width).ok_or(Error::InvalidLength)?;
    input.get(offset..end).ok_or(Error::InvalidLength)
}

fn put(output: &mut [u8], offset: usize, value: &[u8]) -> Result<()> {
    let end = offset
        .checked_add(value.len())
        .ok_or(Error::InvalidLength)?;
    let target = output.get_mut(offset..end).ok_or(Error::InvalidLength)?;
    target.copy_from_slice(value);
    Ok(())
}

fn put_byte(output: &mut [u8], offset: usize, value: u8) -> Result<()> {
    let target = output.get_mut(offset).ok_or(Error::InvalidLength)?;
    *target = value;
    Ok(())
}

fn put_u16(output: &mut [u8], offset: usize, value: u16) -> Result<()> {
    put(output, offset, &value.to_le_bytes())
}

fn put_u32(output: &mut [u8], offset: usize, value: u32) -> Result<()> {
    put(output, offset, &value.to_le_bytes())
}

fn put_u64(output: &mut [u8], offset: usize, value: u64) -> Result<()> {
    put(output, offset, &value.to_le_bytes())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn id(value: u8) -> [u8; 32] {
        [value; 32]
    }

    fn semantic() -> ContextV1 {
        ContextV1 {
            candidate: id(6),
            actor: id(7),
            order: id(8),
            parent_request_digest: id(9),
            order_nonce: 11,
            generation: 12,
            page_index: 13,
            execution_index: 14,
            transfer_index: 2,
        }
    }

    fn transfer() -> CustodyRequestV1 {
        CustodyRequestV1 {
            operation: OperationV1::Transfer,
            caller_role: CallerRoleV1::Trading,
            source_compartment: CompartmentV1::Settlement,
            destination_compartment: CompartmentV1::HoardPrincipal,
            release_set: id(1),
            market: id(2),
            realm: id(3),
            context: id(4),
            caller_program: id(5),
            semantic: semantic(),
            source: id(10),
            destination: id(11),
            source_vault_context: id(14),
            destination_vault_context: id(15),
            mint: id(12),
            token_program: id(13),
            payer: [0; 32],
            rent_refund: [0; 32],
            expected_revision: 4,
            resulting_revision: 5,
            amount: 17,
            rent_lamports: 0,
        }
    }

    fn initialize() -> CustodyRequestV1 {
        CustodyRequestV1 {
            operation: OperationV1::InitializeReplay,
            caller_role: CallerRoleV1::Trading,
            source_compartment: CompartmentV1::None,
            destination_compartment: CompartmentV1::None,
            release_set: id(1),
            market: id(2),
            realm: id(3),
            context: id(4),
            caller_program: id(5),
            semantic: semantic(),
            source: [0; 32],
            destination: [0; 32],
            source_vault_context: [0; 32],
            destination_vault_context: [0; 32],
            mint: [0; 32],
            token_program: [0; 32],
            payer: id(20),
            rent_refund: id(21),
            expected_revision: 0,
            resulting_revision: 1,
            amount: 0,
            rent_lamports: 2_000_000,
        }
    }

    #[test]
    fn generated_request_roundtrips_and_refuses_reserved_bytes() {
        let request = transfer();
        let bytes = request.to_bytes().expect("request");
        assert_eq!(CustodyRequestV1::decode(&bytes), Ok(request));
        assert_eq!(bytes.len(), CUSTODY_REQUEST_BYTES_V1);
        let mut hostile = bytes;
        if let Some(byte) = hostile.get_mut(REQUEST_RESERVED_OFFSET) {
            *byte = 1;
        }
        assert_eq!(
            CustodyRequestV1::decode(&hostile),
            Err(Error::NonCanonicalBytes)
        );
    }

    #[test]
    fn exact_operation_shapes_refuse_alias_zero_and_rent_conflation() {
        let mut hostile = transfer();
        hostile.destination = hostile.source;
        assert_eq!(hostile.validate(), Err(Error::AliasedTransferAccounts));
        let mut hostile = transfer();
        hostile.amount = 0;
        assert_eq!(hostile.validate(), Err(Error::InvalidOperationShape));
        let mut hostile = transfer();
        hostile.rent_lamports = 1;
        assert_eq!(hostile.validate(), Err(Error::InvalidOperationShape));
        let mut hostile = transfer();
        hostile.resulting_revision = 6;
        assert_eq!(hostile.validate(), Err(Error::RevisionOverflow));
        let mut hostile = transfer();
        hostile.expected_revision = u64::MAX;
        hostile.resulting_revision = 0;
        assert_eq!(hostile.validate(), Err(Error::RevisionOverflow));
        let mut hostile = transfer();
        hostile.caller_role = CallerRoleV1::Custody;
        assert_eq!(hostile.validate(), Err(Error::UnknownCallerRole));
        let mut hostile = transfer();
        hostile.source_compartment = CompartmentV1::External;
        hostile.source_vault_context = [0; 32];
        hostile.semantic.actor = [0; 32];
        assert_eq!(hostile.validate(), Err(Error::ExternalActorRequired));
    }

    #[test]
    fn replay_is_bound_to_role_release_market_realm_context_and_generation() {
        let init = initialize();
        let state = CustodyReplayV1::initialize(init, id(30), id(31)).expect("state");
        let bytes = state.to_bytes().expect("state bytes");
        assert_eq!(CustodyReplayV1::decode(&bytes), Ok(state));

        let mut next = transfer();
        next.expected_revision = 1;
        next.resulting_revision = 2;
        let advanced = state.advance(next, id(32), id(33)).expect("advance");
        assert_eq!(advanced.next_revision, 2);
        assert_eq!(advanced.last_request_digest, id(32));

        let mut stale = next;
        stale.expected_revision = 0;
        stale.resulting_revision = 1;
        assert_eq!(
            state.advance(stale, id(32), id(33)),
            Err(Error::ReplayRevisionMismatch)
        );
        let mut substituted = next;
        substituted.realm = id(99);
        assert_eq!(
            state.advance(substituted, id(32), id(33)),
            Err(Error::ReplayBindingMismatch)
        );
    }

    #[test]
    fn receipt_commits_exact_balances_request_and_replay_state() {
        let request = transfer();
        let evidence = ReceiptEvidenceV1 {
            source_before: 100,
            source_after: 83,
            destination_before: 3,
            destination_after: 20,
            poststate_commitment: id(40),
            replay_state_digest: id(41),
        };
        let receipt = CustodyReceiptV1::new(request, id(42), evidence).expect("receipt");
        let bytes = receipt.to_bytes().expect("receipt bytes");
        assert_eq!(CustodyReceiptV1::decode(&bytes), Ok(receipt));
        assert_eq!(receipt.verify_for(request, id(42), id(41)), Ok(()));
        assert_eq!(
            receipt.verify_for(request, id(43), id(41)),
            Err(Error::ReceiptMismatch)
        );

        let hostile = ReceiptEvidenceV1 {
            destination_after: 21,
            ..evidence
        };
        assert_eq!(
            CustodyReceiptV1::new(request, id(42), hostile),
            Err(Error::BalanceArithmetic)
        );
    }

    #[test]
    fn vault_seed_constructor_is_exact_and_is_the_only_request_projection() {
        let request = transfer();
        let source = CustodyVaultSeedsV1::new(
            request.market,
            request.release_set,
            request.source_vault_context,
            request.source_compartment,
        );
        let destination = CustodyVaultSeedsV1::new(
            request.market,
            request.release_set,
            request.destination_vault_context,
            request.destination_compartment,
        );
        assert_eq!(CustodyVaultSeedsV1::from_request(request, true), source);
        assert_eq!(
            CustodyVaultSeedsV1::from_request(request, false),
            destination
        );

        let source_compartment = [request.source_compartment.tag()];
        assert_eq!(
            source.as_slices(),
            [
                CUSTODY_VAULT_PDA_DOMAIN_V1,
                request.market.as_slice(),
                request.release_set.as_slice(),
                request.source_vault_context.as_slice(),
                source_compartment.as_slice(),
            ]
        );

        for hostile in [
            CustodyVaultSeedsV1::new(
                id(99),
                request.release_set,
                request.source_vault_context,
                request.source_compartment,
            ),
            CustodyVaultSeedsV1::new(
                request.market,
                id(99),
                request.source_vault_context,
                request.source_compartment,
            ),
            CustodyVaultSeedsV1::new(
                request.market,
                request.release_set,
                id(99),
                request.source_compartment,
            ),
            CustodyVaultSeedsV1::new(
                request.market,
                request.release_set,
                request.source_vault_context,
                CompartmentV1::FeeVault,
            ),
        ] {
            assert_ne!(hostile, source);
            assert_ne!(hostile.as_slices(), source.as_slices());
        }
    }

    #[test]
    fn protected_compartment_tags_are_physically_distinct() {
        assert_ne!(
            CompartmentV1::HoardPrincipal as u8,
            CompartmentV1::FeeVault as u8
        );
        assert_ne!(
            CompartmentV1::HoardPrincipal as u8,
            CompartmentV1::LivenessVault as u8
        );
        assert_ne!(
            CompartmentV1::HoardPrincipal as u8,
            CompartmentV1::RecoveryReserve as u8
        );
    }
}
