#!/bin/sh
set -eu

crate_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_dir=$(CDPATH= cd -- "$crate_dir/../.." && pwd)
formal_dir="$repo_dir/formal/dclutch-semantics"
accepted="$crate_dir/tests/generated/basis_corpus_v3.rs"
temporary=$(mktemp "${TMPDIR:-/tmp}/dclutch-product-basis-corpus-v3.XXXXXX")
trap 'rm -f "$temporary"' EXIT HUP INT TERM

(
  cd "$formal_dir"
  lake build DClutchSemantics.ProductBasisV3
  lake env lean --run EmitProductBasisV3CorpusRust.lean > "$temporary"
)

test "$(sed -n '1p' "$temporary")" = \
  '// @generated by formal/dclutch-semantics/EmitProductBasisV3CorpusRust.lean; do not edit.'
test "$(sed -n '2p' "$temporary")" = \
  'use super::{BasisAgreementCaseV3, BasisCategoricalCaseV3};'

# A corpus that silently shrank would still be byte-identical to whatever the
# emitter now produces, so the counts are pinned here as well as in the test
# that consumes them.
grep -q '^pub const BASIS_AGREEMENT_CASES_V3: \[BasisAgreementCaseV3; 22\] = \[$' "$temporary"
grep -q '^pub const BASIS_CATEGORICAL_CASES_V3: \[BasisCategoricalCaseV3; 3\] = \[$' "$temporary"

# rustfmt IS run, and the comment that used to stand here said the opposite for
# a reason that measurement did not support: "the file is reached through
# include! rather than as a module, so nothing formats it in place either".
# `include!` stops `cargo fmt`'s module walk and stops nothing else --
# `tools/lane.sh fmt <path>`, this tree's own recommended formatting command,
# reformats it, and this corpus moves a long way under rustfmt (200 emitted
# lines become 860). So the raw compare was green only until somebody ran that
# command, exactly as `ea4c46e02` was. The pins above still read the emitter's
# RAW output, where each record is one unwrapped line; the compare reads it
# formatted, which is what the committed file now is.
rustfmt --edition 2024 "$temporary"
cmp "$temporary" "$accepted"
