#!/usr/bin/env node
// tools/genref/generate.mjs -- emits docs/reference/ from the protocol's own
// authorities. The OUTPUTS are generated; this file is the hand-written
// renderer and carries the reference's connective prose as templates.
//
// Sources (all in-tree except the inventory, which is produced fresh from the
// tree by the census tool each run):
//   - the route/refusal inventory emitted by `dclutch-route-census inventory`
//     (tools/gauntlet/census), passed in with --inventory
//   - tools/gauntlet/blocked.json
//   - tools/gauntlet/*/bindings.json and */*-bindings.json
//   - tools/gauntlet/CU_BUDGETS.json
//   - crates/dclutch-refusal-registry/src/lib.rs (band allocation)
//   - docs/decisions/*.md (ADR index)
//   - apps/dclutch-web/lib/generated/*.ts (the Lean/Rust-emitted ABI modules,
//     each byte-gated by its own `abi:*:verify`)
//
// Modes:
//   node generate.mjs --inventory FILE            regenerate docs/reference/
//   node generate.mjs --inventory FILE --check    byte-compare, write nothing
//
// docs/reference/ is wholly owned by this generator: on regenerate, stray
// files there are removed; on --check, they fail the gate. Every write goes
// through a same-directory temporary file and an atomic rename, so a failed
// run leaves the last accepted output byte-for-byte intact (AGENTS.md,
// "never redirect a generator directly into a canonical tracked output").
//
// Determinism: no timestamps, no absolute paths, every collection sorted.
// The check gate is the proof.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, "..", "..");

// ---------------------------------------------------------------- arguments

const argv = process.argv.slice(2);
let inventoryPath = null;
let check = false;
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === "--inventory") inventoryPath = argv[++i];
  else if (argv[i] === "--check") check = true;
  else {
    console.error(`genref: unknown argument ${argv[i]}`);
    process.exit(2);
  }
}
if (!inventoryPath) {
  console.error(
    "genref: --inventory FILE is required (tools/genref/generate.sh produces it)",
  );
  process.exit(2);
}

const OUT_DIR = path.join(REPO, "docs", "reference");

// ------------------------------------------------------------------ helpers

const readJSON = (p) => JSON.parse(fs.readFileSync(p, "utf8"));
const read = (p) => fs.readFileSync(p, "utf8");

function mdCell(s) {
  return String(s).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function table(headers, rows, align = null) {
  const sep = headers.map((_, i) =>
    align && align[i] === "r" ? "---:" : "---",
  );
  const line = (cells) => `| ${cells.map(mdCell).join(" | ")} |`;
  return [line(headers), `| ${sep.join(" | ")} |`, ...rows.map(line)].join(
    "\n",
  );
}

function hexBytes(bytes) {
  return bytes.map((b) => b.toString(16).padStart(2, "0")).join(" ");
}

function asciiBytes(bytes) {
  if (bytes.every((b) => b >= 0x20 && b <= 0x7e)) {
    return bytes.map((b) => String.fromCharCode(b)).join("");
  }
  return "";
}

function codeHex(code) {
  return "0x" + code.toString(16).toUpperCase().padStart(4, "0");
}

function num(n) {
  return n.toLocaleString("en-US");
}

function generatedHeader(sources) {
  return [
    "<!--",
    "  @generated by tools/genref/generate.mjs -- DO NOT EDIT.",
    "  Regenerate: tools/genref/generate.sh",
    "  Verify:     tools/genref/generate.sh --check",
    `  Sources: ${sources.join("; ")}`,
    "-->",
    "",
  ].join("\n");
}

// ------------------------------------------------------------ load sources

const inventory = readJSON(inventoryPath);
const programs = [...inventory.programs].sort((a, b) =>
  a.label < b.label ? -1 : 1,
);

const blocked = readJSON(path.join(REPO, "tools", "gauntlet", "blocked.json"));
const budgetsFile = readJSON(
  path.join(REPO, "tools", "gauntlet", "CU_BUDGETS.json"),
);

const gauntletDir = path.join(REPO, "tools", "gauntlet");
const bindingsFiles = [];
for (const entry of fs.readdirSync(gauntletDir).sort()) {
  const sub = path.join(gauntletDir, entry);
  if (!fs.statSync(sub).isDirectory()) continue;
  for (const f of fs.readdirSync(sub).sort()) {
    if (f === "bindings.json" || f.endsWith("-bindings.json")) {
      bindingsFiles.push(path.join(sub, f));
    }
  }
}

const decisionsDir = path.join(REPO, "docs", "decisions");
const decisionFiles = fs
  .readdirSync(decisionsDir)
  .filter((f) => f.endsWith(".md"))
  .sort();

const generatedTsDir = path.join(REPO, "apps", "dclutch-web", "lib", "generated");
const tsModules = fs
  .readdirSync(generatedTsDir)
  .filter((f) => f.endsWith(".ts"))
  .sort();

const registrySource = read(
  path.join(REPO, "crates", "dclutch-refusal-registry", "src", "lib.rs"),
);

// -------------------------------------------------- route execution status

// route id -> [{campaign, outcome, refusal?, file}]
const routeEvidence = new Map();
// binding route refs that match no inventory route id
const unknownRefs = [];

const inventoryRouteIds = new Set();
for (const p of programs) for (const r of p.routes) inventoryRouteIds.add(r.id);

for (const file of bindingsFiles) {
  const rel = path.relative(REPO, file);
  const data = readJSON(file);
  for (const b of data.bindings ?? []) {
    for (const ref of b.routes ?? []) {
      if (!inventoryRouteIds.has(ref)) {
        unknownRefs.push({ ref, file: rel, label: b.label });
        continue;
      }
      if (!routeEvidence.has(ref)) routeEvidence.set(ref, []);
      routeEvidence.get(ref).push({
        campaign: data.campaign ?? rel,
        outcome: b.outcome ?? "?",
        file: rel,
      });
    }
  }
}

// blocked.json: most specific matching rule wins; trailing '*' is a prefix
// glob (the file's own stated rules).
const blockedRules = blocked.blocked.map((b) => ({
  route: b.route,
  reason: b.reason,
}));
function blockedRuleFor(routeId) {
  let best = null;
  for (const rule of blockedRules) {
    if (rule.route.endsWith("*")) {
      const prefix = rule.route.slice(0, -1);
      if (routeId.startsWith(prefix)) {
        if (!best || rule.route.length > best.route.length) best = rule;
      }
    } else if (rule.route === routeId) {
      return rule; // exact always wins
    }
  }
  return best;
}

function firstSentence(s) {
  const m = s.match(/^(.*?\.)(\s|$)/s);
  return (m ? m[1] : s).replaceAll("\n", " ");
}

function routeStatus(routeId) {
  const ev = routeEvidence.get(routeId);
  if (ev) {
    const parts = [...new Set(ev.map((e) => `${e.outcome} (${e.campaign})`))]
      .sort();
    return { kind: "witnessed", text: parts.join("; ") };
  }
  const rule = blockedRuleFor(routeId);
  if (rule) {
    return {
      kind: "blocked",
      text: `blocked by rule \`${rule.route}\`: ${firstSentence(rule.reason)}`,
    };
  }
  return { kind: "none", text: "NEVER-EXECUTED, no stated reason" };
}

// ------------------------------------------------------ refusal band table

// Parse `/// Band ... .` doc lines paired with `pub const *_BASE: u32 = ...;`
const bandRows = [];
{
  const lines = registrySource.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(
      /^pub const ([A-Z0-9_]+(?:_BASE|_REFUSAL_BASE)): u32 = (0x[0-9A-Fa-f_]+);/,
    );
    if (!m) continue;
    // walk back over the doc comment block
    let doc = [];
    for (let j = i - 1; j >= 0; j--) {
      const dm = lines[j].match(/^\/\/\/ ?(.*)$/);
      if (!dm) break;
      doc.unshift(dm[1]);
    }
    const docText = doc.join(" ").trim();
    if (!/^Band /.test(docText)) continue;
    const base = parseInt(m[2].replaceAll("_", ""), 16);
    bandRows.push({
      constant: m[1],
      base,
      band: base >> 12,
      doc: docText.replace(/\.$/, ""),
    });
  }
  bandRows.sort((a, b) => a.base - b.base);
}

// ------------------------------------------------------------ ABI modules

// Parse one machine-emitted TS module into typed constants. Anything the
// parser does not recognize is carried verbatim into an "unrendered" bucket
// rather than dropped: the reference must not silently narrow its source.
function parseTsModule(name) {
  const text = read(path.join(generatedTsDir, name));
  const headerLines = [];
  for (const line of text.split("\n")) {
    if (line.startsWith("//")) headerLines.push(line.replace(/^\/\/ ?/, ""));
    else if (line.trim() === "") continue;
    else break;
  }
  // Split into export statements (statements may span lines).
  const statements = [];
  const re = /^export /gm;
  const starts = [];
  let m;
  while ((m = re.exec(text)) !== null) starts.push(m.index);
  for (let i = 0; i < starts.length; i++) {
    const end = i + 1 < starts.length ? starts[i + 1] : text.length;
    statements.push(text.slice(starts[i], end).trim());
  }

  const numbers = [];
  const byteArrays = [];
  const strings = [];
  const frozen = [];
  const functions = [];
  const unrendered = [];

  for (const stmt of statements) {
    let mm;
    if (
      (mm = stmt.match(/^export const ([A-Za-z0-9_]+) = (-?\d+) as const;$/))
    ) {
      numbers.push({ name: mm[1], value: Number(mm[2]) });
    } else if (
      (mm = stmt.match(
        /^export const ([A-Za-z0-9_]+) = Uint8Array\.from\(\[([\s\S]*?)\]\);$/,
      ))
    ) {
      const bytes = mm[2]
        .split(",")
        .map((s) => s.trim())
        .filter((s) => s.length > 0)
        .map((s) => Number(s));
      byteArrays.push({ name: mm[1], bytes });
    } else if (
      (mm = stmt.match(
        /^export const ([A-Za-z0-9_]+) = new TextEncoder\(\)\.encode\('([^']*)'\);$/,
      ))
    ) {
      strings.push({ name: mm[1], value: mm[2] });
    } else if (
      (mm = stmt.match(
        /^export const ([A-Za-z0-9_]+) = '([^']*)' as const;$/,
      ))
    ) {
      strings.push({ name: mm[1], value: mm[2] });
    } else if (
      (mm = stmt.match(
        /^export const ([A-Za-z0-9_]+) = Object\.freeze\(([\s\S]*?)\) as [\s\S]*?;$/,
      ))
    ) {
      let value = null;
      try {
        value = JSON.parse(mm[2]);
      } catch {
        unrendered.push(stmt);
        continue;
      }
      frozen.push({ name: mm[1], value });
    } else if ((mm = stmt.match(/^export function ([A-Za-z0-9_]+)/))) {
      functions.push({ name: mm[1] });
    } else {
      unrendered.push(stmt);
    }
  }

  return {
    file: name,
    header: headerLines,
    numbers,
    byteArrays,
    strings,
    frozen,
    functions,
    unrendered,
  };
}

const abiModules = tsModules.map(parseTsModule);

// ------------------------------------------------------------------ pages

const pages = new Map(); // relpath -> content

// ---- README.md (index + connective narrative)

{
  const rows = programs.map((p) => [
    `\`${p.label}\``,
    `\`${p.package}\``,
    p.routes.filter((r) => r.kind === "entry").length,
    p.routes.filter((r) => r.kind !== "entry").length,
    p.refusals.length,
  ]);
  const totalRoutes = programs.reduce((n, p) => n + p.routes.length, 0);
  const totalRefusals = programs.reduce((n, p) => n + p.refusals.length, 0);
  const witnessed = [...inventoryRouteIds].filter(
    (id) => routeEvidence.has(id),
  ).length;

  pages.set(
    "README.md",
    generatedHeader([
      "census inventory",
      "tools/gauntlet/blocked.json",
      "tools/gauntlet/*/bindings",
      "tools/gauntlet/CU_BUDGETS.json",
      "crates/dclutch-refusal-registry",
      "docs/decisions",
      "apps/dclutch-web/lib/generated",
    ]) +
      `# dClutch protocol reference

This reference is generated from the same authorities that run the protocol:
the route census enumerates programs, routes, and refusal enums from source;
the gauntlet's bindings and blocked ledger state which routes have executed
under which campaign and why the rest have not; the compute budgets are the
checked-in ceilings the campaigns are asserted against; the refusal-band
registry allocates the error-code space; the ADRs record the decisions; and
the ABI tables are read from the emitted modules that the browser itself
decodes with, each byte-gated against its emitting authority. Nothing in this
directory is hand-maintained, so nothing in it can drift silently: regenerate
with \`tools/genref/generate.sh\`, verify with
\`tools/genref/generate.sh --check\`.

Current totals: **${programs.length} programs**, **${totalRoutes} routes**
(${witnessed} with an in-tree execution binding), **${totalRefusals} protocol
refusal codes**.

- [programs.md](programs.md) -- the on-chain programs, their entrypoints, and
  their counts.
- [routes.md](routes.md) -- every instruction route, its selector magic, and
  its execution status. The standing doctrine: a route ships with the campaign
  row that executes it, or ships marked never-executed.
- [refusals.md](refusals.md) -- the band allocation and every refusal code
  with its meaning. A refusal is the protocol working: dClutch fails closed,
  and the code names exactly which program refused and why.
- [budgets.md](budgets.md) -- the golden transactions' compute budgets and
  the tolerance rule that keeps them honest.
- [decisions.md](decisions.md) -- the architecture decision records.
- [abi/](abi/README.md) -- record layouts, magics, PDA seed domains, schema
  identities, and account tables, per surface.

Evidence level, stated once for the whole reference: everything here
describes a locally executed protocol -- ProgramTest banks and local Agave
validators. Nothing is deployed to any cluster and nothing is released.
`,
  );
}

// ---- programs.md

{
  const rows = programs.map((p) => {
    const entry = p.entrypoints
      .map((e) => `\`${e.function}\` (${e.provenance})`)
      .join("; ");
    const bands = [
      ...new Set(p.refusals.map((r) => r.code >> 12)),
    ].sort((a, b) => a - b);
    return [
      `\`${p.label}\``,
      `\`${p.package}\``,
      bands.map((b) => "0x" + b.toString(16).toUpperCase()).join(", "),
      p.routes.filter((r) => r.kind === "entry").length,
      p.routes.filter((r) => r.kind !== "entry").length,
      p.refusals.length,
      entry,
    ];
  });
  pages.set(
    "programs.md",
    generatedHeader(["census inventory"]) +
      `# Programs

The census enumerates every program crate under \`programs/\` that declares an
SBF entrypoint. "Entry routes" are dispatch arms selected by instruction bytes
(magics); "action routes" are the actions reachable inside an entry route's
request grammar.

` +
      table(
        [
          "program",
          "package",
          "refusal band",
          "entry routes",
          "action routes",
          "refusal codes",
          "entrypoint",
        ],
        rows,
      ) +
      "\n",
  );
}

// ---- routes.md

{
  const sections = [];
  const neverExecuted = [];
  for (const p of programs) {
    const routes = [...p.routes].sort((a, b) => (a.id < b.id ? -1 : 1));
    const rows = routes.map((r) => {
      const sel = r.selectors
        .map((s) => {
          if (s.kind === "magic") {
            const bytes = [];
            for (let i = 0; i < s.bytes.length; i += 2) {
              bytes.push(parseInt(s.bytes.slice(i, i + 2), 16));
            }
            const a = s.ascii ?? asciiBytes(bytes);
            return a ? `magic \`${a}\`` : `magic \`${s.bytes}\``;
          }
          if (s.kind === "variant") return `variant \`${s.path}\``;
          return `${s.kind} \`${s.constant ?? s.path ?? ""}\``;
        })
        .join("; ");
      const st = routeStatus(r.id);
      if (st.kind === "none") neverExecuted.push(r.id);
      return [
        `\`${r.id}\``,
        r.kind,
        sel || "--",
        st.text,
        `\`${r.provenance}\``,
      ];
    });
    sections.push(
      `## ${p.label}\n\n` +
        table(["route", "kind", "selector", "status", "provenance"], rows),
    );
  }

  let unknown = "";
  if (unknownRefs.length > 0) {
    const rows = unknownRefs
      .sort((a, b) => (a.ref < b.ref ? -1 : 1))
      .map((u) => [`\`${u.ref}\``, `\`${u.file}\``, u.label]);
    unknown =
      `\n\n## Bindings naming routes the census does not\n\n` +
      `These route references appear in a bindings file but match no route id
in the current inventory. Each is either a stale binding or a census gap;
neither is silently droppable.\n\n` +
      table(["reference", "bindings file", "binding label"], rows);
  }

  pages.set(
    "routes.md",
    generatedHeader([
      "census inventory",
      "tools/gauntlet/blocked.json",
      "tools/gauntlet/*/bindings",
    ]) +
      `# Routes

Every instruction route the census enumerates, with its selector and its
execution status. Status comes from two in-tree ledgers: the gauntlet
campaigns' bindings (authored by the gauntlet, never by a campaign) name the
routes each witnessed transaction executes or refuses, and
\`tools/gauntlet/blocked.json\` names every route deliberately not driven yet,
with the reason. A route with neither is listed as **NEVER-EXECUTED, no
stated reason** -- the row that should make someone uncomfortable.

A "witnessed" status here means an in-tree campaign binds the route; it is
campaign coverage, not a proof about all inputs. Blocked reasons are
truncated to their first sentence -- the full entries live in
\`blocked.json\`.

Currently **${neverExecuted.length}** of **${inventoryRouteIds.size}** routes
have neither an execution binding nor a blocked entry.

` +
      sections.join("\n\n") +
      unknown +
      "\n",
  );
}

// ---- refusals.md

{
  const bandTable = table(
    ["base", "band", "allocation"],
    bandRows.map((b) => [
      `\`${codeHex(b.base)}\``,
      "0x" + b.band.toString(16).toUpperCase(),
      b.doc,
    ]),
  );

  const sections = programs.map((p) => {
    const refusals = [...p.refusals].sort((a, b) => a.code - b.code);
    const rows = refusals.map((r) => [
      `\`${codeHex(r.code)}\``,
      `\`${r.enum_name}::${r.variant}\``,
      r.doc || "(no doc comment)",
      `\`${r.provenance}\``,
    ]);
    return (
      `## ${p.label}\n\n` + table(["code", "refusal", "meaning", "provenance"], rows)
    );
  });

  const totalRefusals = programs.reduce((n, p) => n + p.refusals.length, 0);

  pages.set(
    "refusals.md",
    generatedHeader([
      "census inventory",
      "crates/dclutch-refusal-registry/src/lib.rs",
    ]) +
      `# Refusal codes

Every custom program error code is namespaced by program (decision 0007;
\`crates/dclutch-refusal-registry\` is the authority). \`band = code >> 12\`,
each band is 0x1000 codes wide, and band 0 is never allocated -- so a custom
code below \`0x1000\` is, by construction, not a dClutch refusal. Read a band
off a log line by dropping the last three hex digits: \`custom program error:
0x5180\` is band 5 (Claims). Bands at \`0x100000\` and above belong to
test-only caller programs that exist to drive hostile CPI cases and are never
deployed.

A refusal is the protocol working. dClutch fails closed: an input, account
shape, authority, or state that does not authenticate exactly is refused with
a code that names the program and the reason, and no partial effect survives
the transaction. The tables below carry all **${totalRefusals}** protocol
codes with their meanings, straight from the refusal enums' own doc comments.

## Band allocation

${bandTable}

` +
      sections.join("\n\n") +
      "\n",
  );
}

// ---- budgets.md

{
  const budgets = budgetsFile.budgets;
  const label = (e) =>
    e.scope === "stage"
      ? `stage ${e.stage.index}: ${e.stage.name} (${e.stage.program_role})`
      : e.transaction;
  const enforced = budgets.filter((e) => e.enforced);
  const recorded = budgets.filter((e) => !e.enforced);

  const mainRows = enforced.map((e) => [
    `\`${e.id}\``,
    e.campaign,
    e.scope,
    label(e),
    num(e.measured),
    num(e.tolerance),
    num(e.budget),
  ]);
  const recRows = recorded.map((e) => [
    `\`${e.id}\``,
    e.campaign,
    e.scope,
    label(e),
    e.measured ? num(e.measured) : "--",
    firstSentence(e.unenforced_reason ?? ""),
  ]);

  const provenance = budgets
    .map((e) => `- \`${e.id}\` -- ${e.provenance.replaceAll("\n", " ")}`)
    .join("\n");

  pages.set(
    "budgets.md",
    generatedHeader(["tools/gauntlet/CU_BUDGETS.json"]) +
      `# Compute budgets for the golden transactions

\`tools/gauntlet/CU_BUDGETS.json\` is the one owner of these numbers; the
gauntlet's witness evaluator asserts them against each campaign's own
finalized evidence, and a red row names the transaction and the delta. The
chain's per-transaction ceiling is **${num(budgetsFile.ceiling.compute_units)}
CU**; a budget above it is refused by the evaluator, which is how the file
says out loud that a transaction has stopped fitting.

The tolerance rule, verbatim from the file:
\`${budgetsFile.tolerance_rule.formula}\`. The measured value of every entry
is the highest draw observed, never a single run. Read
\`tools/gauntlet/CU_BUDGETS.md\` before changing a number -- in particular
what it says about noise: PDA bump search costs 1,500 CU per iteration and
moves with the keys in play, which is why the campaigns run seeded and why
the tolerances are what they are.

## Enforced budgets

` +
      table(
        ["id", "campaign", "scope", "what", "measured", "tolerance", "budget"],
        mainRows,
        [null, null, null, null, "r", "r", "r"],
      ) +
      `

## Recorded, not enforced

` +
      table(
        ["id", "campaign", "scope", "what", "measured", "why unenforced"],
        recRows,
        [null, null, null, null, "r", null],
      ) +
      `

## Provenance

${provenance}
`,
  );
}

// ---- decisions.md

{
  const rows = [];
  for (const f of decisionFiles) {
    const text = read(path.join(decisionsDir, f));
    const lines = text.split("\n");
    const title = (lines[0] ?? "").replace(/^#\s*/, "");
    let status = "";
    for (let i = 1; i < lines.length; i++) {
      if (lines[i].startsWith("Status:")) {
        const para = [];
        for (let j = i; j < lines.length && lines[j].trim() !== ""; j++) {
          para.push(lines[j]);
        }
        status = firstSentence(
          para.join(" ").replace(/^Status:\s*/, ""),
        );
        break;
      }
    }
    rows.push([`[${title}](../decisions/${f})`, status]);
  }
  pages.set(
    "decisions.md",
    generatedHeader(["docs/decisions/*.md"]) +
      `# Architecture decision records

The decisions that bind the implementation. Each record carries its own
context, alternatives, and consequences; this index carries the first
sentence of each record's status line.

` +
      table(["decision", "status"], rows) +
      "\n",
  );
}

// ---- abi/ pages

{
  const indexRows = [];
  for (const mod of abiModules) {
    const base = mod.file.replace(/\.ts$/, "");
    const out = `abi/${base}.md`;
    indexRows.push([
      `[${base}](${base}.md)`,
      mod.header.find((l) => l.includes("@generated"))?.replace(
        /^@generated /,
        "",
      ) ?? "",
      mod.header
        .find((l) => l.startsWith("Regenerate with:"))
        ?.replace(/^Regenerate with:\s*/, "") ?? "",
    ]);

    const parts = [];
    parts.push(
      generatedHeader([
        `apps/dclutch-web/lib/generated/${mod.file} (which is itself generated -- see its header below)`,
      ]),
    );
    parts.push(`# ABI: ${base}\n`);
    parts.push(
      `Source module: \`apps/dclutch-web/lib/generated/${mod.file}\`, whose own header reads:\n`,
    );
    parts.push("```");
    parts.push(...mod.header);
    parts.push("```\n");

    if (mod.byteArrays.length > 0) {
      const rows = mod.byteArrays.map((b) => {
        const a = asciiBytes(b.bytes);
        return [
          `\`${b.name}\``,
          b.bytes.length,
          a ? `\`${a}\`` : "--",
          `\`${hexBytes(b.bytes)}\``,
        ];
      });
      parts.push(`## Byte constants (magics, seed domains, schema identities)\n`);
      parts.push(table(["name", "len", "ascii", "bytes"], rows));
      parts.push("");
    }

    if (mod.strings.length > 0) {
      const rows = mod.strings.map((s) => [`\`${s.name}\``, `\`${s.value}\``]);
      parts.push(`## String constants\n`);
      parts.push(table(["name", "value"], rows));
      parts.push("");
    }

    if (mod.numbers.length > 0) {
      const rows = mod.numbers.map((n) => [`\`${n.name}\``, num(n.value)]);
      parts.push(`## Numeric constants (widths, offsets, counts, tags)\n`);
      parts.push(table(["name", "value"], rows, [null, "r"]));
      parts.push("");
    }

    // Pair *LABELS* arrays with their *ROLES* siblings into account tables.
    const consumed = new Set();
    for (const fz of mod.frozen) {
      if (!fz.name.includes("LABELS")) continue;
      const rolesName = fz.name.replace("LABELS", "ROLES");
      const roles = mod.frozen.find((g) => g.name === rolesName);
      if (
        roles &&
        Array.isArray(roles.value) &&
        roles.value.length === fz.value.length &&
        roles.value.every((v) => typeof v === "object" && v !== null)
      ) {
        consumed.add(fz.name);
        consumed.add(rolesName);
        const rows = fz.value.map((labelText, i) => [
          i,
          labelText,
          roles.value[i].signer ? "signer" : "",
          roles.value[i].writable ? "writable" : "",
        ]);
        parts.push(`## Account table: \`${fz.name}\` / \`${rolesName}\`\n`);
        parts.push(table(["#", "account", "signer", "writable"], rows));
        parts.push("");
      }
    }
    for (const fz of mod.frozen) {
      if (consumed.has(fz.name)) continue;
      parts.push(`## \`${fz.name}\`\n`);
      if (Array.isArray(fz.value) && fz.value.every((v) => typeof v !== "object")) {
        parts.push(
          table(
            ["#", "value"],
            fz.value.map((v, i) => [i, `\`${String(v)}\``]),
          ),
        );
      } else {
        parts.push("```json");
        parts.push(JSON.stringify(fz.value, null, 1));
        parts.push("```");
      }
      parts.push("");
    }

    if (mod.functions.length > 0) {
      parts.push(`## Functions (see the source module)\n`);
      parts.push(mod.functions.map((f) => `- \`${f.name}\``).join("\n"));
      parts.push("");
    }

    if (mod.unrendered.length > 0) {
      parts.push(`## Unrendered exports (verbatim)\n`);
      parts.push(
        "The renderer did not recognize these statement shapes; they are\ncarried verbatim so the reference never silently narrows its source.\n",
      );
      for (const stmt of mod.unrendered) {
        parts.push("```ts");
        parts.push(stmt);
        parts.push("```");
      }
      parts.push("");
    }

    pages.set(out, parts.join("\n"));
  }

  pages.set(
    "abi/README.md",
    generatedHeader(["apps/dclutch-web/lib/generated/*.ts"]) +
      `# ABI surfaces

One page per emitted ABI module. These are the byte layouts the protocol
actually enforces: magics, PDA seed domains, schema release identities,
record widths and field offsets, and account tables. The source modules live
in \`apps/dclutch-web/lib/generated/\` -- they are what the browser decodes
with, each carries an \`abi:*:verify\` byte-compare gate against its emitting
authority (the Lean emitters in \`formal/dclutch-semantics\` or the canonical
Rust contracts), and \`npm test\` runs every gate. This directory renders
them; it never restates them by hand.

` +
      table(["surface", "module authority", "regenerate"], indexRows) +
      "\n",
  );
}

// ----------------------------------------------------------- write / check

function walk(dir, base = dir, acc = []) {
  if (!fs.existsSync(dir)) return acc;
  for (const e of fs.readdirSync(dir).sort()) {
    const p = path.join(dir, e);
    if (fs.statSync(p).isDirectory()) walk(p, base, acc);
    else acc.push(path.relative(base, p));
  }
  return acc;
}

const expected = new Map(
  [...pages.entries()].sort(([a], [b]) => (a < b ? -1 : 1)),
);

if (check) {
  const existing = walk(OUT_DIR);
  let failed = false;
  for (const [rel, content] of expected) {
    const p = path.join(OUT_DIR, rel);
    if (!fs.existsSync(p)) {
      console.error(`genref check: MISSING ${path.relative(REPO, p)}`);
      failed = true;
    } else if (read(p) !== content) {
      console.error(`genref check: STALE ${path.relative(REPO, p)}`);
      failed = true;
    }
  }
  for (const rel of existing) {
    if (!expected.has(rel)) {
      console.error(
        `genref check: STRAY ${path.join("docs/reference", rel)} (not produced by the generator)`,
      );
      failed = true;
    }
  }
  if (failed) {
    console.error(
      "genref check: docs/reference is not the generator's output. Regenerate with tools/genref/generate.sh and commit the result.",
    );
    process.exit(1);
  }
  console.log(
    `genref check: docs/reference matches (${expected.size} files, byte-identical).`,
  );
} else {
  fs.mkdirSync(path.join(OUT_DIR, "abi"), { recursive: true });
  for (const [rel, content] of expected) {
    const p = path.join(OUT_DIR, rel);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    const tmp = p + ".genref-tmp";
    fs.writeFileSync(tmp, content);
    fs.renameSync(tmp, p);
  }
  for (const rel of walk(OUT_DIR)) {
    if (!expected.has(rel)) {
      fs.unlinkSync(path.join(OUT_DIR, rel));
      console.log(`genref: removed stray ${path.join("docs/reference", rel)}`);
    }
  }
  console.log(`genref: wrote ${expected.size} files under docs/reference/.`);
}
