//! The Hoard/Position seam plane: `Intent::Split`, and the shared account list,
//! validation order, kernel step, and write-back that
//! [`super::merge_materialize`] reuses for `Merge`, `Materialize`, and
//! `Dematerialize`.
//!
//! This module contains no economic logic.  Every transition is
//! [`clutch_kernel::MarketState`]; byte ownership is [`clutch_solana_layout`]
//! and the reference-only codecs of [`clutch_solana_reference`]; metadata
//! authentication and the CLO-DELTA-V1 primitives are [`crate::accounts`].
//! What lives here is the account list, the order of the checks, the program
//! addresses each account must be, and the write-back.
//!
//! ## The seam plane is one plane
//!
//! `Split`, `Merge`, `Materialize`, and `Dematerialize` are the four requests
//! the offline reference adapter routes through one `TransitionMetadata` /
//! `StateBytes` / `ExpectedBindings` triple, so they take one account list
//! here too.  Two modules own them (the ownership table in
//! `docs/implementation/SBF_BRINGUP.md` splits by family), but a second copy of
//! the account list would be a second place for the seam's writable set to
//! drift, so the list, the checks, and the write-back live here and
//! `merge_materialize` calls [`seam`].
//!
//! ## CLO-DELTA-V1 is now carried, not deferred
//!
//! The single-instruction bring-up program carried the retired closed
//! single-position equality `internal + external == total_supply` and took nine
//! accounts.  It now takes **ten**: the market-wide supply ledger, appended
//! after the replay account exactly as `ExpectedBindings::supply` is the last
//! state binding of the reference adapter.  The equality is replaced by the
//! three checked obligations of `docs/implementation/MULTI_POSITION_CLOSURE.md`
//! through [`crate::accounts`]:
//!
//! | obligation | where |
//! | --- | --- |
//! | C1 two-term closure against the kernel aggregate | [`accounts::require_two_term_closure`], pre-state and post-state |
//! | C2 representation bound on the presented triple | [`accounts::require_representation_bound`], pre-state and post-state |
//! | C3 ledger moved by exactly the position delta | [`accounts::apply_ledger_delta`], once per ledger term |
//!
//! A market holding a second position is therefore representable here, which is
//! the whole point of the change: the retired equality refused every such
//! market.
//!
//! ## Consequence for the emitted SVM fixtures
//!
//! `harness/` is frozen this wave and still emits a nine-account `Split`
//! transaction, so the transactions under `tx/` no longer match this
//! instruction's account count and the SVM leg of the differential must be
//! regenerated by the harness lane before it means anything again.  Its *host*
//! leg — the fixture build and the offline reference adapter run inside
//! `build_fixture` — is untouched and still passes.  The host differential in
//! this module is what covers the transitions in the meantime; the SVM-side
//! differential for the seam plane is a named follow-up wave.
//!
//! ## What the host differential does and does not cover
//!
//! [`seam`] takes its program addresses as an already-derived [`Bindings`]
//! value rather than deriving them inline, because program-address derivation
//! is a runtime syscall and [`crate::seeds::find`] is deliberately not compiled
//! for the host.  On-chain, [`process`] supplies [`derive_bindings`]; in the
//! host differential the test supplies the same trusted bindings the offline
//! reference adapter itself takes as `ExpectedBindings`.  So the differential
//! covers request decoding, metadata authentication, every linkage and closure
//! check, the kernel step, and the write-back — everything the reference
//! adapter models — and covers exactly one thing less than the SVM leg: that
//! the derived address is the canonical one.  That gap is the derivation, and
//! it is the reference adapter's own gap too.

use crate::accounts::{
    self, apply_ledger_delta, expect_pda, require, require_count, require_distinct,
    require_representation_bound, require_signer, require_two_term_closure, KernelFacts, Outcome,
    StateRole, SupplyFacts,
};
use crate::error::{ClutchError, Refusal};
use crate::seeds;
use clutch_kernel::{MarketState, Phase, Position, MAX_OUTCOMES as KERNEL_MAX_OUTCOMES};
use clutch_solana_layout::{
    account_len, Hash32, HoardAccount, Intent, PositionAccount, SupplyLedgerAccount, MAX_OUTCOMES,
};
use clutch_solana_reference::{
    Action, ExternalAccount, KernelAccount, ReplayAccount, Request, EXTERNAL_ACCOUNT_LEN,
    KERNEL_ACCOUNT_LEN, REPLAY_ACCOUNT_LEN,
};
use solana_account_info::AccountInfo;
use solana_pubkey::Pubkey;

/// Exact number of accounts every seam instruction accepts.
///
/// A fixed count is itself a check: a remaining-account shuffle cannot append
/// an extra writable account for a later instruction to reuse.
pub const ACCOUNT_COUNT: usize = 10;

/// Authenticated actor; must be the position owner.
pub const IX_ACTOR: usize = 0;
/// Realm configuration account (read-only).
pub const IX_REALM: usize = 1;
/// Profile identity account (read-only).
pub const IX_PROFILE: usize = 2;
/// Market account.
pub const IX_MARKET: usize = 3;
/// Hoard collateral account.
pub const IX_HOARD: usize = 4;
/// Owner position account.
pub const IX_POSITION: usize = 5;
/// Reference-only kernel-aggregate account.
pub const IX_KERNEL: usize = 6;
/// Reference-only external-shadow account.
pub const IX_EXTERNAL: usize = 7;
/// Reference-only replay-sequence account.
pub const IX_REPLAY: usize = 8;
/// Market-wide two-term supply ledger.
pub const IX_SUPPLY: usize = 9;

/// The program-owned state roles of the seam plane, in account-list order.
const STATE_ROLES: [StateRole; 9] = [
    StateRole::read_only(IX_REALM, account_len::REALM),
    StateRole::read_only(IX_PROFILE, account_len::PROFILE),
    StateRole::writable(IX_MARKET, account_len::MARKET),
    StateRole::writable(IX_HOARD, account_len::HOARD),
    StateRole::writable(IX_POSITION, account_len::POSITION),
    StateRole::writable(IX_KERNEL, KERNEL_ACCOUNT_LEN),
    StateRole::writable(IX_EXTERNAL, EXTERNAL_ACCOUNT_LEN),
    StateRole::writable(IX_REPLAY, REPLAY_ACCOUNT_LEN),
    StateRole::writable(IX_SUPPLY, account_len::SUPPLY_LEDGER),
];

/// One already-routed `Split` request.
///
/// [`crate::dispatch`] destructures the envelope so that this module never has
/// to re-match an action it already knows, and so there is no unreachable
/// fallback arm pretending another intent could arrive here.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SplitRequest {
    /// Exact replay sequence the request claims.
    pub sequence: u64,
    /// Market identity the intent binds.
    pub market: Hash32,
    /// Owner identity the intent binds.
    pub owner: Hash32,
    /// Complete sets to create.
    pub quantity: u64,
}

/// One already-routed seam transition.
///
/// The four variants are exactly the four layout intents the offline reference
/// adapter routes through one account plane, and all four are implemented.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SeamOp {
    /// Add a complete internal set.
    Split {
        /// Market identity the intent binds.
        market: Hash32,
        /// Owner identity the intent binds.
        owner: Hash32,
        /// Complete sets to create.
        quantity: u64,
    },
    /// Remove a complete internal set.
    Merge {
        /// Market identity the intent binds.
        market: Hash32,
        /// Owner identity the intent binds.
        owner: Hash32,
        /// Complete sets to destroy.
        quantity: u64,
    },
    /// Move one outcome from the internal ledger to the external shadow.
    Materialize {
        /// Market identity the intent binds.
        market: Hash32,
        /// Owner identity the intent binds.
        owner: Hash32,
        /// Caller-named destination, which must be the external-shadow account.
        destination: Hash32,
        /// Outcome index.
        outcome: u8,
        /// Claim atoms to move.
        quantity: u64,
    },
    /// Move one outcome from the external shadow back to the internal ledger.
    Dematerialize {
        /// Market identity the intent binds.
        market: Hash32,
        /// Owner identity the intent binds.
        owner: Hash32,
        /// Caller-named source, which must be the external-shadow account.
        source: Hash32,
        /// Outcome index.
        outcome: u8,
        /// Claim atoms to move.
        quantity: u64,
    },
}

impl SeamOp {
    /// Market identity this intent binds.
    const fn market(&self) -> Hash32 {
        match self {
            Self::Split { market, .. }
            | Self::Merge { market, .. }
            | Self::Materialize { market, .. }
            | Self::Dematerialize { market, .. } => *market,
        }
    }

    /// Owner identity this intent binds.
    const fn owner(&self) -> Hash32 {
        match self {
            Self::Split { owner, .. }
            | Self::Merge { owner, .. }
            | Self::Materialize { owner, .. }
            | Self::Dematerialize { owner, .. } => *owner,
        }
    }
}

/// Convert one decoded request into the seam transition it names.
///
/// Anything that is not a seam intent refuses
/// [`ClutchError::UnsupportedInstruction`] rather than being silently routed
/// into a plane that does not model it.  [`crate::dispatch`] already routes only
/// the four seam intents here, so that arm is defence in depth and not a
/// reachable path today.
pub fn seam_op(request: &Request) -> Outcome<SeamOp> {
    match request.action {
        Action::Layout(Intent::Split {
            market,
            owner,
            quantity,
        }) => Ok(SeamOp::Split {
            market,
            owner,
            quantity,
        }),
        Action::Layout(Intent::Merge {
            market,
            owner,
            quantity,
        }) => Ok(SeamOp::Merge {
            market,
            owner,
            quantity,
        }),
        Action::Layout(Intent::Materialize {
            market,
            owner,
            destination,
            outcome,
            quantity,
        }) => Ok(SeamOp::Materialize {
            market,
            owner,
            destination,
            outcome,
            quantity,
        }),
        Action::Layout(Intent::Dematerialize {
            market,
            owner,
            source,
            outcome,
            quantity,
        }) => Ok(SeamOp::Dematerialize {
            market,
            owner,
            source,
            outcome,
            quantity,
        }),
        _ => Err(ClutchError::UnsupportedInstruction.into()),
    }
}

/// The identities every seam program address is derived from.
///
/// Each one is read out of a decoded account, never out of the instruction
/// data: a caller-named identity would be exactly the trusted binding
/// obligation 1 of `docs/implementation/SOLANA_REFERENCE_ADAPTER.md` forbids.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Identities {
    /// Realm namespace, from the market account.
    pub realm: [u8; 32],
    /// Profile identity, from the market account.
    pub profile: [u8; 32],
    /// Market identity, from the market account.
    pub market: [u8; 32],
    /// Owner identity, from the position account.
    pub owner: [u8; 32],
    /// Position generation, from the position account.
    pub generation: u64,
}

/// Canonical program address and bump for every account in the seam plane.
///
/// The two `None`-bump roles of [`expect_pda`] — Profile and the reference-only
/// kernel aggregate — carry a bump here that is never compared, because their
/// frozen layouts have no bump field to compare it against.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Bindings {
    /// Canonical Realm address and bump.
    pub realm: (Pubkey, u8),
    /// Canonical Profile address; the bump is not stored and not compared.
    pub profile: (Pubkey, u8),
    /// Canonical Market address and bump.
    pub market: (Pubkey, u8),
    /// Canonical Hoard address and bump.
    pub hoard: (Pubkey, u8),
    /// Canonical Position address and bump.
    pub position: (Pubkey, u8),
    /// Canonical kernel-aggregate address; the bump is not stored.
    pub kernel: (Pubkey, u8),
    /// Canonical external-shadow address and bump.
    pub external: (Pubkey, u8),
    /// Canonical replay-sequence address and bump.
    pub replay: (Pubkey, u8),
    /// Canonical supply-ledger address and bump.
    pub supply: (Pubkey, u8),
}

/// Derive every seam program address from the frozen seed schema.
///
/// This is the only part of the plane that cannot run off-chain: derivation is
/// a runtime syscall and [`crate::seeds::find`] is not compiled for the host.
/// It is therefore a parameter of [`seam`] rather than an inline call, so the
/// host differential can supply the same already-derived bindings the offline
/// reference adapter takes as `ExpectedBindings` and compare everything else.
#[inline(never)]
pub fn derive_bindings(program_id: &Pubkey, ids: &Identities) -> Bindings {
    Bindings {
        realm: seeds::realm_pda(program_id, &ids.realm),
        profile: seeds::profile_pda(program_id, &ids.realm, &ids.profile),
        market: seeds::market_pda(program_id, &ids.realm, &ids.market),
        hoard: seeds::hoard_pda(program_id, &ids.market),
        position: seeds::position_pda(program_id, &ids.market, &ids.owner),
        kernel: seeds::kernel_pda(program_id, &ids.market),
        external: seeds::external_pda(program_id, &ids.market, &ids.owner, ids.generation),
        replay: seeds::replay_pda(program_id, &ids.market, &ids.owner, ids.generation),
        supply: seeds::supply_pda(program_id, &ids.market),
    }
}

/// The post-state the pure kernel produced for the market aggregate.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct KernelPost {
    collateral: u64,
    total_supply: [u64; MAX_OUTCOMES],
    phase: u8,
    resolved_payout: u8,
}

/// Run one seam transition on the pure kernel and re-encode the aggregate.
///
/// The whole `KernelAccount`/`MarketState` working set lives in this frame and
/// nowhere else: a `MarketState` carries the entire frozen payout set, which is
/// most of an SBF call frame on its own.  `position` is updated in place only
/// after every kernel check has passed, because every `MarketState` transition
/// completes all of its checks before its first write.
#[inline(never)]
fn kernel_step(
    kernel_data: &mut [u8],
    outcome_count: u8,
    collateral_before: u64,
    position: &mut Position,
    op: &SeamOp,
) -> Outcome<KernelPost> {
    let mut account = KernelAccount::decode(kernel_data)?;
    if usize::from(outcome_count) > KERNEL_MAX_OUTCOMES || account.payouts.outcomes != outcome_count
    {
        return Err(ClutchError::MismatchedState.into());
    }
    let phase = match account.phase {
        0 => Phase::Active,
        1 => Phase::Resolved,
        _ => return Err(ClutchError::NonCanonical.into()),
    };
    let mut market = MarketState {
        outcomes: outcome_count,
        phase,
        resolved_payout: account.resolved_payout,
        collateral: collateral_before,
        total_supply: account.total_supply,
        payouts: account.payouts,
    };
    market.check_invariants()?;
    match op {
        SeamOp::Split { quantity, .. } => market.split(position, *quantity)?,
        SeamOp::Merge { quantity, .. } => market.merge(position, *quantity)?,
        SeamOp::Materialize {
            outcome, quantity, ..
        } => market.materialize(position, *outcome, *quantity)?,
        SeamOp::Dematerialize {
            outcome, quantity, ..
        } => market.dematerialize(position, *outcome, *quantity)?,
    }
    account.phase = match market.phase {
        Phase::Active => 0,
        Phase::Resolved => 1,
    };
    account.resolved_payout = market.resolved_payout;
    account.total_supply = market.total_supply;
    account.encode(kernel_data)?;
    Ok(KernelPost {
        collateral: market.collateral,
        total_supply: market.total_supply,
        phase: account.phase,
        resolved_payout: account.resolved_payout,
    })
}

/// Move the two-term ledger by exactly the position delta and re-close it.
///
/// This is C3 followed by C1 and C2 over the post-state, in the offline
/// reference adapter's order.  Re-closing after the delta is what forces the
/// kernel's aggregate supply effect to equal its per-position effect: a
/// divergence refuses instead of corrupting the ledger.
#[inline(never)]
fn ledger_step(
    supply_data: &mut [u8],
    outcome_count: u8,
    pre_internal: &[u64; MAX_OUTCOMES],
    pre_external: &[u64; MAX_OUTCOMES],
    post: &Position,
    kernel: &KernelPost,
) -> Outcome<()> {
    let mut ledger = SupplyLedgerAccount::decode(supply_data)?;
    apply_ledger_delta(
        &mut ledger.internal_supply,
        outcome_count,
        pre_internal,
        &post.internal,
    )?;
    apply_ledger_delta(
        &mut ledger.external_supply,
        outcome_count,
        pre_external,
        &post.external,
    )?;
    let facts = SupplyFacts {
        market: ledger.market,
        realm: ledger.realm,
        generation: ledger.generation,
        outcome_count: ledger.outcome_count,
        internal_supply: ledger.internal_supply,
        external_supply: ledger.external_supply,
        stored_bump: ledger.stored_bump,
    };
    let aggregate = KernelFacts {
        market: ledger.market,
        phase: kernel.phase,
        payout_outcomes: outcome_count,
        total_supply: kernel.total_supply,
    };
    require_two_term_closure(&facts, &aggregate, outcome_count)?;
    require_representation_bound(&facts, &post.internal, &post.external, outcome_count)?;
    ledger.encode(supply_data)?;
    Ok(())
}

/// Validate hostile accounts and apply exactly one seam transition.
///
/// The check order is the bring-up program's, which is the offline reference
/// adapter's with two named differences, both of which only change *which of
/// two simultaneous faults* is reported and never whether a request is
/// accepted:
///
/// 1. the actor's signature is authenticated first here and inside the
///    per-intent arm there, because a runtime hands this program a signature
///    assertion before it hands it any account data; and
/// 2. `Split`'s collateral-cap and cash checks precede the kernel invariant
///    check here and follow it there.
///
/// `Merge`'s cash *credit* is not one of those differences: it lands after the
/// kernel step on both sides, because on both sides it is the consequence of a
/// burn rather than a precondition of a mint.
///
/// Every check that decides *acceptance* is in the reference's order, and the
/// host differential in this module's tests pins the correspondence one fault
/// at a time.
pub fn seam<D>(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    sequence: u64,
    op: &SeamOp,
    derive: D,
) -> Outcome<()>
where
    D: FnOnce(&Identities) -> Bindings,
{
    require_count(accounts, ACCOUNT_COUNT)?;

    let actor = &accounts[IX_ACTOR];
    require_signer(actor)?;

    /* Role uniqueness.  A writable alias would let one logical debit or credit
     * land twice, which is obligation 3 of the reference adapter doc. */
    require_distinct(accounts)?;

    /* Program ownership, executable bit, declared mutability by role, and exact
     * data length per role. */
    accounts::validate_state_roles(program_id, accounts, &STATE_ROLES)?;

    let realm = accounts::read_realm(&accounts[IX_REALM].data.borrow())?;
    let profile = accounts::read_profile(&accounts[IX_PROFILE].data.borrow())?;
    let market = accounts::read_market(&accounts[IX_MARKET].data.borrow())?;
    let mut hoard = HoardAccount::decode(&accounts[IX_HOARD].data.borrow())?;
    let mut position = PositionAccount::decode(&accounts[IX_POSITION].data.borrow())?;
    let kernel = accounts::read_kernel(&accounts[IX_KERNEL].data.borrow())?;
    let mut external = ExternalAccount::decode(&accounts[IX_EXTERNAL].data.borrow())?;
    let mut replay = ReplayAccount::decode(&accounts[IX_REPLAY].data.borrow())?;
    let supply = accounts::read_supply(&accounts[IX_SUPPLY].data.borrow())?;

    /* Derived addresses.  Caller-supplied expected keys are never accepted:
     * every address is recomputed from the frozen seed schema and compared,
     * and every stored bump is compared against the canonical bump. */
    let bindings = derive(&Identities {
        realm: market.realm.bytes(),
        profile: market.profile.bytes(),
        market: market.market.bytes(),
        owner: position.owner.bytes(),
        generation: position.generation,
    });
    expect_pda(
        accounts[IX_REALM].key,
        bindings.realm,
        Some(realm.stored_bump),
    )?;
    expect_pda(accounts[IX_PROFILE].key, bindings.profile, None)?;
    expect_pda(
        accounts[IX_MARKET].key,
        bindings.market,
        Some(market.stored_bump),
    )?;
    expect_pda(
        accounts[IX_HOARD].key,
        bindings.hoard,
        Some(hoard.stored_bump),
    )?;
    require(
        market.hoard_bump == bindings.hoard.1,
        ClutchError::WrongBump,
    )?;
    expect_pda(
        accounts[IX_POSITION].key,
        bindings.position,
        Some(position.stored_bump),
    )?;
    expect_pda(accounts[IX_KERNEL].key, bindings.kernel, None)?;
    expect_pda(
        accounts[IX_EXTERNAL].key,
        bindings.external,
        Some(external.stored_bump),
    )?;
    expect_pda(
        accounts[IX_REPLAY].key,
        bindings.replay,
        Some(replay.stored_bump),
    )?;
    expect_pda(
        accounts[IX_SUPPLY].key,
        bindings.supply,
        Some(supply.stored_bump),
    )?;

    /* Cross-account linkage, mirroring `validate_links` in the offline
     * reference adapter -- the supply-ledger edges included -- plus the
     * Realm/Profile edges the reference only checks at market initialization. */
    require(
        realm.realm == market.realm
            && realm.profile == market.profile
            && profile.profile == market.profile
            && profile.realm == market.realm
            && realm.profile_version == profile.version
            && usize::from(realm.max_outcomes) == MAX_OUTCOMES
            && market.outcome_count <= realm.max_outcomes,
        ClutchError::MismatchedState,
    )?;
    require(
        market.market == hoard.market
            && market.realm == hoard.realm
            && market.market == position.market
            && market.market == kernel.market
            && market.market == external.market
            && market.market == replay.market
            && market.market == supply.market
            && market.realm == supply.realm
            && market.outcome_count == supply.outcome_count
            && position.owner == external.owner
            && position.owner == replay.owner
            && position.generation == external.position_generation
            && position.generation == replay.position_generation
            && (market.lifecycle != 0 || kernel.phase == 0)
            && (market.lifecycle != 1 || kernel.phase == 1)
            && market.lifecycle <= 1
            && kernel.payout_outcomes == market.outcome_count
            && usize::from(market.outcome_count) <= KERNEL_MAX_OUTCOMES,
        ClutchError::MismatchedState,
    )?;

    /* Padding beyond the active outcome count must be canonically zero in every
     * balance vector.  The ledger's own padding is refused by its frozen codec,
     * which is why it is not re-checked here. */
    let count = usize::from(market.outcome_count);
    let mut padding = count;
    while padding < MAX_OUTCOMES {
        require(
            position.internal[padding] == 0
                && kernel.total_supply[padding] == 0
                && external.balances[padding] == 0,
            ClutchError::NonCanonical,
        )?;
        padding += 1;
    }

    /* CLO-DELTA-V1 C1 and C2 over the pre-state, before any write.  C2 is a
     * one-sided bound and not the retired equality: a ledger term above the
     * presented position is another position's claim, while a position above
     * the ledger term is a counterfeit and refuses. */
    require_two_term_closure(&supply, &kernel, market.outcome_count)?;
    require_representation_bound(
        &supply,
        &position.internal,
        &external.balances,
        market.outcome_count,
    )?;

    require(sequence == replay.sequence, ClutchError::Replay)?;
    let next_sequence = replay
        .sequence
        .checked_add(1)
        .ok_or(Refusal::Adapter(ClutchError::Replay))?;

    /* Per-intent authorization and binding, in the offline reference adapter's
     * per-arm order. */
    match op {
        SeamOp::Split { quantity, .. } => {
            authorize_and_bind(actor, &position, market.market, op)?;
            require(
                market.lifecycle == 0 && position.close_state == 0,
                ClutchError::NotActive,
            )?;
            /* Collateral cap and position cash are checked before the kernel
             * runs, in the same order as the offline reference adapter. */
            let next_collateral = hoard
                .collateral_atoms
                .checked_add(*quantity)
                .ok_or(Refusal::Adapter(ClutchError::Arithmetic))?;
            require(
                next_collateral <= market.collateral_cap,
                ClutchError::CollateralCap,
            )?;
            position.cash_atoms = position
                .cash_atoms
                .checked_sub(*quantity)
                .ok_or(Refusal::Adapter(ClutchError::Arithmetic))?;
        }
        SeamOp::Merge { .. } => {
            authorize_and_bind(actor, &position, market.market, op)?;
            require(
                market.lifecycle == 0 && position.close_state == 0,
                ClutchError::NotActive,
            )?;
            /* NO COLLATERAL-CAP CHECK, and the reference adapter has none
             * either: a merge lowers `hoard.collateral_atoms`, so it cannot
             * cross a ceiling the pre-state was under, and a cap check here
             * would strand a market that is somehow already above its cap in
             * the one direction that must always stay open.  The cash credit
             * is not here either: it is the *consequence* of the burn and
             * lands after the kernel step below, mirroring the reference. */
        }
        SeamOp::Materialize { destination, .. } => {
            authorize_and_bind(actor, &position, market.market, op)?;
            /* The caller names a destination; the program never believes it.
             * The external-shadow account at `IX_EXTERNAL` has already been
             * proved to be the canonical derived address, so requiring the
             * named destination to equal it is exactly "the caller named the
             * derived address", which is obligation 1 of the reference adapter
             * doc discharged on-chain rather than assumed. */
            require(
                destination.bytes() == accounts[IX_EXTERNAL].key.to_bytes(),
                ClutchError::WrongPda,
            )?;
        }
        SeamOp::Dematerialize { source, .. } => {
            authorize_and_bind(actor, &position, market.market, op)?;
            require(
                source.bytes() == accounts[IX_EXTERNAL].key.to_bytes(),
                ClutchError::WrongPda,
            )?;
        }
    }

    /* Everything below this line writes.  A refusal after this point aborts the
     * instruction, and SVM transaction semantics -- not this program -- are
     * what discard the partial write. */
    let pre_internal = position.internal;
    let pre_external = external.balances;
    let mut moved = Position {
        internal: pre_internal,
        external: pre_external,
    };
    let kernel_post = {
        let mut kernel_data = accounts[IX_KERNEL]
            .try_borrow_mut_data()
            .map_err(|_| Refusal::Adapter(ClutchError::AccountBorrowFailed))?;
        kernel_step(
            &mut kernel_data,
            market.outcome_count,
            hoard.collateral_atoms,
            &mut moved,
            op,
        )?
    };

    /* A merge's cash credit, at exactly the reference adapter's point in the
     * order: after the kernel burned the complete set that justifies it, and
     * before the ledger delta.  `quantity` is the released collateral because
     * a complete set is worth exactly one atom of it on both sides of the
     * kernel.  `Split`'s debit is a *precondition* and therefore sits above,
     * with the collateral cap; this is a *consequence* and sits here, which is
     * the order `Action::RedeemInternal` credits a payout in too. */
    if let SeamOp::Merge { quantity, .. } = op {
        position.cash_atoms = position
            .cash_atoms
            .checked_add(*quantity)
            .ok_or(Refusal::Adapter(ClutchError::Arithmetic))?;
    }

    {
        let mut supply_data = accounts[IX_SUPPLY]
            .try_borrow_mut_data()
            .map_err(|_| Refusal::Adapter(ClutchError::AccountBorrowFailed))?;
        ledger_step(
            &mut supply_data,
            market.outcome_count,
            &pre_internal,
            &pre_external,
            &moved,
            &kernel_post,
        )?;
    }

    hoard.collateral_atoms = kernel_post.collateral;
    position.internal = moved.internal;
    external.balances = moved.external;
    replay.sequence = next_sequence;

    hoard.encode(
        &mut accounts[IX_HOARD]
            .try_borrow_mut_data()
            .map_err(|_| Refusal::Adapter(ClutchError::AccountBorrowFailed))?,
    )?;
    position.encode(
        &mut accounts[IX_POSITION]
            .try_borrow_mut_data()
            .map_err(|_| Refusal::Adapter(ClutchError::AccountBorrowFailed))?,
    )?;
    external.encode(
        &mut accounts[IX_EXTERNAL]
            .try_borrow_mut_data()
            .map_err(|_| Refusal::Adapter(ClutchError::AccountBorrowFailed))?,
    )?;
    replay.encode(
        &mut accounts[IX_REPLAY]
            .try_borrow_mut_data()
            .map_err(|_| Refusal::Adapter(ClutchError::AccountBorrowFailed))?,
    )?;

    /* Market bytes are deliberately untouched: no seam transition changes them.
     * The differential still compares them against the reference adapter's
     * re-encoded post-state, so a codec that did not round-trip would fail the
     * comparison rather than hide inside a rewrite. */
    Ok(())
}

/// Authenticate the actor as the position owner and bind the intent's names.
///
/// Split out so that the three authorizing intents run one identical pair of
/// checks in one identical order rather than three copies of it.
fn authorize_and_bind(
    actor: &AccountInfo,
    position: &PositionAccount,
    market: Hash32,
    op: &SeamOp,
) -> Outcome<()> {
    require(
        actor.key.to_bytes() == position.owner.bytes(),
        ClutchError::UnauthorizedActor,
    )?;
    require(
        op.market() == market && op.owner() == position.owner,
        ClutchError::MismatchedState,
    )
}

/// Validate hostile accounts and apply exactly one `Split`.
pub fn process(
    program_id: &Pubkey,
    accounts: &[AccountInfo],
    request: &SplitRequest,
) -> Outcome<()> {
    seam(
        program_id,
        accounts,
        request.sequence,
        &SeamOp::Split {
            market: request.market,
            owner: request.owner,
            quantity: request.quantity,
        },
        |ids| derive_bindings(program_id, ids),
    )
}

/* ------------------------------------------------------------------------ */
/* Host differential against the offline reference adapter                   */
/* ------------------------------------------------------------------------ */

/// The seam plane's host-side differential harness, shared with
/// [`super::merge_materialize`].
///
/// Every case here builds one set of fixture bytes, runs **this program's
/// processor path** over `AccountInfo`s holding those bytes, runs
/// `clutch_solana_reference::apply` over the same bytes, and asserts that the
/// two agree: byte-identical post-state when both accept, and corresponding
/// refusal classes when both refuse.  A case where one accepts and the other
/// refuses fails loudly, which is the whole point.
#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use clutch_kernel::{Error as KernelError, PayoutSet, PayoutVector, MAX_PAYOUTS};
    use clutch_solana_layout::{
        canonical_market_id, canonical_outcome_id, canonical_profile_hash, canonical_realm_id,
        CodecError, FeedId, MarketAccount, ProfileAccount, RealmAccount, MAX_INTENT_BYTES,
        PROFILE_FLAG_POLICY_FROZEN, PROFILE_PARENT_BYTES,
    };
    use clutch_solana_reference::{
        apply, AccountMetadata, ActorMetadata, Error as ReferenceError, ExpectedBindings,
        StateBytes, TransitionMetadata, TransitionOutput,
    };

    /// Fixture constants, chosen to be exactly the offline reference adapter's
    /// own `fixture()` so that a disagreement is a real disagreement rather
    /// than two different scenarios.
    const REALM_NONCE: u64 = 7;
    const MARKET_NONCE: u64 = 9;
    const GENERATION: u64 = 2;
    const CASH_ATOMS: u64 = 100;
    const RESERVED_CASH_ATOMS: u64 = 7;
    const COLLATERAL_CAP: u64 = 1_000;
    const OUTCOME_COUNT: u8 = 2;
    const OWNER_FILL: u8 = 31;
    const PROGRAM_FILL: u8 = 0x50;

    /// The reference request envelope's three private constants.
    ///
    /// They are private to `clutch_solana_reference`, so this copy is kept
    /// honest by [`layout_request`], which refuses to return bytes that do not
    /// decode back to the request they claim to encode.
    const REQUEST_TAG: u8 = 0xd1;
    const REFERENCE_VERSION: u8 = 1;
    const ACTION_LAYOUT: u8 = 0;

    pub(crate) fn h(value: u8) -> Hash32 {
        Hash32::from_bytes([value; 32])
    }

    pub(crate) fn key(value: u8) -> Pubkey {
        Pubkey::new_from_array([value; 32])
    }

    fn hash_of(value: &Pubkey) -> Hash32 {
        Hash32::from_bytes(value.to_bytes())
    }

    fn fixed<const N: usize>(data: &[u8]) -> [u8; N] {
        let mut out = [0_u8; N];
        out.copy_from_slice(data);
        out
    }

    /// The nine program-owned account byte images of one seam account list.
    #[derive(Clone, Debug, Eq, PartialEq)]
    pub(crate) struct Seam {
        pub realm: [u8; account_len::REALM],
        pub profile: [u8; account_len::PROFILE],
        pub market: [u8; account_len::MARKET],
        pub hoard: [u8; account_len::HOARD],
        pub position: [u8; account_len::POSITION],
        pub kernel: [u8; KERNEL_ACCOUNT_LEN],
        pub external: [u8; EXTERNAL_ACCOUNT_LEN],
        pub replay: [u8; REPLAY_ACCOUNT_LEN],
        pub supply: [u8; account_len::SUPPLY_LEDGER],
    }

    impl Seam {
        fn datas(&self) -> Vec<Vec<u8>> {
            vec![
                self.realm.to_vec(),
                self.profile.to_vec(),
                self.market.to_vec(),
                self.hoard.to_vec(),
                self.position.to_vec(),
                self.kernel.to_vec(),
                self.external.to_vec(),
                self.replay.to_vec(),
                self.supply.to_vec(),
            ]
        }

        fn from_datas(datas: &[Vec<u8>]) -> Self {
            Self {
                realm: fixed(&datas[0]),
                profile: fixed(&datas[1]),
                market: fixed(&datas[2]),
                hoard: fixed(&datas[3]),
                position: fixed(&datas[4]),
                kernel: fixed(&datas[5]),
                external: fixed(&datas[6]),
                replay: fixed(&datas[7]),
                supply: fixed(&datas[8]),
            }
        }

        fn state_bytes(&self) -> StateBytes<'_> {
            StateBytes {
                market: &self.market,
                hoard: &self.hoard,
                position: &self.position,
                kernel: &self.kernel,
                external: &self.external,
                replay: &self.replay,
                supply: &self.supply,
            }
        }
    }

    /// Owned backing store for one host-side `AccountInfo`.
    struct Cell {
        key: Pubkey,
        owner: Pubkey,
        lamports: u64,
        data: Vec<u8>,
        is_signer: bool,
        is_writable: bool,
        executable: bool,
    }

    impl Cell {
        fn info(&mut self) -> AccountInfo<'_> {
            AccountInfo::new(
                &self.key,
                self.is_signer,
                self.is_writable,
                &mut self.lamports,
                &mut self.data,
                &self.owner,
                self.executable,
            )
        }
    }

    /// One differential scenario: the presented accounts, the trusted
    /// bindings, and the state bytes both adapters run over.
    #[derive(Clone, Debug)]
    pub(crate) struct Case {
        /// Program identity every state account must be owned by.
        pub program: Pubkey,
        /// Presented account keys, in seam account-list order.
        pub keys: [Pubkey; ACCOUNT_COUNT],
        /// Runtime-reported owner of each account.
        pub owners: [Pubkey; ACCOUNT_COUNT],
        /// Declared writability of each account.
        pub writable: [bool; ACCOUNT_COUNT],
        /// Whether the runtime authenticated the actor's signature.
        pub signer: bool,
        /// The trusted derivation both adapters compare against.
        pub bindings: Bindings,
        /// The account byte images.
        pub state: Seam,
    }

    impl Case {
        fn cells(&self) -> Vec<Cell> {
            let mut cells = vec![Cell {
                key: self.keys[IX_ACTOR],
                owner: Pubkey::new_from_array([0; 32]),
                lamports: 1,
                data: Vec::new(),
                is_signer: self.signer,
                is_writable: self.writable[IX_ACTOR],
                executable: false,
            }];
            for (offset, data) in self.state.datas().into_iter().enumerate() {
                let index = offset + IX_REALM;
                cells.push(Cell {
                    key: self.keys[index],
                    owner: self.owners[index],
                    lamports: 1,
                    data,
                    is_signer: false,
                    is_writable: self.writable[index],
                    executable: false,
                });
            }
            cells
        }

        /// Run this program's processor path over the case.
        ///
        /// This mirrors [`crate::dispatch::process`] with exactly one
        /// substitution: already-derived bindings replace
        /// [`derive_bindings`], because program-address derivation is a
        /// runtime syscall (see [`crate::seeds::find`]).  The offline
        /// reference adapter takes the same bindings as trusted input, so the
        /// two sides are compared over the same footing.
        pub(crate) fn program(&self, request: &[u8]) -> (Outcome<()>, Seam) {
            let mut cells = self.cells();
            let result = {
                let infos: Vec<AccountInfo<'_>> = cells.iter_mut().map(Cell::info).collect();
                Request::decode(request)
                    .map_err(Refusal::from)
                    .and_then(|decoded| {
                        let op = seam_op(&decoded)?;
                        seam(&self.program, &infos, decoded.sequence, &op, |_| {
                            self.bindings
                        })
                    })
            };
            let datas: Vec<Vec<u8>> = cells.into_iter().skip(1).map(|cell| cell.data).collect();
            (result, Seam::from_datas(&datas))
        }

        fn metadata(&self) -> TransitionMetadata {
            let account = |index: usize| AccountMetadata {
                key: hash_of(&self.keys[index]),
                owner_program: hash_of(&self.owners[index]),
                writable: self.writable[index],
            };
            TransitionMetadata {
                market: account(IX_MARKET),
                hoard: account(IX_HOARD),
                position: account(IX_POSITION),
                kernel: account(IX_KERNEL),
                external: account(IX_EXTERNAL),
                replay: account(IX_REPLAY),
                supply: account(IX_SUPPLY),
                actor: ActorMetadata {
                    key: hash_of(&self.keys[IX_ACTOR]),
                    signer: self.signer,
                },
            }
        }

        fn expected(&self) -> ExpectedBindings {
            ExpectedBindings {
                program_id: hash_of(&self.program),
                market: hash_of(&self.bindings.market.0),
                hoard: hash_of(&self.bindings.hoard.0),
                position: hash_of(&self.bindings.position.0),
                kernel: hash_of(&self.bindings.kernel.0),
                external: hash_of(&self.bindings.external.0),
                replay: hash_of(&self.bindings.replay.0),
                supply: hash_of(&self.bindings.supply.0),
                market_bump: self.bindings.market.1,
                hoard_bump: self.bindings.hoard.1,
                position_bump: self.bindings.position.1,
                external_bump: self.bindings.external.1,
                replay_bump: self.bindings.replay.1,
                supply_bump: self.bindings.supply.1,
            }
        }

        /// Run the offline reference adapter over the case.
        pub(crate) fn reference(
            &self,
            request: &[u8],
        ) -> core::result::Result<TransitionOutput, ReferenceError> {
            apply(
                request,
                self.state.state_bytes(),
                &self.metadata(),
                &self.expected(),
            )
        }

        /// Assert both adapters agree, and return the shared post-state when
        /// they both accept.
        pub(crate) fn differential(&self, request: &[u8], label: &str) -> Option<Seam> {
            let reference = self.reference(request);
            let (program, post) = self.program(request);
            match (reference, program) {
                (Ok(expected), Ok(())) => {
                    assert_eq!(post.market, expected.market, "{label}: market bytes");
                    assert_eq!(post.hoard, expected.hoard, "{label}: hoard bytes");
                    assert_eq!(post.position, expected.position, "{label}: position bytes");
                    assert_eq!(post.kernel, expected.kernel, "{label}: kernel bytes");
                    assert_eq!(post.external, expected.external, "{label}: external bytes");
                    assert_eq!(post.replay, expected.replay, "{label}: replay bytes");
                    assert_eq!(post.supply, expected.supply, "{label}: supply-ledger bytes");
                    assert_eq!(post.realm, self.state.realm, "{label}: Realm is read-only");
                    assert_eq!(
                        post.profile, self.state.profile,
                        "{label}: Profile is read-only"
                    );
                    Some(post)
                }
                (Err(reference), Err(program)) => {
                    assert_eq!(
                        Class::of_reference(reference),
                        Class::of_program(program),
                        "{label}: refusal class ({reference:?} against {program:?})"
                    );
                    None
                }
                (Ok(_), Err(program)) => {
                    panic!("{label}: the reference accepted and this program refused {program:?}")
                }
                (Err(reference), Ok(())) => {
                    panic!("{label}: this program accepted and the reference refused {reference:?}")
                }
            }
        }

        /// Run one accepted transition and advance the case to its post-state.
        pub(crate) fn advance(&mut self, request: &[u8], label: &str) {
            self.state = self
                .differential(request, label)
                .unwrap_or_else(|| panic!("{label}: both adapters were expected to accept"));
        }

        /// Assert both adapters refuse, in the named class.
        ///
        /// The class is named rather than merely compared so that a case that
        /// starts refusing for a different reason than it was written for
        /// fails instead of quietly still agreeing, and so that a case both
        /// adapters stop refusing at all fails instead of passing vacuously.
        pub(crate) fn refuses(&self, request: &[u8], label: &str, expected: Class) {
            assert!(
                self.differential(request, label).is_none(),
                "{label}: both adapters were expected to refuse"
            );
            assert_eq!(
                Class::of_reference(self.reference(request).expect_err("reference refuses")),
                expected,
                "{label}: reference refusal class"
            );
            assert_eq!(
                Class::of_program(self.program(request).0.expect_err("this program refuses")),
                expected,
                "{label}: this program's refusal class"
            );
        }
    }

    /// The refusal classes the two adapters are compared over.
    ///
    /// The two crates have separate error enums by design — one models an
    /// offline transition, the other a runtime account plane — so a
    /// differential over raw codes would be meaningless.  This is the
    /// correspondence, written once:
    ///
    /// | reference | this program |
    /// | --- | --- |
    /// | `AccountAlias` | `AccountAlias` |
    /// | `MissingSignature` | `MissingSignature` |
    /// | `UnauthorizedActor` | `UnauthorizedActor` |
    /// | `WrongAccountKey`, `WrongBump` | `WrongPda`, `WrongBump` |
    /// | `NotWritable` | `NotWritable`, `UnexpectedWritable` |
    /// | `WrongProgramOwner` | `WrongProgramOwner`, `ExecutableAccount` |
    /// | `MismatchedState` | `MismatchedState`, `NotActive` |
    /// | `NonCanonical` | `NonCanonical` |
    /// | `AggregateClosureMismatch` | `AggregateClosureMismatch` |
    /// | `Replay` | `Replay` |
    /// | `Arithmetic` | `Arithmetic` |
    /// | `CollateralCap` | `CollateralCap` |
    /// | `UnsupportedIntent` | `UnsupportedInstruction` |
    /// | `Kernel(e)` | `Kernel(e)` — the *same* kernel refusal |
    /// | `Layout(e)` | `Codec(e)` — the *same* codec refusal |
    ///
    /// Two of those rows are refinements rather than renames, and both are
    /// deliberate: this program distinguishes a read-only role arriving
    /// writable from a writable role arriving read-only, and distinguishes the
    /// lifecycle/close-state refusal (`NotActive`) from the generic
    /// `MismatchedState` the reference reports for it.  Neither refinement
    /// changes which requests are accepted.
    #[derive(Clone, Copy, Debug, Eq, PartialEq)]
    pub(crate) enum Class {
        Alias,
        Signature,
        Actor,
        Binding,
        Writability,
        Owner,
        MismatchedState,
        NonCanonical,
        Closure,
        Replay,
        Arithmetic,
        CollateralCap,
        Unsupported,
        Kernel(KernelError),
        Codec(CodecError),
        Envelope,
    }

    impl Class {
        fn of_reference(error: ReferenceError) -> Self {
            match error {
                ReferenceError::AccountAlias => Self::Alias,
                ReferenceError::MissingSignature => Self::Signature,
                ReferenceError::UnauthorizedActor => Self::Actor,
                ReferenceError::WrongAccountKey | ReferenceError::WrongBump => Self::Binding,
                ReferenceError::NotWritable => Self::Writability,
                ReferenceError::WrongProgramOwner => Self::Owner,
                ReferenceError::MismatchedState => Self::MismatchedState,
                ReferenceError::NonCanonical => Self::NonCanonical,
                ReferenceError::AggregateClosureMismatch => Self::Closure,
                ReferenceError::Replay => Self::Replay,
                ReferenceError::Arithmetic => Self::Arithmetic,
                ReferenceError::CollateralCap => Self::CollateralCap,
                ReferenceError::UnsupportedIntent => Self::Unsupported,
                ReferenceError::Kernel(inner) => Self::Kernel(inner),
                ReferenceError::Layout(inner) => Self::Codec(inner),
                ReferenceError::WrongLength
                | ReferenceError::WrongTag
                | ReferenceError::WrongVersion => Self::Envelope,
                other => panic!("no differential class for reference refusal {other:?}"),
            }
        }

        fn of_program(refusal: Refusal) -> Self {
            match refusal {
                Refusal::Adapter(ClutchError::AccountAlias) => Self::Alias,
                Refusal::Adapter(ClutchError::MissingSignature) => Self::Signature,
                Refusal::Adapter(ClutchError::UnauthorizedActor) => Self::Actor,
                Refusal::Adapter(ClutchError::WrongPda | ClutchError::WrongBump) => Self::Binding,
                Refusal::Adapter(ClutchError::NotWritable | ClutchError::UnexpectedWritable) => {
                    Self::Writability
                }
                Refusal::Adapter(
                    ClutchError::WrongProgramOwner | ClutchError::ExecutableAccount,
                ) => Self::Owner,
                Refusal::Adapter(ClutchError::MismatchedState | ClutchError::NotActive) => {
                    Self::MismatchedState
                }
                Refusal::Adapter(ClutchError::NonCanonical) => Self::NonCanonical,
                Refusal::Adapter(ClutchError::AggregateClosureMismatch) => Self::Closure,
                Refusal::Adapter(ClutchError::Replay) => Self::Replay,
                Refusal::Adapter(ClutchError::Arithmetic) => Self::Arithmetic,
                Refusal::Adapter(ClutchError::CollateralCap) => Self::CollateralCap,
                Refusal::Adapter(ClutchError::UnsupportedInstruction) => Self::Unsupported,
                Refusal::Kernel(inner) => Self::Kernel(inner),
                Refusal::Codec(inner) => Self::Codec(inner),
                Refusal::Reference(
                    ReferenceError::WrongLength
                    | ReferenceError::WrongTag
                    | ReferenceError::WrongVersion,
                ) => Self::Envelope,
                other => panic!("no differential class for program refusal {other:?}"),
            }
        }
    }

    /// Encode one layout intent into a reference request envelope.
    ///
    /// The envelope constants are copied because they are private to
    /// `clutch_solana_reference`; the round-trip assertion is what makes a
    /// drift in either the constants or the intent codec a test failure here
    /// rather than a silent divergence.
    pub(crate) fn layout_request(sequence: u64, intent: Intent) -> Vec<u8> {
        let mut intent_bytes = [0_u8; MAX_INTENT_BYTES];
        let len = intent.encode(&mut intent_bytes).expect("intent encodes");
        let mut out = Vec::with_capacity(13 + len);
        out.push(REQUEST_TAG);
        out.push(REFERENCE_VERSION);
        out.extend_from_slice(&sequence.to_le_bytes());
        out.push(ACTION_LAYOUT);
        out.extend_from_slice(&(len as u16).to_le_bytes());
        out.extend_from_slice(&intent_bytes[..len]);
        assert_eq!(
            Request::decode(&out),
            Ok(Request {
                sequence,
                action: Action::Layout(intent),
            }),
            "the hand-built envelope must decode to the request it claims"
        );
        out
    }

    fn payout_set() -> PayoutSet {
        let mut vectors = [PayoutVector::ZERO; MAX_PAYOUTS];
        let mut left = [0; MAX_OUTCOMES];
        left[0] = 1;
        vectors[0] = PayoutVector::new(1, left);
        let mut right = [0; MAX_OUTCOMES];
        right[1] = 1;
        vectors[1] = PayoutVector::new(1, right);
        PayoutSet::new(2, 2, vectors)
    }

    /// The market/owner identities the fixture is built around.
    pub(crate) struct Ids {
        pub realm: Hash32,
        pub profile: Hash32,
        pub market: Hash32,
        pub owner: Hash32,
    }

    pub(crate) fn ids() -> Ids {
        let profile = canonical_profile_hash(&[0x5b; PROFILE_PARENT_BYTES])
            .expect("exact parent preimage length");
        let realm = canonical_realm_id(profile, REALM_NONCE);
        Ids {
            realm,
            profile,
            market: canonical_market_id(realm, profile, MARKET_NONCE),
            owner: h(OWNER_FILL),
        }
    }

    /// The canonical accepted seam case.
    ///
    /// Every bump is the offline reference adapter's own fixture bump, so a
    /// case built here and a case built there differ in nothing but the two
    /// Realm/Profile accounts the reference does not model.
    pub(crate) fn fixture() -> Case {
        let Ids {
            realm,
            profile,
            market: market_id,
            owner,
        } = ids();
        let feed = FeedId::from_bytes([9; 32]);
        let mut outcomes = [Hash32::ZERO; MAX_OUTCOMES];
        outcomes[0] = canonical_outcome_id(market_id, 0);
        outcomes[1] = canonical_outcome_id(market_id, 1);

        let realm_account = RealmAccount {
            realm,
            profile,
            max_outcomes: MAX_OUTCOMES as u8,
            profile_version: 2,
            stored_bump: 2,
            flags: 0,
        };
        let profile_account = ProfileAccount {
            profile,
            realm,
            version: 2,
            flags: PROFILE_FLAG_POLICY_FROZEN,
            collateral_policy_digest: h(0xc0),
        };
        let market = MarketAccount {
            market: market_id,
            realm,
            profile,
            terms: h(12),
            outcome_count: OUTCOME_COUNT,
            lifecycle: 0,
            stored_bump: 3,
            hoard_bump: 4,
            outcomes,
            feed,
            collateral_cap: COLLATERAL_CAP,
            created_slot: 55,
            reserved: Hash32::ZERO,
        };
        let hoard = HoardAccount {
            market: market_id,
            realm,
            authority: h(10),
            collateral_atoms: 0,
            stored_bump: 4,
            flags: 0,
        };
        let position = PositionAccount {
            market: market_id,
            owner,
            generation: GENERATION,
            internal: [0; MAX_OUTCOMES],
            cash_atoms: CASH_ATOMS,
            reserved_cash_atoms: RESERVED_CASH_ATOMS,
            stored_bump: 5,
            close_state: 0,
        };
        let kernel = KernelAccount {
            market: market_id,
            phase: 0,
            resolved_payout: 0,
            payouts: payout_set(),
            total_supply: [0; MAX_OUTCOMES],
        };
        let external = ExternalAccount {
            market: market_id,
            owner,
            position_generation: GENERATION,
            balances: [0; MAX_OUTCOMES],
            stored_bump: 6,
            flags: 0,
        };
        let replay = ReplayAccount {
            market: market_id,
            owner,
            position_generation: GENERATION,
            sequence: 0,
            stored_bump: 7,
            flags: 0,
        };
        let supply = SupplyLedgerAccount {
            market: market_id,
            realm,
            generation: GENERATION,
            outcome_count: OUTCOME_COUNT,
            internal_supply: [0; MAX_OUTCOMES],
            external_supply: [0; MAX_OUTCOMES],
            stored_bump: 10,
            flags: 0,
        };

        let mut state = Seam {
            realm: [0; account_len::REALM],
            profile: [0; account_len::PROFILE],
            market: [0; account_len::MARKET],
            hoard: [0; account_len::HOARD],
            position: [0; account_len::POSITION],
            kernel: [0; KERNEL_ACCOUNT_LEN],
            external: [0; EXTERNAL_ACCOUNT_LEN],
            replay: [0; REPLAY_ACCOUNT_LEN],
            supply: [0; account_len::SUPPLY_LEDGER],
        };
        realm_account.encode(&mut state.realm).expect("realm");
        profile_account.encode(&mut state.profile).expect("profile");
        market.encode(&mut state.market).expect("market");
        hoard.encode(&mut state.hoard).expect("hoard");
        position.encode(&mut state.position).expect("position");
        kernel.encode(&mut state.kernel).expect("kernel");
        external.encode(&mut state.external).expect("external");
        replay.encode(&mut state.replay).expect("replay");
        supply.encode(&mut state.supply).expect("supply");

        let program = key(PROGRAM_FILL);
        let keys = [
            Pubkey::new_from_array(owner.bytes()),
            key(51),
            key(52),
            key(53),
            key(54),
            key(55),
            key(56),
            key(57),
            key(58),
            key(59),
        ];
        Case {
            program,
            keys,
            owners: [program; ACCOUNT_COUNT],
            writable: [
                false, false, false, true, true, true, true, true, true, true,
            ],
            signer: true,
            bindings: Bindings {
                realm: (keys[IX_REALM], 2),
                profile: (keys[IX_PROFILE], 0),
                market: (keys[IX_MARKET], 3),
                hoard: (keys[IX_HOARD], 4),
                position: (keys[IX_POSITION], 5),
                kernel: (keys[IX_KERNEL], 0),
                external: (keys[IX_EXTERNAL], 6),
                replay: (keys[IX_REPLAY], 7),
                supply: (keys[IX_SUPPLY], 10),
            },
            state,
        }
    }

    /// A `Split` request for the fixture's market and owner.
    pub(crate) fn split_request(sequence: u64, quantity: u64) -> Vec<u8> {
        let ids = ids();
        layout_request(
            sequence,
            Intent::Split {
                market: ids.market,
                owner: ids.owner,
                quantity,
            },
        )
    }

    /// Overwrite one position field in an already-encoded seam state.
    pub(crate) fn edit_position(state: &mut Seam, edit: impl FnOnce(&mut PositionAccount)) {
        let mut position = PositionAccount::decode(&state.position).expect("position decodes");
        edit(&mut position);
        position.encode(&mut state.position).expect("position");
    }

    #[test]
    fn the_seam_plane_takes_the_supply_ledger_as_its_tenth_account() {
        /* The account list is a check, so its shape is pinned: ten accounts,
         * nine of them program-owned state roles, the ledger last, and exactly
         * two read-only roles. */
        assert_eq!(ACCOUNT_COUNT, 10);
        assert_eq!(STATE_ROLES.len(), ACCOUNT_COUNT - 1);
        assert_eq!(IX_SUPPLY, ACCOUNT_COUNT - 1);
        assert_eq!(STATE_ROLES[8].index, IX_SUPPLY);
        assert_eq!(STATE_ROLES[8].len, account_len::SUPPLY_LEDGER);
        assert!(STATE_ROLES[8].writable);
        assert_eq!(
            STATE_ROLES.iter().filter(|role| !role.writable).count(),
            2,
            "only Realm and Profile are read-only"
        );
        for (offset, role) in STATE_ROLES.iter().enumerate() {
            assert_eq!(role.index, offset + IX_REALM, "roles are in list order");
        }
    }

    #[test]
    fn split_agrees_byte_for_byte_with_the_reference_adapter() {
        let mut case = fixture();
        case.advance(&split_request(0, 11), "split 11");
        case.advance(&split_request(1, 9), "split 9 more");

        /* The ledger is not a copy of the position: it is the market-wide
         * aggregate the position is bounded by, and CLO-DELTA-V1 moved it by
         * the delta twice. */
        let supply = SupplyLedgerAccount::decode(&case.state.supply).expect("ledger decodes");
        assert_eq!(supply.internal_supply[0], 20);
        assert_eq!(supply.internal_supply[1], 20);
        assert_eq!(supply.external_supply[0], 0);
        let position = PositionAccount::decode(&case.state.position).expect("position decodes");
        assert_eq!(position.cash_atoms, CASH_ATOMS - 20);
        assert_eq!(position.internal[0], 20);
    }

    #[test]
    fn split_refusals_agree_with_the_reference_adapter() {
        let base = fixture();

        // Insufficient balance: the position cannot pay the cash the split costs.
        base.refuses(
            &split_request(0, CASH_ATOMS + 1),
            "cash underflow",
            Class::Arithmetic,
        );

        // Wrong signer: authenticated, but not the position owner.
        let mut stranger = fixture();
        stranger.keys[IX_ACTOR] = key(0x9e);
        stranger.refuses(&split_request(0, 11), "stranger signs", Class::Actor);

        // Missing signature.
        let mut unsigned = fixture();
        unsigned.signer = false;
        unsigned.refuses(
            &split_request(0, 11),
            "owner never signed",
            Class::Signature,
        );

        // Aliased accounts: two logical roles filled by one key.
        let mut aliased = fixture();
        aliased.keys[IX_POSITION] = aliased.keys[IX_HOARD];
        aliased.bindings.position = aliased.bindings.hoard;
        aliased.refuses(
            &split_request(0, 11),
            "position aliases hoard",
            Class::Alias,
        );

        // Stale replay.
        base.refuses(&split_request(7, 11), "stale sequence", Class::Replay);

        // A state account this program does not own.
        let mut foreign = fixture();
        foreign.owners[IX_SUPPLY] = key(0xbb);
        foreign.refuses(&split_request(0, 11), "foreign ledger owner", Class::Owner);

        // A writable role presented read-only.
        let mut frozen = fixture();
        frozen.writable[IX_SUPPLY] = false;
        frozen.refuses(
            &split_request(0, 11),
            "read-only ledger",
            Class::Writability,
        );

        // A key that is not the trusted derivation, and a bump that is not.
        let mut wrong_key = fixture();
        wrong_key.bindings.supply.0 = key(0xd4);
        wrong_key.refuses(
            &split_request(0, 11),
            "ledger key is not derived",
            Class::Binding,
        );
        let mut wrong_bump = fixture();
        wrong_bump.bindings.supply.1 = 11;
        wrong_bump.refuses(
            &split_request(0, 11),
            "ledger bump is not canonical",
            Class::Binding,
        );

        // The intent names a market the presented accounts do not carry.
        let ids = ids();
        base.refuses(
            &layout_request(
                0,
                Intent::Split {
                    market: h(0x77),
                    owner: ids.owner,
                    quantity: 11,
                },
            ),
            "intent names another market",
            Class::MismatchedState,
        );

        // The immutable collateral cap.
        base.refuses(
            &split_request(0, COLLATERAL_CAP + 1),
            "collateral cap",
            Class::CollateralCap,
        );

        // A closed position, which this program refines to `NotActive` and the
        // reference reports as `MismatchedState`; both are one class.
        let mut closed = fixture();
        edit_position(&mut closed.state, |position| position.close_state = 1);
        closed.refuses(
            &split_request(0, 11),
            "closing position",
            Class::MismatchedState,
        );
    }

    #[test]
    fn a_forged_position_cannot_split_against_an_empty_ledger() {
        /* CLO-DELTA-V1 C2: a position claiming balance the market-wide ledger
         * does not carry is a counterfeit, and both adapters refuse it before
         * any write. */
        let mut forged = fixture();
        edit_position(&mut forged.state, |position| position.internal[0] = 1);
        forged.refuses(
            &split_request(0, 11),
            "forged internal claim",
            Class::Closure,
        );

        let (result, post) = forged.program(&split_request(0, 11));
        assert_eq!(result, Err(ClutchError::AggregateClosureMismatch.into()));
        assert_eq!(post, forged.state, "a refused split writes nothing");
    }

    /// Join a second owner's position/external/replay triple to the
    /// market-wide accounts of an existing case.
    ///
    /// The second triple carries its own keys, its own bumps, and a position
    /// generation (5) that deliberately differs from the supply ledger's
    /// accounting era (2), which is the CLO-DELTA-V1 decoupling the reference
    /// adapter's own multi-position test pins.
    pub(crate) fn second_position(shared: &Case) -> Case {
        let ids = ids();
        let owner = h(32);
        let position = PositionAccount {
            market: ids.market,
            owner,
            generation: 5,
            internal: [0; MAX_OUTCOMES],
            cash_atoms: CASH_ATOMS,
            reserved_cash_atoms: RESERVED_CASH_ATOMS,
            stored_bump: 15,
            close_state: 0,
        };
        let external = ExternalAccount {
            market: ids.market,
            owner,
            position_generation: 5,
            balances: [0; MAX_OUTCOMES],
            stored_bump: 16,
            flags: 0,
        };
        let replay = ReplayAccount {
            market: ids.market,
            owner,
            position_generation: 5,
            sequence: 0,
            stored_bump: 17,
            flags: 0,
        };
        let mut case = shared.clone();
        position
            .encode(&mut case.state.position)
            .expect("second position");
        external
            .encode(&mut case.state.external)
            .expect("second shadow");
        replay
            .encode(&mut case.state.replay)
            .expect("second replay");
        case.keys[IX_ACTOR] = Pubkey::new_from_array(owner.bytes());
        case.keys[IX_POSITION] = key(60);
        case.keys[IX_EXTERNAL] = key(61);
        case.keys[IX_REPLAY] = key(62);
        case.bindings.position = (case.keys[IX_POSITION], 15);
        case.bindings.external = (case.keys[IX_EXTERNAL], 16);
        case.bindings.replay = (case.keys[IX_REPLAY], 17);
        case
    }

    #[test]
    fn a_second_position_is_representable_and_both_adapters_agree() {
        /* This is the case the retired closed single-position equality made
         * unrepresentable, and the reason the port to CLO-DELTA-V1 was worth
         * taking a tenth account for.  Under the old check the first split
         * would succeed and every later transition by *either* owner would
         * refuse `AggregateClosureMismatch`, because no single position could
         * equal a market aggregate two positions contribute to. */
        let mut first = fixture();
        first.advance(&split_request(0, 20), "first owner splits 20");

        let mut second = second_position(&first);
        let request = layout_request(
            0,
            Intent::Split {
                market: ids().market,
                owner: h(32),
                quantity: 30,
            },
        );
        second.advance(&request, "second owner splits 30");

        let supply = SupplyLedgerAccount::decode(&second.state.supply).expect("ledger decodes");
        let one = PositionAccount::decode(&first.state.position).expect("first decodes");
        let two = PositionAccount::decode(&second.state.position).expect("second decodes");
        assert_eq!(one.internal[0], 20);
        assert_eq!(two.internal[0], 30);
        assert_eq!(
            supply.internal_supply[0],
            one.internal[0] + two.internal[0],
            "the ledger is the sum over positions, not a copy of one of them"
        );
        assert_eq!(supply.internal_supply[1], 50);
        assert_eq!(supply.external_supply[0], 0);

        // The first owner can still transact against the shared aggregate.
        let mut carried = first.clone();
        carried.state = second.state.clone();
        one.encode(&mut carried.state.position)
            .expect("first position");
        ExternalAccount {
            market: ids().market,
            owner: ids().owner,
            position_generation: GENERATION,
            balances: [0; MAX_OUTCOMES],
            stored_bump: 6,
            flags: 0,
        }
        .encode(&mut carried.state.external)
        .expect("first shadow");
        ReplayAccount {
            market: ids().market,
            owner: ids().owner,
            position_generation: GENERATION,
            sequence: 1,
            stored_bump: 7,
            flags: 0,
        }
        .encode(&mut carried.state.replay)
        .expect("first replay");
        carried.advance(&split_request(1, 5), "first owner splits again");
        let supply = SupplyLedgerAccount::decode(&carried.state.supply).expect("ledger decodes");
        assert_eq!(supply.internal_supply[0], 55);
    }

    #[test]
    fn an_unsupported_action_never_reaches_the_seam_plane() {
        /* `crate::dispatch` routes only the four seam intents here, so this is
         * defence in depth; it is pinned because the arm is otherwise
         * untested. */
        let request = Request {
            sequence: 0,
            action: Action::Resolve { payout_index: 0 },
        };
        assert_eq!(
            seam_op(&request),
            Err(ClutchError::UnsupportedInstruction.into())
        );
    }
}
