#!/bin/sh
set -eu

crate_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_dir=$(CDPATH= cd -- "$crate_dir/../.." && pwd)
formal_dir="$repo_dir/formal/dclutch-semantics"
accepted="$crate_dir/src/generated_runtime_v3.rs"
temporary=$(mktemp "${TMPDIR:-/tmp}/dclutch-product-basis-runtime-v3.XXXXXX")
trap 'rm -f "$temporary"' EXIT HUP INT TERM

(
  cd "$formal_dir"
  lake build DClutchSemantics.ProductBasisV3Abi
  lake env lean --run EmitProductBasisV3AbiRust.lean > "$temporary"
)

test "$(sed -n '1p' "$temporary")" = \
  '// @generated by formal/dclutch-semantics/EmitProductBasisV3AbiRust.lean; do not edit.'

# Pinned by value, not merely by shape. Every literal below is an offset that
# deployed decoders already read on chain, so a Lean schema edit that moves one
# fails here rather than at settlement. The two reserved spans are named
# explicitly because they are what lets an old decoder refuse -- rather than
# misread -- a record written by a newer one.
grep -q '^pub const BASIS_HEADER_BYTES_V3: usize = 256;$' "$temporary"
grep -q '^pub const BASIS_SCHEMA_V3: u16 = 3;$' "$temporary"
grep -q '^pub const BASIS_KIND_OFFSET_V3: usize = 16;$' "$temporary"
grep -q '^pub const BASIS_ROUNDING_OFFSET_V3: usize = 17;$' "$temporary"
grep -q '^pub const BASIS_HEADER_RESERVED_OFFSET_V3: usize = 18;$' "$temporary"
grep -q '^pub const BASIS_WIDTH_OFFSET_V3: usize = 20;$' "$temporary"
grep -q '^pub const BASIS_HEADER_TAIL_RESERVED_OFFSET_V3: usize = 208;$' "$temporary"
grep -q '^pub const TERM_BYTES_V3: usize = 32;$' "$temporary"
grep -q '^pub const TERM_AMPLITUDE_OFFSET_V3: usize = 24;$' "$temporary"

rustfmt --edition 2024 "$temporary"
cmp "$temporary" "$accepted"
