#![forbid(unsafe_code)]
#![deny(missing_docs)]

//! Host compiler for one exact recurring-Series Shadow-AOT release bundle.
//!
//! The compiler is deliberately outside the SBF crate's dependency graph. It
//! calls the same canonical Series artifact constructors as Trading, decodes
//! every result again, and returns bytes suitable for a checked-in generated
//! module. It does not choose release identities, synthesize child requests,
//! sign, submit, or publish an ArtifactRelease.

use dclutch_account_profile_contract::{
    lifecycle_v3::{CURRENT_RENT_QUOTE_SCHEMA_RELEASE_ID_V5, StateLifecyclePolicyV5},
    v2::{AccountProfileV2, SCHEMA_RELEASE_ID as ACCOUNT_PROFILE_SCHEMA_RELEASE_ID_V2},
};
use dclutch_capability_program_contract::v4::{
    ArtifactReferenceV4, CAPABILITY_PROGRAM_V4_BYTES, CapabilityArtifactsV4, CapabilityProgramV4,
};
use dclutch_core_contract::ContentId;
use dclutch_effect_kernel::v4::{ProgramV4 as EffectProgramV4, SCHEMA_RELEASE_ID_V4};
use dclutch_execution_strategy_contract::{
    shadow_v3::{SHADOW_ACK_SCHEMA_ID_V3, SHADOW_REQUEST_SCHEMA_ID_V3},
    v2::{
        EXECUTION_STRATEGY_ADMISSION_SCHEMA_ID_V2, EXECUTION_STRATEGY_CERTIFICATE_SCHEMA_ID_V2,
        EXECUTION_STRATEGY_PROGRAM_BYTES_V2, EXECUTION_STRATEGY_PROGRAM_SCHEMA_ID_V2,
        ExecutionStrategyProgramV2, StrategyDispositionV2,
    },
};
use dclutch_request_profile_contract::{RequestProfileV1, SCHEMA_RELEASE_ID as REQUEST_SCHEMA_ID};
use dclutch_trading_sbf::series::{
    account_profile_v4::{
        SERIES_CONSUME_ACCOUNT_PROFILE_BYTES_V4, SeriesConsumeAccountProfileInputV4,
        encode_series_consume_account_profile_v4_atomic,
    },
    consume_artifacts_v4::{
        SERIES_CONSUME_BASE_EFFECT_BYTES_V4, SERIES_CONSUME_EFFECT_BYTES_V4,
        SERIES_CONSUME_REQUEST_PROFILE_BYTES_V4, SERIES_CONSUME_TRANSITION_BYTES_V4,
        SeriesConsumeChildRequestsV4, encode_series_consume_effect_v4_from_requests_atomic,
        encode_series_consume_request_profile_v4_atomic,
        encode_series_consume_transition_v4_atomic,
    },
};
use dclutch_transition_vm::v3::{
    ProgramV3 as TransitionProgramV3, SCHEMA_RELEASE_ID as TRANSITION_SCHEMA_ID,
};
use sha2::{Digest, Sha256};

mod manifest;

pub use manifest::*;

/// Domain for the exact generated bundle and provenance commitment.
pub const SERIES_SHADOW_BUNDLE_DIGEST_DOMAIN_V4: &[u8] =
    b"dclutch:series-shadow-generated-bundle:v4";
/// Semantic identity of this compiler source contract.
pub const SERIES_SHADOW_COMPILER_RELEASE_PREIMAGE_V4: &[u8] =
    b"dclutch/compiler/series-shadow-bundle-v4";
/// Fixed AccountProfile base width before the one dynamic FundingState span.
pub const SERIES_SHADOW_FIXED_ACCOUNT_COUNT_V4: usize = 157;

/// Capability semantic identities selected independently of executable bytes.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SeriesShadowDescriptorSemanticsV4 {
    /// Recurring-Series capability kind.
    pub kind: ContentId,
    /// Finalized Template schema.
    pub config_schema: ContentId,
    /// Family request schema.
    pub request_schema: ContentId,
    /// Mutable Series-root schema.
    pub root_schema: ContentId,
    /// Ticket/occurrence derivation policy.
    pub derivation_policy: ContentId,
    /// Physical capacity profile.
    pub capacity_profile: ContentId,
    /// Exact mutable Series root-tail width.
    pub root_state_bytes: u32,
}

/// Exact source bytes whose identities are committed by the manifest.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SeriesShadowReleaseSourcesV4<'a> {
    /// Exact `series/consume_artifacts_v4.rs` semantic source bytes.
    pub semantic_source: &'a [u8],
    /// Exact generator source bytes used for deterministic rebuilding.
    pub compiler_source: &'a [u8],
    /// Exact pinned compiler/toolchain manifest bytes.
    pub toolchain_manifest: &'a [u8],
    /// Translation-validation certificate content identity.
    pub certificate: ContentId,
}

/// One exact occurrence-specific source manifest.
#[derive(Clone, Copy)]
pub struct SeriesShadowBundleSourceV4<'a> {
    /// Semantic descriptor coordinates.
    pub descriptor: SeriesShadowDescriptorSemanticsV4,
    /// Exact release provenance identities.
    pub release_sources: SeriesShadowReleaseSourcesV4<'a>,
    /// Exact selected LifecycleV5 bytes.
    pub lifecycle: &'a [u8],
    /// Exact pre-execution data widths at the 157 fixed logical coordinates.
    pub fixed_data_lengths: &'a [u32; SERIES_SHADOW_FIXED_ACCOUNT_COUNT_V4],
    /// Exact canonical child requests for this occurrence.
    pub child_requests: SeriesConsumeChildRequestsV4<'a>,
}

/// Complete generated bytes embedded by one specialized accelerator release.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CompiledSeriesShadowBundleV4 {
    /// Exact CapabilityProgramV4 descriptor bytes.
    pub capability_program: [u8; CAPABILITY_PROGRAM_V4_BYTES],
    /// Exact Profile13 bytes.
    pub account_profile: Vec<u8>,
    /// Exact fixed-header RequestProfile bytes.
    pub request_profile: Vec<u8>,
    /// Exact selected LifecycleV5 bytes.
    pub lifecycle: Vec<u8>,
    /// Exact TransitionVM V3 bytes.
    pub transition: Vec<u8>,
    /// Exact global DCE5 Effect bytes.
    pub effect: Vec<u8>,
    /// Exact Shadow-AOT ExecutionStrategy bytes.
    pub strategy: [u8; EXECUTION_STRATEGY_PROGRAM_BYTES_V2],
    /// Translation-validation certificate identity selected by the strategy.
    pub certificate: ContentId,
    /// Reviewed semantic source identity.
    pub semantic_source: ContentId,
    /// Compiler source identity.
    pub compiler_source: ContentId,
    /// Exact compiler/toolchain build-manifest identity.
    pub toolchain: ContentId,
    /// Domain-separated digest of every embedded byte and provenance identity.
    pub bundle_digest: ContentId,
}

/// Stable refusal from bundle compilation or hostile redecoding.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SeriesShadowBundleCompileErrorV4 {
    /// An input content identity or compiler digest was invalid.
    Identity,
    /// LifecycleV5 content authentication or decode refused.
    Lifecycle,
    /// AccountProfile generation or decode refused.
    AccountProfile,
    /// RequestProfile generation or decode refused.
    RequestProfile,
    /// Transition generation or decode refused.
    Transition,
    /// Effect generation or decode refused.
    Effect,
    /// Strategy construction or decode refused.
    Strategy,
    /// CapabilityProgram construction or decode refused.
    CapabilityProgram,
    /// Source-manifest hostile decoding or bounded geometry refused.
    Manifest,
    /// Exact source bytes differed from the identities committed by the manifest.
    SourceIdentity,
    /// Deterministic rebuilding produced any different byte or digest.
    RebuildMismatch,
}

/// Result alias for the exact host compiler.
pub type Result<T> = core::result::Result<T, SeriesShadowBundleCompileErrorV4>;

/// Compile and hostile-redecode one exact occurrence-specific AOT bundle.
pub fn compile_series_shadow_bundle_v4(
    source: SeriesShadowBundleSourceV4<'_>,
) -> Result<CompiledSeriesShadowBundleV4> {
    let lifecycle_id = content(source.lifecycle)?;
    StateLifecyclePolicyV5::decode_selected(
        lifecycle_id.to_bytes(),
        lifecycle_id.to_bytes(),
        source.lifecycle,
    )
    .map_err(|_| SeriesShadowBundleCompileErrorV4::Lifecycle)?;

    let mut account_scratch = vec![0_u8; SERIES_CONSUME_ACCOUNT_PROFILE_BYTES_V4];
    let mut account_profile = vec![0_u8; SERIES_CONSUME_ACCOUNT_PROFILE_BYTES_V4];
    encode_series_consume_account_profile_v4_atomic(
        SeriesConsumeAccountProfileInputV4 {
            fixed_data_lengths: source.fixed_data_lengths,
        },
        &mut account_scratch,
        &mut account_profile,
    )
    .map_err(|_| SeriesShadowBundleCompileErrorV4::AccountProfile)?;
    AccountProfileV2::decode(&account_profile)
        .map_err(|_| SeriesShadowBundleCompileErrorV4::AccountProfile)?;

    let mut request_scratch = vec![0_u8; SERIES_CONSUME_REQUEST_PROFILE_BYTES_V4];
    let mut request_profile = vec![0_u8; SERIES_CONSUME_REQUEST_PROFILE_BYTES_V4];
    encode_series_consume_request_profile_v4_atomic(&mut request_scratch, &mut request_profile)
        .map_err(|_| SeriesShadowBundleCompileErrorV4::RequestProfile)?;
    RequestProfileV1::decode(&request_profile)
        .map_err(|_| SeriesShadowBundleCompileErrorV4::RequestProfile)?;

    let mut transition_scratch = vec![0_u8; SERIES_CONSUME_TRANSITION_BYTES_V4];
    let mut transition = vec![0_u8; SERIES_CONSUME_TRANSITION_BYTES_V4];
    encode_series_consume_transition_v4_atomic(&mut transition_scratch, &mut transition)
        .map_err(|_| SeriesShadowBundleCompileErrorV4::Transition)?;
    TransitionProgramV3::decode(&transition)
        .map_err(|_| SeriesShadowBundleCompileErrorV4::Transition)?;

    let mut base_scratch = vec![0_u8; SERIES_CONSUME_BASE_EFFECT_BYTES_V4];
    let mut base_effect = vec![0_u8; SERIES_CONSUME_BASE_EFFECT_BYTES_V4];
    let mut effect_scratch = vec![0_u8; SERIES_CONSUME_EFFECT_BYTES_V4];
    let mut effect = vec![0_u8; SERIES_CONSUME_EFFECT_BYTES_V4];
    encode_series_consume_effect_v4_from_requests_atomic(
        source.child_requests,
        &mut base_scratch,
        &mut base_effect,
        &mut effect_scratch,
        &mut effect,
    )
    .map_err(|_| SeriesShadowBundleCompileErrorV4::Effect)?;
    EffectProgramV4::decode(&effect).map_err(|_| SeriesShadowBundleCompileErrorV4::Effect)?;

    let account_id = content(&account_profile)?;
    let request_id = content(&request_profile)?;
    let transition_id = content(&transition)?;
    let effect_id = content(&effect)?;
    let strategy_value = ExecutionStrategyProgramV2::new(
        StrategyDispositionV2::ShadowAot,
        id(TRANSITION_SCHEMA_ID)?,
        transition_id,
        id(EXECUTION_STRATEGY_CERTIFICATE_SCHEMA_ID_V2)?,
        Some(source.release_sources.certificate),
        id(EXECUTION_STRATEGY_ADMISSION_SCHEMA_ID_V2)?,
        None,
        id(SHADOW_REQUEST_SCHEMA_ID_V3)?,
        id(SHADOW_ACK_SCHEMA_ID_V3)?,
    )
    .map_err(|_| SeriesShadowBundleCompileErrorV4::Strategy)?;
    let strategy = strategy_value.to_bytes();
    ExecutionStrategyProgramV2::decode(&strategy)
        .map_err(|_| SeriesShadowBundleCompileErrorV4::Strategy)?;
    let strategy_id = content(&strategy)?;

    let descriptor_value = CapabilityProgramV4::new(
        source.descriptor.kind,
        source.descriptor.config_schema,
        source.descriptor.request_schema,
        source.descriptor.root_schema,
        source.descriptor.derivation_policy,
        source.descriptor.capacity_profile,
        CapabilityArtifactsV4 {
            account_profile: reference(ACCOUNT_PROFILE_SCHEMA_RELEASE_ID_V2, account_id)?,
            request_profile: reference(REQUEST_SCHEMA_ID, request_id)?,
            lifecycle: reference(CURRENT_RENT_QUOTE_SCHEMA_RELEASE_ID_V5, lifecycle_id)?,
            strategy: reference(EXECUTION_STRATEGY_PROGRAM_SCHEMA_ID_V2, strategy_id)?,
            transition: reference(TRANSITION_SCHEMA_ID, transition_id)?,
            effect: reference(SCHEMA_RELEASE_ID_V4, effect_id)?,
        },
        source.descriptor.root_state_bytes,
    )
    .map_err(|_| SeriesShadowBundleCompileErrorV4::CapabilityProgram)?;
    let capability_program = descriptor_value.encode();
    CapabilityProgramV4::decode(&capability_program)
        .map_err(|_| SeriesShadowBundleCompileErrorV4::CapabilityProgram)?;

    let semantic_source = content(source.release_sources.semantic_source)?;
    let compiler_source = content(source.release_sources.compiler_source)?;
    let toolchain = content(source.release_sources.toolchain_manifest)?;
    let bundle_digest = bundle_digest(
        &capability_program,
        &account_profile,
        &request_profile,
        source.lifecycle,
        &transition,
        &effect,
        &strategy,
        [
            semantic_source,
            compiler_source,
            toolchain,
            source.release_sources.certificate,
        ],
    )?;
    Ok(CompiledSeriesShadowBundleV4 {
        capability_program,
        account_profile,
        request_profile,
        lifecycle: source.lifecycle.to_vec(),
        transition,
        effect,
        strategy,
        certificate: source.release_sources.certificate,
        semantic_source,
        compiler_source,
        toolchain,
        bundle_digest,
    })
}

fn reference(schema: [u8; 32], program: ContentId) -> Result<ArtifactReferenceV4> {
    Ok(ArtifactReferenceV4::new(id(schema)?, program))
}

fn id(bytes: [u8; 32]) -> Result<ContentId> {
    ContentId::new(bytes).map_err(|_| SeriesShadowBundleCompileErrorV4::Identity)
}

fn content(bytes: &[u8]) -> Result<ContentId> {
    id(Sha256::digest(bytes).into())
}

#[allow(clippy::too_many_arguments)]
pub(crate) fn bundle_digest(
    capability: &[u8],
    account: &[u8],
    request: &[u8],
    lifecycle: &[u8],
    transition: &[u8],
    effect: &[u8],
    strategy: &[u8],
    provenance: [ContentId; 4],
) -> Result<ContentId> {
    let mut hasher = Sha256::new();
    hasher.update(SERIES_SHADOW_BUNDLE_DIGEST_DOMAIN_V4);
    for bytes in [
        capability, account, request, lifecycle, transition, effect, strategy,
    ] {
        hasher.update(
            u64::try_from(bytes.len())
                .map_err(|_| SeriesShadowBundleCompileErrorV4::Identity)?
                .to_le_bytes(),
        );
        hasher.update(bytes);
    }
    for identity in provenance {
        hasher.update(identity.to_bytes());
    }
    id(hasher.finalize().into())
}
