#!/usr/bin/env node
// tools/genref/generate.mjs -- emits docs/reference/ from the protocol's own
// authorities. The OUTPUTS are generated; this file is the hand-written
// renderer and carries the reference's connective prose as templates.
//
// Sources (all in-tree except the inventory, which is produced fresh from the
// tree by the census tool each run):
//   - the route/refusal inventory emitted by `dclutch-route-census inventory`
//     (tools/gauntlet/census), passed in with --inventory
//   - tools/gauntlet/blocked.json
//   - tools/gauntlet/*/bindings.json and */*-bindings.json
//   - tools/gauntlet/CU_BUDGETS.json
//   - crates/dclutch-refusal-registry/src/lib.rs (band allocation)
//   - docs/decisions/*.md (ADR index)
//   - apps/dclutch-web/lib/generated/*.ts (the Lean/Rust-emitted ABI modules,
//     each byte-gated by its own `abi:*:verify`)
//
// Modes:
//   node generate.mjs --inventory FILE            regenerate docs/reference/
//   node generate.mjs --inventory FILE --check    byte-compare, write nothing
//
// docs/reference/ is wholly owned by this generator: on regenerate, stray
// files there are removed; on --check, they fail the gate. Every write goes
// through a same-directory temporary file and an atomic rename, so a failed
// run leaves the last accepted output byte-for-byte intact (AGENTS.md,
// "never redirect a generator directly into a canonical tracked output").
//
// Determinism: no timestamps, no absolute paths, every collection sorted.
// The check gate is the proof.

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { VALIDATOR_TOKEN, launchesLocalValidator } from "./substrate-control.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, "..", "..");

// ---------------------------------------------------------------- arguments

const argv = process.argv.slice(2);
let inventoryPath = null;
let check = false;
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === "--inventory") inventoryPath = argv[++i];
  else if (argv[i] === "--check") check = true;
  else {
    console.error(`genref: unknown argument ${argv[i]}`);
    process.exit(2);
  }
}
if (!inventoryPath) {
  console.error(
    "genref: --inventory FILE is required (tools/genref/generate.sh produces it)",
  );
  process.exit(2);
}

const OUT_DIR = path.join(REPO, "docs", "reference");

// ------------------------------------------------------------------ helpers

const readJSON = (p) => JSON.parse(fs.readFileSync(p, "utf8"));
const read = (p) => fs.readFileSync(p, "utf8");
const sha256 = (p) =>
  crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex");

function mdCell(s) {
  return String(s).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function table(headers, rows, align = null) {
  const sep = headers.map((_, i) =>
    align && align[i] === "r" ? "---:" : "---",
  );
  const line = (cells) => `| ${cells.map(mdCell).join(" | ")} |`;
  return [line(headers), `| ${sep.join(" | ")} |`, ...rows.map(line)].join(
    "\n",
  );
}

function hexBytes(bytes) {
  return bytes.map((b) => b.toString(16).padStart(2, "0")).join(" ");
}

function asciiBytes(bytes) {
  if (bytes.every((b) => b >= 0x20 && b <= 0x7e)) {
    return bytes.map((b) => String.fromCharCode(b)).join("");
  }
  return "";
}

function codeHex(code) {
  return "0x" + code.toString(16).toUpperCase().padStart(4, "0");
}

function num(n) {
  return n.toLocaleString("en-US");
}

function generatedHeader(sources) {
  return [
    "<!--",
    "  @generated by tools/genref/generate.mjs -- DO NOT EDIT.",
    "  Regenerate: tools/genref/generate.sh",
    "  Verify:     tools/genref/generate.sh --check",
    `  Sources: ${sources.join("; ")}`,
    "-->",
    "",
  ].join("\n");
}

// ------------------------------------------------------------ load sources

const inventory = readJSON(inventoryPath);
const programs = [...inventory.programs].sort((a, b) =>
  a.label < b.label ? -1 : 1,
);

const blocked = readJSON(path.join(REPO, "tools", "gauntlet", "blocked.json"));
const budgetsFile = readJSON(
  path.join(REPO, "tools", "gauntlet", "CU_BUDGETS.json"),
);

const gauntletDir = path.join(REPO, "tools", "gauntlet");
const bindingsFiles = [];
for (const entry of fs.readdirSync(gauntletDir).sort()) {
  const sub = path.join(gauntletDir, entry);
  if (!fs.statSync(sub).isDirectory()) continue;
  for (const f of fs.readdirSync(sub).sort()) {
    if (f === "bindings.json" || f.endsWith("-bindings.json")) {
      bindingsFiles.push(path.join(sub, f));
    }
  }
}

const decisionsDir = path.join(REPO, "docs", "decisions");
const decisionFiles = fs
  .readdirSync(decisionsDir)
  .filter((f) => f.endsWith(".md"))
  .sort();

const generatedTsDir = path.join(REPO, "apps", "dclutch-web", "lib", "generated");
const tsModules = fs
  .readdirSync(generatedTsDir)
  .filter((f) => f.endsWith(".ts"))
  .sort();

const registrySource = read(
  path.join(REPO, "crates", "dclutch-refusal-registry", "src", "lib.rs"),
);

// -------------------------------------------------- route execution status

// route id -> [{campaign, outcome, refusal?, file}]
const routeEvidence = new Map();
// Refusal id -> the campaigns whose folded evidence carried it. Derived from
// the same bindings the census folds, never typed: `census observe` refuses to
// admit a `refused` binding unless the chain's own `Program <id> failed:
// custom program error: 0xN` line reports that exact code AND the program the
// refusal id names raised it. So a refusal id reaching this map has fired on a
// real ELF, or its tier is red.
const refusalEvidence = new Map();
// Refusals a campaign observed but credited to no enumerated code. They are
// real refusals and deliberately NOT counted as an observed code.
let uncreditedRefusals = 0;
// binding route refs that match no inventory route id
const unknownRefs = [];

const inventoryRouteIds = new Set();
for (const p of programs) for (const r of p.routes) inventoryRouteIds.add(r.id);

for (const file of bindingsFiles) {
  const rel = path.relative(REPO, file);
  const data = readJSON(file);
  for (const b of data.bindings ?? []) {
    for (const ref of b.routes ?? []) {
      if (!inventoryRouteIds.has(ref)) {
        unknownRefs.push({ ref, file: rel, label: b.label });
        continue;
      }
      if (!routeEvidence.has(ref)) routeEvidence.set(ref, []);
      routeEvidence.get(ref).push({
        campaign: data.campaign ?? rel,
        outcome: b.outcome ?? "?",
        file: rel,
      });
    }
    if (b.outcome === "refused") {
      if (b.refusal) {
        if (!refusalEvidence.has(b.refusal)) refusalEvidence.set(b.refusal, []);
        refusalEvidence.get(b.refusal).push({
          campaign: data.campaign ?? rel,
          file: rel,
        });
      } else if (b.unnamed_refusal) {
        uncreditedRefusals += 1;
      }
    }
  }
}

// ------------------------------------------------ the substrate of a witness

// `routes.md` says "witnessed" and means "a campaign binding names it". That
// sentence hides three different evidence levels behind one word: the C-16
// rehearsal sorted the same 101 witnessed rows and found 0 on devnet, 19 on a
// validator and 57 on an in-process ProgramTest bank. The register could not
// print the difference because nothing in the tree recorded which substrate a
// campaign ran on. `tools/gauntlet/substrates.json` records it, one row per
// campaign, and this is where it is CHECKED -- a declaration nobody verifies is
// the mirror the census exists to refuse.
const SUBSTRATE_RANK = {
  none: 0,
  "program-test": 1,
  "local-validator": 2,
  devnet: 3,
};

const substratesFile = path.join(gauntletDir, "substrates.json");
const substrates = readJSON(substratesFile);
const substrateFor = new Map();
for (const row of substrates.campaigns) {
  substrateFor.set(row.campaign, row);
}

{
  const problems = [];
  const declared = new Set(substrateFor.keys());
  const bound = new Set();
  for (const file of bindingsFiles) {
    bound.add(readJSON(file).campaign ?? path.relative(REPO, file));
  }
  for (const campaign of [...bound].sort()) {
    if (!declared.has(campaign)) {
      problems.push(
        `campaign \`${campaign}\` binds routes but has no row in tools/gauntlet/substrates.json. ` +
          `Add one naming its substrate (${Object.keys(SUBSTRATE_RANK).join(" | ")}), its runner and its producer.`,
      );
    }
  }
  for (const campaign of [...declared].sort()) {
    const row = substrateFor.get(campaign);
    if (!bound.has(campaign)) {
      problems.push(
        `tools/gauntlet/substrates.json declares \`${campaign}\`, which binds no route in any bindings.json. ` +
          `A stale row looks exactly like a live one from the register.`,
      );
    }
    if (!(row.substrate in SUBSTRATE_RANK) || row.substrate === "none") {
      problems.push(`\`${campaign}\`: substrate \`${row.substrate}\` is not one of the declared classes`);
    }
    if (row.reproducible !== true && typeof row.reproducible !== "string") {
      problems.push(
        `\`${campaign}\`: \`reproducible\` must be true or a sentence saying what stops the ` +
          `campaign completing. A campaign that no longer runs has to have somewhere to say so.`,
      );
    }
    for (const key of ["runner", "producer"]) {
      const rel = row[key];
      if (rel !== null && !fs.existsSync(path.join(REPO, rel))) {
        problems.push(`\`${campaign}\`: ${key} \`${rel}\` does not exist`);
      }
    }
    // The positive control. A campaign that says `local-validator` must reach
    // one; a campaign that says `program-test` must not. Without this the
    // substrate column is one more authored sentence, and an authored sentence
    // is the thing this page exists to stop being the only evidence.
    //
    // It used to be `runner.includes("solana-test-validator")` over the raw
    // file, and `tools/gauntlet/lineage/run-lineage.sh` passed it on a COMMENT
    // — a control that could not fail for the reason it exists. It now strips
    // shell comments and follows the scripts the runner invokes one level down,
    // which is where that campaign's validator actually lives. See
    // tools/genref/substrate-control.mjs for what it does and does not claim.
    if (row.runner) {
      const control = launchesLocalValidator(REPO, row.runner);
      if (row.substrate === "local-validator" && !control.launches) {
        problems.push(
          `\`${campaign}\`: declared local-validator, but no executable text in ` +
            `${control.searched.join(", ")} names ${VALIDATOR_TOKEN} ` +
            `(comments do not count, and only scripts the runner invokes are followed)`,
        );
      }
      if (row.substrate === "program-test" && control.launches) {
        problems.push(
          `\`${campaign}\`: declared program-test, but ${control.sites.join(", ")} ` +
            `names ${VALIDATOR_TOKEN} in executable text`,
        );
      }
    }
  }
  if (problems.length > 0) {
    for (const problem of problems) console.error(`genref: ${problem}`);
    console.error(
      "genref: tools/gauntlet/substrates.json does not describe this tree's campaigns.",
    );
    process.exit(1);
  }
}

// ------------------------------------------------------- devnet witnesses

// The one evidence class the register had no channel for. A cohort's devnet
// transactions live in prose evidence documents in five textual shapes, with
// sixteen signatures elided to `X...Y` and no census route id anywhere, so a
// route driven on a public chain for three cohorts running read as
// NEVER-EXECUTED. `docs/evidence/witnesses/*.json` is the channel; every
// chain-derived field in it is written by
// tools/gauntlet/devnet-witness/corroborate.py from devnet's own reply, and a
// claimed route whose program the chain does not show invoked is dropped there
// rather than credited here.
const witnessDir = path.join(REPO, "docs", "evidence", "witnesses");
const devnetWitness = new Map(); // route id -> [{cohort, stage, magic, signature, slot, file}]
const devnetDocuments = [];
if (fs.existsSync(witnessDir)) {
  for (const name of fs.readdirSync(witnessDir).sort()) {
    if (!name.endsWith(".json")) continue;
    const file = path.join(witnessDir, name);
    const document = readJSON(file);
    const rel = path.relative(REPO, file);
    devnetDocuments.push({
      file: rel,
      sha256: sha256(file),
      cohort: document.cohort,
      cluster: document.cluster,
      records: document.records,
    });
    for (const record of document.records ?? []) {
      for (const route of record.routes_corroborated ?? []) {
        if (!devnetWitness.has(route)) devnetWitness.set(route, []);
        devnetWitness.get(route).push({
          cohort: document.cohort,
          stage: record.stage,
          magic: record.magic,
          signature: record.signature,
          slot: record.slot,
          file: rel,
        });
      }
    }
  }
}

// blocked.json: most specific matching rule wins; trailing '*' is a prefix
// glob (the file's own stated rules).
const blockedRules = blocked.blocked.map((b) => ({
  route: b.route,
  reason: b.reason,
}));
function blockedRuleFor(routeId) {
  let best = null;
  for (const rule of blockedRules) {
    if (rule.route.endsWith("*")) {
      const prefix = rule.route.slice(0, -1);
      if (routeId.startsWith(prefix)) {
        if (!best || rule.route.length > best.route.length) best = rule;
      }
    } else if (rule.route === routeId) {
      return rule; // exact always wins
    }
  }
  return best;
}

function firstSentence(s) {
  const m = s.match(/^(.*?\.)(\s|$)/s);
  return (m ? m[1] : s).replaceAll("\n", " ");
}

function routeStatus(routeId) {
  const ev = routeEvidence.get(routeId);
  if (ev) {
    const parts = [...new Set(ev.map((e) => `${e.outcome} (${e.campaign})`))]
      .sort();
    return { kind: "witnessed", text: parts.join("; ") };
  }
  const rule = blockedRuleFor(routeId);
  if (rule) {
    return {
      kind: "blocked",
      text: `blocked by rule \`${rule.route}\`: ${firstSentence(rule.reason)}`,
    };
  }
  return { kind: "none", text: "NEVER-EXECUTED, no stated reason" };
}

// ------------------------------------------------------ refusal band table

// Parse `/// Band ... .` doc lines paired with `pub const *_BASE: u32 = ...;`
const bandRows = [];
{
  const lines = registrySource.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(
      /^pub const ([A-Z0-9_]+(?:_BASE|_REFUSAL_BASE)): u32 = (0x[0-9A-Fa-f_]+);/,
    );
    if (!m) continue;
    // walk back over the doc comment block
    let doc = [];
    for (let j = i - 1; j >= 0; j--) {
      const dm = lines[j].match(/^\/\/\/ ?(.*)$/);
      if (!dm) break;
      doc.unshift(dm[1]);
    }
    const docText = doc.join(" ").trim();
    if (!/^Band /.test(docText)) continue;
    const base = parseInt(m[2].replaceAll("_", ""), 16);
    bandRows.push({
      constant: m[1],
      base,
      band: base >> 12,
      doc: docText.replace(/\.$/, ""),
    });
  }
  bandRows.sort((a, b) => a.base - b.base);
}

// ------------------------------------------------------------ ABI modules

// Parse one machine-emitted TS module into typed constants. Anything the
// parser does not recognize is carried verbatim into an "unrendered" bucket
// rather than dropped: the reference must not silently narrow its source.
function parseTsModule(name) {
  const text = read(path.join(generatedTsDir, name));
  const headerLines = [];
  for (const line of text.split("\n")) {
    if (line.startsWith("//")) headerLines.push(line.replace(/^\/\/ ?/, ""));
    else if (line.trim() === "") continue;
    else break;
  }
  // Split into export statements (statements may span lines).
  const statements = [];
  const re = /^export /gm;
  const starts = [];
  let m;
  while ((m = re.exec(text)) !== null) starts.push(m.index);
  for (let i = 0; i < starts.length; i++) {
    const end = i + 1 < starts.length ? starts[i + 1] : text.length;
    statements.push(text.slice(starts[i], end).trim());
  }

  const numbers = [];
  const byteArrays = [];
  const strings = [];
  const frozen = [];
  const functions = [];
  const unrendered = [];

  for (const stmt of statements) {
    let mm;
    if (
      (mm = stmt.match(/^export const ([A-Za-z0-9_]+) = (-?\d+) as const;$/))
    ) {
      numbers.push({ name: mm[1], value: Number(mm[2]) });
    } else if (
      (mm = stmt.match(
        /^export const ([A-Za-z0-9_]+) = Uint8Array\.from\(\[([\s\S]*?)\]\);$/,
      ))
    ) {
      const bytes = mm[2]
        .split(",")
        .map((s) => s.trim())
        .filter((s) => s.length > 0)
        .map((s) => Number(s));
      byteArrays.push({ name: mm[1], bytes });
    } else if (
      (mm = stmt.match(
        /^export const ([A-Za-z0-9_]+) = new TextEncoder\(\)\.encode\('([^']*)'\);$/,
      ))
    ) {
      strings.push({ name: mm[1], value: mm[2] });
    } else if (
      (mm = stmt.match(
        /^export const ([A-Za-z0-9_]+) = '([^']*)' as const;$/,
      ))
    ) {
      strings.push({ name: mm[1], value: mm[2] });
    } else if (
      (mm = stmt.match(
        /^export const ([A-Za-z0-9_]+) = Object\.freeze\(([\s\S]*?)\) as [\s\S]*?;$/,
      ))
    ) {
      let value = null;
      try {
        value = JSON.parse(mm[2]);
      } catch {
        unrendered.push(stmt);
        continue;
      }
      frozen.push({ name: mm[1], value });
    } else if ((mm = stmt.match(/^export function ([A-Za-z0-9_]+)/))) {
      functions.push({ name: mm[1] });
    } else {
      unrendered.push(stmt);
    }
  }

  return {
    file: name,
    header: headerLines,
    numbers,
    byteArrays,
    strings,
    frozen,
    functions,
    unrendered,
  };
}

const abiModules = tsModules.map(parseTsModule);

// ------------------------------------------------------------------ pages

const pages = new Map(); // relpath -> content

// ---- README.md (index + connective narrative)

{
  const rows = programs.map((p) => [
    `\`${p.label}\``,
    `\`${p.package}\``,
    p.routes.filter((r) => r.kind === "entry").length,
    p.routes.filter((r) => r.kind !== "entry").length,
    p.refusals.length,
  ]);
  const totalRoutes = programs.reduce((n, p) => n + p.routes.length, 0);
  const totalRefusals = programs.reduce((n, p) => n + p.refusals.length, 0);
  const witnessed = [...inventoryRouteIds].filter(
    (id) => routeEvidence.has(id),
  ).length;

  pages.set(
    "README.md",
    generatedHeader([
      "census inventory",
      "tools/gauntlet/blocked.json",
      "tools/gauntlet/*/bindings",
      "tools/gauntlet/CU_BUDGETS.json",
      "crates/dclutch-refusal-registry",
      "docs/decisions",
      "apps/dclutch-web/lib/generated",
    ]) +
      `# dClutch protocol reference

The exact numbers behind dClutch, generated straight from the code -- so
these pages always match the source they describe. Regenerate with
\`tools/genref/generate.sh\`; \`--check\` verifies the match byte for byte.

- [programs.md](programs.md) -- the on-chain programs and what each one
  does.
- [routes.md](routes.md) -- every instruction the programs accept, and
  whether the test campaigns have run it yet.
- [route-witnesses.md](route-witnesses.md) -- and what actually ran it:
  devnet, a local validator, or an in-process test bank, with the artifact
  and digest for each.
- [refusals.md](refusals.md) -- every error code the protocol can return,
  with its meaning.
- [budgets.md](budgets.md) -- what the key transactions cost in compute,
  measured against Solana's per-transaction limit.
- [decisions.md](decisions.md) -- why the architecture is the way it is,
  one decision per record.
- [abi/](abi/README.md) -- byte layouts: magics, PDA seed domains, record
  widths and offsets, account tables.

Current totals: **${programs.length} programs**, **${totalRoutes} routes**
(${witnessed} exercised by the test campaigns), **${totalRefusals} refusal
codes**.

If you'd rather start with prose, the [guides](../guides/README.md)
explain the protocol in plain terms and link back into these tables.

The seven dClutch programs are deployed on Solana devnet, where one market is
now open for trading. These tables describe the checked-in protocol and its
devnet and local tooling; they are not a mainnet release manifest, and that
market's collateral is a devnet test token, so there is no value at risk.
`,
  );
}

// ---- programs.md

{
  const rows = programs.map((p) => {
    const entry = p.entrypoints
      .map((e) => `\`${e.function}\` (${e.provenance})`)
      .join("; ");
    const bands = [
      ...new Set(p.refusals.map((r) => r.code >> 12)),
    ].sort((a, b) => a - b);
    return [
      `\`${p.label}\``,
      `\`${p.package}\``,
      bands.map((b) => "0x" + b.toString(16).toUpperCase()).join(", "),
      p.routes.filter((r) => r.kind === "entry").length,
      p.routes.filter((r) => r.kind !== "entry").length,
      p.refusals.length,
      entry,
    ];
  });
  pages.set(
    "programs.md",
    generatedHeader(["census inventory"]) +
      `# Programs

Every on-chain program in this repository, enumerated from the source under
\`programs/\`. "Entry routes" are the instructions a program dispatches on
directly (selected by magic bytes); "action routes" are the actions
reachable inside an entry route's request.

` +
      table(
        [
          "program",
          "package",
          "refusal band",
          "entry routes",
          "action routes",
          "refusal codes",
          "entrypoint",
        ],
        rows,
      ) +
      "\n",
  );
}

// ---- routes.md

// A route's admissible Market prestates, as the guard's own named constant
// declares them. The census reads the constant structurally; this renders it.
// An empty list is NOT "every phase" -- it is "no phase gate was read here" --
// and the two must not print the same, because a client that cannot tell them
// apart is the defect this column exists to close.
function phaseGate(route, program) {
  const gates = route.admissible_prestates ?? [];
  // "no constant was read here" and "there is no discriminant to read" are
  // different facts about a route, and a client that cannot tell them apart
  // keeps waiting for a phase answer that will never arrive. The census
  // declares the second per program, with its own staleness checks.
  if (gates.length === 0) {
    return program?.no_persisted_discriminant
      ? "no state machine"
      : "no phase gate";
  }
  // Every set NAMES ITS MACHINE. The whole content of a declaration is which
  // discriminant it constrains, and a Market is `Open` for the entire span in
  // which its Source moves `Primary` to `Resolved` -- so a cell that dropped
  // the machine would invite a reader to check a Source set against a Market
  // phase and publish an admission nobody declared.
  const render = (g) => {
    const body =
      g.prestates && g.prestates.length > 0
        ? g.prestates.map((s) => `${s.phase}+${s.readiness}`).join(", ")
        : g.phases.join(", ");
    return `\`${g.machine ?? "market"}: ${body}\``;
  };
  // Entries sharing an `alternative` are the branches of ONE selection, so
  // they unite; everything else is a separate gate on the same execution, so
  // it intersects. Printing them the same way makes a route that admits three
  // phases read as a route that admits none.
  const groups = new Map();
  const conjuncts = [];
  for (const gate of gates) {
    if (gate.alternative === undefined || gate.alternative === null) {
      conjuncts.push(render(gate));
      continue;
    }
    if (!groups.has(gate.alternative)) groups.set(gate.alternative, []);
    groups.get(gate.alternative).push(render(gate));
  }
  for (const members of groups.values()) {
    conjuncts.push(members.length === 1 ? members[0] : members.join(" or "));
  }
  return conjuncts.join("; ");
}

{
  const sections = [];
  const neverExecuted = [];
  let gatedRoutes = 0;
  const noMachine = programs
    .filter((p) => p.no_persisted_discriminant)
    .map(
      (p) =>
        `- \`${p.label}\`'s ${p.routes.length} routes: ` +
        `${p.no_persisted_discriminant}.`,
    )
    .join("\n");
  for (const p of programs) {
    const routes = [...p.routes].sort((a, b) => (a.id < b.id ? -1 : 1));
    const rows = routes.map((r) => {
      const sel = r.selectors
        .map((s) => {
          if (s.kind === "magic") {
            const bytes = [];
            for (let i = 0; i < s.bytes.length; i += 2) {
              bytes.push(parseInt(s.bytes.slice(i, i + 2), 16));
            }
            const a = s.ascii ?? asciiBytes(bytes);
            return a ? `magic \`${a}\`` : `magic \`${s.bytes}\``;
          }
          if (s.kind === "variant") return `variant \`${s.path}\``;
          return `${s.kind} \`${s.constant ?? s.path ?? ""}\``;
        })
        .join("; ");
      const st = routeStatus(r.id);
      if (st.kind === "none") neverExecuted.push(r.id);
      if ((r.admissible_prestates ?? []).length > 0) gatedRoutes += 1;
      return [
        `\`${r.id}\``,
        r.kind,
        sel || "--",
        phaseGate(r, p),
        st.text,
        `\`${r.provenance}\``,
      ];
    });
    sections.push(
      `## ${p.label}\n\n` +
        table(
          ["route", "kind", "selector", "phase", "status", "provenance"],
          rows,
        ),
    );
  }

  let unknown = "";
  if (unknownRefs.length > 0) {
    const rows = unknownRefs
      .sort((a, b) => (a.ref < b.ref ? -1 : 1))
      .map((u) => [`\`${u.ref}\``, `\`${u.file}\``, u.label]);
    unknown =
      `\n\n## Campaign records naming routes the code does not\n\n` +
      `These route names appear in a campaign's records but match no route in
the current code. Each one is stale or a gap; it is listed here so it gets
fixed rather than dropped.\n\n` +
      table(["reference", "bindings file", "binding label"], rows);
  }

  pages.set(
    "routes.md",
    generatedHeader([
      "census inventory",
      "tools/gauntlet/blocked.json",
      "tools/gauntlet/*/bindings",
    ]) +
      `# Routes

Every instruction the programs accept, with its selector and where it
stands:

- **witnessed** -- a campaign binding in \`tools/gauntlet/*/bindings.json\`
  claims this route, and names the campaign. Read that as *bound*, not as
  *corroborated*: this page is generated from the bindings alone, so it
  cannot tell a route whose evidence was folded from one whose campaign has
  never been run. It also cannot tell you WHAT ran the route, and the three
  answers are not interchangeable -- see
  [route-witnesses.md](route-witnesses.md), which splits this column by
  substrate, records the artifact and digest behind each row, and lists the
  entries \`blocked.json\` holds against routes that now execute (a state this
  page renders as \`witnessed\`, because it returns that before it consults
  the blocked set).

  Corroboration against the chain's own logs -- signatures, slots, refusal
  codes, \`Program <address> invoke\` lines -- is a separate pipeline,
  \`dclutch-route-census observe\`, whose output is a \`CENSUS.md\` **written to
  a run directory and never committed**. This page said for months that
  CENSUS.md was the evidence where the two disagree; a reader cannot open it,
  and from inside the repository "corroborated" and "never generated" look the
  same. The devnet half of that corroboration IS in the tree, under
  \`docs/evidence/witnesses/\`, and route-witnesses.md counts it. And even a
  corroborated row is test coverage, never a proof about every input.
- **blocked** -- the route cannot be driven yet, and the reason is written
  down in \`tools/gauntlet/blocked.json\` (rows show the first sentence;
  the file has the rest). A campaign that exists and passes but emits no
  census evidence is recorded here too, with its owner, rather than being
  left to look like a route nobody ever wrote.
- **NEVER-EXECUTED** -- no campaign binding names it and no reason is
  recorded yet.

Currently **${neverExecuted.length}** of **${inventoryRouteIds.size}**
routes are in that last group.

The **phase** column is the route's own guard, not a summary of one. It is
the named admission constant the guard checks against -- one admission type
per persisted state machine, \`MarketAdmissionV1\`,
\`SourceAdmissionV1\`, \`DealerScenarioCheckpointAdmissionV1\` and
\`DealerScenarioReservationAdmissionV1\` today -- read out of the Rust that
enforces it, so a reader is reading the conjunct the program executes.
\`market: Founding+Ready\` is an exact prestate; a bare \`market: Retiring\` is a
guard that names no readiness and so admits every one. It is a NECESSARY
condition and never a sufficient one: an act whose prestate is excluded cannot
succeed, and an act whose prestate is admitted still has every account,
release and request check ahead of it.

Each set names the STATE MACHINE it is over -- \`market: Open\` is the Core
Market's phase, \`source: Primary\` is the Source resolution state -- because a
Market is \`Open\` for the whole span in which its Source moves \`Primary\` to
\`Resolved\`, and a set checked against the wrong discriminant is an admission
nobody declared. A route may carry gates over more than one machine, and then
it passes all of them.

Two sets joined by **or** are the two branches of ONE guard written as a
selection -- \`if action == RedeemTerminal { .. } else { .. }\` -- so the route
admits their UNION. Sets separated by **;** are separate guards on the same
execution, so the route admits their INTERSECTION. A reader that treats the
first as the second reports that a route admitting three phases admits none.

**no phase gate** means no constant was read for that route -- an authoring
route with no state to consult, a guard still written inline, a guard reached
only under a boolean branch or inside a loop that may not be entered, a guard
in a crate this program's dispatch does not reach, or a route the enumerator
could not follow into. It does not mean the route admits every phase, and a
consumer that treats the two alike is repeating the defect this column was
added to close. **${gatedRoutes}** of **${inventoryRouteIds.size}** routes
carry a gate today.

**no state machine** is a DIFFERENT fact, and it is the program's own
declaration rather than an absence: this program persists no lifecycle
discriminant for any route to consult, so no amount of further naming will
ever put a set in these cells. It is carried in the census with two checks --
such a program must declare no admissible-state set, and its sources must name
no known machine's discriminant -- so a state model that grows one makes the
declaration unclassified in the same run. What those programs authenticate
instead:

${noMachine}

` +
      sections.join("\n\n") +
      unknown +
      "\n",
  );
}

// ---- route-witnesses.md

{
  // One row per route: WHAT KIND of thing executed it, and where the artifact
  // that says so lives. `routes.md` answers "did a campaign claim this route";
  // this answers "and what ran, and can I check it without running anything".
  const rows = [];
  const falsifiedBlocks = [];
  const unreproducible = [];
  const klassOf = (substrate) =>
    substrate === "program-test" ? "ProgramTest only" : substrate;
  const counts = {
    devnet: 0,
    "local-validator": 0,
    "program-test": 0,
    "blocked": 0,
    "never-executed": 0,
  };
  const perCampaign = new Map();

  for (const program of programs) {
    for (const route of program.routes) {
      const evidence = routeEvidence.get(route.id) ?? [];
      const campaigns = [...new Set(evidence.map((e) => e.campaign))].sort();
      let best = "none";
      let artifacts = [];
      for (const entry of evidence) {
        const row = substrateFor.get(entry.campaign);
        const substrate = row ? row.substrate : "none";
        if (SUBSTRATE_RANK[substrate] > SUBSTRATE_RANK[best]) {
          best = substrate;
          artifacts = [];
        }
        if (substrate === best && !artifacts.includes(entry.file)) {
          artifacts.push(entry.file);
        }
        const held = perCampaign.get(entry.campaign) ?? new Set();
        held.add(route.id);
        perCampaign.set(entry.campaign, held);
      }
      const devnet = devnetWitness.get(route.id) ?? [];
      if (devnet.length > 0) {
        best = "devnet";
        artifacts = [...new Set(devnet.map((w) => w.file))].sort();
      }

      // A route can be BOTH bound and blocked, and `routes.md` cannot show it:
      // its status function returns `witnessed` before it consults
      // `blockedRuleFor`, so a blocking entry whose route now executes renders
      // as witnessed and its stale reason never surfaces. The C-16 rehearsal
      // found six of them by joining the two files by hand. Here the join is
      // free, so the register prints them.
      const alsoBlocked = best !== "none" ? blockedRuleFor(route.id) : null;
      if (alsoBlocked) {
        falsifiedBlocks.push([
          `\`${route.id}\``,
          klassOf(best),
          campaigns.map((c) => `\`${c}\``).join(", ") || "devnet",
          `\`${alsoBlocked.route}\``,
          firstSentence(alsoBlocked.reason),
        ]);
      }

      let klass = best;
      let detail;
      if (best === "none") {
        const rule = blockedRuleFor(route.id);
        klass = rule ? "blocked" : "never-executed";
        detail = rule ? `blocked by rule \`${rule.route}\`` : "no campaign, no reason recorded";
        artifacts = rule ? ["tools/gauntlet/blocked.json"] : [];
      } else if (best === "devnet") {
        // The campaigns stay in the cell. A devnet witness is the STRONGEST
        // evidence for a route, never the only evidence, and a register that
        // dropped the binding when a stronger one arrived would make a route
        // look less covered the moment it became more covered.
        // One transaction can appear in two witness documents -- a hand-joined
        // one and a discovered one both name the founding magics -- and the
        // route is no better witnessed for being listed twice.
        const chain = [
          ...new Set(
            devnet.map(
              (w) => `cohort ${w.cohort} \`${w.magic ?? w.stage}\` slot ${num(w.slot)}`,
            ),
          ),
        ]
          .sort()
          .join("; ");
        detail =
          campaigns.length > 0
            ? `${chain}; also bound by ${campaigns.map((c) => `\`${c}\``).join(", ")}`
            : chain;
      } else {
        detail = campaigns.map((c) => `\`${c}\``).join(", ");
      }
      counts[klass] += 1;
      // A route whose ONLY evidence comes from campaigns that do not complete
      // at HEAD. Its bindings are claims about a run nobody can repeat, which
      // is a different thing from never having been driven and a different
      // thing again from being driven today.
      if (
        best !== "none" &&
        campaigns.length > 0 &&
        devnet.length === 0 &&
        campaigns.every((c) => substrateFor.get(c).reproducible !== true)
      ) {
        unreproducible.push([`\`${route.id}\``, klassOf(best), campaigns.map((c) => `\`${c}\``).join(", ")]);
      }
      rows.push([
        `\`${route.id}\``,
        klass,
        detail,
        artifacts.map((a) => `\`${a}\``).join("<br>") || "--",
      ]);
    }
  }

  const witnessedByChain = counts.devnet + counts["local-validator"];
  const artifactRows = [];
  for (const file of bindingsFiles) {
    const rel = path.relative(REPO, file);
    const data = readJSON(file);
    const campaign = data.campaign ?? rel;
    const row = substrateFor.get(campaign);
    artifactRows.push([
      `\`${campaign}\``,
      row.substrate,
      row.reproducible === true ? "yes" : "**NO**",
      num((perCampaign.get(campaign) ?? new Set()).size),
      row.runner ? `\`${row.runner}\`` : "**none** -- driven by hand",
      `\`${sha256(file).slice(0, 16)}\``,
    ]);
  }
  for (const document of devnetDocuments) {
    artifactRows.push([
      `cohort ${document.cohort} (${document.cluster})`,
      "devnet",
      "yes",
      num(
        new Set(
          document.records.flatMap((r) => r.routes_corroborated ?? []),
        ).size,
      ),
      "`tools/gauntlet/devnet-witness/corroborate.py`",
      `\`${document.sha256.slice(0, 16)}\``,
    ]);
  }

  const devnetRows = [];
  for (const document of devnetDocuments) {
    for (const record of document.records ?? []) {
      devnetRows.push([
        document.cohort,
        record.stage,
        record.magic ? `\`${record.magic}\`` : "--",
        num(record.slot),
        num((record.routes_corroborated ?? []).length),
        num((record.not_corroborated ?? []).length),
        `\`${record.signature.slice(0, 12)}...\``,
      ]);
    }
  }

  pages.set(
    "route-witnesses.md",
    generatedHeader([
      "census inventory",
      "tools/gauntlet/substrates.json",
      "tools/gauntlet/*/bindings",
      "tools/gauntlet/blocked.json",
      "docs/evidence/witnesses/*.json",
    ]) +
      `# Route witnesses

[routes.md](routes.md) prints **witnessed** when a campaign binding names a
route. That one word covers three different evidence levels, and until this
page existed the register could not tell them apart -- so a route exercised
only by an in-process test bank and a route driven on a public chain rendered
identically. This page is the split, and it is generated, so "corroborated"
and "never generated" stop being indistinguishable from inside the repository.

Every row names the artifact you would read to check it and that artifact's
SHA-256, so a reviewer can verify a claim without re-running a gauntlet.

| class | routes | what actually executed the route |
| --- | ---: | --- |
| **devnet** | **${num(counts.devnet)}** | a finalized transaction on Solana devnet, named by signature and slot, and corroborated against the chain's own logs |
| **local validator** | ${num(counts["local-validator"])} | \`solana-test-validator\`: a real Agave runtime, real slots, real finalization, on localhost |
| **ProgramTest only** | ${num(counts["program-test"])} | an in-process \`solana-program-test\` bank. It runs the REAL SBF ELFs -- which is why it is evidence -- but it is not a validator: no packet limit, no leader schedule, no finalization, no fee market |
| **blocked** | ${num(counts.blocked)} | no campaign; \`tools/gauntlet/blocked.json\` records a reason and an owner |
| **never-executed** | ${num(counts["never-executed"])} | no campaign and no reason recorded |

**A real Agave runtime drives ${num(witnessedByChain)} of the
${num(rows.length)}.** \`docs/MASTER_COMPLETION_CONTRACT.md\` item 5 asks for a local
validator or devnet transaction where the route is chain-facing; those are the
rows that meet it. The ProgramTest column is not a lesser version of the same
thing -- \`tools/gauntlet/DESIGN.md\` admits that substrate only as a labelled
fast lane, and a route witnessed there alone has never been refused for size
or for time by a runtime that could.

## What a devnet witness does and does not say

It says: this signature is finalized on devnet, its outer instruction's first
eight bytes are the declared magic sent to the declared program, and the
transaction's own \`Program <address> invoke\` lines show every claimed route's
program running. That is \`dclutch-route-census observe\`'s rule, applied
unchanged to a public chain.

It does **not** say which internal branch a program took, and it is not a
proof about every input. A claimed route whose program the chain does not show
invoked is recorded in the witness document's \`not_corroborated\` list and is
counted nowhere.

${
  devnetRows.length > 0
    ? table(
        ["cohort", "stage", "magic", "slot", "routes", "dropped", "signature"],
        devnetRows,
        [null, null, null, "r", "r", "r", null],
      )
    : "*No devnet witness document exists yet, so the devnet count above is zero.*"
}

Refresh a document with \`tools/gauntlet/devnet-witness/corroborate.py --write
FILE\`; \`--check\` re-reads every one of them from devnet and fails on any
field the chain does not agree with.

## Campaigns, and the substrate each one ran on

Declared in \`tools/gauntlet/substrates.json\` and checked here: a campaign that
says \`local-validator\` must NAME \`solana-test-validator\` in executable text --
in its runner, or in a script that runner invokes -- a campaign that says
\`program-test\` must not, and a campaign that binds a route with no row at all
fails this generator rather than rendering as \`unknown\`. Shell comments are
stripped before the search, because until 2026-09-04 they were not and one
campaign passed this control on a sentence in its header.

` +
      table(
        ["campaign", "substrate", "reproduces", "routes", "runner", "artifact sha256"],
        artifactRows,
        [null, null, null, "r", null, null],
      ) +
      `

## Routes whose only witness is a campaign that does not reproduce

A binding is a claim about a run that happened. A claim whose run cannot be
repeated is not corroboration, and \`tools/gauntlet/substrates.json\` now carries
a \`reproduces\` field per campaign so a campaign that stops completing has
somewhere to say so. These are the routes left standing on one.

${
  unreproducible.length > 0
    ? table(["route", "class", "the campaign(s)"], unreproducible)
    : "*None: every witnessed route has at least one campaign that completes.*"
}

## Blocks their own route has already falsified

\`tools/gauntlet/blocked.json\`'s rule is "keep an entry only while it is true,
and delete it the moment its route executes". [routes.md](routes.md) cannot
enforce it: that page returns **witnessed** before it consults the blocked set,
so a route that is both bound and blocked renders as witnessed and its stale
reason never surfaces. The join is free here, so these are the entries whose
route now executes.

${
  falsifiedBlocks.length > 0
    ? table(
        ["route", "class", "driven by", "blocking rule", "the reason, first sentence"],
        falsifiedBlocks,
      )
    : "*None: every blocking entry names a route no campaign drives.*"
}

## Every route

` +
      table(["route", "class", "evidence", "artifact"], rows) +
      "\n",
  );
}

// ---- refusals.md

{
  const bandTable = table(
    ["base", "band", "allocation"],
    bandRows.map((b) => [
      `\`${codeHex(b.base)}\``,
      "0x" + b.band.toString(16).toUpperCase(),
      b.doc,
    ]),
  );

  const observedCell = (id) => {
    const ev = refusalEvidence.get(id);
    if (!ev) return "--";
    return [...new Set(ev.map((e) => e.campaign))].sort().join("; ");
  };

  const sections = programs.map((p) => {
    const refusals = [...p.refusals].sort((a, b) => a.code - b.code);
    const rows = refusals.map((r) => [
      `\`${codeHex(r.code)}\``,
      `\`${r.enum_name}::${r.variant}\``,
      r.summary || "(no doc comment)",
      observedCell(r.id),
      `\`${r.provenance}\``,
    ]);
    return (
      `## ${p.label}\n\n` +
      table(["code", "refusal", "meaning", "observed firing", "provenance"], rows)
    );
  });

  const totalRefusals = programs.reduce((n, p) => n + p.refusals.length, 0);
  const inventoryRefusalIds = new Set();
  for (const p of programs) for (const r of p.refusals) inventoryRefusalIds.add(r.id);
  const observedIds = [...refusalEvidence.keys()].filter((id) =>
    inventoryRefusalIds.has(id),
  );
  const observedCount = observedIds.length;
  const observingCampaigns = [
    ...new Set(
      [...refusalEvidence.values()].flat().map((e) => e.campaign),
    ),
  ].sort();

  pages.set(
    "refusals.md",
    generatedHeader([
      "census inventory",
      "crates/dclutch-refusal-registry/src/lib.rs",
    ]) +
      `# Refusal codes

Every error code the protocol can return, with its meaning. When dClutch
refuses a transaction, the whole transaction rolls back -- no partial
effect survives -- and the code says exactly which program refused and why.
A refusal isn't a malfunction; it's the protocol keeping the rules.

Reading a code: each program owns its own block ("band") of codes, and
\`band = code >> 12\` -- drop the last three hex digits to get the band. So
\`custom program error: 0x5180\` is band 5, which is Claims. Band 0 is
never used, meaning a code below \`0x1000\` came from some other program in
your transaction, not from dClutch. Bands at \`0x100000\` and above belong
to test-only programs that are never deployed.

The tables below carry all **${totalRefusals}** codes, with meanings taken
from the source code's own documentation.

## Which of these have actually fired

**${observedCount} of ${totalRefusals}** codes have been observed refusing a real
transaction against a compiled ELF.

The \`observed firing\` column names the campaign that saw each one. It is
DERIVED at generation time and never typed: it is read out of the census
bindings under \`tools/gauntlet/*/bindings.json\`, the same place
\`routes.md\` takes its route evidence from. Nobody maintains this number, and
a count carried by hand is exactly what it replaces.

That derivation is sound because of what a binding costs to write. \`census
observe\` refuses to admit a \`refused\` binding unless the finalized logs carry
\`custom program error: 0xN\` for exactly the code the refusal id names, AND the
program the chain says raised it is the program that id belongs to. A code
cannot reach this column by being claimed; a fold had to have seen it.

**Two things this column is not.**

It reads the bindings, not the ledgers. The folded observation ledgers live
under \`/private/tmp\` and are not checked in, so the per-transaction records
are outside this repository and this column cannot cite a signature or a slot.
What it can say, and does, is which campaign's bindings a fold validated. If the
ledgers are ever checked in, this column should read them instead and gain the
citation.

${
    uncreditedRefusals === 0
      ? "It also counts only codes credited to a program's own taxonomy. No campaign currently records an uncredited refusal."
      : `It also counts only codes credited to a program's own taxonomy. A further
${uncreditedRefusals} binding${uncreditedRefusals === 1 ? "" : "s"} record${uncreditedRefusals === 1 ? "s" : ""} a refusal the chain really did report but which is
credited to no enumerated code -- a child's code propagated verbatim through the
frame that invoked it, most often. Those are real refusals and are deliberately
not counted above.`
  }

**And the denominator is the narrower of two.** These tables carry the
${totalRefusals} codes belonging to the programs the route census enumerates.
The tree as a whole declares more -- the census reports its own, larger figure
across every package it indexes -- and the difference is codes in packages that
have no enumerated program, so no campaign could observe them through a route.

${
    observedCount === 0
      ? "No campaign in this tree currently binds a named refusal."
      : `The ${observingCampaigns.length} campaigns contributing:
${observingCampaigns.map((c) => `\`${c}\``).join(", ")}.`
  }

## Band allocation

${bandTable}

` +
      sections.join("\n\n") +
      "\n",
  );
}

// ---- budgets.md

{
  const budgets = budgetsFile.budgets;
  const label = (e) =>
    e.scope === "stage"
      ? `stage ${e.stage.index}: ${e.stage.name} (${e.stage.program_role})`
      : e.transaction;
  const enforced = budgets.filter((e) => e.enforced);
  const recorded = budgets.filter((e) => !e.enforced);

  const mainRows = enforced.map((e) => [
    `\`${e.id}\``,
    e.campaign,
    e.scope,
    label(e),
    num(e.measured),
    num(e.tolerance),
    num(e.budget),
  ]);
  const recRows = recorded.map((e) => [
    `\`${e.id}\``,
    e.campaign,
    e.scope,
    label(e),
    e.measured ? num(e.measured) : "--",
    firstSentence(e.unenforced_reason ?? ""),
  ]);

  const provenance = budgets
    .map((e) => `- \`${e.id}\` -- ${e.provenance.replaceAll("\n", " ")}`)
    .join("\n");

  pages.set(
    "budgets.md",
    generatedHeader(["tools/gauntlet/CU_BUDGETS.json"]) +
      `# Compute budgets for the golden transactions

What the protocol's key transactions cost, in compute units, measured from
real runs. Solana allows at most
**${num(budgetsFile.ceiling.compute_units)} CU** per transaction; a budget
above that ceiling fails this file's own checks, so a transaction that
stops fitting gets caught here, loudly.

Each budget is measured cost plus a tolerance
(\`${budgetsFile.tolerance_rule.formula}\`), where the measured value is
the highest cost seen across runs, never a single run. Changing a number?
Read \`tools/gauntlet/CU_BUDGETS.md\` first -- costs move with the accounts
in play, and it explains how much of that is noise.

## Enforced budgets

` +
      table(
        ["id", "campaign", "scope", "what", "measured", "tolerance", "budget"],
        mainRows,
        [null, null, null, null, "r", "r", "r"],
      ) +
      `

## Recorded, not enforced

` +
      table(
        ["id", "campaign", "scope", "what", "measured", "why unenforced"],
        recRows,
        [null, null, null, null, "r", null],
      ) +
      `

## Provenance

${provenance}
`,
  );
}

// ---- decisions.md

{
  const rows = [];
  for (const f of decisionFiles) {
    const text = read(path.join(decisionsDir, f));
    const lines = text.split("\n");
    const title = (lines[0] ?? "").replace(/^#\s*/, "");
    let status = "";
    for (let i = 1; i < lines.length; i++) {
      if (lines[i].startsWith("Status:")) {
        const para = [];
        for (let j = i; j < lines.length && lines[j].trim() !== ""; j++) {
          para.push(lines[j]);
        }
        status = firstSentence(
          para.join(" ").replace(/^Status:\s*/, ""),
        );
        break;
      }
    }
    rows.push([`[${title}](../decisions/${f})`, status]);
  }
  pages.set(
    "decisions.md",
    generatedHeader(["docs/decisions/*.md"]) +
      `# Architecture decision records

Why the protocol is built the way it is, one decision per record. Each
record carries its context, the alternatives, and the consequences; this
index shows each record's current status.

` +
      table(["decision", "status"], rows) +
      "\n",
  );
}

// ---- abi/ pages

{
  const indexRows = [];
  for (const mod of abiModules) {
    const base = mod.file.replace(/\.ts$/, "");
    const out = `abi/${base}.md`;
    indexRows.push([
      `[${base}](${base}.md)`,
      mod.header.find((l) => l.includes("@generated"))?.replace(
        /^@generated /,
        "",
      ) ?? "",
      mod.header
        .find((l) => l.startsWith("Regenerate with:"))
        ?.replace(/^Regenerate with:\s*/, "") ?? "",
    ]);

    const parts = [];
    parts.push(
      generatedHeader([
        `apps/dclutch-web/lib/generated/${mod.file} (which is itself generated -- see its header below)`,
      ]),
    );
    parts.push(`# ABI: ${base}\n`);
    parts.push(
      `Source module: \`apps/dclutch-web/lib/generated/${mod.file}\`, whose own header reads:\n`,
    );
    parts.push("```");
    parts.push(...mod.header);
    parts.push("```\n");

    if (mod.byteArrays.length > 0) {
      const rows = mod.byteArrays.map((b) => {
        const a = asciiBytes(b.bytes);
        return [
          `\`${b.name}\``,
          b.bytes.length,
          a ? `\`${a}\`` : "--",
          `\`${hexBytes(b.bytes)}\``,
        ];
      });
      parts.push(`## Byte constants (magics, seed domains, schema identities)\n`);
      parts.push(table(["name", "len", "ascii", "bytes"], rows));
      parts.push("");
    }

    if (mod.strings.length > 0) {
      const rows = mod.strings.map((s) => [`\`${s.name}\``, `\`${s.value}\``]);
      parts.push(`## String constants\n`);
      parts.push(table(["name", "value"], rows));
      parts.push("");
    }

    if (mod.numbers.length > 0) {
      const rows = mod.numbers.map((n) => [`\`${n.name}\``, num(n.value)]);
      parts.push(`## Numeric constants (widths, offsets, counts, tags)\n`);
      parts.push(table(["name", "value"], rows, [null, "r"]));
      parts.push("");
    }

    // Pair *LABELS* arrays with their *ROLES* siblings into account tables.
    const consumed = new Set();
    for (const fz of mod.frozen) {
      if (!fz.name.includes("LABELS")) continue;
      const rolesName = fz.name.replace("LABELS", "ROLES");
      const roles = mod.frozen.find((g) => g.name === rolesName);
      if (
        roles &&
        Array.isArray(roles.value) &&
        roles.value.length === fz.value.length &&
        roles.value.every((v) => typeof v === "object" && v !== null)
      ) {
        consumed.add(fz.name);
        consumed.add(rolesName);
        const rows = fz.value.map((labelText, i) => [
          i,
          labelText,
          roles.value[i].signer ? "signer" : "",
          roles.value[i].writable ? "writable" : "",
        ]);
        parts.push(`## Account table: \`${fz.name}\` / \`${rolesName}\`\n`);
        parts.push(table(["#", "account", "signer", "writable"], rows));
        parts.push("");
      }
    }
    for (const fz of mod.frozen) {
      if (consumed.has(fz.name)) continue;
      parts.push(`## \`${fz.name}\`\n`);
      if (Array.isArray(fz.value) && fz.value.every((v) => typeof v !== "object")) {
        parts.push(
          table(
            ["#", "value"],
            fz.value.map((v, i) => [i, `\`${String(v)}\``]),
          ),
        );
      } else {
        parts.push("```json");
        parts.push(JSON.stringify(fz.value, null, 1));
        parts.push("```");
      }
      parts.push("");
    }

    if (mod.functions.length > 0) {
      parts.push(`## Functions (see the source module)\n`);
      parts.push(mod.functions.map((f) => `- \`${f.name}\``).join("\n"));
      parts.push("");
    }

    if (mod.unrendered.length > 0) {
      parts.push(`## Unrendered exports (verbatim)\n`);
      parts.push(
        "The renderer did not recognize these statement shapes, so they are\nshown verbatim rather than dropped.\n",
      );
      for (const stmt of mod.unrendered) {
        parts.push("```ts");
        parts.push(stmt);
        parts.push("```");
      }
      parts.push("");
    }

    pages.set(out, parts.join("\n"));
  }

  pages.set(
    "abi/README.md",
    generatedHeader(["apps/dclutch-web/lib/generated/*.ts"]) +
      `# ABI surfaces

The exact bytes the protocol speaks: instruction magics, PDA seed domains,
record widths and field offsets, and account tables -- one page per
surface.

These pages are rendered from the same generated modules the web app uses
to decode chain data (\`apps/dclutch-web/lib/generated/\`). Each module is
byte-checked against the Rust or Lean source that defines its layout, and
\`npm test\` runs every check.

` +
      table(["surface", "module authority", "regenerate"], indexRows) +
      "\n",
  );
}

// ----------------------------------------------------------- write / check

function walk(dir, base = dir, acc = []) {
  if (!fs.existsSync(dir)) return acc;
  for (const e of fs.readdirSync(dir).sort()) {
    const p = path.join(dir, e);
    if (fs.statSync(p).isDirectory()) walk(p, base, acc);
    else acc.push(path.relative(base, p));
  }
  return acc;
}

const expected = new Map(
  [...pages.entries()].sort(([a], [b]) => (a < b ? -1 : 1)),
);

if (check) {
  const existing = walk(OUT_DIR);
  let failed = false;
  for (const [rel, content] of expected) {
    const p = path.join(OUT_DIR, rel);
    if (!fs.existsSync(p)) {
      console.error(`genref check: MISSING ${path.relative(REPO, p)}`);
      failed = true;
    } else if (read(p) !== content) {
      console.error(`genref check: STALE ${path.relative(REPO, p)}`);
      failed = true;
    }
  }
  for (const rel of existing) {
    if (!expected.has(rel)) {
      console.error(
        `genref check: STRAY ${path.join("docs/reference", rel)} (not produced by the generator)`,
      );
      failed = true;
    }
  }
  if (failed) {
    console.error(
      "genref check: docs/reference is not the generator's output. Regenerate with tools/genref/generate.sh and commit the result.",
    );
    process.exit(1);
  }
  console.log(
    `genref check: docs/reference matches (${expected.size} files, byte-identical).`,
  );
} else {
  fs.mkdirSync(path.join(OUT_DIR, "abi"), { recursive: true });
  for (const [rel, content] of expected) {
    const p = path.join(OUT_DIR, rel);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    const tmp = p + ".genref-tmp";
    fs.writeFileSync(tmp, content);
    fs.renameSync(tmp, p);
  }
  for (const rel of walk(OUT_DIR)) {
    if (!expected.has(rel)) {
      fs.unlinkSync(path.join(OUT_DIR, rel));
      console.log(`genref: removed stray ${path.join("docs/reference", rel)}`);
    }
  }
  console.log(`genref: wrote ${expected.size} files under docs/reference/.`);
}
