#!/usr/bin/env node
// tools/genref/generate.mjs -- emits docs/reference/ from the protocol's own
// authorities. The OUTPUTS are generated; this file is the hand-written
// renderer and carries the reference's connective prose as templates.
//
// Sources (all in-tree except the inventory, which is produced fresh from the
// tree by the census tool each run):
//   - the route/refusal inventory emitted by `dclutch-route-census inventory`
//     (tools/gauntlet/census), passed in with --inventory
//   - tools/gauntlet/blocked.json
//   - tools/gauntlet/execution-evidence.json and its declared census ledgers
//   - tools/gauntlet/*/bindings.json and */*-bindings.json
//   - docs/evidence/witnesses/*.json (corroborated devnet transactions)
//   - tools/gauntlet/CU_BUDGETS.json
//   - crates/dclutch-refusal-registry/src/lib.rs (band allocation)
//   - docs/decisions/*.md (ADR index)
//   - packages/dclutch-sdk/lib/generated/*.ts (the Lean/Rust-emitted ABI modules,
//     each byte-gated by its own `abi:*:verify`)
//
// Modes:
//   node generate.mjs --inventory FILE            regenerate docs/reference/
//   node generate.mjs --inventory FILE --check    byte-compare, write nothing
//
// docs/reference/ is wholly owned by this generator: on regenerate, stray
// files there are removed; on --check, they fail the gate. Every write goes
// through a same-directory temporary file and an atomic rename, so a failed
// run leaves the last accepted output byte-for-byte intact (AGENTS.md,
// "never redirect a generator directly into a canonical tracked output").
//
// Determinism: no timestamps, no absolute paths, every collection sorted.
// The check gate is the proof.

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { VALIDATOR_TOKEN, launchesLocalValidator } from "./substrate-control.mjs";
import {
  SUBSTRATE_RANK,
  classifyRouteEvidence,
} from "./route-evidence.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, "..", "..");

// ---------------------------------------------------------------- arguments

const argv = process.argv.slice(2);
let inventoryPath = null;
let check = false;
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === "--inventory") inventoryPath = argv[++i];
  else if (argv[i] === "--check") check = true;
  else {
    console.error(`genref: unknown argument ${argv[i]}`);
    process.exit(2);
  }
}
if (!inventoryPath) {
  console.error(
    "genref: --inventory FILE is required (tools/gate reference produces it)",
  );
  process.exit(2);
}

const OUT_DIR = path.join(REPO, "docs", "reference");

// ------------------------------------------------------------------ helpers

const readJSON = (p) => JSON.parse(fs.readFileSync(p, "utf8"));
const read = (p) => fs.readFileSync(p, "utf8");
const sha256 = (p) =>
  crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex");

function mdCell(s) {
  return String(s).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function table(headers, rows, align = null) {
  const sep = headers.map((_, i) =>
    align && align[i] === "r" ? "---:" : "---",
  );
  const line = (cells) => `| ${cells.map(mdCell).join(" | ")} |`;
  return [line(headers), `| ${sep.join(" | ")} |`, ...rows.map(line)].join(
    "\n",
  );
}

function hexBytes(bytes) {
  return bytes.map((b) => b.toString(16).padStart(2, "0")).join(" ");
}

function asciiBytes(bytes) {
  if (bytes.every((b) => b >= 0x20 && b <= 0x7e)) {
    return bytes.map((b) => String.fromCharCode(b)).join("");
  }
  return "";
}

function codeHex(code) {
  return "0x" + code.toString(16).toUpperCase().padStart(4, "0");
}

function num(n) {
  return n.toLocaleString("en-US");
}

// Connective prose that interpolates a derived count changes width when the
// count does. Wrapping it here is what lets the sentence be DERIVED rather than
// hand-written to fit the column: greedy, deterministic, no reflow of anything
// already broken by the author.
function wrap(text, width = 76) {
  const out = [];
  for (const paragraph of text.trim().split("\n\n")) {
    let line = "";
    for (const word of paragraph.split(/\s+/)) {
      if (line && line.length + 1 + word.length > width) {
        out.push(line);
        line = word;
      } else line = line ? `${line} ${word}` : word;
    }
    if (line) out.push(line);
    out.push("");
  }
  return out.slice(0, -1).join("\n");
}

function generatedHeader(sources) {
  return [
    "<!--",
    "  @generated by tools/genref/generate.mjs -- DO NOT EDIT.",
    "  Regenerate: tools/gate reference --converge",
    "  Verify:     tools/gate reference --check --converge",
    `  Sources: ${sources.join("; ")}`,
    "-->",
    "",
  ].join("\n");
}

// ------------------------------------------------------------ load sources

const inventory = readJSON(inventoryPath);
const programs = [...inventory.programs].sort((a, b) =>
  a.label < b.label ? -1 : 1,
);

const blocked = readJSON(path.join(REPO, "tools", "gauntlet", "blocked.json"));
const budgetsFile = readJSON(
  path.join(REPO, "tools", "gauntlet", "CU_BUDGETS.json"),
);

const gauntletDir = path.join(REPO, "tools", "gauntlet");
const bindingsFiles = [];
for (const entry of fs.readdirSync(gauntletDir).sort()) {
  const sub = path.join(gauntletDir, entry);
  if (!fs.statSync(sub).isDirectory()) continue;
  for (const f of fs.readdirSync(sub).sort()) {
    if (f === "bindings.json" || f.endsWith("-bindings.json")) {
      bindingsFiles.push(path.join(sub, f));
    }
  }
}

const decisionsDir = path.join(REPO, "docs", "decisions");
const decisionFiles = fs
  .readdirSync(decisionsDir)
  .filter((f) => f.endsWith(".md"))
  .sort();

const generatedTsDir = path.join(REPO, "packages", "dclutch-sdk", "lib", "generated");
const tsModules = fs
  .readdirSync(generatedTsDir)
  .filter((f) => f.endsWith(".ts"))
  .sort();


// -------------------------------------------------- route execution status

// A binding is an authored claim that a route was intended to be driven. It is
// useful campaign metadata, but is not checked native evidence: the durable
// ledger produced by `census observe` is the thing that carries the signature,
// slot, program identity, instruction bytes and admitted outcome.
const bindingEvidence = new Map(); // route id -> [{campaign, outcome, file}]
const refusalClaimEvidence = new Map(); // refusal id -> binding claims
let uncreditedRefusalClaims = 0;
// binding route refs that match no inventory route id
const unknownRefs = [];

const inventoryRouteIds = new Set();
for (const p of programs) for (const r of p.routes) inventoryRouteIds.add(r.id);

for (const file of bindingsFiles) {
  const rel = path.relative(REPO, file);
  const data = readJSON(file);
  for (const b of data.bindings ?? []) {
    for (const ref of b.routes ?? []) {
      if (!inventoryRouteIds.has(ref)) {
        unknownRefs.push({ ref, file: rel, label: b.label });
        continue;
      }
      if (!bindingEvidence.has(ref)) bindingEvidence.set(ref, []);
      bindingEvidence.get(ref).push({
        campaign: data.campaign ?? rel,
        outcome: b.outcome ?? "?",
        file: rel,
      });
    }
    if (b.outcome === "refused") {
      if (b.refusal) {
        if (!refusalClaimEvidence.has(b.refusal)) refusalClaimEvidence.set(b.refusal, []);
        refusalClaimEvidence.get(b.refusal).push({
          campaign: data.campaign ?? rel,
          file: rel,
        });
      } else if (b.unnamed_refusal) {
        uncreditedRefusalClaims += 1;
      }
    }
  }
}

// ----------------------------------------------- the substrate of a binding

// Bindings retain the substrate claimed by their campaign without promoting
// that claim to execution evidence. `tools/gauntlet/substrates.json` records
// it, one row per campaign, and this is where the runner control is checked.
const substratesFile = path.join(gauntletDir, "substrates.json");
const substrates = readJSON(substratesFile);
const substrateFor = new Map();
for (const row of substrates.campaigns) {
  substrateFor.set(row.campaign, row);
}

{
  const problems = [];
  const declared = new Set(substrateFor.keys());
  const bound = new Set();
  for (const file of bindingsFiles) {
    bound.add(readJSON(file).campaign ?? path.relative(REPO, file));
  }
  for (const campaign of [...bound].sort()) {
    if (!declared.has(campaign)) {
      problems.push(
        `campaign \`${campaign}\` binds routes but has no row in tools/gauntlet/substrates.json. ` +
          `Add one naming its substrate (${Object.keys(SUBSTRATE_RANK).join(" | ")}), its runner and its producer.`,
      );
    }
  }
  for (const campaign of [...declared].sort()) {
    const row = substrateFor.get(campaign);
    if (!bound.has(campaign)) {
      problems.push(
        `tools/gauntlet/substrates.json declares \`${campaign}\`, which binds no route in any bindings.json. ` +
          `A stale row looks exactly like a live one from the register.`,
      );
    }
    if (!(row.substrate in SUBSTRATE_RANK) || row.substrate === "none") {
      problems.push(`\`${campaign}\`: substrate \`${row.substrate}\` is not one of the declared classes`);
    }
    if (row.reproducible !== true && typeof row.reproducible !== "string") {
      problems.push(
        `\`${campaign}\`: \`reproducible\` must be true or a sentence saying what stops the ` +
          `campaign completing. A campaign that no longer runs has to have somewhere to say so.`,
      );
    }
    for (const key of ["runner", "producer"]) {
      const rel = row[key];
      if (rel !== null && !fs.existsSync(path.join(REPO, rel))) {
        problems.push(`\`${campaign}\`: ${key} \`${rel}\` does not exist`);
      }
    }
    // The positive control. A campaign that says `local-validator` must reach
    // one; a campaign that says `program-test` must not. Without this the
    // substrate column is one more authored sentence, and an authored sentence
    // is the thing this page exists to stop being the only evidence.
    //
    // It used to be `runner.includes("solana-test-validator")` over the raw
    // file, and `tools/gauntlet/lineage/run-lineage.sh` passed it on a COMMENT
    // — a control that could not fail for the reason it exists. It now strips
    // shell comments and follows the scripts the runner invokes one level down,
    // which is where that campaign's validator actually lives. See
    // tools/genref/substrate-control.mjs for what it does and does not claim.
    if (row.runner) {
      const control = launchesLocalValidator(REPO, row.runner);
      if (row.substrate === "local-validator" && !control.launches) {
        problems.push(
          `\`${campaign}\`: declared local-validator, but no executable text in ` +
            `${control.searched.join(", ")} names ${VALIDATOR_TOKEN} ` +
            `(comments do not count, and only scripts the runner invokes are followed)`,
        );
      }
      if (row.substrate === "program-test" && control.launches) {
        problems.push(
          `\`${campaign}\`: declared program-test, but ${control.sites.join(", ")} ` +
            `names ${VALIDATOR_TOKEN} in executable text`,
        );
      }
    }
  }
  if (problems.length > 0) {
    for (const problem of problems) console.error(`genref: ${problem}`);
    console.error(
      "genref: tools/gauntlet/substrates.json does not describe this tree's campaigns.",
    );
    process.exit(1);
  }
}

for (const entries of bindingEvidence.values()) {
  for (const entry of entries) {
    entry.substrate = substrateFor.get(entry.campaign).substrate;
  }
}

// ------------------------------------------------------- devnet witnesses

// The one evidence class the register had no channel for. A cohort's devnet
// transactions live in prose evidence documents in five textual shapes, with
// sixteen signatures elided to `X...Y` and no census route id anywhere, so a
// route driven on a public chain for three cohorts running read as
// NEVER-EXECUTED. `docs/evidence/witnesses/*.json` is the channel; every
// chain-derived field in it is written by
// tools/gauntlet/devnet-witness/corroborate.py from devnet's own reply, and a
// claimed route whose program the chain does not show invoked is dropped there
// rather than credited here.
const witnessDir = path.join(REPO, "docs", "evidence", "witnesses");
const nativeEvidence = new Map(); // route id -> checked native observations
const refusalEvidence = new Map(); // refusal id -> checked native observations
const devnetWitness = new Map(); // accepted route id -> finalized devnet records
const devnetDocuments = [];
if (fs.existsSync(witnessDir)) {
  for (const name of fs.readdirSync(witnessDir).sort()) {
    if (!name.endsWith(".json")) continue;
    const file = path.join(witnessDir, name);
    const document = readJSON(file);
    const rel = path.relative(REPO, file);
    if (
      document.schema !== "dclutch-devnet-route-witness-v1" ||
      document.cluster !== "devnet"
    ) {
      throw new Error(`${rel}: not a corroborated devnet witness document`);
    }
    devnetDocuments.push({
      file: rel,
      sha256: sha256(file),
      cohort: document.cohort,
      cluster: document.cluster,
      records: document.records,
    });
    for (const record of document.records ?? []) {
      if (record.outcome !== "executed" && record.outcome !== "refused") {
        throw new Error(`${rel}: devnet record ${record.stage} has no exact outcome`);
      }
      if (
        typeof record.signature !== "string" ||
        record.signature.length === 0 ||
        !Number.isFinite(record.slot) ||
        !Array.isArray(record.programs_invoked) ||
        record.programs_invoked.length === 0
      ) {
        throw new Error(`${rel}: devnet record ${record.stage} lacks finalized provenance`);
      }
      for (const route of record.routes_corroborated ?? []) {
        if (!inventoryRouteIds.has(route)) continue;
        const observation = {
          substrate: "devnet",
          outcome: record.outcome,
          campaign: `cohort-${document.cohort}`,
          cohort: document.cohort,
          stage: record.stage,
          magic: record.magic,
          signature: record.signature,
          slot: record.slot,
          file: rel,
        };
        if (!nativeEvidence.has(route)) nativeEvidence.set(route, []);
        nativeEvidence.get(route).push(observation);
        if (record.outcome === "executed") {
          if (!devnetWitness.has(route)) devnetWitness.set(route, []);
          devnetWitness.get(route).push(observation);
        }
      }
    }
  }
}

// Checked-in local and ProgramTest ledgers are explicit inputs. Discovery by
// filename would let any convenient JSON silently become evidence; the
// manifest is the review boundary and every observation still has to carry the
// census ledger schema and finalized-instruction evidence level.
const executionEvidenceFile = path.join(gauntletDir, "execution-evidence.json");
const executionEvidence = readJSON(executionEvidenceFile);
if (executionEvidence.schema !== "dclutch-route-execution-evidence-manifest-v1") {
  throw new Error("tools/gauntlet/execution-evidence.json has an unknown schema");
}
const exactLedgerDocuments = [];
const exactLedgerPaths = new Set();
for (const declared of executionEvidence.ledgers ?? []) {
  if (!(declared.substrate in SUBSTRATE_RANK) || declared.substrate === "none") {
    throw new Error(`${declared.path}: exact ledger has unknown substrate ${declared.substrate}`);
  }
  if (exactLedgerPaths.has(declared.path)) {
    throw new Error(`${declared.path}: exact ledger is declared twice`);
  }
  if (typeof declared.source_relation !== "string" || declared.source_relation.length === 0) {
    throw new Error(`${declared.path}: exact ledger must name its source relation`);
  }
  exactLedgerPaths.add(declared.path);
  const file = path.resolve(REPO, declared.path);
  if (path.relative(REPO, file).startsWith("..") || !fs.existsSync(file)) {
    throw new Error(`${declared.path}: exact ledger path is absent or outside the repository`);
  }
  const ledger = readJSON(file);
  if (ledger.schema !== "dclutch-gauntlet-execution-ledger-v1") {
    throw new Error(`${declared.path}: not a dclutch-route-census execution ledger`);
  }
  exactLedgerDocuments.push({ ...declared, sha256: sha256(file), ledger });
  for (const observation of ledger.observations ?? []) {
    if (!inventoryRouteIds.has(observation.route)) {
      throw new Error(`${declared.path}: observation names unknown route ${observation.route}`);
    }
    if (observation.evidence_level !== "finalized-instruction") {
      throw new Error(`${declared.path}: ${observation.route} is not finalized-instruction evidence`);
    }
    if (observation.outcome !== "executed" && observation.outcome !== "refused") {
      throw new Error(`${declared.path}: ${observation.route} has no exact outcome`);
    }
    if (
      typeof observation.campaign !== "string" ||
      observation.campaign.length === 0 ||
      typeof observation.signature !== "string" ||
      observation.signature.length === 0 ||
      !Number.isFinite(observation.slot) ||
      !Array.isArray(observation.programs_invoked) ||
      observation.programs_invoked.length === 0 ||
      !/^[0-9a-f]{64}$/.test(observation.evidence_sha256 ?? "") ||
      typeof observation.evidence_path !== "string" ||
      observation.evidence_path.length === 0
    ) {
      throw new Error(`${declared.path}: ${observation.route} lacks admitted native provenance`);
    }
    const entry = {
      ...observation,
      substrate: declared.substrate,
      source_relation: declared.source_relation,
      file: declared.path,
    };
    if (!nativeEvidence.has(observation.route)) nativeEvidence.set(observation.route, []);
    nativeEvidence.get(observation.route).push(entry);
    if (observation.refusal) {
      if (!refusalEvidence.has(observation.refusal)) refusalEvidence.set(observation.refusal, []);
      refusalEvidence.get(observation.refusal).push(entry);
    }
  }
}

// blocked.json: most specific matching rule wins; trailing '*' is a prefix
// glob (the file's own stated rules).
const blockedRules = blocked.blocked.map((b) => ({
  route: b.route,
  reason: b.reason,
  class: b.class,
}));
function blockedRuleFor(routeId) {
  let best = null;
  for (const rule of blockedRules) {
    if (rule.route.endsWith("*")) {
      const prefix = rule.route.slice(0, -1);
      if (routeId.startsWith(prefix)) {
        if (!best || rule.route.length > best.route.length) best = rule;
      }
    } else if (rule.route === routeId) {
      return rule; // exact always wins
    }
  }
  return best;
}

function firstSentence(s) {
  const m = s.match(/^(.*?\.)(\s|$)/s);
  return (m ? m[1] : s).replaceAll("\n", " ");
}

// ------------------------------------------------- one classifier, one tally

// Every `blocked.json` entry declares which KIND of block it is, and the
// taxonomy is closed here rather than left to a reader's judgement. An entry
// with no `class` fails this generator instead of being counted as whatever is
// convenient.
const BLOCK_CLASSES = new Map([
  ["out-of-release-set", "no tier deploys the program at all"],
  ["structural", "genuinely undrivable at HEAD, and the entry argues why"],
  ["repointing", "not a block: the entry redirects a reader, or records one already discharged"],
  ["unwired", "the route IS driven today and emits no census evidence -- a wiring gap"],
  ["status-report", "no campaign or tier drives it yet, and nothing structural is in the way"],
]);
{
  const bad = blocked.blocked.filter((b) => !BLOCK_CLASSES.has(b.class));
  if (bad.length > 0) {
    console.error(
      "genref: tools/gauntlet/blocked.json entries with no known `class`:\n" +
        bad.map((b) => `  ${b.route}: ${JSON.stringify(b.class)}`).join("\n") +
        "\n  known classes: " + [...BLOCK_CLASSES.keys()].join(", "),
    );
    process.exit(1);
  }
}

// ONE AUTHOR for the distinction that matters: accepted checked native
// evidence, an exact refusal, and an authored binding claim are different
// facts. Both generated route pages and the README consume this classification.
function classifyRoute(routeId) {
  return classifyRouteEvidence({
    bindings: bindingEvidence.get(routeId) ?? [],
    native: nativeEvidence.get(routeId) ?? [],
    rule: blockedRuleFor(routeId),
  });
}
const routeClass = new Map(
  [...inventoryRouteIds].map((id) => [id, classifyRoute(id)]),
);

const tally = {
  routes: inventoryRouteIds.size,
  "accepted-agave": 0,
  "accepted-program-test": 0,
  "refused-only": 0,
  "success-claim": 0,
  "refusal-claim": 0,
  blocked: 0,
  unrecorded: 0,
  noSuccessfulClaim: 0,
};
for (const held of routeClass.values()) {
  tally[held.kind] += 1;
  if (held.acceptedNative.length === 0 && held.successfulClaims.length === 0) {
    tally.noSuccessfulClaim += 1;
  }
}

const acceptedBySubstrate = {
  "local-validator": new Set(),
  devnet: new Set(),
  "program-test": new Set(),
};
for (const [route, entries] of nativeEvidence) {
  for (const entry of entries) {
    if (entry.outcome === "executed") acceptedBySubstrate[entry.substrate]?.add(route);
  }
}

const COVERAGE_FORMULAS = `- **historical accepted Agave union: ${tally["accepted-agave"]} of ${tally.routes}** -- an
  \`executed\` finalized native observation in a checked census ledger or an
  \`executed\` corroborated devnet record. A binding cannot enter this set, and
  this count is not final-source acceptance.
- **historical local-validator accepted: ${acceptedBySubstrate["local-validator"].size} of ${tally.routes}** --
  checked successful local-validator ledger rows.
- **historical devnet accepted: ${acceptedBySubstrate.devnet.size} of ${tally.routes}** --
  checked successful devnet records. The local and devnet sets can overlap, so
  their counts do not add to the union.
- **successful-binding-only: ${tally["success-claim"]} of ${tally.routes}** -- at
  least one campaign binding says \`executed\`, but no checked native observation
  in the repository does. Its declared substrate is useful provenance, not an
  acceptance result.
- **checked refused-only: ${tally["refused-only"]} of ${tally.routes}** -- a
  finalized native refusal with no accepted native evidence. It proves a
  boundary was reached; it never proves the accepted poststate.
- **refusal-binding-only: ${tally["refusal-claim"]} of ${tally.routes}** -- an
  authored refusal binding with no checked native row. It is a claim, not an
  observed refusal.
- **no historical successful claim: ${tally.noSuccessfulClaim} of ${tally.routes}** --
  no accepted native observation and no \`executed\` binding. This includes exact
  refusals, refusal claims, blocked rows and wholly unrecorded rows.

\`tools/gauntlet/blocked.json\` has ${blocked.blocked.length} entries and classifies
${tally.blocked} otherwise unclaimed routes. Writing a blocker can move a route
between blocked and unrecorded; it cannot change any acceptance count.`;

function routeStatus(routeId) {
  const held = routeClass.get(routeId) ?? classifyRoute(routeId);
  const native = (entries) =>
    [...new Set(entries.map((e) => `${e.substrate} ${e.campaign} slot ${num(e.slot)}`))]
      .sort()
      .join("; ");
  const claims = (entries) =>
    [...new Set(entries.map((e) => `${e.substrate} ${e.campaign}`))].sort().join("; ");
  if (held.kind === "accepted-agave") {
    return {
      kind: held.kind,
      text: `ACCEPTED-AGAVE-HISTORICAL (${native(held.acceptedNative.filter((e) => e.substrate !== "program-test"))})`,
    };
  }
  if (held.kind === "accepted-program-test") {
    return { kind: held.kind, text: `PROGRAMTEST-ACCEPTED (${native(held.acceptedNative)})` };
  }
  if (held.kind === "refused-only") {
    const claimed = held.successfulClaims.length > 0
      ? `; successful binding claim: ${claims(held.successfulClaims)}`
      : "";
    return { kind: held.kind, text: `REFUSED-ONLY (${native(held.refusedNative)}${claimed})` };
  }
  if (held.kind === "success-claim") {
    return {
      kind: held.kind,
      text: `SUCCESS-CLAIM-ONLY (${claims(held.successfulClaims)}; no checked native ledger row)`,
    };
  }
  if (held.kind === "refusal-claim") {
    return {
      kind: held.kind,
      text: `REFUSAL-CLAIM-ONLY (${claims(held.refusalClaims)}; no checked native ledger row)`,
    };
  }
  if (held.kind === "blocked") {
    return {
      kind: "blocked",
      text: `blocked by rule \`${held.rule.route}\` (${held.rule.class}): ${firstSentence(held.rule.reason)}`,
    };
  }
  return { kind: "unrecorded", text: "UNRECORDED, no evidence, binding or stated reason" };
}

// ------------------------------------------------------ refusal band table

// From the census inventory, which reads the registry crate's generated table:
// one author for the allocation, shared with the client route-census mirrors.
// (This used to regex `lib.rs` for constants that moved to `generated_bands.rs`
// on 2026-09-02, and shipped an empty table until 2026-09-04.)
if (!Array.isArray(inventory.bands) || inventory.bands.length === 0) {
  throw new Error("the census inventory carries no bands; rebuild it (tools/gate census)");
}
const bandShift = Math.log2(inventory.bands[0].span);
const bandRows = inventory.bands
  .map((b) => ({
    base: b.base,
    band: b.base >> bandShift,
    doc: `Band ${b.base >> bandShift} -- \`${b.package}\` (${b.label}${
      b.tier === "test-caller" ? ", test caller" : ""
    })`,
  }))
  .sort((a, b) => a.base - b.base);

// ------------------------------------------------------------ ABI modules

// Parse one machine-emitted TS module into typed constants. Anything the
// parser does not recognize is carried verbatim into an "unrendered" bucket
// rather than dropped: the reference must not silently narrow its source.
function parseTsModule(name) {
  const text = read(path.join(generatedTsDir, name));
  const headerLines = [];
  for (const line of text.split("\n")) {
    if (line.startsWith("//")) headerLines.push(line.replace(/^\/\/ ?/, ""));
    else if (line.trim() === "") continue;
    else break;
  }
  // Split into export statements (statements may span lines).
  const statements = [];
  const re = /^export /gm;
  const starts = [];
  let m;
  while ((m = re.exec(text)) !== null) starts.push(m.index);
  for (let i = 0; i < starts.length; i++) {
    const end = i + 1 < starts.length ? starts[i + 1] : text.length;
    statements.push(text.slice(starts[i], end).trim());
  }

  const numbers = [];
  const byteArrays = [];
  const strings = [];
  const frozen = [];
  const functions = [];
  const unrendered = [];

  for (const stmt of statements) {
    let mm;
    if (
      (mm = stmt.match(/^export const ([A-Za-z0-9_]+) = (-?\d+) as const;$/))
    ) {
      numbers.push({ name: mm[1], value: Number(mm[2]) });
    } else if (
      (mm = stmt.match(
        /^export const ([A-Za-z0-9_]+) = Uint8Array\.from\(\[([\s\S]*?)\]\);$/,
      ))
    ) {
      const bytes = mm[2]
        .split(",")
        .map((s) => s.trim())
        .filter((s) => s.length > 0)
        .map((s) => Number(s));
      byteArrays.push({ name: mm[1], bytes });
    } else if (
      (mm = stmt.match(
        /^export const ([A-Za-z0-9_]+) = new TextEncoder\(\)\.encode\('([^']*)'\);$/,
      ))
    ) {
      strings.push({ name: mm[1], value: mm[2] });
    } else if (
      (mm = stmt.match(
        /^export const ([A-Za-z0-9_]+) = '([^']*)' as const;$/,
      ))
    ) {
      strings.push({ name: mm[1], value: mm[2] });
    } else if (
      (mm = stmt.match(
        /^export const ([A-Za-z0-9_]+) = Object\.freeze\(([\s\S]*?)\) as [\s\S]*?;$/,
      ))
    ) {
      let value = null;
      try {
        value = JSON.parse(mm[2]);
      } catch {
        unrendered.push(stmt);
        continue;
      }
      frozen.push({ name: mm[1], value });
    } else if ((mm = stmt.match(/^export function ([A-Za-z0-9_]+)/))) {
      functions.push({ name: mm[1] });
    } else {
      unrendered.push(stmt);
    }
  }

  return {
    file: name,
    header: headerLines,
    numbers,
    byteArrays,
    strings,
    frozen,
    functions,
    unrendered,
  };
}

const abiModules = tsModules.map(parseTsModule);

// ------------------------------------------------------------------ pages

const pages = new Map(); // relpath -> content

// ---- README.md (index + connective narrative)

{
  const rows = programs.map((p) => [
    `\`${p.label}\``,
    `\`${p.package}\``,
    p.routes.filter((r) => r.kind === "entry").length,
    p.routes.filter((r) => r.kind !== "entry").length,
    p.refusals.length,
  ]);
  const totalRoutes = programs.reduce((n, p) => n + p.routes.length, 0);
  const totalRefusals = programs.reduce((n, p) => n + p.refusals.length, 0);
  // The same classification routes.md and route-witnesses.md print. Only the
  // checked native set is called accepted here; bindings have their own count.
  const acceptedAgave = tally["accepted-agave"];
  const successfulClaims = tally["success-claim"];
  const exactRefusals = tally["refused-only"];
  const refusalClaims = tally["refusal-claim"];
  // A hand-written sentence about the chain is a fact with two authors under a
  // "DO NOT EDIT" header, and `--check --converge` reaches a fixpoint on it
  // forever. This one said "the seven dClutch programs are deployed on Solana
  // devnet" five lines under a derived "8 programs" and was never re-derived.
  // Derive what the register can actually see: which programs a finalized
  // devnet transaction has corroborated a route of.
  const onDevnet = programs.filter((p) =>
    p.routes.some((r) => (devnetWitness.get(r.id) ?? []).length > 0),
  );
  const offDevnet = programs.filter((p) => !onDevnet.includes(p));
  const labelList = (ps) =>
    ps.map((p) => `\`${p.label}\``).join(", ").replace(/, ([^,]*)$/, ps.length > 2 ? ", and $1" : " and $1");

  pages.set(
    "README.md",
    generatedHeader([
      "census inventory",
      "tools/gauntlet/blocked.json",
      "tools/gauntlet/*/bindings",
      "tools/gauntlet/execution-evidence.json",
      "checked census ledgers",
      "docs/evidence/witnesses/*.json",
      "tools/gauntlet/CU_BUDGETS.json",
      "crates/dclutch-refusal-registry",
      "docs/decisions",
      "packages/dclutch-sdk/lib/generated",
    ]) +
      `# dClutch protocol reference

The exact numbers behind dClutch, generated straight from the code -- so
these pages always match the source they describe. Regenerate with
\`tools/gate reference --converge\`; \`--check\` verifies the match byte for byte.

- [programs.md](programs.md) -- the on-chain programs and what each one
  does.
- [routes.md](routes.md) -- every instruction the programs accept, with exact
  accepted/refused evidence kept separate from campaign claims.
- [route-witnesses.md](route-witnesses.md) -- checked native ledgers and devnet
  records, followed by the separate campaign binding register.
- [refusals.md](refusals.md) -- every error code the protocol can return,
  with its meaning.
- [budgets.md](budgets.md) -- what the key transactions cost in compute,
  measured against Solana's per-transaction limit.
- [decisions.md](decisions.md) -- why the architecture is the way it is,
  one decision per record.
- [abi/](abi/README.md) -- byte layouts: magics, PDA seed domains, record
  widths and offsets, account tables.

Current totals: **${programs.length} programs**, **${totalRoutes} routes**
(**${acceptedAgave} in the historical accepted Agave union**,
**${successfulClaims} successful-binding-only**, **${exactRefusals} checked
refused-only**, **${refusalClaims} refusal-binding-only**), **${totalRefusals}
refusal codes**.

If you'd rather start with prose, the [guides](../guides/README.md)
explain the protocol in plain terms and link back into these tables.

${wrap(
        `${num(onDevnet.length)} of the ${programs.length} programs have at least one route corroborated by a finalized transaction on Solana devnet${
          offDevnet.length === 0
            ? ""
            : `; ${labelList(offDevnet)} ${
                offDevnet.length === 1 ? "has" : "have"
              } no devnet witness at all`
        }. Accepted evidence is a historical union of the listed observations. A source-relation label describes one ledger; it does not establish complete final-source coverage or say every program that ran is the one this tree builds today. These tables describe the checked-in protocol and its devnet and local tooling; they are not a mainnet release manifest, and devnet collateral is a test token, so there is no value at risk.`,
      )}
`,
  );
}

// ---- programs.md

{
  const rows = programs.map((p) => {
    const entry = p.entrypoints
      .map((e) => `\`${e.function}\` (${e.provenance})`)
      .join("; ");
    const bands = [
      ...new Set(p.refusals.map((r) => r.code >> 12)),
    ].sort((a, b) => a - b);
    return [
      `\`${p.label}\``,
      `\`${p.package}\``,
      bands.map((b) => "0x" + b.toString(16).toUpperCase()).join(", "),
      p.routes.filter((r) => r.kind === "entry").length,
      p.routes.filter((r) => r.kind !== "entry").length,
      p.refusals.length,
      entry,
    ];
  });
  pages.set(
    "programs.md",
    generatedHeader(["census inventory"]) +
      `# Programs

Every on-chain program in this repository, enumerated from the source under
\`programs/\`. "Entry routes" are the instructions a program dispatches on
directly (selected by magic bytes); "action routes" are the actions
reachable inside an entry route's request.

` +
      table(
        [
          "program",
          "package",
          "refusal band",
          "entry routes",
          "action routes",
          "refusal codes",
          "entrypoint",
        ],
        rows,
      ) +
      "\n",
  );
}

// ---- routes.md

// A route's admissible Market prestates, as the guard's own named constant
// declares them. The census reads the constant structurally; this renders it.
// An empty list is NOT "every phase" -- it is "no phase gate was read here" --
// and the two must not print the same, because a client that cannot tell them
// apart is the defect this column exists to close.
function phaseGate(route, program) {
  const gates = route.admissible_prestates ?? [];
  // "no constant was read here" and "there is no discriminant to read" are
  // different facts about a route, and a client that cannot tell them apart
  // keeps waiting for a phase answer that will never arrive. The census
  // declares the second per program, with its own staleness checks.
  if (gates.length === 0) {
    return program?.no_persisted_discriminant
      ? "no state machine"
      : "no phase gate";
  }
  // Every set NAMES ITS MACHINE. The whole content of a declaration is which
  // discriminant it constrains, and a Market is `Open` for the entire span in
  // which its Source moves `Primary` to `Resolved` -- so a cell that dropped
  // the machine would invite a reader to check a Source set against a Market
  // phase and publish an admission nobody declared.
  const render = (g) => {
    const body =
      g.prestates && g.prestates.length > 0
        ? g.prestates.map((s) => `${s.phase}+${s.readiness}`).join(", ")
        : g.phases.join(", ");
    return `\`${g.machine ?? "market"}: ${body}\``;
  };
  // Entries sharing an `alternative` are the branches of ONE selection, so
  // they unite; everything else is a separate gate on the same execution, so
  // it intersects. Printing them the same way makes a route that admits three
  // phases read as a route that admits none.
  const groups = new Map();
  const conjuncts = [];
  for (const gate of gates) {
    if (gate.alternative === undefined || gate.alternative === null) {
      conjuncts.push(render(gate));
      continue;
    }
    if (!groups.has(gate.alternative)) groups.set(gate.alternative, []);
    groups.get(gate.alternative).push(render(gate));
  }
  for (const members of groups.values()) {
    conjuncts.push(members.length === 1 ? members[0] : members.join(" or "));
  }
  return conjuncts.join("; ");
}

{
  const sections = [];
  const neverExecuted = [];
  let gatedRoutes = 0;
  const noMachine = programs
    .filter((p) => p.no_persisted_discriminant)
    .map(
      (p) =>
        `- \`${p.label}\`'s ${p.routes.length} routes: ` +
        `${p.no_persisted_discriminant}.`,
    )
    .join("\n");
  for (const p of programs) {
    const routes = [...p.routes].sort((a, b) => (a.id < b.id ? -1 : 1));
    const rows = routes.map((r) => {
      const sel = r.selectors
        .map((s) => {
          if (s.kind === "magic") {
            // A magic the census NAMED but could not evaluate. `4b2519c3a`
            // began resolving a predicate selector to the magic its body
            // compares, and three of Trading's do so through a constant this
            // reader cannot fold, so the row carries the name and no bytes.
            // Rendering the name is the honest cell; reading `.length` off it
            // threw, and a generator that throws takes the whole reference
            // down rather than one cell.
            if (!s.bytes) {
              return `magic \`${s.constant ?? "?"}\` (bytes unresolved)`;
            }
            const bytes = [];
            for (let i = 0; i < s.bytes.length; i += 2) {
              bytes.push(parseInt(s.bytes.slice(i, i + 2), 16));
            }
            const a = s.ascii ?? asciiBytes(bytes);
            return a ? `magic \`${a}\`` : `magic \`${s.bytes}\``;
          }
          if (s.kind === "variant") {
            const wire = s.native
              ? ` at byte ${s.native.offset} = 0x${s.native.value.toString(16).padStart(2, "0")}`
              : "";
            return `variant \`${s.path}\`${wire}`;
          }
          // Every selector carries its value under its OWN field name --
          // `constant`, `path`, `function`, `text` -- and reading only the
          // first two printed an empty pair of backticks for 50 of them:
          // all 35 predicates (`function`) and all 15 tags (`text`). The page
          // whose job is to say which bytes select which route said nothing
          // there, in a cell that looked filled in. A selector kind this
          // reader does not know now renders its KIND rather than a blank,
          // because a name is a lead and a blank is a lie.
          if (s.kind === "fallthrough") return "fallthrough";
          const value = s.constant ?? s.path ?? s.function ?? s.text ?? null;
          return value ? `${s.kind} \`${value}\`` : s.kind;
        })
        .join("; ");
      const st = routeStatus(r.id);
      if (st.kind === "unrecorded") neverExecuted.push(r.id);
      // The page prints `tally.unrecorded`; this is the same set counted a
      // second way, and a disagreement means the classifier and the renderer
      // walked different routes.

      if ((r.admissible_prestates ?? []).length > 0) gatedRoutes += 1;
      return [
        `\`${r.id}\``,
        r.kind,
        sel || "--",
        phaseGate(r, p),
        st.text,
        `\`${r.provenance}\``,
      ];
    });
    sections.push(
      `## ${p.label}\n\n` +
        table(
          ["route", "kind", "selector", "phase", "status", "provenance"],
          rows,
        ),
    );
  }
  if (neverExecuted.length !== tally.unrecorded) {
    throw new Error(
      `routes.md rendered ${neverExecuted.length} unrecorded rows; classifier counted ${tally.unrecorded}`,
    );
  }

  let unknown = "";
  if (unknownRefs.length > 0) {
    const rows = unknownRefs
      .sort((a, b) => (a.ref < b.ref ? -1 : 1))
      .map((u) => [`\`${u.ref}\``, `\`${u.file}\``, u.label]);
    unknown =
      `\n\n## Campaign records naming routes the code does not\n\n` +
      `These route names appear in a campaign's records but match no route in
the current code. Each one is stale or a gap; it is listed here so it gets
fixed rather than dropped.\n\n` +
      table(["reference", "bindings file", "binding label"], rows);
  }

  // Gates that are real, enforced, and NOT the route's own.
  //
  // One route may be the entry for several families -- Trading's
  // `process_hot_execution_v3` is the whole Hot surface -- and each family's
  // prelude declines the others by returning a non-error before it reads
  // anything. What such a prelude gates is necessary to ITS family and to no
  // other, so it cannot go in the phase column: written there it would tell
  // four General and Dealer acts they need a Series ticket nobody in their
  // execution has, which is the false READY TO PREFLIGHT the phase column
  // exists to remove, inverted. It is printed here instead, with the
  // classifier that selects it named, so a consumer may publish one only
  // against an execution it can show takes that selection.
  let selected = "";
  const selectedRows = [];
  for (const p of programs) {
    for (const r of [...p.routes].sort((a, b) => (a.id < b.id ? -1 : 1))) {
      for (const g of r.selected_prestates ?? []) {
        const body =
          g.prestates && g.prestates.length > 0
            ? g.prestates.map((s) => `${s.phase}+${s.readiness}`).join(", ")
            : g.phases.join(", ");
        selectedRows.push([
          `\`${r.id}\``,
          `\`${g.selected_by}\``,
          `\`${g.machine}: ${body}\``,
          `\`${g.provenance}\``,
        ]);
      }
    }
  }
  if (selectedRows.length > 0) {
    selected =
      `\n\n## Gates behind a selection\n\n` +
      `These sets are enforced on the route named, and they are **not** that
route's admissible prestates. The classifier column names the function that
DECLINES -- it returns \`Ok(None)\` for a request outside its family, which is
not a refusal -- so everything past it runs for one family alone. A consumer
may check one of these only against an execution it can show reaches that
classifier; against the route as a whole it states a condition three quarters
of the route's callers do not have.\n\n` +
      table(["route", "classifier", "set", "provenance"], selectedRows);
  }

  pages.set(
    "routes.md",
    generatedHeader([
      "census inventory",
      "tools/gauntlet/blocked.json",
      "tools/gauntlet/*/bindings",
      "tools/gauntlet/execution-evidence.json",
      "checked census ledgers",
      "docs/evidence/witnesses/*.json",
    ]) +
      `# Routes

Every instruction the programs accept, with its selector and evidence status.
The status vocabulary is ordered by what the repository can check:

- **ACCEPTED-AGAVE-HISTORICAL** -- an \`executed\` finalized native observation in a
  checked \`dclutch-route-census\` ledger, or an \`executed\` corroborated
  devnet record. The row names its substrate, campaign and slot. This status
  does not establish final-source acceptance; the source relation is listed in
  the checked-evidence table.
- **PROGRAMTEST-ACCEPTED** -- an accepted finalized-instruction ledger row from
  an in-process bank. It ran a real ELF, but no validator checked packet size,
  scheduling or finalization.
- **REFUSED-ONLY** -- checked native evidence reached the route and refused,
  with no accepted native observation. It proves a boundary, not an accepted
  poststate.
- **SUCCESS-CLAIM-ONLY** and **REFUSAL-CLAIM-ONLY** -- a campaign binding names
  the outcome, but no checked native ledger row in this repository corroborates
  it. The declared substrate is shown only as provenance of the claim.
- **blocked** -- no evidence or binding names the route, and
  \`tools/gauntlet/blocked.json\` records a reason, class and owner.
- **UNRECORDED** -- no evidence, binding or blocking reason exists.

Bindings remain useful as the campaign plan and historical claim register.
They cannot create an accepted or exact-refusal status. The fold that can do so
is \`dclutch-route-census observe\`; durable ledgers admitted to this reference
are listed explicitly in \`tools/gauntlet/execution-evidence.json\`. Devnet
records under \`docs/evidence/witnesses/\` carry the same executed/refused
outcome split. A refusal record is never counted as accepted execution.

## Derived coverage partitions

${COVERAGE_FORMULAS}

The **phase** column is the route's own guard, not a summary of one. It is
the named admission constant the guard checks against -- one admission type
per persisted state machine, \`MarketAdmissionV1\`,
\`SourceAdmissionV1\`, \`DealerScenarioCheckpointAdmissionV1\` and
\`DealerScenarioReservationAdmissionV1\` today -- read out of the Rust that
enforces it, so a reader is reading the conjunct the program executes.
\`market: Founding+Ready\` is an exact prestate; a bare \`market: Retiring\` is a
guard that names no readiness and so admits every one. It is a NECESSARY
condition and never a sufficient one: an act whose prestate is excluded cannot
succeed, and an act whose prestate is admitted still has every account,
release and request check ahead of it.

Each set names the STATE MACHINE it is over -- \`market: Open\` is the Core
Market's phase, \`source: Primary\` is the Source resolution state -- because a
Market is \`Open\` for the whole span in which its Source moves \`Primary\` to
\`Resolved\`, and a set checked against the wrong discriminant is an admission
nobody declared. A route may carry gates over more than one machine, and then
it passes all of them.

Two sets joined by **or** are the two branches of ONE guard written as a
selection -- \`if action == RedeemTerminal { .. } else { .. }\` -- so the route
admits their UNION. Sets separated by **;** are separate guards on the same
execution, so the route admits their INTERSECTION. A reader that treats the
first as the second reports that a route admitting three phases admits none.

**no phase gate** means no constant was read for that route -- an authoring
route with no state to consult, a guard still written inline, a guard reached
only under a boolean branch or inside a loop that may not be entered, a guard
in a crate this program's dispatch does not reach, or a route the enumerator
could not follow into. It does not mean the route admits every phase, and a
consumer that treats the two alike is repeating the defect this column was
added to close. **${gatedRoutes}** of **${inventoryRouteIds.size}** routes
carry a gate today.

**no state machine** is a DIFFERENT fact, and it is the program's own
declaration rather than an absence: this program persists no lifecycle
discriminant for any route to consult, so no amount of further naming will
ever put a set in these cells. It is carried in the census with two checks --
such a program must declare no admissible-state set, and its sources must name
no known machine's discriminant -- so a state model that grows one makes the
declaration unclassified in the same run. What those programs authenticate
instead:

${noMachine}

` +
      sections.join("\n\n") +
      unknown +
      selected +
      "\n",
  );
}

// ---- route-witnesses.md

{
  const rows = [];
  const activeBlocks = [];
  const unreproducible = [];
  const counts = {
    "accepted-agave": 0,
    "accepted-program-test": 0,
    "refused-only": 0,
    "success-claim": 0,
    "refusal-claim": 0,
    blocked: 0,
    unrecorded: 0,
  };
  const perCampaign = new Map();

  const claimText = (entries) =>
    [...new Set(entries.map((entry) => `\`${entry.campaign}\` (${entry.outcome})`))]
      .sort()
      .join(", ");
  const nativeText = (entries) =>
    [...new Set(entries.map((entry) =>
      `${entry.substrate} \`${entry.campaign}\` slot ${num(entry.slot)} ` +
      `\`${entry.signature.slice(0, 12)}...\``,
    ))].sort().join("; ");
  const artifactsFor = (entries) =>
    [...new Set(entries.map((entry) => entry.file))].sort();
  const classText = (held) => {
    if (held.kind === "accepted-agave") return `${held.substrate} accepted (historical)`;
    if (held.kind === "accepted-program-test") return "ProgramTest accepted";
    if (held.kind === "refused-only") return `${held.substrate} refused-only`;
    if (held.kind === "success-claim") return `${held.substrate} success claim`;
    if (held.kind === "refusal-claim") return `${held.substrate} refusal claim`;
    return held.kind;
  };

  for (const [route, entries] of bindingEvidence) {
    for (const entry of entries) {
      const held = perCampaign.get(entry.campaign) ?? {
        executed: new Set(),
        refused: new Set(),
      };
      if (entry.outcome === "executed") held.executed.add(route);
      else if (entry.outcome === "refused") held.refused.add(route);
      perCampaign.set(entry.campaign, held);
    }
  }

  for (const program of programs) {
    for (const route of program.routes) {
      const held = routeClass.get(route.id);
      counts[held.kind] += 1;
      let relevant = [];
      let detail = "";
      if (held.kind === "accepted-agave") {
        relevant = held.acceptedNative.filter((entry) => entry.substrate !== "program-test");
        detail = nativeText(relevant);
      } else if (held.kind === "accepted-program-test") {
        relevant = held.acceptedNative;
        detail = nativeText(relevant);
      } else if (held.kind === "refused-only") {
        relevant = held.refusedNative;
        detail = nativeText(relevant);
      } else if (held.kind === "success-claim") {
        relevant = held.successfulClaims;
        detail = `${claimText(relevant)}; no checked native ledger row`;
      } else if (held.kind === "refusal-claim") {
        relevant = held.refusalClaims;
        detail = `${claimText(relevant)}; no checked native ledger row`;
      } else if (held.kind === "blocked") {
        detail = `blocked by rule \`${held.rule.route}\``;
        relevant = [{ file: "tools/gauntlet/blocked.json" }];
      } else {
        detail = "no evidence, binding or reason recorded";
      }

      const supplementalClaims = held.bindings.filter((entry) => !relevant.includes(entry));
      if (supplementalClaims.length > 0) {
        detail += `; binding register: ${claimText(supplementalClaims)}`;
      }
      if (held.rule && (held.native.length > 0 || held.bindings.length > 0)) {
        activeBlocks.push([
          `\`${route.id}\``,
          classText(held),
          `\`${held.rule.route}\``,
          firstSentence(held.rule.reason),
        ]);
      }
      if (
        (held.kind === "success-claim" || held.kind === "refusal-claim") &&
        relevant.every((entry) => substrateFor.get(entry.campaign).reproducible !== true)
      ) {
        unreproducible.push([
          `\`${route.id}\``,
          classText(held),
          claimText(relevant),
        ]);
      }
      rows.push([
        `\`${route.id}\``,
        classText(held),
        detail,
        artifactsFor(relevant).map((file) => `\`${file}\``).join("<br>") || "--",
      ]);
    }
  }

  const classified = Object.values(counts).reduce((sum, count) => sum + count, 0);
  if (
    classified !== tally.routes ||
    counts["accepted-agave"] !== tally["accepted-agave"] ||
    counts["accepted-program-test"] !== tally["accepted-program-test"] ||
    counts["refused-only"] !== tally["refused-only"] ||
    counts["success-claim"] !== tally["success-claim"] ||
    counts["refusal-claim"] !== tally["refusal-claim"] ||
    counts.blocked !== tally.blocked ||
    counts.unrecorded !== tally.unrecorded
  ) {
    throw new Error("routes.md and route-witnesses.md evidence partitions disagree");
  }

  const bindingRows = bindingsFiles.map((file) => {
    const rel = path.relative(REPO, file);
    const data = readJSON(file);
    const campaign = data.campaign ?? rel;
    const row = substrateFor.get(campaign);
    const held = perCampaign.get(campaign) ?? { executed: new Set(), refused: new Set() };
    return [
      `\`${campaign}\``,
      row.substrate,
      row.reproducible === true ? "yes" : "**NO**",
      num(held.executed.size),
      num(held.refused.size),
      row.runner ? `\`${row.runner}\`` : "**none** -- driven by hand",
      `\`${rel}\` / \`${sha256(file).slice(0, 16)}\``,
    ];
  });
  const ledgerRows = exactLedgerDocuments.map((document) => {
    const executed = new Set();
    const refused = new Set();
    for (const observation of document.ledger.observations ?? []) {
      (observation.outcome === "executed" ? executed : refused).add(observation.route);
    }
    return [
      `\`${document.path}\``,
      document.substrate,
      document.source_relation,
      num(executed.size),
      num(refused.size),
      `\`${document.sha256.slice(0, 16)}\``,
    ];
  });
  const devnetRows = devnetDocuments.map((document) => {
    const executed = new Set();
    const refused = new Set();
    for (const record of document.records ?? []) {
      const into = record.outcome === "executed" ? executed : refused;
      for (const route of record.routes_corroborated ?? []) {
        if (inventoryRouteIds.has(route)) into.add(route);
      }
    }
    return [
      `cohort ${document.cohort}`,
      document.cluster,
      num(executed.size),
      num(refused.size),
      `\`${document.file}\` / \`${document.sha256.slice(0, 16)}\``,
    ];
  });

  pages.set(
    "route-witnesses.md",
    generatedHeader([
      "census inventory",
      "tools/gauntlet/execution-evidence.json",
      "checked census ledgers",
      "docs/evidence/witnesses/*.json",
      "tools/gauntlet/substrates.json",
      "tools/gauntlet/*/bindings",
      "tools/gauntlet/blocked.json",
    ]) +
      `# Route evidence and binding claims

This page keeps checked execution evidence separate from the campaign binding
register. A binding names what a campaign claims it drove. Only an
\`executed\` finalized-instruction row admitted by \`dclutch-route-census\`, or
an \`executed\` corroborated devnet record, establishes historical accepted
Agave route execution. It is not final-source coverage. A refused transaction
remains refused even when its binding names a local validator, and ProgramTest
remains a separate substrate.

| partition | routes | authority |
| --- | ---: | --- |
| **historical accepted Agave** | **${num(counts["accepted-agave"])}** | checked native local-validator ledgers and successful devnet records; not final-source coverage |
| **checked ProgramTest accepted** | ${num(counts["accepted-program-test"])} | checked native ProgramTest ledgers; no validator claim |
| **successful binding only** | ${num(counts["success-claim"])} | authored \`executed\` bindings without a checked native row |
| **checked refused-only** | ${num(counts["refused-only"])} | finalized native refusal and no native acceptance |
| **refusal binding only** | ${num(counts["refusal-claim"])} | authored \`refused\` binding without a checked native row |
| **blocked** | ${num(counts.blocked)} | no evidence or binding; a blocker records why and who owns it |
| **unrecorded** | ${num(counts.unrecorded)} | no evidence, binding or reason |

${COVERAGE_FORMULAS}

## Checked native evidence sources

These ledger paths are an explicit manifest, not filename discovery. Adding a
new immutable ledger automatically changes the derived route counts; historical
totals are never edited by hand.

${ledgerRows.length > 0
  ? table(["ledger", "substrate", "source relation", "accepted routes", "refused routes", "sha256"], ledgerRows)
  : "*No checked census ledger is declared.*"}

Existing devnet witness files are also exact native evidence, split by their
recorded outcome:

${devnetRows.length > 0
  ? table(["source", "cluster", "accepted routes", "refused routes", "artifact / sha256"], devnetRows)
  : "*No devnet witness file is present.*"}

## Campaign binding register

This table preserves every campaign declaration and its substrate. Its route
columns are binding claims, not accepted-evidence counts. \`reproduces\` is an
authored current status and is checked separately from transaction evidence.

${table(
  ["campaign", "substrate", "reproduces", "executed claims", "refused claims", "runner", "binding / sha256"],
  bindingRows,
  [null, null, null, "r", "r", null, null],
)}

## Binding-only routes whose campaign does not reproduce

${unreproducible.length > 0
  ? table(["route", "claim class", "campaign claim(s)"], unreproducible)
  : "*None: every binding-only route has at least one campaign declared reproducible.*"}

## Blocking entries beside recorded activity

A blocker beside exact evidence or a binding claim needs review. The activity
may falsify it, or a refusal/claim may leave its reason intact; this table does
not decide which.

${activeBlocks.length > 0
  ? table(["route", "evidence class", "blocking rule", "reason, first sentence"], activeBlocks)
  : "*None.*"}

## Every route

${table(["route", "class", "evidence or claim", "artifact"], rows)}
`,
  );
}


// ---- refusals.md

{
  const bandTable = table(
    ["base", "band", "allocation"],
    bandRows.map((b) => [
      `\`${codeHex(b.base)}\``,
      "0x" + b.band.toString(16).toUpperCase(),
      b.doc,
    ]),
  );

  const observedCell = (id) => {
    const ev = refusalEvidence.get(id);
    if (!ev) return "--";
    return [...new Set(ev.map((e) => `${e.campaign} slot ${num(e.slot)}`))].sort().join("; ");
  };
  const claimedCell = (id) => {
    const ev = refusalClaimEvidence.get(id);
    if (!ev) return "--";
    return [...new Set(ev.map((e) => e.campaign))].sort().join("; ");
  };

  const sections = programs.map((p) => {
    const refusals = [...p.refusals].sort((a, b) => a.code - b.code);
    const rows = refusals.map((r) => [
      `\`${codeHex(r.code)}\``,
      `\`${r.enum_name}::${r.variant}\``,
      r.summary || "(no doc comment)",
      observedCell(r.id),
      claimedCell(r.id),
      `\`${r.provenance}\``,
    ]);
    return (
      `## ${p.label}\n\n` +
      table(["code", "refusal", "meaning", "checked firing", "binding claim", "provenance"], rows)
    );
  });

  const totalRefusals = programs.reduce((n, p) => n + p.refusals.length, 0);
  const inventoryRefusalIds = new Set();
  for (const p of programs) for (const r of p.refusals) inventoryRefusalIds.add(r.id);
  const observedIds = [...refusalEvidence.keys()].filter((id) =>
    inventoryRefusalIds.has(id),
  );
  const observedCount = observedIds.length;
  const observingCampaigns = [
    ...new Set(
      [...refusalEvidence.values()].flat().map((e) => e.campaign),
    ),
  ].sort();
  const claimedIds = [...refusalClaimEvidence.keys()].filter((id) =>
    inventoryRefusalIds.has(id),
  );
  const claimedCount = claimedIds.length;
  const claimingCampaigns = [
    ...new Set(
      [...refusalClaimEvidence.values()].flat().map((entry) => entry.campaign),
    ),
  ].sort();

  pages.set(
    "refusals.md",
    generatedHeader([
      "census inventory",
      "crates/dclutch-refusal-registry (bands, via the census inventory)",
      "tools/gauntlet/execution-evidence.json",
      "checked census ledgers",
      "tools/gauntlet/*/bindings",
    ]) +
      `# Refusal codes

Every error code the protocol can return, with its meaning. When dClutch
refuses a transaction, the whole transaction rolls back -- no partial
effect survives -- and the code says exactly which program refused and why.
A refusal isn't a malfunction; it's the protocol keeping the rules.

Reading a code: each program owns its own block ("band") of codes, and
\`band = code >> 12\` -- drop the last three hex digits to get the band. So
\`custom program error: 0x5180\` is band 5, which is Claims. Band 0 is
never used, meaning a code below \`0x1000\` came from some other program in
your transaction, not from dClutch. Bands at \`0x100000\` and above belong
to test-only programs that are never deployed.

The tables below carry all **${totalRefusals}** codes, with meanings taken
from the source code's own documentation.

## Checked firings and binding claims

**${observedCount} of ${totalRefusals}** codes have a checked firing in a durable
census ledger. The \`checked firing\` column names the campaign and slot from an
observation that \`census observe\` admitted using the finalized log's exact
custom code and the program address that raised it.

A separate **${claimedCount} of ${totalRefusals}** codes appear in authored
refusal bindings. The \`binding claim\` column preserves those campaign claims
without calling them observed. A binding can be written before its evidence is
folded or survive after a run artifact disappears; it never promotes itself
into the checked column.

${
    uncreditedRefusalClaims === 0
      ? "No binding currently carries an uncredited refusal claim."
      : `A further ${uncreditedRefusalClaims} binding${uncreditedRefusalClaims === 1 ? "" : "s"}
record${uncreditedRefusalClaims === 1 ? "s" : ""} an uncredited refusal claim.
Without a checked ledger row, this page does not say which program or code
actually refused.`
  }

**And the denominator is the narrower of two.** These tables carry the
${totalRefusals} codes belonging to the programs the route census enumerates.
The tree as a whole declares more -- the census reports its own, larger figure
across every package it indexes -- and the difference is codes in packages that
have no enumerated program, so no campaign could observe them through a route.

${
    observedCount === 0
      ? "No checked ledger in the manifest currently carries a named refusal firing."
      : `The ${observingCampaigns.length} checked campaigns contributing:
${observingCampaigns.map((c) => `\`${c}\``).join(", ")}.`
  }

${
    claimedCount === 0
      ? "No campaign binding currently names a refusal code."
      : `The ${claimingCampaigns.length} campaigns contributing binding claims:
${claimingCampaigns.map((c) => `\`${c}\``).join(", ")}.`
  }

## Band allocation

${bandTable}

` +
      sections.join("\n\n") +
      "\n",
  );
}

// ---- budgets.md

{
  const budgets = budgetsFile.budgets;
  const label = (e) =>
    e.scope === "stage"
      ? `stage ${e.stage.index}: ${e.stage.name} (${e.stage.program_role})`
      : e.transaction;
  const enforced = budgets.filter((e) => e.enforced);
  const recorded = budgets.filter((e) => !e.enforced);

  const mainRows = enforced.map((e) => [
    `\`${e.id}\``,
    e.campaign,
    e.scope,
    label(e),
    num(e.measured),
    num(e.tolerance),
    num(e.budget),
  ]);
  const recRows = recorded.map((e) => [
    `\`${e.id}\``,
    e.campaign,
    e.scope,
    label(e),
    e.measured ? num(e.measured) : "--",
    firstSentence(e.unenforced_reason ?? ""),
  ]);

  const provenance = budgets
    .map((e) => `- \`${e.id}\` -- ${e.provenance.replaceAll("\n", " ")}`)
    .join("\n");

  pages.set(
    "budgets.md",
    generatedHeader(["tools/gauntlet/CU_BUDGETS.json"]) +
      `# Compute budgets for the golden transactions

What the protocol's key transactions cost, in compute units, measured from
real runs. Solana allows at most
**${num(budgetsFile.ceiling.compute_units)} CU** per transaction; a budget
above that ceiling fails this file's own checks, so a transaction that
stops fitting gets caught here, loudly.

Each budget is measured cost plus a tolerance
(\`${budgetsFile.tolerance_rule.formula}\`), where the measured value is
the highest cost seen across runs, never a single run. Changing a number?
Read \`tools/gauntlet/CU_BUDGETS.md\` first -- costs move with the accounts
in play, and it explains how much of that is noise.

## Enforced budgets

` +
      table(
        ["id", "campaign", "scope", "what", "measured", "tolerance", "budget"],
        mainRows,
        [null, null, null, null, "r", "r", "r"],
      ) +
      `

## Recorded, not enforced

` +
      table(
        ["id", "campaign", "scope", "what", "measured", "why unenforced"],
        recRows,
        [null, null, null, null, "r", null],
      ) +
      `

## Provenance

${provenance}
`,
  );
}

// ---- decisions.md

{
  const rows = [];
  for (const f of decisionFiles) {
    const text = read(path.join(decisionsDir, f));
    const lines = text.split("\n");
    const title = (lines[0] ?? "").replace(/^#\s*/, "");
    let status = "";
    for (let i = 1; i < lines.length; i++) {
      if (lines[i].startsWith("Status:")) {
        const para = [];
        for (let j = i; j < lines.length && lines[j].trim() !== ""; j++) {
          para.push(lines[j]);
        }
        status = firstSentence(
          para.join(" ").replace(/^Status:\s*/, ""),
        );
        break;
      }
    }
    rows.push([`[${title}](../decisions/${f})`, status]);
  }
  // The status marker is the first ALL-CAPS word of the status sentence, so the
  // counts below are derived from the records rather than kept by hand.
  const marker = (status) =>
    (status.replace(/^\*+/, "").match(/^[A-Z]{2,}/) || [""])[0];
  const provisionalCount = rows.filter(([, s]) => marker(s) === "PROVISIONAL")
    .length;
  const openCount = rows.filter(([, s]) => marker(s) === "OPEN").length;
  const confirmedCount = rows.filter(([, s]) => marker(s) === "CONFIRMED")
    .length;
  // Which records name the 15:50 reading as their confirming act is a fact the
  // records carry; it was hand-written here as "0024-0034 ... the five
  // pre-docket rulings (0019-0023) ... stay PROVISIONAL" and went on being
  // printed two lines above a derived "0 PROVISIONAL". Derive it.
  const CONFIRMING_ACT = "2026-09-04 15:50 EDT";
  const confirmedByAct = rows
    .filter(([, s]) => marker(s) === "CONFIRMED" && s.includes(CONFIRMING_ACT))
    .map(([t]) => Number((t.match(/\.\.\/decisions\/(\d+)-/) ?? [])[1]))
    .filter((n) => Number.isFinite(n))
    .sort((a, b) => a - b);
  // Contiguous runs render as a range; anything else lists every record, so a
  // record joining or leaving the act cannot hide inside a span.
  const spans = [];
  for (const n of confirmedByAct) {
    const last = spans[spans.length - 1];
    if (last && n === last[1] + 1) last[1] = n;
    else spans.push([n, n]);
  }
  const pad = (n) => String(n).padStart(4, "0");
  const actList = spans
    .map(([a, b]) => (a === b ? pad(a) : `${pad(a)}-${pad(b)}`))
    .join(", ");
  pages.set(
    "decisions.md",
    generatedHeader(["docs/decisions/*.md"]) +
      `# Architecture decision records

Why the protocol is built the way it is, one decision per record. Each
record carries its context, the alternatives, and the consequences; this
index shows each record's current status.

A ruling that lives only inside a narrative file has no durable home, which
is what these records are for. Every item on the 2026-09-04 rulings docket
now has one: D1 economics (0024), D2 the failure selector (0025), D3 the
privacy horizon (0018), D4 mainnet's place (0026), D5 recovery (0027), D6
the accelerator output page (0028, which carries a read as well as its
ruling, because ember asked for the architecture rather than a switch), D7
the product list (0029), and D8 rent across an epoch (0030). Records
0019-0023 hold the five rulings the orchestrator made under ember's standing
goal before that docket. Records 0031-0034 hold the mechanism agenda's
rulings, made under the same standing goal later the same day: the agenda
itself (0031), the joint clearing's three owed rulings (0032), the founder
bond's mode (0033) and the ensemble's flagship parameters (0034).

Statuses are load-bearing, and there are three live ones. **PROVISIONAL**
means the orchestrator ruled under ember's standing goal and ember has not
read it yet; it is in force, and ember may reverse it at the cost the
record's last section states. **CONFIRMED** means ember has read the ruling
and accepted it in conversation without amending it — it was not re-argued,
so nothing in the record moved, and it stays reversible on request at that
same cost. **OPEN** means nobody has ruled.

${wrap(
        `On 2026-09-04 at 15:50 EDT ember read the docket and the mechanism cohort page and found the takes *"overall reasonable"*. **${num(confirmedByAct.length)} records name that one reading as their confirming act** -- ${actList} -- and each states in its own Status paragraph what it was before it. Counted from the records below rather than kept by hand: **${confirmedCount} CONFIRMED, ${provisionalCount} PROVISIONAL, ${openCount} OPEN**; every other record is accepted, adopted, ratified or ruled.`,
      )}

The one thing still waiting on ember is not a record but an item inside one:
decision 0029's tenth item, the conditional layer's flagship child market —
its feature gate, its slot and its metric. That record is CONFIRMED for its
nine ruled items and its addendum carries the tenth as OPEN, which is why
the OPEN column above counts zero while a question is still owed.

` +
      table(["decision", "status"], rows) +
      "\n",
  );
}

// ---- abi/ pages

{
  const indexRows = [];
  for (const mod of abiModules) {
    const base = mod.file.replace(/\.ts$/, "");
    const out = `abi/${base}.md`;
    indexRows.push([
      `[${base}](${base}.md)`,
      mod.header.find((l) => l.includes("@generated"))?.replace(
        /^@generated /,
        "",
      ) ?? "",
      mod.header
        .find((l) => l.startsWith("Regenerate with:"))
        ?.replace(/^Regenerate with:\s*/, "") ?? "",
    ]);

    const parts = [];
    parts.push(
      generatedHeader([
        `packages/dclutch-sdk/lib/generated/${mod.file} (which is itself generated -- see its header below)`,
      ]),
    );
    parts.push(`# ABI: ${base}\n`);
    parts.push(
      `Source module: \`packages/dclutch-sdk/lib/generated/${mod.file}\`, whose own header reads:\n`,
    );
    parts.push("```");
    parts.push(...mod.header);
    parts.push("```\n");

    if (mod.byteArrays.length > 0) {
      const rows = mod.byteArrays.map((b) => {
        const a = asciiBytes(b.bytes);
        return [
          `\`${b.name}\``,
          b.bytes.length,
          a ? `\`${a}\`` : "--",
          `\`${hexBytes(b.bytes)}\``,
        ];
      });
      parts.push(`## Byte constants (magics, seed domains, schema identities)\n`);
      parts.push(table(["name", "len", "ascii", "bytes"], rows));
      parts.push("");
    }

    if (mod.strings.length > 0) {
      const rows = mod.strings.map((s) => [`\`${s.name}\``, `\`${s.value}\``]);
      parts.push(`## String constants\n`);
      parts.push(table(["name", "value"], rows));
      parts.push("");
    }

    if (mod.numbers.length > 0) {
      const rows = mod.numbers.map((n) => [`\`${n.name}\``, num(n.value)]);
      parts.push(`## Numeric constants (widths, offsets, counts, tags)\n`);
      parts.push(table(["name", "value"], rows, [null, "r"]));
      parts.push("");
    }

    // Pair *LABELS* arrays with their *ROLES* siblings into account tables.
    const consumed = new Set();
    for (const fz of mod.frozen) {
      if (!fz.name.includes("LABELS")) continue;
      const rolesName = fz.name.replace("LABELS", "ROLES");
      const roles = mod.frozen.find((g) => g.name === rolesName);
      if (
        roles &&
        Array.isArray(roles.value) &&
        roles.value.length === fz.value.length &&
        roles.value.every((v) => typeof v === "object" && v !== null)
      ) {
        consumed.add(fz.name);
        consumed.add(rolesName);
        const rows = fz.value.map((labelText, i) => [
          i,
          labelText,
          roles.value[i].signer ? "signer" : "",
          roles.value[i].writable ? "writable" : "",
        ]);
        parts.push(`## Account table: \`${fz.name}\` / \`${rolesName}\`\n`);
        parts.push(table(["#", "account", "signer", "writable"], rows));
        parts.push("");
      }
    }
    for (const fz of mod.frozen) {
      if (consumed.has(fz.name)) continue;
      parts.push(`## \`${fz.name}\`\n`);
      if (Array.isArray(fz.value) && fz.value.every((v) => typeof v !== "object")) {
        parts.push(
          table(
            ["#", "value"],
            fz.value.map((v, i) => [i, `\`${String(v)}\``]),
          ),
        );
      } else {
        parts.push("```json");
        parts.push(JSON.stringify(fz.value, null, 1));
        parts.push("```");
      }
      parts.push("");
    }

    if (mod.functions.length > 0) {
      parts.push(`## Functions (see the source module)\n`);
      parts.push(mod.functions.map((f) => `- \`${f.name}\``).join("\n"));
      parts.push("");
    }

    if (mod.unrendered.length > 0) {
      parts.push(`## Unrendered exports (verbatim)\n`);
      parts.push(
        "The renderer did not recognize these statement shapes, so they are\nshown verbatim rather than dropped.\n",
      );
      for (const stmt of mod.unrendered) {
        parts.push("```ts");
        parts.push(stmt);
        parts.push("```");
      }
      parts.push("");
    }

    pages.set(out, parts.join("\n"));
  }

  pages.set(
    "abi/README.md",
    generatedHeader(["packages/dclutch-sdk/lib/generated/*.ts"]) +
      `# ABI surfaces

The exact bytes the protocol speaks: instruction magics, PDA seed domains,
record widths and field offsets, and account tables -- one page per
surface.

These pages are rendered from the same generated modules the SDK, the web app and the CLI use
to decode chain data (\`packages/dclutch-sdk/lib/generated/\`). Each module is
byte-checked against the Rust or Lean source that defines its layout, and
\`npm test\` runs every check.

` +
      table(["surface", "module authority", "regenerate"], indexRows) +
      "\n",
  );
}

// ----------------------------------------------------------- write / check

function walk(dir, base = dir, acc = []) {
  if (!fs.existsSync(dir)) return acc;
  for (const e of fs.readdirSync(dir).sort()) {
    const p = path.join(dir, e);
    if (fs.statSync(p).isDirectory()) walk(p, base, acc);
    else acc.push(path.relative(base, p));
  }
  return acc;
}

const expected = new Map(
  [...pages.entries()].sort(([a], [b]) => (a < b ? -1 : 1)),
);

if (check) {
  const existing = walk(OUT_DIR);
  let failed = false;
  for (const [rel, content] of expected) {
    const p = path.join(OUT_DIR, rel);
    if (!fs.existsSync(p)) {
      console.error(`genref check: MISSING ${path.relative(REPO, p)}`);
      failed = true;
    } else if (read(p) !== content) {
      console.error(`genref check: STALE ${path.relative(REPO, p)}`);
      failed = true;
    }
  }
  for (const rel of existing) {
    if (!expected.has(rel)) {
      console.error(
        `genref check: STRAY ${path.join("docs/reference", rel)} (not produced by the generator)`,
      );
      failed = true;
    }
  }
  if (failed) {
    console.error(
      "genref check: docs/reference is not the generator's output. Regenerate with tools/gate reference --converge and commit the result.",
    );
    process.exit(1);
  }
  console.log(
    `genref check: docs/reference matches (${expected.size} files, byte-identical).`,
  );
} else {
  fs.mkdirSync(path.join(OUT_DIR, "abi"), { recursive: true });
  for (const [rel, content] of expected) {
    const p = path.join(OUT_DIR, rel);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    const tmp = p + ".genref-tmp";
    fs.writeFileSync(tmp, content);
    fs.renameSync(tmp, p);
  }
  for (const rel of walk(OUT_DIR)) {
    if (!expected.has(rel)) {
      fs.unlinkSync(path.join(OUT_DIR, rel));
      console.log(`genref: removed stray ${path.join("docs/reference", rel)}`);
    }
  }
  console.log(`genref: wrote ${expected.size} files under docs/reference/.`);
}
