#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Emit a cohort's job-directory stage scripts as ONE family, from the runbook.

Today every cohort's ~18 stage scripts are hand-written, and each one re-derives
the same preamble by copy: the job root, the driver, the endpoint, the genesis
hash, the bash-3.2 empty-array spelling, the backup-before-attempt. Measured on
cohort-15's job directory: 34 scripts naming 82 absolute paths, 23 of them into
a build scratch that a cleanup can delete and strand the cohort. That is what
`db1e4eaa6` fixed for the ONE generated script and could not fix for the rest,
because the rest have no generator.

This is the generator. Every emitted script:

  * resolves everything from `$HERE` -- the job directory is the unit, and a
    path into a build scratch is not in it. Enforced, not intended: the
    self-contained value test below refuses to leave a script naming any
    absolute path, and `test.sh` proves it red.
  * resolves the driver from `$HERE/bin` and CHECKS ITS DIGEST against the
    `.sha256` staging wrote beside it, so a swapped driver is refused rather
    than run.
  * reads the endpoint credential AT USE TIME from the environment. No file
    here holds it, and none ever prints it.
  * BACKS UP BEFORE IT ATTEMPTS. An output that exists is copied under
    `$HERE/backups/<stage>/` with the attempt's Unix time before anything
    overwrites it.
  * carries THE VERIFIER THE ROW NAMES, as the thing to check, in words. The
    exit code is not the verifier; this repository has paid for that three
    times in one day.

What the rows do NOT yet carry is each command's own flags. Rather than guess
them, an emitted script reads `$HERE/flags/<stage>.flags` -- one argument per
line, `#` comments allowed -- and REFUSES when it is absent. That keeps the
un-captured knowledge in exactly one countable place per stage instead of
spread through a hand-written script, and the count is the migration's ledger.

usage: generate-stage-scripts.py --cohort 15 --out <dir> [--delta]
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import stat
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import importlib.util

_spec = importlib.util.spec_from_file_location("check_steps", HERE / "check-steps.py")
check_steps = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(check_steps)

MARKER = "# GENERATED BY tools/cohort/generate-stage-scripts.py -- edit the runbook, not this file."
# `/dev/null` is a kernel device, not an input a job directory has to carry.
# Nothing else is exempt: a real filesystem path is exactly what strands a
# cohort when the tree that held it is deleted.
ALLOWED_ABSOLUTE = {"/dev/null"}
ABSOLUTE = re.compile(r"""(?<![\w$:/])/[A-Za-z0-9._/-]+""")
DRIVER_BINARY = "dclutch-local-successor-bootstrap"


def wrap(text: str, width: int = 74, prefix: str = "#   ") -> list[str]:
    words, lines, line = text.split(), [], ""
    for word in words:
        if line and len(line) + 1 + len(word) > width:
            lines.append(prefix + line)
            line = word
        else:
            line = f"{line} {word}".strip()
    if line:
        lines.append(prefix + line)
    return lines


PREAMBLE = """\
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd -P)"

# THE ENDPOINT CREDENTIAL IS READ AT USE TIME AND HELD BY NO FILE HERE. A keyed
# endpoint carries its credential in the query string, which is exactly why this
# file names an environment variable and never a URL.
: "${DCLUTCH_RPC_URL:?export it; this job directory deliberately does not hold it}"

STAGE=%(stage_literal)s
OUT="$HERE/$STAGE"
mkdir -p "$OUT" "$HERE/backups/$STAGE"

# BACK UP BEFORE THE ATTEMPT, never after it. An output that already exists is
# the evidence of the last attempt, and the next attempt is exactly when it
# stops being recoverable.
backup() {
    [ -e "$1" ] || return 0
    cp -Rp "$1" "$HERE/backups/$STAGE/$(basename "$1").$(date -u +%%s)"
}

# The flags this command needs, one per line. The runbook carries the row's
# command and its verifier; it does not yet carry each driver's own arguments,
# so they live in ONE file per stage rather than inside a hand-written script.
FLAGS_FILE="$HERE/flags/$STAGE.flags"
[ -f "$FLAGS_FILE" ] || { echo "$STAGE: no $FLAGS_FILE; this stage's own flags are not in the runbook yet" >&2; exit 64; }
FLAGS=()
while IFS= read -r line; do
    case "$line" in ''|'#'*) continue ;; esac
    FLAGS+=("$line")
done < "$FLAGS_FILE"
# A flags file holding only comments is the same as no flags file: it would run
# the driver with no arguments and call that a stage. (It is also a bash 3.2
# trap -- "${FLAGS[@]}" on an empty array under `set -u` is an unbound-variable
# error -- so this refusal is required twice over.)
[ "${#FLAGS[@]}" -gt 0 ] || { echo "$STAGE: $FLAGS_FILE names no flags; this stage's own flags are not in the runbook yet" >&2; exit 64; }
"""

DRIVER_BOOTSTRAP = """
# THE DRIVER IS BESIDE US AND ITS DIGEST IS CHECKED. Staging copies the built
# binary in and writes the digest next to it; a swapped driver is refused here
# rather than discovered by its output.
DRIVER="$HERE/bin/%(binary)s"
[ -x "$DRIVER" ] || { echo "$STAGE: no driver at bin/%(binary)s; the job directory carries its own" >&2; exit 2; }
if [ -f "$DRIVER.sha256" ]; then
    OBSERVED="$(shasum -a 256 "$DRIVER" | awk '{print $1}')"
    DECLARED="$(cat "$DRIVER.sha256")"
    [ "$OBSERVED" = "$DECLARED" ] || { echo "$STAGE: driver digest $OBSERVED is not the staged $DECLARED" >&2; exit 2; }
fi

MODE="${1:---preflight}"
EXTRA=()
# bash 3.2 under `set -u`: a bare "${EXTRA[@]}" on an empty array is an
# unbound-variable error, so the +-expansion spelling is required, not stylistic.
[ "$MODE" = "--execute" ] && EXTRA=( --execute )
backup "$OUT/%(subcommand)s.json"
"$DRIVER" %(subcommand)s \\
    --rpc-url "$DCLUTCH_RPC_URL" --i-mean-devnet %(genesis)s \\
    "${FLAGS[@]}" ${EXTRA[@]+"${EXTRA[@]}"}
"""

DRIVER_SOLANA = """
# The Solana CLI and the deployer key live outside any job directory, so they
# are named by ENVIRONMENT and never by path: a path written here is a path that
# stops being true the moment this directory is archived or handed over.
: "${%(cli_env)s:?absolute path to the solana CLI required}"
: "${%(deployer_env)s:?absolute deployer keypair path required}"
CLI="${%(cli_env)s}"
backup "$OUT/%(stage_slug)s.tsv"
"${CLI}" --version >/dev/null || { echo "$STAGE: the named solana CLI does not run" >&2; exit 2; }
"${CLI}" %(subcommand)s --url "$DCLUTCH_RPC_URL" --keypair "${%(deployer_env)s}" "${FLAGS[@]}"
"""

DRIVER_SCRIPT = """
# A repository script, named by ENVIRONMENT. The job directory does not own the
# tree, so it does not write the tree's path down.
: "${%(repo_env)s:?absolute path to the dclutch repository required}"
TOOL="$%(repo_env)s/%(path)s"
[ -f "$TOOL" ] || { echo "$STAGE: no %(path)s under the named repository" >&2; exit 2; }
backup "$OUT"
%(runner)s "$TOOL" "${FLAGS[@]}"
"""

DRIVER_COMMIT = """
# THIS ROW IS A COMMIT, NOT A RUN, and that is why it is a row: its omission is
# invisible until money has moved. There is nothing here to execute.
echo "$STAGE is a source commit in the dclutch tree, not a command in this job directory." >&2
echo "What to do:" >&2
%(what)s
exit 64
"""


def emit(row, index, view_step, document) -> str:
    stage = view_step["stage"]
    slug = re.sub(r"[^a-z0-9-]+", "-", stage.lower()).strip("-")
    genesis = document["cluster"]["genesis_hash"]
    kind, _, rest = row["driver"].partition(":")

    lines = ["#!/usr/bin/env bash", MARKER, "#",
             f"# {view_step['id']} {stage}   (runbook key: {row['key']}, since cohort {row['since']})",
             "#", "# WHAT THIS DOES"]
    lines += wrap(view_step["command"])
    lines += ["#", "# THE VERIFIER, WHICH IS WHAT SAYS THIS RAN -- not the exit code:"]
    lines += wrap(view_step["verifier"])
    if view_step["blocks"] != "-":
        lines += ["#", "# Nothing at step " + view_step["blocks"] + " may start until this is green."]
    if view_step["cost"] != "-":
        lines += ["#", f"# Priced from cohort-{document['prior_cohort']}'s own ledger: {view_step['cost']} SOL."]
    lines.append("")

    if kind == "commit":
        # No endpoint, no driver, no flags: asking for what it cannot use is how
        # a stage acquires a ceremony nobody can explain.
        body = 'set -euo pipefail\nSTAGE="%s"\n' % slug
        body += DRIVER_COMMIT % {
            "what": "\n".join(f'echo "  {line[4:]}" >&2' for line in wrap(view_step["command"], prefix="#   ")),
        }
        return "\n".join(lines) + body

    body = PREAMBLE % {"stage_literal": f'"{slug}"'}
    if kind == "bootstrap":
        body += DRIVER_BOOTSTRAP % {"binary": DRIVER_BINARY, "subcommand": rest, "genesis": genesis}
    elif kind == "solana-cli":
        body += DRIVER_SOLANA % {
            "cli_env": document["host"]["solana_cli_env"],
            "deployer_env": document["host"]["deployer_keypair_env"],
            "subcommand": rest.replace("-", " ", 1) if rest.startswith("program-") else rest,
            "stage_slug": slug,
        }
    elif kind == "script":
        body += DRIVER_SCRIPT % {
            "repo_env": document["host"]["repo_env"], "path": rest,
            "runner": "python3" if rest.endswith(".py") else "bash",
        }
    elif kind == "simulator":
        body += DRIVER_SCRIPT % {
            "repo_env": document["host"]["repo_env"],
            "path": "tools/load-simulator/simulator.py", "runner": "python3",
        }
    else:
        raise SystemExit(f"{row['key']}: driver kind {kind!r} has no emission")

    body += f'\necho "{slug.upper().replace("-", "_")}_EXIT=0"\n'
    return "\n".join(lines) + body


def selfcontained(path: pathlib.Path) -> list[str]:
    offenders = []
    for number, line in enumerate(path.read_text().splitlines(), 1):
        if number == 1 and line.startswith("#!"):
            continue
        for match in ABSOLUTE.finditer(line):
            if match.group(0) in ALLOWED_ABSOLUTE:
                continue
            offenders.append(f"{path.name}:{number}: {match.group(0)}")
    return offenders


def credentialfree(path: pathlib.Path) -> list[str]:
    text = path.read_text()
    return [f"{path.name}: holds an endpoint credential"] if re.search(r"https?://[^\s\"']*[?@]", text) else []


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--cohort", required=True)
    parser.add_argument("--out", required=True, help="a job directory; refuses to clobber hand-written scripts")
    parser.add_argument("--delta", action="store_true")
    arguments = parser.parse_args()

    document = check_steps.manifest(arguments.cohort)
    table = check_steps.rows()
    problems: list[str] = []
    check_steps.structural(table, problems)
    chosen = check_steps.select(table, int(document["cohort"]), arguments.delta)
    view = check_steps.render(table, chosen, document, problems)
    if problems:
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        return 1

    out = pathlib.Path(arguments.out).resolve()
    out.mkdir(parents=True, exist_ok=True)
    # THE LIVE JOB DIRECTORY IS NOT OURS TO REWRITE. A hand-written stage script
    # is a cohort in flight; refusing here is cheaper than a lane discovering it.
    for existing in sorted(out.glob("*.sh")):
        if MARKER not in existing.read_text():
            print(f"refusing to write beside a hand-written script: {existing.name}", file=sys.stderr)
            return 2

    written, offences = [], []
    for index, (row, step) in enumerate(zip(chosen, view)):
        slug = re.sub(r"[^a-z0-9-]+", "-", step["stage"].lower()).strip("-")
        path = out / f"{step['id']}-{slug}.sh"
        path.write_text(emit(row, index, step, document))
        path.chmod(path.stat().st_mode | stat.S_IXUSR)
        written.append(path)
        offences += selfcontained(path) + credentialfree(path)

    if offences:
        # A generator that merely INTENDS not to write a secret or a stranding
        # path, and one that checks, log identically. So it checks, every time,
        # and removes what it wrote rather than leaving it to be trusted.
        print("refusing to leave a job directory whose scripts depend on paths outside it:", file=sys.stderr)
        for offence in offences:
            print(f"  {offence}", file=sys.stderr)
        for path in written:
            path.unlink()
        return 2

    flags = out / "flags"
    flags.mkdir(exist_ok=True)
    for row, step in zip(chosen, view):
        slug = re.sub(r"[^a-z0-9-]+", "-", step["stage"].lower()).strip("-")
        target = flags / f"{slug}.flags"
        if target.exists():
            continue
        target.write_text(
            f"# {step['id']} {step['stage']}: the flags this driver needs, one per line.\n"
            f"# The runbook carries the command and the verifier, not these. Until it\n"
            f"# does, this file is where that knowledge lives -- and counting these\n"
            f"# files is how the migration measures what is left.\n")
    print(f"cohort-{document['cohort']}{' delta' if arguments.delta else ''}: "
          f"{len(written)} stage scripts, {len(list(flags.glob('*.flags')))} flag files, "
          f"0 absolute paths, 0 credentials")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
