#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Emit a cohort's job-directory stage scripts as ONE family, from the runbook.

Cohort-15 ran from 33 hand-written scripts naming 82 absolute paths and 134
flags the runbook did not carry, in four structural shapes -- a bounded wait, an
attempt loop, guard-exits, and one script waiting on another's log. Every one of
those is now a column: the flags are `args`, the shapes are `shape`, and the
peer-chaining is `blocks`. This generator is where they become bash.

Every emitted script:

  * resolves everything from `$HERE` -- the job directory is the unit, and a
    path into a build scratch is not in it. Enforced, not intended: the
    self-contained value test below refuses to leave a script naming any
    absolute path, and `test.sh` proves it red.
  * resolves the driver from `$HERE/bin` and CHECKS ITS DIGEST against the
    `.sha256` staging wrote beside it, so a swapped driver is refused rather
    than run.
  * reads the endpoint credential AT USE TIME from the environment. No file
    here holds it, and none ever prints it.
  * REFUSES TO START until every row that `blocks` it has left its GREEN
    marker -- a stage chained behind a settle no longer greps another script's
    log to find out whether the settle landed.
  * BACKS UP BEFORE IT ATTEMPTS. An output that exists is copied under
    `$HERE/backups/<stage>/` with the attempt's Unix time before anything
    overwrites it.
  * carries THE VERIFIER THE ROW NAMES, as the thing to check, in words, and
    writes its GREEN marker only when its last invocation exited zero. The exit
    code is not the verifier; this repository has paid for that three times in
    one day.

A row whose `args` are `-` is emitted as a script that refuses with the
sentence "this row carries no args yet", so the count of those is visible in
the job directory rather than in a lane's memory. A row that names `{market.x}`
is emitted once per market of the kind its stage implies; the manifest's
`markets` list is the authority for how many.

usage: generate-stage-scripts.py --cohort 15 --out <dir> [--delta]
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import pathlib
import re
import stat
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
_spec = importlib.util.spec_from_file_location("check_steps", HERE / "check-steps.py")
check_steps = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(check_steps)

MARKER = "# GENERATED BY tools/cohort/generate-stage-scripts.py -- edit the runbook, not this file."
# `/dev/null` is a kernel device, not an input a job directory has to carry.
# Nothing else is exempt: a real filesystem path is exactly what strands a
# cohort when the tree that held it is deleted.
ALLOWED_ABSOLUTE = {"/dev/null"}
# A leading `/` not preceded by a word char, `$`, `:` or `/`, and not itself
# beginning `//` -- a real absolute path has no empty segment, so `s/x//p` and a
# `http://` scheme are not paths this test should flag.
ABSOLUTE = re.compile(r"""(?<![\w$:/])/(?!/)[A-Za-z0-9._/-]+""")
DRIVER_BINARY = "dclutch-local-successor-bootstrap"
ATTEMPTS = 6
JOURNAL_PASSES = 40
ROLE_FLAG = {"rent": "rent-credit"}
# Write-directory flags whose driver creates the directory itself and refuses
# one that already exists.
FRESH_DIRECTORY_FLAGS = {"account-dir"}

# Which rows fan out over which markets. A row naming `{market.` runs once per
# market whose kind is in the set; the ROW KEY says which, so every new row of
# a kind the default does not cover has to be named here. Cohort-16 and
# cohort-17 both paid for that: `openbatch-two-pass` and its two successors ask
# for `{market.result_domain_record}`, a field only a General market carries,
# and the default kinds sent them at market 1 -- so the generator refused the
# whole family and the acts were run by hand.
MARKET_KIND = {
    "found-two-source": ("two-source",),
    "crank-ladder": ("two-source",),
    "capture-rung": ("two-source",),
    "found-general-family": ("general",),
    "refound-general": ("general",),
    "found-general": ("general",),
    "activate-general": ("general",),
    "openbatch-refounded": ("general",),
    "openbatch-two-pass": ("general",),
    "openbatch-frozen-tables": ("general",),
    "close-batch": ("general",),
    "second-open-batch": ("general",),
    "openbatch": ("general",),
    "seal-general": ("general",),
}
DEFAULT_KINDS = ("direct", "two-source")


def wrap(text: str, width: int = 74, prefix: str = "#   ") -> list[str]:
    words, lines, line = text.split(), [], ""
    for word in words:
        if line and len(line) + 1 + len(word) > width:
            lines.append(prefix + line)
            line = word
        else:
            line = f"{line} {word}".strip()
    if line:
        lines.append(prefix + line)
    return lines


PREAMBLE = """\
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd -P)"
# A STAGE MUST NOT INHERIT THE CALLER'S WORKING DIRECTORY. Everything here is
# rooted at $HERE already, but a `script` row shells into the repository and
# cargo reads `rust-toolchain.toml` from the CWD, so a stage launched from a
# sibling checkout builds with that checkout's toolchain. Measured 2026-09-06.
cd "$HERE"
STAGE=%(stage_literal)s
OUT="$HERE/$STAGE"
MODE="${1:---preflight}"
case "$MODE" in --preflight|--execute) ;; *) echo "$STAGE: first argument is --preflight (default) or --execute; stage arguments follow it" >&2; exit 64 ;; esac
ARG1="${2:-}"; ARG2="${3:-}"; ARG3="${4:-}"
MODEWORD="${MODE#--}"
EXTRA=()
# bash 3.2 under `set -u`: a bare "${EXTRA[@]}" on an empty array is an
# unbound-variable error, so the +-expansion spelling below is required.
[ "$MODE" = "--execute" ] && EXTRA=( --execute )

# NOTHING STARTS UNTIL WHAT BLOCKS IT IS GREEN. The runbook's `blocks` column is
# this guard; a stage chained behind another no longer greps its log.
%(guards)s
mkdir -p "$OUT" "$HERE/backups/$STAGE"
rm -f "$OUT/GREEN"

# BACK UP BEFORE THE ATTEMPT, never after it. An output that already exists is
# the evidence of the last attempt, and the next attempt is exactly when it
# stops being recoverable.
backup() {
    [ -e "$1" ] || return 0
    cp -Rp "$1" "$HERE/backups/$STAGE/$(basename "$1").$(date -u +%%s)"
}
sha() { shasum -a 256 "$1" | awk '{print $1}'; }
# One JSON field, read with the interpreter the runbook already requires.
#
# The General session's admitted caller-authority span is seeded by the PLAN's
# own familyRequestDigest, and the plan does not exist until a route has been
# produced -- so the OpenBatch row is a two-pass loop and this is how the second
# pass names the first pass's digest without a human transcribing 64 hex.
field() {
    python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))[sys.argv[2]])' "$1" "$2"
}
# A ProgramData account is a 45-byte Loader header then the ELF; the ELF digest
# is what the release gate and the chain both name.
elfsha() { tail -c +46 "$1" | shasum -a 256 | awk '{print $1}'; }
# A role's semantic release id, from the operator's own derivation beside us.
# The runbook's semantic-release-ids.py writes that file from the SHIPPED
# ARTIFACTS in this directory; nothing here types a hex string, and
# `validate_prepare` re-derives every artifact-derived id from the artifact it
# was supplied beside and refuses a mismatch by name.
semantic() {
    [ -f "$HERE/semantic-release-ids.txt" ] \
        || { echo "$STAGE: no semantic-release-ids.txt; the cohort runbook's semantic-release-ids.py writes it from this directory's own candidate artifacts" >&2; exit 2; }
    value="$(awk -v role="$1" '$1 == role { print $2 }' "$HERE/semantic-release-ids.txt")"
    [ -n "$value" ] || { echo "$STAGE: semantic-release-ids.txt names no role $1" >&2; exit 2; }
    printf '%%s' "$value"
}
%(helpers)s
"""

ENDPOINT = """\
# THE ENDPOINT CREDENTIAL IS READ AT USE TIME AND HELD BY NO FILE HERE. A keyed
# endpoint carries its credential in the query string, which is exactly why this
# file names an environment variable and never a URL.
: "${DCLUTCH_RPC_URL:?export it; this job directory deliberately does not hold it}"
GENESIS=%(genesis)s
slot() {
    curl -sS -X POST -H 'content-type: application/json' \\
        -d '{"jsonrpc":"2.0","id":1,"method":"getSlot","params":[{"commitment":"finalized"}]}' "$DCLUTCH_RPC_URL" \\
        | python3 -c 'import json,sys; print(json.load(sys.stdin)["result"])'
}
"""

SOLANA_CLI = """\
# The Solana CLI and the deployer key live outside any job directory, so they
# are named by ENVIRONMENT and never by path: a path written here is a path that
# stops being true the moment this directory is archived or handed over.
: "${%(cli_env)s:?absolute path to the solana CLI required}"
CLI="${%(cli_env)s}"
"$CLI" --version >/dev/null || { echo "$STAGE: the named solana CLI does not run" >&2; exit 2; }
# THE PROGRAM ACCOUNT NAMES ITS OWN ProgramData AT OFFSET 4, and reading it
# there needs no key. `solana program show` is the same fact behind a CLI that
# demands a default signer for a pure read -- it exits "No default signer found"
# in a job directory that deliberately holds no key, and inside a command
# substitution that empties the address instead of stopping the stage, so the
# next command fails naming a MISSING ARGUMENT rather than a missing signer. A
# Loader-v3 Program account is four bytes of enum and thirty-two of address,
# which is cohort-14's own verifier text: "each Program account still names its
# ProgramData at offset 4". The request is built in python from the
# environment, never interpolated into a shell-quoted JSON literal.
programdata() {
    DCLUTCH_PROGRAM_ACCOUNT="$1" python3 - <<'PROGRAMDATA_V1'
import base64, json, os, sys, urllib.request

address = os.environ["DCLUTCH_PROGRAM_ACCOUNT"]
if not address:
    sys.exit("programdata: no program address was given")
request = urllib.request.Request(
    os.environ["DCLUTCH_RPC_URL"],
    data=json.dumps({
        "jsonrpc": "2.0",
        "id": 1,
        "method": "getAccountInfo",
        "params": [address, {
            "encoding": "base64",
            "commitment": "finalized",
            "dataSlice": {"offset": 4, "length": 32},
        }],
    }).encode(),
    headers={"content-type": "application/json"},
)
with urllib.request.urlopen(request, timeout=30) as answer:
    value = json.load(answer).get("result", {}).get("value")
if not value:
    sys.exit("programdata: no finalized account at " + address)
raw = base64.b64decode(value["data"][0])
if len(raw) != 32:
    sys.exit("programdata: " + address + " is not a 36-byte Loader-v3 Program account")
alphabet = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
number = int.from_bytes(raw, "big")
out = ""
while number:
    number, remainder = divmod(number, 58)
    out = alphabet[remainder] + out
for byte in raw:
    if byte:
        break
    out = "1" + out
print(out)
PROGRAMDATA_V1
}
"""

DRIVER_BOOTSTRAP = """\
# THE DRIVER IS BESIDE US AND ITS DIGEST IS CHECKED. Staging copies the built
# binary in and writes the digest next to it; a swapped driver is refused here
# rather than discovered by its output.
DRIVER="$HERE/bin/%(binary)s"
[ -x "$DRIVER" ] || { echo "$STAGE: no driver at bin/%(binary)s; the job directory carries its own" >&2; exit 2; }
if [ -f "$DRIVER.sha256" ]; then
    OBSERVED="$(sha "$DRIVER")"
    DECLARED="$(cat "$DRIVER.sha256")"
    [ "$OBSERVED" = "$DECLARED" ] || { echo "$STAGE: driver digest $OBSERVED is not the staged $DECLARED" >&2; exit 2; }
fi
"""

REPO = """\
# A repository script, named by ENVIRONMENT. The job directory does not own the
# tree, so it does not write the tree's path down.
: "${%(repo_env)s:?absolute path to the dclutch repository required}"
"""

WAIT = """
# THE WAIT IS BOUNDED THE WAY `wait_until_unix_seconds_v1` IS BOUNDED: a ceiling
# it refuses rather than sleeps past, at most one sleep and one re-read, against
# the CHAIN's clock. The guard is the LAST statement before the act and it
# EXITS rather than falling through -- cohort-14's runner refused its wait and
# acted anyway.
CEILING="${WAIT_CEILING_SECONDS:-%(ceiling)s}"
schedule() {
    "$DRIVER" devnet-sponsored-relay-schedule-v1 --rpc-url "$DCLUTCH_RPC_URL" --i-mean-devnet "$GENESIS" \\
        --window-record %(window)s "$@"
}
field() { python3 -c 'import json,sys; p=json.load(sys.stdin)["plan"]; print(eval(sys.argv[1], {}, {"p": p}))' "$1"; }
echo "=== bounded wait for the %(phase)s (ceiling ${CEILING}s) at $(date -u +%%FT%%TZ) ==="
for pass in 1 2; do
    DOC="$(schedule)"
    NOW="$(printf '%%s' "$DOC" | field 'p["observed_unix_seconds"]')"
    TARGET="$(printf '%%s' "$DOC" | field 'p["%(phase)s"]["at_unix_seconds"]')"
    REMAINING=$(( TARGET - NOW ))
    echo "pass $pass: chain clock $NOW, target $TARGET, ${REMAINING}s remaining"
    [ "$REMAINING" -le 0 ] && break
    if [ "$REMAINING" -gt "$CEILING" ]; then
        echo "REFUSED: ${REMAINING}s is past the stated ceiling of ${CEILING}s; a wait this long is a scheduling decision" >&2
        exit 2
    fi
    sleep "$REMAINING"
done
echo "=== re-read the schedule; the guard EXITS, it does not fall through ==="
backup "$OUT/schedule-at-%(phase)s.json"; rm -f "$OUT/schedule-at-%(phase)s.json"
schedule --output "$OUT/schedule-at-%(phase)s.json" > "$OUT/log-schedule-at-%(phase)s.txt" 2>&1
VERDICT="$(field 'p["%(phase)s"]["verdict"]' < "$OUT/schedule-at-%(phase)s.json")"
NOW="$(field 'p["observed_unix_seconds"]' < "$OUT/schedule-at-%(phase)s.json")"
if [ "$VERDICT" != "due" ]; then
    echo "REFUSED: the %(phase)s verdict is '$VERDICT', not 'due'; the %(phase)s is NOT fired" >&2; exit 2
fi
%(window_guard)s
"""

WINDOW_GUARD_CAPTURE = """\
START="$(field 'p["window"]["start_unix_seconds"]' < "$OUT/schedule-at-capture.json")"
END="$(field 'p["window"]["end_unix_seconds"]' < "$OUT/schedule-at-capture.json")"
DEADLINE=$(( END - 120 ))
echo "chain clock $NOW; window [$START, $END]; ladder deadline $DEADLINE"
if [ "$NOW" -lt "$START" ] || [ "$NOW" -gt "$DEADLINE" ]; then
    echo "REFUSED: chain clock $NOW is outside [$START, $DEADLINE]; the capture is NOT fired" >&2; exit 2
fi"""

WINDOW_GUARD_SETTLE = """\
LEGAL="$(field 'p["settle"]["legal_from_unix_seconds"]' < "$OUT/schedule-at-settle.json")"
DEADLINE=9999999999
echo "chain clock $NOW; settle legal from $LEGAL"
if [ "$NOW" -lt "$LEGAL" ]; then
    echo "REFUSED: chain clock $NOW is before $LEGAL; the settle is NOT fired" >&2; exit 2
fi"""

ATTEMPT_LOOP = """
# THE ACT IS TWO PHASES: the first --execute writes a key-free planned report
# and refuses; the sign must follow it back to back, because the candidate PDA
# is seeded by the live publish_time and a stale plan earns "derived sponsored
# coordinates changed after preflight". Each attempt gets its OWN output path.
LANDED=no
for attempt in $(seq 1 %(attempts)s); do
    if [ "$(date -u +%%s)" -gt "${DEADLINE:-9999999999}" ]; then echo "REFUSED: local clock past $DEADLINE; stopping" >&2; exit 2; fi
    echo "--- %(label)s attempt $attempt at $(date -u +%%FT%%TZ) ---"
%(plan)s > "$OUT/log-%(label)s-a$attempt-plan.txt" 2>&1 || true
%(sign)s > "$OUT/log-%(label)s-a$attempt-sign.txt" 2>&1 && { echo "%(upper)s_LANDED attempt=$attempt"; LANDED=yes; break; }
    grep -iE "^Error|refus|supersed" "$OUT/log-%(label)s-a$attempt-sign.txt" | head -3 || true
done
[ "$LANDED" = yes ] || { echo "%(upper)s_NOT_LANDED after %(attempts)s attempts" >&2; exit 1; }
"""

JOURNAL_LOOP = """
# A JOURNAL: one durable action per pass, rerun to advance. The loop is bounded
# by passes AND by a wall-clock deadline, because two signers on one payer is a
# race this project has already lost a founding to. AN EXPIRED PLAN IS NOT A
# FAILURE, AND THE TOOL SAYS SO IN WORDS: a Planned entry that was never signed
# carries no durability obligation, so it is preserved under a dated name and
# the next pass plans fresh; an entry in any other phase is left where it is.
JOURNAL_DEADLINE="${JOURNAL_DEADLINE_UNIX:-$(( $(date -u +%%s) + 21600 ))}"
DONE=no
for pass in $(seq 1 ${JOURNAL_PASSES:-%(passes)s}); do
    if %(done_test)s; then DONE=yes; break; fi
    NOW="$(date -u +%%s)"
    if [ "$NOW" -ge "$JOURNAL_DEADLINE" ]; then echo "STOPPED: wall clock $NOW reached the deadline $JOURNAL_DEADLINE before completion" >&2; exit 3; fi
    echo "--- %(label)s pass $pass at $(date -u +%%FT%%TZ), $(( JOURNAL_DEADLINE - NOW ))s of budget left ---"
    set +e
    PASS_OUT="$(%(act)s 2>&1)"
    STATUS=$?
    set -e
    printf '%%s\\n' "$PASS_OUT" | tail -12
    if [ "$STATUS" -ne 0 ] && printf '%%s' "$PASS_OUT" | grep -qE "blockhash expired before key load|prestate changed after durable planning|planned protocol prestate differed"; then
        for entry in %(journal_dir)s/*.json; do
            [ -f "$entry" ] || continue
            if [ "$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("phase","unknown"))' "$entry")" = "planned" ]; then
                mv "$entry" "$entry.expired.$(date -u +%%s)"
                echo "preserved expired plan $(basename "$entry")"
                STATUS=0
            fi
        done
    fi
    [ "$STATUS" -eq 0 ] || { echo "REFUSED at pass $pass with exit $STATUS; stopping" >&2; exit "$STATUS"; }
done
if [ "$DONE" = no ] && %(done_test)s; then DONE=yes; fi
[ "$DONE" = yes ] || { echo "%(upper)s_NOT_COMPLETE after ${JOURNAL_PASSES:-%(passes)s} passes" >&2; exit 1; }
echo "%(upper)s_COMPLETE"
"""

COMMIT = """\
set -euo pipefail
STAGE=%(stage_literal)s
# THIS ROW IS A COMMIT, NOT A RUN, and that is why it is a row: its omission is
# invisible until money has moved. There is nothing here to execute.
echo "$STAGE is a source commit in the dclutch tree, not a command in this job directory." >&2
echo "What to do:" >&2
%(what)s
exit 64
"""

NO_ARGS = """\
set -euo pipefail
STAGE=%(stage_literal)s
echo "$STAGE: this row carries no args yet; the runbook names its command and its verifier and not the driver's own arguments" >&2
echo "Run it by hand from the row's command, and put what you ran into the args column." >&2
exit 64
"""


class Emission(Exception):
    pass


def market_kinds(key: str) -> tuple[str, ...]:
    return MARKET_KIND.get(key, DEFAULT_KINDS)


def per_market(row: dict) -> bool:
    """A row fans out over markets if it names a market field OR waits on a
    market's own schedule -- a `wait:` row reads `{market.window_record}` from
    the template rather than from its args, and would otherwise emit once with
    no market."""
    return "{market." in row["args"] or row["shape"].startswith("wait:")


def lookup_or_refuse(document: dict, dotted: str, where: str):
    value = check_steps.lookup(document, dotted)
    if value is None:
        raise Emission(f"{where}: the manifest has no field {dotted!r}")
    return value


def expand_inline_loops(text: str, document: dict, market: dict | None, where: str) -> str:
    """`@roles{ ... }`, `@owned_roles{ ... }`, `@list:a.b{ ... }` -> repeated text."""
    out = []
    i = 0
    while True:
        match = check_steps.INLINE_LOOP.search(text, i)
        if not match:
            out.append(text[i:])
            break
        out.append(text[i:match.start()])
        depth, j = 1, match.end()
        while j < len(text) and depth:
            depth += {"{": 1, "}": -1}.get(text[j], 0)
            j += 1
        body = text[match.end():j - 1]
        head = match.group(0)[1:-1]
        if head == "roles":
            items = [(role, {"role": role, "role_flag": ROLE_FLAG.get(role, role)}) for role in document["roles"]]
        elif head == "owned_roles":
            items = [(role, {"role": role, "role_flag": ROLE_FLAG.get(role, role)}) for role in document["owned_roles"]]
        else:
            dotted = head[len("list:"):]
            if dotted.startswith("market."):
                if market is None:
                    raise Emission(f"{where}: {{{dotted}}} needs a market")
                node = market
                for part in dotted.split(".")[1:]:
                    node = node.get(part) if isinstance(node, dict) else None
                    if node is None:
                        raise Emission(f"{where}: market {market.get('label')} has no field {dotted!r}")
            else:
                node = lookup_or_refuse(document, dotted, where)
            if not isinstance(node, list):
                raise Emission(f"{where}: {dotted!r} is not a list")
            items = [(str(item), {"item": str(item)}) for item in node]
        rendered = []
        for _, scope in items:
            piece = body
            for name, value in scope.items():
                piece = piece.replace("{" + name + "}", value)
            rendered.append(piece.strip())
        out.append(" ".join(rendered))
        i = j
    return "".join(out)


def substitute(text: str, document: dict, prior: dict | None, market: dict | None,
               scope: dict[str, str], stages: dict[str, str], where: str) -> str:
    text = expand_inline_loops(text, document, market, where)
    # The loop-scope names (`{role}`, `{participant}`, ...) are resolved by
    # TEXT replacement first, so a single placeholder pass then resolves
    # `{programs.custody}` and `{pubkey:keys/participant-1.json}` -- and never
    # re-scans the bash it just emitted for `{execute}` (a `${EXTRA[@]...}`
    # brace is not a placeholder).
    for name, value in scope.items():
        text = text.replace("{" + name + "}", value)

    def one(match):
        raw = match.group(1)
        if raw == "mode":
            return "$MODEWORD"
        if raw == "attempt":
            return "$attempt"
        if raw == "execute":
            return '${EXTRA[@]+"${EXTRA[@]}"}'
        if raw.startswith("execute:"):
            # DOUBLE QUOTES, because the payload carries $HERE. Single-quoted,
            # `--fee-payer-keypair $HERE/keys/campaign-payer.json` reached the
            # driver with the four characters `$HERE` in it and earned "fee
            # settlement payer keypair path must be absolute" -- a refusal about
            # a path that was never a path. The outer $( ) is deliberately
            # unquoted so the payload still splits into separate arguments; the
            # generator already refuses absolute paths, and a job directory with
            # a space in its name would be caught by the self-contained test.
            payload = raw[len("execute:"):]
            if '"' in payload:
                raise Emission(f"{where}: an {{execute:…}} payload may not contain a double quote")
            return '$( [ "$MODE" = --execute ] && printf %s "' + payload + '" )'
        if raw.startswith("pubkey:"):
            path = one(check_steps.PLACEHOLDER.fullmatch(raw[len("pubkey:"):])) if raw[len("pubkey:"):].startswith("{") else raw[len("pubkey:"):]
            return '$(solana-keygen pubkey "$HERE/' + path + '")'
        if raw.startswith("stage:"):
            key = raw[len("stage:"):]
            if key not in stages:
                raise Emission(f"{where}: {{stage:{key}}} names a row this cohort does not run")
            return "$HERE/" + stages[key]
        if raw.startswith("market."):
            if market is None:
                raise Emission(f"{where}: {{{raw}}} used in a row with no market")
            node = market
            for part in raw.split(".")[1:]:
                node = node.get(part) if isinstance(node, dict) else None
                if node is None:
                    raise Emission(f"{where}: market {market.get('label')!r} has no field {raw!r}; record it in the manifest and regenerate")
            if not isinstance(node, (str, int)):
                raise Emission(f"{where}: market field {raw!r} is not a value")
            return str(node)
        if raw.startswith("prior."):
            if prior is None:
                raise Emission(f"{where}: {{{raw}}} needs cohorts/{document['prior_cohort']}.json")
            field = raw[len("prior."):]
            if field == "job_dirname":
                return pathlib.PurePath(prior["job_dir"]).name
            value = check_steps.lookup(prior, field)
            if value is None:
                raise Emission(f"{where}: the prior manifest has no field {field!r}")
            return str(value)
        return str(lookup_or_refuse(document, raw, where))

    # Innermost-first to a fixpoint, so `{pubkey:{market.fill.debtor_keypair}}`
    # resolves the inner name and then the outer. A `{` preceded by `$` is a
    # bash parameter expansion (`${ARG2:+--prior ...}`, and the `${EXTRA[@]...}`
    # an `{execute}` expands to), never a placeholder -- so re-scanning the
    # emitted output leaves it alone. A `{...}` body may hold `:` and `/`, which
    # the gate's plainer placeholder does not match; this generator has its own.
    pattern = re.compile(r"(?<!\$)\{([^{}]+)\}")
    for _ in range(6):
        new = pattern.sub(one, text)
        if new == text:
            break
        text = new
    return text


def command_line(kind: str, rest: str, document: dict) -> str:
    if kind == "bootstrap":
        return '"$DRIVER" ' + rest.replace(" ", ' --rpc-url "$DCLUTCH_RPC_URL" --i-mean-devnet "$GENESIS" ', 1) if " " in rest else '"$DRIVER" ' + rest
    if kind == "bootstrap-public":
        sub, _, tail = rest.partition(" ")
        return f'"$DRIVER" {sub} --rpc-url {document["cluster"]["public_url"]} --i-mean-devnet "$GENESIS" {tail}'
    if kind == "bootstrap-offline":
        return '"$DRIVER" ' + rest
    if kind == "solana":
        sub = rest.split(" ")
        # `--url` rides after the subcommand words (`program deploy`, `transfer`).
        words = 2 if sub[0] in ("program", "address-lookup-table", "stake") else 1
        return '"$CLI" ' + " ".join(sub[:words]) + ' --url "$DCLUTCH_RPC_URL" ' + " ".join(sub[words:])
    if kind == "script":
        path, _, tail = rest.partition(" ")
        runner = "python3" if path.endswith(".py") else "bash"
        return f'{runner} "$DCLUTCH_REPO/{path}" {tail}'
    if kind == "simulator":
        return f'python3 "$DCLUTCH_REPO/tools/load-simulator/simulator.py" {rest}'
    if kind == "sh":
        return rest
    raise Emission(f"driver kind {kind!r} has no emission")


def emit(row, view_step, document, prior, market, stages) -> str:
    key = row["key"]
    stage = view_step["stage"]
    slug = re.sub(r"[^a-z0-9-]+", "-", stage.lower()).strip("-")
    label = market["label"] if market else None
    stage_dir = f"{key}-{label}" if market else key
    where = f"{key}" + (f" (market {label})" if market else "")

    lines = ["#!/usr/bin/env bash", MARKER, "#",
             f"# {view_step['id']} {stage}   (runbook key: {key}, since cohort {row['since']}"
             + (f", market {label}" if market else "") + ")",
             "#", "# WHAT THIS DOES"]
    lines += wrap(view_step["command"])
    lines += ["#", "# THE VERIFIER, WHICH IS WHAT SAYS THIS RAN -- not the exit code:"]
    lines += wrap(view_step["verifier"])
    if view_step["blocks"] != "-":
        lines += ["#", "# Nothing at step " + view_step["blocks"] + " may start until this is green."]
    if view_step["cost"] != "-":
        lines += ["#", f"# Priced from cohort-{document['prior_cohort']}'s own ledger: {view_step['cost']} SOL."]
    lines.append("")
    head = "\n".join(lines)

    if row["shape"] == "commit":
        what = "\n".join(f'echo "  {line[4:]}" >&2' for line in wrap(view_step["command"], prefix="#   "))
        return head + COMMIT % {"stage_literal": f'"{stage_dir}"', "what": what}
    if row["args"] == "-":
        return head + NO_ARGS % {"stage_literal": f'"{stage_dir}"'}

    # The guards: every row that blocks THIS row must have left GREEN.
    blockers = [r["key"] for r in row["_chosen"] if row["key"] in [b.strip() for b in r["blocks"].split(",")]]
    guards = []
    for blocker in blockers:
        for bdir in stages_for(blocker, row["_chosen"], document, label):
            guards.append(f'[ -f "$HERE/{bdir}/GREEN" ] || {{ echo "$STAGE: {bdir} has not gone green; nothing here may start until it has" >&2; exit 65; }}')
    if not guards:
        guards.append("# (nothing blocks this row)")

    invs = check_steps.invocations(row["args"])
    kinds = {check_steps.invocation_parts(t)[3].split(" ", 1)[0] for t in invs}
    needs_endpoint = kinds & {"bootstrap", "bootstrap-public", "solana", "script", "simulator", "sh"} or row["shape"] in check_steps.LOOPING
    needs_driver = kinds & {"bootstrap", "bootstrap-public", "bootstrap-offline"} or row["shape"] in check_steps.LOOPING
    needs_cli = "solana" in kinds or "programdata" in row["args"] or "$CLI" in row["args"]
    needs_repo = kinds & {"script", "simulator"}
    helpers = ""
    if needs_endpoint:
        helpers += ENDPOINT % {"genesis": document["cluster"]["genesis_hash"]}
    if needs_cli:
        helpers += SOLANA_CLI % {"cli_env": document["host"]["solana_cli_env"]}
    if needs_driver:
        helpers += DRIVER_BOOTSTRAP % {"binary": DRIVER_BINARY}
    if needs_repo:
        helpers += REPO % {"repo_env": document["host"]["repo_env"]}
    for var in sorted(set(re.findall(r"\$(DCLUTCH_[A-Z_]+)", row["args"])) - {"DCLUTCH_RPC_URL", "DCLUTCH_REPO"}):
        helpers += f': "${{{var}:?required by this stage}}"\n'

    body = PREAMBLE % {"stage_literal": f'"{stage_dir}"', "guards": "\n".join(guards), "helpers": helpers}

    roles = document["roles"] if row["shape"] == "per-role" else [None]
    acts: list[tuple[str, str | None]] = []
    plain: list[str] = []
    for role in roles:
        scope = {"role": role, "role_flag": ROLE_FLAG.get(role, role)} if role else {}
        for text in invs:
            loop, act, skip, rest = check_steps.invocation_parts(text)
            done_spec = None
            m = check_steps.ACT.match(text.split(" ", 1)[1] if loop else text)
            if act and m and m.group(0).strip().startswith("*["):
                done_spec = m.group(0).strip()[2:-1]
            kind, _, tail = rest.partition(" ")
            repeats: list[dict[str, str]]
            if loop == "@roles":
                repeats = [{"role": r, "role_flag": ROLE_FLAG.get(r, r)} for r in document["roles"]]
            elif loop == "@owned_roles":
                repeats = [{"role": r, "role_flag": ROLE_FLAG.get(r, r)} for r in document["owned_roles"]]
            elif loop == "@participants":
                repeats = [{"participant": p} for p in document["payer"]["participant_keypairs"]]
            else:
                repeats = [{}]
            for extra in repeats:
                line = command_line(kind, substitute(tail, document, prior, market, {**scope, **extra}, stages, where), document)
                if act:
                    acts.append((line, substitute(done_spec, document, prior, market, {**scope, **extra}, stages, where) if done_spec else None))
                    continue
                if skip:
                    # THE PATH A `?` CHECKS IS THE ROW'S OWN OUTPUT, WHICH IS
                    # ALWAYS UNDER $OUT. Taking the first write-shaped flag was
                    # wrong the moment a row also READ one: `arm-relay` passes
                    # `--evidence $HERE/<market>/campaign-open.json`, the
                    # founding's report, before its `--output $OUT/...`, so both
                    # invocations announced "present, not overwriting" about an
                    # input that had of course been there since the founding,
                    # and the stage produced nothing. Measured on cohort-17.
                    candidates = [(m.group(1), m.group(2)) for m in re.finditer(
                        r"--(output|evidence|out|completion)(?:-dir)?\s+(\S+)", line)]
                    named = [v for f, v in candidates if f != "evidence"] \
                        or [v for f, v in candidates]
                    if not named:
                        raise Emission(f"{where}: a `?` invocation names no --output/--evidence to check")
                    line = f'if [ -e "{named[0]}" ]; then echo "{named[0]} present, not overwriting"; else {line}; fi'
                else:
                    output = re.search(r"--(output|evidence|out|completion)(-dir)?\s+(\S+)", line)
                    if output and output.group(3).startswith("$OUT"):
                        path = output.group(3)
                        # A DIRECTORY THIS ROW MUST HAND THE DRIVER HAS TO SURVIVE
                        # ITS OWN BACKUP. `--output-dir` is emptied for the fresh
                        # attempt and then recreated, because the driver refuses
                        # "No such file or directory" on an absent one -- the
                        # preamble's mkdir and this rm otherwise cancel out, which
                        # is what cohort-17 measured.
                        remake = ""
                        if output.group(2) and output.group(1) not in FRESH_DIRECTORY_FLAGS \
                           and f"{output.group(1)}-dir" not in FRESH_DIRECTORY_FLAGS:
                            remake = f'; mkdir -p "{path}"'
                        line = f'backup "{path}"; rm -rf "{path}"{remake}\n{line}'
                plain.append(line)

    # A ROW THAT WRITES OUTSIDE $OUT HAS TO BE ALLOWED TO. The preamble creates
    # $OUT and the backup directory and nothing else, so `prepare` -- whose
    # `--output-file $HERE/observed/<role>.programdata.bin` is the runbook's own
    # words -- died on the FIRST role with "No such file or directory (os error
    # 2)" and no name for what was missing.
    #
    # ONLY THE PARENT, NEVER THE DIRECTORY ITSELF. `prepare --account-dir
    # $HERE/accounts` creates its own account directory and REFUSES one that
    # already exists ("create fresh account directory ...: File exists"), so a
    # generator that made the leaf would trade one refusal for another. The
    # parents are derived from the row's own write flags rather than listed.
    written = set()
    for line, _ in acts + [(t, None) for t in plain]:
        for flag, value in re.findall(r"--([a-z-]*(?:output|evidence|completion|campaign|journal|account|dump|receipt)[a-z-]*)\s+(\S+)", line):
            if not (value.startswith("$HERE/") or value.startswith("$OUT/")):
                continue
            # A `-dir` flag names a directory, and the two drivers that take one
            # want OPPOSITE things: `devnet-direct-trade-produce-v1 --output-dir`
            # refuses "No such file or directory" when it is absent, and
            # `prepare --account-dir` refuses "create fresh account directory:
            # File exists" when it is present. Both measured on cohort-17. So
            # the leaf is created for every write directory except the ones a
            # driver insists on creating itself, and that set is named here
            # rather than guessed from the flag's shape.
            parent = value if (flag.endswith("-dir") and flag not in FRESH_DIRECTORY_FLAGS) \
                else value.rsplit("/", 1)[0]
            if parent not in ("$HERE", "$OUT"):
                written.add(parent)
    if written:
        body += "# Every directory this row's own write flags name, and no other.\n"
        body += "mkdir -p " + " ".join(f'"{d}"' for d in sorted(written)) + "\n"

    if row["shape"] in ("once", "per-role"):
        body += "\n" + "\n".join(plain) + "\n"
    elif row["shape"] in ("attempts", "wait:capture", "wait:settle"):
        before = plain
        if row["shape"].startswith("wait:"):
            phase = row["shape"][5:]
            body += WAIT % {"ceiling": 2000, "phase": phase,
                            "window": substitute("{market.window_record}", document, prior, market, {}, stages, where),
                            "window_guard": WINDOW_GUARD_CAPTURE if phase == "capture" else WINDOW_GUARD_SETTLE}
        if before:
            body += "\n" + "\n".join(before) + "\n"
        for line, _ in acts:
            act_label = re.search(r"--action\s+(\S+)", line)
            act_label = act_label.group(1) if act_label else "act"
            body += ATTEMPT_LOOP % {"attempts": ATTEMPTS, "label": act_label, "upper": act_label.upper().replace("-", "_"),
                                    "plan": "    " + line, "sign": "    " + line}
    elif row["shape"] == "journal":
        if plain:
            body += "\n" + "\n".join(plain) + "\n"
        for line, done in acts:
            if not done:
                raise Emission(f"{where}: a journal act must name what says it is done: *[FILE] or *[FILE:field,field]")
            path, _, fields = done.partition(":")
            if fields:
                checks = " and ".join(f'd.get("{f}") is not None' for f in fields.split(","))
                done_test = f'[ -f "{path}" ] && python3 -c \'import json,sys; d=json.load(open(sys.argv[1])); sys.exit(0 if ({checks}) else 1)\' "{path}"'
            else:
                done_test = f'[ -f "{path}" ]'
            journal_dir = re.search(r"--journal-dir\s+(\S+)", line)
            act_label = re.search(r'"\$DRIVER" (\S+)', line)
            act_label = (act_label.group(1) if act_label else "act").replace("devnet-", "").replace("-v1", "")
            body += JOURNAL_LOOP % {"passes": JOURNAL_PASSES, "label": act_label, "upper": act_label.upper().replace("-", "_"),
                                    "act": line, "done_test": done_test,
                                    "journal_dir": journal_dir.group(1) if journal_dir else "$OUT"}
    else:
        raise Emission(f"{where}: shape {row['shape']!r} has no emission")

    body += f'\ntouch "$OUT/GREEN"\necho "{stage_dir.upper().replace("-", "_")}_EXIT=0"\n'
    return head + body


def stages_for(key: str, chosen: list[dict], document: dict, label: str | None) -> list[str]:
    """The output directories a row emits: one, or one per market it fans over."""
    row = next((r for r in chosen if r["key"] == key), None)
    if row is None:
        return []
    if not per_market(row):
        return [key]
    kinds = market_kinds(key)
    # A per-market row blocking a per-market row binds the SAME market; a
    # per-market row blocking a one-shot row means all of its markets.
    markets = [m for m in document.get("markets", []) if m.get("kind", "direct") in kinds]
    if label is not None and any(m["label"] == label for m in markets):
        return [f"{key}-{label}"]
    return [f"{key}-{m['label']}" for m in markets]


def selfcontained(path: pathlib.Path) -> list[str]:
    offenders = []
    for number, line in enumerate(path.read_text().splitlines(), 1):
        if number == 1 and line.startswith("#!"):
            continue
        for match in ABSOLUTE.finditer(line):
            if match.group(0) in ALLOWED_ABSOLUTE:
                continue
            offenders.append(f"{path.name}:{number}: {match.group(0)}")
    return offenders


def credentialfree(path: pathlib.Path) -> list[str]:
    text = path.read_text()
    return [f"{path.name}: holds an endpoint credential"] if re.search(r"https?://[^\s\"']*[?@]", text) else []


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--cohort", required=True)
    parser.add_argument("--out", required=True, help="a job directory; refuses to clobber hand-written scripts")
    parser.add_argument("--delta", action="store_true")
    arguments = parser.parse_args()

    document = check_steps.manifest(arguments.cohort)
    prior_path = check_steps.COHORTS / f"{document.get('prior_cohort')}.json"
    prior = json.loads(prior_path.read_text()) if prior_path.exists() else None
    table = check_steps.rows()
    problems: list[str] = []
    check_steps.structural(table, problems)
    chosen = check_steps.select(table, int(document["cohort"]), arguments.delta)
    view = check_steps.render(table, chosen, document, problems)
    if problems:
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        return 1
    for row in chosen:
        row["_chosen"] = chosen

    out = pathlib.Path(arguments.out).resolve()
    out.mkdir(parents=True, exist_ok=True)
    # THE LIVE JOB DIRECTORY IS NOT OURS TO REWRITE. A hand-written stage script
    # is a cohort in flight; refusing here is cheaper than a lane discovering it.
    for existing in sorted(out.glob("*.sh")):
        if MARKER not in existing.read_text():
            print(f"refusing to write beside a hand-written script: {existing.name}", file=sys.stderr)
            return 2

    written, offences, unemitted = [], [], []
    try:
        for row, step in zip(chosen, view):
            markets = [None]
            if per_market(row):
                markets = [m for m in document.get("markets", []) if m.get("kind", "direct") in market_kinds(row["key"])]
                if not markets:
                    print(f"  {row['key']}: no market of kind {market_kinds(row['key'])} in the manifest; not emitted")
                    continue
            stages = {r["key"]: (r["key"] + "-{label}" if per_market(r) else r["key"]) for r in chosen}
            for market in markets:
                bound = {k: v.replace("{label}", market["label"] if market else "") for k, v in stages.items()}
                suffix = f"-{market['label']}" if market else ""
                path = out / f"{step['id']}-{row['key']}{suffix}.sh"
                path.write_text(emit(row, step, document, prior, market, bound))
                path.chmod(path.stat().st_mode | stat.S_IXUSR)
                written.append(path)
                offences += selfcontained(path) + credentialfree(path)
                if row["args"] == "-" and row["shape"] != "commit":
                    unemitted.append(row["key"])
    except Emission as refusal:
        print(f"refusing: {refusal}", file=sys.stderr)
        for path in written:
            path.unlink()
        return 2

    if offences:
        # A generator that merely INTENDS not to write a secret or a stranding
        # path, and one that checks, log identically. So it checks, every time,
        # and removes what it wrote rather than leaving it to be trusted.
        print("refusing to leave a job directory whose scripts depend on paths outside it:", file=sys.stderr)
        for offence in offences:
            print(f"  {offence}", file=sys.stderr)
        for path in written:
            path.unlink()
        return 2

    print(f"cohort-{document['cohort']}{' delta' if arguments.delta else ''}: "
          f"{len(written)} stage scripts, 0 absolute paths, 0 credentials, "
          f"{len(unemitted)} rows carrying no args yet" + (f" ({', '.join(unemitted)})" if unemitted else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
