"""tools/gate emission -- every generated file: guarded, at its formatting fixpoint, pinned, and byte-identical to its emitter.

  tools/gate emission                 the cheap gate (~2s): --verify, --pins and --fixpoint together
  tools/gate emission --census        print the census of generated files and their guards
  tools/gate emission --write         rewrite tools/gates/emission-coverage.md from the census
  tools/gate emission --verify        byte-gate emission-coverage.md against the tree
  tools/gate emission --fixpoint      raw-compared Rust emissions that rustfmt does not leave alone,
                                      against fixpoint-debt.tsv; --write-debt rewrites that baseline
  tools/gate emission --pins          the two-sided wire vectors still carry their reviewed digests;
                                      --repin re-pins from disk after a deliberate move
  tools/gate emission --affected RANGE   which guards a git range could have moved
  tools/gate emission --run RANGE | --run --all   run those guards for real (needs lake, rustfmt, node)

Refuses: a generated file (its first line names a Lean emitter) with no guard
that re-runs that emitter and compares; a guard comparing raw emitter stdout over
a file rustfmt would reflow (one `lane.sh fmt` from red); a wire-vector fixture
whose sha256 differs from the pin a human typed; a guard whose comparison fails.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from .common import EXIT_FAIL, EXIT_PASS, EXIT_PREREQ, EXIT_USAGE, GATES, REPO, Prereq, have, note, sh, tracked_files

COVERAGE = GATES / "emission-coverage.md"
FIXPOINT_DEBT = GATES / "fixpoint-debt.tsv"
PINS = GATES / "wire-vector-pins.tsv"
FORMAL_DIR = "formal/dclutch-semantics"

# The provenance header a Lean emitter prints as its first line; the check scripts assert the same line.
HEADER_RE = re.compile(r"^(?://|#|--) @generated by formal/dclutch-semantics/(Emit[A-Za-z0-9_]+\.lean); do not edit\.$")
# `lake env lean --run EmitFoo.lean` inside a check script: the emitter it re-runs.
SCRIPT_EMITTER_RE = re.compile(r"lake env lean --run\s+(Emit[A-Za-z0-9_]+\.lean)")
# `node scripts/lean-emit.mjs <Module> EmitFoo.lean <target> --check` in a package.json script.
LEAN_EMIT_RE = re.compile(r"lean-emit\.mjs\s+\S+\s+(Emit[A-Za-z0-9_]+\.lean)\s+(\S+)(?:\s+(--check))?")
# A Rust integration test that runs the emitter and asserts its stdout equals the committed bytes.
RUST_EMITTER_RE = re.compile(r'"(Emit[A-Za-z0-9_]+\.lean)"')
RUST_READBACK_RE = re.compile(r"fs::read\b|include_str!|read_to_string\b")
RUST_COMPARE_RE = re.compile(r"assert_eq!")
RUSTFMT_RE = re.compile(r"\brustfmt\b")


def runs_rustfmt(text: str) -> bool:
    """Whether a guard INVOKES rustfmt (a comment saying it does not is not an invocation)."""
    for line in text.splitlines():
        if line.lstrip().startswith(("#", "//", "*", "/*")):
            continue
        if RUSTFMT_RE.search(line):
            return True
    return False


@dataclass
class Guard:
    path: str
    emitters: set[str] = field(default_factory=set)
    kind: str = "shell"  # shell | lean-emit | cargo-test
    workdir: str = ""
    command: list[str] = field(default_factory=list)
    normalises: bool = False


@dataclass
class Census:
    generated: dict[str, str]
    guards: list[Guard]

    @property
    def guarded_emitters(self) -> set[str]:
        return set().union(*(g.emitters for g in self.guards)) if self.guards else set()

    def split(self):
        covered = self.guarded_emitters
        return ({f: e for f, e in self.generated.items() if e in covered},
                {f: e for f, e in self.generated.items() if e not in covered})


def first_line(path: Path) -> str | None:
    try:
        with path.open("rb") as handle:
            return handle.readline(4096).decode("utf-8").rstrip("\n")
    except (OSError, UnicodeDecodeError):
        return None


def discover_generated(root: Path, files: list[str]) -> dict[str, str]:
    generated = {}
    for rel in files:
        if rel.startswith(f"{FORMAL_DIR}/") or rel == FORMAL_DIR:
            continue  # the emitter prints the header as a literal: author, not artifact
        line = first_line(root / rel)
        match = HEADER_RE.match(line) if line else None
        if match:
            generated[rel] = match.group(1)
    return generated


def discover_guards(root: Path, files: list[str]) -> list[Guard]:
    guards: list[Guard] = []
    for rel in files:
        if not rel.endswith(".sh") or "check" not in Path(rel).name:
            continue
        try:
            text = (root / rel).read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        emitters = set(SCRIPT_EMITTER_RE.findall(text))
        if emitters:
            guards.append(Guard(rel, emitters, "shell", str(Path(rel).parent), ["sh", str(root / rel)], runs_rustfmt(text)))
    for rel in files:
        if Path(rel).name != "package.json":
            continue
        try:
            text = (root / rel).read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        pkg_dir = str(Path(rel).parent)
        for emitter, _target, check in LEAN_EMIT_RE.findall(text):
            if check:
                guards.append(Guard(f"{pkg_dir}: lean-emit {emitter}", {emitter}, "lean-emit", pkg_dir, ["node", "scripts/lean-emit.mjs"]))
    for rel in files:
        path = Path(rel)
        if path.suffix != ".rs" or path.parent.name != "tests":
            continue
        crate_dir = path.parent.parent
        if not (root / crate_dir / "Cargo.toml").is_file():
            continue
        try:
            text = (root / rel).read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if not RUST_READBACK_RE.search(text) or not RUST_COMPARE_RE.search(text):
            continue
        emitters = set(RUST_EMITTER_RE.findall(text))
        if emitters:
            guards.append(Guard(rel, emitters, "cargo-test", str(crate_dir),
                                ["cargo", "test", "--manifest-path", f"{crate_dir}/Cargo.toml", "--test", path.stem],
                                runs_rustfmt(text)))
    return sorted(guards, key=lambda g: g.path)


def build_census(root: Path = REPO) -> Census:
    files = tracked_files(root)
    return Census(discover_generated(root, files), discover_guards(root, files))


def render_coverage(census: Census) -> str:
    guarded, unguarded = census.split()
    emitters = set(census.generated.values())
    covered = census.guarded_emitters & emitters
    rust_guards = [g for g in census.guards if g.kind != "lean-emit"]
    raw = [g for g in rust_guards if not g.normalises]
    lines = [
        "<!-- @generated by tools/gate emission --write -- do not hand-edit; byte-gated by tools/gate emission --verify -->",
        "# Lean emission coverage",
        "",
        f"**{len(census.generated)} generated files from {len(emitters)} emitters. "
        f"{len(guarded)} guarded ({len(covered)} emitters), "
        f"{len(unguarded)} unguarded ({len(emitters) - len(covered)} emitters).**",
        "",
        "A guard is a comparison, never a build: a `check*.sh` script, a `package.json` script passing `--check`, "
        "or a Rust integration test that reads the committed artifact back and asserts equality. "
        "This file counts guards that EXIST; `tools/gate guards` runs them. "
        f"**Normalises** says whether a guard runs rustfmt over the emission before comparing: of the {len(rust_guards)} guards "
        f"over Rust emissions, {len(rust_guards) - len(raw)} do and {len(raw)} compare raw emitter stdout, which is green only "
        "while the emission is already a rustfmt fixpoint (`tools/gate emission --fixpoint` keeps `fixpoint-debt.tsv` honest).",
        "",
        "## Guards",
        "",
        "| Guard | Kind | Normalises | Emitters re-run |",
        "|---|---|---|---|",
    ]
    for guard in census.guards:
        names = ", ".join(f"`{e}`" for e in sorted(guard.emitters))
        shape = "n/a" if guard.kind == "lean-emit" else ("yes" if guard.normalises else "raw")
        lines.append(f"| `{guard.path}` | {guard.kind} | {shape} | {names} |")
    lines += ["", "## Guarded generated files", "", "| File | Emitter |", "|---|---|"]
    lines += [f"| `{rel}` | `{guarded[rel]}` |" for rel in sorted(guarded)]
    lines += ["", "## Unguarded generated files", ""]
    if unguarded:
        by_emitter: dict[str, list[str]] = {}
        for rel, emitter in unguarded.items():
            by_emitter.setdefault(emitter, []).append(rel)
        lines += ["| Emitter | Files with no guard |", "|---|---|"]
        lines += [f"| `{e}` | {'<br>'.join(f'`{f}`' for f in sorted(by_emitter[e]))} |" for e in sorted(by_emitter)]
    else:
        lines.append("None. Every generated file has a guard behind it.")
    return "\n".join(lines) + "\n\n"


# ------------------------------------------------------------------ fixpoint

def normalising_emitters(census: Census) -> set[str]:
    return set().union(*(g.emitters for g in census.guards if g.normalises)) if census.guards else set()


def fixpoint_hazards(root: Path, census: Census) -> list[tuple[str, str]]:
    """Generated Rust files whose guard compares raw stdout and which rustfmt does not leave alone."""
    if not have("rustfmt"):
        raise Prereq("rustfmt is not on PATH (rustup toolchain install 1.97.1); the fixpoint check has not passed")
    normalised = normalising_emitters(census)
    hazards = []
    with tempfile.TemporaryDirectory() as tmp:
        target = Path(tmp) / "generated.rs"
        for rel, emitter in sorted(census.generated.items()):
            if not rel.endswith(".rs") or emitter in normalised:
                continue
            original = (root / rel).read_bytes()
            target.write_bytes(original)
            result = subprocess.run(["rustfmt", "--edition", "2024", str(target)], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            if result.returncode != 0 or target.read_bytes() != original:
                hazards.append((rel, emitter))
    return hazards


def read_fixpoint_debt(path: Path = FIXPOINT_DEBT) -> list[tuple[str, str]]:
    if not path.is_file():
        return []
    rows = []
    for line in path.read_text().splitlines():
        if line.strip() and not line.startswith("#"):
            rel, _, emitter = line.partition("\t")
            rows.append((rel, emitter))
    return sorted(rows)


def render_fixpoint_debt(hazards: list[tuple[str, str]]) -> str:
    head = [
        "# @generated by tools/gate emission --fixpoint --write-debt",
        "# Generated Rust files rustfmt does not leave alone whose guard compares raw emitter stdout:",
        "# green today, red the first time anyone runs `tools/lane.sh fmt` on the path. The owning lane",
        "# repairs a row by teaching the guard to rustfmt the emission before comparing, or by making the",
        "# emitter print what rustfmt would print. A RATCHET: a new pair reds --fixpoint; so does a repaired one still listed.",
        "# path\temitter",
    ]
    return "\n".join(head + [f"{rel}\t{emitter}" for rel, emitter in sorted(hazards)]) + "\n"


def fixpoint(root: Path = REPO, *, write_debt: bool = False) -> int:
    census = build_census(root)
    hazards = fixpoint_hazards(root, census)
    if write_debt:
        FIXPOINT_DEBT.write_text(render_fixpoint_debt(hazards))
        print(f"FIXPOINT-DEBT\t{FIXPOINT_DEBT}\nSUMMARY\thazards={len(hazards)}")
        return EXIT_PASS
    recorded = read_fixpoint_debt()
    arrived = [row for row in hazards if row not in recorded]
    repaired = [row for row in recorded if row not in hazards]
    for rel, emitter in arrived:
        print(f"FIXPOINT\tARRIVED\t{rel}\t{emitter}\traw-compared and rustfmt does not leave it alone")
    for rel, emitter in repaired:
        print(f"FIXPOINT\tREPAIRED\t{rel}\t{emitter}\tno longer a hazard; drop it with --write-debt")
    print(f"SUMMARY\thazards={len(hazards)}\trecorded={len(recorded)}\tarrived={len(arrived)}\trepaired={len(repaired)}"
          f"\tstatus={'STOP' if (arrived or repaired) else 'PASS'}")
    return EXIT_FAIL if (arrived or repaired) else EXIT_PASS


# ------------------------------------------------------------------ wire-vector pins

def pins(root: Path = REPO, *, repin: bool = False, pins_path: Path = PINS) -> int:
    """The reviewed sha256 of each two-sided wire vector, in a file no test can write.

    Each authoring test accepts DCLUTCH_WRITE_WIRE_VECTOR=1 to rewrite its fixture,
    which also makes a moved wire green on both sides at once. The pin is the half
    a human has to type. A deliberate move commits the fixture and the pin together.
    """
    if not pins_path.is_file():
        raise Prereq("tools/gates/wire-vector-pins.tsv is absent; the DCLUTCH_WRITE_WIRE_VECTOR escape hatch is unguarded")
    moved, missing, lines = [], [], []
    for number, line in enumerate(pins_path.read_text().splitlines(), 1):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        fields = line.split("\t")
        if len(fields) != 3:
            raise Prereq(f"wire-vector-pins.tsv:{number}: expected sha256, path, authoring test")
        pinned, relative, test = fields
        path = root / relative
        if not path.exists():
            missing.append(relative)
            lines.append(line)
            continue
        actual = hashlib.sha256(path.read_bytes()).hexdigest()
        if actual != pinned:
            moved.append(f"  {relative}\n    pinned {pinned}\n    on disk {actual}\n    authored by {test}")
        lines.append(f"{actual if repin else pinned}\t{relative}\t{test}")
    if missing:
        print("wire-vector-pins: a pinned fixture is MISSING, which re-pinning does not fix: " + ", ".join(missing))
        return EXIT_FAIL
    if repin:
        if not moved:
            print("wire-vector-pins: nothing moved")
            return EXIT_PASS
        header = [l for l in pins_path.read_text().splitlines() if not l.strip() or l.lstrip().startswith("#")]
        pins_path.write_text("\n".join(header + lines) + "\n")
        print(f"wire-vector-pins: RE-PINNED {len(moved)} fixture(s); commit the fixture and the pin TOGETHER, digests in the message:")
        print("\n".join(moved))
        return EXIT_PASS
    if moved:
        print(f"wire-vector-pins: {len(moved)} fixture(s) do not match their reviewed digest:")
        print("\n".join(moved))
        print("Deliberate move: re-run the authoring test with DCLUTCH_WRITE_WIRE_VECTOR=1, then `tools/gate emission --pins --repin`, one commit.")
        return EXIT_FAIL
    print(f"wire-vector-pins: {len(lines)} pinned fixture(s) match")
    return EXIT_PASS


# ------------------------------------------------------------------ running the guards

def changed_paths(root: Path, revision_range: str) -> list[str]:
    result = sh(["git", "-C", root, "diff", "--name-only", revision_range], capture=True)
    if result.returncode != 0:
        raise Prereq(f"cannot read '{revision_range}': {result.stderr.strip()}")
    return [line for line in result.stdout.splitlines() if line]


def affected_guards(census: Census, changed: list[str]):
    """Any edit under formal/ selects EVERY guard (Lean modules share definitions);
    an edit to a generated file alone selects that file's guard."""
    touched_formal = [p for p in changed if p.startswith(f"{FORMAL_DIR}/")]
    if touched_formal:
        return list(census.guards), f"{len(touched_formal)} file(s) under {FORMAL_DIR}/ changed; every guard is in scope"
    selected, reasons, changed_set = {}, [], set(changed)
    for guard in census.guards:
        if guard.path in changed_set:
            selected[guard.path] = guard
            reasons.append(f"{guard.path} itself changed")
    for rel, emitter in census.generated.items():
        if rel in changed_set:
            for guard in census.guards:
                if emitter in guard.emitters:
                    selected[guard.path] = guard
                    reasons.append(f"{rel} changed, guarded by {guard.path}")
    return list(selected.values()), "; ".join(reasons) or "nothing in scope"


def npm_script_for(root: Path, pkg_dir: str, emitter: str) -> str | None:
    try:
        data = json.loads((root / pkg_dir / "package.json").read_text())
    except (OSError, ValueError):
        return None
    for name, body in (data.get("scripts") or {}).items():
        if emitter in body and "--check" in body:
            return name
    return None


def run_guards(root: Path, guards: list[Guard]) -> int:
    failures = 0
    for guard in guards:
        print(f"EMISSION-GUARD\trun\t{guard.path}", flush=True)
        if guard.kind == "shell":
            result = subprocess.run(["sh", guard.path], cwd=root)
        elif guard.kind == "cargo-test":
            result = subprocess.run(guard.command, cwd=root)  # this one test binary, never a bare -p
        else:
            pkg_dir, emitter = guard.path.split(": lean-emit ")
            name = npm_script_for(root, pkg_dir, emitter)
            if name is None:
                print(f"EMISSION-GUARD\tskip\t{guard.path}\tno --check script found")
                continue
            result = subprocess.run(["npm", "run", "--silent", name], cwd=root / pkg_dir)
        failures += result.returncode != 0
        print(f"EMISSION-GUARD\t{'FAIL' if result.returncode else 'ok'}\t{guard.path}", flush=True)
    return failures


# ------------------------------------------------------------------ the tiers

def verify(root: Path = REPO) -> int:
    census = build_census(root)
    guarded, unguarded = census.split()
    fresh = render_coverage(census)
    drifted = (COVERAGE.read_text() if COVERAGE.is_file() else None) != fresh
    print(f"SUMMARY\tgenerated={len(census.generated)}\tguarded={len(guarded)}\tunguarded={len(unguarded)}"
          f"\tguards={len(census.guards)}\tdrift={drifted}\tstatus={'STOP' if drifted else 'PASS'}")
    if drifted:
        print("emission: emission-coverage.md is stale. `tools/gate emission --write`, then read the diff: "
              "if the unguarded count went UP, a generated file arrived with nothing checking it.", file=sys.stderr)
    return EXIT_FAIL if drifted else EXIT_PASS


def cheap(*, dry_run: bool = False):
    if dry_run:
        note("$ tools/gate emission --verify && tools/gate emission --pins && tools/gate emission --fixpoint")
        return EXIT_PASS, ""
    if verify():
        return EXIT_FAIL, "emission-coverage.md no longer describes this tree"
    if pins():
        return EXIT_FAIL, "a wire vector moved without its pin"
    if not have("rustfmt"):
        return EXIT_PREREQ, "rustfmt is not on PATH, so the formatting hazards were not checked"
    if fixpoint():
        return EXIT_FAIL, "a raw-compared emission rustfmt does not leave alone (or a repaired row still listed)"
    return EXIT_PASS, ""


def verdict(*, range_: str | None = None, dry_run: bool = False):
    if not have("lake"):
        return EXIT_PREREQ, "lake (Lean) is not on PATH, so no byte-identity guard ran"
    if dry_run:
        note(f"$ tools/gate emission --run {range_ or '--all'}")
        return EXIT_PASS, ""
    census = build_census(REPO)
    selected, why = (affected_guards(census, changed_paths(REPO, range_)) if range_ else (list(census.guards), "--all"))
    print(f"EMISSION-GUARD\tscope\t{why}")
    failures = run_guards(REPO, selected)
    print(f"SUMMARY\tran={len(selected)}\tfailures={failures}")
    return (EXIT_FAIL, f"{failures} guard(s) failed: a generated file no longer matches its emitter") if failures else (EXIT_PASS, "")


def main(argv: list[str]) -> int:
    if argv and argv[0] in ("-h", "--help"):
        print(__doc__.strip())
        return EXIT_PASS
    flags = set(a for a in argv if a.startswith("--"))
    values = {a: argv[i + 1] for i, a in enumerate(argv) if a in ("--affected", "--run") and i + 1 < len(argv) and not argv[i + 1].startswith("--")}
    unknown = flags - {"--census", "--write", "--verify", "--fixpoint", "--write-debt", "--pins", "--repin", "--affected", "--run", "--all"}
    if unknown:
        print(f"emission: unknown option {sorted(unknown)[0]}", file=sys.stderr)
        return EXIT_USAGE
    if not flags:
        code, detail = cheap()
        if detail:
            print(f"emission: {detail}", file=sys.stderr)
        return code
    if "--fixpoint" in flags:
        return fixpoint(write_debt="--write-debt" in flags)
    if "--pins" in flags:
        return pins(repin="--repin" in flags)
    if "--verify" in flags:
        return verify()
    census = build_census(REPO)
    if "--write" in flags:
        COVERAGE.write_text(render_coverage(census))
        guarded, unguarded = census.split()
        print(f"COVERAGE\t{COVERAGE}\nSUMMARY\tgenerated={len(census.generated)}\tguarded={len(guarded)}\tunguarded={len(unguarded)}\tguards={len(census.guards)}")
        return EXIT_PASS
    if "--affected" in flags or "--run" in flags:
        if "--all" in flags:
            selected, why, touched = list(census.guards), "--all", []
        else:
            revision_range = values.get("--affected") or values.get("--run")
            if not revision_range:
                print("emission: --run needs a git range, or --all", file=sys.stderr)
                return EXIT_USAGE
            touched = changed_paths(REPO, revision_range)
            selected, why = affected_guards(census, touched)
        print(f"EMISSION-GUARD\tscope\t{why}")
        for guard in sorted(selected, key=lambda g: g.path):
            print(f"EMISSION-GUARD\tselected\t{guard.path}")
        _, unguarded = census.split()
        for rel in sorted(set(touched) & set(unguarded)):
            print(f"EMISSION-GUARD\tUNGUARDED\t{rel}\tgenerated file changed and NO guard re-runs its emitter")
        if "--run" in flags:
            if not have("lake"):
                raise Prereq("lake (Lean) is not on PATH")
            if not selected:
                print("EMISSION-GUARD\tnothing to run")
                return EXIT_PASS
            failures = run_guards(REPO, selected)
            print(f"SUMMARY\tran={len(selected)}\tfailures={failures}")
            return EXIT_FAIL if failures else EXIT_PASS
        return EXIT_PASS
    sys.stdout.write(render_coverage(census))
    return EXIT_PASS
