//! The two-sided selector-9 AccountProfile vector.
//!
//! `apps/dclutch-web/lib/dealerAccountProfileV3.ts` re-implements this crate's
//! profile encoder byte for byte, so `validateDealerAccountProfileV3` can
//! compare a fetched profile against what the route must have published. It is
//! a HAND-MAINTAINED MIRROR with no generator behind it, which is the most
//! expensive shape a browser surface can have: nothing relates it to the
//! encoder, so it drifts silently and only a real transaction finds out.
//!
//! It had drifted. 8e4aa710e found three wrong bytes -- a signer bit copied
//! from `SignedDeltaFrameSpecV3` instead of from the encoder that drops it, and
//! a `RequireKey` guard that f5d4912e REMOVED still mirrored at two offsets --
//! and from efca6966 until that commit the browser would have refused every
//! real selector-9 profile. Nothing went red, because nothing tested it: the
//! browser's own test covers selector 1 only, and the comparison that found
//! these was done BY HAND, out of band. A hand comparison protects the day it
//! is run and nothing after it.
//!
//! This is the durable form. One fixture, two independent producers: the Rust
//! encoder here, and `expectedScenarioProfile` in the browser's mirror, checked
//! by `dealerAccountProfileV3.vector.test.ts` in both TypeScript trees. If the
//! profile moves, THIS test goes red first -- the authority stays in the
//! program, and the browser is the side that has to catch up.
//!
//! DERIVATION OF THE INPUT, so no number here is chosen to make something pass:
//! `common_data_lengths` is the width vector of the five injected accounts the
//! encoder reads -- root, config, Product root, portfolio, linked basis. The
//! config width is not free: the encoder REFUSES unless entry 1 equals
//! `DEALER_CONFIG_BYTES_V4`, so it is taken from that constant rather than
//! typed. The other four are arbitrary distinct plausible widths; they are
//! INPUTS, and the assertion is that both languages lay the same inputs out
//! identically.
//!
//! Regenerate with `DCLUTCH_WRITE_WIRE_VECTOR=1 cargo test -p
//! dclutch-trading-sbf --test dealer_scenario_profile_vector`, and only when
//! the profile deliberately moved. Regenerating is how a deliberate move lands;
//! it is not a way to make a red go away.

use std::{env, fs, path::PathBuf};

use dclutch_trading_sbf::dealer::v3_trade_profile::{
    DEALER_CONFIG_BYTES_V4, DEALER_SCENARIO_ACCOUNT_PROFILE_BYTES_V4,
    DealerScenarioAccountProfileInputV4, encode_dealer_scenario_account_profile_v4_atomic,
};

/// The encoder pins this one itself: it refuses when entry 1 is anything else.
const CONFIG_WIDTH: u32 = DEALER_CONFIG_BYTES_V4 as u32;
const COMMON_DATA_LENGTHS: [u32; 5] = [64, CONFIG_WIDTH, 96, 112, 128];

fn vector_paths() -> [PathBuf; 2] {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    [
        root.join("apps/dclutch-web/fixtures/dealer-scenario-account-profile-v4.json"),
        root.join("packages/dclutch-sdk/fixtures/dealer-scenario-account-profile-v4.json"),
    ]
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

fn encoded_profile() -> Vec<u8> {
    let mut scratch = vec![0_u8; DEALER_SCENARIO_ACCOUNT_PROFILE_BYTES_V4];
    let mut output = vec![0_u8; DEALER_SCENARIO_ACCOUNT_PROFILE_BYTES_V4];
    encode_dealer_scenario_account_profile_v4_atomic(
        DealerScenarioAccountProfileInputV4 {
            common_data_lengths: COMMON_DATA_LENGTHS,
        },
        &mut scratch,
        &mut output,
    )
    .expect("selector-9 account profile encodes at the stated width vector");
    output
}

fn rendered_vector() -> String {
    let profile = encoded_profile();
    let lengths = COMMON_DATA_LENGTHS
        .iter()
        .map(|value| value.to_string())
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        concat!(
            "{{\n",
            "  \"note\": \"Generated by programs/dclutch-trading-sbf/tests/dealer_scenario_profile_vector.rs; do not hand-edit.\",\n",
            "  \"commonDataLengths\": [{lengths}],\n",
            "  \"profileBytes\": {width},\n",
            "  \"profileHex\": \"{profile}\"\n",
            "}}\n"
        ),
        lengths = lengths,
        width = profile.len(),
        profile = hex(&profile),
    )
}

#[test]
fn browser_mirror_and_encoder_agree_on_every_profile_byte() {
    let rendered = rendered_vector();
    if env::var_os("DCLUTCH_WRITE_WIRE_VECTOR").is_some() {
        for path in vector_paths() {
            fs::write(&path, &rendered).expect("write the selector-9 profile vector");
        }
        return;
    }
    for path in vector_paths() {
        let committed = fs::read_to_string(&path).unwrap_or_else(|error| {
            panic!(
                "read the selector-9 profile vector at {}: {error}",
                path.display()
            )
        });
        assert_eq!(
            committed,
            rendered,
            "the selector-9 account profile moved and {} did not follow; regenerate with \
             DCLUTCH_WRITE_WIRE_VECTOR=1 only if the move was deliberate, and expect the \
             browser's mirror to go red until it catches up",
            path.display()
        );
    }
}

#[test]
fn the_vector_is_the_whole_profile_and_not_a_prefix() {
    // A vector that silently covered less than the artifact would be the same
    // defect one level up: the hand comparison this replaces checked all 2,100
    // bytes, and so must this.
    assert_eq!(
        encoded_profile().len(),
        DEALER_SCENARIO_ACCOUNT_PROFILE_BYTES_V4
    );
}
