'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';

import {
  PRODUCT_MAX_COMPUTE_UNITS,
  compileProductV2,
  evaluateProductV2,
  parseProductKnots,
  parseProductTerms,
  prepareProductV2LiabilityTransaction,
  productInteger,
  type CompiledProductV2,
  type ProductV2LiabilityPlan,
} from '@/lib/productV2';
import { SolanaRpcClient } from '@/lib/rpc';

function message(error: unknown): string { return error instanceof Error ? error.message : 'Product V2 operation failed without a usable refusal reason'; }
function compact(value: string): string { return value.length > 22 ? `${value.slice(0, 10)}…${value.slice(-8)}` : value; }
function base64(bytes: Uint8Array): string { let binary = ''; for (let offset = 0; offset < bytes.length; offset += 16_384) binary += String.fromCharCode(...bytes.slice(offset, offset + 16_384)); return btoa(binary); }

export default function ProductV2Studio() {
  const [productId, setProductId] = useState(''); const [domainId, setDomainId] = useState(''); const [unitId, setUnitId] = useState(''); const [payoutScale, setPayoutScale] = useState(''); const [knotDenominator, setKnotDenominator] = useState(''); const [knots, setKnots] = useState(''); const [terms, setTerms] = useState('');
  const [compiled, setCompiled] = useState<CompiledProductV2 | null>(null); const [compileStatus, setCompileStatus] = useState('No Product has been authored or compiled.');
  const [sampleNumerator, setSampleNumerator] = useState(''); const [sampleDenominator, setSampleDenominator] = useState(''); const [sample, setSample] = useState<string | null>(null);
  const [endpoint, setEndpoint] = useState('http://127.0.0.1:8899'); const [registry, setRegistry] = useState(''); const [payer, setPayer] = useState(''); const [market, setMarket] = useState(''); const [domainRecord, setDomainRecord] = useState(''); const [lookupTable, setLookupTable] = useState(''); const [available, setAvailable] = useState(''); const [computeLimit, setComputeLimit] = useState(String(PRODUCT_MAX_COMPUTE_UNITS));
  const [plan, setPlan] = useState<ProductV2LiabilityPlan | null>(null); const [chainStatus, setChainStatus] = useState('No finalized Product authority has been reacquired.');

  async function compile(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setCompiled(null); setSample(null); setCompileStatus('Checking exact integers, canonical term order, runtime width, and fixed-layout bytes…');
    try {
      const value = await compileProductV2({ productId: productInteger(productId, 'product scalar ID'), domainId: productInteger(domainId, 'domain scalar ID'), coordinateUnitId: productInteger(unitId, 'coordinate-unit scalar ID'), payoutScale: productInteger(payoutScale, 'payout scale'), knotDenominator: productInteger(knotDenominator, 'knot denominator'), knots: parseProductKnots(knots), terms: parseProductTerms(terms) });
      setCompiled(value); setCompileStatus(`Compiled ${value.input.knots.length} knots and ${value.input.terms.length} canonical terms into exactly ${value.bytes.length} bytes.`);
    } catch (error) { setCompileStatus(`Refused: ${message(error)}`); }
  }

  function evaluate(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSample(null); if (compiled === null) return;
    try { const numerator = productInteger(sampleNumerator, 'sample numerator'); const denominator = productInteger(sampleDenominator, 'sample denominator'); setSample(`${evaluateProductV2(compiled, numerator, denominator)} scaled payout atoms at ${numerator}/${denominator}`); } catch (error) { setSample(`Refused: ${message(error)}`); }
  }

  async function build(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPlan(null); if (compiled === null) return; setChainStatus('Reacquiring the Market-selected manifest, Product/domain/binding records, three artifact releases and deployments, output PDAs, rent, lookup table, and packet boundary…');
    try {
      const value = await prepareProductV2LiabilityTransaction(new SolanaRpcClient(endpoint), compiled, { registryProgram: registry, payer, market, resultDomainRecord: domainRecord, lookupTable, available: productInteger(available, 'available collateral'), computeUnitLimit: Number(computeLimit) });
      setPlan(value); setChainStatus(`Ready: atomic evidence + liability admission is ${value.wireBytes.length} bytes and remains unsigned.`);
    } catch (error) { setChainStatus(`Refused: ${message(error)}`); }
  }

  return <main className="product-shell direct-workspace product-v2-studio">
    <header className="product-nav"><Link className="brand" href="/"><span className="brand-mark">dC</span><span>dClutch</span></Link><nav><Link href="/direct">Direct</Link><Link href="/economic">Economic</Link><Link href="/general">General</Link><Link className="active" href="/product-v2">Product V2</Link><Link href="/release">Release</Link></nav><span className="preview-control"><i className="preview-dot" />exact rational</span></header>
    <section className="market-heading"><div><div className="market-kicker"><span>signed rational line</span><span>runtime width 2..16</span><span>one floor</span></div><h1>Author the payoff as data. Inspect every authority that makes it executable.</h1><p>Knots are signed i128 numerators over one positive u64 denominator. Terms are canonical constants, ramps, or tents with clamped tails. Coordinates remain exact rationals; the sole rounding boundary is the final floor into scaled payout atoms after interpolation.</p></div></section>
    <form className="direct-card" onSubmit={compile}><div className="direct-card-heading"><span>01</span><div><h2>Compile one canonical Product V2 record</h2><p>No market or deployment is implied. This first stage owns only exact semantic data and its content identity.</p></div></div>
      <div className="direct-form-grid"><label><span>Product scalar ID · nonzero u64</span><input required inputMode="numeric" value={productId} onChange={(event) => setProductId(event.target.value.trim())} /></label><label><span>Domain scalar ID · nonzero u64</span><input required inputMode="numeric" value={domainId} onChange={(event) => setDomainId(event.target.value.trim())} /></label><label><span>Coordinate-unit scalar ID · nonzero u64</span><input required inputMode="numeric" value={unitId} onChange={(event) => setUnitId(event.target.value.trim())} /></label><label><span>Payout scale · atoms per unit</span><input required inputMode="numeric" value={payoutScale} onChange={(event) => setPayoutScale(event.target.value.trim())} /></label><label><span>Common knot denominator · nonzero u64</span><input required inputMode="numeric" value={knotDenominator} onChange={(event) => setKnotDenominator(event.target.value.trim())} /></label></div>
      <div className="product-author-grid"><label><span>Strictly increasing signed knot numerators · one i128 per line</span><textarea required value={knots} onChange={(event) => setKnots(event.target.value)} spellCheck={false} /></label><label><span>Payoff terms · one canonical expression per line</span><textarea required value={terms} onChange={(event) => setTerms(event.target.value)} spellCheck={false} /><small>constant amplitude<br />ramp-up left-index right-index amplitude<br />ramp-down left-index right-index amplitude<br />tent left-index peak-index right-index amplitude</small></label></div>
      <button type="submit">Compile exact Product bytes</button><p className="direct-status" aria-live="polite">{compileStatus}</p>
      {compiled && <div className="direct-output product-compiled"><dl><div><dt>Canonical record identity</dt><dd>{compiled.digestHex}</dd></div><div><dt>Exact ABI</dt><dd>576 bytes · {compiled.input.knots.length} active knots · {compiled.input.terms.length} active terms</dd></div><div><dt>Conservative liability</dt><dd>{compiled.liabilityBound.toString()} scaled payout atoms</dd></div><div><dt>Rounding semantic release</dt><dd>{compiled.roundingReleaseId}</dd></div></dl><label><span>576-byte Product V2 record · base64</span><textarea readOnly value={base64(compiled.bytes)} /></label><div className="product-region-grid">{compiled.regions.map((region) => <article className="registered-state-card" key={`${region.label}-${region.left}`}><span className="eyebrow">{region.label}</span><h3>{region.left} → {region.right}</h3><p>Exact rational coordinates; shape-specific endpoint clamp.</p></article>)}</div></div>}
    </form>
    {compiled && <form className="direct-card" onSubmit={evaluate}><div className="direct-card-heading"><span>02</span><div><h2>Evaluate without quantizing the coordinate</h2><p>The preview uses the compiled bytes&apos; exact rational semantics. Only the final nonnegative payout interpolation is floored.</p></div></div><div className="direct-form-grid"><label><span>Signed result numerator · i128</span><input required value={sampleNumerator} onChange={(event) => setSampleNumerator(event.target.value.trim())} /></label><label><span>Positive result denominator · u64</span><input required value={sampleDenominator} onChange={(event) => setSampleDenominator(event.target.value.trim())} /></label></div><button type="submit">Evaluate exact coordinate</button><p className="direct-status" aria-live="polite">{sample ?? 'No coordinate has been evaluated.'}</p></form>}
    {compiled && <form className="direct-card" onSubmit={build}><div className="direct-card-heading"><span>03</span><div><h2>Build atomic founding evidence and admission</h2><p>The authored digest must already be the Market-selected finalized payoff record. The browser derives every other record/staging/output PDA, reauthenticates all three current Loader-v3 deployments, and uses one finalized Address Lookup Table to keep the exact 10-account evaluator plus 28-account liability admission packet bounded.</p></div></div>
      <div className="direct-form-grid"><label><span>Finalized RPC endpoint</span><input required value={endpoint} onChange={(event) => setEndpoint(event.target.value.trim())} /></label><label><span>Registry / Market Core program</span><input required value={registry} onChange={(event) => setRegistry(event.target.value.trim())} /></label><label><span>External fee payer public key</span><input required value={payer} onChange={(event) => setPayer(event.target.value.trim())} /></label><label><span>Founding Market PDA</span><input required value={market} onChange={(event) => setMarket(event.target.value.trim())} /></label><label><span>Finite result-domain finalized record</span><input required value={domainRecord} onChange={(event) => setDomainRecord(event.target.value.trim())} /></label><label><span>Finalized Address Lookup Table</span><input required value={lookupTable} onChange={(event) => setLookupTable(event.target.value.trim())} /></label><label><span>Available collateral · payout atoms</span><input required inputMode="numeric" value={available} onChange={(event) => setAvailable(event.target.value.trim())} /></label><label><span>Transaction compute-unit limit</span><input required inputMode="numeric" value={computeLimit} onChange={(event) => setComputeLimit(event.target.value.trim())} /></label></div>
      <button type="submit">Reacquire authority &amp; build unsigned transaction</button><p className="direct-status" aria-live="polite">{chainStatus}</p>
      {plan && <div className="direct-output product-admission-output"><dl><div><dt>Finalized Market</dt><dd>{plan.market} · generation {plan.generation} · slot {plan.observedSlot}</dd></div><div><dt>Binding authority</dt><dd>{plan.bindingDigest}</dd></div><div><dt>Finite result domain</dt><dd>{plan.resultDomain.semanticId}<br />{plan.resultDomain.outcomeCount} outcomes · denominator {plan.resultDomain.denominator} · cuts [{plan.resultDomain.cuts.join(', ')}]</dd></div><div><dt>Coordinate / result units</dt><dd>{plan.resultDomain.coordinateDomainId}<br />{plan.resultDomain.resultUnitId}</dd></div><div><dt>Liability / failure / total</dt><dd>{plan.liabilityBound} / {plan.failurePayout} / {plan.totalBound} atoms · available {plan.available}</dd></div><div><dt>Evidence certificate</dt><dd>{plan.certificateMode} · {plan.certificate}<br />{plan.certificateDigest}</dd></div><div><dt>Admission receipt</dt><dd>{plan.receiptMode} · {plan.receipt}<br />{plan.receiptDigest}</dd></div><div><dt>Physical output rent</dt><dd>{plan.rentDebitLamports} lamports</dd></div><div><dt>Unsigned v0 packet</dt><dd>{plan.wireBytes.length} / 1232 bytes · {plan.lookupAddressesUsed} lookup addresses</dd></div><div><dt>External signer</dt><dd>{plan.requiredSigners.join(', ')}</dd></div></dl><div className="registered-state-grid">{Object.entries(plan.artifactReleases).map(([name, release]) => <article className="registered-state-card" key={name}><span className="eyebrow">{name} release</span><h3>{compact(name === 'evaluator' ? plan.payoffProgram : name === 'admission' ? plan.admissionProgram : plan.resolutionProgram)}</h3><p>artifact {compact(release.digest)} · semantic {compact(release.semanticRelease)}</p><p>ProgramData {compact(release.programData)} · slot {release.deploymentSlot}</p></article>)}</div><label><span>112-byte evaluator request · base64</span><textarea readOnly value={base64(plan.requestBytes)} /></label><label><span>128-byte admission request · base64</span><textarea readOnly value={base64(plan.admissionBytes)} /></label><label><span>Unsigned atomic v0 transaction · base64</span><textarea readOnly value={base64(plan.wireBytes)} /></label><p className="direct-refusal"><strong>No signing or submission occurred.</strong> The payer signature remains external, and the finalized blockhash will expire.</p></div>}
    </form>}
    <footer className="product-footer"><span>Static clients are untrusted projections</span><span>No private keys · no signing · no submission</span></footer>
  </main>;
}
