// @generated by formal/dclutch-semantics/EmitClaimSbfProfile.lean; do not edit.
pub(crate) const ACCOUNT_COUNT_OFFSET: usize = 0;
pub(crate) const AUTHORITY_OFFSET: usize = 8;
pub(crate) const PROJECTION_OFFSET: usize = 10344;
pub(crate) const PROJECTION_DATA_OFFSET: usize = 10432;
pub(crate) const INSTRUCTION_LENGTH_OFFSET: usize = 20760;
pub(crate) const INSTRUCTION_OFFSET: usize = 20768;
pub(crate) const PROGRAM_ID_OFFSET: usize = 20840;
pub(crate) const AUTHORITY_FRAME_WORD: u64 = 511;
pub(crate) const PROJECTION_FRAME_WORD: u64 = 65791;
pub(crate) const PROJECTION_DATA_BYTES: u64 = 80;
pub(crate) const INSTRUCTION_BYTES: u64 = 72;
pub(crate) const STATE_MAGIC_WORD: u64 = 5691884356;
pub(crate) const PLAN_HEADER_WORD: u64 = 4403520422724;
pub(crate) const EFFECT_0_TAG: u64 = 0;
pub(crate) const EFFECT_1_TAG: u64 = 256;
pub(crate) const EFFECT_2_TAG: u64 = 65537;
pub(crate) const EFFECT_3_TAG: u64 = 65794;
