#![cfg_attr(target_os = "solana", no_std)]

//! Alias-simple exact-account SBF executor for Lean-owned Direct claim routes.

include!("generated_profile.rs");

use dclutch_direct_codec::{
    RegisteredIntentStateV1, REGISTERED_FILL_PROGRAM, REGISTERED_PHASE_OUTPUT_REGISTER,
    REGISTERED_REMAINING_OUTPUT_REGISTER, REGISTERED_SEQUENCE_OUTPUT_REGISTER,
};
use dclutch_transition_vm::{execute, Registers};

const ERROR: u64 = 5_u64 << 32;

#[cfg(target_os = "solana")]
#[panic_handler]
fn panic(_info: &core::panic::PanicInfo<'_>) -> ! {
    loop {}
}

#[inline(always)]
unsafe fn read_u64(input: *mut u8, offset: usize) -> u64 {
    // SAFETY: every caller relies on the entrypoint's named loader-extent and
    // alignment boundary and supplies a Lean-generated in-bounds offset.
    unsafe { core::ptr::read(input.add(offset).cast::<u64>()) }
}

#[inline(always)]
unsafe fn read_u8(input: *mut u8, offset: usize) -> u8 {
    // SAFETY: every caller supplies a generated in-bounds offset.
    unsafe { core::ptr::read(input.add(offset).cast_const()) }
}

#[inline(always)]
unsafe fn write_u64(input: *mut u8, offset: usize, value: u64) {
    // SAFETY: every caller writes an aligned field in a validated writable
    // account frame described by the Lean-generated profile.
    unsafe { core::ptr::write(input.add(offset).cast::<u64>(), value) };
}

#[inline(always)]
unsafe fn write_u8(input: *mut u8, offset: usize, value: u8) {
    // SAFETY: every caller writes a generated in-bounds field in a validated
    // writable account frame.
    unsafe { core::ptr::write(input.add(offset), value) };
}

#[inline(always)]
unsafe fn equal_32(input: *mut u8, left: usize, right: usize) -> bool {
    // SAFETY: propagated from the function boundary and exact profile offsets.
    unsafe {
        read_u64(input, left) == read_u64(input, right)
            && read_u64(input, left + 8) == read_u64(input, right + 8)
            && read_u64(input, left + 16) == read_u64(input, right + 16)
            && read_u64(input, left + 24) == read_u64(input, right + 24)
    }
}

#[inline(always)]
unsafe fn read_32(input: *mut u8, offset: usize) -> [u8; 32] {
    let mut output = [0_u8; 32];
    let mut index = 0;
    while index < output.len() {
        // SAFETY: the caller supplies a validated 32-byte extent.
        output[index] = unsafe { read_u8(input, offset + index) };
        index += 1;
    }
    output
}

#[inline(always)]
fn add_checked(left: u64, right: u64) -> Option<u64> {
    let result = left.wrapping_add(right);
    if result < left {
        None
    } else {
        Some(result)
    }
}

#[inline(always)]
unsafe fn exact_state_frame(
    input: *mut u8,
    account_offset: usize,
    data_offset: usize,
    frame_word: u64,
    data_bytes: u64,
    magic_word: u64,
    program_id_offset: usize,
) -> bool {
    // SAFETY: propagated from the entrypoint's loader boundary. The offsets are
    // generated by Lean and describe fields within the same account frame.
    unsafe {
        read_u64(input, account_offset) == frame_word
            && read_u64(input, account_offset + 80) == data_bytes
            && equal_32(input, account_offset + 40, program_id_offset)
            && equal_32(input, AUTHORITY_OFFSET + 8, data_offset + 8)
            && read_u64(input, data_offset) == magic_word
    }
}

#[inline(always)]
unsafe fn accounts_are_distinct_at<const N: usize>(input: *mut u8, offsets: [usize; N]) -> bool {
    let mut left = 0;
    while left < offsets.len() {
        let mut right = left + 1;
        while right < offsets.len() {
            // SAFETY: each offset identifies a validated loader account frame.
            if unsafe { equal_32(input, offsets[left] + 8, offsets[right] + 8) } {
                return false;
            }
            right += 1;
        }
        left += 1;
    }
    true
}

#[derive(Clone, Copy)]
struct RegisteredSuccessor {
    remaining: u64,
    sequence: u64,
    phase: u8,
}

#[inline(never)]
fn registered_successor(state: RegisteredIntentStateV1, fill: u64) -> Option<RegisteredSuccessor> {
    if state.phase != 0 || state.remaining == 0 || state.remaining > state.intent.maximum_fill {
        return None;
    }
    let mut registers = Registers::zeroed();
    for (index, value) in state.fill_input_scalars(fill).into_iter().enumerate() {
        registers.set_scalar(index, value).ok()?;
    }
    execute(&REGISTERED_FILL_PROGRAM, &mut registers).ok()?;
    let remaining = registers
        .scalar(REGISTERED_REMAINING_OUTPUT_REGISTER)
        .ok()?;
    let sequence = registers.scalar(REGISTERED_SEQUENCE_OUTPUT_REGISTER).ok()?;
    let phase = u8::try_from(registers.scalar(REGISTERED_PHASE_OUTPUT_REGISTER).ok()?).ok()?;
    if phase > 3 {
        return None;
    }
    Some(RegisteredSuccessor {
        remaining,
        sequence,
        phase,
    })
}

#[inline(always)]
fn registration_successor(state: RegisteredIntentStateV1, replay_nonce: u64) -> Option<u64> {
    if state.phase != 0
        || state.maker == [0; 32]
        || state.intent.side > 1
        || state.intent.lifecycle > 2
        || state.intent.valid_from > state.intent.valid_through
        || state.intent.maximum_fill == 0
        || state.remaining != state.intent.maximum_fill
        || state.sequence != 0
        || state.intent.nonce != replay_nonce
    {
        return None;
    }
    add_checked(replay_nonce, 1)
}

/// Dispatch one exact controller-authorized inline or registered claim route.
///
/// Inline replay roots and registered local sequences share this canonical
/// owner with Position claims. The controller has already authenticated their
/// profile/maker PDA coordinates; this child independently checks controller
/// authority, program ownership, exact route-specific state shapes, the
/// generated transition or ordered effect plan, and arithmetic.
///
/// # Safety
///
/// The pinned Solana loader must provide a non-null, aligned ABI-v1 buffer with
/// the complete extent implied by the Lean-generated exact-account profile.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn entrypoint(input: *mut u8) -> u64 {
    if input.is_null() {
        return ERROR;
    }

    // Five-account fills share the same authority and first mutable-account
    // offset; the first mutable account's exact width selects inline versus
    // registered fill. Two-account terminal mutations have their own exact
    // profile. No caller-provided tag can reinterpret account state bytes.
    unsafe {
        match read_u64(input, ACCOUNT_COUNT_OFFSET) {
            5 => match read_u64(input, SELLER_REPLAY_OFFSET + 80) {
                REPLAY_DATA_BYTES => execute_inline(input),
                REGISTERED_DATA_BYTES => execute_registered(input),
                _ => ERROR,
            },
            3 => execute_registered_create(input),
            2 => execute_registered_terminal(input),
            _ => ERROR,
        }
    }
}

#[inline(always)]
unsafe fn zero_span(input: *mut u8, offset: usize, bytes: usize) -> bool {
    let mut index = 0;
    while index < bytes {
        // SAFETY: the caller validated the exact account or instruction extent.
        if unsafe { read_u8(input, offset + index) } != 0 {
            return false;
        }
        index += 1;
    }
    true
}

#[inline(always)]
unsafe fn copy_span(input: *mut u8, source: usize, destination: usize, bytes: usize) {
    let mut index = 0;
    while index < bytes {
        // SAFETY: the caller validated both exact extents before copying.
        let value = unsafe { read_u8(input, source + index) };
        unsafe { write_u8(input, destination + index, value) };
        index += 1;
    }
}

#[inline(never)]
unsafe fn execute_registered_create(input: *mut u8) -> u64 {
    // SAFETY: the generated three-account profile establishes every read and
    // write extent. Both state writes occur only after canonical state, replay,
    // authority, ownership, alias, and arithmetic admission succeeds.
    unsafe {
        if read_u64(input, AUTHORITY_OFFSET) != AUTHORITY_FRAME_WORD
            || read_u64(input, AUTHORITY_OFFSET + 80) != 0
            || read_u64(input, CREATE_REPLAY_OFFSET) != REPLAY_FRAME_WORD
            || read_u64(input, CREATE_REPLAY_OFFSET + 80) != REPLAY_DATA_BYTES
            || !equal_32(input, CREATE_REPLAY_OFFSET + 40, CREATE_PROGRAM_ID_OFFSET)
            || read_u64(input, CREATE_REGISTRATION_OFFSET) != REGISTERED_FRAME_WORD
            || read_u64(input, CREATE_REGISTRATION_OFFSET + 80) != REGISTERED_DATA_BYTES
            || !equal_32(
                input,
                CREATE_REGISTRATION_OFFSET + 40,
                CREATE_PROGRAM_ID_OFFSET,
            )
            || !accounts_are_distinct_at(
                input,
                [
                    AUTHORITY_OFFSET,
                    CREATE_REPLAY_OFFSET,
                    CREATE_REGISTRATION_OFFSET,
                ],
            )
            || read_u64(input, CREATE_INSTRUCTION_LENGTH_OFFSET) != CREATE_INSTRUCTION_BYTES
            || !zero_span(
                input,
                CREATE_REGISTRATION_DATA_OFFSET,
                REGISTERED_DATA_BYTES as usize,
            )
        {
            return ERROR;
        }
        let state = match decode_registered(input, CREATE_INSTRUCTION_OFFSET) {
            Some(state) => state,
            None => return ERROR,
        };
        if state.controller != read_32(input, AUTHORITY_OFFSET + 8) {
            return ERROR;
        }
        let replay_is_vacant =
            zero_span(input, CREATE_REPLAY_DATA_OFFSET, REPLAY_DATA_BYTES as usize);
        let replay_nonce = if replay_is_vacant {
            0
        } else {
            if read_u64(input, CREATE_REPLAY_DATA_OFFSET) != REPLAY_MAGIC_WORD
                || !equal_32(input, AUTHORITY_OFFSET + 8, CREATE_REPLAY_DATA_OFFSET + 8)
            {
                return ERROR;
            }
            read_u64(input, CREATE_REPLAY_DATA_OFFSET + 40)
        };
        let next_nonce = match registration_successor(state, replay_nonce) {
            Some(nonce) => nonce,
            None => return ERROR,
        };
        if replay_is_vacant {
            write_u64(input, CREATE_REPLAY_DATA_OFFSET, REPLAY_MAGIC_WORD);
            copy_span(
                input,
                AUTHORITY_OFFSET + 8,
                CREATE_REPLAY_DATA_OFFSET + 8,
                32,
            );
        }
        write_u64(input, CREATE_REPLAY_DATA_OFFSET + 40, next_nonce);
        copy_span(
            input,
            CREATE_INSTRUCTION_OFFSET,
            CREATE_REGISTRATION_DATA_OFFSET,
            REGISTERED_DATA_BYTES as usize,
        );
        0
    }
}

#[inline(never)]
unsafe fn execute_inline(input: *mut u8) -> u64 {
    // SAFETY: the loader extent/alignment assumption is named above. All
    // semantic bytes and write authority are checked before the four writes.
    unsafe {
        if read_u64(input, AUTHORITY_OFFSET) != AUTHORITY_FRAME_WORD
            || read_u64(input, AUTHORITY_OFFSET + 80) != 0
            || !exact_state_frame(
                input,
                SELLER_REPLAY_OFFSET,
                SELLER_REPLAY_DATA_OFFSET,
                REPLAY_FRAME_WORD,
                REPLAY_DATA_BYTES,
                REPLAY_MAGIC_WORD,
                PROGRAM_ID_OFFSET,
            )
            || !exact_state_frame(
                input,
                BUYER_REPLAY_OFFSET,
                BUYER_REPLAY_DATA_OFFSET,
                REPLAY_FRAME_WORD,
                REPLAY_DATA_BYTES,
                REPLAY_MAGIC_WORD,
                PROGRAM_ID_OFFSET,
            )
            || !exact_state_frame(
                input,
                SELLER_POSITION_OFFSET,
                SELLER_POSITION_DATA_OFFSET,
                POSITION_FRAME_WORD,
                POSITION_DATA_BYTES,
                POSITION_MAGIC_WORD,
                PROGRAM_ID_OFFSET,
            )
            || !exact_state_frame(
                input,
                BUYER_POSITION_OFFSET,
                BUYER_POSITION_DATA_OFFSET,
                POSITION_FRAME_WORD,
                POSITION_DATA_BYTES,
                POSITION_MAGIC_WORD,
                PROGRAM_ID_OFFSET,
            )
            || !accounts_are_distinct_at(
                input,
                [
                    AUTHORITY_OFFSET,
                    SELLER_REPLAY_OFFSET,
                    BUYER_REPLAY_OFFSET,
                    SELLER_POSITION_OFFSET,
                    BUYER_POSITION_OFFSET,
                ],
            )
            || read_u64(input, INSTRUCTION_LENGTH_OFFSET) != INSTRUCTION_BYTES
        {
            return ERROR;
        }

        let seller_outcome = read_u64(input, SELLER_POSITION_DATA_OFFSET + 40);
        let buyer_outcome = read_u64(input, BUYER_POSITION_DATA_OFFSET + 40);
        if seller_outcome > u64::from(u32::MAX)
            || seller_outcome != buyer_outcome
            || read_u64(input, INSTRUCTION_OFFSET) != PLAN_HEADER_WORD
            || read_u64(input, INSTRUCTION_OFFSET + 8) != EFFECT_0_TAG
            || read_u64(input, INSTRUCTION_OFFSET + 24) != EFFECT_1_TAG
            || (read_u64(input, INSTRUCTION_OFFSET + 40) & 0xffff_ffff) != EFFECT_2_TAG
            || (read_u64(input, INSTRUCTION_OFFSET + 40) >> 32) != seller_outcome
            || (read_u64(input, INSTRUCTION_OFFSET + 56) & 0xffff_ffff) != EFFECT_3_TAG
            || (read_u64(input, INSTRUCTION_OFFSET + 56) >> 32) != seller_outcome
        {
            return ERROR;
        }

        let seller_nonce = read_u64(input, SELLER_REPLAY_DATA_OFFSET + 40);
        let buyer_nonce = read_u64(input, BUYER_REPLAY_DATA_OFFSET + 40);
        let seller_claims = read_u64(input, SELLER_POSITION_DATA_OFFSET + 48);
        let buyer_claims = read_u64(input, BUYER_POSITION_DATA_OFFSET + 48);
        let next_seller = match add_checked(seller_nonce, 1) {
            Some(value) => value,
            None => return ERROR,
        };
        let next_buyer = match add_checked(buyer_nonce, 1) {
            Some(value) => value,
            None => return ERROR,
        };
        let plan_seller_nonce = read_u64(input, INSTRUCTION_OFFSET + 16);
        let plan_buyer_nonce = read_u64(input, INSTRUCTION_OFFSET + 32);
        let claim_debit = read_u64(input, INSTRUCTION_OFFSET + 48);
        let claim_credit = read_u64(input, INSTRUCTION_OFFSET + 64);

        if plan_seller_nonce != next_seller
            || plan_buyer_nonce != next_buyer
            || claim_debit != claim_credit
            || seller_claims < claim_debit
        {
            return ERROR;
        }
        let next_buyer_claims = match add_checked(buyer_claims, claim_credit) {
            Some(value) => value,
            None => return ERROR,
        };

        write_u64(input, SELLER_REPLAY_DATA_OFFSET + 40, next_seller);
        write_u64(input, BUYER_REPLAY_DATA_OFFSET + 40, next_buyer);
        write_u64(
            input,
            SELLER_POSITION_DATA_OFFSET + 48,
            seller_claims - claim_debit,
        );
        write_u64(input, BUYER_POSITION_DATA_OFFSET + 48, next_buyer_claims);
        0
    }
}

#[inline(always)]
unsafe fn exact_registered_frame(
    input: *mut u8,
    account_offset: usize,
    data_offset: usize,
) -> bool {
    // SAFETY: propagated from the exact generated registered loader profile.
    unsafe {
        read_u64(input, account_offset) == REGISTERED_FRAME_WORD
            && read_u64(input, account_offset + 80) == REGISTERED_DATA_BYTES
            && equal_32(input, account_offset + 40, REGISTERED_PROGRAM_ID_OFFSET)
            && equal_32(input, AUTHORITY_OFFSET + 8, data_offset + 16)
            && read_u64(input, data_offset) == REGISTERED_MAGIC_WORD
    }
}

#[inline(always)]
unsafe fn decode_registered(input: *mut u8, data_offset: usize) -> Option<RegisteredIntentStateV1> {
    // SAFETY: exact_registered_frame establishes the 232-byte extent before
    // this helper is called.
    let bytes = unsafe {
        core::slice::from_raw_parts(
            input.add(data_offset).cast_const(),
            REGISTERED_DATA_BYTES as usize,
        )
    };
    RegisteredIntentStateV1::decode(bytes).ok()
}

#[inline(never)]
unsafe fn execute_registered(input: *mut u8) -> u64 {
    // SAFETY: all offsets and frame words are generated from the registered
    // profile. No state write occurs until every decoder and arithmetic check
    // below has succeeded.
    unsafe {
        if read_u64(input, AUTHORITY_OFFSET) != AUTHORITY_FRAME_WORD
            || read_u64(input, AUTHORITY_OFFSET + 80) != 0
            || !exact_registered_frame(
                input,
                REGISTERED_SELLER_OFFSET,
                REGISTERED_SELLER_DATA_OFFSET,
            )
            || !exact_registered_frame(input, REGISTERED_BUYER_OFFSET, REGISTERED_BUYER_DATA_OFFSET)
            || !exact_state_frame(
                input,
                REGISTERED_SELLER_POSITION_OFFSET,
                REGISTERED_SELLER_POSITION_DATA_OFFSET,
                POSITION_FRAME_WORD,
                POSITION_DATA_BYTES,
                POSITION_MAGIC_WORD,
                REGISTERED_PROGRAM_ID_OFFSET,
            )
            || !exact_state_frame(
                input,
                REGISTERED_BUYER_POSITION_OFFSET,
                REGISTERED_BUYER_POSITION_DATA_OFFSET,
                POSITION_FRAME_WORD,
                POSITION_DATA_BYTES,
                POSITION_MAGIC_WORD,
                REGISTERED_PROGRAM_ID_OFFSET,
            )
            || !accounts_are_distinct_at(
                input,
                [
                    AUTHORITY_OFFSET,
                    REGISTERED_SELLER_OFFSET,
                    REGISTERED_BUYER_OFFSET,
                    REGISTERED_SELLER_POSITION_OFFSET,
                    REGISTERED_BUYER_POSITION_OFFSET,
                ],
            )
            || read_u64(input, REGISTERED_INSTRUCTION_LENGTH_OFFSET) != REGISTERED_INSTRUCTION_BYTES
            || read_u64(input, REGISTERED_INSTRUCTION_OFFSET) != REGISTERED_INSTRUCTION_HEADER_WORD
        {
            return ERROR;
        }

        let seller = match decode_registered(input, REGISTERED_SELLER_DATA_OFFSET) {
            Some(state) => state,
            None => return ERROR,
        };
        let buyer = match decode_registered(input, REGISTERED_BUYER_DATA_OFFSET) {
            Some(state) => state,
            None => return ERROR,
        };
        let seller_outcome = read_u64(input, REGISTERED_SELLER_POSITION_DATA_OFFSET + 40);
        let buyer_outcome = read_u64(input, REGISTERED_BUYER_POSITION_DATA_OFFSET + 40);
        if seller.intent.side != 0
            || buyer.intent.side != 1
            || seller.intent.outcome != buyer.intent.outcome
            || seller.intent.market != buyer.intent.market
            || seller.intent.generation != buyer.intent.generation
            || seller.maker == [0; 32]
            || buyer.maker == [0; 32]
            || seller.maker == buyer.maker
            || seller_outcome != u64::from(seller.intent.outcome)
            || buyer_outcome != seller_outcome
        {
            return ERROR;
        }

        let fill = read_u64(input, REGISTERED_INSTRUCTION_OFFSET + 8);
        let seller_next = match registered_successor(seller, fill) {
            Some(state) => state,
            None => return ERROR,
        };
        let buyer_next = match registered_successor(buyer, fill) {
            Some(state) => state,
            None => return ERROR,
        };
        let seller_claims = read_u64(input, REGISTERED_SELLER_POSITION_DATA_OFFSET + 48);
        let buyer_claims = read_u64(input, REGISTERED_BUYER_POSITION_DATA_OFFSET + 48);
        if seller_claims < fill {
            return ERROR;
        }
        let buyer_claims_next = match add_checked(buyer_claims, fill) {
            Some(value) => value,
            None => return ERROR,
        };

        write_u8(input, REGISTERED_SELLER_DATA_OFFSET + 10, seller_next.phase);
        write_u64(
            input,
            REGISTERED_SELLER_DATA_OFFSET + 216,
            seller_next.remaining,
        );
        write_u64(
            input,
            REGISTERED_SELLER_DATA_OFFSET + 224,
            seller_next.sequence,
        );
        write_u8(input, REGISTERED_BUYER_DATA_OFFSET + 10, buyer_next.phase);
        write_u64(
            input,
            REGISTERED_BUYER_DATA_OFFSET + 216,
            buyer_next.remaining,
        );
        write_u64(
            input,
            REGISTERED_BUYER_DATA_OFFSET + 224,
            buyer_next.sequence,
        );
        write_u64(
            input,
            REGISTERED_SELLER_POSITION_DATA_OFFSET + 48,
            seller_claims - fill,
        );
        write_u64(
            input,
            REGISTERED_BUYER_POSITION_DATA_OFFSET + 48,
            buyer_claims_next,
        );
        0
    }
}

#[inline(always)]
unsafe fn exact_terminal_registered_frame(input: *mut u8) -> bool {
    // SAFETY: propagated from the generated two-account terminal profile.
    unsafe {
        read_u64(input, TERMINAL_REGISTRATION_OFFSET) == REGISTERED_FRAME_WORD
            && read_u64(input, TERMINAL_REGISTRATION_OFFSET + 80) == REGISTERED_DATA_BYTES
            && equal_32(
                input,
                TERMINAL_REGISTRATION_OFFSET + 40,
                TERMINAL_PROGRAM_ID_OFFSET,
            )
            && equal_32(
                input,
                AUTHORITY_OFFSET + 8,
                TERMINAL_REGISTRATION_DATA_OFFSET + 16,
            )
            && read_u64(input, TERMINAL_REGISTRATION_DATA_OFFSET) == REGISTERED_MAGIC_WORD
    }
}

#[inline(always)]
fn terminal_successor(
    state: RegisteredIntentStateV1,
    expected_sequence: u64,
    phase: u8,
) -> Option<u64> {
    if state.phase != 0
        || state.remaining == 0
        || state.remaining > state.intent.maximum_fill
        || state.sequence != expected_sequence
        || (phase != 2 && phase != 3)
    {
        return None;
    }
    add_checked(state.sequence, 1)
}

#[inline(never)]
unsafe fn execute_registered_terminal(input: *mut u8) -> u64 {
    // SAFETY: the exact two-account profile is checked before decoding or
    // writing the registration. The single write set is committed only after
    // sequence, phase, and arithmetic admission succeeds.
    unsafe {
        if read_u64(input, AUTHORITY_OFFSET) != AUTHORITY_FRAME_WORD
            || read_u64(input, AUTHORITY_OFFSET + 80) != 0
            || !exact_terminal_registered_frame(input)
            || equal_32(
                input,
                AUTHORITY_OFFSET + 8,
                TERMINAL_REGISTRATION_OFFSET + 8,
            )
            || read_u64(input, TERMINAL_INSTRUCTION_LENGTH_OFFSET) != TERMINAL_INSTRUCTION_BYTES
        {
            return ERROR;
        }
        let header = read_u64(input, TERMINAL_INSTRUCTION_OFFSET);
        let phase = if header == TERMINAL_CANCEL_HEADER_WORD {
            2
        } else if header == TERMINAL_EXPIRE_HEADER_WORD {
            3
        } else {
            return ERROR;
        };
        let state = match decode_registered(input, TERMINAL_REGISTRATION_DATA_OFFSET) {
            Some(state) => state,
            None => return ERROR,
        };
        let expected_sequence = read_u64(input, TERMINAL_INSTRUCTION_OFFSET + 8);
        let next_sequence = match terminal_successor(state, expected_sequence, phase) {
            Some(sequence) => sequence,
            None => return ERROR,
        };
        write_u8(input, TERMINAL_REGISTRATION_DATA_OFFSET + 10, phase);
        write_u64(
            input,
            TERMINAL_REGISTRATION_DATA_OFFSET + 224,
            next_sequence,
        );
        0
    }
}

#[cfg(test)]
mod tests {
    extern crate std;

    use super::*;
    use dclutch_direct_codec::CompactIntentV1;

    fn state(side: u8, lifecycle: u8) -> RegisteredIntentStateV1 {
        RegisteredIntentStateV1 {
            phase: 0,
            controller: [7; 32],
            maker: [8_u8.wrapping_add(side); 32],
            intent: CompactIntentV1 {
                side,
                outcome: 1,
                lifecycle,
                market: [4; 32],
                generation: 3,
                nonce: 9,
                valid_from: 0,
                valid_through: u64::MAX,
                maximum_fill: 2_000,
                limit_price: 500_000,
                fee_basis_points: 25,
                collateral_account: [5_u8.wrapping_add(side); 32],
            },
            remaining: 2_000,
            sequence: 4,
        }
    }

    #[test]
    fn generated_program_advances_each_registered_policy() {
        let gtc = registered_successor(state(0, 2), 500).expect("GTC transition");
        assert_eq!(gtc.remaining, 1_500);
        assert_eq!(gtc.sequence, 5);
        assert_eq!(gtc.phase, 0);

        let ioc = registered_successor(state(1, 1), 500).expect("IOC transition");
        assert_eq!(ioc.remaining, 1_500);
        assert_eq!(ioc.sequence, 5);
        assert_eq!(ioc.phase, 2);

        let fok = registered_successor(state(0, 0), 2_000).expect("FOK transition");
        assert_eq!(fok.remaining, 0);
        assert_eq!(fok.sequence, 5);
        assert_eq!(fok.phase, 1);
    }

    #[test]
    fn generated_program_refuses_invalid_or_replayed_state() {
        assert!(registered_successor(state(0, 0), 500).is_none());
        assert!(registered_successor(state(0, 2), 0).is_none());
        let mut closed = state(0, 2);
        closed.phase = 2;
        assert!(registered_successor(closed, 500).is_none());
        let mut impossible = state(0, 2);
        impossible.remaining = 2_001;
        assert!(registered_successor(impossible, 500).is_none());
        let mut overflow = state(0, 2);
        overflow.sequence = u64::MAX;
        assert!(registered_successor(overflow, 500).is_none());
    }

    #[test]
    fn registration_consumes_global_nonce_once() {
        let mut pending = state(0, 2);
        pending.intent.nonce = 0;
        pending.sequence = 0;
        assert_eq!(registration_successor(pending, 0), Some(1));
        assert_eq!(registration_successor(pending, 1), None);

        let mut empty = pending;
        empty.intent.maximum_fill = 0;
        empty.remaining = 0;
        assert_eq!(registration_successor(empty, 0), None);
        let mut noncanonical = pending;
        noncanonical.remaining -= 1;
        assert_eq!(registration_successor(noncanonical, 0), None);
        let mut overflow = pending;
        overflow.intent.nonce = u64::MAX;
        assert_eq!(registration_successor(overflow, u64::MAX), None);
    }

    #[test]
    fn terminal_mutations_are_sequence_pinned() {
        let open = state(0, 2);
        assert_eq!(terminal_successor(open, 4, 2), Some(5));
        assert_eq!(terminal_successor(open, 4, 3), Some(5));
        assert_eq!(terminal_successor(open, 3, 2), None);
        assert_eq!(terminal_successor(open, 4, 1), None);
        let mut terminal = open;
        terminal.phase = 2;
        assert_eq!(terminal_successor(terminal, 4, 2), None);
        let mut overflow = open;
        overflow.sequence = u64::MAX;
        assert_eq!(terminal_successor(overflow, u64::MAX, 2), None);
    }
}
