#![cfg_attr(target_os = "solana", no_std)]

//! Alias-simple exact-account SBF executor for the Lean-owned claim plan.

include!("generated_profile.rs");

const ERROR: u64 = 5_u64 << 32;

#[cfg(target_os = "solana")]
#[panic_handler]
fn panic(_info: &core::panic::PanicInfo<'_>) -> ! {
    loop {}
}

#[inline(always)]
unsafe fn read_u64(input: *mut u8, offset: usize) -> u64 {
    // SAFETY: every caller relies on the entrypoint's named loader-extent and
    // alignment boundary and supplies a Lean-generated in-bounds offset.
    unsafe { core::ptr::read(input.add(offset).cast::<u64>()) }
}

#[inline(always)]
unsafe fn write_u64(input: *mut u8, offset: usize, value: u64) {
    // SAFETY: every caller writes an aligned field in a validated writable
    // account frame described by the Lean-generated profile.
    unsafe { core::ptr::write(input.add(offset).cast::<u64>(), value) };
}

#[inline(always)]
unsafe fn equal_32(input: *mut u8, left: usize, right: usize) -> bool {
    // SAFETY: propagated from the function boundary and exact profile offsets.
    unsafe {
        read_u64(input, left) == read_u64(input, right)
            && read_u64(input, left + 8) == read_u64(input, right + 8)
            && read_u64(input, left + 16) == read_u64(input, right + 16)
            && read_u64(input, left + 24) == read_u64(input, right + 24)
    }
}

#[inline(always)]
fn add_checked(left: u64, right: u64) -> Option<u64> {
    let result = left.wrapping_add(right);
    if result < left {
        None
    } else {
        Some(result)
    }
}

#[inline(always)]
unsafe fn exact_state_frame(
    input: *mut u8,
    account_offset: usize,
    data_offset: usize,
    frame_word: u64,
    data_bytes: u64,
    magic_word: u64,
) -> bool {
    // SAFETY: propagated from the entrypoint's loader boundary. The offsets are
    // generated by Lean and describe fields within the same account frame.
    unsafe {
        read_u64(input, account_offset) == frame_word
            && read_u64(input, account_offset + 80) == data_bytes
            && equal_32(input, account_offset + 40, PROGRAM_ID_OFFSET)
            && equal_32(input, AUTHORITY_OFFSET + 8, data_offset + 8)
            && read_u64(input, data_offset) == magic_word
    }
}

#[inline(always)]
unsafe fn accounts_are_distinct(input: *mut u8) -> bool {
    let offsets = [
        AUTHORITY_OFFSET,
        SELLER_REPLAY_OFFSET,
        BUYER_REPLAY_OFFSET,
        SELLER_POSITION_OFFSET,
        BUYER_POSITION_OFFSET,
    ];
    let mut left = 0;
    while left < offsets.len() {
        let mut right = left + 1;
        while right < offsets.len() {
            // SAFETY: each offset identifies a validated loader account frame.
            if unsafe { equal_32(input, offsets[left] + 8, offsets[right] + 8) } {
                return false;
            }
            right += 1;
        }
        left += 1;
    }
    true
}

/// Execute one exact controller-authorized four-effect claim plan.
///
/// Replay nonces and Position claims each have one canonical account owner.
/// The controller has already authenticated their profile/maker PDA coordinates;
/// this child independently checks controller authority, program ownership,
/// exact state shapes, the ordered effect plan, and arithmetic.
///
/// # Safety
///
/// The pinned Solana loader must provide a non-null, aligned ABI-v1 buffer with
/// the complete extent implied by the Lean-generated exact-account profile.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn entrypoint(input: *mut u8) -> u64 {
    if input.is_null() {
        return ERROR;
    }

    // SAFETY: the loader extent/alignment assumption is named above. All
    // semantic bytes and write authority are checked before the four writes.
    unsafe {
        if read_u64(input, ACCOUNT_COUNT_OFFSET) != 5
            || read_u64(input, AUTHORITY_OFFSET) != AUTHORITY_FRAME_WORD
            || read_u64(input, AUTHORITY_OFFSET + 80) != 0
            || !exact_state_frame(
                input,
                SELLER_REPLAY_OFFSET,
                SELLER_REPLAY_DATA_OFFSET,
                REPLAY_FRAME_WORD,
                REPLAY_DATA_BYTES,
                REPLAY_MAGIC_WORD,
            )
            || !exact_state_frame(
                input,
                BUYER_REPLAY_OFFSET,
                BUYER_REPLAY_DATA_OFFSET,
                REPLAY_FRAME_WORD,
                REPLAY_DATA_BYTES,
                REPLAY_MAGIC_WORD,
            )
            || !exact_state_frame(
                input,
                SELLER_POSITION_OFFSET,
                SELLER_POSITION_DATA_OFFSET,
                POSITION_FRAME_WORD,
                POSITION_DATA_BYTES,
                POSITION_MAGIC_WORD,
            )
            || !exact_state_frame(
                input,
                BUYER_POSITION_OFFSET,
                BUYER_POSITION_DATA_OFFSET,
                POSITION_FRAME_WORD,
                POSITION_DATA_BYTES,
                POSITION_MAGIC_WORD,
            )
            || !accounts_are_distinct(input)
            || read_u64(input, INSTRUCTION_LENGTH_OFFSET) != INSTRUCTION_BYTES
        {
            return ERROR;
        }

        let seller_outcome = read_u64(input, SELLER_POSITION_DATA_OFFSET + 40);
        let buyer_outcome = read_u64(input, BUYER_POSITION_DATA_OFFSET + 40);
        if seller_outcome > u64::from(u32::MAX)
            || seller_outcome != buyer_outcome
            || read_u64(input, INSTRUCTION_OFFSET) != PLAN_HEADER_WORD
            || read_u64(input, INSTRUCTION_OFFSET + 8) != EFFECT_0_TAG
            || read_u64(input, INSTRUCTION_OFFSET + 24) != EFFECT_1_TAG
            || (read_u64(input, INSTRUCTION_OFFSET + 40) & 0xffff_ffff) != EFFECT_2_TAG
            || (read_u64(input, INSTRUCTION_OFFSET + 40) >> 32) != seller_outcome
            || (read_u64(input, INSTRUCTION_OFFSET + 56) & 0xffff_ffff) != EFFECT_3_TAG
            || (read_u64(input, INSTRUCTION_OFFSET + 56) >> 32) != seller_outcome
        {
            return ERROR;
        }

        let seller_nonce = read_u64(input, SELLER_REPLAY_DATA_OFFSET + 40);
        let buyer_nonce = read_u64(input, BUYER_REPLAY_DATA_OFFSET + 40);
        let seller_claims = read_u64(input, SELLER_POSITION_DATA_OFFSET + 48);
        let buyer_claims = read_u64(input, BUYER_POSITION_DATA_OFFSET + 48);
        let next_seller = match add_checked(seller_nonce, 1) {
            Some(value) => value,
            None => return ERROR,
        };
        let next_buyer = match add_checked(buyer_nonce, 1) {
            Some(value) => value,
            None => return ERROR,
        };
        let plan_seller_nonce = read_u64(input, INSTRUCTION_OFFSET + 16);
        let plan_buyer_nonce = read_u64(input, INSTRUCTION_OFFSET + 32);
        let claim_debit = read_u64(input, INSTRUCTION_OFFSET + 48);
        let claim_credit = read_u64(input, INSTRUCTION_OFFSET + 64);

        if plan_seller_nonce != next_seller
            || plan_buyer_nonce != next_buyer
            || claim_debit != claim_credit
            || seller_claims < claim_debit
        {
            return ERROR;
        }
        let next_buyer_claims = match add_checked(buyer_claims, claim_credit) {
            Some(value) => value,
            None => return ERROR,
        };

        write_u64(input, SELLER_REPLAY_DATA_OFFSET + 40, next_seller);
        write_u64(input, BUYER_REPLAY_DATA_OFFSET + 40, next_buyer);
        write_u64(
            input,
            SELLER_POSITION_DATA_OFFSET + 48,
            seller_claims - claim_debit,
        );
        write_u64(input, BUYER_POSITION_DATA_OFFSET + 48, next_buyer_claims);
        0
    }
}
