// @generated by formal/dclutch-semantics/EmitGeneralControllerRequestV3Rust.lean; do not edit.
pub(crate) const REQUEST_V3_ABI_VERSION: u16 = 3;
pub(crate) const REQUEST_V3_BYTES: usize = 64;
pub(crate) const REQUEST_V3_MAGIC: [u8; 8] = [
    0x44, 0x43, 0x47, 0x52, 0x45, 0x51, 0x30, 0x33,
];
pub(crate) const REQUEST_V3_ACTION_OFFSET: usize = 10;
pub(crate) const REQUEST_V3_MANIFEST_ORDER_OFFSET: usize = 11;
pub(crate) const REQUEST_V3_EXPECTED_REVISION_OFFSET: usize = 16;
pub(crate) const REQUEST_V3_SUBJECT_ID_OFFSET: usize = 24;
pub(crate) const REQUEST_V3_PAGE_INDEX_OFFSET: usize = 56;
pub(crate) const REQUEST_V3_EXECUTION_INDEX_OFFSET: usize = 60;
pub(crate) const REQUEST_V3_PRIMARY_BUMP_OFFSET: usize = 61;
pub(crate) const REQUEST_V3_SECONDARY_BUMP_OFFSET: usize = 62;
pub(crate) const REQUEST_V3_RESULT_BUMP_OFFSET: usize = 63;
