// @generated by formal/dclutch-semantics/EmitClaimsConservationV1Rust.lean; do not edit.
/// Implemented schema version.
pub const CLAIMS_CONSERVATION_SCHEMA_VERSION_V1: u16 = 1;
/// Exact canonical request width.
pub const CLAIMS_CONSERVATION_REQUEST_BYTES_V1: usize = 592;
/// Canonical outer-route request magic: `DCLCNS01`.
pub const CLAIMS_CONSERVATION_REQUEST_MAGIC_V1: [u8; 8] =
    [0x44, 0x43, 0x4c, 0x43, 0x4e, 0x53, 0x30, 0x31];
/// The split direction's one-byte selector.
pub const CLAIMS_CONSERVATION_SPLIT_TAG_V1: u8 = 0;
/// The merge direction's one-byte selector.
pub const CLAIMS_CONSERVATION_MERGE_TAG_V1: u8 = 1;
pub(crate) const MAGIC_OFFSET: usize = 0;
pub(crate) const VERSION_OFFSET: usize = 8;
pub(crate) const DIRECTION_OFFSET: usize = 10;
pub(crate) const HEADER_RESERVED_OFFSET: usize = 11;
pub(crate) const REALM_OFFSET: usize = 16;
pub(crate) const MARKET_OFFSET: usize = 48;
pub(crate) const RELEASE_SET_OFFSET: usize = 80;
pub(crate) const CUSTODY_CONTEXT_OFFSET: usize = 112;
pub(crate) const AGGREGATE_OFFSET: usize = 144;
pub(crate) const POSITION_OFFSET: usize = 176;
pub(crate) const OWNER_OFFSET: usize = 208;
pub(crate) const EXTERNAL_COLLATERAL_OFFSET: usize = 240;
pub(crate) const HOARD_VAULT_OFFSET: usize = 272;
pub(crate) const MINT_OFFSET: usize = 304;
pub(crate) const TOKEN_PROGRAM_OFFSET: usize = 336;
pub(crate) const CLAIMS_PROGRAM_OFFSET: usize = 368;
pub(crate) const PRODUCT_RECORD_DIGEST_OFFSET: usize = 400;
pub(crate) const LINKED_BASIS_RECORD_DIGEST_OFFSET: usize = 432;
pub(crate) const SEMANTIC_BASIS_ID_OFFSET: usize = 464;
pub(crate) const GENERATION_OFFSET: usize = 496;
pub(crate) const QUANTITY_OFFSET: usize = 504;
pub(crate) const BASIS_SCALE_OFFSET: usize = 512;
pub(crate) const COLLATERAL_ATOMS_OFFSET: usize = 520;
pub(crate) const EXPECTED_MARKET_REVISION_OFFSET: usize = 528;
pub(crate) const EXPECTED_POSITION_REVISION_OFFSET: usize = 536;
pub(crate) const EXPECTED_CUSTODY_REVISION_OFFSET: usize = 544;
pub(crate) const PRE_EXTERNAL_AMOUNT_OFFSET: usize = 552;
pub(crate) const POST_EXTERNAL_AMOUNT_OFFSET: usize = 560;
pub(crate) const PRE_HOARD_AMOUNT_OFFSET: usize = 568;
pub(crate) const POST_HOARD_AMOUNT_OFFSET: usize = 576;
pub(crate) const CLAIM_COUNT_OFFSET: usize = 584;
pub(crate) const TAIL_RESERVED_OFFSET: usize = 588;
pub(crate) const HEADER_RESERVED_BYTES: usize = 5;
pub(crate) const TAIL_RESERVED_BYTES: usize = 4;
