import DClutchSemantics.IR
import DClutchSemantics.Direct
import DClutchSemantics.DirectLifecycle
import DClutchSemantics.DirectLifecycleProgram
import DClutchSemantics.DirectLifecycleAbi
import DClutchSemantics.RegisteredPhysical
import DClutchSemantics.RegisteredControllerAbi
import DClutchSemantics.DirectProofs
import DClutchSemantics.Codec
import DClutchSemantics.Examples
import DClutchSemantics.SbfProfile
import DClutchSemantics.Physical
import DClutchSemantics.ClaimSbfProfile
import DClutchSemantics.TransitionVM
import DClutchSemantics.TransitionVMV2
import DClutchSemantics.DirectProgram
import DClutchSemantics.CompiledPhysical
import DClutchSemantics.DirectControllerCodec
import DClutchSemantics.EconomicKernel
import DClutchSemantics.EconomicExamples
import DClutchSemantics.EconomicCodec
import DClutchSemantics.ExecutionRelease
import DClutchSemantics.SourceResolution
import DClutchSemantics.SourceResolutionAbi
import DClutchSemantics.SourceMaterialV2Abi
import DClutchSemantics.SourceRecoveryPolicyV2Abi
import DClutchSemantics.SourceResolutionStateV2Abi
import DClutchSemantics.SourceResolutionTerminalV2Abi
import DClutchSemantics.GeneralClearing
import DClutchSemantics.GeneralClearingExamples
import DClutchSemantics.GeneralV5Assurance
import DClutchSemantics.GeneralControllerAbi
import DClutchSemantics.GeneralConfigAbi
import DClutchSemantics.GeneralConfigV3Abi
import DClutchSemantics.ProductPayoff
import DClutchSemantics.ProductPayoffExamples
import DClutchSemantics.ProductPayoffAbi
import DClutchSemantics.LiabilityBasisV2
import DClutchSemantics.ClaimsRepresentation
import DClutchSemantics.ClaimsRepresentationExamples
import DClutchSemantics.DealerLiquidity
import DClutchSemantics.DealerLiquidityExamples
import DClutchSemantics.DealerScenarioCollateral
import DClutchSemantics.DealerScenarioSolvency
import DClutchSemantics.DealerTradingProfile
import DClutchSemantics.Series
import DClutchSemantics.SeriesExamples
import DClutchSemantics.MarketCore
import DClutchSemantics.MarketCoreExamples
import DClutchSemantics.MarketRetirementV1Abi
import DClutchSemantics.CapabilityProgramV3Abi
import DClutchSemantics.CapabilityProgramV4Abi
import DClutchSemantics.RequestProfileAbi
import DClutchSemantics.RequestProfileV4Abi
import DClutchSemantics.StateLifecyclePolicyV5Abi
import DClutchSemantics.AccountProfileV2Profile13
import DClutchSemantics.AccountProfileV2Profile14
import DClutchSemantics.RepresentationCompositionV3Abi
import DClutchSemantics.ProductRepresentationExposureV3Abi
import DClutchSemantics.EffectProgramV4Abi
import DClutchSemantics.RationalCrossDomainV3

/-!
Fresh Lean-owned semantics for dClutch's compact protocol specializer.

This package intentionally has no dependency on the neighboring research
repositories or on the Rust implementation.  The Rust implementation is a
differential oracle, not a source of formal definitions.
-/
