import DClutchSemantics.DirectControllerCodec

open DClutch
open DClutch.DirectControllerCodec

def rustByte (byte : UInt8) : String := s!"0x{Codec.byteHex byte}"

def emitByteArray (name : String) (bytes : List UInt8) : IO Unit := do
  IO.println s!"pub(crate) const {name}: [u8; {bytes.length}] = [{String.intercalate ", " (bytes.map rustByte)}];"

def intentRustField : IntentField → String
  | .side => "side"
  | .outcome => "outcome"
  | .lifecycle => "lifecycle"
  | .market => "market"
  | .generation => "generation"
  | .nonce => "nonce"
  | .validFrom => "valid_from"
  | .validThrough => "valid_through"
  | .maximumFill => "maximum_fill"
  | .limitPrice => "limit_price"
  | .feeBasisPoints => "fee_basis_points"
  | .collateralAccount => "collateral_account"

def intentDecodeExpression (field : IntentField) : String :=
  let offset := s!"$crate::generated_layout::{IntentField.rustName field}"
  match field with
  | .side | .outcome | .lifecycle => s!"$crate::byte($input, {offset})?"
  | .market | .collateralAccount => s!"$crate::array($input, {offset})?"
  | .feeBasisPoints => s!"$crate::u16_at($input, {offset})?"
  | _ => s!"$crate::u64_at($input, {offset})?"

def intentEncodeStatement (field : IntentField) : String :=
  let offset := s!"$crate::generated_layout::{IntentField.rustName field}"
  let value := s!"$value.{intentRustField field}"
  match field with
  | .side | .outcome | .lifecycle =>
      s!"$crate::put_byte(&mut $output, {offset}, {value})?;"
  | .market | .collateralAccount =>
      s!"$crate::put(&mut $output, {offset}, &{value})?;"
  | _ => s!"$crate::put(&mut $output, {offset}, &{value}.to_le_bytes())?;"

def controllerRustField : ControllerField → String
  | .controllerBump => "controller_bump"
  | .sellerReplayBump => "seller_replay_bump"
  | .buyerReplayBump => "buyer_replay_bump"
  | .sellerPositionBump => "seller_position_bump"
  | .buyerPositionBump => "buyer_position_bump"
  | .fill => "fill"
  | .executionPrice => "execution_price"
  | .seller => "seller"
  | .buyer => "buyer"

def controllerDecodeExpression (field : ControllerField) : String :=
  let offset := s!"$crate::generated_layout::{ControllerField.rustName field}"
  match field with
  | .controllerBump | .sellerReplayBump | .buyerReplayBump
  | .sellerPositionBump | .buyerPositionBump => s!"$crate::byte($input, {offset})?"
  | .fill | .executionPrice => s!"$crate::u64_at($input, {offset})?"
  | .seller | .buyer =>
      s!"$crate::CompactIntentV1::decode($crate::slice($input, {offset}, $crate::COMPACT_INTENT_BYTES)?)?"

def controllerEncodeStatement (field : ControllerField) : String :=
  let offset := s!"$crate::generated_layout::{ControllerField.rustName field}"
  let value := s!"$value.{controllerRustField field}"
  match field with
  | .controllerBump | .sellerReplayBump | .buyerReplayBump
  | .sellerPositionBump | .buyerPositionBump =>
      s!"$crate::put_byte(&mut $output, {offset}, {value})?;"
  | .fill | .executionPrice =>
      s!"$crate::put(&mut $output, {offset}, &{value}.to_le_bytes())?;"
  | .seller | .buyer =>
      s!"$crate::put(&mut $output, {offset}, &{value}.encode()?)?;"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitDirectCodecRust.lean; do not edit."
  IO.println s!"pub(crate) const ABI_VERSION: u16 = {version};"
  IO.println s!"pub(crate) const COMPACT_INTENT_BYTES_VALUE: usize = {compactIntentBytes};"
  IO.println s!"pub(crate) const CONTROLLER_INSTRUCTION_BYTES_VALUE: usize = {controllerInstructionBytes};"
  IO.println s!"pub(crate) const MAGIC_OFFSET: usize = {magicOffset};"
  IO.println s!"pub(crate) const VERSION_OFFSET: usize = {versionOffset};"
  emitByteArray "INTENT_MAGIC_BYTES" intentMagic
  emitByteArray "CONTROLLER_MAGIC_BYTES" controllerMagic
  for field in IntentField.all do
    IO.println s!"pub(crate) const {IntentField.rustName field}: usize = {IntentField.offset field};"
  IO.println s!"pub(crate) const INTENT_RESERVED_A_OFFSET: usize = {intentReservedAOffset};"
  IO.println s!"pub(crate) const INTENT_RESERVED_A_WIDTH: usize = {intentReservedAWidth};"
  IO.println s!"pub(crate) const INTENT_RESERVED_B_OFFSET: usize = {intentReservedBOffset};"
  IO.println s!"pub(crate) const INTENT_RESERVED_B_WIDTH: usize = {intentReservedBWidth};"
  for field in ControllerField.all do
    IO.println s!"pub(crate) const {ControllerField.rustName field}: usize = {ControllerField.offset field};"
  IO.println s!"pub(crate) const CONTROLLER_RESERVED_OFFSET: usize = {controllerReservedOffset};"
  IO.println s!"pub(crate) const CONTROLLER_RESERVED_WIDTH: usize = {controllerReservedWidth};"
  IO.println ""
  IO.println "macro_rules! decode_compact_intent_fields {"
  IO.println "    ($input:expr) => {"
  IO.println "        $crate::CompactIntentV1 {"
  for field in IntentField.all do
    IO.println s!"            {intentRustField field}: {intentDecodeExpression field},"
  IO.println "        }"
  IO.println "    };"
  IO.println "}"
  IO.println "pub(crate) use decode_compact_intent_fields;"
  IO.println ""
  IO.println "macro_rules! encode_compact_intent_fields {"
  IO.println "    ($output:ident, $value:ident) => {{"
  for field in IntentField.all do
    IO.println s!"        {intentEncodeStatement field}"
  IO.println "    }};"
  IO.println "}"
  IO.println "pub(crate) use encode_compact_intent_fields;"
  IO.println ""
  IO.println "macro_rules! decode_controller_fields {"
  IO.println "    ($input:expr) => {"
  IO.println "        $crate::ControllerInstructionV1 {"
  for field in ControllerField.all do
    IO.println s!"            {controllerRustField field}: {controllerDecodeExpression field},"
  IO.println "        }"
  IO.println "    };"
  IO.println "}"
  IO.println "pub(crate) use decode_controller_fields;"
  IO.println ""
  IO.println "macro_rules! encode_controller_fields {"
  IO.println "    ($output:ident, $value:ident) => {{"
  for field in ControllerField.all do
    IO.println s!"        {controllerEncodeStatement field}"
  IO.println "    }};"
  IO.println "}"
  IO.println "pub(crate) use encode_controller_fields;"
