import DClutchSemantics.RequestProfileAbi

/-! Emit RequestProfile ABI constants and generated agreement/refusal corpora. -/

open DClutch
open DClutch.RequestProfileAbi

def rustByte (byte : UInt8) : String := s!"0x{Codec.byteHex byte}"

def emitBytes (name : String) (value : List UInt8) : IO Unit := do
  IO.println s!"pub const {name}: [u8; {value.length}] = ["
  IO.println s!"    {String.intercalate ", " (value.map rustByte)},"
  IO.println "];"

def emitSlice (name : String) (value : List UInt8) : IO Unit := do
  IO.println s!"pub const {name}: &[u8] = &["
  IO.println s!"    {String.intercalate ", " (value.map rustByte)},"
  IO.println "];"

def emitCorpus (name : String) (corpus : List (List UInt8)) : IO Unit := do
  let width := (corpus.head?).map (·.length) |>.getD 0
  IO.println s!"pub const {name}: [[u8; {width}]; {corpus.length}] = ["
  for value in corpus do
    if value.length != width then
      throw <| IO.userError "request-profile refusal corpus has inconsistent widths"
    IO.println "    ["
    IO.println s!"        {String.intercalate ", " (value.map rustByte)},"
    IO.println "    ],"
  IO.println "];"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitRequestProfileAbiRust.lean; do not edit."
  IO.println s!"pub const REQUEST_PROFILE_HEADER_BYTES_V1: usize = {headerBytes};"
  IO.println s!"pub const REQUEST_PROFILE_OPERATION_BYTES_V1: usize = {operationBytes};"
  IO.println s!"pub const REQUEST_PROFILE_MAX_BYTES_V1: usize = {finalizedRecordMaxBytes};"
  IO.println s!"pub const REQUEST_PROFILE_SCHEMA_VERSION_V1: u16 = {schemaVersion};"
  IO.println s!"pub const REQUEST_PROFILE_ARTIFACT_PROFILE_V1: u16 = {artifactProfile};"
  emitSlice "REQUEST_PROFILE_SCHEMA_RELEASE_PREIMAGE_V1" schemaReleasePreimage
  emitBytes "REQUEST_PROFILE_SCHEMA_RELEASE_ID_V1" schemaReleaseId
  emitBytes "REQUEST_PROFILE_MAGIC_V1" magic
  for field in headerLayout do
    IO.println s!"pub const {HeaderField.rustName field.spec.name}: usize = {field.offset};"
  for field in operationLayout do
    IO.println s!"pub const {OperationField.rustName field.spec.name}: usize = {field.offset};"
  IO.println s!"pub const OP_REQUIRE_U8: u8 = {OperationKind.requireU8.tag.toNat};"
  IO.println s!"pub const OP_REQUIRE_U16: u8 = {OperationKind.requireU16.tag.toNat};"
  IO.println s!"pub const OP_REQUIRE_U32: u8 = {OperationKind.requireU32.tag.toNat};"
  IO.println s!"pub const OP_REQUIRE_U64: u8 = {OperationKind.requireU64.tag.toNat};"
  IO.println s!"pub const OP_REQUIRE_ZERO_RANGE: u8 = {OperationKind.requireZeroRange.tag.toNat};"
  IO.println s!"pub const OP_PROJECT_U8: u8 = {OperationKind.projectU8.tag.toNat};"
  IO.println s!"pub const OP_PROJECT_U16: u8 = {OperationKind.projectU16.tag.toNat};"
  IO.println s!"pub const OP_PROJECT_U32: u8 = {OperationKind.projectU32.tag.toNat};"
  IO.println s!"pub const OP_PROJECT_U64: u8 = {OperationKind.projectU64.tag.toNat};"
  IO.println s!"pub const OP_PROJECT_IDENTITY: u8 = {OperationKind.projectIdentity.tag.toNat};"
  IO.println "#[cfg(test)]"
  emitBytes "AGREEMENT_PROFILE_V1" (encodeProfile agreementProfile)
  IO.println "#[cfg(test)]"
  emitBytes "AGREEMENT_REQUEST_TAIL2_V1" agreementRequestTail2
  IO.println "#[cfg(test)]"
  emitCorpus "PROFILE_REFUSAL_CORPUS_V1" profileRefusalCorpus
  IO.println "#[cfg(test)]"
  emitCorpus "REQUEST_REFUSAL_CORPUS_TAIL2_V1" requestRefusalCorpusTail2
  IO.println "#[cfg(test)]"
  emitBytes "OVERSIZED_PROFILE_V1" oversizedProfileBytes
