import DClutchSemantics.ProductGradedBasisAdmissionV3Abi

open DClutch DClutch.ProductGradedBasisAdmissionV3Abi

def rustByte (byte : UInt8) : String := s!"0x{Codec.byteHex byte}"

def emitBytes (name : String) (value : List UInt8) : IO Unit := do
  IO.println "#[rustfmt::skip]"
  IO.println s!"pub const {name}: [u8; {value.length}] = ["
  for line in List.range ((value.length + 15) / 16) do
    let chunk := (value.drop (line * 16)).take 16
    IO.println s!"    {String.intercalate ", " (chunk.map rustByte)},"
  IO.println "];"

def emitSlice (name : String) (value : List UInt8) : IO Unit := do
  IO.println "#[rustfmt::skip]"
  IO.println s!"pub const {name}: &[u8] = &["
  IO.println s!"    {String.intercalate ", " (value.map rustByte)},"
  IO.println "];"

def emitOffsets {name : Type} (layout : List (AbiSchema.PlacedField name))
    (rustName : name → String) : IO Unit := do
  for field in layout do
    IO.println s!"pub const {rustName field.spec.name}: usize = {field.offset};"

def main : IO Unit := do
  IO.println "// @generated by EmitProductGradedBasisAdmissionV3AbiRust.lean; do not edit."
  IO.println s!"pub const APPROXIMATION_CERTIFICATE_BYTES_V3: usize = {certificateBytes};"
  IO.println s!"pub const GRADED_BASIS_ADMISSION_BYTES_V3: usize = {admissionBytes};"
  IO.println s!"pub const GRADED_BASIS_REGISTRY_SCHEMA_VERSION_V3: u16 = {schemaVersion};"
  emitBytes "APPROXIMATION_CERTIFICATE_MAGIC_V3" certificateMagic
  emitBytes "GRADED_BASIS_ADMISSION_MAGIC_V3" admissionMagic
  emitSlice "GRADED_BASIS_RECORD_SCHEMA_PREIMAGE_V3" basisSchemaPreimage
  emitBytes "GRADED_BASIS_RECORD_SCHEMA_ID_V3" basisSchemaId
  emitSlice "GRADED_BASIS_CERTIFICATE_SCHEMA_PREIMAGE_V3" certificateSchemaPreimage
  emitBytes "GRADED_BASIS_CERTIFICATE_SCHEMA_ID_V3" certificateSchemaId
  emitSlice "GRADED_BASIS_ADMISSION_SCHEMA_PREIMAGE_V3" admissionSchemaPreimage
  emitBytes "GRADED_BASIS_ADMISSION_SCHEMA_ID_V3" admissionSchemaId
  emitOffsets certificateLayout CertificateField.rustName
  emitOffsets admissionLayout AdmissionField.rustName
