import DClutchSemantics.LiabilityBasisV2
import DClutchSemantics.Codec

/-!
Emit the exact provisional ramp ABI constants plus a finite semantic agreement
and hostile-decoder corpus. The handwritten Rust kernel consumes this output;
this executable does not emit Rust transition logic.
-/

open DClutch.LiabilityBasisV2
open DClutch.LiabilityBasisV2.PhysicalAbi

def rustByte (byte : UInt8) : String := s!"0x{DClutch.Codec.byteHex byte}"

def rustBytes (bytes : List UInt8) : String :=
  s!"[{String.intercalate ", " (bytes.map rustByte)}]"

def request
    (scale knotDenominator : Nat) (left right coordinate : Int)
    (coordinateDenominator : Nat) : Request := {
  scale
  knotDenominator
  leftNumerator := left
  rightNumerator := right
  coordinateNumerator := coordinate
  coordinateDenominator
}

def agreementRequests : List Request := [
  request 100 1 0 10 (-1) 1,
  request 100 1 0 10 0 1,
  request 10 1 0 1 1 3,
  request 10 1 0 1 2 6,
  request 10 1 0 1 2 3,
  request 100 1 0 10 10 1,
  request 7 1 (-2) 2 0 1,
  request 4294967295 4294967295 (-9223372036854775808)
    9223372036854775807 0 4294967295
]

def changed (bytes : List UInt8) (offset : Nat) (value : UInt8) : List UInt8 :=
  bytes.set offset value

def zeroSpan (bytes : List UInt8) (offset width : Nat) : List UInt8 :=
  (List.range width).foldl (fun result index => result.set (offset + index) 0) bytes

def hostileRequests : List (List UInt8) :=
  let base := encodeRequest (request 100 1 0 10 5 1)
  [
    changed base magicOffset 0,
    changed base versionOffset 3,
    changed base profileOffset 2,
    changed base reservedOffset 1,
    zeroSpan base scaleOffset 4,
    zeroSpan base knotDenominatorOffset 4,
    zeroSpan base coordinateDenominatorOffset 4,
    encodeRequest (request 100 1 0 0 0 1),
    encodeRequest (request 100 1 2 1 0 1)
  ]

def emitAgreement (index : Nat) (request : Request) : IO Unit := do
  let decoded ← match decodeRequest (encodeRequest request) with
    | .ok decoded => pure decoded
    | .error error => throw <| IO.userError s!"agreement request {index} decoded as {error}"
  let expected ← match decoded.evaluate? with
    | some [primary, complement] => pure [primary, complement]
    | _ => throw <| IO.userError s!"agreement request {index} did not evaluate"
  IO.println "    AgreementCaseV2 {"
  IO.println s!"        request: {rustBytes (encodeRequest request)},"
  IO.println s!"        expected: [{expected[0]!}, {expected[1]!}],"
  IO.println "    },"

def emitRefusal (index : Nat) (request : List UInt8) : IO Unit := do
  let error ← match decodeRequest request with
    | .error error => pure error
    | .ok _ => throw <| IO.userError s!"hostile request {index} was admitted"
  IO.println "    RefusalCaseV2 {"
  IO.println s!"        request: {rustBytes request},"
  IO.println s!"        error_tag: {error},"
  IO.println "    },"

def main : IO Unit := do
  IO.println "// @generated by formal/dclutch-semantics/EmitLiabilityBasisV2Rust.lean; do not edit."
  IO.println "use super::{AgreementCaseV2, RefusalCaseV2};"
  IO.println s!"pub const RAMP_REQUEST_BYTES_V2: usize = {requestBytes};"
  IO.println s!"pub const RAMP_SCHEMA_VERSION_V2: u16 = {schemaVersion};"
  IO.println s!"pub const RAMP_PROFILE_V2: u16 = {profile};"
  IO.println s!"pub const RAMP_MAGIC_OFFSET_V2: usize = {magicOffset};"
  IO.println s!"pub const RAMP_VERSION_OFFSET_V2: usize = {versionOffset};"
  IO.println s!"pub const RAMP_PROFILE_OFFSET_V2: usize = {profileOffset};"
  IO.println s!"pub const RAMP_SCALE_OFFSET_V2: usize = {scaleOffset};"
  IO.println s!"pub const RAMP_KNOT_DENOMINATOR_OFFSET_V2: usize = {knotDenominatorOffset};"
  IO.println s!"pub const RAMP_LEFT_NUMERATOR_OFFSET_V2: usize = {leftNumeratorOffset};"
  IO.println s!"pub const RAMP_RIGHT_NUMERATOR_OFFSET_V2: usize = {rightNumeratorOffset};"
  IO.println s!"pub const RAMP_COORDINATE_NUMERATOR_OFFSET_V2: usize = {coordinateNumeratorOffset};"
  IO.println s!"pub const RAMP_COORDINATE_DENOMINATOR_OFFSET_V2: usize = {coordinateDenominatorOffset};"
  IO.println s!"pub const RAMP_RESERVED_OFFSET_V2: usize = {reservedOffset};"
  IO.println s!"pub const RAMP_RESERVED_BYTES_V2: usize = {reservedBytes};"
  IO.println s!"pub const RAMP_MAGIC_V2: [u8; 8] = {rustBytes requestMagic};"
  IO.println s!"pub const AGREEMENT_CASES_V2: [AgreementCaseV2; {agreementRequests.length}] = ["
  for indexed in agreementRequests.zipIdx do
    emitAgreement indexed.2 indexed.1
  IO.println "];"
  IO.println s!"pub const REFUSAL_CASES_V2: [RefusalCaseV2; {hostileRequests.length}] = ["
  for indexed in hostileRequests.zipIdx do
    emitRefusal indexed.2 indexed.1
  IO.println "];"
