import DClutchSemantics.DirectProgram

open DClutch

def rustByte (byte : UInt8) : String := s!"0x{Codec.byteHex byte}"

def main : IO Unit := do
  let bytes := TransitionVM.Codec.encodeProgram DirectProgram.program
  IO.println "// @generated by formal/dclutch-semantics/EmitDirectProgramRust.lean; do not edit."
  for register in DirectProgram.ScalarSlot.all do
    IO.println s!"pub(crate) const {DirectProgram.ScalarSlot.rustName register}: usize = {DirectProgram.ScalarSlot.index register};"
  IO.println s!"pub(crate) const SCALAR_COUNT: usize = {DirectProgram.Scalar.count};"
  IO.println "const _: [usize; SCALAR_COUNT] = ["
  for register in DirectProgram.ScalarSlot.all do
    IO.println s!"    {DirectProgram.ScalarSlot.rustName register},"
  IO.println "];"
  for register in DirectProgram.IdentitySlot.all do
    IO.println s!"pub(crate) const {DirectProgram.IdentitySlot.rustName register}: usize = {DirectProgram.IdentitySlot.index register};"
  IO.println s!"pub(crate) const IDENTITY_COUNT: usize = {DirectProgram.Identity.count};"
  IO.println "const _: [usize; IDENTITY_COUNT] = ["
  for register in DirectProgram.IdentitySlot.all do
    IO.println s!"    {DirectProgram.IdentitySlot.rustName register},"
  IO.println "];"
  IO.println ""
  IO.println s!"pub(crate) const DIRECT_PROGRAM: [u8; {bytes.length}] = ["
  for line in List.range ((bytes.length + 15) / 16) do
    let chunk := (bytes.drop (line * 16)).take 16
    IO.println s!"    {String.intercalate ", " (chunk.map rustByte)},"
  IO.println "];"
