//! Checked finite-corpus evidence for one Direct interpreter/AOT comparison.
//!
//! This manifest does not turn a finite corpus into universal source
//! refinement. It gives `ExecutionStrategyCertificateV2` one canonical content
//! identity that binds the exact semantic sources, both Rust executors, emitted
//! program/layout inputs, validator implementation, toolchains, and successful
//! result transcript used by the comparison.

use dclutch_core_contract::ContentId;

use crate::{Error, Result, encode_hex, sha256};

/// Canonical checked translation-validation manifest magic.
pub const CHECKED_TRANSLATION_VALIDATION_MAGIC_V1: [u8; 8] = *b"DCLTTRV1";
/// Implemented checked translation-validation schema.
pub const CHECKED_TRANSLATION_VALIDATION_SCHEMA_V1: u16 = 1;
/// Exact number of independently hashed evidence inputs.
pub const CHECKED_TRANSLATION_VALIDATION_INPUT_COUNT_V1: usize = 21;
/// Exact fixed manifest width.
pub const CHECKED_TRANSLATION_VALIDATION_BYTES_V1: usize =
    16 + CHECKED_TRANSLATION_VALIDATION_INPUT_COUNT_V1 * 32;

const SCHEMA_OFFSET: usize = 8;
const INPUT_COUNT_OFFSET: usize = 10;
const RESERVED_OFFSET: usize = 12;
const DIGESTS_OFFSET: usize = 16;

/// Stable ordered labels for the 21 exact evidence inputs.
pub const CHECKED_TRANSLATION_VALIDATION_LABELS_V1: [&str;
    CHECKED_TRANSLATION_VALIDATION_INPUT_COUNT_V1] = [
    "corpus",
    "lean_direct_controller_codec",
    "lean_direct_program",
    "lean_transition_vm",
    "lean_direct_lifecycle",
    "lean_registered_controller_abi",
    "lean_registered_physical",
    "lean_direct_corpus_emitter",
    "lean_registered_creation_corpus_emitter",
    "rust_direct_codec",
    "rust_transition_vm",
    "rust_direct_aot",
    "rust_direct_aot_generated",
    "rust_validator",
    "rust_registration_validator",
    "rust_terminal_validator",
    "interpreter_program_include",
    "validator_result",
    "rustc_verbose",
    "lake_version",
    "validator_cargo_lock",
];

/// Exact byte inputs consumed by one Direct translation-validation run.
#[derive(Clone, Copy)]
pub struct TranslationValidationEvidenceV1<'a> {
    /// Lean-emitted finite corpus consumed by the validator.
    pub corpus: &'a [u8],
    /// Lean semantic sources and corpus emitters in canonical label order.
    pub lean_sources: [&'a [u8]; 8],
    /// Rust interpreter/AOT/validator sources and emitted program input.
    pub rust_sources: [&'a [u8]; 8],
    /// Successful validator stdout, containing exactly one result line.
    pub validator_result: &'a [u8],
    /// Exact `rustc -Vv` output.
    pub rustc_verbose: &'a [u8],
    /// Exact `lake --version` output.
    pub lake_version: &'a [u8],
    /// Standalone validator Cargo lockfile.
    pub validator_cargo_lock: &'a [u8],
}

impl<'a> TranslationValidationEvidenceV1<'a> {
    fn ordered(self) -> [&'a [u8]; CHECKED_TRANSLATION_VALIDATION_INPUT_COUNT_V1] {
        [
            self.corpus,
            self.lean_sources[0],
            self.lean_sources[1],
            self.lean_sources[2],
            self.lean_sources[3],
            self.lean_sources[4],
            self.lean_sources[5],
            self.lean_sources[6],
            self.lean_sources[7],
            self.rust_sources[0],
            self.rust_sources[1],
            self.rust_sources[2],
            self.rust_sources[3],
            self.rust_sources[4],
            self.rust_sources[5],
            self.rust_sources[6],
            self.rust_sources[7],
            self.validator_result,
            self.rustc_verbose,
            self.lake_version,
            self.validator_cargo_lock,
        ]
    }

    fn validate(self) -> Result<()> {
        if self.ordered().iter().any(|bytes| bytes.is_empty())
            || !self
                .corpus
                .starts_with(b"dclutch-direct-translation-corpus-v1\n")
            || !self
                .validator_result
                .starts_with(b"translation validation passed:")
            || self
                .validator_result
                .iter()
                .filter(|byte| **byte == b'\n')
                .count()
                != 1
            || !self.validator_result.ends_with(b"\n")
            || !self.rustc_verbose.starts_with(b"rustc ")
            || !self.rustc_verbose.ends_with(b"\n")
            || !self.lake_version.starts_with(b"Lake version ")
            || !self.lake_version.ends_with(b"\n")
            || !self
                .validator_cargo_lock
                .starts_with(b"# This file is automatically @generated by Cargo.")
        {
            return Err(Error::InvalidTranslationValidation);
        }
        Ok(())
    }
}

/// Canonical digest-only evidence manifest for one exact comparison run.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CheckedTranslationValidationV1 {
    digests: [[u8; 32]; CHECKED_TRANSLATION_VALIDATION_INPUT_COUNT_V1],
}

impl CheckedTranslationValidationV1 {
    /// Decode and hostile-revalidate one exact fixed-width manifest.
    pub fn decode(bytes: &[u8]) -> Result<Self> {
        if bytes.len() != CHECKED_TRANSLATION_VALIDATION_BYTES_V1 {
            return Err(Error::InvalidLength);
        }
        if bytes.get(..8) != Some(CHECKED_TRANSLATION_VALIDATION_MAGIC_V1.as_slice()) {
            return Err(Error::InvalidMagic);
        }
        if read_u16(bytes, SCHEMA_OFFSET)? != CHECKED_TRANSLATION_VALIDATION_SCHEMA_V1 {
            return Err(Error::UnsupportedSchema);
        }
        if usize::from(read_u16(bytes, INPUT_COUNT_OFFSET)?)
            != CHECKED_TRANSLATION_VALIDATION_INPUT_COUNT_V1
            || bytes.get(RESERVED_OFFSET..DIGESTS_OFFSET) != Some([0_u8; 4].as_slice())
        {
            return Err(Error::InvalidTranslationValidation);
        }
        let mut digests = [[0_u8; 32]; CHECKED_TRANSLATION_VALIDATION_INPUT_COUNT_V1];
        for (index, digest) in digests.iter_mut().enumerate() {
            let offset = DIGESTS_OFFSET
                .checked_add(index.checked_mul(32).ok_or(Error::ArithmeticOverflow)?)
                .ok_or(Error::ArithmeticOverflow)?;
            digest.copy_from_slice(bytes.get(offset..offset + 32).ok_or(Error::InvalidLength)?);
            if digest.iter().all(|byte| *byte == 0) {
                return Err(Error::ZeroIdentifier);
            }
        }
        let result = Self { digests };
        if result.encode().as_slice() != bytes {
            return Err(Error::InvalidTranslationValidation);
        }
        Ok(result)
    }

    /// Encode the canonical fixed-width manifest.
    pub fn encode(self) -> [u8; CHECKED_TRANSLATION_VALIDATION_BYTES_V1] {
        let mut output = [0_u8; CHECKED_TRANSLATION_VALIDATION_BYTES_V1];
        output[..8].copy_from_slice(&CHECKED_TRANSLATION_VALIDATION_MAGIC_V1);
        output[SCHEMA_OFFSET..SCHEMA_OFFSET + 2]
            .copy_from_slice(&CHECKED_TRANSLATION_VALIDATION_SCHEMA_V1.to_le_bytes());
        output[INPUT_COUNT_OFFSET..INPUT_COUNT_OFFSET + 2].copy_from_slice(
            &u16::try_from(CHECKED_TRANSLATION_VALIDATION_INPUT_COUNT_V1)
                .expect("translation evidence count fits u16")
                .to_le_bytes(),
        );
        for (index, digest) in self.digests.iter().enumerate() {
            let offset = DIGESTS_OFFSET + index * 32;
            output
                .get_mut(offset..offset + 32)
                .expect("fixed translation manifest layout")
                .copy_from_slice(digest);
        }
        output
    }

    /// Content identity suitable for `ExecutionStrategyCertificateV2`.
    pub fn translation_validation_id(self) -> Result<ContentId> {
        ContentId::new(sha256(&self.encode())).map_err(|_| Error::ZeroIdentifier)
    }

    /// Return one input digest by its stable label-order index.
    pub fn digest(self, index: usize) -> Result<[u8; 32]> {
        self.digests
            .get(index)
            .copied()
            .ok_or(Error::InvalidTranslationValidation)
    }

    /// Emit a deterministic inspection projection without overstating scope.
    pub fn render_text(self) -> Result<String> {
        let mut output = String::new();
        push_line(&mut output, "format", "dclutch-translation-validation-v1");
        push_line(
            &mut output,
            "translation_validation_id",
            &encode_hex(self.translation_validation_id()?.as_bytes()),
        );
        for (label, digest) in CHECKED_TRANSLATION_VALIDATION_LABELS_V1
            .iter()
            .zip(self.digests)
        {
            push_line(&mut output, label, &encode_hex(&digest));
        }
        push_line(
            &mut output,
            "evidence_class",
            "finite-corpus-three-way-differential-agreement",
        );
        push_line(
            &mut output,
            "excluded_claim",
            "universal-source-or-sbf-runtime-refinement",
        );
        Ok(output)
    }
}

/// Build one manifest from exact nonempty evidence inputs.
pub fn build_checked_translation_validation(
    evidence: TranslationValidationEvidenceV1<'_>,
) -> Result<CheckedTranslationValidationV1> {
    evidence.validate()?;
    let mut digests = [[0_u8; 32]; CHECKED_TRANSLATION_VALIDATION_INPUT_COUNT_V1];
    for (digest, bytes) in digests.iter_mut().zip(evidence.ordered()) {
        *digest = sha256(bytes);
        if digest.iter().all(|byte| *byte == 0) {
            return Err(Error::ZeroIdentifier);
        }
    }
    Ok(CheckedTranslationValidationV1 { digests })
}

/// Require an existing manifest to match every supplied evidence byte.
pub fn verify_checked_translation_validation(
    manifest: &[u8],
    evidence: TranslationValidationEvidenceV1<'_>,
) -> Result<CheckedTranslationValidationV1> {
    let expected = CheckedTranslationValidationV1::decode(manifest)?;
    let rebuilt = build_checked_translation_validation(evidence)?;
    if rebuilt != expected {
        return Err(Error::CheckedTranslationValidationMismatch);
    }
    Ok(expected)
}

fn read_u16(bytes: &[u8], offset: usize) -> Result<u16> {
    let value: [u8; 2] = bytes
        .get(offset..offset + 2)
        .ok_or(Error::InvalidLength)?
        .try_into()
        .map_err(|_| Error::InvalidLength)?;
    Ok(u16::from_le_bytes(value))
}

fn push_line(output: &mut String, key: &str, value: &str) {
    output.push_str(key);
    output.push('=');
    output.push_str(value);
    output.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;

    fn evidence<'a>(bytes: &'a [u8]) -> TranslationValidationEvidenceV1<'a> {
        TranslationValidationEvidenceV1 {
            corpus: b"dclutch-direct-translation-corpus-v1\nprogram|00\n",
            lean_sources: [bytes; 8],
            rust_sources: [bytes; 8],
            validator_result: b"translation validation passed: finite exact corpus\n",
            rustc_verbose: b"rustc 1.97.1\nbinary: rustc\n",
            lake_version: b"Lake version 5.0.0 (Lean version 4.30.0)\n",
            validator_cargo_lock:
                b"# This file is automatically @generated by Cargo.\nversion = 4\n",
        }
    }

    #[test]
    fn manifest_roundtrips_and_binds_every_input() {
        let checked =
            build_checked_translation_validation(evidence(b"source-a")).expect("checked manifest");
        let bytes = checked.encode();
        assert_eq!(bytes.len(), CHECKED_TRANSLATION_VALIDATION_BYTES_V1);
        assert_eq!(CheckedTranslationValidationV1::decode(&bytes), Ok(checked));
        assert_eq!(
            verify_checked_translation_validation(&bytes, evidence(b"source-a")),
            Ok(checked)
        );
        assert_eq!(
            verify_checked_translation_validation(&bytes, evidence(b"source-b")),
            Err(Error::CheckedTranslationValidationMismatch)
        );
        let text = checked.render_text().expect("inspection text");
        assert!(text.contains("finite-corpus-three-way-differential-agreement"));
        assert!(text.contains("universal-source-or-sbf-runtime-refinement"));
    }

    #[test]
    fn hostile_width_header_digest_and_result_inputs_refuse() {
        let checked =
            build_checked_translation_validation(evidence(b"source-a")).expect("checked manifest");
        let bytes = checked.encode();
        for width in 0..bytes.len() {
            assert!(
                CheckedTranslationValidationV1::decode(
                    bytes.get(..width).expect("bounded hostile width")
                )
                .is_err()
            );
        }
        let mut trailing = bytes.to_vec();
        trailing.push(0);
        assert_eq!(
            CheckedTranslationValidationV1::decode(&trailing),
            Err(Error::InvalidLength)
        );
        for offset in [0, SCHEMA_OFFSET, INPUT_COUNT_OFFSET, RESERVED_OFFSET] {
            let mut hostile = bytes;
            *hostile.get_mut(offset).expect("fixed hostile offset") ^= 1;
            assert!(CheckedTranslationValidationV1::decode(&hostile).is_err());
        }
        let mut substituted_digest = bytes;
        *substituted_digest
            .get_mut(DIGESTS_OFFSET)
            .expect("fixed first digest offset") ^= 1;
        assert!(CheckedTranslationValidationV1::decode(&substituted_digest).is_ok());
        assert_eq!(
            verify_checked_translation_validation(&substituted_digest, evidence(b"source-a")),
            Err(Error::CheckedTranslationValidationMismatch)
        );
        let mut invalid = evidence(b"source-a");
        invalid.validator_result = b"translation validation failed\n";
        assert_eq!(
            build_checked_translation_validation(invalid),
            Err(Error::InvalidTranslationValidation)
        );
    }
}
