#!/bin/sh
set -eu

# The Claims market-closure request and receipt ABI comes from Lean and nothing
# re-ran the emitter. Both records are parsed by the Claims closure route, so a
# hand edit here moves a persisted wire layout with no author noticing.

crate_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repository_dir=$(CDPATH= cd -- "$crate_dir/../.." && pwd)
formal_dir="$repository_dir/formal/dclutch-semantics"

candidate=$(mktemp "${TMPDIR:-/tmp}/dclutch-generated.XXXXXX")
trap 'rm -f "$candidate"' EXIT HUP INT TERM

# Assert the provenance header and that the emitter produced a whole file
# rather than a truncated one, then normalize with the repository's pinned
# rustfmt and byte-compare. Formatting is normalized rather than asserted
# because the committed bytes are rustfmt output, not raw emitter output;
# `rustfmt` resolves through rust-toolchain.toml from inside the tree.
#
# Each emission is spelled out rather than folded into a loop, because the
# emission census matches `lake env lean --run <Emitter>` literally: an emitter
# reached through a shell variable is an emitter the census cannot see, and a
# guard the census cannot see guards nothing as far as the ratchet is concerned.
verify() {
  emitter=$1
  target=$2
  minimum_lines=$3
  test "$(sed -n '1p' "$candidate")" = "// @generated by formal/dclutch-semantics/$emitter; do not edit."
  test "$(wc -l <"$candidate" | tr -d ' ')" -ge "$minimum_lines"
  rustfmt --edition 2024 "$candidate"
  cmp "$candidate" "$crate_dir/src/$target"
}

(
  cd "$formal_dir"
  lake build DClutchSemantics.MarketRetirementV1Abi >/dev/null
  lake env lean --run EmitClaimsMarketClosureV1Rust.lean >"$candidate"
)
grep -q '^pub const CLAIMS_MARKET_CLOSURE_VERSION_V1: u16 = 1;$' "$candidate"
grep -q '^pub const CLAIMS_MARKET_CLOSURE_REQUEST_BYTES_V1: usize = 256;$' "$candidate"
grep -q '^pub const CLAIMS_MARKET_CLOSURE_RECEIPT_BYTES_V1: usize = 320;$' "$candidate"
verify EmitClaimsMarketClosureV1Rust.lean generated_market_closure_v1.rs 40

(
  cd "$formal_dir"
  lake build DClutchSemantics.ClaimsLiabilityBasisStateV2Abi >/dev/null
  lake env lean --run EmitClaimsLiabilityBasisStateV2Rust.lean >"$candidate"
)
grep -q '^pub const LIABILITY_BASIS_MARKET_HEADER_BYTES_V2: usize = 256;$' "$candidate"
grep -q '^pub const LIABILITY_BASIS_POSITION_HEADER_BYTES_V2: usize = 128;$' "$candidate"
grep -q '^pub const LIABILITY_BASIS_MARKET_SEED_V2: &\[u8\] = b"dclutch:lbv2:market";$' "$candidate"
verify EmitClaimsLiabilityBasisStateV2Rust.lean generated_liability_basis_state_v2.rs 40
