/-
  Generated by `qedlift` from `target/deploy/dclutch_claims_proof_sbf.so`.

End-to-end lift demonstration:
1. The .text bytes are embedded verbatim as a `ByteArray`.
2. `Decode.decodeProgram` recovers the instruction sequence;
`native_decide` proves the decode is correct.
3. A `cuTripleWithinMem` Hoare triple is stated over the
decoded sequence. The pre/post atom synthesis is the next
iteration's work (the "symbolic executor" piece); for the
demo, see the worked example in
`SVM/SBPF/Macros.lean` (`dclutch_claims_proof_sbf_macro_spec_auto`) where the
theorem is proved by `sl_block_auto` against the same
instruction sequence.
-/

import SVM.SBPF.Decode
import SVM.SBPF.RunnerBridge
import SVM.SBPF.Macros
import SVM.SBPF.SatWitness

set_option maxRecDepth 65536
set_option maxHeartbeats 4000000

namespace Examples.Lifted.DclutchClaimsProofSbfLifted

open SVM.SBPF

/-- `.text` bytes extracted from the .so by qedlift. -/
def DclutchClaimsProofSbfLiftedBytes : ByteArray := ⟨#[
  0x18, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00,
  0x15, 0x01, 0x77, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x55, 0x02, 0x75, 0x00, 0x02, 0x00, 0x00, 0x00,
  0x79, 0x12, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x55, 0x02, 0x73, 0x00, 0xff, 0x01, 0x00, 0x00,
  0x79, 0x12, 0x58, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x55, 0x02, 0x71, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x12, 0x68, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x55, 0x02, 0x6f, 0x00, 0xff, 0x00, 0x01, 0x00,
  0x79, 0x12, 0xb8, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x55, 0x02, 0x6d, 0x00, 0x50, 0x00, 0x00, 0x00,
  0x79, 0x12, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x13, 0x70, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x5d, 0x32, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x13, 0x78, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x14, 0x18, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x5d, 0x34, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x13, 0x80, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x14, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x5d, 0x34, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x13, 0x88, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x14, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x1d, 0x34, 0x61, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x13, 0x18, 0x51, 0x00, 0x00, 0x00, 0x00,
  0x55, 0x03, 0x5f, 0x00, 0x48, 0x00, 0x00, 0x00,
  0x79, 0x13, 0x68, 0x51, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x14, 0x90, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x5d, 0x34, 0x5c, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x13, 0x70, 0x51, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x14, 0x98, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x5d, 0x34, 0x59, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x13, 0x78, 0x51, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x14, 0xa0, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x5d, 0x34, 0x56, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x13, 0x80, 0x51, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x14, 0xa8, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x5d, 0x34, 0x53, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x13, 0x18, 0x00, 0x00, 0x00, 0x00, 0x00,
  0xbf, 0x36, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x4f, 0x26, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x14, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x4f, 0x46, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x15, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x4f, 0x56, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x15, 0x06, 0x4b, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x16, 0xc8, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x5d, 0x62, 0x49, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x12, 0xd0, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x5d, 0x23, 0x47, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x12, 0xd8, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x5d, 0x24, 0x45, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x12, 0xe0, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x5d, 0x25, 0x43, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x12, 0xc0, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x18, 0x03, 0x00, 0x00, 0x44, 0x43, 0x43, 0x53,
  0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
  0x5d, 0x32, 0x3f, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x12, 0xe8, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x18, 0x03, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x2d, 0x32, 0x3b, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x13, 0x20, 0x51, 0x00, 0x00, 0x00, 0x00,
  0x18, 0x04, 0x00, 0x00, 0x44, 0x43, 0x45, 0x46,
  0x00, 0x00, 0x00, 0x00, 0x01, 0x04, 0x00, 0x00,
  0x5d, 0x43, 0x37, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x13, 0x28, 0x51, 0x00, 0x00, 0x00, 0x00,
  0x55, 0x03, 0x35, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x13, 0x38, 0x51, 0x00, 0x00, 0x00, 0x00,
  0x55, 0x03, 0x33, 0x00, 0x00, 0x01, 0x00, 0x00,
  0x79, 0x13, 0x48, 0x51, 0x00, 0x00, 0x00, 0x00,
  0xbf, 0x34, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x67, 0x04, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00,
  0x77, 0x04, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00,
  0x55, 0x04, 0x2e, 0x00, 0x01, 0x00, 0x01, 0x00,
  0x77, 0x03, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00,
  0x5d, 0x23, 0x2c, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x13, 0x58, 0x51, 0x00, 0x00, 0x00, 0x00,
  0xbf, 0x34, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x67, 0x04, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00,
  0x77, 0x04, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00,
  0x55, 0x04, 0x27, 0x00, 0x02, 0x01, 0x01, 0x00,
  0x77, 0x03, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00,
  0x5d, 0x23, 0x25, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x12, 0xf0, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x07, 0x02, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
  0xb7, 0x03, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
  0x15, 0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
  0xb7, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x57, 0x03, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
  0x55, 0x03, 0x1e, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x13, 0xf8, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x07, 0x03, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
  0xb7, 0x04, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
  0x15, 0x03, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
  0xb7, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x57, 0x04, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
  0x55, 0x04, 0x17, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x14, 0x00, 0x29, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x15, 0x50, 0x51, 0x00, 0x00, 0x00, 0x00,
  0xad, 0x54, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x16, 0x30, 0x51, 0x00, 0x00, 0x00, 0x00,
  0x5d, 0x26, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x16, 0x40, 0x51, 0x00, 0x00, 0x00, 0x00,
  0x5d, 0x36, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x16, 0x60, 0x51, 0x00, 0x00, 0x00, 0x00,
  0x5d, 0x65, 0x0e, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x79, 0x17, 0x08, 0x29, 0x00, 0x00, 0x00, 0x00,
  0xbf, 0x56, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x0f, 0x76, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0xb7, 0x07, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
  0xad, 0x56, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
  0xb7, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x57, 0x07, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
  0x55, 0x07, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x7b, 0x61, 0x08, 0x29, 0x00, 0x00, 0x00, 0x00,
  0x7b, 0x31, 0xf8, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x7b, 0x21, 0xf0, 0x28, 0x00, 0x00, 0x00, 0x00,
  0x1f, 0x54, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x7b, 0x41, 0x00, 0x29, 0x00, 0x00, 0x00, 0x00,
  0xb7, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x95, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
]⟩

/-- Text section file-offset: 0x100000120. -/
def DclutchClaimsProofSbfLiftedTextOffset : Nat := 0x100000120

/-- Decoded form of the .text bytes. -/
def DclutchClaimsProofSbfLiftedInsns : Array Insn := #[
  .lddw .r0 (21474836480),
  .jeq .r1 (.imm (0)) 118,
  .ldx .dword .r2 .r1 0,
  .jne .r2 (.imm (2)) 118,
  .ldx .dword .r2 .r1 8,
  .jne .r2 (.imm (511)) 118,
  .ldx .dword .r2 .r1 88,
  .jne .r2 (.imm (0)) 118,
  .ldx .dword .r2 .r1 10344,
  .jne .r2 (.imm (65791)) 118,
  .ldx .dword .r2 .r1 10424,
  .jne .r2 (.imm (80)) 118,
  .ldx .dword .r2 .r1 16,
  .ldx .dword .r3 .r1 10352,
  .jne .r2 (.reg .r3) 24,
  .ldx .dword .r3 .r1 10360,
  .ldx .dword .r4 .r1 24,
  .jne .r4 (.reg .r3) 24,
  .ldx .dword .r3 .r1 10368,
  .ldx .dword .r4 .r1 32,
  .jne .r4 (.reg .r3) 24,
  .ldx .dword .r3 .r1 10376,
  .ldx .dword .r4 .r1 40,
  .jeq .r4 (.reg .r3) 118,
  .ldx .dword .r3 .r1 20760,
  .jne .r3 (.imm (72)) 118,
  .ldx .dword .r3 .r1 20840,
  .ldx .dword .r4 .r1 10384,
  .jne .r4 (.reg .r3) 118,
  .ldx .dword .r3 .r1 20848,
  .ldx .dword .r4 .r1 10392,
  .jne .r4 (.reg .r3) 118,
  .ldx .dword .r3 .r1 20856,
  .ldx .dword .r4 .r1 10400,
  .jne .r4 (.reg .r3) 118,
  .ldx .dword .r3 .r1 20864,
  .ldx .dword .r4 .r1 10408,
  .jne .r4 (.reg .r3) 118,
  .ldx .dword .r3 .r1 24,
  .mov64 .r6 (.reg .r3),
  .or64 .r6 (.reg .r2),
  .ldx .dword .r4 .r1 32,
  .or64 .r6 (.reg .r4),
  .ldx .dword .r5 .r1 40,
  .or64 .r6 (.reg .r5),
  .jeq .r6 (.imm (0)) 118,
  .ldx .dword .r6 .r1 10440,
  .jne .r2 (.reg .r6) 118,
  .ldx .dword .r2 .r1 10448,
  .jne .r3 (.reg .r2) 118,
  .ldx .dword .r2 .r1 10456,
  .jne .r4 (.reg .r2) 118,
  .ldx .dword .r2 .r1 10464,
  .jne .r5 (.reg .r2) 118,
  .ldx .dword .r2 .r1 10432,
  .lddw .r3 (5691884356),
  .jne .r2 (.reg .r3) 118,
  .ldx .dword .r2 .r1 10472,
  .lddw .r3 (4294967295),
  .jgt .r2 (.reg .r3) 118,
  .ldx .dword .r3 .r1 20768,
  .lddw .r4 (4403520422724),
  .jne .r3 (.reg .r4) 118,
  .ldx .dword .r3 .r1 20776,
  .jne .r3 (.imm (0)) 118,
  .ldx .dword .r3 .r1 20792,
  .jne .r3 (.imm (256)) 118,
  .ldx .dword .r3 .r1 20808,
  .mov64 .r4 (.reg .r3),
  .lsh64 .r4 (.imm (32)),
  .rsh64 .r4 (.imm (32)),
  .jne .r4 (.imm (65537)) 118,
  .rsh64 .r3 (.imm (32)),
  .jne .r3 (.reg .r2) 118,
  .ldx .dword .r3 .r1 20824,
  .mov64 .r4 (.reg .r3),
  .lsh64 .r4 (.imm (32)),
  .rsh64 .r4 (.imm (32)),
  .jne .r4 (.imm (65794)) 118,
  .rsh64 .r3 (.imm (32)),
  .jne .r3 (.reg .r2) 118,
  .ldx .dword .r2 .r1 10480,
  .add64 .r2 (.imm (1)),
  .mov64 .r3 (.imm (1)),
  .jeq .r2 (.imm (0)) 86,
  .mov64 .r3 (.imm (0)),
  .and64 .r3 (.imm (1)),
  .jne .r3 (.imm (0)) 118,
  .ldx .dword .r3 .r1 10488,
  .add64 .r3 (.imm (1)),
  .mov64 .r4 (.imm (1)),
  .jeq .r3 (.imm (0)) 93,
  .mov64 .r4 (.imm (0)),
  .and64 .r4 (.imm (1)),
  .jne .r4 (.imm (0)) 118,
  .ldx .dword .r4 .r1 10496,
  .ldx .dword .r5 .r1 20816,
  .jlt .r4 (.reg .r5) 118,
  .ldx .dword .r6 .r1 20784,
  .jne .r6 (.reg .r2) 118,
  .ldx .dword .r6 .r1 20800,
  .jne .r6 (.reg .r3) 118,
  .ldx .dword .r6 .r1 20832,
  .jne .r5 (.reg .r6) 118,
  .ldx .dword .r7 .r1 10504,
  .mov64 .r6 (.reg .r5),
  .add64 .r6 (.reg .r7),
  .mov64 .r7 (.imm (1)),
  .jlt .r6 (.reg .r5) 110,
  .mov64 .r7 (.imm (0)),
  .and64 .r7 (.imm (1)),
  .jne .r7 (.imm (0)) 118,
  .stx .dword .r1 10504 .r6,
  .stx .dword .r1 10488 .r3,
  .stx .dword .r1 10480 .r2,
  .sub64 .r4 (.reg .r5),
  .stx .dword .r1 10496 .r4,
  .mov64 .r0 (.imm (0)),
  .exit
]

/-- The V0 function registry (murmur3 key → target slot) solana-sbpf built
    at load, mirroring `Elf.buildFnRegistry` (audit H2). Resolves internal
    `call` immediates to `.call_local` targets. -/
def DclutchClaimsProofSbfLiftedFnRegistry : List (Nat × Nat) := [(1910755201, 0)]

/-- The bytes decode exactly to the expected instruction array. -/
theorem DclutchClaimsProofSbfLifted_decodes :
    Decode.decodeProgram DclutchClaimsProofSbfLiftedBytes DclutchClaimsProofSbfLiftedFnRegistry = some DclutchClaimsProofSbfLiftedInsns := by
  native_decide

/-! ## Symbolically lifted Hoare triple

Synthesised by qedlift's symbolic executor walking the
decoded insns left-to-right. Closed by `sl_block_auto`. -/

open Memory in
theorem DclutchClaimsProofSbfLifted_lifted_spec
    (vR0Old baseAddr oldMemD_0 vR2Old oldMemD_1 oldMemD_2 oldMemD_3 oldMemD_4 oldMemD_5 oldMemD_6 vR3Old oldMemD_7 oldMemD_8 oldMemD_9 vR4Old oldMemD_10 oldMemD_11 oldMemD_12 oldMemD_13 oldMemD_14 oldMemD_15 oldMemD_16 vR6Old oldMemD_17 oldMemD_18 vR5Old oldMemD_19 oldMemD_20 oldMemD_21 oldMemD_22 oldMemD_23 oldMemD_24 oldMemD_25 oldMemD_26 oldMemD_27 oldMemD_28 oldMemD_29 oldMemD_30 oldMemD_31 oldMemD_32 oldMemD_33 oldMemD_34 oldMemD_35 oldMemD_36 oldMemD_37 vR7Old : Nat)
    (holdMemD_0_lt : oldMemD_0 < 2 ^ 64)
    (holdMemD_1_lt : oldMemD_1 < 2 ^ 64)
    (holdMemD_2_lt : oldMemD_2 < 2 ^ 64)
    (holdMemD_3_lt : oldMemD_3 < 2 ^ 64)
    (holdMemD_4_lt : oldMemD_4 < 2 ^ 64)
    (holdMemD_5_lt : oldMemD_5 < 2 ^ 64)
    (holdMemD_6_lt : oldMemD_6 < 2 ^ 64)
    (holdMemD_7_lt : oldMemD_7 < 2 ^ 64)
    (holdMemD_8_lt : oldMemD_8 < 2 ^ 64)
    (holdMemD_9_lt : oldMemD_9 < 2 ^ 64)
    (holdMemD_10_lt : oldMemD_10 < 2 ^ 64)
    (holdMemD_11_lt : oldMemD_11 < 2 ^ 64)
    (holdMemD_12_lt : oldMemD_12 < 2 ^ 64)
    (holdMemD_13_lt : oldMemD_13 < 2 ^ 64)
    (holdMemD_14_lt : oldMemD_14 < 2 ^ 64)
    (holdMemD_15_lt : oldMemD_15 < 2 ^ 64)
    (holdMemD_16_lt : oldMemD_16 < 2 ^ 64)
    (holdMemD_17_lt : oldMemD_17 < 2 ^ 64)
    (holdMemD_18_lt : oldMemD_18 < 2 ^ 64)
    (holdMemD_19_lt : oldMemD_19 < 2 ^ 64)
    (holdMemD_20_lt : oldMemD_20 < 2 ^ 64)
    (holdMemD_21_lt : oldMemD_21 < 2 ^ 64)
    (holdMemD_22_lt : oldMemD_22 < 2 ^ 64)
    (holdMemD_23_lt : oldMemD_23 < 2 ^ 64)
    (holdMemD_24_lt : oldMemD_24 < 2 ^ 64)
    (holdMemD_25_lt : oldMemD_25 < 2 ^ 64)
    (holdMemD_26_lt : oldMemD_26 < 2 ^ 64)
    (holdMemD_27_lt : oldMemD_27 < 2 ^ 64)
    (holdMemD_28_lt : oldMemD_28 < 2 ^ 64)
    (holdMemD_29_lt : oldMemD_29 < 2 ^ 64)
    (holdMemD_30_lt : oldMemD_30 < 2 ^ 64)
    (holdMemD_31_lt : oldMemD_31 < 2 ^ 64)
    (holdMemD_32_lt : oldMemD_32 < 2 ^ 64)
    (holdMemD_33_lt : oldMemD_33 < 2 ^ 64)
    (holdMemD_34_lt : oldMemD_34 < 2 ^ 64)
    (holdMemD_35_lt : oldMemD_35 < 2 ^ 64)
    (holdMemD_36_lt : oldMemD_36 < 2 ^ 64)
    (holdMemD_37_lt : oldMemD_37 < 2 ^ 64)
    (h_branch0 : baseAddr ≠ toU64 0)
    (h_branch1 : oldMemD_0 = toU64 2)
    (h_branch2 : oldMemD_1 = toU64 511)
    (h_branch3 : oldMemD_2 = toU64 0)
    (h_branch4 : oldMemD_3 = toU64 65791)
    (h_branch5 : oldMemD_4 = toU64 80)
    (h_branch6 : oldMemD_5 ≠ oldMemD_6)
    (h_branch7 : oldMemD_7 = toU64 72)
    (h_branch8 : oldMemD_9 = oldMemD_8)
    (h_branch9 : oldMemD_11 = oldMemD_10)
    (h_branch10 : oldMemD_13 = oldMemD_12)
    (h_branch11 : oldMemD_15 = oldMemD_14)
    (h_branch12 : (((((oldMemD_16 ||| oldMemD_5) % U64_MODULUS) ||| oldMemD_17) % U64_MODULUS) ||| oldMemD_18) % U64_MODULUS ≠ toU64 0)
    (h_branch13 : oldMemD_5 = oldMemD_19)
    (h_branch14 : oldMemD_16 = oldMemD_20)
    (h_branch15 : oldMemD_17 = oldMemD_21)
    (h_branch16 : oldMemD_18 = oldMemD_22)
    (h_branch17 : oldMemD_23 = toU64 5691884356)
    (h_branch18 : ¬ oldMemD_24 > toU64 4294967295)
    (h_branch19 : oldMemD_25 = toU64 4403520422724)
    (h_branch20 : oldMemD_26 = toU64 0)
    (h_branch21 : oldMemD_27 = toU64 256)
    (h_branch22 : ((oldMemD_28 <<< (toU64 32 % 64)) % U64_MODULUS) >>> (toU64 32 % 64) = toU64 65537)
    (h_branch23 : oldMemD_28 >>> (toU64 32 % 64) = oldMemD_24)
    (h_branch24 : ((oldMemD_29 <<< (toU64 32 % 64)) % U64_MODULUS) >>> (toU64 32 % 64) = toU64 65794)
    (h_branch25 : oldMemD_29 >>> (toU64 32 % 64) = oldMemD_24)
    (h_branch26 : wrapAdd oldMemD_30 (toU64 1) ≠ toU64 0)
    (h_branch27 : ((toU64 0) &&& toU64 1) % U64_MODULUS = toU64 0)
    (h_branch28 : wrapAdd oldMemD_31 (toU64 1) ≠ toU64 0)
    (h_branch29 : ((toU64 0) &&& toU64 1) % U64_MODULUS = toU64 0)
    (h_branch30 : ¬ oldMemD_32 < oldMemD_33)
    (h_branch31 : oldMemD_34 = wrapAdd oldMemD_30 (toU64 1))
    (h_branch32 : oldMemD_35 = wrapAdd oldMemD_31 (toU64 1))
    (h_branch33 : oldMemD_33 = oldMemD_36)
    (h_branch34 : ¬ wrapAdd oldMemD_33 oldMemD_37 < oldMemD_33)
    (h_branch35 : ((toU64 0) &&& toU64 1) % U64_MODULUS = toU64 0)
    : cuTripleWithinMem 109 0 0 118
      ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((CodeReq.singleton 0 (.lddw .r0 (21474836480))).union
        (CodeReq.singleton 1 (.jeq .r1 (.imm (0)) 118))).union
        (CodeReq.singleton 2 (.ldx .dword .r2 .r1 0))).union
        (CodeReq.singleton 3 (.jne .r2 (.imm (2)) 118))).union
        (CodeReq.singleton 4 (.ldx .dword .r2 .r1 8))).union
        (CodeReq.singleton 5 (.jne .r2 (.imm (511)) 118))).union
        (CodeReq.singleton 6 (.ldx .dword .r2 .r1 88))).union
        (CodeReq.singleton 7 (.jne .r2 (.imm (0)) 118))).union
        (CodeReq.singleton 8 (.ldx .dword .r2 .r1 10344))).union
        (CodeReq.singleton 9 (.jne .r2 (.imm (65791)) 118))).union
        (CodeReq.singleton 10 (.ldx .dword .r2 .r1 10424))).union
        (CodeReq.singleton 11 (.jne .r2 (.imm (80)) 118))).union
        (CodeReq.singleton 12 (.ldx .dword .r2 .r1 16))).union
        (CodeReq.singleton 13 (.ldx .dword .r3 .r1 10352))).union
        (CodeReq.singleton 14 (.jne .r2 (.reg .r3) 24))).union
        (CodeReq.singleton 24 (.ldx .dword .r3 .r1 20760))).union
        (CodeReq.singleton 25 (.jne .r3 (.imm (72)) 118))).union
        (CodeReq.singleton 26 (.ldx .dword .r3 .r1 20840))).union
        (CodeReq.singleton 27 (.ldx .dword .r4 .r1 10384))).union
        (CodeReq.singleton 28 (.jne .r4 (.reg .r3) 118))).union
        (CodeReq.singleton 29 (.ldx .dword .r3 .r1 20848))).union
        (CodeReq.singleton 30 (.ldx .dword .r4 .r1 10392))).union
        (CodeReq.singleton 31 (.jne .r4 (.reg .r3) 118))).union
        (CodeReq.singleton 32 (.ldx .dword .r3 .r1 20856))).union
        (CodeReq.singleton 33 (.ldx .dword .r4 .r1 10400))).union
        (CodeReq.singleton 34 (.jne .r4 (.reg .r3) 118))).union
        (CodeReq.singleton 35 (.ldx .dword .r3 .r1 20864))).union
        (CodeReq.singleton 36 (.ldx .dword .r4 .r1 10408))).union
        (CodeReq.singleton 37 (.jne .r4 (.reg .r3) 118))).union
        (CodeReq.singleton 38 (.ldx .dword .r3 .r1 24))).union
        (CodeReq.singleton 39 (.mov64 .r6 (.reg .r3)))).union
        (CodeReq.singleton 40 (.or64 .r6 (.reg .r2)))).union
        (CodeReq.singleton 41 (.ldx .dword .r4 .r1 32))).union
        (CodeReq.singleton 42 (.or64 .r6 (.reg .r4)))).union
        (CodeReq.singleton 43 (.ldx .dword .r5 .r1 40))).union
        (CodeReq.singleton 44 (.or64 .r6 (.reg .r5)))).union
        (CodeReq.singleton 45 (.jeq .r6 (.imm (0)) 118))).union
        (CodeReq.singleton 46 (.ldx .dword .r6 .r1 10440))).union
        (CodeReq.singleton 47 (.jne .r2 (.reg .r6) 118))).union
        (CodeReq.singleton 48 (.ldx .dword .r2 .r1 10448))).union
        (CodeReq.singleton 49 (.jne .r3 (.reg .r2) 118))).union
        (CodeReq.singleton 50 (.ldx .dword .r2 .r1 10456))).union
        (CodeReq.singleton 51 (.jne .r4 (.reg .r2) 118))).union
        (CodeReq.singleton 52 (.ldx .dword .r2 .r1 10464))).union
        (CodeReq.singleton 53 (.jne .r5 (.reg .r2) 118))).union
        (CodeReq.singleton 54 (.ldx .dword .r2 .r1 10432))).union
        (CodeReq.singleton 55 (.lddw .r3 (5691884356)))).union
        (CodeReq.singleton 56 (.jne .r2 (.reg .r3) 118))).union
        (CodeReq.singleton 57 (.ldx .dword .r2 .r1 10472))).union
        (CodeReq.singleton 58 (.lddw .r3 (4294967295)))).union
        (CodeReq.singleton 59 (.jgt .r2 (.reg .r3) 118))).union
        (CodeReq.singleton 60 (.ldx .dword .r3 .r1 20768))).union
        (CodeReq.singleton 61 (.lddw .r4 (4403520422724)))).union
        (CodeReq.singleton 62 (.jne .r3 (.reg .r4) 118))).union
        (CodeReq.singleton 63 (.ldx .dword .r3 .r1 20776))).union
        (CodeReq.singleton 64 (.jne .r3 (.imm (0)) 118))).union
        (CodeReq.singleton 65 (.ldx .dword .r3 .r1 20792))).union
        (CodeReq.singleton 66 (.jne .r3 (.imm (256)) 118))).union
        (CodeReq.singleton 67 (.ldx .dword .r3 .r1 20808))).union
        (CodeReq.singleton 68 (.mov64 .r4 (.reg .r3)))).union
        (CodeReq.singleton 69 (.lsh64 .r4 (.imm (32))))).union
        (CodeReq.singleton 70 (.rsh64 .r4 (.imm (32))))).union
        (CodeReq.singleton 71 (.jne .r4 (.imm (65537)) 118))).union
        (CodeReq.singleton 72 (.rsh64 .r3 (.imm (32))))).union
        (CodeReq.singleton 73 (.jne .r3 (.reg .r2) 118))).union
        (CodeReq.singleton 74 (.ldx .dword .r3 .r1 20824))).union
        (CodeReq.singleton 75 (.mov64 .r4 (.reg .r3)))).union
        (CodeReq.singleton 76 (.lsh64 .r4 (.imm (32))))).union
        (CodeReq.singleton 77 (.rsh64 .r4 (.imm (32))))).union
        (CodeReq.singleton 78 (.jne .r4 (.imm (65794)) 118))).union
        (CodeReq.singleton 79 (.rsh64 .r3 (.imm (32))))).union
        (CodeReq.singleton 80 (.jne .r3 (.reg .r2) 118))).union
        (CodeReq.singleton 81 (.ldx .dword .r2 .r1 10480))).union
        (CodeReq.singleton 82 (.add64 .r2 (.imm (1))))).union
        (CodeReq.singleton 83 (.mov64 .r3 (.imm (1))))).union
        (CodeReq.singleton 84 (.jeq .r2 (.imm (0)) 86))).union
        (CodeReq.singleton 85 (.mov64 .r3 (.imm (0))))).union
        (CodeReq.singleton 86 (.and64 .r3 (.imm (1))))).union
        (CodeReq.singleton 87 (.jne .r3 (.imm (0)) 118))).union
        (CodeReq.singleton 88 (.ldx .dword .r3 .r1 10488))).union
        (CodeReq.singleton 89 (.add64 .r3 (.imm (1))))).union
        (CodeReq.singleton 90 (.mov64 .r4 (.imm (1))))).union
        (CodeReq.singleton 91 (.jeq .r3 (.imm (0)) 93))).union
        (CodeReq.singleton 92 (.mov64 .r4 (.imm (0))))).union
        (CodeReq.singleton 93 (.and64 .r4 (.imm (1))))).union
        (CodeReq.singleton 94 (.jne .r4 (.imm (0)) 118))).union
        (CodeReq.singleton 95 (.ldx .dword .r4 .r1 10496))).union
        (CodeReq.singleton 96 (.ldx .dword .r5 .r1 20816))).union
        (CodeReq.singleton 97 (.jlt .r4 (.reg .r5) 118))).union
        (CodeReq.singleton 98 (.ldx .dword .r6 .r1 20784))).union
        (CodeReq.singleton 99 (.jne .r6 (.reg .r2) 118))).union
        (CodeReq.singleton 100 (.ldx .dword .r6 .r1 20800))).union
        (CodeReq.singleton 101 (.jne .r6 (.reg .r3) 118))).union
        (CodeReq.singleton 102 (.ldx .dword .r6 .r1 20832))).union
        (CodeReq.singleton 103 (.jne .r5 (.reg .r6) 118))).union
        (CodeReq.singleton 104 (.ldx .dword .r7 .r1 10504))).union
        (CodeReq.singleton 105 (.mov64 .r6 (.reg .r5)))).union
        (CodeReq.singleton 106 (.add64 .r6 (.reg .r7)))).union
        (CodeReq.singleton 107 (.mov64 .r7 (.imm (1))))).union
        (CodeReq.singleton 108 (.jlt .r6 (.reg .r5) 110))).union
        (CodeReq.singleton 109 (.mov64 .r7 (.imm (0))))).union
        (CodeReq.singleton 110 (.and64 .r7 (.imm (1))))).union
        (CodeReq.singleton 111 (.jne .r7 (.imm (0)) 118))).union
        (CodeReq.singleton 112 (.stx .dword .r1 10504 .r6))).union
        (CodeReq.singleton 113 (.stx .dword .r1 10488 .r3))).union
        (CodeReq.singleton 114 (.stx .dword .r1 10480 .r2))).union
        (CodeReq.singleton 115 (.sub64 .r4 (.reg .r5)))).union
        (CodeReq.singleton 116 (.stx .dword .r1 10496 .r4))).union
        (CodeReq.singleton 117 (.mov64 .r0 (.imm (0))))))
      ((.r0 ↦ᵣ vR0Old) **
      (.r1 ↦ᵣ baseAddr) **
      (effectiveAddr baseAddr 0 ↦U64 oldMemD_0) **
      (.r2 ↦ᵣ vR2Old) **
      (effectiveAddr baseAddr 8 ↦U64 oldMemD_1) **
      (effectiveAddr baseAddr 88 ↦U64 oldMemD_2) **
      (effectiveAddr baseAddr 10344 ↦U64 oldMemD_3) **
      (effectiveAddr baseAddr 10424 ↦U64 oldMemD_4) **
      (effectiveAddr baseAddr 16 ↦U64 oldMemD_5) **
      (effectiveAddr baseAddr 10352 ↦U64 oldMemD_6) **
      (.r3 ↦ᵣ vR3Old) **
      (effectiveAddr baseAddr 20760 ↦U64 oldMemD_7) **
      (effectiveAddr baseAddr 20840 ↦U64 oldMemD_8) **
      (effectiveAddr baseAddr 10384 ↦U64 oldMemD_9) **
      (.r4 ↦ᵣ vR4Old) **
      (effectiveAddr baseAddr 20848 ↦U64 oldMemD_10) **
      (effectiveAddr baseAddr 10392 ↦U64 oldMemD_11) **
      (effectiveAddr baseAddr 20856 ↦U64 oldMemD_12) **
      (effectiveAddr baseAddr 10400 ↦U64 oldMemD_13) **
      (effectiveAddr baseAddr 20864 ↦U64 oldMemD_14) **
      (effectiveAddr baseAddr 10408 ↦U64 oldMemD_15) **
      (effectiveAddr baseAddr 24 ↦U64 oldMemD_16) **
      (.r6 ↦ᵣ vR6Old) **
      (effectiveAddr baseAddr 32 ↦U64 oldMemD_17) **
      (effectiveAddr baseAddr 40 ↦U64 oldMemD_18) **
      (.r5 ↦ᵣ vR5Old) **
      (effectiveAddr baseAddr 10440 ↦U64 oldMemD_19) **
      (effectiveAddr baseAddr 10448 ↦U64 oldMemD_20) **
      (effectiveAddr baseAddr 10456 ↦U64 oldMemD_21) **
      (effectiveAddr baseAddr 10464 ↦U64 oldMemD_22) **
      (effectiveAddr baseAddr 10432 ↦U64 oldMemD_23) **
      (effectiveAddr baseAddr 10472 ↦U64 oldMemD_24) **
      (effectiveAddr baseAddr 20768 ↦U64 oldMemD_25) **
      (effectiveAddr baseAddr 20776 ↦U64 oldMemD_26) **
      (effectiveAddr baseAddr 20792 ↦U64 oldMemD_27) **
      (effectiveAddr baseAddr 20808 ↦U64 oldMemD_28) **
      (effectiveAddr baseAddr 20824 ↦U64 oldMemD_29) **
      (effectiveAddr baseAddr 10480 ↦U64 oldMemD_30) **
      (effectiveAddr baseAddr 10488 ↦U64 oldMemD_31) **
      (effectiveAddr baseAddr 10496 ↦U64 oldMemD_32) **
      (effectiveAddr baseAddr 20816 ↦U64 oldMemD_33) **
      (effectiveAddr baseAddr 20784 ↦U64 oldMemD_34) **
      (effectiveAddr baseAddr 20800 ↦U64 oldMemD_35) **
      (effectiveAddr baseAddr 20832 ↦U64 oldMemD_36) **
      (effectiveAddr baseAddr 10504 ↦U64 oldMemD_37) **
      (.r7 ↦ᵣ vR7Old))
      ((.r0 ↦ᵣ toU64 0) **
      (.r1 ↦ᵣ baseAddr) **
      (effectiveAddr baseAddr 0 ↦U64 oldMemD_0) **
      (.r2 ↦ᵣ wrapAdd oldMemD_30 (toU64 1)) **
      (effectiveAddr baseAddr 8 ↦U64 oldMemD_1) **
      (effectiveAddr baseAddr 88 ↦U64 oldMemD_2) **
      (effectiveAddr baseAddr 10344 ↦U64 oldMemD_3) **
      (effectiveAddr baseAddr 10424 ↦U64 oldMemD_4) **
      (effectiveAddr baseAddr 16 ↦U64 oldMemD_5) **
      (effectiveAddr baseAddr 10352 ↦U64 oldMemD_6) **
      (.r3 ↦ᵣ wrapAdd oldMemD_31 (toU64 1)) **
      (effectiveAddr baseAddr 20760 ↦U64 oldMemD_7) **
      (effectiveAddr baseAddr 20840 ↦U64 oldMemD_8) **
      (effectiveAddr baseAddr 10384 ↦U64 oldMemD_9) **
      (.r4 ↦ᵣ wrapSub oldMemD_32 oldMemD_33) **
      (effectiveAddr baseAddr 20848 ↦U64 oldMemD_10) **
      (effectiveAddr baseAddr 10392 ↦U64 oldMemD_11) **
      (effectiveAddr baseAddr 20856 ↦U64 oldMemD_12) **
      (effectiveAddr baseAddr 10400 ↦U64 oldMemD_13) **
      (effectiveAddr baseAddr 20864 ↦U64 oldMemD_14) **
      (effectiveAddr baseAddr 10408 ↦U64 oldMemD_15) **
      (effectiveAddr baseAddr 24 ↦U64 oldMemD_16) **
      (.r6 ↦ᵣ wrapAdd oldMemD_33 oldMemD_37) **
      (effectiveAddr baseAddr 32 ↦U64 oldMemD_17) **
      (effectiveAddr baseAddr 40 ↦U64 oldMemD_18) **
      (.r5 ↦ᵣ oldMemD_33) **
      (effectiveAddr baseAddr 10440 ↦U64 oldMemD_19) **
      (effectiveAddr baseAddr 10448 ↦U64 oldMemD_20) **
      (effectiveAddr baseAddr 10456 ↦U64 oldMemD_21) **
      (effectiveAddr baseAddr 10464 ↦U64 oldMemD_22) **
      (effectiveAddr baseAddr 10432 ↦U64 oldMemD_23) **
      (effectiveAddr baseAddr 10472 ↦U64 oldMemD_24) **
      (effectiveAddr baseAddr 20768 ↦U64 oldMemD_25) **
      (effectiveAddr baseAddr 20776 ↦U64 oldMemD_26) **
      (effectiveAddr baseAddr 20792 ↦U64 oldMemD_27) **
      (effectiveAddr baseAddr 20808 ↦U64 oldMemD_28) **
      (effectiveAddr baseAddr 20824 ↦U64 oldMemD_29) **
      (effectiveAddr baseAddr 10480 ↦U64 wrapAdd oldMemD_30 (toU64 1)) **
      (effectiveAddr baseAddr 10488 ↦U64 wrapAdd oldMemD_31 (toU64 1)) **
      (effectiveAddr baseAddr 10496 ↦U64 wrapSub oldMemD_32 oldMemD_33) **
      (effectiveAddr baseAddr 20816 ↦U64 oldMemD_33) **
      (effectiveAddr baseAddr 20784 ↦U64 oldMemD_34) **
      (effectiveAddr baseAddr 20800 ↦U64 oldMemD_35) **
      (effectiveAddr baseAddr 20832 ↦U64 oldMemD_36) **
      (effectiveAddr baseAddr 10504 ↦U64 wrapAdd oldMemD_33 oldMemD_37) **
      (.r7 ↦ᵣ ((toU64 0) &&& toU64 1) % U64_MODULUS))
      (fun rt => (((((((((((((((((((((((((((((((((((((((((rt.containsRange (effectiveAddr baseAddr 0) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 8) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 88) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10344) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10424) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 16) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10352) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20760) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20840) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10384) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20848) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10392) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20856) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10400) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20864) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10408) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 24) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 32) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 40) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10440) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10448) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10456) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10464) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10432) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10472) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20768) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20776) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20792) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20808) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20824) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10480) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10488) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10496) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20816) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20784) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20800) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20832) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10504) 8 = true) ∧
                  rt.containsWritable (effectiveAddr baseAddr 10504) 8 = true) ∧
                  rt.containsWritable (effectiveAddr baseAddr 10488) 8 = true) ∧
                  rt.containsWritable (effectiveAddr baseAddr 10480) 8 = true) ∧
                  rt.containsWritable (effectiveAddr baseAddr 10496) 8 = true) := by
  have h_0 := lddw_spec .r0 21474836480 (vR0Old) 0 (by decide)
  have h_1 := jeq_imm_not_taken_spec .r1 0 (baseAddr) 1 118 h_branch0
  have h_2 := ldxdw_spec .r2 .r1 0 (vR2Old) (baseAddr) oldMemD_0 2 (by decide) holdMemD_0_lt
  have h_3 := jne_imm_not_taken_spec .r2 2 (oldMemD_0) 3 118 h_branch1
  have h_4 := ldxdw_spec .r2 .r1 8 (oldMemD_0) (baseAddr) oldMemD_1 4 (by decide) holdMemD_1_lt
  have h_5 := jne_imm_not_taken_spec .r2 511 (oldMemD_1) 5 118 h_branch2
  have h_6 := ldxdw_spec .r2 .r1 88 (oldMemD_1) (baseAddr) oldMemD_2 6 (by decide) holdMemD_2_lt
  have h_7 := jne_imm_not_taken_spec .r2 0 (oldMemD_2) 7 118 h_branch3
  have h_8 := ldxdw_spec .r2 .r1 10344 (oldMemD_2) (baseAddr) oldMemD_3 8 (by decide) holdMemD_3_lt
  have h_9 := jne_imm_not_taken_spec .r2 65791 (oldMemD_3) 9 118 h_branch4
  have h_10 := ldxdw_spec .r2 .r1 10424 (oldMemD_3) (baseAddr) oldMemD_4 10 (by decide) holdMemD_4_lt
  have h_11 := jne_imm_not_taken_spec .r2 80 (oldMemD_4) 11 118 h_branch5
  have h_12 := ldxdw_spec .r2 .r1 16 (oldMemD_4) (baseAddr) oldMemD_5 12 (by decide) holdMemD_5_lt
  have h_13 := ldxdw_spec .r3 .r1 10352 (vR3Old) (baseAddr) oldMemD_6 13 (by decide) holdMemD_6_lt
  have h_14 := jne_reg_taken_spec .r2 .r3 (oldMemD_5) (oldMemD_6) 14 24 h_branch6
  have h_24 := ldxdw_spec .r3 .r1 20760 (oldMemD_6) (baseAddr) oldMemD_7 24 (by decide) holdMemD_7_lt
  have h_25 := jne_imm_not_taken_spec .r3 72 (oldMemD_7) 25 118 h_branch7
  have h_26 := ldxdw_spec .r3 .r1 20840 (oldMemD_7) (baseAddr) oldMemD_8 26 (by decide) holdMemD_8_lt
  have h_27 := ldxdw_spec .r4 .r1 10384 (vR4Old) (baseAddr) oldMemD_9 27 (by decide) holdMemD_9_lt
  have h_28 := jne_reg_not_taken_spec .r4 .r3 (oldMemD_9) (oldMemD_8) 28 118 h_branch8
  have h_29 := ldxdw_spec .r3 .r1 20848 (oldMemD_8) (baseAddr) oldMemD_10 29 (by decide) holdMemD_10_lt
  have h_30 := ldxdw_spec .r4 .r1 10392 (oldMemD_9) (baseAddr) oldMemD_11 30 (by decide) holdMemD_11_lt
  have h_31 := jne_reg_not_taken_spec .r4 .r3 (oldMemD_11) (oldMemD_10) 31 118 h_branch9
  have h_32 := ldxdw_spec .r3 .r1 20856 (oldMemD_10) (baseAddr) oldMemD_12 32 (by decide) holdMemD_12_lt
  have h_33 := ldxdw_spec .r4 .r1 10400 (oldMemD_11) (baseAddr) oldMemD_13 33 (by decide) holdMemD_13_lt
  have h_34 := jne_reg_not_taken_spec .r4 .r3 (oldMemD_13) (oldMemD_12) 34 118 h_branch10
  have h_35 := ldxdw_spec .r3 .r1 20864 (oldMemD_12) (baseAddr) oldMemD_14 35 (by decide) holdMemD_14_lt
  have h_36 := ldxdw_spec .r4 .r1 10408 (oldMemD_13) (baseAddr) oldMemD_15 36 (by decide) holdMemD_15_lt
  have h_37 := jne_reg_not_taken_spec .r4 .r3 (oldMemD_15) (oldMemD_14) 37 118 h_branch11
  have h_38 := ldxdw_spec .r3 .r1 24 (oldMemD_14) (baseAddr) oldMemD_16 38 (by decide) holdMemD_16_lt
  have h_39 := mov64_reg_spec .r6 .r3 (vR6Old) (oldMemD_16) 39 (by decide)
  have h_40 := or64_reg_spec .r6 .r2 (oldMemD_16) (oldMemD_5) 40 (by decide)
  have h_41 := ldxdw_spec .r4 .r1 32 (oldMemD_15) (baseAddr) oldMemD_17 41 (by decide) holdMemD_17_lt
  have h_42 := or64_reg_spec .r6 .r4 ((oldMemD_16 ||| oldMemD_5) % U64_MODULUS) (oldMemD_17) 42 (by decide)
  have h_43 := ldxdw_spec .r5 .r1 40 (vR5Old) (baseAddr) oldMemD_18 43 (by decide) holdMemD_18_lt
  have h_44 := or64_reg_spec .r6 .r5 ((((oldMemD_16 ||| oldMemD_5) % U64_MODULUS) ||| oldMemD_17) % U64_MODULUS) (oldMemD_18) 44 (by decide)
  have h_45 := jeq_imm_not_taken_spec .r6 0 ((((((oldMemD_16 ||| oldMemD_5) % U64_MODULUS) ||| oldMemD_17) % U64_MODULUS) ||| oldMemD_18) % U64_MODULUS) 45 118 h_branch12
  have h_46 := ldxdw_spec .r6 .r1 10440 ((((((oldMemD_16 ||| oldMemD_5) % U64_MODULUS) ||| oldMemD_17) % U64_MODULUS) ||| oldMemD_18) % U64_MODULUS) (baseAddr) oldMemD_19 46 (by decide) holdMemD_19_lt
  have h_47 := jne_reg_not_taken_spec .r2 .r6 (oldMemD_5) (oldMemD_19) 47 118 h_branch13
  have h_48 := ldxdw_spec .r2 .r1 10448 (oldMemD_5) (baseAddr) oldMemD_20 48 (by decide) holdMemD_20_lt
  have h_49 := jne_reg_not_taken_spec .r3 .r2 (oldMemD_16) (oldMemD_20) 49 118 h_branch14
  have h_50 := ldxdw_spec .r2 .r1 10456 (oldMemD_20) (baseAddr) oldMemD_21 50 (by decide) holdMemD_21_lt
  have h_51 := jne_reg_not_taken_spec .r4 .r2 (oldMemD_17) (oldMemD_21) 51 118 h_branch15
  have h_52 := ldxdw_spec .r2 .r1 10464 (oldMemD_21) (baseAddr) oldMemD_22 52 (by decide) holdMemD_22_lt
  have h_53 := jne_reg_not_taken_spec .r5 .r2 (oldMemD_18) (oldMemD_22) 53 118 h_branch16
  have h_54 := ldxdw_spec .r2 .r1 10432 (oldMemD_22) (baseAddr) oldMemD_23 54 (by decide) holdMemD_23_lt
  have h_55 := lddw_spec .r3 5691884356 (oldMemD_16) 55 (by decide)
  have h_56 := jne_reg_not_taken_spec .r2 .r3 (oldMemD_23) (toU64 5691884356) 56 118 h_branch17
  have h_57 := ldxdw_spec .r2 .r1 10472 (oldMemD_23) (baseAddr) oldMemD_24 57 (by decide) holdMemD_24_lt
  have h_58 := lddw_spec .r3 4294967295 (toU64 5691884356) 58 (by decide)
  have h_59 := jgt_reg_not_taken_spec .r2 .r3 (oldMemD_24) (toU64 4294967295) 59 118 h_branch18
  have h_60 := ldxdw_spec .r3 .r1 20768 (toU64 4294967295) (baseAddr) oldMemD_25 60 (by decide) holdMemD_25_lt
  have h_61 := lddw_spec .r4 4403520422724 (oldMemD_17) 61 (by decide)
  have h_62 := jne_reg_not_taken_spec .r3 .r4 (oldMemD_25) (toU64 4403520422724) 62 118 h_branch19
  have h_63 := ldxdw_spec .r3 .r1 20776 (oldMemD_25) (baseAddr) oldMemD_26 63 (by decide) holdMemD_26_lt
  have h_64 := jne_imm_not_taken_spec .r3 0 (oldMemD_26) 64 118 h_branch20
  have h_65 := ldxdw_spec .r3 .r1 20792 (oldMemD_26) (baseAddr) oldMemD_27 65 (by decide) holdMemD_27_lt
  have h_66 := jne_imm_not_taken_spec .r3 256 (oldMemD_27) 66 118 h_branch21
  have h_67 := ldxdw_spec .r3 .r1 20808 (oldMemD_27) (baseAddr) oldMemD_28 67 (by decide) holdMemD_28_lt
  have h_68 := mov64_reg_spec .r4 .r3 (toU64 4403520422724) (oldMemD_28) 68 (by decide)
  have h_69 := lsh64_imm_spec .r4 32 (oldMemD_28) 69 (by decide)
  have h_70 := rsh64_imm_spec .r4 32 ((oldMemD_28 <<< (toU64 32 % 64)) % U64_MODULUS) 70 (by decide)
  have h_71 := jne_imm_not_taken_spec .r4 65537 (((oldMemD_28 <<< (toU64 32 % 64)) % U64_MODULUS) >>> (toU64 32 % 64)) 71 118 h_branch22
  have h_72 := rsh64_imm_spec .r3 32 (oldMemD_28) 72 (by decide)
  have h_73 := jne_reg_not_taken_spec .r3 .r2 (oldMemD_28 >>> (toU64 32 % 64)) (oldMemD_24) 73 118 h_branch23
  have h_74 := ldxdw_spec .r3 .r1 20824 (oldMemD_28 >>> (toU64 32 % 64)) (baseAddr) oldMemD_29 74 (by decide) holdMemD_29_lt
  have h_75 := mov64_reg_spec .r4 .r3 (((oldMemD_28 <<< (toU64 32 % 64)) % U64_MODULUS) >>> (toU64 32 % 64)) (oldMemD_29) 75 (by decide)
  have h_76 := lsh64_imm_spec .r4 32 (oldMemD_29) 76 (by decide)
  have h_77 := rsh64_imm_spec .r4 32 ((oldMemD_29 <<< (toU64 32 % 64)) % U64_MODULUS) 77 (by decide)
  have h_78 := jne_imm_not_taken_spec .r4 65794 (((oldMemD_29 <<< (toU64 32 % 64)) % U64_MODULUS) >>> (toU64 32 % 64)) 78 118 h_branch24
  have h_79 := rsh64_imm_spec .r3 32 (oldMemD_29) 79 (by decide)
  have h_80 := jne_reg_not_taken_spec .r3 .r2 (oldMemD_29 >>> (toU64 32 % 64)) (oldMemD_24) 80 118 h_branch25
  have h_81 := ldxdw_spec .r2 .r1 10480 (oldMemD_24) (baseAddr) oldMemD_30 81 (by decide) holdMemD_30_lt
  have h_82 := add64_imm_spec .r2 1 (oldMemD_30) 82 (by decide)
  have h_83 := mov64_imm_spec .r3 1 (oldMemD_29 >>> (toU64 32 % 64)) 83 (by decide)
  have h_84 := jeq_imm_not_taken_spec .r2 0 (wrapAdd oldMemD_30 (toU64 1)) 84 86 h_branch26
  have h_85 := mov64_imm_spec .r3 0 (toU64 1) 85 (by decide)
  have h_86 := and64_imm_spec .r3 1 (toU64 0) 86 (by decide)
  have h_87 := jne_imm_not_taken_spec .r3 0 (((toU64 0) &&& toU64 1) % U64_MODULUS) 87 118 h_branch27
  have h_88 := ldxdw_spec .r3 .r1 10488 (((toU64 0) &&& toU64 1) % U64_MODULUS) (baseAddr) oldMemD_31 88 (by decide) holdMemD_31_lt
  have h_89 := add64_imm_spec .r3 1 (oldMemD_31) 89 (by decide)
  have h_90 := mov64_imm_spec .r4 1 (((oldMemD_29 <<< (toU64 32 % 64)) % U64_MODULUS) >>> (toU64 32 % 64)) 90 (by decide)
  have h_91 := jeq_imm_not_taken_spec .r3 0 (wrapAdd oldMemD_31 (toU64 1)) 91 93 h_branch28
  have h_92 := mov64_imm_spec .r4 0 (toU64 1) 92 (by decide)
  have h_93 := and64_imm_spec .r4 1 (toU64 0) 93 (by decide)
  have h_94 := jne_imm_not_taken_spec .r4 0 (((toU64 0) &&& toU64 1) % U64_MODULUS) 94 118 h_branch29
  have h_95 := ldxdw_spec .r4 .r1 10496 (((toU64 0) &&& toU64 1) % U64_MODULUS) (baseAddr) oldMemD_32 95 (by decide) holdMemD_32_lt
  have h_96 := ldxdw_spec .r5 .r1 20816 (oldMemD_18) (baseAddr) oldMemD_33 96 (by decide) holdMemD_33_lt
  have h_97 := jlt_reg_not_taken_spec .r4 .r5 (oldMemD_32) (oldMemD_33) 97 118 h_branch30
  have h_98 := ldxdw_spec .r6 .r1 20784 (oldMemD_19) (baseAddr) oldMemD_34 98 (by decide) holdMemD_34_lt
  have h_99 := jne_reg_not_taken_spec .r6 .r2 (oldMemD_34) (wrapAdd oldMemD_30 (toU64 1)) 99 118 h_branch31
  have h_100 := ldxdw_spec .r6 .r1 20800 (oldMemD_34) (baseAddr) oldMemD_35 100 (by decide) holdMemD_35_lt
  have h_101 := jne_reg_not_taken_spec .r6 .r3 (oldMemD_35) (wrapAdd oldMemD_31 (toU64 1)) 101 118 h_branch32
  have h_102 := ldxdw_spec .r6 .r1 20832 (oldMemD_35) (baseAddr) oldMemD_36 102 (by decide) holdMemD_36_lt
  have h_103 := jne_reg_not_taken_spec .r5 .r6 (oldMemD_33) (oldMemD_36) 103 118 h_branch33
  have h_104 := ldxdw_spec .r7 .r1 10504 (vR7Old) (baseAddr) oldMemD_37 104 (by decide) holdMemD_37_lt
  have h_105 := mov64_reg_spec .r6 .r5 (oldMemD_36) (oldMemD_33) 105 (by decide)
  have h_106 := add64_reg_spec .r6 .r7 (oldMemD_33) (oldMemD_37) 106 (by decide)
  have h_107 := mov64_imm_spec .r7 1 (oldMemD_37) 107 (by decide)
  have h_108 := jlt_reg_not_taken_spec .r6 .r5 (wrapAdd oldMemD_33 oldMemD_37) (oldMemD_33) 108 110 h_branch34
  have h_109 := mov64_imm_spec .r7 0 (toU64 1) 109 (by decide)
  have h_110 := and64_imm_spec .r7 1 (toU64 0) 110 (by decide)
  have h_111 := jne_imm_not_taken_spec .r7 0 (((toU64 0) &&& toU64 1) % U64_MODULUS) 111 118 h_branch35
  have h_112 := stxdw_spec .r1 .r6 10504 (baseAddr) (wrapAdd oldMemD_33 oldMemD_37) oldMemD_37 112
  have h_113 := stxdw_spec .r1 .r3 10488 (baseAddr) (wrapAdd oldMemD_31 (toU64 1)) oldMemD_31 113
  have h_114 := stxdw_spec .r1 .r2 10480 (baseAddr) (wrapAdd oldMemD_30 (toU64 1)) oldMemD_30 114
  have h_115 := sub64_reg_spec .r4 .r5 (oldMemD_32) (oldMemD_33) 115 (by decide)
  have h_116 := stxdw_spec .r1 .r4 10496 (baseAddr) (wrapSub oldMemD_32 oldMemD_33) oldMemD_32 116
  have h_117 := mov64_imm_spec .r0 0 (toU64 21474836480) 117 (by decide)
  sl_block_iter [h_0, h_1, h_2, h_3, h_4, h_5, h_6, h_7, h_8, h_9, h_10, h_11, h_12, h_13, h_14, h_24, h_25, h_26, h_27, h_28, h_29, h_30, h_31, h_32, h_33, h_34, h_35, h_36, h_37, h_38, h_39, h_40, h_41, h_42, h_43, h_44, h_45, h_46, h_47, h_48, h_49, h_50, h_51, h_52, h_53, h_54, h_55, h_56, h_57, h_58, h_59, h_60, h_61, h_62, h_63, h_64, h_65, h_66, h_67, h_68, h_69, h_70, h_71, h_72, h_73, h_74, h_75, h_76, h_77, h_78, h_79, h_80, h_81, h_82, h_83, h_84, h_85, h_86, h_87, h_88, h_89, h_90, h_91, h_92, h_93, h_94, h_95, h_96, h_97, h_98, h_99, h_100, h_101, h_102, h_103, h_104, h_105, h_106, h_107, h_108, h_109, h_110, h_111, h_112, h_113, h_114, h_115, h_116, h_117] generalizing [((toU64 0) &&& toU64 1) % U64_MODULUS, wrapSub oldMemD_32 oldMemD_33, wrapAdd oldMemD_33 oldMemD_37, wrapAdd oldMemD_30 (toU64 1), wrapAdd oldMemD_31 (toU64 1)]

/-! ## Satisfiability witness (soundness-audit H8)

The triple's precondition is SATISFIABLE at the concrete
assignment below — an overlapping (vacuous) sepConj would fail
`native_decide` here, so vacuity cannot ship. The guards pin
each `addrK` literal to its `h_addrK` defining equation at the
assignment; the witness goal is the theorem's precondition with
the variables instantiated, so the reflected `SatWitness` atoms
are tied to the real pre by the elaborator's defeq check.
Value-level path hypotheses (`h_branch*`) are not certified
consistent — they are outside the overlap-vacuity class this
guards against. -/

open Memory in
example : ∃ s,
    ((.r0 ↦ᵣ 0) **
      (.r1 ↦ᵣ 17179869184) **
      (effectiveAddr 17179869184 0 ↦U64 0) **
      (.r2 ↦ᵣ 0) **
      (effectiveAddr 17179869184 8 ↦U64 0) **
      (effectiveAddr 17179869184 88 ↦U64 0) **
      (effectiveAddr 17179869184 10344 ↦U64 0) **
      (effectiveAddr 17179869184 10424 ↦U64 0) **
      (effectiveAddr 17179869184 16 ↦U64 0) **
      (effectiveAddr 17179869184 10352 ↦U64 0) **
      (.r3 ↦ᵣ 0) **
      (effectiveAddr 17179869184 20760 ↦U64 0) **
      (effectiveAddr 17179869184 20840 ↦U64 0) **
      (effectiveAddr 17179869184 10384 ↦U64 0) **
      (.r4 ↦ᵣ 0) **
      (effectiveAddr 17179869184 20848 ↦U64 0) **
      (effectiveAddr 17179869184 10392 ↦U64 0) **
      (effectiveAddr 17179869184 20856 ↦U64 0) **
      (effectiveAddr 17179869184 10400 ↦U64 0) **
      (effectiveAddr 17179869184 20864 ↦U64 0) **
      (effectiveAddr 17179869184 10408 ↦U64 0) **
      (effectiveAddr 17179869184 24 ↦U64 0) **
      (.r6 ↦ᵣ 0) **
      (effectiveAddr 17179869184 32 ↦U64 0) **
      (effectiveAddr 17179869184 40 ↦U64 0) **
      (.r5 ↦ᵣ 0) **
      (effectiveAddr 17179869184 10440 ↦U64 0) **
      (effectiveAddr 17179869184 10448 ↦U64 0) **
      (effectiveAddr 17179869184 10456 ↦U64 0) **
      (effectiveAddr 17179869184 10464 ↦U64 0) **
      (effectiveAddr 17179869184 10432 ↦U64 0) **
      (effectiveAddr 17179869184 10472 ↦U64 0) **
      (effectiveAddr 17179869184 20768 ↦U64 0) **
      (effectiveAddr 17179869184 20776 ↦U64 0) **
      (effectiveAddr 17179869184 20792 ↦U64 0) **
      (effectiveAddr 17179869184 20808 ↦U64 0) **
      (effectiveAddr 17179869184 20824 ↦U64 0) **
      (effectiveAddr 17179869184 10480 ↦U64 0) **
      (effectiveAddr 17179869184 10488 ↦U64 0) **
      (effectiveAddr 17179869184 10496 ↦U64 0) **
      (effectiveAddr 17179869184 20816 ↦U64 0) **
      (effectiveAddr 17179869184 20784 ↦U64 0) **
      (effectiveAddr 17179869184 20800 ↦U64 0) **
      (effectiveAddr 17179869184 20832 ↦U64 0) **
      (effectiveAddr 17179869184 10504 ↦U64 0) **
      (.r7 ↦ᵣ 0)) s := by
  have w := SatWitness.sat_witness
    [.reg .r0 0,
     .reg .r1 17179869184,
     .u64 17179869184 0,
     .reg .r2 0,
     .u64 17179869192 0,
     .u64 17179869272 0,
     .u64 17179879528 0,
     .u64 17179879608 0,
     .u64 17179869200 0,
     .u64 17179879536 0,
     .reg .r3 0,
     .u64 17179889944 0,
     .u64 17179890024 0,
     .u64 17179879568 0,
     .reg .r4 0,
     .u64 17179890032 0,
     .u64 17179879576 0,
     .u64 17179890040 0,
     .u64 17179879584 0,
     .u64 17179890048 0,
     .u64 17179879592 0,
     .u64 17179869208 0,
     .reg .r6 0,
     .u64 17179869216 0,
     .u64 17179869224 0,
     .reg .r5 0,
     .u64 17179879624 0,
     .u64 17179879632 0,
     .u64 17179879640 0,
     .u64 17179879648 0,
     .u64 17179879616 0,
     .u64 17179879656 0,
     .u64 17179889952 0,
     .u64 17179889960 0,
     .u64 17179889976 0,
     .u64 17179889992 0,
     .u64 17179890008 0,
     .u64 17179879664 0,
     .u64 17179879672 0,
     .u64 17179879680 0,
     .u64 17179890000 0,
     .u64 17179889968 0,
     .u64 17179889984 0,
     .u64 17179890016 0,
     .u64 17179879688 0,
     .reg .r7 0]
    (by native_decide)
  exact w

open Memory in
theorem DclutchClaimsProofSbfLifted_balance_correct
    (vR0Old baseAddr oldMemD_0 vR2Old oldMemD_1 oldMemD_2 oldMemD_3 oldMemD_4 oldMemD_5 oldMemD_6 vR3Old oldMemD_7 oldMemD_8 oldMemD_9 vR4Old oldMemD_10 oldMemD_11 oldMemD_12 oldMemD_13 oldMemD_14 oldMemD_15 oldMemD_16 vR6Old oldMemD_17 oldMemD_18 vR5Old oldMemD_19 oldMemD_20 oldMemD_21 oldMemD_22 oldMemD_23 oldMemD_24 oldMemD_25 oldMemD_26 oldMemD_27 oldMemD_28 oldMemD_29 oldMemD_30 oldMemD_31 oldMemD_32 oldMemD_33 oldMemD_34 oldMemD_35 oldMemD_36 oldMemD_37 vR7Old : Nat)
    (holdMemD_0_lt : oldMemD_0 < 2 ^ 64)
    (holdMemD_1_lt : oldMemD_1 < 2 ^ 64)
    (holdMemD_2_lt : oldMemD_2 < 2 ^ 64)
    (holdMemD_3_lt : oldMemD_3 < 2 ^ 64)
    (holdMemD_4_lt : oldMemD_4 < 2 ^ 64)
    (holdMemD_5_lt : oldMemD_5 < 2 ^ 64)
    (holdMemD_6_lt : oldMemD_6 < 2 ^ 64)
    (holdMemD_7_lt : oldMemD_7 < 2 ^ 64)
    (holdMemD_8_lt : oldMemD_8 < 2 ^ 64)
    (holdMemD_9_lt : oldMemD_9 < 2 ^ 64)
    (holdMemD_10_lt : oldMemD_10 < 2 ^ 64)
    (holdMemD_11_lt : oldMemD_11 < 2 ^ 64)
    (holdMemD_12_lt : oldMemD_12 < 2 ^ 64)
    (holdMemD_13_lt : oldMemD_13 < 2 ^ 64)
    (holdMemD_14_lt : oldMemD_14 < 2 ^ 64)
    (holdMemD_15_lt : oldMemD_15 < 2 ^ 64)
    (holdMemD_16_lt : oldMemD_16 < 2 ^ 64)
    (holdMemD_17_lt : oldMemD_17 < 2 ^ 64)
    (holdMemD_18_lt : oldMemD_18 < 2 ^ 64)
    (holdMemD_19_lt : oldMemD_19 < 2 ^ 64)
    (holdMemD_20_lt : oldMemD_20 < 2 ^ 64)
    (holdMemD_21_lt : oldMemD_21 < 2 ^ 64)
    (holdMemD_22_lt : oldMemD_22 < 2 ^ 64)
    (holdMemD_23_lt : oldMemD_23 < 2 ^ 64)
    (holdMemD_24_lt : oldMemD_24 < 2 ^ 64)
    (holdMemD_25_lt : oldMemD_25 < 2 ^ 64)
    (holdMemD_26_lt : oldMemD_26 < 2 ^ 64)
    (holdMemD_27_lt : oldMemD_27 < 2 ^ 64)
    (holdMemD_28_lt : oldMemD_28 < 2 ^ 64)
    (holdMemD_29_lt : oldMemD_29 < 2 ^ 64)
    (holdMemD_30_lt : oldMemD_30 < 2 ^ 64)
    (holdMemD_31_lt : oldMemD_31 < 2 ^ 64)
    (holdMemD_32_lt : oldMemD_32 < 2 ^ 64)
    (holdMemD_33_lt : oldMemD_33 < 2 ^ 64)
    (holdMemD_34_lt : oldMemD_34 < 2 ^ 64)
    (holdMemD_35_lt : oldMemD_35 < 2 ^ 64)
    (holdMemD_36_lt : oldMemD_36 < 2 ^ 64)
    (holdMemD_37_lt : oldMemD_37 < 2 ^ 64)
    (h_branch0 : baseAddr ≠ toU64 0)
    (h_branch1 : oldMemD_0 = toU64 2)
    (h_branch2 : oldMemD_1 = toU64 511)
    (h_branch3 : oldMemD_2 = toU64 0)
    (h_branch4 : oldMemD_3 = toU64 65791)
    (h_branch5 : oldMemD_4 = toU64 80)
    (h_branch6 : oldMemD_5 ≠ oldMemD_6)
    (h_branch7 : oldMemD_7 = toU64 72)
    (h_branch8 : oldMemD_9 = oldMemD_8)
    (h_branch9 : oldMemD_11 = oldMemD_10)
    (h_branch10 : oldMemD_13 = oldMemD_12)
    (h_branch11 : oldMemD_15 = oldMemD_14)
    (h_branch12 : (((((oldMemD_16 ||| oldMemD_5) % U64_MODULUS) ||| oldMemD_17) % U64_MODULUS) ||| oldMemD_18) % U64_MODULUS ≠ toU64 0)
    (h_branch13 : oldMemD_5 = oldMemD_19)
    (h_branch14 : oldMemD_16 = oldMemD_20)
    (h_branch15 : oldMemD_17 = oldMemD_21)
    (h_branch16 : oldMemD_18 = oldMemD_22)
    (h_branch17 : oldMemD_23 = toU64 5691884356)
    (h_branch18 : ¬ oldMemD_24 > toU64 4294967295)
    (h_branch19 : oldMemD_25 = toU64 4403520422724)
    (h_branch20 : oldMemD_26 = toU64 0)
    (h_branch21 : oldMemD_27 = toU64 256)
    (h_branch22 : ((oldMemD_28 <<< (toU64 32 % 64)) % U64_MODULUS) >>> (toU64 32 % 64) = toU64 65537)
    (h_branch23 : oldMemD_28 >>> (toU64 32 % 64) = oldMemD_24)
    (h_branch24 : ((oldMemD_29 <<< (toU64 32 % 64)) % U64_MODULUS) >>> (toU64 32 % 64) = toU64 65794)
    (h_branch25 : oldMemD_29 >>> (toU64 32 % 64) = oldMemD_24)
    (h_branch26 : wrapAdd oldMemD_30 (toU64 1) ≠ toU64 0)
    (h_branch27 : ((toU64 0) &&& toU64 1) % U64_MODULUS = toU64 0)
    (h_branch28 : wrapAdd oldMemD_31 (toU64 1) ≠ toU64 0)
    (h_branch29 : ((toU64 0) &&& toU64 1) % U64_MODULUS = toU64 0)
    (h_branch30 : ¬ oldMemD_32 < oldMemD_33)
    (h_branch31 : oldMemD_34 = wrapAdd oldMemD_30 (toU64 1))
    (h_branch32 : oldMemD_35 = wrapAdd oldMemD_31 (toU64 1))
    (h_branch33 : oldMemD_33 = oldMemD_36)
    (h_branch34 : ¬ wrapAdd oldMemD_33 oldMemD_37 < oldMemD_33)
    (h_branch35 : ((toU64 0) &&& toU64 1) % U64_MODULUS = toU64 0)
    (h_funds0 : oldMemD_33 ≤ oldMemD_32)
    (h_src_lt0 : oldMemD_32 < 2 ^ 64)
    (h_noovf1 : oldMemD_33 + oldMemD_37 < 2 ^ 64)
    : cuTripleWithinMem 109 0 0 118
      ((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((CodeReq.singleton 0 (.lddw .r0 (21474836480))).union
        (CodeReq.singleton 1 (.jeq .r1 (.imm (0)) 118))).union
        (CodeReq.singleton 2 (.ldx .dword .r2 .r1 0))).union
        (CodeReq.singleton 3 (.jne .r2 (.imm (2)) 118))).union
        (CodeReq.singleton 4 (.ldx .dword .r2 .r1 8))).union
        (CodeReq.singleton 5 (.jne .r2 (.imm (511)) 118))).union
        (CodeReq.singleton 6 (.ldx .dword .r2 .r1 88))).union
        (CodeReq.singleton 7 (.jne .r2 (.imm (0)) 118))).union
        (CodeReq.singleton 8 (.ldx .dword .r2 .r1 10344))).union
        (CodeReq.singleton 9 (.jne .r2 (.imm (65791)) 118))).union
        (CodeReq.singleton 10 (.ldx .dword .r2 .r1 10424))).union
        (CodeReq.singleton 11 (.jne .r2 (.imm (80)) 118))).union
        (CodeReq.singleton 12 (.ldx .dword .r2 .r1 16))).union
        (CodeReq.singleton 13 (.ldx .dword .r3 .r1 10352))).union
        (CodeReq.singleton 14 (.jne .r2 (.reg .r3) 24))).union
        (CodeReq.singleton 24 (.ldx .dword .r3 .r1 20760))).union
        (CodeReq.singleton 25 (.jne .r3 (.imm (72)) 118))).union
        (CodeReq.singleton 26 (.ldx .dword .r3 .r1 20840))).union
        (CodeReq.singleton 27 (.ldx .dword .r4 .r1 10384))).union
        (CodeReq.singleton 28 (.jne .r4 (.reg .r3) 118))).union
        (CodeReq.singleton 29 (.ldx .dword .r3 .r1 20848))).union
        (CodeReq.singleton 30 (.ldx .dword .r4 .r1 10392))).union
        (CodeReq.singleton 31 (.jne .r4 (.reg .r3) 118))).union
        (CodeReq.singleton 32 (.ldx .dword .r3 .r1 20856))).union
        (CodeReq.singleton 33 (.ldx .dword .r4 .r1 10400))).union
        (CodeReq.singleton 34 (.jne .r4 (.reg .r3) 118))).union
        (CodeReq.singleton 35 (.ldx .dword .r3 .r1 20864))).union
        (CodeReq.singleton 36 (.ldx .dword .r4 .r1 10408))).union
        (CodeReq.singleton 37 (.jne .r4 (.reg .r3) 118))).union
        (CodeReq.singleton 38 (.ldx .dword .r3 .r1 24))).union
        (CodeReq.singleton 39 (.mov64 .r6 (.reg .r3)))).union
        (CodeReq.singleton 40 (.or64 .r6 (.reg .r2)))).union
        (CodeReq.singleton 41 (.ldx .dword .r4 .r1 32))).union
        (CodeReq.singleton 42 (.or64 .r6 (.reg .r4)))).union
        (CodeReq.singleton 43 (.ldx .dword .r5 .r1 40))).union
        (CodeReq.singleton 44 (.or64 .r6 (.reg .r5)))).union
        (CodeReq.singleton 45 (.jeq .r6 (.imm (0)) 118))).union
        (CodeReq.singleton 46 (.ldx .dword .r6 .r1 10440))).union
        (CodeReq.singleton 47 (.jne .r2 (.reg .r6) 118))).union
        (CodeReq.singleton 48 (.ldx .dword .r2 .r1 10448))).union
        (CodeReq.singleton 49 (.jne .r3 (.reg .r2) 118))).union
        (CodeReq.singleton 50 (.ldx .dword .r2 .r1 10456))).union
        (CodeReq.singleton 51 (.jne .r4 (.reg .r2) 118))).union
        (CodeReq.singleton 52 (.ldx .dword .r2 .r1 10464))).union
        (CodeReq.singleton 53 (.jne .r5 (.reg .r2) 118))).union
        (CodeReq.singleton 54 (.ldx .dword .r2 .r1 10432))).union
        (CodeReq.singleton 55 (.lddw .r3 (5691884356)))).union
        (CodeReq.singleton 56 (.jne .r2 (.reg .r3) 118))).union
        (CodeReq.singleton 57 (.ldx .dword .r2 .r1 10472))).union
        (CodeReq.singleton 58 (.lddw .r3 (4294967295)))).union
        (CodeReq.singleton 59 (.jgt .r2 (.reg .r3) 118))).union
        (CodeReq.singleton 60 (.ldx .dword .r3 .r1 20768))).union
        (CodeReq.singleton 61 (.lddw .r4 (4403520422724)))).union
        (CodeReq.singleton 62 (.jne .r3 (.reg .r4) 118))).union
        (CodeReq.singleton 63 (.ldx .dword .r3 .r1 20776))).union
        (CodeReq.singleton 64 (.jne .r3 (.imm (0)) 118))).union
        (CodeReq.singleton 65 (.ldx .dword .r3 .r1 20792))).union
        (CodeReq.singleton 66 (.jne .r3 (.imm (256)) 118))).union
        (CodeReq.singleton 67 (.ldx .dword .r3 .r1 20808))).union
        (CodeReq.singleton 68 (.mov64 .r4 (.reg .r3)))).union
        (CodeReq.singleton 69 (.lsh64 .r4 (.imm (32))))).union
        (CodeReq.singleton 70 (.rsh64 .r4 (.imm (32))))).union
        (CodeReq.singleton 71 (.jne .r4 (.imm (65537)) 118))).union
        (CodeReq.singleton 72 (.rsh64 .r3 (.imm (32))))).union
        (CodeReq.singleton 73 (.jne .r3 (.reg .r2) 118))).union
        (CodeReq.singleton 74 (.ldx .dword .r3 .r1 20824))).union
        (CodeReq.singleton 75 (.mov64 .r4 (.reg .r3)))).union
        (CodeReq.singleton 76 (.lsh64 .r4 (.imm (32))))).union
        (CodeReq.singleton 77 (.rsh64 .r4 (.imm (32))))).union
        (CodeReq.singleton 78 (.jne .r4 (.imm (65794)) 118))).union
        (CodeReq.singleton 79 (.rsh64 .r3 (.imm (32))))).union
        (CodeReq.singleton 80 (.jne .r3 (.reg .r2) 118))).union
        (CodeReq.singleton 81 (.ldx .dword .r2 .r1 10480))).union
        (CodeReq.singleton 82 (.add64 .r2 (.imm (1))))).union
        (CodeReq.singleton 83 (.mov64 .r3 (.imm (1))))).union
        (CodeReq.singleton 84 (.jeq .r2 (.imm (0)) 86))).union
        (CodeReq.singleton 85 (.mov64 .r3 (.imm (0))))).union
        (CodeReq.singleton 86 (.and64 .r3 (.imm (1))))).union
        (CodeReq.singleton 87 (.jne .r3 (.imm (0)) 118))).union
        (CodeReq.singleton 88 (.ldx .dword .r3 .r1 10488))).union
        (CodeReq.singleton 89 (.add64 .r3 (.imm (1))))).union
        (CodeReq.singleton 90 (.mov64 .r4 (.imm (1))))).union
        (CodeReq.singleton 91 (.jeq .r3 (.imm (0)) 93))).union
        (CodeReq.singleton 92 (.mov64 .r4 (.imm (0))))).union
        (CodeReq.singleton 93 (.and64 .r4 (.imm (1))))).union
        (CodeReq.singleton 94 (.jne .r4 (.imm (0)) 118))).union
        (CodeReq.singleton 95 (.ldx .dword .r4 .r1 10496))).union
        (CodeReq.singleton 96 (.ldx .dword .r5 .r1 20816))).union
        (CodeReq.singleton 97 (.jlt .r4 (.reg .r5) 118))).union
        (CodeReq.singleton 98 (.ldx .dword .r6 .r1 20784))).union
        (CodeReq.singleton 99 (.jne .r6 (.reg .r2) 118))).union
        (CodeReq.singleton 100 (.ldx .dword .r6 .r1 20800))).union
        (CodeReq.singleton 101 (.jne .r6 (.reg .r3) 118))).union
        (CodeReq.singleton 102 (.ldx .dword .r6 .r1 20832))).union
        (CodeReq.singleton 103 (.jne .r5 (.reg .r6) 118))).union
        (CodeReq.singleton 104 (.ldx .dword .r7 .r1 10504))).union
        (CodeReq.singleton 105 (.mov64 .r6 (.reg .r5)))).union
        (CodeReq.singleton 106 (.add64 .r6 (.reg .r7)))).union
        (CodeReq.singleton 107 (.mov64 .r7 (.imm (1))))).union
        (CodeReq.singleton 108 (.jlt .r6 (.reg .r5) 110))).union
        (CodeReq.singleton 109 (.mov64 .r7 (.imm (0))))).union
        (CodeReq.singleton 110 (.and64 .r7 (.imm (1))))).union
        (CodeReq.singleton 111 (.jne .r7 (.imm (0)) 118))).union
        (CodeReq.singleton 112 (.stx .dword .r1 10504 .r6))).union
        (CodeReq.singleton 113 (.stx .dword .r1 10488 .r3))).union
        (CodeReq.singleton 114 (.stx .dword .r1 10480 .r2))).union
        (CodeReq.singleton 115 (.sub64 .r4 (.reg .r5)))).union
        (CodeReq.singleton 116 (.stx .dword .r1 10496 .r4))).union
        (CodeReq.singleton 117 (.mov64 .r0 (.imm (0))))))
      ((.r0 ↦ᵣ vR0Old) **
      (.r1 ↦ᵣ baseAddr) **
      (effectiveAddr baseAddr 0 ↦U64 oldMemD_0) **
      (.r2 ↦ᵣ vR2Old) **
      (effectiveAddr baseAddr 8 ↦U64 oldMemD_1) **
      (effectiveAddr baseAddr 88 ↦U64 oldMemD_2) **
      (effectiveAddr baseAddr 10344 ↦U64 oldMemD_3) **
      (effectiveAddr baseAddr 10424 ↦U64 oldMemD_4) **
      (effectiveAddr baseAddr 16 ↦U64 oldMemD_5) **
      (effectiveAddr baseAddr 10352 ↦U64 oldMemD_6) **
      (.r3 ↦ᵣ vR3Old) **
      (effectiveAddr baseAddr 20760 ↦U64 oldMemD_7) **
      (effectiveAddr baseAddr 20840 ↦U64 oldMemD_8) **
      (effectiveAddr baseAddr 10384 ↦U64 oldMemD_9) **
      (.r4 ↦ᵣ vR4Old) **
      (effectiveAddr baseAddr 20848 ↦U64 oldMemD_10) **
      (effectiveAddr baseAddr 10392 ↦U64 oldMemD_11) **
      (effectiveAddr baseAddr 20856 ↦U64 oldMemD_12) **
      (effectiveAddr baseAddr 10400 ↦U64 oldMemD_13) **
      (effectiveAddr baseAddr 20864 ↦U64 oldMemD_14) **
      (effectiveAddr baseAddr 10408 ↦U64 oldMemD_15) **
      (effectiveAddr baseAddr 24 ↦U64 oldMemD_16) **
      (.r6 ↦ᵣ vR6Old) **
      (effectiveAddr baseAddr 32 ↦U64 oldMemD_17) **
      (effectiveAddr baseAddr 40 ↦U64 oldMemD_18) **
      (.r5 ↦ᵣ vR5Old) **
      (effectiveAddr baseAddr 10440 ↦U64 oldMemD_19) **
      (effectiveAddr baseAddr 10448 ↦U64 oldMemD_20) **
      (effectiveAddr baseAddr 10456 ↦U64 oldMemD_21) **
      (effectiveAddr baseAddr 10464 ↦U64 oldMemD_22) **
      (effectiveAddr baseAddr 10432 ↦U64 oldMemD_23) **
      (effectiveAddr baseAddr 10472 ↦U64 oldMemD_24) **
      (effectiveAddr baseAddr 20768 ↦U64 oldMemD_25) **
      (effectiveAddr baseAddr 20776 ↦U64 oldMemD_26) **
      (effectiveAddr baseAddr 20792 ↦U64 oldMemD_27) **
      (effectiveAddr baseAddr 20808 ↦U64 oldMemD_28) **
      (effectiveAddr baseAddr 20824 ↦U64 oldMemD_29) **
      (effectiveAddr baseAddr 10480 ↦U64 oldMemD_30) **
      (effectiveAddr baseAddr 10488 ↦U64 oldMemD_31) **
      (effectiveAddr baseAddr 10496 ↦U64 oldMemD_32) **
      (effectiveAddr baseAddr 20816 ↦U64 oldMemD_33) **
      (effectiveAddr baseAddr 20784 ↦U64 oldMemD_34) **
      (effectiveAddr baseAddr 20800 ↦U64 oldMemD_35) **
      (effectiveAddr baseAddr 20832 ↦U64 oldMemD_36) **
      (effectiveAddr baseAddr 10504 ↦U64 oldMemD_37) **
      (.r7 ↦ᵣ vR7Old))
      ((.r0 ↦ᵣ toU64 0) **
      (.r1 ↦ᵣ baseAddr) **
      (effectiveAddr baseAddr 0 ↦U64 oldMemD_0) **
      (.r2 ↦ᵣ wrapAdd oldMemD_30 (toU64 1)) **
      (effectiveAddr baseAddr 8 ↦U64 oldMemD_1) **
      (effectiveAddr baseAddr 88 ↦U64 oldMemD_2) **
      (effectiveAddr baseAddr 10344 ↦U64 oldMemD_3) **
      (effectiveAddr baseAddr 10424 ↦U64 oldMemD_4) **
      (effectiveAddr baseAddr 16 ↦U64 oldMemD_5) **
      (effectiveAddr baseAddr 10352 ↦U64 oldMemD_6) **
      (.r3 ↦ᵣ wrapAdd oldMemD_31 (toU64 1)) **
      (effectiveAddr baseAddr 20760 ↦U64 oldMemD_7) **
      (effectiveAddr baseAddr 20840 ↦U64 oldMemD_8) **
      (effectiveAddr baseAddr 10384 ↦U64 oldMemD_9) **
      (.r4 ↦ᵣ wrapSub oldMemD_32 oldMemD_33) **
      (effectiveAddr baseAddr 20848 ↦U64 oldMemD_10) **
      (effectiveAddr baseAddr 10392 ↦U64 oldMemD_11) **
      (effectiveAddr baseAddr 20856 ↦U64 oldMemD_12) **
      (effectiveAddr baseAddr 10400 ↦U64 oldMemD_13) **
      (effectiveAddr baseAddr 20864 ↦U64 oldMemD_14) **
      (effectiveAddr baseAddr 10408 ↦U64 oldMemD_15) **
      (effectiveAddr baseAddr 24 ↦U64 oldMemD_16) **
      (.r6 ↦ᵣ wrapAdd oldMemD_33 oldMemD_37) **
      (effectiveAddr baseAddr 32 ↦U64 oldMemD_17) **
      (effectiveAddr baseAddr 40 ↦U64 oldMemD_18) **
      (.r5 ↦ᵣ oldMemD_33) **
      (effectiveAddr baseAddr 10440 ↦U64 oldMemD_19) **
      (effectiveAddr baseAddr 10448 ↦U64 oldMemD_20) **
      (effectiveAddr baseAddr 10456 ↦U64 oldMemD_21) **
      (effectiveAddr baseAddr 10464 ↦U64 oldMemD_22) **
      (effectiveAddr baseAddr 10432 ↦U64 oldMemD_23) **
      (effectiveAddr baseAddr 10472 ↦U64 oldMemD_24) **
      (effectiveAddr baseAddr 20768 ↦U64 oldMemD_25) **
      (effectiveAddr baseAddr 20776 ↦U64 oldMemD_26) **
      (effectiveAddr baseAddr 20792 ↦U64 oldMemD_27) **
      (effectiveAddr baseAddr 20808 ↦U64 oldMemD_28) **
      (effectiveAddr baseAddr 20824 ↦U64 oldMemD_29) **
      (effectiveAddr baseAddr 10480 ↦U64 wrapAdd oldMemD_30 (toU64 1)) **
      (effectiveAddr baseAddr 10488 ↦U64 wrapAdd oldMemD_31 (toU64 1)) **
      (effectiveAddr baseAddr 10496 ↦U64 oldMemD_32 - oldMemD_33) **
      (effectiveAddr baseAddr 20816 ↦U64 oldMemD_33) **
      (effectiveAddr baseAddr 20784 ↦U64 oldMemD_34) **
      (effectiveAddr baseAddr 20800 ↦U64 oldMemD_35) **
      (effectiveAddr baseAddr 20832 ↦U64 oldMemD_36) **
      (effectiveAddr baseAddr 10504 ↦U64 oldMemD_33 + oldMemD_37) **
      (.r7 ↦ᵣ ((toU64 0) &&& toU64 1) % U64_MODULUS))
      (fun rt => (((((((((((((((((((((((((((((((((((((((((rt.containsRange (effectiveAddr baseAddr 0) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 8) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 88) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10344) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10424) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 16) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10352) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20760) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20840) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10384) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20848) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10392) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20856) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10400) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20864) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10408) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 24) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 32) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 40) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10440) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10448) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10456) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10464) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10432) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10472) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20768) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20776) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20792) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20808) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20824) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10480) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10488) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10496) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20816) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20784) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20800) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 20832) 8 = true) ∧
                  rt.containsRange (effectiveAddr baseAddr 10504) 8 = true) ∧
                  rt.containsWritable (effectiveAddr baseAddr 10504) 8 = true) ∧
                  rt.containsWritable (effectiveAddr baseAddr 10488) 8 = true) ∧
                  rt.containsWritable (effectiveAddr baseAddr 10480) 8 = true) ∧
                  rt.containsWritable (effectiveAddr baseAddr 10496) 8 = true) := by
  have h := DclutchClaimsProofSbfLifted_lifted_spec vR0Old baseAddr oldMemD_0 vR2Old oldMemD_1 oldMemD_2 oldMemD_3 oldMemD_4 oldMemD_5 oldMemD_6 vR3Old oldMemD_7 oldMemD_8 oldMemD_9 vR4Old oldMemD_10 oldMemD_11 oldMemD_12 oldMemD_13 oldMemD_14 oldMemD_15 oldMemD_16 vR6Old oldMemD_17 oldMemD_18 vR5Old oldMemD_19 oldMemD_20 oldMemD_21 oldMemD_22 oldMemD_23 oldMemD_24 oldMemD_25 oldMemD_26 oldMemD_27 oldMemD_28 oldMemD_29 oldMemD_30 oldMemD_31 oldMemD_32 oldMemD_33 oldMemD_34 oldMemD_35 oldMemD_36 oldMemD_37 vR7Old holdMemD_0_lt holdMemD_1_lt holdMemD_2_lt holdMemD_3_lt holdMemD_4_lt holdMemD_5_lt holdMemD_6_lt holdMemD_7_lt holdMemD_8_lt holdMemD_9_lt holdMemD_10_lt holdMemD_11_lt holdMemD_12_lt holdMemD_13_lt holdMemD_14_lt holdMemD_15_lt holdMemD_16_lt holdMemD_17_lt holdMemD_18_lt holdMemD_19_lt holdMemD_20_lt holdMemD_21_lt holdMemD_22_lt holdMemD_23_lt holdMemD_24_lt holdMemD_25_lt holdMemD_26_lt holdMemD_27_lt holdMemD_28_lt holdMemD_29_lt holdMemD_30_lt holdMemD_31_lt holdMemD_32_lt holdMemD_33_lt holdMemD_34_lt holdMemD_35_lt holdMemD_36_lt holdMemD_37_lt h_branch0 h_branch1 h_branch2 h_branch3 h_branch4 h_branch5 h_branch6 h_branch7 h_branch8 h_branch9 h_branch10 h_branch11 h_branch12 h_branch13 h_branch14 h_branch15 h_branch16 h_branch17 h_branch18 h_branch19 h_branch20 h_branch21 h_branch22 h_branch23 h_branch24 h_branch25 h_branch26 h_branch27 h_branch28 h_branch29 h_branch30 h_branch31 h_branch32 h_branch33 h_branch34 h_branch35
  rw [← wrapSub_of_le h_funds0 h_src_lt0, ← wrapAdd_of_lt h_noovf1]
  exact h

end Examples.Lifted.DclutchClaimsProofSbfLifted
