#![no_std]
#![forbid(unsafe_code)]
#![deny(missing_docs)]

//! Allocation-free interpreter for Lean-owned claim-representation data.
//!
//! The interpreter prepares one exact wrapper successor, one adapter intent,
//! and a borrowed iterator of EconomicKernel intents. It does not mutate or
//! duplicate Market supply, Hoard, native/materialized supply, token state, or
//! Registry authority. A physical adapter must apply every prepared component
//! atomically before persisting [`PreparedTransition::post_state`].

/// Stable refusal from hostile decoding or transition admission.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Error {
    /// A fixed or descriptor-derived wire width was not exact.
    InvalidLength,
    /// The requested wire type's magic bytes differed.
    InvalidMagic,
    /// The ABI version is unsupported.
    UnsupportedVersion,
    /// Reserved bytes or a boolean byte were noncanonical.
    NonCanonicalReserved,
    /// A required identity was all zero.
    ZeroIdentity,
    /// The descriptor had no outcomes or no positive claim weight.
    InvalidClaimVector,
    /// A receipt-lot scale was zero.
    ZeroReceiptUnits,
    /// The action tag was not generated by Lean.
    UnknownAction,
    /// The selected release set or normalized receipt was substituted.
    ReleaseMismatch,
    /// Registry/Claims release authentication was incomplete.
    UnauthenticatedRelease,
    /// Descriptor, state, or action identities did not join exactly.
    IdentityMismatch,
    /// Optimistic replay nonce or issued-lot coordinates were stale.
    ReplayMismatch,
    /// The wrapper capability was already retired.
    AlreadyRetired,
    /// The Economic-owner phase does not admit the generated action rule.
    InvalidPhase,
    /// A required lot count was zero or retirement carried nonzero lots.
    InvalidLots,
    /// A redemption exceeded issued lots or retirement was nonempty.
    InsufficientLots,
    /// Nonce advancement overflowed `u64`.
    NonceOverflow,
    /// Lot, claim, or receipt arithmetic overflowed `u64`.
    ArithmeticOverflow,
}

/// Result alias for this interpreter.
pub type Result<T> = core::result::Result<T, Error>;

/// Generated wrapper-state lot mutation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum LotEffect {
    /// Add issued lots.
    Add,
    /// Subtract redeemed lots.
    Subtract,
    /// Require zero lots and retire the wrapper child.
    Retire,
}

/// Generated EconomicKernel intent style.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EconomicStyle {
    /// Convert claimant-native claims into wrapper materialized claims.
    Materialize,
    /// Convert wrapper materialized claims back to claimant-native claims.
    Dematerialize,
    /// Dematerialize, then terminally redeem every nonzero basket claim.
    Terminal,
    /// Emit no Market-level economic transition.
    None,
}

/// Generated representation-adapter intent style.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AdapterStyle {
    /// Mint exact receipt units to the authenticated claimant.
    Mint,
    /// Burn exact receipt units from the authenticated claimant.
    Burn,
    /// Retire an empty representation adapter child.
    Retire,
}

/// One immutable Lean-generated action rule.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ActionRule {
    tag: u8,
    allowed_phases: u8,
    lot_effect: LotEffect,
    requires_positive_lots: bool,
    economic_style: EconomicStyle,
    adapter_style: AdapterStyle,
}

#[allow(missing_docs)]
mod generated {
    use super::{ActionRule, AdapterStyle, EconomicStyle, LotEffect};

    include!("generated.rs");
}

use generated::*;

/// Exact canonical representation action wire width.
pub const ACTION_WIRE_BYTES_V1: usize = ACTION_BYTES;

/// Economic lifecycle projected by the EconomicKernel owner.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EconomicPhase {
    /// Market liabilities may be issued, represented, or redeemed.
    Open,
    /// A winner exists and terminal claims may be redeemed.
    Terminal,
    /// Terminal redemption is underway.
    Retiring,
    /// Market-level economics are fully retired.
    Retired,
}

impl EconomicPhase {
    const fn mask(self) -> u8 {
        match self {
            Self::Open => PHASE_OPEN,
            Self::Terminal => PHASE_TERMINAL,
            Self::Retiring => PHASE_RETIRING,
            Self::Retired => PHASE_RETIRED,
        }
    }
}

/// Registry/Core-normalized admission for the selected Claims role.
///
/// The booleans are explicit physical-adapter assumptions. This crate does not
/// parse Loader V3, ProgramData, activation-cache, or Registry accounts.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ClaimsReleaseAdmission {
    /// Immutable release set selected by the Market/capability.
    pub selected_release_set_id: [u8; 32],
    /// Release-set identity in the current authenticated Registry receipt.
    pub receipt_release_set_id: [u8; 32],
    /// Whether the Registry/Core adapter authenticated its source and owner.
    pub registry_authenticated: bool,
    /// Whether the receipt is for the exact selected Claims-role binding.
    pub claims_role_authenticated: bool,
    /// Whether the activation cache was authenticated.
    pub activation_cache_authenticated: bool,
    /// Whether the current deployment was reauthenticated.
    pub current_deployment_reauthenticated: bool,
}

/// Borrowed immutable representation descriptor.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct DescriptorV1<'a> {
    descriptor_id: [u8; 32],
    market_id: [u8; 32],
    product_id: [u8; 32],
    result_domain_id: [u8; 32],
    adapter_asset_id: [u8; 32],
    release_set_id: [u8; 32],
    outcome_count: u32,
    receipt_units_per_lot: u64,
    claim_atoms: &'a [u8],
}

impl<'a> DescriptorV1<'a> {
    /// Hostile-decode one canonical variable-width descriptor.
    pub fn decode(input: &'a [u8]) -> Result<Self> {
        if input.len() < DESCRIPTOR_HEADER_BYTES {
            return Err(Error::InvalidLength);
        }
        exact_magic(input, DESCRIPTOR_MAGIC_OFFSET, &DESCRIPTOR_MAGIC)?;
        require_version(input, DESCRIPTOR_VERSION_OFFSET)?;
        require_zero(input, DESCRIPTOR_RESERVED_HEADER_OFFSET, 6)?;
        require_zero(input, DESCRIPTOR_RESERVED_BODY_OFFSET, 4)?;
        let descriptor_id = nonzero_array(input, DESCRIPTOR_ID_OFFSET)?;
        let market_id = nonzero_array(input, DESCRIPTOR_MARKET_ID_OFFSET)?;
        let product_id = nonzero_array(input, DESCRIPTOR_PRODUCT_ID_OFFSET)?;
        let result_domain_id = nonzero_array(input, DESCRIPTOR_RESULT_DOMAIN_ID_OFFSET)?;
        let adapter_asset_id = nonzero_array(input, DESCRIPTOR_ADAPTER_ASSET_ID_OFFSET)?;
        let release_set_id = nonzero_array(input, DESCRIPTOR_RELEASE_SET_ID_OFFSET)?;
        let outcome_count = u32_at(input, DESCRIPTOR_OUTCOME_COUNT_OFFSET)?;
        if outcome_count == 0 {
            return Err(Error::InvalidClaimVector);
        }
        let receipt_units_per_lot = u64_at(input, DESCRIPTOR_RECEIPT_UNITS_PER_LOT_OFFSET)?;
        if receipt_units_per_lot == 0 {
            return Err(Error::ZeroReceiptUnits);
        }
        let outcome_len = usize::try_from(outcome_count).map_err(|_| Error::InvalidLength)?;
        let tail_bytes = outcome_len
            .checked_mul(CLAIM_ATOM_BYTES)
            .ok_or(Error::InvalidLength)?;
        let expected = DESCRIPTOR_HEADER_BYTES
            .checked_add(tail_bytes)
            .ok_or(Error::InvalidLength)?;
        if input.len() != expected {
            return Err(Error::InvalidLength);
        }
        let claim_atoms = slice(input, DESCRIPTOR_HEADER_BYTES, tail_bytes)?;
        let mut any_positive = false;
        let mut index = 0_usize;
        while index < outcome_len {
            let offset = index
                .checked_mul(CLAIM_ATOM_BYTES)
                .ok_or(Error::InvalidLength)?;
            if u64_at(claim_atoms, offset)? != 0 {
                any_positive = true;
            }
            index = index.checked_add(1).ok_or(Error::InvalidLength)?;
        }
        if !any_positive {
            return Err(Error::InvalidClaimVector);
        }
        Ok(Self {
            descriptor_id,
            market_id,
            product_id,
            result_domain_id,
            adapter_asset_id,
            release_set_id,
            outcome_count,
            receipt_units_per_lot,
            claim_atoms,
        })
    }

    /// Encode into the one exact descriptor-width caller buffer.
    pub fn encode_into(self, output: &mut [u8]) -> Result<()> {
        let expected = DESCRIPTOR_HEADER_BYTES
            .checked_add(self.claim_atoms.len())
            .ok_or(Error::InvalidLength)?;
        if output.len() != expected {
            return Err(Error::InvalidLength);
        }
        output.fill(0);
        put(output, DESCRIPTOR_MAGIC_OFFSET, &DESCRIPTOR_MAGIC)?;
        put(
            output,
            DESCRIPTOR_VERSION_OFFSET,
            &ABI_VERSION.to_le_bytes(),
        )?;
        put(output, DESCRIPTOR_ID_OFFSET, &self.descriptor_id)?;
        put(output, DESCRIPTOR_MARKET_ID_OFFSET, &self.market_id)?;
        put(output, DESCRIPTOR_PRODUCT_ID_OFFSET, &self.product_id)?;
        put(
            output,
            DESCRIPTOR_RESULT_DOMAIN_ID_OFFSET,
            &self.result_domain_id,
        )?;
        put(
            output,
            DESCRIPTOR_ADAPTER_ASSET_ID_OFFSET,
            &self.adapter_asset_id,
        )?;
        put(
            output,
            DESCRIPTOR_RELEASE_SET_ID_OFFSET,
            &self.release_set_id,
        )?;
        put(
            output,
            DESCRIPTOR_OUTCOME_COUNT_OFFSET,
            &self.outcome_count.to_le_bytes(),
        )?;
        put(
            output,
            DESCRIPTOR_RECEIPT_UNITS_PER_LOT_OFFSET,
            &self.receipt_units_per_lot.to_le_bytes(),
        )?;
        put(output, DESCRIPTOR_HEADER_BYTES, self.claim_atoms)
    }

    /// Immutable descriptor identity.
    #[must_use]
    pub const fn descriptor_id(self) -> [u8; 32] {
        self.descriptor_id
    }

    /// Immutable Market identity.
    #[must_use]
    pub const fn market_id(self) -> [u8; 32] {
        self.market_id
    }

    /// Product identity owning the result coordinates.
    #[must_use]
    pub const fn product_id(self) -> [u8; 32] {
        self.product_id
    }

    /// Product-owned result-domain identity.
    #[must_use]
    pub const fn result_domain_id(self) -> [u8; 32] {
        self.result_domain_id
    }

    /// Representation adapter asset identity.
    #[must_use]
    pub const fn adapter_asset_id(self) -> [u8; 32] {
        self.adapter_asset_id
    }

    /// Immutable selected execution release-set identity.
    #[must_use]
    pub const fn release_set_id(self) -> [u8; 32] {
        self.release_set_id
    }

    /// Product-owned outcome width.
    #[must_use]
    pub const fn outcome_count(self) -> u32 {
        self.outcome_count
    }

    /// Exact adapter receipt units representing one descriptor lot.
    #[must_use]
    pub const fn receipt_units_per_lot(self) -> u64 {
        self.receipt_units_per_lot
    }

    /// Borrow the exact little-endian `u64[outcome_count]` atoms-per-lot tail.
    #[must_use]
    pub const fn claim_atoms_bytes(self) -> &'a [u8] {
        self.claim_atoms
    }

    /// Exact claim atoms for one outcome in one descriptor lot.
    pub fn claim_atoms_per_lot(self, outcome: u32) -> Result<u64> {
        if outcome >= self.outcome_count {
            return Err(Error::InvalidClaimVector);
        }
        let index = usize::try_from(outcome).map_err(|_| Error::InvalidClaimVector)?;
        let offset = index
            .checked_mul(CLAIM_ATOM_BYTES)
            .ok_or(Error::InvalidClaimVector)?;
        u64_at(self.claim_atoms, offset)
    }
}

/// Canonical fixed action request.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ActionV1 {
    /// Lean-generated action tag.
    pub tag: u8,
    /// Exact immutable descriptor identity.
    pub descriptor_id: [u8; 32],
    /// Immutable release set expected by the caller.
    pub expected_release_set_id: [u8; 32],
    /// Claimant receiving mints or authorizing burns.
    pub claimant: [u8; 32],
    /// Exact optimistic wrapper nonce.
    pub expected_next_nonce: u64,
    /// Exact optimistic issued-lot count.
    pub expected_issued_lots: u64,
    /// Exact lots to issue or redeem; retirement requires zero.
    pub lots: u64,
}

impl ActionV1 {
    /// Hostile-decode one exact action.
    pub fn decode(input: &[u8]) -> Result<Self> {
        exact_width(input, ACTION_BYTES)?;
        exact_magic(input, ACTION_MAGIC_OFFSET, &ACTION_MAGIC)?;
        require_version(input, ACTION_VERSION_OFFSET)?;
        require_zero(input, ACTION_RESERVED_OFFSET, 5)?;
        let value = Self {
            tag: byte_at(input, ACTION_TAG_OFFSET)?,
            descriptor_id: nonzero_array(input, ACTION_DESCRIPTOR_ID_OFFSET)?,
            expected_release_set_id: nonzero_array(input, ACTION_EXPECTED_RELEASE_SET_ID_OFFSET)?,
            claimant: nonzero_array(input, ACTION_CLAIMANT_OFFSET)?,
            expected_next_nonce: u64_at(input, ACTION_EXPECTED_NEXT_NONCE_OFFSET)?,
            expected_issued_lots: u64_at(input, ACTION_EXPECTED_ISSUED_LOTS_OFFSET)?,
            lots: u64_at(input, ACTION_LOTS_OFFSET)?,
        };
        rule(value.tag)?;
        Ok(value)
    }

    /// Encode into the exact generated action width.
    pub fn encode(self) -> Result<[u8; ACTION_BYTES]> {
        rule(self.tag)?;
        require_identity(&self.descriptor_id)?;
        require_identity(&self.expected_release_set_id)?;
        require_identity(&self.claimant)?;
        let mut output = [0_u8; ACTION_BYTES];
        put(&mut output, ACTION_MAGIC_OFFSET, &ACTION_MAGIC)?;
        put(
            &mut output,
            ACTION_VERSION_OFFSET,
            &ABI_VERSION.to_le_bytes(),
        )?;
        put_byte(&mut output, ACTION_TAG_OFFSET, self.tag)?;
        put(
            &mut output,
            ACTION_DESCRIPTOR_ID_OFFSET,
            &self.descriptor_id,
        )?;
        put(
            &mut output,
            ACTION_EXPECTED_RELEASE_SET_ID_OFFSET,
            &self.expected_release_set_id,
        )?;
        put(&mut output, ACTION_CLAIMANT_OFFSET, &self.claimant)?;
        put(
            &mut output,
            ACTION_EXPECTED_NEXT_NONCE_OFFSET,
            &self.expected_next_nonce.to_le_bytes(),
        )?;
        put(
            &mut output,
            ACTION_EXPECTED_ISSUED_LOTS_OFFSET,
            &self.expected_issued_lots.to_le_bytes(),
        )?;
        put(&mut output, ACTION_LOTS_OFFSET, &self.lots.to_le_bytes())?;
        Ok(output)
    }
}

/// Canonical fixed wrapper-child state.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct StateV1 {
    /// Immutable descriptor identity.
    pub descriptor_id: [u8; 32],
    /// Next exact replay nonce.
    pub next_nonce: u64,
    /// Exact issued descriptor lots.
    pub issued_lots: u64,
    /// Whether this wrapper child is retired.
    pub retired: bool,
}

impl StateV1 {
    /// Hostile-decode one exact state.
    pub fn decode(input: &[u8]) -> Result<Self> {
        exact_width(input, STATE_BYTES)?;
        exact_magic(input, STATE_MAGIC_OFFSET, &STATE_MAGIC)?;
        require_version(input, STATE_VERSION_OFFSET)?;
        require_zero(input, STATE_RESERVED_OFFSET, 5)?;
        let retired = match byte_at(input, STATE_RETIRED_OFFSET)? {
            0 => false,
            1 => true,
            _ => return Err(Error::NonCanonicalReserved),
        };
        Ok(Self {
            descriptor_id: nonzero_array(input, STATE_DESCRIPTOR_ID_OFFSET)?,
            next_nonce: u64_at(input, STATE_NEXT_NONCE_OFFSET)?,
            issued_lots: u64_at(input, STATE_ISSUED_LOTS_OFFSET)?,
            retired,
        })
    }

    /// Encode into the exact generated state width.
    pub fn encode(self) -> Result<[u8; STATE_BYTES]> {
        require_identity(&self.descriptor_id)?;
        let mut output = [0_u8; STATE_BYTES];
        put(&mut output, STATE_MAGIC_OFFSET, &STATE_MAGIC)?;
        put(
            &mut output,
            STATE_VERSION_OFFSET,
            &ABI_VERSION.to_le_bytes(),
        )?;
        put_byte(&mut output, STATE_RETIRED_OFFSET, u8::from(self.retired))?;
        put(&mut output, STATE_DESCRIPTOR_ID_OFFSET, &self.descriptor_id)?;
        put(
            &mut output,
            STATE_NEXT_NONCE_OFFSET,
            &self.next_nonce.to_le_bytes(),
        )?;
        put(
            &mut output,
            STATE_ISSUED_LOTS_OFFSET,
            &self.issued_lots.to_le_bytes(),
        )?;
        Ok(output)
    }
}

/// Exact adapter effect prepared for the physical representation boundary.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AdapterMutation {
    /// Mint exact receipt units to the authenticated claimant.
    Mint {
        /// Authenticated claimant/recipient identity.
        claimant: [u8; 32],
        /// Exact receipt units.
        receipt_units: u64,
    },
    /// Burn exact receipt units from the authenticated claimant.
    Burn {
        /// Authenticated claimant/owner identity.
        claimant: [u8; 32],
        /// Exact receipt units.
        receipt_units: u64,
    },
    /// Retire the empty adapter child without changing Market economics.
    Retire,
}

/// One exact first-order command for the separately owned EconomicKernel.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EconomicIntent {
    /// Convert native claimant claims into materialized wrapper claims.
    Materialize {
        /// Product-owned outcome selector.
        outcome: u32,
        /// Exact claim atoms.
        quantity: u64,
    },
    /// Convert materialized wrapper claims back into native claimant claims.
    Dematerialize {
        /// Product-owned outcome selector.
        outcome: u32,
        /// Exact claim atoms.
        quantity: u64,
    },
    /// Terminally redeem native claimant claims after dematerialization.
    RedeemTerminal {
        /// Product-owned outcome selector.
        outcome: u32,
        /// Exact claim atoms.
        quantity: u64,
    },
}

/// Allocation-free iterator over descriptor-specialized Economic intents.
#[derive(Clone, Copy, Debug)]
pub struct EconomicIntents<'a> {
    descriptor: DescriptorV1<'a>,
    style: EconomicStyle,
    lots: u64,
    stage: u8,
    outcome: u32,
}

impl Iterator for EconomicIntents<'_> {
    type Item = EconomicIntent;

    fn next(&mut self) -> Option<Self::Item> {
        loop {
            if self.style == EconomicStyle::None {
                return None;
            }
            if self.outcome >= self.descriptor.outcome_count {
                if self.style == EconomicStyle::Terminal && self.stage == 0 {
                    self.stage = 1;
                    self.outcome = 0;
                } else {
                    return None;
                }
            }
            let outcome = self.outcome;
            self.outcome = self.outcome.saturating_add(1);
            let atoms = self.descriptor.claim_atoms_per_lot(outcome).ok()?;
            let quantity = atoms.checked_mul(self.lots)?;
            if quantity == 0 {
                continue;
            }
            return Some(match (self.style, self.stage) {
                (EconomicStyle::Materialize, _) => {
                    EconomicIntent::Materialize { outcome, quantity }
                }
                (EconomicStyle::Dematerialize, _) | (EconomicStyle::Terminal, 0) => {
                    EconomicIntent::Dematerialize { outcome, quantity }
                }
                (EconomicStyle::Terminal, _) => {
                    EconomicIntent::RedeemTerminal { outcome, quantity }
                }
                (EconomicStyle::None, _) => return None,
            });
        }
    }
}

/// Successfully prepared but not yet physically applied transition.
#[derive(Clone, Copy, Debug)]
pub struct PreparedTransition<'a> {
    post_state: StateV1,
    adapter_mutation: AdapterMutation,
    economic_intents: EconomicIntents<'a>,
}

impl<'a> PreparedTransition<'a> {
    /// Exact candidate wrapper state. Persist only after all effects succeed.
    #[must_use]
    pub const fn post_state(self) -> StateV1 {
        self.post_state
    }

    /// Exact representation-adapter mutation.
    #[must_use]
    pub const fn adapter_mutation(self) -> AdapterMutation {
        self.adapter_mutation
    }

    /// Borrowed, allocation-free EconomicKernel intent iterator.
    #[must_use]
    pub const fn economic_intents(self) -> EconomicIntents<'a> {
        self.economic_intents
    }
}

/// Prepare one unified Bearer/Structured/Fractional representation transition.
///
/// Success is not physical execution. The caller must authenticate physical
/// accounts, execute every Economic and token effect atomically, and persist
/// the returned state only after all effects succeed.
pub fn prepare<'a>(
    descriptor: DescriptorV1<'a>,
    state: StateV1,
    action: ActionV1,
    phase: EconomicPhase,
    release: ClaimsReleaseAdmission,
) -> Result<PreparedTransition<'a>> {
    let rule = rule(action.tag)?;
    if descriptor.descriptor_id != state.descriptor_id
        || descriptor.descriptor_id != action.descriptor_id
    {
        return Err(Error::IdentityMismatch);
    }
    admit_release(descriptor, action, release)?;
    if state.next_nonce != action.expected_next_nonce
        || state.issued_lots != action.expected_issued_lots
    {
        return Err(Error::ReplayMismatch);
    }
    if state.retired {
        return Err(Error::AlreadyRetired);
    }
    if rule.allowed_phases & phase.mask() == 0 {
        return Err(Error::InvalidPhase);
    }
    if rule.requires_positive_lots {
        if action.lots == 0 {
            return Err(Error::InvalidLots);
        }
    } else if action.lots != 0 {
        return Err(Error::InvalidLots);
    }
    let next_nonce = state
        .next_nonce
        .checked_add(1)
        .ok_or(Error::NonceOverflow)?;
    let (issued_lots, retired) = match rule.lot_effect {
        LotEffect::Add => (
            state
                .issued_lots
                .checked_add(action.lots)
                .ok_or(Error::ArithmeticOverflow)?,
            false,
        ),
        LotEffect::Subtract => (
            state
                .issued_lots
                .checked_sub(action.lots)
                .ok_or(Error::InsufficientLots)?,
            false,
        ),
        LotEffect::Retire => {
            if state.issued_lots != 0 {
                return Err(Error::InsufficientLots);
            }
            (0, true)
        }
    };
    validate_products(descriptor, state.issued_lots)?;
    validate_products(descriptor, action.lots)?;
    validate_products(descriptor, issued_lots)?;
    let receipt_units = descriptor
        .receipt_units_per_lot
        .checked_mul(action.lots)
        .ok_or(Error::ArithmeticOverflow)?;
    let adapter_mutation = match rule.adapter_style {
        AdapterStyle::Mint => AdapterMutation::Mint {
            claimant: action.claimant,
            receipt_units,
        },
        AdapterStyle::Burn => AdapterMutation::Burn {
            claimant: action.claimant,
            receipt_units,
        },
        AdapterStyle::Retire => AdapterMutation::Retire,
    };
    Ok(PreparedTransition {
        post_state: StateV1 {
            descriptor_id: state.descriptor_id,
            next_nonce,
            issued_lots,
            retired,
        },
        adapter_mutation,
        economic_intents: EconomicIntents {
            descriptor,
            style: rule.economic_style,
            lots: action.lots,
            stage: 0,
            outcome: 0,
        },
    })
}

fn admit_release(
    descriptor: DescriptorV1<'_>,
    action: ActionV1,
    release: ClaimsReleaseAdmission,
) -> Result<()> {
    if descriptor.release_set_id != action.expected_release_set_id
        || descriptor.release_set_id != release.selected_release_set_id
        || descriptor.release_set_id != release.receipt_release_set_id
    {
        return Err(Error::ReleaseMismatch);
    }
    if !release.registry_authenticated
        || !release.claims_role_authenticated
        || !release.activation_cache_authenticated
        || !release.current_deployment_reauthenticated
    {
        return Err(Error::UnauthenticatedRelease);
    }
    Ok(())
}

fn validate_products(descriptor: DescriptorV1<'_>, lots: u64) -> Result<()> {
    descriptor
        .receipt_units_per_lot
        .checked_mul(lots)
        .ok_or(Error::ArithmeticOverflow)?;
    let mut outcome = 0_u32;
    while outcome < descriptor.outcome_count {
        descriptor
            .claim_atoms_per_lot(outcome)?
            .checked_mul(lots)
            .ok_or(Error::ArithmeticOverflow)?;
        outcome = outcome.checked_add(1).ok_or(Error::ArithmeticOverflow)?;
    }
    Ok(())
}

fn rule(tag: u8) -> Result<ActionRule> {
    generated_rule(tag).ok_or(Error::UnknownAction)
}

fn exact_width(input: &[u8], expected: usize) -> Result<()> {
    if input.len() == expected {
        Ok(())
    } else {
        Err(Error::InvalidLength)
    }
}

fn exact_magic(input: &[u8], offset: usize, expected: &[u8]) -> Result<()> {
    if slice(input, offset, expected.len())? == expected {
        Ok(())
    } else {
        Err(Error::InvalidMagic)
    }
}

fn require_version(input: &[u8], offset: usize) -> Result<()> {
    if u16_at(input, offset)? == ABI_VERSION {
        Ok(())
    } else {
        Err(Error::UnsupportedVersion)
    }
}

fn require_zero(input: &[u8], offset: usize, width: usize) -> Result<()> {
    if slice(input, offset, width)?.iter().all(|byte| *byte == 0) {
        Ok(())
    } else {
        Err(Error::NonCanonicalReserved)
    }
}

fn require_identity(identity: &[u8; 32]) -> Result<()> {
    if identity.iter().all(|byte| *byte == 0) {
        Err(Error::ZeroIdentity)
    } else {
        Ok(())
    }
}

fn nonzero_array(input: &[u8], offset: usize) -> Result<[u8; 32]> {
    let value = array_at(input, offset)?;
    require_identity(&value)?;
    Ok(value)
}

fn slice(input: &[u8], offset: usize, width: usize) -> Result<&[u8]> {
    let end = offset.checked_add(width).ok_or(Error::InvalidLength)?;
    input.get(offset..end).ok_or(Error::InvalidLength)
}

fn array_at(input: &[u8], offset: usize) -> Result<[u8; 32]> {
    slice(input, offset, 32)?
        .try_into()
        .map_err(|_| Error::InvalidLength)
}

fn byte_at(input: &[u8], offset: usize) -> Result<u8> {
    input.get(offset).copied().ok_or(Error::InvalidLength)
}

fn u16_at(input: &[u8], offset: usize) -> Result<u16> {
    let bytes: [u8; 2] = slice(input, offset, 2)?
        .try_into()
        .map_err(|_| Error::InvalidLength)?;
    Ok(u16::from_le_bytes(bytes))
}

fn u32_at(input: &[u8], offset: usize) -> Result<u32> {
    let bytes: [u8; 4] = slice(input, offset, 4)?
        .try_into()
        .map_err(|_| Error::InvalidLength)?;
    Ok(u32::from_le_bytes(bytes))
}

fn u64_at(input: &[u8], offset: usize) -> Result<u64> {
    let bytes: [u8; 8] = slice(input, offset, 8)?
        .try_into()
        .map_err(|_| Error::InvalidLength)?;
    Ok(u64::from_le_bytes(bytes))
}

fn put(output: &mut [u8], offset: usize, bytes: &[u8]) -> Result<()> {
    let end = offset
        .checked_add(bytes.len())
        .ok_or(Error::InvalidLength)?;
    let target = output.get_mut(offset..end).ok_or(Error::InvalidLength)?;
    target.copy_from_slice(bytes);
    Ok(())
}

fn put_byte(output: &mut [u8], offset: usize, byte: u8) -> Result<()> {
    let target = output.get_mut(offset).ok_or(Error::InvalidLength)?;
    *target = byte;
    Ok(())
}

#[cfg(test)]
mod tests {
    extern crate std;

    use super::*;
    use std::vec::Vec;

    fn release(descriptor: DescriptorV1<'_>) -> ClaimsReleaseAdmission {
        ClaimsReleaseAdmission {
            selected_release_set_id: descriptor.release_set_id(),
            receipt_release_set_id: descriptor.release_set_id(),
            registry_authenticated: true,
            claims_role_authenticated: true,
            activation_cache_authenticated: true,
            current_deployment_reauthenticated: true,
        }
    }

    fn decoded() -> (DescriptorV1<'static>, StateV1, ActionV1) {
        let descriptor = match DescriptorV1::decode(&EXAMPLE_DESCRIPTOR) {
            Ok(value) => value,
            Err(error) => unreachable!("generated descriptor refused: {error:?}"),
        };
        let state = match StateV1::decode(&EXAMPLE_EMPTY_STATE) {
            Ok(value) => value,
            Err(error) => unreachable!("generated state refused: {error:?}"),
        };
        let action = match ActionV1::decode(&EXAMPLE_ISSUE_ACTION) {
            Ok(value) => value,
            Err(error) => unreachable!("generated action refused: {error:?}"),
        };
        (descriptor, state, action)
    }

    #[test]
    fn lean_examples_round_trip_and_issue_exactly() {
        let (descriptor, state, action) = decoded();
        let mut encoded = [0_u8; EXAMPLE_DESCRIPTOR.len()];
        assert_eq!(descriptor.encode_into(&mut encoded), Ok(()));
        assert_eq!(encoded, EXAMPLE_DESCRIPTOR);
        assert_eq!(state.encode(), Ok(EXAMPLE_EMPTY_STATE));
        assert_eq!(action.encode(), Ok(EXAMPLE_ISSUE_ACTION));

        let prepared = match prepare(
            descriptor,
            state,
            action,
            EconomicPhase::Open,
            release(descriptor),
        ) {
            Ok(value) => value,
            Err(error) => unreachable!("canonical issue refused: {error:?}"),
        };
        assert_eq!(
            prepared.post_state(),
            StateV1 {
                descriptor_id: descriptor.descriptor_id(),
                next_nonce: 1,
                issued_lots: 3,
                retired: false,
            }
        );
        assert_eq!(
            prepared.adapter_mutation(),
            AdapterMutation::Mint {
                claimant: [7; 32],
                receipt_units: 30,
            }
        );
        assert_eq!(
            prepared.economic_intents().collect::<Vec<_>>(),
            std::vec![
                EconomicIntent::Materialize {
                    outcome: 0,
                    quantity: 3
                },
                EconomicIntent::Materialize {
                    outcome: 1,
                    quantity: 6
                },
                EconomicIntent::Materialize {
                    outcome: 2,
                    quantity: 3
                },
            ]
        );
    }

    #[test]
    fn bearer_structured_and_fractional_are_descriptor_data() {
        let (_, state, mut action) = decoded();

        let mut bearer_bytes = EXAMPLE_DESCRIPTOR;
        bearer_bytes
            [DESCRIPTOR_RECEIPT_UNITS_PER_LOT_OFFSET..DESCRIPTOR_RECEIPT_UNITS_PER_LOT_OFFSET + 8]
            .copy_from_slice(&1_u64.to_le_bytes());
        bearer_bytes[DESCRIPTOR_HEADER_BYTES..].fill(0);
        bearer_bytes[DESCRIPTOR_HEADER_BYTES + 8..DESCRIPTOR_HEADER_BYTES + 16]
            .copy_from_slice(&1_u64.to_le_bytes());
        let bearer = match DescriptorV1::decode(&bearer_bytes) {
            Ok(value) => value,
            Err(error) => unreachable!("bearer descriptor refused: {error:?}"),
        };
        action.lots = 4;
        let bearer_transition =
            match prepare(bearer, state, action, EconomicPhase::Open, release(bearer)) {
                Ok(value) => value,
                Err(error) => unreachable!("bearer issue refused: {error:?}"),
            };
        assert_eq!(
            bearer_transition.adapter_mutation(),
            AdapterMutation::Mint {
                claimant: [7; 32],
                receipt_units: 4,
            }
        );
        assert_eq!(
            bearer_transition.economic_intents().collect::<Vec<_>>(),
            std::vec![EconomicIntent::Materialize {
                outcome: 1,
                quantity: 4,
            }]
        );

        let mut structured_bytes = bearer_bytes;
        structured_bytes[DESCRIPTOR_HEADER_BYTES..].fill(0);
        structured_bytes[DESCRIPTOR_HEADER_BYTES..DESCRIPTOR_HEADER_BYTES + 8]
            .copy_from_slice(&2_u64.to_le_bytes());
        structured_bytes[DESCRIPTOR_HEADER_BYTES + 16..DESCRIPTOR_HEADER_BYTES + 24]
            .copy_from_slice(&3_u64.to_le_bytes());
        let structured = match DescriptorV1::decode(&structured_bytes) {
            Ok(value) => value,
            Err(error) => unreachable!("structured descriptor refused: {error:?}"),
        };
        action.lots = 2;
        let structured_transition = match prepare(
            structured,
            state,
            action,
            EconomicPhase::Open,
            release(structured),
        ) {
            Ok(value) => value,
            Err(error) => unreachable!("structured issue refused: {error:?}"),
        };
        assert_eq!(
            structured_transition.adapter_mutation(),
            AdapterMutation::Mint {
                claimant: [7; 32],
                receipt_units: 2,
            }
        );
        assert_eq!(
            structured_transition.economic_intents().collect::<Vec<_>>(),
            std::vec![
                EconomicIntent::Materialize {
                    outcome: 0,
                    quantity: 4,
                },
                EconomicIntent::Materialize {
                    outcome: 2,
                    quantity: 6,
                },
            ]
        );
    }

    #[test]
    fn redeem_terminal_and_retire_share_the_generated_interpreter() {
        let (descriptor, _, mut action) = decoded();
        let issued = StateV1 {
            descriptor_id: descriptor.descriptor_id(),
            next_nonce: 1,
            issued_lots: 3,
            retired: false,
        };
        action.tag = 2;
        action.expected_next_nonce = 1;
        action.expected_issued_lots = 3;
        action.lots = 2;
        let redeemed = match prepare(
            descriptor,
            issued,
            action,
            EconomicPhase::Open,
            release(descriptor),
        ) {
            Ok(value) => value,
            Err(error) => unreachable!("canonical redeem refused: {error:?}"),
        };
        assert_eq!(redeemed.post_state().issued_lots, 1);
        assert_eq!(
            redeemed.adapter_mutation(),
            AdapterMutation::Burn {
                claimant: [7; 32],
                receipt_units: 20,
            }
        );
        assert_eq!(redeemed.economic_intents().count(), 3);

        action.tag = 3;
        action.lots = 3;
        let terminal = match prepare(
            descriptor,
            issued,
            action,
            EconomicPhase::Retiring,
            release(descriptor),
        ) {
            Ok(value) => value,
            Err(error) => unreachable!("terminal redeem refused: {error:?}"),
        };
        let terminal_intents = terminal.economic_intents().collect::<Vec<_>>();
        assert_eq!(terminal_intents.len(), 6);
        assert_eq!(
            terminal_intents.get(3),
            Some(&EconomicIntent::RedeemTerminal {
                outcome: 0,
                quantity: 3,
            })
        );

        let empty = StateV1 {
            descriptor_id: descriptor.descriptor_id(),
            next_nonce: 2,
            issued_lots: 0,
            retired: false,
        };
        action.tag = 4;
        action.expected_next_nonce = 2;
        action.expected_issued_lots = 0;
        action.lots = 0;
        let retired = match prepare(
            descriptor,
            empty,
            action,
            EconomicPhase::Retiring,
            release(descriptor),
        ) {
            Ok(value) => value,
            Err(error) => unreachable!("empty retirement refused: {error:?}"),
        };
        assert!(retired.post_state().retired);
        assert_eq!(retired.adapter_mutation(), AdapterMutation::Retire);
        assert_eq!(retired.economic_intents().next(), None);
    }

    #[test]
    fn hostile_descriptor_action_and_state_decoding_refuses() {
        let mut descriptor = EXAMPLE_DESCRIPTOR;
        descriptor[0] = 0;
        assert_eq!(DescriptorV1::decode(&descriptor), Err(Error::InvalidMagic));
        descriptor = EXAMPLE_DESCRIPTOR;
        descriptor[DESCRIPTOR_VERSION_OFFSET] = 2;
        assert_eq!(
            DescriptorV1::decode(&descriptor),
            Err(Error::UnsupportedVersion)
        );
        descriptor = EXAMPLE_DESCRIPTOR;
        descriptor[DESCRIPTOR_RESERVED_HEADER_OFFSET] = 1;
        assert_eq!(
            DescriptorV1::decode(&descriptor),
            Err(Error::NonCanonicalReserved)
        );
        descriptor = EXAMPLE_DESCRIPTOR;
        descriptor[DESCRIPTOR_ID_OFFSET..DESCRIPTOR_ID_OFFSET + 32].fill(0);
        assert_eq!(DescriptorV1::decode(&descriptor), Err(Error::ZeroIdentity));
        descriptor = EXAMPLE_DESCRIPTOR;
        descriptor[DESCRIPTOR_OUTCOME_COUNT_OFFSET..DESCRIPTOR_OUTCOME_COUNT_OFFSET + 4].fill(0);
        assert_eq!(
            DescriptorV1::decode(&descriptor),
            Err(Error::InvalidClaimVector)
        );
        descriptor = EXAMPLE_DESCRIPTOR;
        descriptor
            [DESCRIPTOR_RECEIPT_UNITS_PER_LOT_OFFSET..DESCRIPTOR_RECEIPT_UNITS_PER_LOT_OFFSET + 8]
            .fill(0);
        assert_eq!(
            DescriptorV1::decode(&descriptor),
            Err(Error::ZeroReceiptUnits)
        );
        descriptor = EXAMPLE_DESCRIPTOR;
        descriptor[DESCRIPTOR_HEADER_BYTES..].fill(0);
        assert_eq!(
            DescriptorV1::decode(&descriptor),
            Err(Error::InvalidClaimVector)
        );
        let truncated = match EXAMPLE_DESCRIPTOR.split_last() {
            Some((_, prefix)) => prefix,
            None => return,
        };
        assert_eq!(DescriptorV1::decode(truncated), Err(Error::InvalidLength));

        let mut action = EXAMPLE_ISSUE_ACTION;
        action[ACTION_TAG_OFFSET] = 99;
        assert_eq!(ActionV1::decode(&action), Err(Error::UnknownAction));
        action = EXAMPLE_ISSUE_ACTION;
        action[ACTION_RESERVED_OFFSET] = 1;
        assert_eq!(ActionV1::decode(&action), Err(Error::NonCanonicalReserved));
        action = EXAMPLE_ISSUE_ACTION;
        action[ACTION_CLAIMANT_OFFSET..ACTION_CLAIMANT_OFFSET + 32].fill(0);
        assert_eq!(ActionV1::decode(&action), Err(Error::ZeroIdentity));

        let mut state = EXAMPLE_EMPTY_STATE;
        state[STATE_RETIRED_OFFSET] = 2;
        assert_eq!(StateV1::decode(&state), Err(Error::NonCanonicalReserved));
        state = EXAMPLE_EMPTY_STATE;
        state[STATE_RESERVED_OFFSET] = 1;
        assert_eq!(StateV1::decode(&state), Err(Error::NonCanonicalReserved));
    }

    #[test]
    fn replay_release_phase_and_overdraw_refuse() {
        let (descriptor, state, mut action) = decoded();
        action.expected_next_nonce = 1;
        assert_eq!(
            prepare(
                descriptor,
                state,
                action,
                EconomicPhase::Open,
                release(descriptor)
            )
            .map(|value| value.post_state()),
            Err(Error::ReplayMismatch)
        );
        action.expected_next_nonce = 0;
        let mut substituted = release(descriptor);
        substituted.receipt_release_set_id = [9; 32];
        assert_eq!(
            prepare(descriptor, state, action, EconomicPhase::Open, substituted)
                .map(|value| value.post_state()),
            Err(Error::ReleaseMismatch)
        );
        let mut unauthenticated = release(descriptor);
        unauthenticated.current_deployment_reauthenticated = false;
        assert_eq!(
            prepare(
                descriptor,
                state,
                action,
                EconomicPhase::Open,
                unauthenticated
            )
            .map(|value| value.post_state()),
            Err(Error::UnauthenticatedRelease)
        );
        assert_eq!(
            prepare(
                descriptor,
                state,
                action,
                EconomicPhase::Terminal,
                release(descriptor)
            )
            .map(|value| value.post_state()),
            Err(Error::InvalidPhase)
        );
        action.tag = 2;
        action.lots = 1;
        assert_eq!(
            prepare(
                descriptor,
                state,
                action,
                EconomicPhase::Open,
                release(descriptor)
            )
            .map(|value| value.post_state()),
            Err(Error::InsufficientLots)
        );
    }

    #[test]
    fn every_scalar_boundary_is_checked() {
        let (descriptor, state, mut action) = decoded();
        let max_nonce = StateV1 {
            next_nonce: u64::MAX,
            ..state
        };
        action.expected_next_nonce = u64::MAX;
        assert_eq!(
            prepare(
                descriptor,
                max_nonce,
                action,
                EconomicPhase::Open,
                release(descriptor)
            )
            .map(|value| value.post_state()),
            Err(Error::NonceOverflow)
        );

        let mut receipt_overflow_bytes = EXAMPLE_DESCRIPTOR;
        receipt_overflow_bytes
            [DESCRIPTOR_RECEIPT_UNITS_PER_LOT_OFFSET..DESCRIPTOR_RECEIPT_UNITS_PER_LOT_OFFSET + 8]
            .copy_from_slice(&u64::MAX.to_le_bytes());
        let receipt_overflow = match DescriptorV1::decode(&receipt_overflow_bytes) {
            Ok(value) => value,
            Err(error) => unreachable!("overflow descriptor refused structurally: {error:?}"),
        };
        action.expected_next_nonce = 0;
        action.lots = 2;
        assert_eq!(
            prepare(
                receipt_overflow,
                state,
                action,
                EconomicPhase::Open,
                release(receipt_overflow)
            )
            .map(|value| value.post_state()),
            Err(Error::ArithmeticOverflow)
        );

        let mut claim_overflow_bytes = EXAMPLE_DESCRIPTOR;
        claim_overflow_bytes[DESCRIPTOR_HEADER_BYTES..DESCRIPTOR_HEADER_BYTES + 8]
            .copy_from_slice(&u64::MAX.to_le_bytes());
        let claim_overflow = match DescriptorV1::decode(&claim_overflow_bytes) {
            Ok(value) => value,
            Err(error) => unreachable!("overflow descriptor refused structurally: {error:?}"),
        };
        assert_eq!(
            prepare(
                claim_overflow,
                state,
                action,
                EconomicPhase::Open,
                release(claim_overflow)
            )
            .map(|value| value.post_state()),
            Err(Error::ArithmeticOverflow)
        );
    }
}
