import DClutchSemantics.AbiSchema
import DClutchSemantics.Codec

/-!
# TypeScript backend for the Lean ABI emitters

The Rust emitters (`Emit*Rust.lean`) print a `pub const` module that a crate
checks in and byte-compares.  This module is the same discipline with a second
backend: it prints a TypeScript module the browser checks in and byte-compares.

The point is a single authority.  Before this backend existed the browser
learned protocol facts by scraping the *generated Rust* with regexes
(`apps/dclutch-web/scripts/generate-*.mjs`) — a mirror of a mirror — or by
restating magic strings, seed domains and offsets by hand.  A surface emitted
through here has exactly one owner: the Lean schema.

## How a new surface adopts this pattern

1. State the layout once as `AbiSchema` data in `DClutchSemantics/<Surface>.lean`
   (fields, widths, magics, seed domains) with the usual width/uniqueness/
   disjointness theorems.  Lean owns the meaning.
2. Add `Emit<Surface>Ts.lean` at the package root whose `main` prints the
   TypeScript module using the helpers below, and register it as a `lean_exe`
   in `lakefile.toml`.
3. Add `abi:<surface>` and `abi:<surface>:verify` scripts to
   `apps/dclutch-web/package.json` that call `node scripts/lean-emit.mjs
   DClutchSemantics.<Surface> Emit<Surface>Ts.lean lib/generated/<surface>.ts
   [--check]`.
4. Run the writer once, check the emitted module in, and delete whatever the
   browser was hand-stating.  `lib/abiCoverage.test.ts` fails CI if a magic,
   seed domain or offset reappears outside `lib/generated/`.

If the surface also has a Rust owner that hand-states the same numbers, emit a
`Emit<Surface>Rust.lean` too and point the crate's constants at it, so the
Rust and TypeScript views are the same Lean object rather than two readings of
it.
-/

namespace DClutch.TsEmit

open DClutch.AbiSchema

/-- Provenance header.  Every emitted module names the Lean file that owns it
and the npm script that reproduces it, so a stale checkout has a one-line fix
rather than a search. -/
def header (leanFile : String) (npmScript : String) : List String := [
  s!"// @generated by formal/dclutch-semantics/{leanFile}; do not edit.",
  s!"// Regenerate with: npm run {npmScript}",
  ""
]

/-- A width, count or offset. -/
def nat (name : String) (value : Nat) : String :=
  s!"export const {name} = {value} as const;"

/-- A literal ASCII record magic, as the browser compares it: a string. -/
def ascii (name : String) (value : String) : String :=
  s!"export const {name} = '{value}' as const;"

/-- Raw bytes as a `Uint8Array` literal. -/
def bytes (name : String) (value : List UInt8) : String :=
  let hex := value.map fun byte => s!"0x{Codec.byteHex byte}"
  s!"export const {name} = Uint8Array.from([{String.intercalate ", " hex}]);"

/-- A PDA seed domain.  The bytes are the UTF-8 encoding of the domain string;
emitting the string keeps the generated module readable while `TextEncoder`
reproduces exactly the bytes the program seeds with. -/
def domain (name : String) (value : String) : String :=
  s!"export const {name} = new TextEncoder().encode('{value}');"

/-- Every placed field of a schema as one offset constant, named by the
surface's own Rust/TypeScript naming function. -/
def offsets {Name : Type} (rename : Name → String)
    (layout : List (PlacedField Name)) : List String :=
  layout.map fun field => nat (rename field.spec.name) field.offset

/-- Print a module: the header, then the sections, blank-line separated. -/
def emit (leadIn : List String) (sections : List (List String)) : IO Unit := do
  for line in leadIn do
    IO.println line
  let mut first := true
  for group in sections do
    if !group.isEmpty then
      if !first then IO.println ""
      first := false
      for line in group do
        IO.println line

end DClutch.TsEmit
