#!/bin/sh
set -eu

crate_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_dir=$(CDPATH= cd -- "$crate_dir/../.." && pwd)
formal_dir="$repo_dir/formal/dclutch-semantics"
accepted="$crate_dir/src/generated_abi.rs"
work_dir=$(mktemp -d "${TMPDIR:-/tmp}/dclutch-structured-v2.XXXXXX")
temporary="$work_dir/generated_abi.rs"
trap 'rm -rf "$work_dir"' EXIT HUP INT TERM

(
  cd "$formal_dir"
  lake build DClutchSemantics.StructuredV2Abi
  lake env lean --run EmitStructuredV2AbiRust.lean > "$temporary"
)

expected_header='// @generated by formal/dclutch-semantics/EmitStructuredV2AbiRust.lean; do not edit.'
test "$(sed -n '1p' "$temporary")" = "$expected_header"
test "$(wc -l < "$temporary" | tr -d ' ')" -eq 95
rustfmt --edition 2024 "$temporary"
cmp "$temporary" "$accepted"
