//! Sole semantic owner of the provenance-pinned synthetic-local Pyth release.
//!
//! This module is absent unless the explicit `synthetic-local-fixture` feature
//! is enabled. Its row is not a Solana-cluster claim and cannot inhabit the
//! deliberately empty production catalog.

use crate::{
    PythReleaseV1Input, SyntheticLocalReleaseV1, SyntheticLocalReleaseV1Error,
    SyntheticLocalReleaseV1Input,
};

/// Domain-separated local label recorded by the fixture evidence manifest.
pub const SYNTHETIC_LOCAL_LABEL_V1: [u8; 32] = [
    0x40, 0x81, 0xd5, 0x5d, 0x40, 0x31, 0x31, 0x3f, 0xcf, 0x4b, 0x7c, 0x41, 0x31, 0x3d, 0x54, 0x7a,
    0x94, 0x41, 0xc8, 0xf9, 0xc0, 0x48, 0x74, 0x1a, 0x7a, 0x95, 0x1b, 0x3e, 0x03, 0x5e, 0x22, 0xd9,
];

/// Domain-separated label for Loader V3 accounts regenerated by the pinned
/// `solana-test-validator 4.0.2 --upgradeable-program` profile.
pub const LOCAL_VALIDATOR_LABEL_V1: [u8; 32] = [
    94, 101, 206, 251, 15, 89, 160, 219, 77, 108, 238, 201, 111, 77, 195, 246, 90, 56, 244, 221,
    95, 110, 127, 30, 120, 77, 122, 29, 37, 8, 176, 167,
];

/// Reconstruct the one checked synthetic-local release from pinned evidence.
pub fn synthetic_local_release_v1() -> Result<SyntheticLocalReleaseV1, SyntheticLocalReleaseV1Error>
{
    SyntheticLocalReleaseV1::new(SyntheticLocalReleaseV1Input {
        local_label: SYNTHETIC_LOCAL_LABEL_V1,
        release: PythReleaseV1Input {
            cluster_id: SYNTHETIC_LOCAL_LABEL_V1,
            receiver_program: [
                12, 183, 250, 122, 93, 166, 40, 251, 172, 169, 154, 234, 153, 247, 191, 59, 220,
                54, 137, 104, 96, 42, 191, 65, 77, 78, 139, 165, 103, 187, 176, 191,
            ],
            receiver_programdata: [
                36, 193, 217, 188, 83, 14, 128, 168, 96, 32, 44, 16, 172, 175, 215, 77, 119, 182,
                74, 169, 54, 67, 73, 241, 216, 23, 185, 252, 58, 36, 131, 42,
            ],
            receiver_config: [
                238, 89, 90, 195, 222, 6, 29, 79, 129, 224, 111, 41, 182, 154, 130, 148, 218, 115,
                206, 1, 195, 236, 196, 54, 206, 145, 180, 165, 98, 100, 91, 13,
            ],
            router_program: [
                241, 11, 10, 220, 120, 104, 244, 85, 102, 87, 169, 5, 247, 20, 69, 206, 236, 66, 7,
                172, 119, 215, 197, 194, 183, 98, 223, 19, 148, 102, 75, 135,
            ],
            router_programdata: [
                129, 50, 201, 239, 143, 229, 66, 230, 102, 107, 79, 207, 240, 58, 197, 139, 124,
                134, 144, 55, 34, 39, 166, 84, 85, 21, 198, 154, 109, 140, 219, 31,
            ],
            config_digest: [
                0x05, 0x03, 0x8c, 0xf7, 0x07, 0xaf, 0xce, 0xac, 0x3d, 0xf1, 0xaa, 0xe7, 0x35, 0xb0,
                0x96, 0x34, 0x4a, 0xd6, 0x39, 0x50, 0x6b, 0x00, 0xf1, 0xdb, 0x0a, 0xc1, 0xc0, 0x84,
                0xd6, 0xb6, 0x45, 0xaa,
            ],
            receiver_abi_id: [
                0xc5, 0x07, 0x95, 0x58, 0x64, 0xfc, 0x34, 0xdb, 0xd5, 0xfe, 0x87, 0xb4, 0xaa, 0x9f,
                0xba, 0x3a, 0x1e, 0xd2, 0x26, 0x90, 0x36, 0x3e, 0xc4, 0x90, 0x44, 0x9e, 0x86, 0x60,
                0xe7, 0x3a, 0xf6, 0x04,
            ],
            router_abi_id: [
                0xf9, 0x06, 0x1f, 0x03, 0xa8, 0x1b, 0x89, 0xdb, 0x29, 0xf4, 0x60, 0x36, 0x77, 0xe3,
                0xb3, 0xd8, 0x9b, 0x3b, 0xbf, 0x08, 0xd6, 0x78, 0x27, 0xb2, 0x83, 0x2f, 0x18, 0xa4,
                0xe2, 0xb6, 0x1a, 0xcb,
            ],
            price_update_codec_id: [
                0x12, 0xd0, 0xce, 0x8b, 0xc3, 0x90, 0x7a, 0xe2, 0x94, 0x90, 0x43, 0x39, 0x7e, 0xaf,
                0x3d, 0x5b, 0xd2, 0x5d, 0xee, 0xd9, 0x84, 0x50, 0xc6, 0x96, 0x9d, 0x95, 0x7b, 0xe4,
                0x02, 0xc8, 0x07, 0xae,
            ],
            adapter_id: [
                0x3f, 0xdf, 0xc9, 0x45, 0x89, 0xc6, 0x9b, 0x13, 0x38, 0x64, 0x46, 0x83, 0x20, 0x97,
                0x6f, 0x8e, 0x79, 0x0e, 0x7f, 0xe0, 0xf1, 0x45, 0x89, 0x7b, 0x6e, 0xab, 0xc2, 0x2b,
                0xd7, 0xc8, 0x71, 0x1b,
            ],
            receiver_deployment_slot: 460_336_311,
            router_deployment_slot: 460_336_290,
            guardian_set_count: 19,
            required_guardian_count: 10,
            upstream_commit: [
                0xf5, 0x0a, 0x3f, 0xaf, 0x9f, 0xc5, 0xa2, 0x23, 0xa2, 0x28, 0x89, 0x79, 0x9b, 0x2f,
                0x77, 0x89, 0x00, 0xf1, 0x86, 0xb3,
            ],
            sdk_crate_digest: [
                0x24, 0x5b, 0x1b, 0x03, 0xdd, 0x21, 0x77, 0x40, 0x20, 0x18, 0xb6, 0x07, 0x2f, 0xcb,
                0xb7, 0xbe, 0xa5, 0xb3, 0xd2, 0x80, 0x42, 0x7b, 0x19, 0x54, 0x79, 0x6b, 0xf1, 0xdc,
                0x18, 0x9b, 0xe4, 0x8b,
            ],
            activation_time: 0,
        },
    })
}

/// Reconstruct the non-production release observed when the pinned real
/// provider ELFs are loaded by `solana-test-validator 4.0.2`.
///
/// That loader profile regenerates both ProgramData headers with deployment
/// slot zero. Every provider, ABI, codec, configuration, quorum, and source
/// fact remains owned by the provenance-pinned captured release above.
pub fn local_validator_release_v1() -> Result<SyntheticLocalReleaseV1, SyntheticLocalReleaseV1Error>
{
    let captured = synthetic_local_release_v1()?;
    let release = captured.release();
    SyntheticLocalReleaseV1::new(SyntheticLocalReleaseV1Input {
        local_label: LOCAL_VALIDATOR_LABEL_V1,
        release: PythReleaseV1Input {
            cluster_id: LOCAL_VALIDATOR_LABEL_V1,
            receiver_program: release.receiver_program(),
            receiver_programdata: release.receiver_programdata(),
            receiver_config: release.receiver_config(),
            router_program: release.router_program(),
            router_programdata: release.router_programdata(),
            config_digest: release.config_digest(),
            receiver_abi_id: release.receiver_abi_id(),
            router_abi_id: release.router_abi_id(),
            price_update_codec_id: release.price_update_codec_id(),
            adapter_id: release.adapter_id(),
            receiver_deployment_slot: 0,
            router_deployment_slot: 0,
            guardian_set_count: release.guardian_set_count(),
            required_guardian_count: release.required_guardian_count(),
            upstream_commit: release.upstream_commit(),
            sdk_crate_digest: release.sdk_crate_digest(),
            activation_time: release.activation_time(),
        },
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pinned_row_is_a_valid_local_marker() {
        let local = synthetic_local_release_v1().expect("pinned synthetic release");
        assert_eq!(local.local_label(), SYNTHETIC_LOCAL_LABEL_V1);
        assert_eq!(local.release().cluster_id(), SYNTHETIC_LOCAL_LABEL_V1);
        assert_eq!(local.release().guardian_set_count(), 19);
        assert_eq!(local.release().required_guardian_count(), 10);
        assert_eq!(
            local.release().upstream_commit(),
            [
                0xf5, 0x0a, 0x3f, 0xaf, 0x9f, 0xc5, 0xa2, 0x23, 0xa2, 0x28, 0x89, 0x79, 0x9b, 0x2f,
                0x77, 0x89, 0x00, 0xf1, 0x86, 0xb3,
            ]
        );
    }

    #[test]
    fn validator_row_changes_only_local_identity_and_regenerated_slots() {
        let captured = synthetic_local_release_v1().expect("pinned captured release");
        let validator = local_validator_release_v1().expect("pinned validator release");
        assert_ne!(captured.local_label(), validator.local_label());
        assert_eq!(validator.local_label(), LOCAL_VALIDATOR_LABEL_V1);
        assert_eq!(validator.release().cluster_id(), LOCAL_VALIDATOR_LABEL_V1);
        assert_eq!(validator.release().receiver_deployment_slot(), 0);
        assert_eq!(validator.release().router_deployment_slot(), 0);

        let mut captured_bytes = captured.release().to_bytes();
        let mut validator_bytes = validator.release().to_bytes();
        captured_bytes[10..42].fill(0);
        validator_bytes[10..42].fill(0);
        captured_bytes[362..378].fill(0);
        validator_bytes[362..378].fill(0);
        assert_eq!(captured_bytes, validator_bytes);
    }
}
