#!/bin/sh
set -eu

# The projected-custody state's layout and tag ABI.
#
# This crate's other emission, `src/generated.rs`, is guarded from
# `programs/dclutch-custody-sbf/check-generated.sh`, which is where that guard
# has always lived. This one is here because the file it compares is here: the
# projected state is a kernel record with no program of its own, and a guard a
# crate cannot run from its own directory is a guard nobody runs.
#
# `ProjectedCustodyPhaseV1` was one of the four machines the route census gates
# on with no Lean owner at all. Its four discriminants were `projected.rs`'s,
# and twelve of its nineteen coordinates were bare arguments inside `encode`
# and `decode` -- including the phase byte itself, which the SDK generator had
# to recover by requiring an encode and a decode expression to agree.

crate_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repository_dir=$(CDPATH= cd -- "$crate_dir/../.." && pwd)
formal_dir="$repository_dir/formal/dclutch-semantics"

candidate=$(mktemp "${TMPDIR:-/tmp}/dclutch-generated.XXXXXX")
trap 'rm -f "$candidate"' EXIT HUP INT TERM

# Assert the provenance header and that the emitter produced a whole file
# rather than a truncated one, then normalize with the repository's pinned
# rustfmt and byte-compare. Formatting is normalized rather than asserted
# because the committed bytes are rustfmt output, not raw emitter output;
# `rustfmt` resolves through rust-toolchain.toml from inside the tree.
#
# Each emission is spelled out rather than folded into a loop, because the
# emission census matches `lake env lean --run <Emitter>` literally: an emitter
# reached through a shell variable is an emitter the census cannot see, and a
# guard the census cannot see guards nothing as far as the ratchet is concerned.
verify() {
  emitter=$1
  target=$2
  minimum_lines=$3
  test "$(sed -n '1p' "$candidate")" = "// @generated by formal/dclutch-semantics/$emitter; do not edit."
  test "$(wc -l <"$candidate" | tr -d ' ')" -ge "$minimum_lines"
  rustfmt --edition 2024 "$candidate"
  cmp "$candidate" "$crate_dir/src/$target"
}

# The pins are the width, the phase coordinate, all four tags, the bound the
# admission bitset indexes with, and the two canonical-zero spans. A tag that
# silently moved would let a client call a locked projection abortable, and a
# reserved span that moved would make every projection founded before it
# non-canonical, so they are pinned rather than only compared.
(
  cd "$formal_dir"
  lake build DClutchSemantics.ProjectedCustodyStateV2Abi >/dev/null
  lake env lean --run EmitProjectedCustodyStateV2Rust.lean >"$candidate"
)
grep -q '^pub const PROJECTED_CUSTODY_STATE_BYTES_V2: usize = 808;$' "$candidate"
grep -q '^pub const PROJECTED_CUSTODY_STATE_PHASE_OFFSET_V2: usize = 10;$' "$candidate"
grep -q '^pub const PROJECTED_CUSTODY_PHASE_INITIALIZED_V1: u8 = 1;$' "$candidate"
grep -q '^pub const PROJECTED_CUSTODY_PHASE_HOARD_OPEN_V1: u8 = 2;$' "$candidate"
grep -q '^pub const PROJECTED_CUSTODY_PHASE_HOARD_LOCKED_V1: u8 = 3;$' "$candidate"
grep -q '^pub const PROJECTED_CUSTODY_PHASE_SOURCE_FUNDED_V1: u8 = 4;$' "$candidate"
grep -q '^pub const PROJECTED_CUSTODY_PHASE_LIMIT_V1: u8 = 5;$' "$candidate"
grep -q '^pub const PROJECTED_CUSTODY_STATE_HEAD_RESERVED_OFFSET_V2: usize = 13;$' "$candidate"
grep -q '^pub const PROJECTED_CUSTODY_STATE_CAP_RESERVED_OFFSET_V2: usize = 24;$' "$candidate"
grep -q '^pub const PROJECTED_CUSTODY_STATE_IDENTITIES_OFFSET_V2: usize = 32;$' "$candidate"
verify EmitProjectedCustodyStateV2Rust.lean generated_projected_state_v2.rs 60
