/**
 * Run one Lean TypeScript emitter and write or byte-compare its output.
 *
 * This is the browser half of the house emission pattern. The Rust half is
 * `crates/<crate>/check-generated.sh`: run the Lean emitter, pin a few exact
 * literals so a silent width change cannot pass, and `cmp` against the file
 * checked into the tree. This does the same for `lib/generated/*.ts`.
 *
 * It deliberately does NOT scrape Rust. The older `generate-*.mjs` scripts read
 * generated Rust with regexes, which made the browser a mirror of a mirror: a
 * Lean edit reached the browser only if someone regenerated the Rust first, and
 * a hand-edited Rust constant reached the browser as though Lean had said it.
 * Here the Lean schema is the only authority, and both backends print from it.
 *
 * Usage:
 *   node scripts/lean-emit.mjs <DClutchSemantics.Module> <EmitFoo.lean> <lib/generated/foo.ts> [--check]
 *
 * The module is named rather than inferred so this builds exactly the schema
 * the emitter imports, the way `check-generated.sh` does on the Rust side.
 *
 * Requires `lake` (elan) on PATH, exactly as the Rust check scripts do.
 */
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const [leanModule, emitter, target, ...flags] = process.argv.slice(2);
if (!leanModule || !emitter || !target) {
  console.error('usage: node scripts/lean-emit.mjs <DClutchSemantics.Module> <EmitFoo.lean> <lib/generated/foo.ts> [--check]');
  process.exit(2);
}

const repositoryRoot = new URL('../../../', import.meta.url);
const formalDir = fileURLToPath(new URL('formal/dclutch-semantics/', repositoryRoot));
const outputUrl = new URL(`../${target}`, import.meta.url);
const check = flags.includes('--check');

function lake(args) {
  const result = spawnSync('lake', args, { cwd: formalDir, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  if (result.error) {
    console.error(`${emitter}: could not run lake (${result.error.message}); elan must be on PATH`);
    process.exit(1);
  }
  if (result.status !== 0) {
    console.error(result.stderr || result.stdout);
    console.error(`${emitter}: lake ${args.join(' ')} failed`);
    process.exit(1);
  }
  return result.stdout;
}

lake(['build', leanModule]);
const emitted = lake(['env', 'lean', '--run', emitter]);

const expectedHeader = `// @generated by formal/dclutch-semantics/${emitter}; do not edit.`;
if (!emitted.startsWith(`${expectedHeader}\n`)) {
  console.error(`${emitter}: emitted module does not open with its own provenance header`);
  process.exit(1);
}

if (check) {
  let current;
  try {
    current = readFileSync(outputUrl, 'utf8');
  } catch {
    console.error(`${target} is missing; run the writer script to create it`);
    process.exit(1);
  }
  if (current !== emitted) {
    console.error(`${target} differs from what ${emitter} emits; regenerate it`);
    process.exit(1);
  }
} else {
  writeFileSync(fileURLToPath(outputUrl), emitted);
}
