[package]
name = "dclutch-general-successor-operator"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
base64 = "=0.22.1"
bincode = "=1.3.3"
dclutch-market = { path = "../dclutch-market" }
dclutch-vm = { path = "../dclutch-vm" }
dclutch-trading = { path = "../dclutch-trading" }
dclutch-operator = { path = "../dclutch-operator" }
dclutch-versioned-message-operator = { path = "../dclutch-versioned-message-operator" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "=0.10.9"
solana-compute-budget-interface = "=3.1.0"
solana-sdk = "=3.0.0"

[lints]
workspace = true
